ERF: /home/runner/work/ERF/ERF/Source/RK3/RK3.H File Reference
RK3.H File Reference
#include <AMReX.H>
#include <AMReX_MultiFab.H>
#include <AMReX_ArrayLim.H>
#include <AMReX_InterpFaceRegister.H>
#include <ERF.H>
#include "IndexDefines.H"
Functions
void MomentumToVelocity (MultiFab &xvel_out, MultiFab &yvel_out, MultiFab &zvel_out, MultiFab &cons_in, MultiFab &xmom_in, MultiFab &ymom_in, MultiFab &zmom_in, int ngrow, const SolverChoice &solverChoice)
void VelocityToMomentum (MultiFab &xvel_in, MultiFab &yvel_in, MultiFab &zvel_in, MultiFab &cons_in, MultiFab &xmom_out, MultiFab &ymom_out, MultiFab &zmom_out, const SolverChoice &solverChoice)
void RK3_advance (int level, MultiFab &cons_old, MultiFab &cons_new, MultiFab &U_old, MultiFab &V_old, MultiFab &W_old, MultiFab &U_new, MultiFab &V_new, MultiFab &W_new, MultiFab &xmom_crse, MultiFab &ymom_crse, MultiFab &zmom_crse, MultiFab &source, std::array< MultiFab, AMREX_SPACEDIM > &faceflux, const amrex::Geometry crse_geom, const amrex::Geometry fine_geom, const amrex::IntVect ref_ratio, const amrex::Real *dxp, const amrex::Real dt, amrex::InterpFaceRegister *ifr, const SolverChoice &solverChoice)
void RK3_stage (int level, MultiFab &cons_old, MultiFab &cons_new, MultiFab &xmom_old, MultiFab &ymom_old, MultiFab &zmom_old, MultiFab &xmom_new, MultiFab &ymom_new, MultiFab &zmom_new, MultiFab &xvel, MultiFab &yvel, MultiFab &zvel, MultiFab &source, std::array< MultiFab, AMREX_SPACEDIM > &faceflux, const amrex::Geometry geom, const amrex::Real *dxp, const amrex::Real dt, amrex::InterpFaceRegister *ifr, const SolverChoice &solverChoice)
AMREX_GPU_DEVICE Real InterpolateFromCellOrFace (const int &i, const int &j, const int &k, const Array4< Real > &qty, const int &qty_index, const enum NextOrPrev &nextOrPrev, const enum Coord &coordDir, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolateDensityFromCellToFace (const int &i, const int &j, const int &k, const Array4< Real > &cons_in, const enum NextOrPrev &nextOrPrev, const enum Coord &coordDir, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolateRhoThetaFromCellToFace (const int &i, const int &j, const int &k, const Array4< Real > &cons_in, const enum NextOrPrev &nextOrPrev, const enum Coord &coordDir, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolateRhoScalarFromCellToFace (const int &i, const int &j, const int &k, const Array4< Real > &cons_in, const enum NextOrPrev &nextOrPrev, const enum Coord &coordDir, const int &spatial_order)
AMREX_GPU_DEVICE Real ComputeAdvectedQuantityForMom (const int &i, const int &j, const int &k, const Array4< Real > &rho_u, const Array4< Real > &rho_v, const Array4< Real > &rho_w, const Array4< Real > &u, const Array4< Real > &v, const Array4< Real > &w, const enum NextOrPrev &nextOrPrev, const enum AdvectedQuantity &advectedQuantity, const enum AdvectingQuantity &advectingQuantity, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionContributionForMom (const int &i, const int &j, const int &k, const Array4< Real > &rho_u, const Array4< Real > &rho_v, const Array4< Real > &rho_w, const Array4< Real > &u, const Array4< Real > &v, const Array4< Real > &w, const enum MomentumEqn &momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const SolverChoice &solverChoice)
AMREX_GPU_DEVICE Real ComputeAdvectedQuantityForState (const int &i, const int &j, const int &k, const Array4< Real > &rho_u, const Array4< Real > &rho_v, const Array4< Real > &rho_w, const Array4< Real > &cell_data, const enum NextOrPrev &nextOrPrev, const enum AdvectedQuantity &advectedQuantity, const enum AdvectingQuantity &advectingQuantity, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionContributionForState (const int &i, const int &j, const int &k, const Array4< Real > &rho_u, const Array4< Real > &rho_v, const Array4< Real > &rho_w, const Array4< Real > &cell_data, const int &qty_index, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real ComputeStrainRate (const int &i, const int &j, const int &k, const Array4< Real > &u, const Array4< Real > &v, const Array4< Real > &w, const enum NextOrPrev &nextOrPrev, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const GpuArray< Real, AMREX_SPACEDIM > &cellSize)
void ComputeTurbulentViscosity (MultiFab &xvel, MultiFab &yvel, MultiFab &zvel, MultiFab &cons_in, MultiFab &eddyViscosity, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const SolverChoice &solverChoice)
AMREX_GPU_DEVICE Real InterpolateTurbulentViscosity (const int &i, const int &j, const int &k, const Array4< Real > &u, const Array4< Real > &v, const Array4< Real > &w, const enum NextOrPrev &nextOrPrev, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &nut)
Compute K (i-1/2, j+1/2, k) etc given K(i, j, k) or nut (i, j, k) is known.
AMREX_GPU_DEVICE Real ComputeStressTerm (const int &i, const int &j, const int &k, const Array4< Real > &u, const Array4< Real > &v, const Array4< Real > &w, const enum NextOrPrev &nextOrPrev, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &nut, const SolverChoice &solverChoice)
AMREX_GPU_DEVICE Real DiffusionContributionForMom (const int &i, const int &j, const int &k, const Array4< Real > &u, const Array4< Real > &v, const Array4< Real > &w, const enum MomentumEqn &momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &nut, const SolverChoice &solverChoice)
AMREX_GPU_DEVICE Real ComputeDiffusionTermForState (const int &i, const int &j, const int &k, const Array4< Real > &cell_data, const int &qty_index, const enum Coord &coordDir)
AMREX_GPU_DEVICE Real DiffusionContributionForState (const int &i, const int &j, const int &k, const Array4< Real > &cell_data, const int &qty_index, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const SolverChoice &solverChoice)
int ComputeGhostCells (const int &spatial_order)
Function Documentation
MomentumToVelocity()
void MomentumToVelocity (MultiFab & xvel_out, MultiFab & yvel_out, MultiFab & zvel_out, MultiFab & cons_in, MultiFab & xmom_in, MultiFab & ymom_in, MultiFab & zmom_in, int ngrow, const SolverChoice & solverChoice)
 {
     BL_PROFILE_VAR("MomentumToVelocity()",MomentumToVelocity);
     // Loop over boxes
     for ( MFIter mfi(cons_in,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& tbx = amrex::grow(mfi.nodaltilebox(0),IntVect(0,ng,ng));
         const Box& tby = amrex::grow(mfi.nodaltilebox(1),IntVect(ng,0,ng));
         const Box& tbz = amrex::grow(mfi.nodaltilebox(2),IntVect(ng,ng,0));
         // Conserved variables on cell centers -- we use this for density
         const Array4<Real>& cons = cons_in.array(mfi);
         // Momentum on faces
         Array4<Real const> const& momx = xmom_in.array(mfi);
         Array4<Real const> const& momy = ymom_in.array(mfi);
         Array4<Real const> const& momz = zmom_in.array(mfi);
         // Velocity on faces
         const Array4<Real>& velx = xvel.array(mfi);
         const Array4<Real>& vely = yvel.array(mfi);
         const Array4<Real>& velz = zvel.array(mfi);
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             velx(i,j,k) = momx(i,j,k)/InterpolateDensityFromCellToFace(
                                         i, j, k, cons, NextOrPrev::prev, Coord::x,
                                         solverChoice.spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             vely(i,j,k) = momy(i,j,k)/InterpolateDensityFromCellToFace(
                                         i, j, k, cons, NextOrPrev::prev, Coord::y,
                                         solverChoice.spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             velz(i,j,k) = momz(i,j,k)/InterpolateDensityFromCellToFace(
                                         i, j, k, cons, NextOrPrev::prev, Coord::z,
                                         solverChoice.spatial_order);
         });
     } // end MFIter
 }
Referenced by MomentumToVelocity(), and RK3_advance().
VelocityToMomentum()
void VelocityToMomentum (MultiFab & xvel_in, MultiFab & yvel_in, MultiFab & zvel_in, MultiFab & cons_in, MultiFab & xmom_out, MultiFab & ymom_out, MultiFab & zmom_out, const SolverChoice & solverChoice)
 {
     BL_PROFILE_VAR("VelocityToMomentum()",VelocityToMomentum);
     // Loop over boxes
     for ( MFIter mfi(cons_in,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         // Conserved/state variables on cell centers -- we use this for density
         const Array4<Real>& cons = cons_in.array(mfi);
         // Momentum on faces, to be computed
         Array4<Real> const& momx = xmom.array(mfi);
         Array4<Real> const& momy = ymom.array(mfi);
         Array4<Real> const& momz = zmom.array(mfi);
         // Velocity on faces, used in computation
         const Array4<Real const>& velx = xvel_in.array(mfi);
         const Array4<Real const>& vely = yvel_in.array(mfi);
         const Array4<Real const>& velz = zvel_in.array(mfi);
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momx(i,j,k) = velx(i,j,k)* InterpolateDensityFromCellToFace(
                                 i, j, k, cons, NextOrPrev::prev, Coord::x,
                                 solverChoice.spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momy(i,j,k) = vely(i,j,k)* InterpolateDensityFromCellToFace(
                                 i, j, k, cons, NextOrPrev::prev, Coord::y,
                                 solverChoice.spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momz(i,j,k) = velz(i,j,k)* InterpolateDensityFromCellToFace(
                                 i, j, k, cons, NextOrPrev::prev, Coord::z,
                                 solverChoice.spatial_order);
         });
     } // end MFIter
 }
Referenced by RK3_advance().
RK3_advance()
void RK3_advance (int level, MultiFab & cons_old, MultiFab & cons_new, MultiFab & U_old, MultiFab & V_old, MultiFab & W_old, MultiFab & U_new, MultiFab & V_new, MultiFab & W_new, MultiFab & xmom_crse, MultiFab & ymom_crse, MultiFab & zmom_crse, MultiFab & source, std::array< MultiFab, AMREX_SPACEDIM > & faceflux, const amrex::Geometry crse_geom, const amrex::Geometry fine_geom, const amrex::IntVect ref_ratio, const amrex::Real * dxp, const amrex::Real dt, amrex::InterpFaceRegister * ifr, const SolverChoice & solverChoice)
 {
     BL_PROFILE_VAR("RK3stepStag()",RK3stepStag);
     int nvars = cons_old.nComp();
     // Determine the number of ghost cells depending on the spatial order
     // **************************************************************************************
     //TODO: Check if this is the only place to specify the number of ghost cells
     //TODO: Also explore how 'ngrow' should be related to the spatial_order
     int ngc = ComputeGhostCells(solverChoice.spatial_order);
     // Allocate temporary MultiFabs to hold the intermediate updates
     // **************************************************************************************
     const BoxArray& ba            = cons_old.boxArray();
     const DistributionMapping& dm = cons_old.DistributionMap();
     // Intermediate solutions (state) -- At cell centers
     MultiFab cons_upd_1(ba,dm,nvars,ngc);
     MultiFab cons_upd_2(ba,dm,nvars,ngc);
     cons_upd_1.setVal(0.0,Rho_comp,nvars,ngc);
     cons_upd_2.setVal(0.0,Rho_comp,nvars,ngc);
     // Intermediate momentum -- On faces
     MultiFab xmom_update_1(convert(ba,IntVect(1,0,0)), dm, 1, 1);
     MultiFab ymom_update_1(convert(ba,IntVect(0,1,0)), dm, 1, 1);
     MultiFab zmom_update_1(convert(ba,IntVect(0,0,1)), dm, 1, 1);
     MultiFab xmom_update_2(convert(ba,IntVect(1,0,0)), dm, 1, 1);
     MultiFab ymom_update_2(convert(ba,IntVect(0,1,0)), dm, 1, 1);
     MultiFab zmom_update_2(convert(ba,IntVect(0,0,1)), dm, 1, 1);
     // Initial momentum -- on faces
     MultiFab xmom_old(convert(ba,IntVect(1,0,0)), dm, 1, 1);
     MultiFab ymom_old(convert(ba,IntVect(0,1,0)), dm, 1, 1);
     MultiFab zmom_old(convert(ba,IntVect(0,0,1)), dm, 1, 1);
     // Final momentum -- on faces
     MultiFab xmom_new(convert(ba,IntVect(1,0,0)), dm, 1, 1);
     MultiFab ymom_new(convert(ba,IntVect(0,1,0)), dm, 1, 1);
     MultiFab zmom_new(convert(ba,IntVect(0,0,1)), dm, 1, 1);
     // **************************************************************************************
     // Prepare for calling the stages of the RK time integration
     // **************************************************************************************
     // Apply BC on old state data at cells before stage 1
     // **************************************************************************************
     cons_old.FillBoundary(fine_geom.periodicity());
     // **************************************************************************************
     // Convert old velocity available on faces to old momentum on faces to be used in time integration
     // **************************************************************************************
     VelocityToMomentum(xvel_old, yvel_old, zvel_old, cons_old, xmom_old, ymom_old, zmom_old, solverChoice);
     // **************************************************************************************
     // HACK HACK HACK -- We copy all of S_old into
     //     cons_upd_1 and cons_upd_2 just so that we can
     //     have values defined in the ghost cells.
     // TODO:  we need to fix this so that cons_upd_1 and cons_upd_2
     //        have interpolated values at the correct time -- not the old time
     // **************************************************************************************
     if (level > 0)
     {
         MultiFab::Copy(cons_upd_1,cons_old,0,0,nvars,ngc);
         MultiFab::Copy(cons_upd_2,cons_old,0,0,nvars,ngc);
         MultiFab::Copy(cons_new  ,cons_old,0,0,nvars,ngc);
     }
     // Apply BC on old momentum data on faces before stage 1
     // **************************************************************************************
     xmom_old.FillBoundary(fine_geom.periodicity());
     ymom_old.FillBoundary(fine_geom.periodicity());
     zmom_old.FillBoundary(fine_geom.periodicity());
     if (level > 0)
     {
         amrex::Array<const MultiFab*,3> cmf_const{&xmom_crse, &ymom_crse, &zmom_crse};
         amrex::Array<MultiFab*,3> fmf{&xmom_old , &ymom_old , &zmom_old};
         // Interpolate from coarse faces to fine faces *only* on the coarse-fine boundary
         ifr->interp(fmf,cmf_const,0,1);
         amrex::Array<MultiFab*,3> cmf{&xmom_crse, &ymom_crse, &zmom_crse};
         int nGrow = 1;
         BoxArray fine_grids(cons_old.boxArray());
         // Interpolate from coarse faces on fine faces outside the fine region
         create_umac_grown(level, nGrow, fine_grids, crse_geom, fine_geom, cmf, fmf, ref_ratio);
     }
     amrex::Vector<MultiFab*> vars_old{&cons_old, &xmom_old, &ymom_old, &zmom_old};
     ERF::applyBCs(fine_geom, vars_old);
     // **************************************************************************************
     // RK3 stage 1: Return update in the cons_upd_1 and [x,y,z]mom_update_1 MultiFabs
     // **************************************************************************************
     RK3_stage(level, cons_old, cons_upd_1,
               xmom_old, ymom_old, zmom_old,
               xmom_update_1, ymom_update_1, zmom_update_1,
               xvel_old, yvel_old, zvel_old,
               source,
               faceflux,
               fine_geom, dxp, dt,
               ifr,
               solverChoice);
     // **************************************************************************************
     // RK3 stage 1: Define updates in the first RK stage
     // **************************************************************************************
     for ( MFIter mfi(cons_old,TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const Box& bx = mfi.tilebox();
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         const Array4<Real> & cu_old     = cons_old.array(mfi);
         const Array4<Real> & cu_up1     = cons_upd_1.array(mfi);
         const Array4<Real>& momx_old = xmom_old.array(mfi);
         const Array4<Real>& momy_old = ymom_old.array(mfi);
         const Array4<Real>& momz_old = zmom_old.array(mfi);
         const Array4<Real>& momx_up1 = xmom_update_1.array(mfi);
         const Array4<Real>& momy_up1 = ymom_update_1.array(mfi);
         const Array4<Real>& momz_up1 = zmom_update_1.array(mfi);
         amrex::ParallelFor(bx, nvars, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             // At this point, the update is stored in cu_up1 ...
             cu_up1(i,j,k,n) += cu_old(i,j,k,n);
             // Now cu_up1 holds the first intermediate solution
         });
         // momentum flux
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momx_up1 ...
             momx_up1(i,j,k) += momx_old(i,j,k);
             // Now momx_up1 holds the first intermediate solution
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momy_up1 ...
             momy_up1(i,j,k) += momy_old(i,j,k);
             // Now momy_up1 holds the first intermediate solution
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momz_up1 ...
             momz_up1(i,j,k) += momz_old(i,j,k);
             // Now momz_up1 holds the first intermediate solution
         });
     }
     // Apply BC on updated momentum data on faces after stage 1 and before stage 2
     // **************************************************************************************
     xmom_update_1.FillBoundary(fine_geom.periodicity());
     ymom_update_1.FillBoundary(fine_geom.periodicity());
     zmom_update_1.FillBoundary(fine_geom.periodicity());
     // Apply BC on updated state data at cells after stage 1 and before stage 2
     // **************************************************************************************
     cons_upd_1.FillBoundary(fine_geom.periodicity());
     amrex::Vector<MultiFab*> vars1{&cons_upd_1, &xmom_update_1, &ymom_update_1, &zmom_update_1};
     ERF::applyBCs(fine_geom, vars1);
     if (level > 0)
     {
         amrex::Array<const MultiFab*,3> cmf_const{&xmom_crse, &ymom_crse, &zmom_crse};
         amrex::Array<MultiFab*,3> fmf{&xmom_update_1 , &ymom_update_1 , &zmom_update_1};
         // Interpolate from coarse faces to fine faces *only* on the coarse-fine boundary
         ifr->interp(fmf,cmf_const,0,1);
         amrex::Array<MultiFab*,3> cmf{&xmom_crse, &ymom_crse, &zmom_crse};
         int nGrow = 1;
         BoxArray fine_grids(cons_old.boxArray());
         // Interpolate from coarse faces on fine faces outside the fine region
         create_umac_grown(level, nGrow, fine_grids, crse_geom, fine_geom, cmf, fmf, ref_ratio);
     }
     // **************************************************************************************
     // Convert updated momentum to updated velocity on faces after stage 1 and before stage 2
     // Make sure we have filled the ghost cells of cons_upd_1 and *mom_update_1 before this call!
     // **************************************************************************************
     MomentumToVelocity(xvel_new, yvel_new, zvel_new, cons_upd_1, xmom_update_1, ymom_update_1, zmom_update_1, 1, solverChoice);
     // **************************************************************************************
     // RK3 stage 2: Return update in the cons_upd_2 and [x,y,z]mom_update_2 MultiFabs
     // **************************************************************************************
     // TODO: We won't need faceflux, edgeflux, and centflux when using the new code architecture
     RK3_stage(level, cons_upd_1, cons_upd_2,
               xmom_update_1, ymom_update_1, zmom_update_1,
               xmom_update_2, ymom_update_2, zmom_update_2,
               xvel_new, yvel_new, zvel_new,
               source,
               faceflux,
               fine_geom, dxp, dt,
               ifr,
               solverChoice);
     // **************************************************************************************
     // RK3 stage 2: Define updates in the second RK stage
     // **************************************************************************************
     for ( MFIter mfi(cons_old,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& bx = mfi.tilebox();
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         const Array4<Real> & cu_old     = cons_old.array(mfi);
         const Array4<Real> & cu_up1     = cons_upd_1.array(mfi);
         const Array4<Real> & cu_up2     = cons_upd_2.array(mfi);
         const Array4<Real>& momx_old = xmom_old.array(mfi);
         const Array4<Real>& momy_old = ymom_old.array(mfi);
         const Array4<Real>& momz_old = zmom_old.array(mfi);
         const Array4<Real>& momx_up1 = xmom_update_1.array(mfi);
         const Array4<Real>& momy_up1 = ymom_update_1.array(mfi);
         const Array4<Real>& momz_up1 = zmom_update_1.array(mfi);
         const Array4<Real>& momx_up2 = xmom_update_2.array(mfi);
         const Array4<Real>& momy_up2 = ymom_update_2.array(mfi);
         const Array4<Real>& momz_up2 = zmom_update_2.array(mfi);
         amrex::ParallelFor(bx, nvars, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             // At this point, the update is stored in cu_up2 ...
             cu_up2(i,j,k,n) = 0.75*cu_old(i,j,k,n) + 0.25*(cu_up1(i,j,k,n) + cu_up2(i,j,k,n));
             // Now cu_up2 holds the second intermediate solution
         });
         // momentum flux
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momx_up2 ...
             momx_up2(i,j,k) = 0.75*momx_old(i,j,k) + 0.25*(momx_up1(i,j,k) + momx_up2(i,j,k));
             // Now momx_up2 holds the second intermediate solution
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momy_up2 ...
             momy_up2(i,j,k) = 0.75*momy_old(i,j,k) + 0.25*(momy_up1(i,j,k) + momy_up2(i,j,k));
             // Now momy_up2 holds the second intermediate solution
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momz_up2 ...
             momz_up2(i,j,k) = 0.75*momz_old(i,j,k) + 0.25*(momz_up1(i,j,k) + momz_up2(i,j,k));
             // Now momz_up2 holds the second intermediate solution
         });
     }
     // TODO: Check if the order of applying BC on cell-centered state or face-centered mom makes any difference
     // Apply BC on updated momentum data on faces after stage 2 and before stage 3
     // **************************************************************************************
     xmom_update_2.FillBoundary(fine_geom.periodicity());
     ymom_update_2.FillBoundary(fine_geom.periodicity());
     zmom_update_2.FillBoundary(fine_geom.periodicity());
     // Apply BC on updated state data at cells after stage 2 and before stage 3
     // **************************************************************************************
     cons_upd_2.FillBoundary(fine_geom.periodicity());
     amrex::Vector<MultiFab*> vars2{&cons_upd_2, &xmom_update_2, &ymom_update_2, &zmom_update_2};
     ERF::applyBCs(fine_geom, vars2);
     if (level > 0)
     {
         amrex::Array<const MultiFab*,3> cmf_const{&xmom_crse, &ymom_crse, &zmom_crse};
         amrex::Array<MultiFab*,3> fmf{&xmom_update_2 , &ymom_update_2 , &zmom_update_2};
         // Interpolate from coarse faces to fine faces *only* on the coarse-fine boundary
         ifr->interp(fmf,cmf_const,0,1);
         amrex::Array<MultiFab*,3> cmf{&xmom_crse, &ymom_crse, &zmom_crse};
         int nGrow = 1;
         BoxArray fine_grids(cons_old.boxArray());
         // Interpolate from coarse faces on fine faces outside the fine region
         create_umac_grown(level, nGrow, fine_grids, crse_geom, fine_geom, cmf, fmf, ref_ratio);
     }
     // **************************************************************************************
     // Convert updated momentum to updated velocity on faces after stage 2 and before stage 3
     // Make sure we have filled the ghost cells of cons_upd_2 and *mom_update_2 before this call!
     // **************************************************************************************
     MomentumToVelocity(xvel_new, yvel_new, zvel_new, cons_upd_2, xmom_update_2, ymom_update_2, zmom_update_2, 1, solverChoice);
     // **************************************************************************************
     // RK3 stage 3: Return update in the cons_new and [x,y,z]mom_new MultiFabs
     // **************************************************************************************
     // TODO: We won't need faceflux, edgeflux, and centflux when using the new code architecture
     RK3_stage(level, cons_upd_2, cons_new,
               xmom_update_2, ymom_update_2, zmom_update_2,
               xmom_new, ymom_new, zmom_new,
               xvel_new, yvel_new, zvel_new,
               source,
               faceflux,
               fine_geom, dxp, dt,
               ifr,
               solverChoice);
     // **************************************************************************************
     // RK3 stage 3: Define updates in the third RK stage
     // **************************************************************************************
     for ( MFIter mfi(cons_old,TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const Box& bx = mfi.tilebox();
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         const Array4<Real> & cu_old = cons_old.array(mfi);
         const Array4<Real> & cu_up2 = cons_upd_2.array(mfi);
         const Array4<Real> & cu_new = cons_new.array(mfi);
         const Array4<Real>& momx_old = xmom_old.array(mfi);
         const Array4<Real>& momy_old = ymom_old.array(mfi);
         const Array4<Real>& momz_old = zmom_old.array(mfi);
         const Array4<Real>& momx_up2 = xmom_update_2.array(mfi);
         const Array4<Real>& momy_up2 = ymom_update_2.array(mfi);
         const Array4<Real>& momz_up2 = zmom_update_2.array(mfi);
         const Array4<Real>& momx_new = xmom_new.array(mfi);
         const Array4<Real>& momy_new = ymom_new.array(mfi);
         const Array4<Real>& momz_new = zmom_new.array(mfi);
         amrex::ParallelFor(bx, nvars, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             // At this point, the update is stored in cu_new ...
             cu_new(i,j,k,n) = (1./3.)*cu_old(i,j,k,n) + (2./3.)*(cu_up2(i,j,k,n) + cu_new(i,j,k,n));
             // Now cu_new holds the final solution
         });
         // momentum flux
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momx_new ...
             momx_new(i,j,k) = (1./3.)*momx_old(i,j,k) + (2./3.)*(momx_up2(i,j,k) + momx_new(i,j,k));
             // Now momx_new holds the final solution
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momy_new ...
             momy_new(i,j,k) = (1./3.)*momy_old(i,j,k) + (2./3.)*(momy_up2(i,j,k) + momy_new(i,j,k));
             // Now momy_new holds the final solution
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             // At this point, the update is stored in momz_new ...
             momz_new(i,j,k) = (1./3.)*momz_old(i,j,k) + (2./3.)*(momz_up2(i,j,k) + momz_new(i,j,k));
             // Now momz_new holds the final solution
         });
     }
     // TODO: Check if the order of applying BC on cell-centered state or face-centered mom makes any difference
     // TODO: Check if we need to apply BC on *mom_new, since we are using them in 'MomentumToVelocity'
     // PKJ comments: Even after applying BC on *mom_new, no noticeable difference in flow data was observed
     // Apply BC on updated momentum data on faces after stage 3 and before going to next time step
     // **************************************************************************************
     ///*
     xmom_new.FillBoundary(fine_geom.periodicity());
     ymom_new.FillBoundary(fine_geom.periodicity());
     zmom_new.FillBoundary(fine_geom.periodicity());
     //*/
     // Apply BC on updated state data at cells after stage 3 and before going to next time step
     // **************************************************************************************
     cons_new.FillBoundary(fine_geom.periodicity());
     amrex::Vector<MultiFab*> vars_new{&cons_new, &xmom_new, &ymom_new, &zmom_new};
     ERF::applyBCs(fine_geom, vars_new);
     // **************************************************************************************
     // Convert updated momentum to updated velocity on faces after stage 3 and before going to next time step
     // **************************************************************************************
     if (level == 1) print_state(xmom_new,IntVect(8,8,8));
     MomentumToVelocity(xvel_new, yvel_new, zvel_new, cons_new, xmom_new, ymom_new, zmom_new, 0, solverChoice);
     // One final application of non-periodic BCs after all RK3 stages have been called, this time on velocities
     xvel_new.FillBoundary(fine_geom.periodicity());
     yvel_new.FillBoundary(fine_geom.periodicity());
     zvel_new.FillBoundary(fine_geom.periodicity());
     amrex::Vector<MultiFab*> vars{&cons_new, &xvel_new, &yvel_new, &zvel_new};
     ERF::applyBCs(fine_geom, vars);
 }
RK3_stage()
void RK3_stage (int level, MultiFab & cons_old, MultiFab & cons_new, MultiFab & xmom_old, MultiFab & ymom_old, MultiFab & zmom_old, MultiFab & xmom_new, MultiFab & ymom_new, MultiFab & zmom_new, MultiFab & xvel, MultiFab & yvel, MultiFab & zvel, MultiFab & source, std::array< MultiFab, AMREX_SPACEDIM > & faceflux, const amrex::Geometry geom, const amrex::Real * dxp, const amrex::Real dt, amrex::InterpFaceRegister * ifr, const SolverChoice & solverChoice)
 {
     BL_PROFILE_VAR("RK3_stage()",RK3_stage);
     const GpuArray<Real, AMREX_SPACEDIM> dx = geom.CellSizeArray();
     // *************************************************************************
     // Fill the ghost cells/faces of the MultiFabs we will need
     // *************************************************************************
     cons_old.FillBoundary(geom.periodicity());
     xmom_old.FillBoundary(geom.periodicity());
     ymom_old.FillBoundary(geom.periodicity());
     zmom_old.FillBoundary(geom.periodicity());
     xvel.FillBoundary(geom.periodicity());
     yvel.FillBoundary(geom.periodicity());
     zvel.FillBoundary(geom.periodicity());
     // Apply BC on state data at cells
     // Apply BC on velocity data on faces
     // Note that in RK3_advance, the BC was applied on momentum
     amrex::Vector<MultiFab*> vars{&cons_old, &xmom_old, &ymom_old, &zmom_old, &xvel, &yvel, &zvel};
     ERF::applyBCs(geom, vars);
     // *************************************************************************
     // Deal with gravity
     Real gravity = solverChoice.use_gravity? CONST_GRAV: 0.0;
     // CONST_GRAV is a positive constant, but application of grav_gpu to the vertical momentum
     // tendency assumes this quantity is negative.
     //    const    Array<Real,AMREX_SPACEDIM> grav{0.0, 0.0, gravity};
     const    Array<Real,AMREX_SPACEDIM> grav{0.0, 0.0, -gravity};
     const GpuArray<Real,AMREX_SPACEDIM> grav_gpu{grav[0], grav[1], grav[2]};
     // *************************************************************************
     // Calculate cell-centered eddy viscosity
     //
     // Notes:
     // 1. Need to apply BC on velocity field so that ComputeStrainRate works
     //    properly
     // 2. Need to call FillBoundary and applyBCs to set ghost values on all
     //    boundaries so that InterpolateTurbulentViscosity works properly
     // *************************************************************************
     MultiFab eddyViscosity(cons_old.boxArray(),cons_old.DistributionMap(),1,1);
     if (solverChoice.use_smagorinsky)
     {
         ComputeTurbulentViscosity(xvel, yvel, zvel, cons_old, eddyViscosity, dx, solverChoice);
         eddyViscosity.FillBoundary(geom.periodicity());
     }
     amrex::Vector<MultiFab*> eddyvisc_update{&eddyViscosity};
     ERF::applyBCs(geom, eddyvisc_update);
     const iMultiFab *mlo_mf_x, *mhi_mf_x;
     const iMultiFab *mlo_mf_y, *mhi_mf_y;
     const iMultiFab *mlo_mf_z, *mhi_mf_z;
     if (level > 0)
     {
         mlo_mf_x = &(ifr->mask(Orientation(0,Orientation::low)));
         mhi_mf_x = &(ifr->mask(Orientation(0,Orientation::high)));
         mlo_mf_y = &(ifr->mask(Orientation(1,Orientation::low)));
         mhi_mf_y = &(ifr->mask(Orientation(1,Orientation::high)));
         mlo_mf_z = &(ifr->mask(Orientation(2,Orientation::low)));
         mhi_mf_z = &(ifr->mask(Orientation(2,Orientation::high)));
     }
     // *************************************************************************
     // Define updates in the current RK stage, fluxes are computed here itself
     //TODO: Benchmarking of performance. We are computing the fluxes on the fly.
     //If the performance slows, consider saving all the fluxes apriori and accessing them here.
     // *************************************************************************
     for ( MFIter mfi(cons_old,TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const Box& bx = mfi.tilebox();
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         Box const& valid_bx = mfi.validbox();
         int vlo_x = valid_bx.smallEnd(0);
         int vhi_x = valid_bx.bigEnd(0);
         int vlo_y = valid_bx.smallEnd(1);
         int vhi_y = valid_bx.bigEnd(1);
         int vlo_z = valid_bx.smallEnd(2);
         int vhi_z = valid_bx.bigEnd(2);
         auto mlo_x = (level > 0) ? mlo_mf_x->const_array(mfi) : Array4<const int>{};
         auto mhi_x = (level > 0) ? mhi_mf_x->const_array(mfi) : Array4<const int>{};
         auto mlo_y = (level > 0) ? mlo_mf_y->const_array(mfi) : Array4<const int>{};
         auto mhi_y = (level > 0) ? mhi_mf_y->const_array(mfi) : Array4<const int>{};
         auto mlo_z = (level > 0) ? mlo_mf_z->const_array(mfi) : Array4<const int>{};
         auto mhi_z = (level > 0) ? mhi_mf_z->const_array(mfi) : Array4<const int>{};
         const Array4<Real> & cell_data_old     = cons_old.array(mfi);
         const Array4<Real> & cell_data_upd     = cons_upd.array(mfi);
         const Array4<Real> & source_fab = source.array(mfi);
         const Array4<Real> & u = xvel.array(mfi);
         const Array4<Real> & v = yvel.array(mfi);
         const Array4<Real> & w = zvel.array(mfi);
         const Array4<Real>& rho_u = xmom_old.array(mfi);
         const Array4<Real>& rho_v = ymom_old.array(mfi);
         const Array4<Real>& rho_w = zmom_old.array(mfi);
         const Array4<Real>& rho_u_upd = xmom_upd.array(mfi);
         const Array4<Real>& rho_v_upd = ymom_upd.array(mfi);
         const Array4<Real>& rho_w_upd = zmom_upd.array(mfi);
         const Array4<Real>& nut = eddyViscosity.array(mfi);
         // **************************************************************************
         // Define updates in the RHS of continuity, temperature, and scalar equations
         // **************************************************************************
         amrex::ParallelFor(bx, cons_old.nComp(),
        [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept {
             cell_data_upd(i, j, k, n) = 0.0; // Initialize the updated state eqn term to zero.
             // Add advection terms.
             if (solverChoice.use_state_advection)
                 cell_data_upd(i, j, k, n) += (-dt) * AdvectionContributionForState(i, j, k, rho_u, rho_v, rho_w, cell_data_old, n, dx, solverChoice.spatial_order);
             // Add diffusive terms.
             if (solverChoice.use_thermal_diffusion && n == RhoTheta_comp)
                 cell_data_upd(i, j, k, n) += dt * DiffusionContributionForState(i, j, k,cell_data_old, RhoTheta_comp, dx, solverChoice);
             if (solverChoice.use_scalar_diffusion && n == RhoScalar_comp)
                 cell_data_upd(i, j, k, n) += dt * DiffusionContributionForState(i, j, k,cell_data_old, RhoScalar_comp, dx, solverChoice);
             // Add source terms. TODO: Put this under a if condition when we implement source term
             cell_data_upd(i, j, k, n) += dt * source_fab(i, j, k, n);
         }
         );
         // *********************************************************************
         // Define updates in the RHS of {x, y, z}-momentum equations
         // *********************************************************************
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // x-momentum equation
             rho_u_upd(i, j, k) = 0.0; // Initialize the updated x-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (i == vlo_x && mlo_x(i,j,k)) || (i == vhi_x+1 && mhi_x(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
             // Add advective terms
             if (solverChoice.use_momentum_advection)
                 rho_u_upd(i, j, k) += (-dt) *
                   AdvectionContributionForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, MomentumEqn::x, dx, solverChoice);
             // Add diffusive terms
             if (solverChoice.use_momentum_diffusion)
                 rho_u_upd(i, j, k) += dt *
                   DiffusionContributionForMom(i, j, k, u, v, w, MomentumEqn::x, dx, nut, solverChoice);
             // Add pressure gradient
             if (solverChoice.use_pressure)
                 rho_u_upd(i, j, k) += (-dt / dx[0]) *
                   (getPgivenRTh(cell_data_old(i, j, k, RhoTheta_comp)) - getPgivenRTh(cell_data_old(i - 1, j, k, RhoTheta_comp)));
             // Add gravity term
             if (solverChoice.use_gravity)
                 rho_u_upd(i, j, k) += dt * grav_gpu[0] *
                   InterpolateDensityFromCellToFace(i, j, k, cell_data_old, NextOrPrev::prev, Coord::x, solverChoice.spatial_order);
             // Add driving pressure gradient
             if (solverChoice.abl_driver_type == ABLDriverType::PressureGradient)
                 rho_u_upd(i, j, k) += (-dt) * solverChoice.abl_pressure_grad[0];
             // Add Coriolis forcing (that assumes east is +x, north is +y)
             if (solverChoice.use_coriolis)
             {
                 Real rho_v_loc = 0.25 * (rho_u(i,j+1,k) + rho_u(i,j,k) + rho_u(i-1,j+1,k) + rho_u(i-1,j,k));
                 Real rho_w_loc = 0.25 * (rho_w(i,j,k+1) + rho_w(i,j,k) + rho_w(i,j-1,k+1) + rho_w(i,j-1,k));
                 rho_u_upd(i, j, k) += dt * solverChoice.coriolis_factor *
                         (rho_v_loc * solverChoice.sinphi - rho_w_loc * solverChoice.cosphi);
             }
             // Add geostrophic forcing
             if (solverChoice.abl_driver_type == ABLDriverType::GeostrophicWind)
                 rho_u_upd(i, j, k) += dt * solverChoice.abl_geo_forcing[0];
             } // not on coarse-fine boundary
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // y-momentum equation
             rho_v_upd(i, j, k) = 0.0; // Initialize the updated y-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (j == vlo_y && mlo_y(i,j,k)) || (j == vhi_y+1 && mhi_y(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
             // Add advective terms
             if (solverChoice.use_momentum_advection)
                 rho_v_upd(i, j, k) += (-dt) * AdvectionContributionForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, MomentumEqn::y, dx, solverChoice);
             // Add diffusive terms
             if (solverChoice.use_momentum_diffusion)
                 rho_v_upd(i, j, k) += dt *
                   DiffusionContributionForMom(i, j, k, u, v, w, MomentumEqn::y, dx, nut, solverChoice);
             // Add pressure gradient
             if (solverChoice.use_pressure)
                 rho_v_upd(i, j, k) += (-dt / dx[1]) *
                   (getPgivenRTh(cell_data_old(i, j, k, RhoTheta_comp)) - getPgivenRTh(cell_data_old(i, j - 1, k, RhoTheta_comp)));
             // Add gravity term
             if (solverChoice.use_gravity)
                rho_v_upd(i, j, k) += dt * grav_gpu[1] *
                   InterpolateDensityFromCellToFace(i, j, k, cell_data_old, NextOrPrev::prev, Coord::y, solverChoice.spatial_order);
             // Add driving pressure gradient
             if (solverChoice.abl_driver_type == ABLDriverType::PressureGradient)
                 rho_v_upd(i, j, k) += (-dt) * solverChoice.abl_pressure_grad[1];
             // Add Coriolis forcing (that assumes east is +x, north is +y)
             if (solverChoice.use_coriolis)
             {
                 Real rho_u_loc = 0.25 * (rho_u(i+1,j,k) + rho_u(i,j,k) + rho_u(i+1,j-1,k) + rho_u(i,j-1,k));
                 rho_v_upd(i, j, k) += (-dt) * solverChoice.coriolis_factor * rho_u_loc * solverChoice.sinphi;
             }
             // Add geostrophic forcing
             if (solverChoice.abl_driver_type == ABLDriverType::GeostrophicWind)
                 rho_v_upd(i, j, k) += dt * solverChoice.abl_geo_forcing[1];
             } // not on coarse-fine boundary
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // z-momentum equation
             rho_w_upd(i, j, k) = 0.0; // Initialize the updated z-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (k == vlo_z && mlo_z(i,j,k)) || (k == vhi_z+1 && mhi_z(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
             // Add advective terms
             if (solverChoice.use_momentum_advection)
                 rho_w_upd(i, j, k) += (-dt) *
                     AdvectionContributionForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, MomentumEqn::z, dx, solverChoice);
             // Add diffusive terms
             if (solverChoice.use_momentum_diffusion)
                 rho_w_upd(i, j, k) += dt *
                     DiffusionContributionForMom(i, j, k, u, v, w, MomentumEqn::z, dx, nut, solverChoice);
             // Add pressure gradient
             if (solverChoice.use_pressure)
                 rho_w_upd(i, j, k) += (-dt / dx[2]) *
                     (getPgivenRTh(cell_data_old(i, j, k, RhoTheta_comp)) - getPgivenRTh(cell_data_old(i, j, k - 1, RhoTheta_comp)));
             // Add gravity term
             if (solverChoice.use_gravity)
                rho_w_upd(i, j, k) += dt * grav_gpu[2] *
                    InterpolateDensityFromCellToFace(i, j, k, cell_data_old, NextOrPrev::prev, Coord::z, solverChoice.spatial_order);
             // Add driving pressure gradient
             if (solverChoice.abl_driver_type == ABLDriverType::PressureGradient)
                 rho_w_upd(i, j, k) += (-dt) * solverChoice.abl_pressure_grad[2];
             // Add Coriolis forcing (that assumes east is +x, north is +y)
             if (solverChoice.use_coriolis)
             {
                 Real rho_u_loc = 0.25 * (rho_u(i+1,j,k) + rho_u(i,j,k) + rho_u(i+1,j,k-1) + rho_u(i,j,k-1));
                 rho_w_upd(i, j, k) += dt * solverChoice.coriolis_factor * rho_u_loc * solverChoice.cosphi;
             }
             } // not on coarse-fine boundary
         });
     }
 }
Referenced by RK3_advance().
InterpolateFromCellOrFace()
AMREX_GPU_DEVICE Real InterpolateFromCellOrFace (const int & i, const int & j, const int & k, const Array4< Real > & qty, const int & qty_index, const enum NextOrPrev & nextOrPrev, const enum Coord & coordDir, const int & spatial_order)
InterpolateDensityFromCellToFace()
AMREX_GPU_DEVICE Real InterpolateDensityFromCellToFace (const int & i, const int & j, const int & k, const Array4< Real > & cons_in, const enum NextOrPrev & nextOrPrev, const enum Coord & coordDir, const int & spatial_order)
InterpolateRhoThetaFromCellToFace()
AMREX_GPU_DEVICE Real InterpolateRhoThetaFromCellToFace (const int & i, const int & j, const int & k, const Array4< Real > & cons_in, const enum NextOrPrev & nextOrPrev, const enum Coord & coordDir, const int & spatial_order)
InterpolateRhoScalarFromCellToFace()
AMREX_GPU_DEVICE Real InterpolateRhoScalarFromCellToFace (const int & i, const int & j, const int & k, const Array4< Real > & cons_in, const enum NextOrPrev & nextOrPrev, const enum Coord & coordDir, const int & spatial_order)
ComputeAdvectedQuantityForMom()
AMREX_GPU_DEVICE Real ComputeAdvectedQuantityForMom (const int & i, const int & j, const int & k, const Array4< Real > & rho_u, const Array4< Real > & rho_v, const Array4< Real > & rho_w, const Array4< Real > & u, const Array4< Real > & v, const Array4< Real > & w, const enum NextOrPrev & nextOrPrev, const enum AdvectedQuantity & advectedQuantity, const enum AdvectingQuantity & advectingQuantity, const int & spatial_order)
{
   Real advectingQty = 0.0;
   Real advectedQty = 1.0;
   if (nextOrPrev == NextOrPrev::next) {
     switch(advectedQuantity) {
     case AdvectedQuantity::u: //x-momentum, reference face index is (i, j, k)
       switch (advectingQuantity) {
       case AdvectingQuantity::rho_u:
         advectedQty = InterpolateFromCellOrFace(i, j, k, u, 0, nextOrPrev, Coord::x, spatial_order); // u(i+1/2,    j, k    )
         advectingQty = 0.5*(rho_u(i+1, j, k) + rho_u(i, j, k)); // Effectively rho_u (i+1/2, j, k)
         break;
       case AdvectingQuantity::rho_v:
         advectedQty = InterpolateFromCellOrFace(i, j, k, u, 0, nextOrPrev, Coord::y, spatial_order); // u(i   , j+1/2, k    )
         advectingQty = 0.5*(rho_v(i, j+1, k) + rho_v(i-1, j+1, k)); // Effectively rho_v (i-1/2, j+1, k)
         break;
       case AdvectingQuantity::rho_w:
         advectedQty = InterpolateFromCellOrFace(i, j, k, u, 0, nextOrPrev, Coord::z, spatial_order); // u(i   , j    , k+1/2)
         advectingQty = 0.5*(rho_w(i, j, k+1) + rho_w(i-1, j, k+1)); // Effectively rho_w (i-1/2, j, k+1)
         break;
       default:
         amrex::Abort("Error: Advecting quantity is unrecognized");
       }
       break;
     case AdvectedQuantity::v: //y-momentum, reference face index is (i, j, k)
       switch (advectingQuantity) {
       case AdvectingQuantity::rho_u:
         advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::x, spatial_order); // v(i+1/2,    j, k    )
         advectingQty = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j-1, k)); // Effectively rho_u (i+1, j-1/2, k)
         break;
       case AdvectingQuantity::rho_v:
         advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::y, spatial_order); // v(i   , j+1/2, k    )
         advectingQty = 0.5*(rho_v(i, j+1, k) + rho_v(i, j, k)); // Effectively rho_v (i, j+1/2, k)
         break;
       case AdvectingQuantity::rho_w:
         advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::z, spatial_order); // v(i   , j    , k+1/2)
         advectingQty = 0.5*(rho_w(i, j, k+1) + rho_w(i, j-1, k+1)); // Effectively rho_w (i, j-1/2, k+1)
         break;
       default:
         amrex::Abort("Error: Advecting quantity is unrecognized");
       }
       break;
     case AdvectedQuantity::w: //z-momentum, reference face index is (i, j, k)
       switch (advectingQuantity) {
       case AdvectingQuantity::rho_u:
         advectedQty = InterpolateFromCellOrFace(i, j, k, w, 0, nextOrPrev, Coord::x, spatial_order); // w(i+1/2,    j, k    )
         advectingQty = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j, k-1)); // Effectively rho_u (i+1, j, k-1/2)
         break;
       case AdvectingQuantity::rho_v:
         advectedQty = InterpolateFromCellOrFace(i, j, k, w, 0, nextOrPrev, Coord::y, spatial_order); // w(i   , j+1/2, k    )
         advectingQty = 0.5*(rho_v(i, j+1, k) + rho_v(i, j+1, k-1)); // Effectively rho_v (i, j+1, k-1/2)
         break;
       case AdvectingQuantity::rho_w:
         advectedQty = InterpolateFromCellOrFace(i, j, k, w, 0, nextOrPrev, Coord::z, spatial_order); // w(i   , j    , k+1/2)
         advectingQty = 0.5*(rho_w(i, j, k+1) + rho_w(i, j, k)); // Effectively rho_w (i, j, k+1/2)
         break;
       default:
         amrex::Abort("Error: Advecting quantity is unrecognized");
       }
       break;
     default:
       amrex::Abort("Error: Advected quantity is unrecognized");
     }
   }
   else { // nextOrPrev == NextOrPrev::prev
     switch(advectedQuantity) {
     case AdvectedQuantity::u: //x-momentum, reference face index is (i, j, k)
       switch (advectingQuantity) {
       case AdvectingQuantity::rho_u:
         advectedQty = InterpolateFromCellOrFace(i, j, k, u, 0, nextOrPrev, Coord::x, spatial_order); // u(i-1/2,    j, k    )
         advectingQty = 0.5*(rho_u(i-1, j, k) + rho_u(i, j, k)); // Effectively rho_u (i-1/2, j, k)
         break;
       case AdvectingQuantity::rho_v:
         advectedQty = InterpolateFromCellOrFace(i, j, k, u, 0, nextOrPrev, Coord::y, spatial_order); // u(i   , j-1/2, k    )
         advectingQty = 0.5*(rho_v(i, j, k) + rho_v(i-1, j, k)); // Effectively rho_v (i-1/2, j, k)
         break;
       case AdvectingQuantity::rho_w:
         advectedQty = InterpolateFromCellOrFace(i, j, k, u, 0, nextOrPrev, Coord::z, spatial_order); // u(i   , j    , k-1/2)
         advectingQty = 0.5*(rho_w(i, j, k) + rho_w(i-1, j, k)); // Effectively rho_w (i-1/2, j, k)
         break;
       default:
         amrex::Abort("Error: Advecting quantity is unrecognized");
       }
       break;
     case AdvectedQuantity::v: //y-momentum, reference face index is (i, j, k)
       switch (advectingQuantity) {
       case AdvectingQuantity::rho_u:
         advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::x, spatial_order); // v(i-1/2,    j, k    )
         advectingQty = 0.5*(rho_u(i, j, k) + rho_u(i, j-1, k)); // Effectively rho_u (i, j-1/2, k)
         break;
       case AdvectingQuantity::rho_v:
         advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::y, spatial_order); // v(i   , j-1/2, k    )
         advectingQty = 0.5*(rho_v(i, j, k) + rho_v(i, j-1, k)); // Effectively rho_v (i, j-1/2, k)
         break;
       case AdvectingQuantity::rho_w:
         advectedQty = InterpolateFromCellOrFace(i, j, k, v, 0, nextOrPrev, Coord::z, spatial_order); // v(i   , j    , k-1/2)
         advectingQty = 0.5*(rho_w(i, j, k) + rho_w(i, j-1, k)); // Effectively rho_w (i, j-1/2, k)
         break;
       default:
         amrex::Abort("Error: Advecting quantity is unrecognized");
       }
       break;
     case AdvectedQuantity::w: //z-momentum, reference face index is (i, j, k)
       switch (advectingQuantity) {
       case AdvectingQuantity::rho_u:
         advectedQty = InterpolateFromCellOrFace(i, j, k, w, 0, nextOrPrev, Coord::x, spatial_order); // w(i-1/2,    j, k    )
         advectingQty = 0.5*(rho_u(i, j, k) + rho_u(i, j, k-1)); // Effectively rho_u (i, j, k-1/2)
         break;
       case AdvectingQuantity::rho_v:
         advectedQty = InterpolateFromCellOrFace(i, j, k, w, 0, nextOrPrev, Coord::y, spatial_order); // w(i   , j-1/2, k    )
         advectingQty = 0.5*(rho_v(i, j, k) + rho_v(i, j, k-1)); // Effectively rho_v (i, j, k-1/2)
         break;
       case AdvectingQuantity::rho_w:
         advectedQty = InterpolateFromCellOrFace(i, j, k, w, 0, nextOrPrev, Coord::z, spatial_order); // w(i   , j    , k-1/2)
         advectingQty = 0.5*(rho_w(i, j, k) + rho_w(i, j, k-1)); // Effectively rho_w (i, j, k-1/2)
         break;
       default:
         amrex::Abort("Error: Advecting quantity is unrecognized");
       }
       break;
     default:
       amrex::Abort("Error: Advected quantity is unrecognized");
     }
   }
   return advectingQty * advectedQty;
 }
Referenced by AdvectionContributionForMom().
AdvectionContributionForMom()
AMREX_GPU_DEVICE Real AdvectionContributionForMom (const int & i, const int & j, const int & k, const Array4< Real > & rho_u, const Array4< Real > & rho_v, const Array4< Real > & rho_w, const Array4< Real > & u, const Array4< Real > & v, const Array4< Real > & w, const enum MomentumEqn & momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const SolverChoice & solverChoice)
{
     auto dx = cellSize[0], dy = cellSize[1], dz = cellSize[2];
     Real advectionContribution = 0.0;
     switch (momentumEqn) {
         case MomentumEqn::x: //x-momentum, reference face index is (i, j, k)
             Real centFluxXXNext, centFluxXXPrev, edgeFluxXYNext, edgeFluxXYPrev, edgeFluxXZNext, edgeFluxXZPrev;
             centFluxXXNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::u, AdvectingQuantity::rho_u, solverChoice.spatial_order);
             centFluxXXPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::u, AdvectingQuantity::rho_u, solverChoice.spatial_order);
             edgeFluxXYNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::u, AdvectingQuantity::rho_v, solverChoice.spatial_order);
             edgeFluxXYPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::u, AdvectingQuantity::rho_v, solverChoice.spatial_order);
             edgeFluxXZNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::u, AdvectingQuantity::rho_w, solverChoice.spatial_order);
             edgeFluxXZPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::u, AdvectingQuantity::rho_w, solverChoice.spatial_order);
             advectionContribution = (centFluxXXNext - centFluxXXPrev) / dx   // Contribution to x-mom eqn from advective flux in x-dir
                                   + (edgeFluxXYNext - edgeFluxXYPrev) / dy   // Contribution to x-mom eqn from advective flux in y-dir
                                   + (edgeFluxXZNext - edgeFluxXZPrev) / dz;  // Contribution to x-mom eqn from advective flux in z-dir
             break;
         case MomentumEqn::y: //y-momentum, reference face index is (i, j, k)
             Real centFluxYYNext, centFluxYYPrev, edgeFluxYXNext, edgeFluxYXPrev, edgeFluxYZNext, edgeFluxYZPrev;
             edgeFluxYXNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::v, AdvectingQuantity::rho_u, solverChoice.spatial_order);
             edgeFluxYXPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::v, AdvectingQuantity::rho_u, solverChoice.spatial_order);
             centFluxYYNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::v, AdvectingQuantity::rho_v, solverChoice.spatial_order);
             centFluxYYPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::v, AdvectingQuantity::rho_v, solverChoice.spatial_order);
             edgeFluxYZNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::v, AdvectingQuantity::rho_w, solverChoice.spatial_order);
             edgeFluxYZPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::v, AdvectingQuantity::rho_w, solverChoice.spatial_order);
             advectionContribution = (edgeFluxYXNext - edgeFluxYXPrev) / dx   // Contribution to y-mom eqn from advective flux in x-dir
                                   + (centFluxYYNext - centFluxYYPrev) / dy   // Contribution to y-mom eqn from advective flux in y-dir
                                   + (edgeFluxYZNext - edgeFluxYZPrev) / dz;  // Contribution to y-mom eqn from advective flux in z-dir
             break;
         case MomentumEqn::z: //z-momentum, reference face index is (i, j, k)
             Real centFluxZZNext, centFluxZZPrev, edgeFluxZXNext, edgeFluxZXPrev, edgeFluxZYNext, edgeFluxZYPrev;
             edgeFluxZXNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::w, AdvectingQuantity::rho_u, solverChoice.spatial_order);
             edgeFluxZXPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::w, AdvectingQuantity::rho_u, solverChoice.spatial_order);
             edgeFluxZYNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::w, AdvectingQuantity::rho_v, solverChoice.spatial_order);
             edgeFluxZYPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::w, AdvectingQuantity::rho_v, solverChoice.spatial_order);
             centFluxZZNext = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::next, AdvectedQuantity::w, AdvectingQuantity::rho_w, solverChoice.spatial_order);
             centFluxZZPrev = ComputeAdvectedQuantityForMom(i, j, k, rho_u, rho_v, rho_w, u, v, w, NextOrPrev::prev, AdvectedQuantity::w, AdvectingQuantity::rho_w, solverChoice.spatial_order);
             advectionContribution = (edgeFluxZXNext - edgeFluxZXPrev) / dx  // Contribution to z-mom eqn from advective flux in x-dir
                                   + (edgeFluxZYNext - edgeFluxZYPrev) / dy  // Contribution to z-mom eqn from advective flux in y-dir
                                   + (centFluxZZNext - centFluxZZPrev) / dz; // Contribution to z-mom eqn from advective flux in z-dir
             break;
         default:
             amrex::Abort("Error: Momentum equation is unrecognized");
     }
     return advectionContribution;
 }
Referenced by RK3_stage().
ComputeAdvectedQuantityForState()
AMREX_GPU_DEVICE Real ComputeAdvectedQuantityForState (const int & i, const int & j, const int & k, const Array4< Real > & rho_u, const Array4< Real > & rho_v, const Array4< Real > & rho_w, const Array4< Real > & cell_data, const enum NextOrPrev & nextOrPrev, const enum AdvectedQuantity & advectedQuantity, const enum AdvectingQuantity & advectingQuantity, const int & spatial_order)
{
   Real advectingQty = 0.0;
   Real advectedQty = 1.0;
   /* NOTE: For the all three types of state equations (continuity, energy, scalar),
    * the advecting quantities are the same */
   if (nextOrPrev == NextOrPrev::next) {
     switch (advectingQuantity) { // reference cell is (i, j, k)
     case AdvectingQuantity::rho_u:
       advectingQty = rho_u(i+1, j, k); // rho_u (i+1, j, k)
       break;
     case AdvectingQuantity::rho_v:
       advectingQty = rho_v(i, j+1, k); // rho_v (i, j+1, k)
       break;
     case AdvectingQuantity::rho_w:
       advectingQty = rho_w(i, j, k+1); // rho_w (i, j, k+1)
       break;
     default:
       amrex::Abort("Error: Advecting quantity is unrecognized");
     }
   }
   else { // nextOrPrev == NextOrPrev::prev
     switch (advectingQuantity) { // reference cell is (i, j, k)
     case AdvectingQuantity::rho_u:
       advectingQty = rho_u(i, j, k); // rho_u (i, j, k)
       break;
     case AdvectingQuantity::rho_v:
       advectingQty = rho_v(i, j, k); // rho_v (i, j, k)
       break;
     case AdvectingQuantity::rho_w:
       advectingQty = rho_w(i, j, k); // rho_w (i, j, k)
       break;
     default:
       amrex::Abort("Error: Advecting quantity is unrecognized");
     }
   }
   // Compute advected quantity for different choice of AdvectingQuantity
   switch(advectedQuantity) {
   case AdvectedQuantity::unity: // continuity equation, reference cell is (i, j, k)
     advectedQty = 1.0; // for AdvectingQuantity = {rho_u, rho_v, rho_w}
     break;
   case AdvectedQuantity::theta:
     switch (advectingQuantity) { // reference cell is (i, j, k)
     case AdvectingQuantity::rho_u:
       // Get theta (i+1/2,    j, k    ) = theta on face (i+1, j  , k  ) for x-dir if nextOrPrev = NextOrPrev::next
       // Get theta (i-1/2,    j, k    ) = theta on face (i,   j  , k  ) for x-dir if nextOrPrev = NextOrPrev::prev
       advectedQty = InterpolateRhoThetaFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::x, spatial_order);
       advectedQty/= InterpolateDensityFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::x, spatial_order);
       break;
     case AdvectingQuantity::rho_v:
       // Get theta (i   , j+1/2, k    ) = theta on face (i  , j+1, k  ) for y-dir if nextOrPrev = NextOrPrev::next
       // Get theta (i   , j-1/2, k    ) = theta on face (i  , j  , k  ) for y-dir if nextOrPrev = NextOrPrev::prev
       advectedQty = InterpolateRhoThetaFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::y, spatial_order);
       advectedQty/= InterpolateDensityFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::y, spatial_order);
       break;
     case AdvectingQuantity::rho_w:
       // Get theta (i   , j    , k+1/2) = theta on face (i  , j  , k+1) for z-dir if nextOrPrev = NextOrPrev::next
       // Get theta (i   , j    , k-1/2) = theta on face (i  , j  , k  ) for z-dir if nextOrPrev = NextOrPrev::prev
       advectedQty = InterpolateRhoThetaFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::z, spatial_order);
       advectedQty/= InterpolateDensityFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::z, spatial_order);
       break;
     default:
       amrex::Abort("Error: Advecting quantity is unrecognized");
     }
     break;
   case AdvectedQuantity::scalar:
     switch (advectingQuantity) { // reference cell is (i, j, k)
     case AdvectingQuantity::rho_u:
       // Get scalar (i+1/2,    j, k    ) = scalar on face (i+1, j  , k  ) for x-dir if nextOrPrev = NextOrPrev::next
       // Get scalar (i-1/2,    j, k    ) = scalar on face (i,   j  , k  ) for x-dir if nextOrPrev = NextOrPrev::prev
       advectedQty = InterpolateRhoScalarFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::x, spatial_order);
       advectedQty/= InterpolateDensityFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::x, spatial_order);
       break;
     case AdvectingQuantity::rho_v:
       // Get scalar (i   , j+1/2, k    ) = scalar on face (i  , j+1, k  ) for y-dir if nextOrPrev = NextOrPrev::next
       // Get scalar (i   , j-1/2, k    ) = scalar on face (i  , j  , k  ) for y-dir if nextOrPrev = NextOrPrev::prev
       advectedQty = InterpolateRhoScalarFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::y, spatial_order);
       advectedQty/= InterpolateDensityFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::y, spatial_order);
       break;
     case AdvectingQuantity::rho_w:
       // Get scalar (i   , j    , k+1/2) = scalar on face (i  , j  , k+1) for z-dir if nextOrPrev = NextOrPrev::next
       // Get scalar (i   , j    , k-1/2) = scalar on face (i  , j  , k  ) for z-dir if nextOrPrev = NextOrPrev::prev
       advectedQty = InterpolateRhoScalarFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::z, spatial_order);
       advectedQty/= InterpolateDensityFromCellToFace(i, j, k, cell_data, nextOrPrev, Coord::z, spatial_order);
       break;
     default:
       amrex::Abort("Error: Advecting quantity is unrecognized");
     }
     break;
   default:
     amrex::Abort("Error: Advected quantity is unrecognized");
   }
   // Return the product of advected and advecting quantities
   return advectingQty * advectedQty;
 }
AdvectionContributionForState()
AMREX_GPU_DEVICE Real AdvectionContributionForState (const int & i, const int & j, const int & k, const Array4< Real > & rho_u, const Array4< Real > & rho_v, const Array4< Real > & rho_w, const Array4< Real > & cell_data, const int & qty_index, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
{
     auto dx = cellSize[0], dy = cellSize[1], dz = cellSize[2];
     Real xFaceFluxNext = 0.0, xFaceFluxPrev = 0.0, yFaceFluxNext = 0.0, yFaceFluxPrev = 0.0, zFaceFluxNext = 0.0, zFaceFluxPrev = 0.0;
     Real advectionContribution = 0.0;
     switch(qty_index) {
         case Rho_comp: // Continuity
             xFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::unity, AdvectingQuantity::rho_u, spatial_order);
             xFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::unity, AdvectingQuantity::rho_u, spatial_order);
             yFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::unity, AdvectingQuantity::rho_v, spatial_order);
             yFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::unity, AdvectingQuantity::rho_v, spatial_order);
             zFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::unity, AdvectingQuantity::rho_w, spatial_order);
             zFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::unity, AdvectingQuantity::rho_w, spatial_order);
             break;
         case RhoTheta_comp: // Temperature
             xFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::theta, AdvectingQuantity::rho_u, spatial_order);
             xFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::theta, AdvectingQuantity::rho_u, spatial_order);
             yFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::theta, AdvectingQuantity::rho_v, spatial_order);
             yFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::theta, AdvectingQuantity::rho_v, spatial_order);
             zFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::theta, AdvectingQuantity::rho_w, spatial_order);
             zFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::theta, AdvectingQuantity::rho_w, spatial_order);
             break;
         case RhoScalar_comp: // Scalar
             xFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::scalar, AdvectingQuantity::rho_u, spatial_order);
             xFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::scalar, AdvectingQuantity::rho_u, spatial_order);
             yFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::scalar, AdvectingQuantity::rho_v, spatial_order);
             yFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::scalar, AdvectingQuantity::rho_v, spatial_order);
             zFaceFluxNext = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::next, AdvectedQuantity::scalar, AdvectingQuantity::rho_w, spatial_order);
             zFaceFluxPrev = ComputeAdvectedQuantityForState(i, j, k, rho_u, rho_v, rho_w, cell_data, NextOrPrev::prev, AdvectedQuantity::scalar, AdvectingQuantity::rho_w, spatial_order);
             break;
         default:
             amrex::Abort("Error: Conserved quantity index is unrecognized");
     }
     // Assemble advection contribution
     advectionContribution = (xFaceFluxNext - xFaceFluxPrev)/ dx  // Advective flux in x-dir
                                + (yFaceFluxNext - yFaceFluxPrev)/ dy  // Advective flux in y-dir
                                + (zFaceFluxNext - zFaceFluxPrev)/ dz; // Advective flux in z-dir
     return advectionContribution;
 }
Referenced by RK3_stage().
ComputeStrainRate()
AMREX_GPU_DEVICE Real ComputeStrainRate (const int & i, const int & j, const int & k, const Array4< Real > & u, const Array4< Real > & v, const Array4< Real > & w, const enum NextOrPrev & nextOrPrev, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const GpuArray< Real, AMREX_SPACEDIM > & cellSize)
{
   Real dx = cellSize[0];
   Real dy = cellSize[1];
   Real dz = cellSize[2];
   Real strainRate = 0;
   //TODO: Account for extra terms in the diagonal elements. See the issue: https://github.com/erf-model/ERF/issues/61
   switch (momentumEqn) {
   case MomentumEqn::x:
     switch (diffDir) {
     case DiffusionDir::x: // S11
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (u(i+1, j, k) - u(i, j, k))/dx; // S11 (i+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (u(i, j, k) - u(i-1, j, k))/dx; // S11 (i-1/2)
       break;
     case DiffusionDir::y: // S12
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (u(i, j+1, k) - u(i, j, k))/dy + (v(i, j+1, k) - v(i-1, j+1, k))/dx; // S12 (j+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (u(i, j, k) - u(i, j-1, k))/dy + (v(i, j, k) - v(i-1, j, k))/dx; // S12 (j-1/2)
       strainRate *= 0.5;
       break;
     case DiffusionDir::z: // S13
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (u(i, j, k+1) - u(i, j, k))/dz + (w(i, j, k+1) - w(i-1, j, k+1))/dx; // S13 (k+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (u(i, j, k) - u(i, j, k-1))/dz + (w(i, j, k) - w(i-1, j, k))/dx; // S13 (k-1/2)
       strainRate *= 0.5;
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::y:
     switch (diffDir) {
     case DiffusionDir::x: // S21
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (u(i+1, j, k) - u(i+1, j-1, k))/dy + (v(i+1, j, k) - v(i, j, k))/dx; // S21 (i+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (u(i, j, k) - u(i, j-1, k))/dy + (v(i, j, k) - v(i-1, j, k))/dx; // S21 (i-1/2)
       strainRate *= 0.5;
       break;
     case DiffusionDir::y: // S22
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (v(i, j+1, k) - v(i, j, k))/dy; // S22 (j+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (v(i, j, k) - v(i, j-1, k))/dy; // S22 (j-1/2)
       break;
     case DiffusionDir::z: // S23
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (v(i, j, k+1) - v(i, j, k))/dz + (w(i, j, k+1) - w(i, j-1, k+1))/dy; // S23 (k+1/2) //TODO: Check this with Branko
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (v(i, j, k) - v(i, j, k-1))/dz + (w(i, j, k) - w(i, j-1, k))/dy; // S23 (k-1/2) //TODO: Check this with Branko
       strainRate *= 0.5;
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::z:
     switch (diffDir) {
     case DiffusionDir::x: // S31
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (u(i+1, j, k) - u(i+1, j, k-1))/dz + (w(i+1, j, k) - w(i, j, k))/dx; // S31 (i+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (u(i, j, k) - u(i, j, k-1))/dz + (w(i, j, k) - w(i-1, j, k))/dx; // S31 (i-1/2)
       strainRate *= 0.5;
       break;
     case DiffusionDir::y: // S32
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (v(i, j+1, k) - v(i, j+1, k-1))/dz + (w(i, j+1, k) - w(i, j, k))/dy; // S32 (j+1/2) //TODO: Check this with Branko
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (v(i, j, k) - v(i, j, k-1))/dz + (w(i, j, k) - w(i, j-1, k))/dy; // S32 (j-1/2) //TODO: Check this with Branko
       strainRate *= 0.5;
       break;
     case DiffusionDir::z: // S33
       if (nextOrPrev == NextOrPrev::next)
         strainRate = (w(i, j, k+1) - w(i, j, k))/dz; // S33 (k+1/2)
       else // nextOrPrev == NextOrPrev::prev
         strainRate = (w(i, j, k) - w(i, j, k-1))/dz; // S33 (k-1/2)
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   default:
     amrex::Abort("Error: Momentum equation is unrecognized");
   }
   return strainRate;
 }
Referenced by ComputeStressTerm().
ComputeTurbulentViscosity()
void ComputeTurbulentViscosity (MultiFab & xvel, MultiFab & yvel, MultiFab & zvel, MultiFab & cons_in, MultiFab & eddyViscosity, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const SolverChoice & solverChoice)
{
     const Real cellVol = cellSize[0] * cellSize[1] * cellSize[2];
     Real Cs = solverChoice.Cs;
     Real CsDeltaSqr = Cs*Cs * std::pow(cellVol, 2.0/3.0);
     for ( MFIter mfi(eddyViscosity,TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const Box &bx = mfi.tilebox();
         const Array4<Real> &cell_data = cons_in.array(mfi);
         const Array4<Real> &K = eddyViscosity.array(mfi);
         const Array4<Real> &u = xvel.array(mfi);
         const Array4<Real> &v = yvel.array(mfi);
         const Array4<Real> &w = zvel.array(mfi);
         amrex::ParallelFor(bx, eddyViscosity.nComp(),[=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             Real S11 = ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::next, MomentumEqn::x, DiffusionDir::x, cellSize);
             Real S22 = ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::next, MomentumEqn::y, DiffusionDir::y, cellSize);
             Real S33 = ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::next, MomentumEqn::z, DiffusionDir::z, cellSize);
             Real S12 = 0.25* (
                       ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::prev, MomentumEqn::x, DiffusionDir::y, cellSize)
                     + ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::next, MomentumEqn::x, DiffusionDir::y, cellSize)
                     + ComputeStrainRate(i+1, j, k, u, v, w, NextOrPrev::prev, MomentumEqn::x, DiffusionDir::y, cellSize)
                     + ComputeStrainRate(i+1, j, k, u, v, w, NextOrPrev::next, MomentumEqn::x, DiffusionDir::y, cellSize)
                     );
             Real S13 = 0.25* (
                       ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::prev, MomentumEqn::x, DiffusionDir::z, cellSize)
                     + ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::next, MomentumEqn::x, DiffusionDir::z, cellSize)
                     + ComputeStrainRate(i+1, j, k, u, v, w, NextOrPrev::prev, MomentumEqn::x, DiffusionDir::z, cellSize)
                     + ComputeStrainRate(i+1, j, k, u, v, w, NextOrPrev::next, MomentumEqn::x, DiffusionDir::z, cellSize)
                     );
             Real S23 = 0.25* (
                       ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::prev, MomentumEqn::y, DiffusionDir::z, cellSize)
                     + ComputeStrainRate(i, j, k, u, v, w, NextOrPrev::next, MomentumEqn::y, DiffusionDir::z, cellSize)
                     + ComputeStrainRate(i, j+1, k, u, v, w, NextOrPrev::prev, MomentumEqn::y, DiffusionDir::z, cellSize)
                     + ComputeStrainRate(i, j+1, k, u, v, w, NextOrPrev::next, MomentumEqn::y, DiffusionDir::z, cellSize)
                     );
             Real SmnSmn = S11*S11 + S22*S22 + S33*S33 + 2.0*S12*S12 + 2.0*S13*S13 + 2.0*S23*S23;
             // TODO: Check sign in the below equation
             K(i, j, k, 0) = 2.0 * CsDeltaSqr * cell_data(i, j, k, Rho_comp) * std::sqrt(2.0*SmnSmn);
         });
     } //mfi
 } // function call
Referenced by RK3_stage().
InterpolateTurbulentViscosity()
AMREX_GPU_DEVICE Real InterpolateTurbulentViscosity (const int & i, const int & j, const int & k, const Array4< Real > & u, const Array4< Real > & v, const Array4< Real > & w, const enum NextOrPrev & nextOrPrev, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & nut)
Compute K (i-1/2, j+1/2, k) etc given K(i, j, k) or nut (i, j, k) is known.
{
   // Assuming we already have 'nut' computed for all (i, j, k)
   Real turbViscInterpolated = 1.0;
   switch (momentumEqn) {
   case MomentumEqn::x: // Reference face is x-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       if (nextOrPrev == NextOrPrev::next)    // K (i  , j, k) needed to obtain tau11 (i+1/2)
         turbViscInterpolated = nut(i, j, k);
       else // nextOrPrev == NextOrPrev::prev // K (i-1, j, k) needed to obtain tau11 (i-1/2)
         turbViscInterpolated = nut(i-1, j, k);
       break;
     case DiffusionDir::y:
       if (nextOrPrev == NextOrPrev::next)    // K (i-1/2, j+1/2, k) needed to obtain tau12 (j+1/2)
         turbViscInterpolated = 0.25*( nut(i-1, j, k) + nut(i, j, k) + nut(i-1, j+1, k) + nut(i, j+1, k) );
       else // nextOrPrev == NextOrPrev::prev // K (i-1/2, j-1/2, k) needed to obtain tau12 (j-1/2)
         turbViscInterpolated = 0.25*( nut(i-1, j, k) + nut(i, j, k) + nut(i-1, j-1, k) + nut(i, j-1, k) );
       break;
     case DiffusionDir::z:
       if (nextOrPrev == NextOrPrev::next)    // K (i-1/2, j, k+1/2) needed to obtain tau13 (k+1/2)
         turbViscInterpolated = 0.25*( nut(i-1, j, k) + nut(i, j, k) + nut(i-1, j, k+1) + nut(i, j, k+1) );
       else // nextOrPrev == NextOrPrev::prev // K (i-1/2, j, k-1/2) needed to obtain tau13 (k-1/2)
         turbViscInterpolated = 0.25*( nut(i-1, j, k) + nut(i, j, k) + nut(i-1, j, k-1) + nut(i, j, k-1) );
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::y: // Reference face is y-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       if (nextOrPrev == NextOrPrev::next)    // K (i+1/2, j-1/2, k) needed to obtain tau21 (i+1/2)
         turbViscInterpolated = 0.25*( nut(i, j-1, k) + nut(i, j, k) + nut(i+1, j-1, k) + nut(i+1, j, k) );
       else // nextOrPrev == NextOrPrev::prev // K (i-1/2, j-1/2, k) needed to obtain tau21 (i-1/2)
         turbViscInterpolated = 0.25*( nut(i, j-1, k) + nut(i, j, k) + nut(i-1, j-1, k) + nut(i-1, j, k) );
       break;
     case DiffusionDir::y:
       if (nextOrPrev == NextOrPrev::next)    // K (i, j  , k) needed to obtain tau22 (j+1/2)
         turbViscInterpolated = nut(i, j, k);
       else // nextOrPrev == NextOrPrev::prev // K (i, j-1, k) needed to obtain tau22 (j-1/2)
         turbViscInterpolated = nut(i, j-1, k);
       break;
     case DiffusionDir::z:
       if (nextOrPrev == NextOrPrev::next)    // K (i, j-1/2, k+1/2) needed to obtain tau23 (k+1/2)
         turbViscInterpolated = 0.25*( nut(i, j-1, k) + nut(i, j, k) + nut(i, j-1, k+1) + nut(i, j, k+1) );
       else // nextOrPrev == NextOrPrev::prev // K (i, j-1/2, k-1/2) needed to obtain tau23 (k-1/2)
         turbViscInterpolated = 0.25*( nut(i, j-1, k) + nut(i, j, k) + nut(i, j-1, k-1) + nut(i, j, k-1) );
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::z: // Reference face is z-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       if (nextOrPrev == NextOrPrev::next)    // K (i+1/2, j, k-1/2) needed to obtain tau31 (i+1/2)
         turbViscInterpolated = 0.25*( nut(i, j, k-1) + nut(i, j, k) + nut(i+1, j, k-1) + nut(i+1, j, k) );
       else // nextOrPrev == NextOrPrev::prev // K (i-1/2, j, k-1/2) needed to obtain tau31 (i-1/2)
         turbViscInterpolated = 0.25*( nut(i, j, k-1) + nut(i, j, k) + nut(i-1, j, k-1) + nut(i-1, j, k) );
       break;
     case DiffusionDir::y:
       if (nextOrPrev == NextOrPrev::next)    // K (i, j+1/2, k-1/2) needed to obtain tau32 (j+1/2)
         turbViscInterpolated = 0.25*( nut(i, j, k-1) + nut(i, j, k) + nut(i, j+1, k-1) + nut(i, j+1, k) );
       else // nextOrPrev == NextOrPrev::prev // K (i, j-1/2, k-1/2) needed to obtain tau32 (j-1/2)
         turbViscInterpolated = 0.25*( nut(i, j, k-1) + nut(i, j, k) + nut(i, j-1, k-1) + nut(i, j-1, k) );
       break;
     case DiffusionDir::z:
       if (nextOrPrev == NextOrPrev::next)    // K (i, j, k  ) needed to obtain tau33 (k+1/2)
         turbViscInterpolated = nut(i, j, k);
       else // nextOrPrev == NextOrPrev::prev // K (i, j, k-1) needed to obtain tau33 (k-1/2)
         turbViscInterpolated = nut(i, j, k-1);
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   default:
     amrex::Abort("Error: Momentum equation is unrecognized");
   }
   return turbViscInterpolated;
 }
Referenced by ComputeStressTerm().
ComputeStressTerm()
AMREX_GPU_DEVICE Real ComputeStressTerm (const int & i, const int & j, const int & k, const Array4< Real > & u, const Array4< Real > & v, const Array4< Real > & w, const enum NextOrPrev & nextOrPrev, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & nut, const SolverChoice & solverChoice)
{
     Real stressTerm = 0.0;
     Real turbViscInterpolated = 0.0;
     // Here, we have computed strain rate on the fly.
     // TODO: It may be better to store S11, S12 etc. at all the (m+1/2) and (m-1/2) grid points (edges) and use them here.
     Real strainRate = ComputeStrainRate(i, j, k, u, v, w, nextOrPrev, momentumEqn, diffDir, cellSize);
     // TODO: Consider passing turbModel to this function instead of computing it here from SolverChoice
     enum TurbulenceModel turbModel;
     //TODO: Update this to account for other turbulence models in future. This would alo require update in SolverChoice
     if (solverChoice.use_smagorinsky)
         turbModel = TurbulenceModel::Smagorinsky;
     else
         turbModel = TurbulenceModel::DNS;
     switch (turbModel) {
         case TurbulenceModel::DNS:
             //TODO: dynamic viscosity, mu, is assumed to be constant in the current implementation.
             // Future implementations may account for mu = mu(T) computed at the coordinate of interest.
             stressTerm = 2.0 * solverChoice.dynamicViscosity * strainRate; // 2*mu*Sij(m+1/2) or 2*mu*Sij(m-1/2)
             break;
         case TurbulenceModel::Smagorinsky:
             turbViscInterpolated = InterpolateTurbulentViscosity(i, j, k, u, v, w, nextOrPrev, momentumEqn, diffDir, cellSize, nut);
             stressTerm = turbViscInterpolated * strainRate; // // K_interp*Sij(m+1/2) or K_interp*Sij(m-1/2)
             break;
         default:
             amrex::Abort("Error: Turbulence model is unrecognized");
     }
     return stressTerm;
 }
Referenced by DiffusionContributionForMom().
DiffusionContributionForMom()
AMREX_GPU_DEVICE Real DiffusionContributionForMom (const int & i, const int & j, const int & k, const Array4< Real > & u, const Array4< Real > & v, const Array4< Real > & w, const enum MomentumEqn & momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & nut, const SolverChoice & solverChoice)
{
     auto dx = cellSize[0], dy = cellSize[1], dz = cellSize[2];
     Real diffusionContribution = 0.0;
     switch (momentumEqn) {
         case MomentumEqn::x:
             Real tau11Next, tau11Prev, tau12Next, tau12Prev, tau13Next, tau13Prev;
             tau11Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::x, cellSize, nut, solverChoice);
             tau11Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::x, cellSize, nut, solverChoice);
             tau12Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::y, cellSize, nut, solverChoice);
             tau12Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::y, cellSize, nut, solverChoice);
             tau13Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::z, cellSize, nut, solverChoice);
             tau13Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::z, cellSize, nut, solverChoice);
             diffusionContribution = (tau11Next - tau11Prev) / dx  // Contribution to x-mom eqn from diffusive flux in x-dir
                                   + (tau12Next - tau12Prev) / dy  // Contribution to x-mom eqn from diffusive flux in y-dir
                                   + (tau13Next - tau13Prev) / dz; // Contribution to x-mom eqn from diffusive flux in z-dir
             break;
         case MomentumEqn::y:
             Real tau21Next, tau21Prev, tau22Next, tau22Prev, tau23Next, tau23Prev;
             tau21Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::x, cellSize, nut, solverChoice);
             tau21Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::x, cellSize, nut, solverChoice);
             tau22Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::y, cellSize, nut, solverChoice);
             tau22Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::y, cellSize, nut, solverChoice);
             tau23Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::z, cellSize, nut, solverChoice);
             tau23Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::z, cellSize, nut, solverChoice);
             diffusionContribution = (tau21Next - tau21Prev) / dx  // Contribution to y-mom eqn from diffusive flux in x-dir
                                   + (tau22Next - tau22Prev) / dy  // Contribution to y-mom eqn from diffusive flux in y-dir
                                   + (tau23Next - tau23Prev) / dz; // Contribution to y-mom eqn from diffusive flux in z-dir
             break;
         case MomentumEqn::z:
             Real tau31Next, tau31Prev, tau32Next, tau32Prev, tau33Next, tau33Prev;
             tau31Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::x, cellSize, nut, solverChoice);
             tau31Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::x, cellSize, nut, solverChoice);
             tau32Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::y, cellSize, nut, solverChoice);
             tau32Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::y, cellSize, nut, solverChoice);
             tau33Next = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::next, momentumEqn, DiffusionDir::z, cellSize, nut, solverChoice);
             tau33Prev = ComputeStressTerm(i, j, k, u, v, w, NextOrPrev::prev, momentumEqn, DiffusionDir::z, cellSize, nut, solverChoice);
             diffusionContribution = (tau31Next - tau31Prev) / dx  // Contribution to z-mom eqn from diffusive flux in x-dir
                                   + (tau32Next - tau32Prev) / dy  // Contribution to z-mom eqn from diffusive flux in y-dir
                                   + (tau33Next - tau33Prev) / dz; // Contribution to z-mom eqn from diffusive flux in z-dir
             break;
         default:
             amrex::Abort("Error: Momentum equation is unrecognized");
     }
     return diffusionContribution;
 }
Referenced by RK3_stage().
ComputeDiffusionTermForState()
AMREX_GPU_DEVICE Real ComputeDiffusionTermForState (const int & i, const int & j, const int & k, const Array4< Real > & cell_data, const int & qty_index, const enum Coord & coordDir)
{
     Real diffusionTerm = 0.0;
     //TODO: Discuss about the implementation changes needed (if any). The current implemenation is based on a previous
     // version of documentation.
     switch (coordDir) {
         case Coord::x:
             diffusionTerm = cell_data(i+1, j, k, qty_index) -2.0*cell_data(i, j, k, qty_index) + cell_data(i-1, j, k, qty_index);
             break;
         case Coord::y:
             diffusionTerm = cell_data(i, j+1, k, qty_index) -2.0*cell_data(i, j, k, qty_index) + cell_data(i, j-1, k, qty_index);
             break;
         case Coord::z:
             diffusionTerm = cell_data(i, j, k+1, qty_index) -2.0*cell_data(i, j, k, qty_index) + cell_data(i, j, k-1, qty_index);
             break;
         default:
             amrex::Abort("Error: Coord direction is unrecognized");
     }
     return diffusionTerm;
 }
Referenced by DiffusionContributionForState().
DiffusionContributionForState()
AMREX_GPU_DEVICE Real DiffusionContributionForState (const int & i, const int & j, const int & k, const Array4< Real > & cell_data, const int & qty_index, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const SolverChoice & solverChoice)
{
     auto dx = cellSize[0], dy = cellSize[1], dz = cellSize[2];
     Real xDiffFlux = 0.0, yDiffFlux = 0.0, zDiffFlux = 0.0, diffCoeff = 0.0;
     xDiffFlux = ComputeDiffusionTermForState(i, j, k, cell_data, qty_index, Coord::x);
     yDiffFlux = ComputeDiffusionTermForState(i, j, k, cell_data, qty_index, Coord::y);
     zDiffFlux = ComputeDiffusionTermForState(i, j, k, cell_data, qty_index, Coord::z);
     //TODO: Discuss about the implementation changes needed (if any). Diffusion coefficients are assumed to be constant.
     switch(qty_index) {
         case RhoTheta_comp: // Temperature
             diffCoeff = solverChoice.alpha_T;
             break;
         case RhoScalar_comp: // Scalar
             diffCoeff = solverChoice.alpha_C;
             break;
         default:
             amrex::Abort("Error: Diffusion term for the data index isn't implemented");
     }
     // Assemble diffusion contribution.
     Real diffusionContribution = diffCoeff *
                                  (  xDiffFlux / (dx*dx)  // Diffusive flux in x-dir
                                   + yDiffFlux / (dy*dy)  // Diffusive flux in y-dir
                                   + zDiffFlux / (dz*dz)  // Diffusive flux in z-dir
                                  );
     return diffusionContribution;
 }
Referenced by RK3_stage().
ComputeGhostCells()
int ComputeGhostCells (const int & spatial_order)
{
   int nGhostCells;
   //TODO: Make sure we have correct number of ghost cells for different spatial orders.
   // As of Oct. 27, 2021 we haven't played around with number of ghost cells as a function of spatial order
   switch (spatial_order) {
     case 1:
       nGhostCells = 1;
       break;
     case 2:
       nGhostCells = 1;
       break;
     case 3:
       nGhostCells = 1;
       break;
     case 4:
       nGhostCells = 1;
       break;
     case 5:
       nGhostCells = 1;
       break;
     case 6:
       nGhostCells = 1;
       break;
     default:
       nGhostCells = 1;
   }
   return nGhostCells;
 }
Referenced by RK3_advance().