var annotated_dup =
[
    [ "ncutils", "namespacencutils.html", [
      [ "NCDType", "structncutils_1_1NCDType.html", "structncutils_1_1NCDType" ],
      [ "NCDim", "structncutils_1_1NCDim.html", "structncutils_1_1NCDim" ],
      [ "NCVar", "structncutils_1_1NCVar.html", "structncutils_1_1NCVar" ],
      [ "NCGroup", "classncutils_1_1NCGroup.html", "classncutils_1_1NCGroup" ],
      [ "NCFile", "classncutils_1_1NCFile.html", "classncutils_1_1NCFile" ]
    ] ],
    [ "ABLMost", "classABLMost.html", "classABLMost" ],
    [ "ABLMostData", "classABLMostData.html", "classABLMostData" ],
    [ "CENTERED2", "structCENTERED2.html", "structCENTERED2" ],
    [ "CENTERED4", "structCENTERED4.html", "structCENTERED4" ],
    [ "CENTERED6", "structCENTERED6.html", "structCENTERED6" ],
    [ "DirectionSelector", "structDirectionSelector.html", "structDirectionSelector" ],
    [ "DirectionSelector< 0 >", "structDirectionSelector_3_010_01_4.html", "structDirectionSelector_3_010_01_4" ],
    [ "DirectionSelector< 1 >", "structDirectionSelector_3_011_01_4.html", "structDirectionSelector_3_011_01_4" ],
    [ "DirectionSelector< 2 >", "structDirectionSelector_3_012_01_4.html", "structDirectionSelector_3_012_01_4" ],
    [ "EbertCurry", "classEbertCurry.html", "classEbertCurry" ],
    [ "ERF", "classERF.html", "classERF" ],
    [ "ERFFillPatcher", "classERFFillPatcher.html", "classERFFillPatcher" ],
    [ "ERFPhysBCFunct", "classERFPhysBCFunct.html", "classERFPhysBCFunct" ],
    [ "InputSoundingData", "structInputSoundingData.html", "structInputSoundingData" ],
    [ "Microphysics", "classMicrophysics.html", "classMicrophysics" ],
    [ "MOSTAverage", "classMOSTAverage.html", "classMOSTAverage" ],
    [ "MRISplitIntegrator", "classMRISplitIntegrator.html", "classMRISplitIntegrator" ],
    [ "MultiBlockContainer", "classMultiBlockContainer.html", "classMultiBlockContainer" ],
    [ "NDArray", "structNDArray.html", "structNDArray" ],
    [ "PlaneAverage", "classPlaneAverage.html", "classPlaneAverage" ],
    [ "RadConstants", "classRadConstants.html", "classRadConstants" ],
    [ "ReadBndryPlanes", "classReadBndryPlanes.html", "classReadBndryPlanes" ],
    [ "Rrtmgp", "classRrtmgp.html", "classRrtmgp" ],
    [ "SatMethods", "classSatMethods.html", "classSatMethods" ],
    [ "Slingo", "classSlingo.html", "classSlingo" ],
    [ "SolverChoice", "structSolverChoice.html", "structSolverChoice" ],
    [ "TimeInterpolatedData", "structTimeInterpolatedData.html", "structTimeInterpolatedData" ],
    [ "UPWIND3", "structUPWIND3.html", "structUPWIND3" ],
    [ "UPWIND5", "structUPWIND5.html", "structUPWIND5" ],
    [ "UPWINDALL", "structUPWINDALL.html", "structUPWINDALL" ],
    [ "WaterVaporSat", "classWaterVaporSat.html", "classWaterVaporSat" ],
    [ "WENO3", "structWENO3.html", "structWENO3" ],
    [ "WENO5", "structWENO5.html", "structWENO5" ],
    [ "WENO_MZQ3", "structWENO__MZQ3.html", "structWENO__MZQ3" ],
    [ "WENO_Z3", "structWENO__Z3.html", "structWENO__Z3" ],
    [ "WENO_Z5", "structWENO__Z5.html", "structWENO__Z5" ],
    [ "WriteBndryPlanes", "classWriteBndryPlanes.html", "classWriteBndryPlanes" ]
];