var annotated_dup =
[
    [ "ncutils", "namespacencutils.html", "namespacencutils" ],
    [ "ABLFieldInit", "structABLFieldInit.html", "structABLFieldInit" ],
    [ "ABLMost", "structABLMost.html", "structABLMost" ],
    [ "BoundaryData", "structBoundaryData.html", "structBoundaryData" ],
    [ "DirectionSelector", "structDirectionSelector.html", "structDirectionSelector" ],
    [ "DirectionSelector< 0 >", "structDirectionSelector_3_010_01_4.html", "structDirectionSelector_3_010_01_4" ],
    [ "DirectionSelector< 1 >", "structDirectionSelector_3_011_01_4.html", "structDirectionSelector_3_011_01_4" ],
    [ "DirectionSelector< 2 >", "structDirectionSelector_3_012_01_4.html", "structDirectionSelector_3_012_01_4" ],
    [ "ERF", "classERF.html", "classERF" ],
    [ "ERF_IC_BC", "classERF__IC__BC.html", "classERF__IC__BC" ],
    [ "ERFPhysBCFunct", "classERFPhysBCFunct.html", "classERFPhysBCFunct" ],
    [ "InitialData", "structInitialData.html", "structInitialData" ],
    [ "InputSoundingData", "structInputSoundingData.html", "structInputSoundingData" ],
    [ "Metgrid_Output", "classMetgrid__Output.html", "classMetgrid__Output" ],
    [ "MRISplitIntegrator", "classMRISplitIntegrator.html", "classMRISplitIntegrator" ],
    [ "NDArray", "structNDArray.html", "structNDArray" ],
    [ "NullFill", "structNullFill.html", "structNullFill" ],
    [ "PlaneAverage", "classPlaneAverage.html", "classPlaneAverage" ],
    [ "ReadBndryPlanes", "classReadBndryPlanes.html", "classReadBndryPlanes" ],
    [ "SolverChoice", "structSolverChoice.html", "structSolverChoice" ],
    [ "TimeInterpolatedData", "structTimeInterpolatedData.html", "structTimeInterpolatedData" ],
    [ "VelPlaneAverage", "classVelPlaneAverage.html", "classVelPlaneAverage" ],
    [ "WriteBndryPlanes", "classWriteBndryPlanes.html", "classWriteBndryPlanes" ]
];