ERF: TimeIntegrator< T > Class Template Reference
TimeIntegrator< T > Class Template Reference
#include <AMReX_TimeIntegrator.H>
Public Member Functions
TimeIntegrator (T &S_data)
virtual ~TimeIntegrator ()
void set_post_timestep (std::function< void()> F)
void set_post_update (std::function< void(T &, amrex::Real)> F)
void set_rhs (std::function< void(T &, const T &, const amrex::Real)> F)
void advance (T &S_old, T &S_new, amrex::Real time, const amrex::Real timestep)
void integrate (T &S_old, T &S_new, amrex::Real start_time, const amrex::Real start_timestep, const amrex::Real end_time, const int nsteps)
void time_interpolate (const T &S_new, const T &S_old, amrex::Real timestep_fraction, T &data)
void map_data (std::function< void(T &)> Map)
Private Attributes
std::unique_ptr< IntegratorBase< T > > integrator_ptr
std::function< void()> post_timestep
Constructor & Destructor Documentation
TimeIntegrator()
template<class T > TimeIntegrator< T >::TimeIntegrator (T & S_data) inline
     {
         amrex::ParmParse pp("integration");
         int integrator_type = IntegratorTypes::ForwardEuler;
         pp.query("type", integrator_type);
         switch (integrator_type)
         {
             case IntegratorTypes::ForwardEuler:
                 integrator_ptr = std::make_unique<FEIntegrator<T> >(S_data);
                 break;
             case IntegratorTypes::ExplicitRungeKutta:
                 integrator_ptr = std::make_unique<RKIntegrator<T> >(S_data);
                 break;
             default:
                 amrex::Error("integration.type did not name a valid integrator type.");
                 break;
         }
         // By default, do nothing post-timestep
         set_post_timestep([](){});
         // By default, do nothing after updating the state
         // In general, this is where BCs should be filled
         set_post_update([](T& S_data, amrex::Real S_time){});
         // By default, do nothing
         set_rhs([](T& S_rhs, const T& S_data, const amrex::Real time){});
     }
~TimeIntegrator()
template<class T > virtual TimeIntegrator< T >::~TimeIntegrator () inline virtual
 {}
Member Function Documentation
advance()
template<class T > void TimeIntegrator< T >::advance (T & S_old, T & S_new, amrex::Real time, const amrex::Real timestep) inline
     {
         integrator_ptr->advance(S_old, S_new, time, timestep);
     }
Referenced by erf_advance().
integrate()
template<class T > void TimeIntegrator< T >::integrate (T & S_old, T & S_new, amrex::Real start_time, const amrex::Real start_timestep, const amrex::Real end_time, const int nsteps) inline
     {
         amrex::Real time = start_time;
         amrex::Real timestep = start_timestep;
         bool stop_advance = false;
         for (int step_number = 0; step_number < nsteps && !stop_advance; ++step_number)
         {
             if (end_time - time < timestep) {
                 timestep = end_time - time;
                 stop_advance = true;
             }
             if (step_number > 0) {
                 std::swap(S_old, S_new);
             }
             // Call the time integrator advance
             integrator_ptr->advance(S_old, S_new, time, timestep);
             // Update our time variable
             time += timestep;
             // Call the post-timestep hook
             post_timestep();
         }
     }
map_data()
template<class T > void TimeIntegrator< T >::map_data (std::function< void(T &)> Map) inline
     {
         integrator_ptr->map_data(Map);
     }
set_post_timestep()
template<class T > void TimeIntegrator< T >::set_post_timestep (std::function< void()> F) inline
     {
         post_timestep = F;
     }
Referenced by TimeIntegrator< T >::TimeIntegrator().
set_post_update()
template<class T > void TimeIntegrator< T >::set_post_update (std::function< void(T &, amrex::Real)> F) inline
     {
         integrator_ptr->set_post_update(F);
     }
Referenced by erf_advance(), and TimeIntegrator< T >::TimeIntegrator().
set_rhs()
template<class T > void TimeIntegrator< T >::set_rhs (std::function< void(T &, const T &, const amrex::Real)> F) inline
     {
         integrator_ptr->set_rhs(F);
     }
Referenced by erf_advance(), and TimeIntegrator< T >::TimeIntegrator().
time_interpolate()
template<class T > void TimeIntegrator< T >::time_interpolate (const T & S_new, const T & S_old, amrex::Real timestep_fraction, T & data) inline
     {
         integrator_ptr->time_interpolate(S_new, S_old, timestep_fraction, data);
     }
Member Data Documentation
integrator_ptr
template<class T > std::unique_ptr<IntegratorBase<T> > TimeIntegrator< T >::integrator_ptr private
Referenced by TimeIntegrator< T >::advance(), TimeIntegrator< T >::integrate(), TimeIntegrator< T >::map_data(), TimeIntegrator< T >::set_post_update(), TimeIntegrator< T >::set_rhs(), TimeIntegrator< T >::time_interpolate(), and TimeIntegrator< T >::TimeIntegrator().
post_timestep
template<class T > std::function<void ()> TimeIntegrator< T >::post_timestep private
Referenced by TimeIntegrator< T >::integrate(), and TimeIntegrator< T >::set_post_timestep().
The documentation for this class was generated from the following file:
/home/runner/work/ERF/ERF/Source/TimeIntegration/AMReX_TimeIntegrator.H