ERF: IntegratorBase< T > Class Template Reference
IntegratorBase< T > Class Template Reference
#include <AMReX_IntegratorBase.H>
Public Member Functions
IntegratorBase ()
virtual ~IntegratorBase ()
void set_rhs (std::function< void(T &, const T &, const amrex::Real)> F)
void set_post_update (std::function< void(T &, amrex::Real)> F)
virtual amrex::Real advance (T &S_old, T &S_new, amrex::Real time, const amrex::Real timestep)
void rhs (T &S_rhs, const T &S_data, const amrex::Real time)
virtual void time_interpolate (const T &S_new, const T &S_old, amrex::Real timestep_fraction, T &data)
virtual void map_data (std::function< void(T &)> Map)
Public Attributes
amrex::Real timestep
Protected Attributes
std::function< void(T &, amrex::Real)> post_update
Private Attributes
std::function< void(T &, const T &, const amrex::Real)> Fun
Constructor & Destructor Documentation
IntegratorBase()
template<class T > IntegratorBase< T >::IntegratorBase () inline
 {}
~IntegratorBase()
template<class T > virtual IntegratorBase< T >::~IntegratorBase () inline virtual
 {}
Member Function Documentation
advance()
template<class T > virtual amrex::Real IntegratorBase< T >::advance (T & S_old, T & S_new, amrex::Real time, const amrex::Real timestep) inline virtual
Reimplemented in FEIntegrator< T >, and RKIntegrator< T >.
     {
         return timestep;
     }
map_data()
template<class T > virtual void IntegratorBase< T >::map_data (std::function< void(T &)> Map) inline virtual
Reimplemented in RKIntegrator< T >, and FEIntegrator< T >.
 {}
rhs()
template<class T > void IntegratorBase< T >::rhs (T & S_rhs, const T & S_data, const amrex::Real time) inline
     {
         Fun(S_rhs, S_data, time);
     }
set_post_update()
template<class T > void IntegratorBase< T >::set_post_update (std::function< void(T &, amrex::Real)> F) inline
     {
         post_update = F;
     }
set_rhs()
template<class T > void IntegratorBase< T >::set_rhs (std::function< void(T &, const T &, const amrex::Real)> F) inline
     {
         Fun = F;
     }
time_interpolate()
template<class T > virtual void IntegratorBase< T >::time_interpolate (const T & S_new, const T & S_old, amrex::Real timestep_fraction, T & data) inline virtual
Reimplemented in RKIntegrator< T >, and FEIntegrator< T >.
 {}
Member Data Documentation
Fun
template<class T > std::function<void(T&, const T&, const amrex::Real)> IntegratorBase< T >::Fun private
Referenced by IntegratorBase< T >::rhs(), and IntegratorBase< T >::set_rhs().
post_update
template<class T > std::function<void (T&, amrex::Real)> IntegratorBase< T >::post_update protected
Referenced by IntegratorBase< T >::set_post_update().
timestep
template<class T > amrex::Real IntegratorBase< T >::timestep
Referenced by FEIntegrator< T >::advance(), and IntegratorBase< T >::advance().
The documentation for this class was generated from the following file:
/home/runner/work/ERF/ERF/Source/TimeIntegration/AMReX_IntegratorBase.H