ERF: PhysProp Class Reference
PhysProp Class Reference
#include <ERF_Phys_prop.H>
Classes
struct physprop_t
Public Member Functions
void physprop_accum_unique_files (const std::string &filename, const std::string &type)
void physprop_init ()
int physprop_get_id (std::string filename) const
void get_sourcefile (int &id, std::string &sourcefile) const
void get_opticstype (int &id, std::string &opticstype) const
void get_sw_hygro_ext (int &id, real2d &sw_hygro_ext) const
void get_sw_hygro_ssa (int &id, real2d &sw_hygro_ssa) const
void get_sw_hygro_asm (int &id, real2d &sw_hygro_asm) const
void get_lw_hygro_abs (int &id, real2d &lw_hygro_abs) const
void get_sw_nonhygro_ext (int &id, real1d &sw_nonhygro_ext) const
void get_sw_nonhygro_ssa (int &id, real1d &sw_nonhygro_ssa) const
void get_sw_nonhygro_asm (int &id, real1d &sw_nonhygro_asm) const
void get_sw_nonhygro_scat (int &id, real1d &sw_nonhygro_scat) const
void get_sw_nonhygro_ascat (int &id, real1d &sw_nonhygro_ascat) const
void get_lw_abs (int &id, real1d &lw_abs) const
void get_ref_real_aer_sw (int &id, real1d &ref_real_aer_sw) const
void get_ref_real_aer_lw (int &id, real1d &ref_real_aer_lw) const
void get_ref_im_aer_sw (int &id, real1d &ref_im_aer_sw) const
void get_ref_im_aer_lw (int &id, real1d &ref_im_aer_lw) const
void get_r_sw_ext (int &id, real2d &r_sw_ext) const
void get_r_sw_scat (int &id, real2d &r_sw_scat) const
void get_r_sw_ascat (int &id, real2d &r_sw_ascat) const
void get_r_lw_abs (int &id, real2d &r_lw_abs) const
void get_mu (int &id, real1d &mu) const
void get_extpsw (int &id, real4d &extpsw) const
void get_abspsw (int &id, real4d &abspsw) const
void get_asmpsw (int &id, real4d &asmpsw) const
void get_absplw (int &id, real4d &absplw) const
void get_refrtabsw (int &id, real2d &refrtabsw) const
void get_refitabsw (int &id, real2d &refitabsw) const
void get_refrtablw (int &id, real2d &refrtablw) const
void get_refitablw (int &id, real2d &refitablw) const
void get_aername (int &id, std::string &aername) const
void get_density_aer (int &id, real &density_aer) const
void get_hygro_aer (int &id, real &hygro_aer) const
void get_dryrad_aer (int &id, real &dryrad_aer) const
void get_dispersion_aer (int &id, real &dispersion_aer) const
void get_num_to_mass_aer (int &id, real &num_to_mass_aer) const
void get_ncoef (int &id, int &ncoef) const
void get_prefr (int &id, int &prefr) const
void get_prefi (int &id, int &prefi) const
void get_sigmag (int &id, real &sigmag) const
void get_dgnum (int &id, real &dgnum) const
void get_dgnumlo (int &id, real &dgnumlo) const
void get_dgnumhi (int &id, real &dgnumhi) const
void get_rhcrystal (int &id, real &rhcrystal) const
void get_rhdeliques (int &id, real &rhdeliques) const
void aerosol_optics_init (physprop_t &phys_prop)
void hygro_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void zero_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void insoluble_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void volcanic_radius_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void volcanic_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void hygroscopic_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void nonhygro_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void refindex_aer_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void modal_optics_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
void bulk_props_init (physprop_t &phys_prop, yakl::SimpleNetCDF &prop)
real exp_interpol (const real1d &x, const real1d &f, const real &y)
real lin_interpol (const real1d &x, const real1d &f, const real &y)
void aer_optics_log_rh (std::string name, const real1d &ext, const real1d &ssa, const real1d &asmin)
Public Attributes
std::vector< physprop_t > physprop
std::vector< std::string > uniquefilenames
Member Function Documentation
aer_optics_log_rh()
void PhysProp::aer_optics_log_rh (std::string name, const real1d & ext, const real1d & ssa, const real1d & asmin) inline
     {
         const int nrh_test = 36;
         //int krh;
         real1d rh_test("rh_test", nrh_test);
         //auto nrh = ext.extent(0);
         parallel_for (SimpleBounds<1> (nrh_test), YAKL_LAMBDA (int krh_test)
         {
             rh_test(krh_test) = sqrt(sqrt(sqrt(sqrt(((krh_test - 1.0) / (nrh_test - 1))))));
         });
         // loop through test rh values
         parallel_for (SimpleBounds<1> (nrh_test), YAKL_LAMBDA (int krh_test)
         {
             /*
             // find corresponding rh index
             auto rh = rh_test(krh_test);
             auto krh = std::min(floor( (rh) * nrh ) + 1, static_cast<real>(nrh - 1));
             auto wrh = (rh) *nrh - krh;
             auto exti = ext(krh + 1) * (wrh + 1) - ext(krh) * wrh;
             auto ssai = ssa(krh + 1) * (wrh + 1) - ssa(krh) * wrh;
             auto asmi = asmin(krh + 1) * (wrh + 1) - asmin(krh) * wrh;
             */
         });
     }
aerosol_optics_init()
void PhysProp::aerosol_optics_init (physprop_t & phys_prop) inline
     {
         using charHost1d = FArray<char,1,yakl::memHost>;
         yakl::SimpleNetCDF prop;
         prop.open(phys_prop.sourcefile, yakl::NETCDF_MODE_READ);
         charHost1d temp;
         prop.read(temp, "opticsmethod");
         for (auto ichar = 1 ; ichar <= temp.extent(0); ichar++)
             if (!isspace(temp(ichar))) phys_prop.opticsmethod += temp(ichar);
         if(strcmp(phys_prop.opticsmethod.c_str(),"zero") == 0) {
             zero_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"hygro") == 0) {
             hygro_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"hygroscopic") == 0) {
             hygroscopic_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"nonhygro") == 0) {
             nonhygro_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"insoluble") == 0) {
             insoluble_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"volcanic_radius") == 0) {
             volcanic_radius_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"volcanic") == 0) {
             volcanic_optics_init(phys_prop, prop);
         } else if (strcmp(phys_prop.opticsmethod.c_str(),"modal") == 0) {
             modal_optics_init(phys_prop, prop);
         } else {
             amrex::Print() << "no options available\n";
         }
     }
Referenced by physprop_init().
bulk_props_init()
void PhysProp::bulk_props_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         using charHost1d = FArray<char,1,yakl::memHost>;
         charHost1d temp;
         prop.read(temp, "name");
         phys_prop.aername = "";
         for (auto ichar = 1 ; ichar <= temp.extent(0); ichar++)
             if (!isspace(temp(ichar))) phys_prop.aername += temp(ichar);
         //  Read props for bulk aerosols
         prop.read( phys_prop.density_aer,       "density" );
         prop.read( phys_prop.dispersion_aer,    "sigma_logr" );
         prop.read( phys_prop.dryrad_aer,        "dryrad" );
         prop.read( phys_prop.hygro_aer,         "hygroscopicity" );
         prop.read( phys_prop.num_to_mass_aer,   "num_to_mass_ratio" );
     }
Referenced by hygro_optics_init(), hygroscopic_optics_init(), insoluble_optics_init(), nonhygro_optics_init(), volcanic_optics_init(), and volcanic_radius_optics_init().
exp_interpol()
real PhysProp::exp_interpol (const real1d & x, const real1d & f, const real & y) inline
     {
         auto n = x.extent(0);
         int k;
         // find k such that x(k) < y =< x(k+1)
         // set k = 1 if y <= x(1)  and  k = n-1 if y > x(n)
         if (y <= x(1)) {
             k = 1;
         }
         else if (y >= x(n)) {
             k = n - 1;
         }
         else {
             k = 1;
             while (y > x(k+1) && k < n) {
                 k = k + 1;
             }
         }
         // interpolate
         auto a = (log(f(k+1)/f(k)))/(x(k+1)-x(k));
         return f(k)*exp(a*(y-x(k)));
     }
Referenced by hygro_optics_init(), and hygroscopic_optics_init().
get_absplw()
void PhysProp::get_absplw (int & id, real4d & absplw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_absplw: illegal ID value %d\n", id);
         absplw = physprop[id].absplw;
     }
Referenced by MamConstituents::get_mode_props().
get_abspsw()
void PhysProp::get_abspsw (int & id, real4d & abspsw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_abspsw: illegal ID value %d\n", id);
         abspsw = physprop[id].abspsw;
     }
Referenced by MamConstituents::get_mode_props().
get_aername()
void PhysProp::get_aername (int & id, std::string & aername) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_aername: illegal ID value %d\n", id);
         aername = physprop[id].aername;
     }
Referenced by MamConstituents::get_aername().
get_asmpsw()
void PhysProp::get_asmpsw (int & id, real4d & asmpsw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_asmpsw: illegal ID value %d\n", id);
         asmpsw = physprop[id].asmpsw;
     }
Referenced by MamConstituents::get_mode_props().
get_density_aer()
void PhysProp::get_density_aer (int & id, real & density_aer) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_density_aer: illegal ID value %d\n", id);
         density_aer = physprop[id].density_aer;
     }
Referenced by MamConstituents::get_density_aer(), MamConstituents::get_mam_density_aer(), MamConstituents::get_mam_props(), MamConstituents::get_mam_props_lw(), and MamConstituents::get_mam_props_sw().
get_dgnum()
void PhysProp::get_dgnum (int & id, real & dgnum) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_dgnum: illegal ID value %d\n", id);
         dgnum = physprop[id].dgnum;
     }
Referenced by MamConstituents::get_mode_props().
get_dgnumhi()
void PhysProp::get_dgnumhi (int & id, real & dgnumhi) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_dgnumhi: illegal ID value %d\n", id);
         dgnumhi = physprop[id].dgnumhi;
     }
Referenced by MamConstituents::get_mode_props().
get_dgnumlo()
void PhysProp::get_dgnumlo (int & id, real & dgnumlo) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_dgnumlo: illegal ID value %d\n", id);
         dgnumlo = physprop[id].dgnumlo;
     }
Referenced by MamConstituents::get_mode_props().
get_dispersion_aer()
void PhysProp::get_dispersion_aer (int & id, real & dispersion_aer) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_dispersion_aer: illegal ID value %d\n", id);
         dispersion_aer = physprop[id].dispersion_aer;
     }
Referenced by MamConstituents::get_dispersion_aer().
get_dryrad_aer()
void PhysProp::get_dryrad_aer (int & id, real & dryrad_aer) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_dryrad_aer: illegal ID value %d\n", id);
         dryrad_aer = physprop[id].dryrad_aer;
     }
Referenced by MamConstituents::get_dryrad_aer().
get_extpsw()
void PhysProp::get_extpsw (int & id, real4d & extpsw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_expsw: illegal ID value %d\n", id);
         extpsw = physprop[id].extpsw;
     }
Referenced by MamConstituents::get_mode_props().
get_hygro_aer()
void PhysProp::get_hygro_aer (int & id, real & hygro_aer) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_hygro_aer: illegal ID value %d\n", id);
         hygro_aer = physprop[id].hygro_aer;
     }
Referenced by MamConstituents::get_hygro_aer(), MamConstituents::get_mam_hygro_aer(), and MamConstituents::get_mam_props().
get_lw_abs()
void PhysProp::get_lw_abs (int & id, real1d & lw_abs) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_lw_abs: illegal ID value %d\n", id);
         lw_abs = physprop[id].lw_abs;
     }
Referenced by MamConstituents::get_aer_lw_abs().
get_lw_hygro_abs()
void PhysProp::get_lw_hygro_abs (int & id, real2d & lw_hygro_abs) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_lw_hygro_abs: illegal ID value %d\n", id);
         lw_hygro_abs = physprop[id].lw_hygro_abs;
     }
Referenced by MamConstituents::get_aer_lw_hygro_abs().
get_mu()
void PhysProp::get_mu (int & id, real1d & mu) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_mu: illegal ID value %d\n", id);
         mu = physprop[id].mu;
     }
Referenced by MamConstituents::get_aer_mu().
get_ncoef()
void PhysProp::get_ncoef (int & id, int & ncoef) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_ncoef: illegal ID value %d\n", id);
         ncoef = physprop[id].ncoef;
     }
Referenced by MamConstituents::get_mode_props().
get_num_to_mass_aer()
void PhysProp::get_num_to_mass_aer (int & id, real & num_to_mass_aer) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_num_to_mass_aer: illegal ID value %d\n", id);
         num_to_mass_aer = physprop[id].num_to_mass_aer;
     }
Referenced by MamConstituents::get_num_to_mass_aer().
get_opticstype()
void PhysProp::get_opticstype (int & id, std::string & opticstype) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_opticstype: illegal ID value %d\n", id);
         opticstype  = physprop[id].opticsmethod;
     }
Referenced by MamConstituents::get_aer_opticstype().
get_prefi()
void PhysProp::get_prefi (int & id, int & prefi) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_prefi: illegal ID value %d\n", id);
         prefi = physprop[id].prefi;
     }
Referenced by MamConstituents::get_mode_props().
get_prefr()
void PhysProp::get_prefr (int & id, int & prefr) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_prefr: illegal ID value %d\n", id);
         prefr = physprop[id].prefr;
     }
Referenced by MamConstituents::get_mode_props().
get_r_lw_abs()
void PhysProp::get_r_lw_abs (int & id, real2d & r_lw_abs) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_r_lw_abs: illegal ID value %d\n", id);
         r_lw_abs = physprop[id].r_lw_abs;
     }
Referenced by MamConstituents::get_aer_r_lw_abs().
get_r_sw_ascat()
void PhysProp::get_r_sw_ascat (int & id, real2d & r_sw_ascat) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_r_sw_ascat: illegal ID value %d\n", id);
         r_sw_ascat = physprop[id].r_sw_ascat;
     }
Referenced by MamConstituents::get_aer_r_sw_ascat().
get_r_sw_ext()
void PhysProp::get_r_sw_ext (int & id, real2d & r_sw_ext) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_r_sw_ext: illegal ID value %d\n", id);
         r_sw_ext = physprop[id].r_sw_ext;
     }
Referenced by MamConstituents::get_aer_r_sw_ext().
get_r_sw_scat()
void PhysProp::get_r_sw_scat (int & id, real2d & r_sw_scat) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_r_sw_scat: illegal ID value %d\n", id);
         r_sw_scat = physprop[id].r_sw_scat;
     }
Referenced by MamConstituents::get_aer_r_sw_scat().
get_ref_im_aer_lw()
void PhysProp::get_ref_im_aer_lw (int & id, real1d & ref_im_aer_lw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_ref_im_aer_lw: illegal ID value %d\n", id);
         ref_im_aer_lw = physprop[id].refindex_im_aer_lw;
     }
Referenced by MamConstituents::get_aer_refindex_aer_lw(), and MamConstituents::get_mam_props_lw().
get_ref_im_aer_sw()
void PhysProp::get_ref_im_aer_sw (int & id, real1d & ref_im_aer_sw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_ref_im_aer_sw: illegal ID value %d\n", id);
         ref_im_aer_sw = physprop[id].refindex_im_aer_sw;
     }
Referenced by MamConstituents::get_aer_refindex_aer_sw(), MamConstituents::get_mam_props(), and MamConstituents::get_mam_props_sw().
get_ref_real_aer_lw()
void PhysProp::get_ref_real_aer_lw (int & id, real1d & ref_real_aer_lw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_ref_real_aer_lw: illegal ID value %d\n", id);
         ref_real_aer_lw = physprop[id].refindex_real_aer_lw;
     }
Referenced by MamConstituents::get_aer_refindex_aer_lw(), and MamConstituents::get_mam_props_lw().
get_ref_real_aer_sw()
void PhysProp::get_ref_real_aer_sw (int & id, real1d & ref_real_aer_sw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_ref_real_aer_sw: illegal ID value %d\n", id);
         ref_real_aer_sw = physprop[id].refindex_real_aer_sw;
     }
Referenced by MamConstituents::get_aer_refindex_aer_sw(), MamConstituents::get_mam_props(), and MamConstituents::get_mam_props_sw().
get_refitablw()
void PhysProp::get_refitablw (int & id, real2d & refitablw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("ger_refitablw: illegal ID value %d\n", id);
         refitablw = physprop[id].refitablw;
     }
Referenced by MamConstituents::get_mode_props().
get_refitabsw()
void PhysProp::get_refitabsw (int & id, real2d & refitabsw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_refitabsw: illegal ID value %d\n", id);
         refitabsw = physprop[id].refitabsw;
     }
Referenced by MamConstituents::get_mode_props().
get_refrtablw()
void PhysProp::get_refrtablw (int & id, real2d & refrtablw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_refrtablw: illegal ID value %d\n", id);
         refrtablw = physprop[id].refrtablw;
     }
Referenced by MamConstituents::get_mode_props().
get_refrtabsw()
void PhysProp::get_refrtabsw (int & id, real2d & refrtabsw) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_refrtabsw: illegal ID value %d\n", id);
         refrtabsw = physprop[id].refrtabsw;
     }
Referenced by MamConstituents::get_mode_props().
get_rhcrystal()
void PhysProp::get_rhcrystal (int & id, real & rhcrystal) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_rhcrystal: illegal ID value %d\n", id);
         rhcrystal = physprop[id].rhcrystal;
     }
Referenced by MamConstituents::get_mode_props().
get_rhdeliques()
void PhysProp::get_rhdeliques (int & id, real & rhdeliques) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_rhdeliques: illegal ID value %d\n", id);
         rhdeliques = physprop[id].rhdeliques;
     }
Referenced by MamConstituents::get_mode_props().
get_sigmag()
void PhysProp::get_sigmag (int & id, real & sigmag) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sigmag: illegal ID value %d\n", id);
         sigmag = physprop[id].sigmag;
     }
Referenced by MamConstituents::get_mode_props().
get_sourcefile()
void PhysProp::get_sourcefile (int & id, std::string & sourcefile) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sourcefile: illegal ID value %d\n", id);
         sourcefile = physprop[id].sourcefile;
     }
get_sw_hygro_asm()
void PhysProp::get_sw_hygro_asm (int & id, real2d & sw_hygro_asm) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_hygro_asm: illegal ID value %d\n", id);
         sw_hygro_asm = physprop[id].sw_hygro_asm;
     }
Referenced by MamConstituents::get_aer_sw_hygro_asm().
get_sw_hygro_ext()
void PhysProp::get_sw_hygro_ext (int & id, real2d & sw_hygro_ext) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_hygro_ext: illegal ID value %d\n", id);
         sw_hygro_ext = physprop[id].sw_hygro_ext;
     }
Referenced by MamConstituents::get_aer_sw_hygro_ext().
get_sw_hygro_ssa()
void PhysProp::get_sw_hygro_ssa (int & id, real2d & sw_hygro_ssa) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_hygro_ssa: illegal ID value %d\n", id);
         sw_hygro_ssa = physprop[id].sw_hygro_ssa;
     }
Referenced by MamConstituents::get_aer_sw_hygro_ssa().
get_sw_nonhygro_ascat()
void PhysProp::get_sw_nonhygro_ascat (int & id, real1d & sw_nonhygro_ascat) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_nonhygro_ascat: illegal ID value %d\n", id);
         sw_nonhygro_ascat = physprop[id].sw_nonhygro_ascat;
     }
Referenced by MamConstituents::get_aer_sw_nonhygro_ascat().
get_sw_nonhygro_asm()
void PhysProp::get_sw_nonhygro_asm (int & id, real1d & sw_nonhygro_asm) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_nonhygro_asm: illegal ID value %d\n", id);
         sw_nonhygro_asm = physprop[id].sw_nonhygro_asm;
     }
Referenced by MamConstituents::get_aer_sw_nonhygro_asm().
get_sw_nonhygro_ext()
void PhysProp::get_sw_nonhygro_ext (int & id, real1d & sw_nonhygro_ext) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_nonhygro_ext: illegal ID value %d\n", id);
         sw_nonhygro_ext = physprop[id].sw_nonhygro_ext;
     }
Referenced by MamConstituents::get_aer_sw_nonhygro_ext().
get_sw_nonhygro_scat()
void PhysProp::get_sw_nonhygro_scat (int & id, real1d & sw_nonhygro_scat) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_nonhygro_scat: illegal ID value %d\n", id);
         sw_nonhygro_scat = physprop[id].sw_nonhygro_scat;
     }
Referenced by MamConstituents::get_aer_sw_nonhygro_scat().
get_sw_nonhygro_ssa()
void PhysProp::get_sw_nonhygro_ssa (int & id, real1d & sw_nonhygro_ssa) const inline
     {
         if (id < 0 || id > physprop.size())
             printf("get_sw_nonhygro_ssa: illegal ID value %d\n", id);
         sw_nonhygro_ssa = physprop[id].sw_nonhygro_ssa;
     }
Referenced by MamConstituents::get_aer_sw_nonhygro_ssa().
hygro_optics_init()
void PhysProp::hygro_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         real1d frh;
         real2d fsw_ext;
         real2d fsw_ssa;
         real2d fsw_asm;
         real2d flw_abs;
         auto nrh       = RadConstants::nrh;
         //auto nbnd      = prop.getDimSize( "lw_band" );
         auto nswbands  = prop.getDimSize( "sw_band" );
         prop.read( fsw_ext, "ext_sw");
         prop.read( fsw_ssa, "ssa_sw");
         prop.read( fsw_asm, "asm_sw");
         prop.read( flw_abs, "abs_lw");
         prop.read( frh,         "rh");
         real1d fswe("fswe",nrh),
             fsws("fsws",nrh),
             fswa("fswa",nrh);
         // interpolate onto cam's rh mesh
         for(auto kbnd = 0; kbnd < nswbands; ++kbnd) {
             for(auto krh = 0; krh < nrh; ++krh) {
                 fswe(krh) = fsw_ext(krh,kbnd)/fsw_ext(1,kbnd);
                 fsws(krh) = fsw_ssa(krh,kbnd)/fsw_ssa(1,kbnd);
                 fswa(krh) = fsw_asm(krh,kbnd)/fsw_asm(1,kbnd);
             }
             // interpolation
             for(auto krh = 0; krh < nrh; ++krh) {
                 auto rh = 1.0/nrh*(krh-1);
                 phys_prop.sw_hygro_ext(krh,kbnd) = exp_interpol(frh,fswe,rh)*fsw_ext(1,kbnd);
                 phys_prop.sw_hygro_ssa(krh,kbnd) = lin_interpol(frh,fsws,rh)*fsw_ssa(1,kbnd);
                 phys_prop.sw_hygro_asm(krh,kbnd) = lin_interpol(frh,fswa,rh)*fsw_asm(1,kbnd);
             }
         }
         // read refractive index data if available
         refindex_aer_init(phys_prop, prop);
         // read bulk aero props
         bulk_props_init(phys_prop, prop);
     }
Referenced by aerosol_optics_init().
hygroscopic_optics_init()
void PhysProp::hygroscopic_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         // temp data from hygroscopic file before interpolation onto cam-rh-mesh
         //int nfilerh; // number of rh values in file
         real1d frh;
         real2d fsw_ext, fsw_ssa, fsw_asm, flw_abs;
         auto nrh      = RadConstants::nrh;
         auto nlwbands = prop.getDimSize( "lw_band" );
         auto nswbands = prop.getDimSize( "sw_band" );
         phys_prop.sw_hygro_ext = real2d("sw_hygro_ext",nrh,nswbands);
         phys_prop.sw_hygro_ssa = real2d("sw_hygro_ssa",nrh,nswbands);
         phys_prop.sw_hygro_asm = real2d("sw_hygro_asm",nrh,nswbands);
         phys_prop.lw_hygro_abs = real2d("lw_hygro_abs",nrh,nlwbands);
         prop.read( fsw_ext, "ext_sw");
         prop.read( fsw_ssa, "ssa_sw");
         prop.read( fsw_asm, "asm_sw");
         prop.read( flw_abs, "abs_lw");
         prop.read( frh,     "rh");
         real1d fswe("",nrh), fsws("",nrh),
                fswa("",nrh), flwa("",nrh);
         // interpolate onto cam's rh mesh
         parallel_for (SimpleBounds<2> (nswbands, nrh), YAKL_LAMBDA (int kbnd, int krh)
         {
             fswe(krh) = fsw_ext(krh,kbnd) / fsw_ext(1,kbnd);
             fsws(krh) = fsw_ssa(krh,kbnd) / fsw_ssa(1,kbnd);
             fswa(krh) = fsw_asm(krh,kbnd) / fsw_asm(1,kbnd);
         });
         parallel_for (SimpleBounds<2> (nswbands, nrh), YAKL_LAMBDA (int kbnd, int krh)
         {
             auto rh = 1.0 / nrh * (krh - 1);
             phys_prop.sw_hygro_ext(krh,kbnd) = exp_interpol( frh, fswe, rh ) * fsw_ext(1, kbnd);
             phys_prop.sw_hygro_ssa(krh,kbnd) = lin_interpol( frh, fswe, rh ) * fsw_ssa(1, kbnd);
             phys_prop.sw_hygro_asm(krh,kbnd) = lin_interpol( frh, fswa, rh ) * fsw_asm(1, kbnd);
         });
         // interpolate long wave
         parallel_for (SimpleBounds<2> (nlwbands, nrh), YAKL_LAMBDA (int kbnd, int krh)
         {
             flwa(krh) = flw_abs(krh,kbnd) / flw_abs(1,kbnd);
         });
         parallel_for (SimpleBounds<2> (nlwbands, nrh), YAKL_LAMBDA (int kbnd, int krh)
         {
             auto rh = 1.0 / nrh * (krh - 1);
             phys_prop.lw_hygro_abs(krh,kbnd) = exp_interpol( frh, flwa, rh ) * flw_abs(1, kbnd);
         });
         // read refractive index data if available
         refindex_aer_init(phys_prop, prop);
         // bulk aero props
         bulk_props_init(phys_prop, prop);
     }
Referenced by aerosol_optics_init().
insoluble_optics_init()
void PhysProp::insoluble_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         auto nbnd      = prop.getDimSize( "lw_band" );
         auto nswbands  = prop.getDimSize( "sw_band" );
         realHost2d ext_sw, ssa_sw, asm_sw, abs_lw;
         phys_prop.sw_nonhygro_ext = real1d("sw_nonhygro_ext", nswbands);
         phys_prop.sw_nonhygro_ssa = real1d("sw_nonhygro_ssa", nswbands);
         phys_prop.sw_nonhygro_asm = real1d("sw_nonhygro_asm", nswbands);
         phys_prop.lw_abs          = real1d("lw_abs", nbnd);
         prop.read( ext_sw, "ext_sw");
         prop.read( ssa_sw, "ssa_sw");
         prop.read( asm_sw, "asm_sw");
         prop.read( abs_lw, "abs_lw");
       parallel_for (SimpleBounds<1>(nswbands), YAKL_LAMBDA (int i)
       {
           phys_prop.sw_nonhygro_ext(i) = ext_sw(i,1);
           phys_prop.sw_nonhygro_ssa(i) = ssa_sw(i,1);
           phys_prop.sw_nonhygro_asm(i) = asm_sw(i,1);
       });
       parallel_for (SimpleBounds<1>(nbnd), YAKL_LAMBDA (int i)
       {
           phys_prop.lw_abs(i) = abs_lw(i,1);
       });
       // read refractive index data if available
       refindex_aer_init(phys_prop, prop);
       // read bulk aero props
       bulk_props_init(phys_prop, prop);
     }
Referenced by aerosol_optics_init().
lin_interpol()
real PhysProp::lin_interpol (const real1d & x, const real1d & f, const real & y) inline
     {
         auto n = x.extent(0);
         int k;
         // find k such that x(k) < y =< x(k+1)
         // set k = 1 if y <= x(1)  and  k = n-1 if y > x(n)
         if (y <= x(1)) {
             k = 1;
         }
         else if (y >= x(n)) {
             k = n - 1;
         }
         else {
             k = 1;
             while (y > x(k+1) && k < n) {
                 k = k + 1;
             }
         }
         // interpolate
         auto a = (f(k+1)-f(k))/(x(k+1)-x(k));
         return f(k)+a*(y-x(k));
     }
Referenced by hygro_optics_init(), and hygroscopic_optics_init().
modal_optics_init()
void PhysProp::modal_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         // NOTE: Definitions for real arrays come from rrtmgp_const.h
         //       and they default to styleFortran ordering.
         realHost5d extpsw, abspsw, asmpsw, absplw;
         auto nlwbnd = prop.getDimSize( "lw_band" );
         auto nswbnd = prop.getDimSize( "sw_band" );
         auto ncoef  = prop.getDimSize( "coef_number" );
         auto prefr  = prop.getDimSize( "refindex_real" );
         auto prefi  = prop.getDimSize( "refindex_im" );
         phys_prop.ncoef = ncoef;
         phys_prop.prefr = prefr;
         phys_prop.prefi = prefi;
         prop.read(extpsw, "extpsw" );
         prop.read(abspsw, "abspsw" );
         prop.read(asmpsw, "asmpsw" );
         prop.read(absplw, "absplw" );
         // styleFortran ordering to be consistent with realHost5d definition
         phys_prop.extpsw = real4d("extpsw", ncoef, prefr, prefi, nswbnd);
         phys_prop.abspsw = real4d("abspsw", ncoef, prefr, prefi, nswbnd);
         phys_prop.asmpsw = real4d("asmpsw", ncoef, prefr, prefi, nswbnd);
         phys_prop.absplw = real4d("absplw", ncoef, prefr, prefi, nswbnd);
         parallel_for (SimpleBounds<4>(nswbnd, prefr, prefi, ncoef),
                       YAKL_LAMBDA (int i, int j, int k, int l)
         {
             phys_prop.extpsw(i,j,k,l) = extpsw(i,j,k,1,l);
             phys_prop.abspsw(i,j,k,l) = abspsw(i,j,k,1,l);
             phys_prop.asmpsw(i,j,k,l) = asmpsw(i,j,k,1,l);
         });
         parallel_for (SimpleBounds<4>(nlwbnd, prefr, prefi, ncoef),
                       YAKL_LAMBDA (int i, int j, int k, int l)
         {
             phys_prop.absplw(i,j,k,l) = absplw(i,j,k,1,l);
         });
         prop.read(phys_prop.refrtabsw,   "refindex_real_sw" );
         prop.read(phys_prop.refitabsw,   "refindex_im_sw" );
         prop.read(phys_prop.refrtablw,   "refindex_real_lw" );
         prop.read(phys_prop.refitablw,   "refindex_im_lw" );
         prop.read(phys_prop.sigmag,      "sigmag" );
         prop.read(phys_prop.dgnum,       "dgnum" );
         prop.read(phys_prop.dgnumlo,     "dgnumlo" );
         prop.read(phys_prop.dgnumhi,     "dgnumhi" );
         prop.read(phys_prop.rhcrystal,   "rhcrystal" );
         prop.read(phys_prop.rhdeliques,  "rhdeliques" );
     }
Referenced by aerosol_optics_init().
nonhygro_optics_init()
void PhysProp::nonhygro_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         //auto nlwbands = prop.getDimSize( "lw_band" );
         //auto nswbands = prop.getDimSize( "sw_band" );
         prop.read( phys_prop.sw_nonhygro_ext, "ext_sw");
         prop.read( phys_prop.sw_nonhygro_ssa, "ssa_sw");
         prop.read( phys_prop.sw_nonhygro_asm, "asm_sw");
         prop.read( phys_prop.lw_abs,          "abs_lw");
         // read refractive index data if available
         refindex_aer_init(phys_prop, prop);
         // read bulk aero props
         bulk_props_init(phys_prop, prop);
     }
Referenced by aerosol_optics_init().
physprop_accum_unique_files()
void PhysProp::physprop_accum_unique_files (const std::string & filename, const std::string & type) inline
     {
         // Count number of aerosols in input radname array.  Aerosols are identified
         // as strings with a ".nc" suffix.
         // Construct a cumulative list of unique filenames containing physical property data.
         // check if filename is either a bulk aerosol or a mode
         if (type == "A" || type == "M") {
             // check if this filename has been used by another aerosol.  If not
             // then add it to the list of unique names.
             if (physprop_get_id(filename) < 0)
                 uniquefilenames.push_back(filename);
         }
     }
Referenced by MamConstituents::MamConstituents().
physprop_get_id()
int PhysProp::physprop_get_id (std::string filename) const inline
     {
         auto physprop_id = -1;
         auto numphysprops = uniquefilenames.size();
         for(auto iphysprop = 0; iphysprop < numphysprops; ++iphysprop) {
             if(uniquefilenames[iphysprop] == filename) {
                 physprop_id = iphysprop;
                 break;
             }
         }
         return physprop_id;
     }
Referenced by MamConstituents::init_mode_comps(), physprop_accum_unique_files(), and MamConstituents::rad_cnst_init().
physprop_init()
void PhysProp::physprop_init () inline
     {
         int numphysprops = uniquefilenames.size();
         physprop.resize(numphysprops);
         for(auto fileindex = 0; fileindex < numphysprops; ++fileindex) {
             physprop[fileindex].sourcefile = uniquefilenames[fileindex];
             aerosol_optics_init(physprop[fileindex]);
         }
     }
Referenced by MamConstituents::rad_cnst_init().
refindex_aer_init()
void PhysProp::refindex_aer_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         prop.read(phys_prop.refindex_real_aer_sw, "refindex_real_aer_sw");
         prop.read(phys_prop.refindex_im_aer_sw, "refindex_im_aer_sw");
         prop.read(phys_prop.refindex_real_aer_lw, "refindex_real_aer_lw");
         prop.read(phys_prop.refindex_im_aer_lw, "refindex_im_aer_lw");
     }
Referenced by hygro_optics_init(), hygroscopic_optics_init(), insoluble_optics_init(), and nonhygro_optics_init().
volcanic_optics_init()
void PhysProp::volcanic_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         //auto nbnd     = prop.getDimSize( "lw_band" );
         //auto nswbands = prop.getDimSize( "sw_band" );
         prop.read( phys_prop.sw_nonhygro_ext,   "bext_sw");
         prop.read( phys_prop.sw_nonhygro_scat,  "bsca_sw");
         prop.read( phys_prop.sw_nonhygro_ascat, "basc_sw");
         prop.read( phys_prop.lw_abs,            "babs_lw");
         // read bulk aero props
         bulk_props_init(phys_prop, prop);
     }
Referenced by aerosol_optics_init().
volcanic_radius_optics_init()
void PhysProp::volcanic_radius_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         //auto n_mu_samples = prop.getDimSize( "mu_samples" );
         //auto nbnd         = prop.getDimSize( "lw_band" );
         //auto nswbands     = prop.getDimSize( "sw_band" );
         prop.read( phys_prop.r_sw_ext,   "bext_sw");
         prop.read( phys_prop.r_sw_scat,  "bsca_sw");
         prop.read( phys_prop.r_sw_ascat, "basc_sw");
         prop.read( phys_prop.r_lw_abs,   "babs_lw");
         prop.read( phys_prop.mu,         "mu_samples");
         // read bulk aero props
         bulk_props_init(phys_prop, prop);
     }
Referenced by aerosol_optics_init().
zero_optics_init()
void PhysProp::zero_optics_init (physprop_t & phys_prop, yakl::SimpleNetCDF & prop) inline
     {
         auto nlwbands  = prop.getDimSize( "lw_band" );
         auto nswbands  = prop.getDimSize( "sw_band" );
         // perhaps this doesn't even need allocated.
         phys_prop.sw_nonhygro_ext = real1d("sw_nonhygro_ext", nswbands);
         phys_prop.sw_nonhygro_ssa = real1d("sw_nonhygro_ssa", nswbands);
         phys_prop.sw_nonhygro_asm = real1d("sw_nonhygro_asm", nswbands);
         phys_prop.lw_abs          = real1d("lwabs", nlwbands);
         yakl::memset(phys_prop.sw_nonhygro_ext, 0.);
         yakl::memset(phys_prop.sw_nonhygro_ssa, 0.);
         yakl::memset(phys_prop.sw_nonhygro_asm, 0.);
         yakl::memset(phys_prop.lw_abs, 0.);
     }
Referenced by aerosol_optics_init().
Member Data Documentation
physprop
std::vector<physprop_t> PhysProp::physprop
Referenced by get_absplw(), get_abspsw(), get_aername(), get_asmpsw(), get_density_aer(), get_dgnum(), get_dgnumhi(), get_dgnumlo(), get_dispersion_aer(), get_dryrad_aer(), get_extpsw(), get_hygro_aer(), get_lw_abs(), get_lw_hygro_abs(), get_mu(), get_ncoef(), get_num_to_mass_aer(), get_opticstype(), get_prefi(), get_prefr(), get_r_lw_abs(), get_r_sw_ascat(), get_r_sw_ext(), get_r_sw_scat(), get_ref_im_aer_lw(), get_ref_im_aer_sw(), get_ref_real_aer_lw(), get_ref_real_aer_sw(), get_refitablw(), get_refitabsw(), get_refrtablw(), get_refrtabsw(), get_rhcrystal(), get_rhdeliques(), get_sigmag(), get_sourcefile(), get_sw_hygro_asm(), get_sw_hygro_ext(), get_sw_hygro_ssa(), get_sw_nonhygro_ascat(), get_sw_nonhygro_asm(), get_sw_nonhygro_ext(), get_sw_nonhygro_scat(), get_sw_nonhygro_ssa(), and physprop_init().
uniquefilenames
std::vector<std::string> PhysProp::uniquefilenames
Referenced by physprop_accum_unique_files(), physprop_get_id(), and physprop_init().
The documentation for this class was generated from the following file:
Source/Radiation/ERF_Phys_prop.H