ERF: WaterVaporSat Class Reference
WaterVaporSat Class Reference
#include <Water_vapor_saturation.H>
Static Public Member Functions
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real svp_water (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real svp_ice (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real svp_trans (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real tq_enthalpy (const amrex::Real &t, const amrex::Real &q, const amrex::Real &hltalt)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void no_ip_hltalt (const amrex::Real &t, amrex::Real &hltalt)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void calc_hltalt (const amrex::Real &t, amrex::Real &hltalt, amrex::Real *tterm=nullptr)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void deriv_outputs (const amrex::Real &t, const amrex::Real &p, const amrex::Real &es, const amrex::Real &qs, const amrex::Real &hltalt, const amrex::Real &tterm, amrex::Real &gam, amrex::Real &dqsdt)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void qsat (const amrex::Real &t, const amrex::Real &p, amrex::Real &es, amrex::Real &qs, amrex::Real *gam=nullptr, amrex::Real *dqsdt=nullptr, amrex::Real *enthalpy=nullptr)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void qsat_water (const amrex::Real &t, const amrex::Real &p, amrex::Real &es, amrex::Real &qs, amrex::Real *gam=nullptr, amrex::Real *dqsdt=nullptr, amrex::Real *enthalpy=nullptr)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void qsat_ice (const amrex::Real &t, const amrex::Real &p, amrex::Real &es, amrex::Real &qs, amrex::Real &gam, amrex::Real &dqsdt, amrex::Real &enthalpy)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void findsp (const amrex::Real &q, const amrex::Real &t, const amrex::Real &p, const bool &use_ice, amrex::Real &tsp, amrex::Real &qsp, int &status)
Static Public Attributes
static constexpr amrex::Real tmin = 127.16
static constexpr amrex::Real tmax = 375.16
static constexpr int npcf = 5
static constexpr const amrex::Real pcf [npcf]
Member Function Documentation
calc_hltalt()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::calc_hltalt (const amrex::Real & t, amrex::Real & hltalt, amrex::Real * tterm = nullptr) inline static
{
         amrex::Real tc, weight;
         no_ip_hltalt(t, hltalt);
         if (t < tmelt) {
             // Weighting of hlat accounts for transition from water to ice.
             tc = t - tmelt;
             if (tc >= -ttrice) {
                 weight = -tc/ttrice;
                 // polynomial expression approximates difference between es
                 // over water and es over ice from 0 to -ttrice (C) (max of
                 // ttrice is 40): required for accurate estimate of es
                 // derivative in transition range from ice to water
                 if (tterm)
                 {
                     for(auto i = npcf-1; i > 0;  --i) *tterm = pcf[i] + tc*(*tterm);
                     *tterm = *tterm/ttrice;
                 }
             }
             else {
                 weight = 1.0;
             }
             hltalt = hltalt + weight*lat_ice;
         }
     }
Referenced by findsp(), and qsat().
deriv_outputs()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::deriv_outputs (const amrex::Real & t, const amrex::Real & p, const amrex::Real & es, const amrex::Real & qs, const amrex::Real & hltalt, const amrex::Real & tterm, amrex::Real & gam, amrex::Real & dqsdt) inline static
{
         // Local variables
         amrex::Real desdt;        // d(es)/dt
         amrex::Real dqsdt_loc;    // local copy of dqsdt
         if (qs == 1.0) {
             dqsdt_loc = 0.;
         }
         else {
             desdt = hltalt*es/(R_v*t*t) + tterm;
             dqsdt_loc = qs*p*desdt/(es*(p-omeps*es));
         }
         dqsdt = dqsdt_loc;
         gam   = dqsdt_loc * (hltalt/Cp_d);
     }
Referenced by qsat(), qsat_ice(), and qsat_water().
findsp()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::findsp (const amrex::Real & q, const amrex::Real & t, const amrex::Real & p, const bool & use_ice, amrex::Real & tsp, amrex::Real & qsp, int & status) inline static
{
         //
         // local variables
         //
         int iter = 8;    // max number of times to iterate the calculation
         amrex::Real es;                   // sat. vapor pressure
         amrex::Real gam;                  // change in sat spec. hum. wrt temperature (times hltalt/cpair)
         amrex::Real dgdt;                 // work variable
         amrex::Real g;                    // work variable
         amrex::Real hltalt;               // lat. heat. of vap.
         amrex::Real qs;                   // spec. hum. of water vapor
         // work variables
         amrex::Real t1, q1, dt, dq;
         amrex::Real qvd;
         amrex::Real r1b, c1, c2, c3;
         constexpr amrex::Real dttol = 1.e-4; // the relative temp error tolerance required to quit the iteration
         constexpr amrex::Real dqtol = 1.e-4; // the relative moisture error tolerance required to quit the iteration
         amrex::Real enin, enout;
         c3 = 287.04*(7.5*log(10.))/Cp_d;
         // Saturation specific humidity at this temperature
         if (use_ice) {
             qsat(t, p, es, qs);
         }
         else {
             qsat_water(t, p, es, qs);
         }
         // make sure a meaningful calculation is possible
         if (p <= 5.*es || qs <= 0. || qs >= 0.5 || t < tmin || t > tmax) {
             status = 1;
             // Keep initial parameters when conditions aren't suitable
             tsp = t;
             qsp = q;
             enin = 1.;
             enout = 1.;
             return;
         }
         // Prepare to iterate
         status = 2;
         // Get initial enthalpy
         if (use_ice)
             calc_hltalt(t,hltalt);
         else
             no_ip_hltalt(t,hltalt);
         enin = tq_enthalpy(t, q, hltalt);
         // make a guess at the wet bulb temp using a UKMO algorithm (from J. Petch)
         c1 = hltalt*c3;
         c2 = std::pow(t + 36., 2);
         r1b = c2/(c2 + c1*qs);
         qvd = r1b * (q - qs);
         tsp = t + ((hltalt/Cp_d)*qvd);
         // Generate qsp, gam, and enout from tsp.
         if (use_ice)
             qsat(tsp, p, es, qsp, &gam, &enout);
         else
             qsat_water(tsp, p, es, qsp, &gam, &enout);
         // iterate on first guess
         for(auto l = 1; l < iter; ++l) {
             g = enin - enout;
             dgdt = -Cp_d * (1 + gam);
             // New tsp
             t1 = tsp - g/dgdt;
             dt = abs(t1 - tsp)/t1;
             tsp = t1;
             // bail out if past end of temperature range
             if ( tsp < tmin ) {
                 tsp = tmin;
                 // Get latent heat and set qsp to a value
                 // that preserves enthalpy.
                 if (use_ice)
                     calc_hltalt(tsp,hltalt);
                 else
                     no_ip_hltalt(tsp,hltalt);
                 qsp = (enin - Cp_d*tsp)/hltalt;
                 enout = tq_enthalpy(tsp, qsp, hltalt);
                 status = 4;
                 break;
             }
             // Re-generate qsp, gam, and enout from new tsp.
             if (use_ice)
                 qsat(tsp, p, es, q1, &gam, &enout);
             else
                 qsat_water(tsp, p, es, q1, &gam, &enout);
             dq = abs(q1 - qsp)/std::max(q1,1.e-12);
             qsp = q1;
             // if converged at this point, exclude it from more iterations
             if (dt < dttol && dq < dqtol) {
                 status = 0;
                 break;
             }
         }
         // Test for enthalpy conservation
         if (abs((enin-enout)/(enin+enout)) > 1.e-4) status = 8;
         return;
     }
no_ip_hltalt()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::no_ip_hltalt (const amrex::Real & t, amrex::Real & hltalt) inline static
{
         hltalt = lat_vap;
         // Account for change of lat_vap with t above freezing where
         // constant slope is given by -2369 j/(kg c) = cpv - cw
         if (t >= tmelt) hltalt = hltalt - 2369.0*(t-tmelt);
     }
Referenced by calc_hltalt(), findsp(), and qsat_water().
qsat()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::qsat (const amrex::Real & t, const amrex::Real & p, amrex::Real & es, amrex::Real & qs, amrex::Real * gam = nullptr, amrex::Real * dqsdt = nullptr, amrex::Real * enthalpy = nullptr) inline static
{
         // Local variables
         amrex::Real hltalt;       // Modified latent heat for T derivatives
         amrex::Real tterm = 0.0;        // Account for d(es)/dT in transition region
         es = svp_trans(t); //estblf(t);
         qs = SatMethods::wv_sat_svp_to_qsat(es, p);
         // Ensures returned es is consistent with limiters on qs.
         es = std::min(es, p);
         // Calculate optional arguments.
         // "generalized" analytic expression for t derivative of es
         // accurate to within 1 percent for 173.16 < t < 373.16
         calc_hltalt(t, hltalt, &tterm);
         if (enthalpy)
         {
             *enthalpy = tq_enthalpy(t, qs, hltalt);
         }
         if (gam && dqsdt)
         {
             deriv_outputs(t, p, es, qs, hltalt, tterm, *gam, *dqsdt);
         }
     }
Referenced by AerRadProps::aer_rad_props_lw(), AerRadProps::aer_rad_props_sw(), findsp(), and ModalAeroWateruptake::modal_aero_wateruptake_dr().
qsat_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::qsat_ice (const amrex::Real & t, const amrex::Real & p, amrex::Real & es, amrex::Real & qs, amrex::Real & gam, amrex::Real & dqsdt, amrex::Real & enthalpy) inline static
{
         // Local variables
         amrex::Real hltalt;       // Modified latent heat for T derivatives
         SatMethods::wv_sat_qsat_ice(t, p, es, qs);
         // For pure ice, just add latent heats.
         hltalt = lat_vap + lat_ice;
         enthalpy = tq_enthalpy(t, qs, hltalt);
         // For pure water/ice transition term is 0.
         deriv_outputs(t, p, es, qs, hltalt, 0., gam, dqsdt);
     }
qsat_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void WaterVaporSat::qsat_water (const amrex::Real & t, const amrex::Real & p, amrex::Real & es, amrex::Real & qs, amrex::Real * gam = nullptr, amrex::Real * dqsdt = nullptr, amrex::Real * enthalpy = nullptr) inline static
{
         // Local variables
         amrex::Real hltalt;       // Modified latent heat for T derivatives
         SatMethods::wv_sat_qsat_water(t, p, es, qs);
         // "generalized" analytic expression for t derivative of es
         // accurate to within 1 percent for 173.16 < t < 373.16
         no_ip_hltalt(t, hltalt);
         if (enthalpy)
         {
             *enthalpy = tq_enthalpy(t, qs, hltalt);
         }
         if (gam && dqsdt)
         {
             // For pure water/ice transition term is 0.
             deriv_outputs(t, p, es, qs, hltalt, 0., *gam, *dqsdt);
         }
     }
Referenced by findsp().
svp_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real WaterVaporSat::svp_ice (const amrex::Real & t) inline static
{
         return SatMethods::wv_sat_svp_ice(t);
     }
svp_trans()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real WaterVaporSat::svp_trans (const amrex::Real & t) inline static
{
         return SatMethods::wv_sat_svp_trans(t);
     }
Referenced by qsat().
svp_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real WaterVaporSat::svp_water (const amrex::Real & t) inline static
{
         return SatMethods::wv_sat_svp_water(t);
     }
tq_enthalpy()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real WaterVaporSat::tq_enthalpy (const amrex::Real & t, const amrex::Real & q, const amrex::Real & hltalt) inline static
{
         return Cp_d * t + hltalt * q;
     }
Referenced by findsp(), qsat(), qsat_ice(), and qsat_water().
Member Data Documentation
npcf
constexpr int WaterVaporSat::npcf = 5 static constexpr
Referenced by calc_hltalt().
pcf
constexpr const amrex::Real WaterVaporSat::pcf[npcf] static constexpr
Initial value:
= {5.04469588506e-01,
                                                   -5.47288442819e+00,
                                                   -3.67471858735e-01,
                                                   -8.95963532403e-03,
                                                   -7.78053686625e-05}
Referenced by calc_hltalt().
tmax
constexpr amrex::Real WaterVaporSat::tmax = 375.16 static constexpr
Referenced by findsp().
tmin
constexpr amrex::Real WaterVaporSat::tmin = 127.16 static constexpr
Referenced by findsp().
The documentation for this class was generated from the following file:
Source/Utils/Water_vapor_saturation.H