ERF: IOManager Class Reference
IOManager Class Reference
Utilities
Input/Output manager.
#include <IOManager.H>
Public Member Functions
IOManager (ERF &)
~IOManager ()
void writePlotFile (const std::string &dir, std::ostream &os, amrex::VisMF::How how)
Write all user-requested fields to disk.
void writeSmallPlotFile (const std::string &dir, std::ostream &os, amrex::VisMF::How how)
write small plotfile
void checkPoint (const std::string &dir, std::ostream &os, amrex::VisMF::How how, bool dump_old_default)
Write checkpoint file.
void restart (amrex::Amr &papa, std::istream &is, bool bReadSpecial)
restart using checkpoint file
void set_state_in_checkpoint (amrex::Vector< int > &state_in_checkpoint)
set state in checkpoint
void setPlotVariables ()
setup the plot variables
void writeJobInfo (const std::string &dir)
write job information
void createNCColumnFile (const std::string &colfile_name, const amrex::Real xloc, const amrex::Real yloc)
Create 1D vertical column output for coupling.
void writeToNCColumnFile (const std::string &colfile_name, const amrex::Real xloc, const amrex::Real yloc)
Write a timestep to 1D vertical column output for coupling.
Static Public Member Functions
static void writeBuildInfo (std::ostream &os)
write build information
Private Attributes
ERF & erf
Detailed Description
Input/Output manager.
This class contains infrastructure to output solution fields during the simulation as well as code that reads a checkpoint file during a restarted simulation. By default the eqsys register the necessary fields during initialization and these fields are output into plot-file and checkpoint file formats based on output frequencies managed by SimTime. The user can request additional fields be output by setting appropriate parameters in the input file. The class also provides the ability to override output of the default fields and output a subset of those fields.
Constructor & Destructor Documentation
IOManager()
IOManager::IOManager (ERF & erf) explicit
     : erf(erf) {}
~IOManager()
IOManager::~IOManager () default
Member Function Documentation
checkPoint()
void IOManager::checkPoint (const std::string & dir, std::ostream & os, amrex::VisMF::How how, bool dump_old_default)
Write checkpoint file.
 {
   if (erf.level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
     {
       std::ofstream ERFHeaderFile;
       std::string FullPathERFHeaderFile = dir;
       FullPathERFHeaderFile += "/ERFHeader";
       ERFHeaderFile.open(FullPathERFHeaderFile.c_str(), std::ios::out);
       ERFHeaderFile << "Checkpoint version: " << current_version << std::endl;
       ERFHeaderFile.close();
     }
     {
       // store elapsed CPU time
       std::ofstream CPUFile;
       std::string FullPathCPUFile = dir;
       FullPathCPUFile += "/CPUtime";
       CPUFile.open(FullPathCPUFile.c_str(), std::ios::out);
       CPUFile << std::setprecision(15) << erf.getCPUTime();
       CPUFile.close();
     }
     /*Not implemented for CUDA{
         // store any problem-specific stuff
         char * dir_for_pass = new char[dir.size() + 1];
         std::copy(dir.begin(), dir.end(), dir_for_pass);
         dir_for_pass[dir.size()] = '\0';
         int len = dir.size();
         Vector<int> int_dir_name(len);
         for (int j = 0; j < len; j++)
       int_dir_name[j] = (int) dir_for_pass[j];
         AMREX_FORT_PROC_CALL(PROBLEM_CHECKPOINT,problem_checkpoint)(int_dir_name.dataPtr(),
     &len);
         delete [] dir_for_pass;
     }*/
   }
 }
createNCColumnFile()
void IOManager::createNCColumnFile (const std::string & colfile_name, const amrex::Real xloc, const amrex::Real yloc)
Create 1D vertical column output for coupling.
 {
   // TODO: Relax assumption of only a single level
   if (erf.parent->finestLevel() > 0) {
     amrex::Error("Cannot createNCColumnFile: present implementation assumes only a single level is present");
   }
   // Create file to which column data will be written every timestep
   if (amrex::ParallelDescriptor::IOProcessor()) {
     auto ncf = ncutils::NCFile::create(colfile_name, NC_CLOBBER | NC_NETCDF4);
     const std::string nt_name = "ntime";
     const std::string nh_name = "nheight";
     // Use one grow cell (on either side) to allow interpolation to boundaries
     const int nheights = erf.geom.Domain().length(2) + 2;
     ncf.enter_def_mode();
     ncf.put_attr("title", "ERF NetCDF Vertical Column Output");
     ncf.put_attr("units", "mks");
     amrex::Vector<amrex::Real> loc = {xloc, yloc};
     ncf.put_attr("location", loc);
     ncf.def_dim(nt_name, NC_UNLIMITED);
     ncf.def_dim(nh_name, nheights);
     ncf.def_var("times", NC_FLOAT, {nt_name});
     ncf.def_var("heights", NC_FLOAT, {nh_name});
     ncf.def_var("wrf_momentum_u", NC_FLOAT, {nt_name, nh_name});
     ncf.def_var("wrf_momentum_v", NC_FLOAT, {nt_name, nh_name});
     ncf.def_var("wrf_temperature", NC_FLOAT, {nt_name, nh_name});
     ncf.def_var("wrf_tflux", NC_FLOAT, {nt_name});
     ncf.exit_def_mode();
     // Put in the Z grid, but not any actual data yet
     amrex::Real zmin = erf.geom.ProbLo(2);
     amrex::Real dz = erf.geom.CellSize(2);
     amrex::Vector<amrex::Real> zvalues(nheights, zmin-0.5*dz);
     for (int ii = 0; ii < nheights; ++ii) {
       zvalues[ii] += ii * dz;
     }
     ncf.var("heights").put(zvalues.data());
     ncf.close();
   }
 }
restart()
void IOManager::restart (amrex::Amr & papa, std::istream & is, bool bReadSpecial)
restart using checkpoint file
 {
   // Let's check ERF checkpoint version first;
   // trying to read from checkpoint; if nonexisting, set it to 0.
   if (input_version == -1) {
     if (amrex::ParallelDescriptor::IOProcessor()) {
       std::ifstream ERFHeaderFile;
       std::string FullPathERFHeaderFile = papa.theRestartFile();
       FullPathERFHeaderFile += "/ERFHeader";
       ERFHeaderFile.open(FullPathERFHeaderFile.c_str(), std::ios::in);
       if (ERFHeaderFile.good()) {
         char foo[256];
         // first line: Checkpoint version: ?
         ERFHeaderFile.getline(foo, 256, ':');
         ERFHeaderFile >> input_version;
         ERFHeaderFile.close();
       } else {
         input_version = 0;
       }
     }
     amrex::ParallelDescriptor::Bcast(
       &input_version, 1, amrex::ParallelDescriptor::IOProcessorNumber());
   }
   AMREX_ASSERT(input_version >= 0);
   /*
     Deal here with new state descriptor types added, with corresponding
     input_version > 0, if applicable
    */
   amrex::Vector<int> state_in_checkpoint(erf.desc_lst.size(), 1);
   set_state_in_checkpoint(state_in_checkpoint);
   for (int i = 0; i < erf.desc_lst.size(); ++i) {
     if (state_in_checkpoint[i] == 0) {
       const amrex::Real ctime = erf.state[i - 1].curTime();
       erf.state[i].define(
         erf.geom.Domain(), erf.grids, erf.dmap, erf.desc_lst[i], ctime, erf.parent->dtLevel(erf.level),
         *(erf.m_factory));
       erf.state[i] = erf.state[i - 1];
     }
   }
   erf.buildMetrics();
   amrex::MultiFab& S_new = erf.get_new_data(State_Type);
   erf.Sborder.define(erf.grids, erf.dmap, NVAR, NUM_GROW, amrex::MFInfo(), erf.Factory());
   // get the elapsed CPU time to now;
   if (erf.level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
     // get elapsed CPU time
     std::ifstream CPUFile;
     std::string FullPathCPUFile = erf.parent->theRestartFile();
     FullPathCPUFile += "/CPUtime";
     CPUFile.open(FullPathCPUFile.c_str(), std::ios::in);
     CPUFile >> erf.previousCPUTimeUsed;
     CPUFile.close();
     amrex::Print() << "read CPU time: " << erf.previousCPUTimeUsed << "\n";
   }
   /*Not implemented for CUDA
       if (level == 0)
       {
     // get problem-specific stuff -- note all processors do this,
     // eliminating the need for a broadcast
     std::string dir = parent->theRestartFile();
     char * dir_for_pass = new char[dir.size() + 1];
     std::copy(dir.begin(), dir.end(), dir_for_pass);
     dir_for_pass[dir.size()] = '\0';
     int len = dir.size();
     Vector<int> int_dir_name(len);
     for (int j = 0; j < len; j++)
         int_dir_name[j] = (int) dir_for_pass[j];
     AMREX_FORT_PROC_CALL(PROBLEM_RESTART,problem_restart)(int_dir_name.dataPtr(),
     &len);
     delete [] dir_for_pass;
       }*/
   if (erf.level > 0 && erf.do_reflux) {
     erf.flux_reg.define(
       erf.grids, papa.boxArray(erf.level - 1), erf.dmap, papa.DistributionMap(erf.level - 1),
       erf.geom, papa.Geom(erf.level - 1), papa.refRatio(erf.level - 1), erf.level, NVAR);
   }
 }
set_state_in_checkpoint()
void IOManager::set_state_in_checkpoint (amrex::Vector< int > & state_in_checkpoint)
set state in checkpoint
 {
   for (int i = 0; i < erf.num_state_type; ++i) {
     state_in_checkpoint[i] = 1;
     if (i == Work_Estimate_Type) {
       state_in_checkpoint[i] = 0;
     }
   }
 }
Referenced by restart().
setPlotVariables()
void IOManager::setPlotVariables ()
setup the plot variables
 {
 }
writeBuildInfo()
void IOManager::writeBuildInfo (std::ostream & os) static
write build information
 {
   std::string PrettyLine = std::string(78, '=') + "\n";
   std::string OtherLine = std::string(78, '-') + "\n";
   std::string SkipSpace = std::string(8, ' ');
   // build information
   os << PrettyLine;
   os << " ERF Build Information\n";
   os << PrettyLine;
   os << "build date:    " << amrex::buildInfoGetBuildDate() << "\n";
   os << "build machine: " << amrex::buildInfoGetBuildMachine() << "\n";
   os << "build dir:     " << amrex::buildInfoGetBuildDir() << "\n";
   os << "AMReX dir:     " << amrex::buildInfoGetAMReXDir() << "\n";
   os << "\n";
   os << "COMP:          " << amrex::buildInfoGetComp() << "\n";
   os << "COMP version:  " << amrex::buildInfoGetCompVersion() << "\n";
   os << "C++ compiler:  " << amrex::buildInfoGetCXXName() << "\n";
   os << "C++ flags:     " << amrex::buildInfoGetCXXFlags() << "\n";
   os << "\n";
   os << "Link flags:    " << amrex::buildInfoGetLinkFlags() << "\n";
   os << "Libraries:     " << amrex::buildInfoGetLibraries() << "\n";
   os << "\n";
   for (int n = 1; n <= amrex::buildInfoGetNumModules(); n++) {
     os << amrex::buildInfoGetModuleName(n) << ": "
        << amrex::buildInfoGetModuleVal(n) << "\n";
   }
   os << "\n";
   const char* githash1 = amrex::buildInfoGetGitHash(1);
   const char* githash2 = amrex::buildInfoGetGitHash(2);
   if (strlen(githash1) > 0) {
     os << "ERF       git hash: " << githash1 << "\n";
   }
   if (strlen(githash2) > 0) {
     os << "AMReX       git hash: " << githash2 << "\n";
   }
   const char* buildgithash = amrex::buildInfoGetBuildGitHash();
   const char* buildgitname = amrex::buildInfoGetBuildGitName();
   if (strlen(buildgithash) > 0) {
     os << buildgitname << " git hash: " << buildgithash << "\n";
   }
   os << "\n";
   os << " ERF Compile time variables: \n";
   os << "\n";
   os << " ERF Defines: \n";
 #ifdef _OPENMP
   os << std::setw(35) << std::left << "_OPENMP " << std::setw(6) << "ON"
      << std::endl;
 #else
   os << std::setw(35) << std::left << "_OPENMP " << std::setw(6) << "OFF"
      << std::endl;
 #endif
 #ifdef MPI_VERSION
   os << std::setw(35) << std::left << "MPI_VERSION " << std::setw(6)
      << MPI_VERSION << std::endl;
 #else
   os << std::setw(35) << std::left << "MPI_VERSION " << std::setw(6)
      << "UNDEFINED" << std::endl;
 #endif
 #ifdef MPI_SUBVERSION
   os << std::setw(35) << std::left << "MPI_SUBVERSION " << std::setw(6)
      << MPI_SUBVERSION << std::endl;
 #else
   os << std::setw(35) << std::left << "MPI_SUBVERSION " << std::setw(6)
      << "UNDEFINED" << std::endl;
 #endif
 #ifdef NUM_ADV
   os << std::setw(35) << std::left << "NUM_ADV=" << NUM_ADV << std::endl;
 #else
   os << std::setw(35) << std::left << "NUM_ADV"
      << "is undefined (0)" << std::endl;
 #endif
   os << "\n\n";
 }
Referenced by main().
writeJobInfo()
void IOManager::writeJobInfo (const std::string & dir)
write job information
 {
   // job_info file with details about the run
   std::ofstream jobInfoFile;
   std::string FullPathJobInfoFile = dir;
   FullPathJobInfoFile += "/job_info";
   jobInfoFile.open(FullPathJobInfoFile.c_str(), std::ios::out);
   std::string PrettyLine = "==================================================="
                            "============================\n";
   std::string OtherLine = "----------------------------------------------------"
                           "----------------------------\n";
   std::string SkipSpace = "        ";
   // job information
   jobInfoFile << PrettyLine;
   jobInfoFile << " ERF Job Information\n";
   jobInfoFile << PrettyLine;
   jobInfoFile << "inputs file: " << inputs_name << "\n\n";
   jobInfoFile << "number of MPI processes: "
               << amrex::ParallelDescriptor::NProcs() << "\n";
 #ifdef _OPENMP
   jobInfoFile << "number of threads:       " << omp_get_max_threads() << "\n";
 #endif
   jobInfoFile << "\n";
   jobInfoFile << "CPU time used since start of simulation (CPU-hours): "
               << erf.getCPUTime() / 3600.0;
   jobInfoFile << "\n\n";
   // plotfile information
   jobInfoFile << PrettyLine;
   jobInfoFile << " Plotfile Information\n";
   jobInfoFile << PrettyLine;
   time_t now = time(0);
   // Convert now to tm struct for local timezone
   tm* localtm = localtime(&now);
   jobInfoFile << "output data / time: " << asctime(localtm);
   std::string currentDir = amrex::FileSystem::CurrentPath();
   jobInfoFile << "output dir:         " << currentDir << "\n";
   jobInfoFile << "\n\n";
   // build information
   jobInfoFile << PrettyLine;
   jobInfoFile << " Build Information\n";
   jobInfoFile << PrettyLine;
   jobInfoFile << "build date:    " << amrex::buildInfoGetBuildDate() << "\n";
   jobInfoFile << "build machine: " << amrex::buildInfoGetBuildMachine() << "\n";
   jobInfoFile << "build dir:     " << amrex::buildInfoGetBuildDir() << "\n";
   jobInfoFile << "AMReX dir:     " << amrex::buildInfoGetAMReXDir() << "\n";
   jobInfoFile << "\n";
   jobInfoFile << "COMP:          " << amrex::buildInfoGetComp() << "\n";
   jobInfoFile << "COMP version:  " << amrex::buildInfoGetCompVersion() << "\n";
   jobInfoFile << "FCOMP:         " << amrex::buildInfoGetFcomp() << "\n";
   jobInfoFile << "FCOMP version: " << amrex::buildInfoGetFcompVersion() << "\n";
   jobInfoFile << "\n";
   for (int n = 1; n <= amrex::buildInfoGetNumModules(); n++) {
     jobInfoFile << amrex::buildInfoGetModuleName(n) << ": "
                 << amrex::buildInfoGetModuleVal(n) << "\n";
   }
   jobInfoFile << "\n";
   const char* githash1 = amrex::buildInfoGetGitHash(1);
   const char* githash2 = amrex::buildInfoGetGitHash(2);
   if (strlen(githash1) > 0) {
     jobInfoFile << "ERF       git hash: " << githash1 << "\n";
   }
   if (strlen(githash2) > 0) {
     jobInfoFile << "AMReX       git hash: " << githash2 << "\n";
   }
   const char* buildgithash = amrex::buildInfoGetBuildGitHash();
   const char* buildgitname = amrex::buildInfoGetBuildGitName();
   if (strlen(buildgithash) > 0) {
     jobInfoFile << buildgitname << " git hash: " << buildgithash << "\n";
   }
   jobInfoFile << "\n\n";
   // grid information
   jobInfoFile << PrettyLine;
   jobInfoFile << " Grid Information\n";
   jobInfoFile << PrettyLine;
   int f_lev = erf.parent->finestLevel();
   for (int i = 0; i <= f_lev; i++) {
     jobInfoFile << " level: " << i << "\n";
     jobInfoFile << "   number of boxes = " << erf.parent->numGrids(i) << "\n";
     jobInfoFile << "   maximum zones   = ";
     for (int n = 0; n < AMREX_SPACEDIM; n++) {
       jobInfoFile << erf.parent->Geom(i).Domain().length(n) << " ";
       // jobInfoFile << parent->Geom(i).ProbHi(n) << " ";
     }
     jobInfoFile << "\n\n";
   }
   jobInfoFile << " Boundary conditions\n";
   amrex::Vector<std::string> lo_bc_out(AMREX_SPACEDIM);
   amrex::Vector<std::string> hi_bc_out(AMREX_SPACEDIM);
   amrex::ParmParse pp("erf");
   pp.getarr("lo_bc", lo_bc_out, 0, AMREX_SPACEDIM);
   pp.getarr("hi_bc", hi_bc_out, 0, AMREX_SPACEDIM);
   // these names correspond to the integer flags setup in the
   // Setup.cpp
   jobInfoFile << "   -x: " << lo_bc_out[0] << "\n";
   jobInfoFile << "   +x: " << hi_bc_out[0] << "\n";
   jobInfoFile << "   -y: " << lo_bc_out[1] << "\n";
   jobInfoFile << "   +y: " << hi_bc_out[1] << "\n";
   jobInfoFile << "   -z: " << lo_bc_out[2] << "\n";
   jobInfoFile << "   +z: " << hi_bc_out[2] << "\n";
   jobInfoFile << "\n\n";
   int mlen = 20;
   jobInfoFile << PrettyLine;
   jobInfoFile << " Species Information\n";
   jobInfoFile << PrettyLine;
   jobInfoFile << std::setw(6) << "index" << SkipSpace << std::setw(mlen + 1)
               << "name" << SkipSpace << std::setw(7) << "A" << SkipSpace
               << std::setw(7) << "Z"
               << "\n";
   jobInfoFile << OtherLine;
   jobInfoFile << "\n\n";
   // runtime parameters
   jobInfoFile << PrettyLine;
   jobInfoFile << " Inputs File Parameters\n";
   jobInfoFile << PrettyLine;
   amrex::ParmParse::dumpTable(jobInfoFile, true);
   jobInfoFile.close();
 }
Referenced by writePlotFile(), and writeSmallPlotFile().
writePlotFile()
void IOManager::writePlotFile (const std::string & dir, std::ostream & os, amrex::VisMF::How how)
Write all user-requested fields to disk.
 {
 std::cout << "writePlotFile_00" << std::endl;
   int i, n;
   //
   // The list of indices of State to write to plotfile.
   // first component of pair is state_type,
   // second component of pair is component # within the state_type
   //
   amrex::Vector<std::pair<int, int>> plot_var_map;
   for (int typ = 0; typ < erf.desc_lst.size(); typ++)
     for (int comp = 0; comp < erf.desc_lst[typ].nComp(); comp++)
       if (
         erf.parent->isStatePlotVar(erf.desc_lst[typ].name(comp)) &&
         erf.desc_lst[typ].getType() == amrex::IndexType::TheCellType())
         plot_var_map.push_back(std::pair<int, int>(typ, comp));
   int num_derive = 0;
   std::list<std::string> derive_names;
   const std::list<amrex::DeriveRec>& dlist = erf.derive_lst.dlist();
   for (std::list<amrex::DeriveRec>::const_iterator it = dlist.begin(),
                                                    end = dlist.end();
        it != end; ++it)
   {
     if (erf.parent->isDerivePlotVar(it->name())) {
       {
         derive_names.push_back(it->name());
         num_derive += it->numDerive();
       }
     }
   }
   int n_data_items = plot_var_map.size() + num_derive;
   amrex::Real cur_time = erf.state[State_Type].curTime();
   if (erf.level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
     //
     // The first thing we write out is the plotfile type.
     //
     os << erf.thePlotFileType() << '\n';
     if (n_data_items == 0)
       amrex::Error("Must specify at least one valid data item to plot");
     os << n_data_items << '\n';
     //
     // Names of variables -- first state, then derived
     //
     for (i = 0; i < plot_var_map.size(); i++) {
       int typ = plot_var_map[i].first;
       int comp = plot_var_map[i].second;
       os << erf.desc_lst[typ].name(comp) << '\n';
     }
     for (std::list<std::string>::const_iterator it = derive_names.begin(),
                                                 end = derive_names.end();
          it != end; ++it) {
       const amrex::DeriveRec* rec = erf.derive_lst.get(*it);
       for (i = 0; i < rec->numDerive(); i++)
         os << rec->variableName(i) << '\n';
     }
     os << AMREX_SPACEDIM << '\n';
     os << erf.parent->cumTime() << '\n';
     int f_lev = erf.parent->finestLevel();
     os << f_lev << '\n';
     for (i = 0; i < AMREX_SPACEDIM; i++)
       os << amrex::DefaultGeometry().ProbLo(i) << ' ';
     os << '\n';
     for (i = 0; i < AMREX_SPACEDIM; i++)
       os << amrex::DefaultGeometry().ProbHi(i) << ' ';
     os << '\n';
     for (i = 0; i < f_lev; i++)
       os << erf.parent->refRatio(i)[0] << ' ';
     os << '\n';
     for (i = 0; i <= f_lev; i++)
       os << erf.parent->Geom(i).Domain() << ' ';
     os << '\n';
     for (i = 0; i <= f_lev; i++)
       os << erf.parent->levelSteps(i) << ' ';
     os << '\n';
     for (i = 0; i <= f_lev; i++) {
       for (int k = 0; k < AMREX_SPACEDIM; k++)
         os << erf.parent->Geom(i).CellSize()[k] << ' ';
       os << '\n';
     }
     os << (int)amrex::DefaultGeometry().Coord() << '\n';
     os << "0\n"; // Write bndry data.
     writeJobInfo(dir);
   }
   // Build the directory to hold the MultiFab at this level.
   // The name is relative to the directory containing the Header file.
   //
   static const std::string BaseName = "/Cell";
   char buf[64];
   sprintf(buf, "Level_%d", erf.level);
   std::string LevelStr = buf;
   //
   // Now for the full pathname of that directory.
   //
   std::string FullPath = dir;
   if (!FullPath.empty() && FullPath[FullPath.size() - 1] != '/')
     FullPath += '/';
   FullPath += LevelStr;
   //
   // Only the I/O processor makes the directory if it doesn't already exist.
   //
   if (amrex::ParallelDescriptor::IOProcessor())
     if (!amrex::UtilCreateDirectory(FullPath, 0755))
       amrex::CreateDirectoryFailed(FullPath);
   //
   // Force other processors to wait till directory is built.
   //
   amrex::ParallelDescriptor::Barrier();
   if (amrex::ParallelDescriptor::IOProcessor()) {
     os << erf.level << ' ' << erf.grids.size() << ' ' << cur_time << '\n';
     os << erf.parent->levelSteps(erf.level) << '\n';
     for (i = 0; i < erf.grids.size(); ++i) {
       amrex::RealBox gridloc =
         amrex::RealBox(erf.grids[i], erf.geom.CellSize(), erf.geom.ProbLo());
       for (n = 0; n < AMREX_SPACEDIM; n++)
         os << gridloc.lo(n) << ' ' << gridloc.hi(n) << '\n';
     }
     //
     // The full relative pathname of the MultiFabs at this level.
     // The name is relative to the Header file containing this name.
     // It's the name that gets written into the Header.
     //
     if (n_data_items > 0) {
       std::string PathNameInHeader = LevelStr;
       PathNameInHeader += BaseName;
       os << PathNameInHeader << '\n';
     }
   }
   //
   // We combine all of the multifabs -- state, derived, etc -- into one
   // multifab -- plotMF.
   // NOTE: we are assuming that each state variable has one component,
   // but a derived variable is allowed to have multiple components.
   int cnt = 0;
   int ncomp = 1;
   const int nGrow = 0;
   amrex::MultiFab plotMF(
     erf.grids, erf.dmap, n_data_items, nGrow, amrex::MFInfo(), erf.Factory());
   amrex::MultiFab* this_dat = 0;
   //
   // Cull data from state variables -- use no ghost cells.
   //
   for (i = 0; i < plot_var_map.size(); i++) {
     int typ = plot_var_map[i].first;
     int comp = plot_var_map[i].second;
     this_dat = &(erf.state[typ].newData());
     amrex::MultiFab::Copy(plotMF, *this_dat, comp, cnt, 1, nGrow);
     cnt++;
   }
   //
   // Cull data from derived variables.
   //
   if (derive_names.size() > 0) {
     for (std::list<std::string>::const_iterator it = derive_names.begin(),
                                                 end = derive_names.end();
          it != end; ++it) {
       const amrex::DeriveRec* rec = erf.derive_lst.get(*it);
       ncomp = rec->numDerive();
       auto derive_dat = erf.derive(*it, cur_time, nGrow);
       amrex::MultiFab::Copy(plotMF, *derive_dat, 0, cnt, ncomp, nGrow);
       cnt += ncomp;
     }
   }
   //
   // Use the Full pathname when naming the MultiFab.
   //
   std::string TheFullPath = FullPath;
   TheFullPath += BaseName;
   amrex::VisMF::Write(plotMF, TheFullPath, how, true);
 }
writeSmallPlotFile()
void IOManager::writeSmallPlotFile (const std::string & dir, std::ostream & os, amrex::VisMF::How how)
write small plotfile
 {
   int i, n;
   //
   // The list of indices of State to write to plotfile.
   // first component of pair is state_type,
   // second component of pair is component # within the state_type
   //
   amrex::Vector<std::pair<int, int>> plot_var_map;
   for (int typ = 0; typ < erf.desc_lst.size(); typ++)
     for (int comp = 0; comp < erf.desc_lst[typ].nComp(); comp++)
       if (
         erf.parent->isStateSmallPlotVar(erf.desc_lst[typ].name(comp)) &&
         erf.desc_lst[typ].getType() == amrex::IndexType::TheCellType())
         plot_var_map.push_back(std::pair<int, int>(typ, comp));
   int n_data_items = plot_var_map.size();
   amrex::Real cur_time = erf.state[State_Type].curTime();
   if (erf.level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
     //
     // The first thing we write out is the plotfile type.
     //
     os << erf.thePlotFileType() << '\n';
     if (n_data_items == 0)
       amrex::Error("Must specify at least one valid data item to plot");
     os << n_data_items << '\n';
     //
     // Names of variables -- first state, then derived
     //
     for (i = 0; i < plot_var_map.size(); i++) {
       int typ = plot_var_map[i].first;
       int comp = plot_var_map[i].second;
       os << erf.desc_lst[typ].name(comp) << '\n';
     }
     os << AMREX_SPACEDIM << '\n';
     os << erf.parent->cumTime() << '\n';
     int f_lev = erf.parent->finestLevel();
     os << f_lev << '\n';
     for (i = 0; i < AMREX_SPACEDIM; i++)
       os << amrex::DefaultGeometry().ProbLo(i) << ' ';
     os << '\n';
     for (i = 0; i < AMREX_SPACEDIM; i++)
       os << amrex::DefaultGeometry().ProbHi(i) << ' ';
     os << '\n';
     for (i = 0; i < f_lev; i++)
       os << erf.parent->refRatio(i)[0] << ' ';
     os << '\n';
     for (i = 0; i <= f_lev; i++)
       os << erf.parent->Geom(i).Domain() << ' ';
     os << '\n';
     for (i = 0; i <= f_lev; i++)
       os << erf.parent->levelSteps(i) << ' ';
     os << '\n';
     for (i = 0; i <= f_lev; i++) {
       for (int k = 0; k < AMREX_SPACEDIM; k++)
         os << erf.parent->Geom(i).CellSize()[k] << ' ';
       os << '\n';
     }
     os << (int)amrex::DefaultGeometry().Coord() << '\n';
     os << "0\n"; // Write bndry data.
     // job_info file with details about the run
     writeJobInfo(dir);
   }
   // Build the directory to hold the MultiFab at this level.
   // The name is relative to the directory containing the Header file.
   //
   static const std::string BaseName = "/Cell";
   char buf[64];
   sprintf(buf, "Level_%d", erf.level);
   std::string LevelStr = buf;
   //
   // Now for the full pathname of that directory.
   //
   std::string FullPath = dir;
   if (!FullPath.empty() && FullPath[FullPath.size() - 1] != '/')
     FullPath += '/';
   FullPath += LevelStr;
   //
   // Only the I/O processor makes the directory if it doesn't already exist.
   //
   if (amrex::ParallelDescriptor::IOProcessor())
     if (!amrex::UtilCreateDirectory(FullPath, 0755))
       amrex::CreateDirectoryFailed(FullPath);
   //
   // Force other processors to wait till directory is built.
   //
   amrex::ParallelDescriptor::Barrier();
   if (amrex::ParallelDescriptor::IOProcessor()) {
     os << erf.level << ' ' << erf.grids.size() << ' ' << cur_time << '\n';
     os << erf.parent->levelSteps(erf.level) << '\n';
     for (i = 0; i < erf.grids.size(); ++i) {
       amrex::RealBox gridloc =
         amrex::RealBox(erf.grids[i], erf.geom.CellSize(), erf.geom.ProbLo());
       for (n = 0; n < AMREX_SPACEDIM; n++)
         os << gridloc.lo(n) << ' ' << gridloc.hi(n) << '\n';
     }
     //
     // The full relative pathname of the MultiFabs at this level.
     // The name is relative to the Header file containing this name.
     // It's the name that gets written into the Header.
     //
     if (n_data_items > 0) {
       std::string PathNameInHeader = LevelStr;
       PathNameInHeader += BaseName;
       os << PathNameInHeader << '\n';
     }
     os << vfraceps << '\n';
   }
   //
   // We combine all of the multifabs -- state, derived, etc -- into one
   // multifab -- plotMF.
   // NOTE: we are assuming that each state variable has one component,
   // but a derived variable is allowed to have multiple components.
   int cnt = 0;
   const int nGrow = 0;
   amrex::MultiFab plotMF(
     erf.grids, erf.dmap, n_data_items, nGrow, amrex::MFInfo(), erf.Factory());
   amrex::MultiFab* this_dat = 0;
   //
   // Cull data from state variables -- use no ghost cells.
   //
   for (i = 0; i < plot_var_map.size(); i++) {
     int typ = plot_var_map[i].first;
     int comp = plot_var_map[i].second;
     this_dat = &(erf.state[typ].newData());
     amrex::MultiFab::Copy(plotMF, *this_dat, comp, cnt, 1, nGrow);
     cnt++;
   }
   //
   // Use the Full pathname when naming the MultiFab.
   //
   std::string TheFullPath = FullPath;
   TheFullPath += BaseName;
   amrex::VisMF::Write(plotMF, TheFullPath, how, true);
 }
writeToNCColumnFile()
void IOManager::writeToNCColumnFile (const std::string & colfile_name, const amrex::Real xloc, const amrex::Real yloc)
Write a timestep to 1D vertical column output for coupling.
 {
   // TODO: Relax assumption of only a single level
   if (erf.parent->finestLevel() > 0) {
     amrex::Error("Cannot writeToNCColumnFile: present implementation assumes only a single level is present");
   }
   // All processors: look for the requested column and get data if it's there
   amrex::Box probBox = erf.geom.Domain();
   const size_t nheights = probBox.length(2) + 2;
   amrex::Gpu::DeviceVector<amrex::Real> d_column_data(nheights*3, 0.0);
   amrex::Vector<amrex::Real> h_column_data(nheights*3, 0.0);
   amrex::Real* ucol = &d_column_data[0];
   amrex::Real* vcol = &d_column_data[nheights];
   amrex::Real* thetacol = &d_column_data[nheights*2];
   // Requested point must be inside problem domain
   if (xloc < erf.geom.ProbLo(0) || xloc > erf.geom.ProbHi(0) ||
       yloc < erf.geom.ProbLo(1) || yloc > erf.geom.ProbHi(1)) {
     amrex::Error("Invalid xy location to save column data - outside of domain");
   }
   // get indices and interpolation coefficients
   const amrex::Real x_cell_loc = probBox.smallEnd(0) + (xloc - erf.geom.ProbLo(0))* erf.geom.InvCellSize(0);
   const amrex::Real y_cell_loc = probBox.smallEnd(1) + (yloc - erf.geom.ProbLo(1))* erf.geom.InvCellSize(1);
   const int iloc = floor(x_cell_loc - 0.5);
   const int jloc = floor(y_cell_loc - 0.5);
   const amrex::Real alpha_x = x_cell_loc - 0.5 - iloc;
   const amrex::Real alpha_y = y_cell_loc - 0.5 - jloc;
   amrex::Array2D<amrex::Real, 0, 1, 0, 1> alpha_theta;
   alpha_theta(0,0) = (1.0 - alpha_x) * (1.0-alpha_y);
   alpha_theta(1,0) = (alpha_x) * (1.0-alpha_y);
   alpha_theta(0,1) = (1.0 - alpha_x) * (alpha_y);
   alpha_theta(1,1) = (alpha_x) * (alpha_y);
   // may need different indices for u,v due to not being collocated
   const int iloc_shift = floor(x_cell_loc) - iloc;
   const int jloc_shift = floor(y_cell_loc) - jloc;
   const amrex::Real alpha_x_u = x_cell_loc - iloc - iloc_shift;
   const amrex::Real alpha_y_v = y_cell_loc - jloc - jloc_shift;
   amrex::Array2D<amrex::Real, 0, 1, 0, 1> alpha_u;
   alpha_u(0,0) = (1.0 - alpha_x_u) * (1.0-alpha_y);
   alpha_u(1,0) = (alpha_x_u) * (1.0-alpha_y);
   alpha_u(0,1) = (1.0 - alpha_x_u) * (alpha_y);
   alpha_u(1,1) = (alpha_x_u) * (alpha_y);
   amrex::Array2D<amrex::Real, 0, 1, 0, 1> alpha_v;
   alpha_v(0,0) = (1.0 - alpha_x) * (1.0-alpha_y_v);
   alpha_v(1,0) = (alpha_x) * (1.0-alpha_y_v);
   alpha_v(0,1) = (1.0 - alpha_x) * (alpha_y_v);
   alpha_v(1,1) = (alpha_x) * (alpha_y_v);
   const int kstart = probBox.smallEnd(2)-1;
   const int kend = probBox.bigEnd(2)+1;
   const amrex::Box target_box(IntVect{iloc, jloc, kstart},
                               IntVect{iloc+1, jloc+1, kend});
   //  Need to get these valid in one grow cell for interpolation
   amrex::MultiFab& S_new = erf.get_new_data(State_Type);
   amrex::MultiFab& U_new = erf.get_new_data(X_Vel_Type);
   amrex::MultiFab& V_new = erf.get_new_data(Y_Vel_Type);
   S_new.FillBoundary(erf.geom.periodicity());
   U_new.FillBoundary(erf.geom.periodicity());
   V_new.FillBoundary(erf.geom.periodicity());
   amrex::Vector<MultiFab*> all_vars{&S_new, &U_new, &V_new};
   ERF::applyBCs(erf.geom,all_vars);
   // No tiling - we're just interested in one location
   for ( MFIter mfi(S_new); mfi.isValid(); ++mfi){
     const amrex::Array4<Real const> & state = S_new.array(mfi);
     const amrex::Array4<Real const> & velx = U_new.array(mfi);
     const amrex::Array4<Real const> & vely = V_new.array(mfi);
     // we want to include data at physical boundary ghost cells
     // for interpolation (i,j) or saving (k)
     amrex::Box vbox = mfi.validbox();
     for (int idir = 0; idir <=2; idir++) {
       if (vbox.smallEnd(idir) == probBox.smallEnd(idir)) {
         vbox.growLo(idir,1);
       }
       if (vbox.bigEnd(idir) == probBox.bigEnd(idir)) {
         vbox.growHi(idir,1);
       }
     }
     // Loop over indices where our box contains data needed for interpolation
     const amrex::Box overlap_box = vbox & target_box;
     if (overlap_box.ok()) {
       amrex::ParallelFor(overlap_box,
       [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept {
         const int idx_vec = k - kstart;
         const int ialpha = i - iloc;
         const int jalpha = j - jloc;
         ucol[idx_vec] += velx(i+iloc_shift,j,k) * alpha_u(ialpha, jalpha);
         vcol[idx_vec] += vely(i,j+jloc_shift,k) * alpha_v(ialpha, jalpha);
         thetacol[idx_vec] += state(i,j,k,RhoTheta_comp) / state(i,j,k,Rho_comp)
           * alpha_theta(ialpha, jalpha);
       });
     }
   }
   // Communicate values to CPU then to the IO processor
   amrex::Gpu::copy(amrex::Gpu::deviceToHost, d_column_data.begin(),
     d_column_data.end(), h_column_data.begin());
   amrex::ParallelDescriptor::ReduceRealSum(h_column_data.data(),
     h_column_data.size(), amrex::ParallelDescriptor::IOProcessorNumber());
   // IO processor only: write the relevant data to file
   if (amrex::ParallelDescriptor::IOProcessor()) {
     auto ncf = ncutils::NCFile::open(colfile_name, NC_WRITE | NC_NETCDF4);
     size_t putloc = ncf.dim("ntime").len();
     // Time
     amrex::Real cumtime = erf.parent->cumTime();
     amrex::Vector<size_t> start_t {putloc};
     amrex::Vector<size_t> count_t {1};
     ncf.var("times").put(&cumtime, start_t, count_t);
     // T flux
     // TODO: Make this the actual flux rather than just a placeholder
     amrex::Real Tflux = 0.0;
     ncf.var("wrf_tflux").put(&Tflux, start_t, count_t);
     // U, V, Theta
     std::vector<size_t> start = {putloc, 0};
     std::vector<size_t> count = {1, nheights};
     ncf.var("wrf_momentum_u").put(&h_column_data[0], start, count);
     ncf.var("wrf_momentum_v").put(&h_column_data[nheights], start, count);
     ncf.var("wrf_temperature").put(&h_column_data[2*nheights], start, count);
     ncf.close();
   }
 }
Member Data Documentation
erf
ERF& IOManager::erf private
Referenced by checkPoint(), createNCColumnFile(), restart(), set_state_in_checkpoint(), writeJobInfo(), writePlotFile(), writeSmallPlotFile(), and writeToNCColumnFile().
The documentation for this class was generated from the following files:
/home/runner/work/ERF/ERF/Source/IO/IOManager.H
/home/runner/work/ERF/ERF/Source/IO/IOManager.cpp
/home/runner/work/ERF/ERF/Source/IO/NCColumnFile.cpp
/home/runner/work/ERF/ERF/Source/IO/PlotFile.cpp