ERF: WSM6 Class Reference
WSM6 Class Reference
#include <ERF_WSM6.H>
Public Member Functions
WSM6 ()
virtual ~WSM6 ()=default
void Define (SolverChoice &sc) override
void Init (const amrex::MultiFab &cons_in, const amrex::BoxArray &grids, const amrex::Geometry &geom, const amrex::Real &dt_advance, std::unique_ptr< amrex::MultiFab > &z_phys_nd, std::unique_ptr< amrex::MultiFab > &detJ_cc) override
void Set_dzmin (const amrex::Real dz_min) override
void Copy_State_to_Micro (const amrex::MultiFab &cons_in) override
void Copy_Micro_to_State (amrex::MultiFab &cons_in) override
void Update_Micro_Vars (amrex::MultiFab &cons_in) override
void Update_State_Vars (amrex::MultiFab &cons_in, const amrex::MultiFab &) override
void Advance (const amrex::Real &dt_advance, const SolverChoice &solverChoice) override
amrex::MultiFab * Qmoist_Ptr (const int &varIdx) override
int Qmoist_Size () override
int Qstate_Moist_Size () override
int Qstate_Moist_NumConc_Size () override
void Qmoist_Restart_Vars (const SolverChoice &, std::vector< int > &a_idx, std::vector< std::string > &a_names) const override
Public Member Functions inherited from NullMoist
NullMoist ()
virtual ~NullMoist ()=default
virtual int Qstate_NonMoist_Size ()
virtual void GetPlotVarNames (amrex::Vector< std::string > &a_vec) const
virtual void GetPlotVar (const std::string &, amrex::MultiFab &) const
virtual void GetPlotVar (const std::string &a_name, amrex::MultiFab &a_mf, const int) const
virtual void SetCurrentLevel (const int &)
virtual void InitLevel (const int, const amrex::MultiFab &)
virtual int getDiagnosticsInterval () const
virtual void Set_RealWidth (const int)
Static Public Attributes
static constexpr amrex::Real dtcldcr = amrex::Real(120.0)
static constexpr amrex::Real n0r = amrex::Real(8.0e6)
static constexpr amrex::Real avtr = amrex::Real(841.9)
static constexpr amrex::Real bvtr = amrex::Real(0.8)
static constexpr amrex::Real r0 = amrex::Real(0.8e-5)
static constexpr amrex::Real peaut = amrex::Real(0.55)
static constexpr amrex::Real xncr = amrex::Real(3.0e8)
static constexpr amrex::Real xmyu = amrex::Real(1.718e-5)
static constexpr amrex::Real avts = amrex::Real(11.72)
static constexpr amrex::Real bvts = amrex::Real(0.41)
static constexpr amrex::Real lamdarmax = amrex::Real(8.0e4)
static constexpr amrex::Real lamdasmax = amrex::Real(1.0e5)
static constexpr amrex::Real dicon = amrex::Real(11.9)
static constexpr amrex::Real dimax = amrex::Real(500.0e-6)
static constexpr amrex::Real pfrz1 = amrex::Real(100.0)
static constexpr amrex::Real pfrz2 = amrex::Real(0.66)
static constexpr amrex::Real qcrmin = amrex::Real(1.0e-9)
static constexpr amrex::Real eacrc = amrex::Real(1.0)
static constexpr amrex::Real dens_snow = amrex::Real(100.0)
static constexpr amrex::Real qs0 = amrex::Real(6.0e-4)
static constexpr amrex::Real n0smax = amrex::Real(1.0e11)
static constexpr amrex::Real n0s = amrex::Real(2.0e6)
static constexpr amrex::Real alpha_wsm6 = amrex::Real(0.12)
Private Types
using FabPtr = std::shared_ptr< amrex::MultiFab >
Private Member Functions
void initialize_coeffs ()
Private Attributes
int m_qmoist_size = 3
int n_qstate_moist_size = 6
int n_qstate_moist_numconc_size = 0
amrex::Vector< int > MicVarMap
amrex::Geometry m_geom
amrex::Real dt {0.0}
amrex::Real m_dzmin {0.0}
int nlev {0}
int zlo {0}
int zhi {0}
int m_axis {2}
bool m_do_cond {true}
amrex::MultiFab * m_z_phys_nd {nullptr}
amrex::MultiFab * m_detJ_cc {nullptr}
amrex::Array< FabPtr, MicVar_WSM6::NumVars > mic_fab_vars
bool m_hail_opt {false}
amrex::Real m_n0g {0}
amrex::Real m_deng {0}
amrex::Real m_avtg {0}
amrex::Real m_bvtg {0}
amrex::Real m_lamdagmax {0}
amrex::Real m_pi_wsm6 {0}
amrex::Real m_xlv1 {0}
amrex::Real m_qc0 {0}
amrex::Real m_qck1 {0}
amrex::Real m_pidnc {0}
amrex::Real m_bvtr1 {0}
amrex::Real m_bvtr2 {0}
amrex::Real m_bvtr3 {0}
amrex::Real m_bvtr4 {0}
amrex::Real m_bvtr6 {0}
amrex::Real m_g1pbr {0}
amrex::Real m_g3pbr {0}
amrex::Real m_g4pbr {0}
amrex::Real m_g5pbro2 {0}
amrex::Real m_g6pbr {0}
amrex::Real m_pvtr {0}
amrex::Real m_eacrr {0}
amrex::Real m_pacrr {0}
amrex::Real m_precr1 {0}
amrex::Real m_precr2 {0}
amrex::Real m_roqimax {0}
amrex::Real m_bvts1 {0}
amrex::Real m_bvts2 {0}
amrex::Real m_bvts3 {0}
amrex::Real m_bvts4 {0}
amrex::Real m_g1pbs {0}
amrex::Real m_g3pbs {0}
amrex::Real m_g4pbs {0}
amrex::Real m_g5pbso2 {0}
amrex::Real m_pvts {0}
amrex::Real m_pacrs {0}
amrex::Real m_precs1 {0}
amrex::Real m_precs2 {0}
amrex::Real m_pidn0r {0}
amrex::Real m_pidn0s {0}
amrex::Real m_pacrc {0}
amrex::Real m_bvtg1 {0}
amrex::Real m_bvtg2 {0}
amrex::Real m_bvtg3 {0}
amrex::Real m_bvtg4 {0}
amrex::Real m_g1pbg {0}
amrex::Real m_g3pbg {0}
amrex::Real m_g4pbg {0}
amrex::Real m_g5pbgo2 {0}
amrex::Real m_pvtg {0}
amrex::Real m_pacrg {0}
amrex::Real m_precg1 {0}
amrex::Real m_precg2 {0}
amrex::Real m_pidn0g {0}
amrex::Real m_rslopermax {0}
amrex::Real m_rslopesmax {0}
amrex::Real m_rslopegmax {0}
amrex::Real m_rsloperbmax {0}
amrex::Real m_rslopesbmax {0}
amrex::Real m_rslopegbmax {0}
amrex::Real m_rsloper2max {0}
amrex::Real m_rslopes2max {0}
amrex::Real m_rslopeg2max {0}
amrex::Real m_rsloper3max {0}
amrex::Real m_rslopes3max {0}
amrex::Real m_rslopeg3max {0}
Member Typedef Documentation
FabPtr
using WSM6::FabPtr = std::shared_ptr<amrex::MultiFab> private
Constructor & Destructor Documentation
WSM6()
WSM6::WSM6 () inline
 {}
~WSM6()
virtual WSM6::~WSM6 () virtual default
Member Function Documentation
Advance()
void WSM6::Advance (const amrex::Real & dt_advance, const SolverChoice & solverChoice) override virtual
Reimplemented from NullMoist.
 {
     dt = dt_advance;
     int microphysics_debug = 0;
     std::string micro_diag_mode = "canonical";
     std::vector<std::string> micro_diag_tags = {"standing"};
     std::vector<std::string> micro_diag_expr = {"standing"};
     std::vector<std::string> micro_diag_store = {"standing"};
     std::vector<int> micro_diag_target_column;
     {
       amrex::ParmParse pp("erf");
       pp.query("microphysics_debug", microphysics_debug);
       pp.query("micro_diag_mode", micro_diag_mode);
       pp.queryarr("micro_diag_tags", micro_diag_tags);
       pp.queryarr("micro_diag_expr", micro_diag_expr);
       pp.queryarr("micro_diag_store", micro_diag_store);
       pp.queryarr("micro_diag_target_column", micro_diag_target_column);
     }
     microphysics_debug = std::max(0, std::min(2, microphysics_debug));
 #ifdef ERF_USE_WSM6_FORT
     const std::string micro_diag_mode_lower = [&]{ std::string m = micro_diag_mode; std::transform(m.begin(), m.end(), m.begin(), [](unsigned char c){ return static_cast<char>(std::tolower(c)); }); return m; }();
     const bool micro_diag_forensic = (micro_diag_mode_lower == "forensic" || micro_diag_mode_lower == "both");
     const int microphysics_debug_bridge = micro_diag_forensic
         ? microphysics_debug
         : std::min(microphysics_debug, 1);
     bool use_wsm6_cpp_answer = false;
     { amrex::ParmParse pp("erf");
       pp.query("use_wsm6_cpp_answer", use_wsm6_cpp_answer); }
     bool run_wsm6_fort = !use_wsm6_cpp_answer;
     static bool wsm6_inited = false;
     // Minimal phase-1 initialization for single-moment WSM6.
     if (!wsm6_inited) {
         constexpr double den0 = 1.28;                 // Standard dry-air density (kg/m^3)
         constexpr double denr = static_cast<double>(rhoh2o);
         constexpr double dens = static_cast<double>(rhos);
         constexpr double cl = static_cast<double>(Cp_l);
         constexpr double cpv = static_cast<double>(Cp_v);
         constexpr int hail_opt = 0;                   // Graupel mode
         mp_wsm6_init_c(den0, denr, dens, cl, cpv, hail_opt);
         wsm6_inited = true;
     }
 #endif
     constexpr double g = static_cast<double>(CONST_GRAV);
     constexpr double cpd = static_cast<double>(Cp_d);
     constexpr double cpv = static_cast<double>(Cp_v);
     constexpr double rd = static_cast<double>(R_d);
     constexpr double rv = static_cast<double>(R_v);
     constexpr double t0c = 273.15;
     constexpr double ep1 = static_cast<double>(R_v / R_d - one);
     amrex::ignore_unused(g, rd, ep1);
     constexpr double ep2 = static_cast<double>(R_d / R_v);
     constexpr double qmin = 1.0e-12;
     constexpr double xls = static_cast<double>(lsub);
     constexpr double xlv0 = static_cast<double>(lat_vap);
     constexpr double xlf0 = static_cast<double>(lat_ice);
     constexpr double den0 = 1.28;
     constexpr double denr = static_cast<double>(rhoh2o);
     constexpr double cliq = static_cast<double>(Cp_l);
     constexpr double cice = 2106.0;
     constexpr double psat = 610.78;
     for (MFIter mfi(*mic_fab_vars[MicVar_WSM6::qv], TileNoZ()); mfi.isValid(); ++mfi) {
         const Box box = mfi.tilebox();
         const Box fab_box = mfi.fabbox();
         auto const& t_arr = mic_fab_vars[MicVar_WSM6::tabs]->array(mfi);
         auto const& qv_arr = mic_fab_vars[MicVar_WSM6::qv]->array(mfi);
         auto const& qc_arr = mic_fab_vars[MicVar_WSM6::qc]->array(mfi);
         auto const& qi_arr = mic_fab_vars[MicVar_WSM6::qi]->array(mfi);
         auto const& qr_arr = mic_fab_vars[MicVar_WSM6::qr]->array(mfi);
         auto const& qs_arr = mic_fab_vars[MicVar_WSM6::qs]->array(mfi);
         auto const& qg_arr = mic_fab_vars[MicVar_WSM6::qg]->array(mfi);
         auto const& den_arr = mic_fab_vars[MicVar_WSM6::rho]->array(mfi);
         auto const& p_arr = mic_fab_vars[MicVar_WSM6::pres]->array(mfi);
         auto rain_arr = mic_fab_vars[MicVar_WSM6::rain_accum]->array(mfi);
         auto snow_arr = mic_fab_vars[MicVar_WSM6::snow_accum]->array(mfi);
         auto graup_arr = mic_fab_vars[MicVar_WSM6::graup_accum]->array(mfi);
         const int ilo = box.smallEnd(0);
         const int ihi = box.bigEnd(0);
         const int jlo = box.smallEnd(1);
         const int jhi = box.bigEnd(1);
         const int klo = box.smallEnd(2);
         const int khi = box.bigEnd(2);
         const bool has_target_override = (micro_diag_target_column.size() == 2);
         const int diag_i = has_target_override ? micro_diag_target_column[0] : ilo;
         const int diag_j = has_target_override ? micro_diag_target_column[1] : jlo;
         const int imlo = fab_box.smallEnd(0);
         const int imhi = fab_box.bigEnd(0);
         const int jmlo = fab_box.smallEnd(1);
         const int jmhi = fab_box.bigEnd(1);
         const int kmlo = fab_box.smallEnd(2);
         const int kmhi = fab_box.bigEnd(2);
         amrex::ignore_unused(ihi, jhi, diag_i, diag_j, imlo, imhi, jmlo, jmhi, kmlo, kmhi);
         const Real dz_val = m_geom.CellSize(2);
         FArrayBox delz_fab(fab_box, 1);
         auto const& delz_arr = delz_fab.array();
         ParallelFor(fab_box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             delz_arr(i,j,k) = dz_val;
         });
         const Array4<const Real> z_arr = (m_z_phys_nd) ? m_z_phys_nd->const_array(mfi) : Array4<const Real> {};
         ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             delz_arr(i,j,k) = (z_arr) ? Real(0.25) * ( (z_arr(i  ,j  ,k+1) - z_arr(i  ,j  ,k))
                                                      + (z_arr(i+1,j  ,k+1) - z_arr(i+1,j  ,k))
                                                      + (z_arr(i  ,j+1,k+1) - z_arr(i  ,j+1,k))
                                                      + (z_arr(i+1,j+1,k+1) - z_arr(i+1,j+1,k)) ) : dz_val;
         });
         Box box2d(box);
         box2d.makeSlab(2, 0);
         Box fab_box2d(fab_box);
         fab_box2d.makeSlab(2, 0);
         // Fortran bridge uses ims:ime, jms:jme storage bounds; these buffers must
         // therefore be allocated on fab_box extents even if C++ kernels only
         // update the valid tile slab (box2d).
         FArrayBox rainncv_fab(fab_box2d, 1);
         FArrayBox sr_fab(fab_box2d, 1);
         FArrayBox snowncv_fab(fab_box2d, 1);
         FArrayBox graupelncv_fab(fab_box2d, 1);
         FArrayBox rainacc_fab(fab_box2d, 1);
         FArrayBox snowacc_fab(fab_box2d, 1);
         FArrayBox graupacc_fab(fab_box2d, 1);
         auto const& rainncv_arr = rainncv_fab.array();
         auto const& sr_arr = sr_fab.array();
         auto const& snowncv_arr = snowncv_fab.array();
         auto const& graupelncv_arr = graupelncv_fab.array();
         auto const& rainacc_arr = rainacc_fab.array();
         auto const& snowacc_arr = snowacc_fab.array();
         auto const& graupacc_arr = graupacc_fab.array();
         ParallelFor(fab_box2d, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             rainncv_arr(i,j,k) = Real(0.0);
             sr_arr(i,j,k) = Real(0.0);
             snowncv_arr(i,j,k) = Real(0.0);
             graupelncv_arr(i,j,k) = Real(0.0);
             rainacc_arr(i,j,k) = Real(0.0);
             snowacc_arr(i,j,k) = Real(0.0);
             graupacc_arr(i,j,k) = Real(0.0);
         });
         ParallelFor(box2d, [=] AMREX_GPU_DEVICE (int i, int j, int) {
             rainacc_arr(i,j,0) = rain_arr(i,j,klo);
             snowacc_arr(i,j,0) = snow_arr(i,j,klo);
             graupacc_arr(i,j,0) = graup_arr(i,j,klo);
             rainncv_arr(i,j,0) = Real(0.0);
             sr_arr(i,j,0) = Real(0.0);
             snowncv_arr(i,j,0) = Real(0.0);
             graupelncv_arr(i,j,0) = Real(0.0);
         });
 #ifdef ERF_USE_WSM6_FORT
         if (run_wsm6_fort) {
             mp_wsm6_run_c(
                 t_arr.dataPtr(),
                 qv_arr.dataPtr(), qc_arr.dataPtr(), qi_arr.dataPtr(),
                 qr_arr.dataPtr(), qs_arr.dataPtr(), qg_arr.dataPtr(),
                 den_arr.dataPtr(), p_arr.dataPtr(), delz_arr.dataPtr(),
                 static_cast<double>(dt), g, cpd, cpv, rd, rv, t0c, ep1, ep2, qmin,
                 xls, xlv0, xlf0, den0, denr, cliq, cice, psat,
                 rainacc_arr.dataPtr(), rainncv_arr.dataPtr(), sr_arr.dataPtr(),
                 snowacc_arr.dataPtr(), snowncv_arr.dataPtr(),
                 graupacc_arr.dataPtr(), graupelncv_arr.dataPtr(),
                 imlo, imhi, jmlo, jmhi, kmlo, kmhi,
                 ilo, ihi, jlo, jhi, klo, khi, microphysics_debug_bridge, diag_i, diag_j);
         } else {
 #endif
         // --- Phase 4 native C++ kernel ---
         // box2d for 1D per-column arrays (already defined above)
         // delqrs1/2/3, delqi: surface precipitation flux accumulators
         FArrayBox delqrs1_fab(box2d,1);
         FArrayBox delqrs2_fab(box2d,1);
         FArrayBox delqrs3_fab(box2d,1);
         FArrayBox delqi_fab(box2d,1);
         FArrayBox tstepsnow_fab(box2d,1);
         FArrayBox tstepgraup_fab(box2d,1);
         auto const& delqrs1_arr    = delqrs1_fab.array();
         auto const& delqrs2_arr    = delqrs2_fab.array();
         auto const& delqrs3_arr    = delqrs3_fab.array();
         auto const& delqi_arr      = delqi_fab.array();
         auto const& tstepsnow_arr   = tstepsnow_fab.array();
         auto const& tstepgraup_arr  = tstepgraup_fab.array();
         ParallelFor(box2d, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             delqrs1_arr(i,j,k) = Real(0.0);
             delqrs2_arr(i,j,k) = Real(0.0);
             delqrs3_arr(i,j,k) = Real(0.0);
             delqi_arr(i,j,k) = Real(0.0);
             tstepsnow_arr(i,j,k) = Real(0.0);
             tstepgraup_arr(i,j,k) = Real(0.0);
         });
         // 3D working FABs
         FArrayBox denfac_fab(fab_box,1);  FArrayBox xni_fab(fab_box,1);
         FArrayBox cpm_fab(fab_box,1);     FArrayBox xl_fab(fab_box,1);
         FArrayBox qsatw_fab(fab_box,1);   FArrayBox qsati_fab(fab_box,1);
         FArrayBox rhw_fab(fab_box,1);     FArrayBox rhi_fab(fab_box,1);
         FArrayBox den_tmp_fab(fab_box,1); FArrayBox delz_tmp_fab(fab_box,1);
         FArrayBox n0sfac_fab(fab_box,1);
         FArrayBox qrs_tmp_r_fab(fab_box,1); FArrayBox qrs_tmp_s_fab(fab_box,1);
         FArrayBox qrs_tmp_g_fab(fab_box,1);
         FArrayBox rslope_r_fab(fab_box,1);  FArrayBox rslope_s_fab(fab_box,1);
         FArrayBox rslope_g_fab(fab_box,1);
         FArrayBox rslope2_r_fab(fab_box,1); FArrayBox rslope2_s_fab(fab_box,1);
         FArrayBox rslope2_g_fab(fab_box,1);
         FArrayBox rslope3_r_fab(fab_box,1); FArrayBox rslope3_s_fab(fab_box,1);
         FArrayBox rslope3_g_fab(fab_box,1);
         FArrayBox rslopeb_r_fab(fab_box,1); FArrayBox rslopeb_s_fab(fab_box,1);
         FArrayBox rslopeb_g_fab(fab_box,1);
         FArrayBox work1_r_fab(fab_box,1);   FArrayBox work1_s_fab(fab_box,1);
         FArrayBox work1_g_fab(fab_box,1);
         FArrayBox work2_fab(fab_box,1);     FArrayBox workdiffw_fab(fab_box,1);
         FArrayBox workdiffi_fab(fab_box,1);
         FArrayBox workr_fab(fab_box,1);     FArrayBox worka_fab(fab_box,1);
         FArrayBox work1c_fab(fab_box,1);
         FArrayBox denqrs1_fab(fab_box,1);   FArrayBox denqrs2_fab(fab_box,1);
         FArrayBox denqrs3_fab(fab_box,1);   FArrayBox denqci_fab(fab_box,1);
         FArrayBox fall_r_fab(fab_box,1);    FArrayBox fall_s_fab(fab_box,1);
         FArrayBox fall_g_fab(fab_box,1);    FArrayBox fallc_fab(fab_box,1);
         FArrayBox qsum_fab(fab_box,1);
         FArrayBox nislfv_r_diag_fab(fab_box,6);
         FArrayBox nislfv_sg_diag_fab(fab_box,6);
         FArrayBox sed_cell_scratch_fab(fab_box, WSM6SedCellScratch::NumComps);
         Box sed_node_box = amrex::surroundingNodes(fab_box, 2);
         FArrayBox sed_node_scratch_fab(sed_node_box, WSM6SedNodeScratch::NumComps);
         // process rates
         FArrayBox praut_fab(fab_box,1); FArrayBox pracw_fab(fab_box,1);
         FArrayBox prevp_fab(fab_box,1); FArrayBox psdep_fab(fab_box,1);
         FArrayBox pgdep_fab(fab_box,1); FArrayBox psaut_fab(fab_box,1);
         FArrayBox pgaut_fab(fab_box,1); FArrayBox praci_fab(fab_box,1);
         FArrayBox piacr_fab(fab_box,1); FArrayBox psaci_fab(fab_box,1);
         FArrayBox psacw_fab(fab_box,1); FArrayBox pgacw_fab(fab_box,1);
         FArrayBox pgaci_fab(fab_box,1); FArrayBox paacw_fab(fab_box,1);
         FArrayBox pracs_fab(fab_box,1); FArrayBox psacr_fab(fab_box,1);
         FArrayBox pgacr_fab(fab_box,1); FArrayBox pgacs_fab(fab_box,1);
         FArrayBox pigen_fab(fab_box,1); FArrayBox pidep_fab(fab_box,1);
         FArrayBox pcond_fab(fab_box,1); FArrayBox psmlt_fab(fab_box,1);
         FArrayBox pgmlt_fab(fab_box,1); FArrayBox pseml_fab(fab_box,1);
         FArrayBox pgeml_fab(fab_box,1); FArrayBox psevp_fab(fab_box,1);
         FArrayBox pgevp_fab(fab_box,1);
         FArrayBox pimlt_fab(fab_box,1); FArrayBox pihmf_fab(fab_box,1);
         FArrayBox pihtf_fab(fab_box,1); FArrayBox pgfrz_fab(fab_box,1);
         auto const& denfac_arr    = denfac_fab.array();
         auto const& xni_arr       = xni_fab.array();
         auto const& cpm_arr       = cpm_fab.array();
         auto const& xl_arr        = xl_fab.array();
         auto const& qsatw_arr     = qsatw_fab.array();
         auto const& qsati_arr     = qsati_fab.array();
         auto const& rhw_arr       = rhw_fab.array();
         auto const& rhi_arr       = rhi_fab.array();
         auto const& den_tmp_arr   = den_tmp_fab.array();
         auto const& delz_tmp_arr  = delz_tmp_fab.array();
         auto const& n0sfac_arr    = n0sfac_fab.array();
         auto const& qrs_tmp_r_arr = qrs_tmp_r_fab.array();
         auto const& qrs_tmp_s_arr = qrs_tmp_s_fab.array();
         auto const& qrs_tmp_g_arr = qrs_tmp_g_fab.array();
         auto const& rslope_r_arr  = rslope_r_fab.array();
         auto const& rslope_s_arr  = rslope_s_fab.array();
         auto const& rslope_g_arr  = rslope_g_fab.array();
         auto const& rslope2_r_arr = rslope2_r_fab.array();
         auto const& rslope2_s_arr = rslope2_s_fab.array();
         auto const& rslope2_g_arr = rslope2_g_fab.array();
         auto const& rslope3_r_arr = rslope3_r_fab.array();
         auto const& rslope3_s_arr = rslope3_s_fab.array();
         auto const& rslope3_g_arr = rslope3_g_fab.array();
         auto const& rslopeb_r_arr = rslopeb_r_fab.array();
         auto const& rslopeb_s_arr = rslopeb_s_fab.array();
         auto const& rslopeb_g_arr = rslopeb_g_fab.array();
         auto const& work1_r_arr   = work1_r_fab.array();
         auto const& work1_s_arr   = work1_s_fab.array();
         auto const& work1_g_arr   = work1_g_fab.array();
         auto const& work2_arr     = work2_fab.array();
         auto const& workdiffw_arr = workdiffw_fab.array();
         auto const& workdiffi_arr = workdiffi_fab.array();
         auto const& workr_arr     = workr_fab.array();
         auto const& worka_arr     = worka_fab.array();
         auto const& work1c_arr    = work1c_fab.array();
         auto const& denqrs1_arr   = denqrs1_fab.array();
         auto const& denqrs2_arr   = denqrs2_fab.array();
         auto const& denqrs3_arr   = denqrs3_fab.array();
         auto const& denqci_arr    = denqci_fab.array();
         auto const& fall_r_arr    = fall_r_fab.array();
         auto const& fall_s_arr    = fall_s_fab.array();
         auto const& fall_g_arr    = fall_g_fab.array();
         auto const& fallc_arr     = fallc_fab.array();
         auto const& qsum_arr      = qsum_fab.array();
         auto const& nislfv_r_diag_arr = nislfv_r_diag_fab.array();
         auto const& nislfv_sg_diag_arr = nislfv_sg_diag_fab.array();
         auto const& sed_cell_scratch_arr = sed_cell_scratch_fab.array();
         auto const& sed_node_scratch_arr = sed_node_scratch_fab.array();
         ParallelFor(fab_box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             work1c_arr(i,j,k) = Real(0.0);
         });
         ParallelFor(fab_box, nislfv_r_diag_fab.nComp(), [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) {
             nislfv_r_diag_arr(i,j,k,n) = Real(0.0);
             nislfv_sg_diag_arr(i,j,k,n) = Real(0.0);
         });
         auto const& praut_arr     = praut_fab.array();
         auto const& pracw_arr     = pracw_fab.array();
         auto const& prevp_arr     = prevp_fab.array();
         auto const& psdep_arr     = psdep_fab.array();
         auto const& pgdep_arr     = pgdep_fab.array();
         auto const& psaut_arr     = psaut_fab.array();
         auto const& pgaut_arr     = pgaut_fab.array();
         auto const& praci_arr     = praci_fab.array();
         auto const& piacr_arr     = piacr_fab.array();
         auto const& psaci_arr     = psaci_fab.array();
         auto const& psacw_arr     = psacw_fab.array();
         auto const& pgacw_arr     = pgacw_fab.array();
         auto const& pgaci_arr     = pgaci_fab.array();
         auto const& paacw_arr     = paacw_fab.array();
         auto const& pracs_arr     = pracs_fab.array();
         auto const& psacr_arr     = psacr_fab.array();
         auto const& pgacr_arr     = pgacr_fab.array();
         auto const& pgacs_arr     = pgacs_fab.array();
         auto const& pigen_arr     = pigen_fab.array();
         auto const& pidep_arr     = pidep_fab.array();
         auto const& pcond_arr     = pcond_fab.array();
         auto const& psmlt_arr     = psmlt_fab.array();
         auto const& pgmlt_arr     = pgmlt_fab.array();
         auto const& pseml_arr     = pseml_fab.array();
         auto const& pgeml_arr     = pgeml_fab.array();
         auto const& psevp_arr     = psevp_fab.array();
         auto const& pgevp_arr     = pgevp_fab.array();
         auto const& pimlt_arr     = pimlt_fab.array();
         auto const& pihmf_arr     = pihmf_fab.array();
         auto const& pihtf_arr     = pihtf_fab.array();
         auto const& pgfrz_arr     = pgfrz_fab.array();
         // Groups A-E: pre-loop setup
         // Clamp negative values (Group A)
         ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             qc_arr(i,j,k) = amrex::max(qc_arr(i,j,k), Real(0.0));
             qr_arr(i,j,k) = amrex::max(qr_arr(i,j,k), Real(0.0));
             qi_arr(i,j,k) = amrex::max(qi_arr(i,j,k), Real(0.0));
             qs_arr(i,j,k) = amrex::max(qs_arr(i,j,k), Real(0.0));
             qg_arr(i,j,k) = amrex::max(qg_arr(i,j,k), Real(0.0));
             den_tmp_arr(i,j,k)  = den_arr(i,j,k);
             delz_tmp_arr(i,j,k) = delz_arr(i,j,k);
         });
         // Group B: cpm, xl — computed once from initial state [lines 455-460]
         const Real xlv1_loc = m_xlv1;
         ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             cpm_arr(i,j,k) = wsm6_cpmcal(qv_arr(i,j,k), Real(qmin), Real(cpd), Real(cpv));
             xl_arr(i,j,k)  = wsm6_xlcal(t_arr(i,j,k), Real(xlv0), xlv1_loc, Real(t0c));
         });
         // Outer minor timestep loop (Rule 29)
         const int wsm6_loops = std::max(
             static_cast<int>(std::round(dt / dtcldcr)), 1);
         const Real dtcld = dt / static_cast<Real>(wsm6_loops);
         const Real qc0    = m_qc0;
         const Real qck1   = m_qck1;
         const Real pvtr   = m_pvtr;
         const Real pacrr  = m_pacrr;
         const Real precr1 = m_precr1;
         const Real precr2 = m_precr2;
         const Real roqimax= m_roqimax;
         const Real pvts   = m_pvts;
         const Real pacrc  = m_pacrc;
         const Real precs1 = m_precs1;
         const Real precs2 = m_precs2;
         const Real g6pbr  = m_g6pbr;
         const Real pvtg   = m_pvtg;
         const Real pacrg  = m_pacrg;
         const Real precg1 = m_precg1;
         const Real precg2 = m_precg2;
         for (int loop = 0; loop < wsm6_loops; ++loop) {
             // G1b: denfac = sqrt(den0/den)  [lines 503-515]
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real invden = Real(1.0) / den_arr(i,j,k);
                 denfac_arr(i,j,k) = std::sqrt(invden * Real(den0));
             });
             // G1c: qsatw, qsati, rhw, rhi  [lines 517-549]
             {
                 const Real ttp  = Real(t0c) + Real(0.01);
                 const Real dldt = Real(cpv) - Real(cliq);
                 const Real xa   = -dldt / Real(rv);
                 const Real xb   =  xa + Real(xlv0) / (Real(rv)*ttp);
                 const Real dldti= Real(cpv) - Real(cice);
                 const Real xai  = -dldti / Real(rv);
                 const Real xbi  =  xai + Real(xls) / (Real(rv)*ttp);
                 ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                     const Real tr = ttp / t_arr(i,j,k);
                     Real qsw = Real(psat)*std::exp(std::log(tr)*xa)*std::exp(xb*(Real(1.0)-tr));
                     qsw = amrex::min(qsw, Real(0.99)*p_arr(i,j,k));
                     qsw = Real(ep2)*qsw / (p_arr(i,j,k) - qsw);
                     qsw = amrex::max(qsw, Real(qmin));
                     qsatw_arr(i,j,k) = qsw;
                     rhw_arr(i,j,k)   = amrex::max(qv_arr(i,j,k)/qsw, Real(qmin));
                     Real qsi = (t_arr(i,j,k) < ttp)
                         ? Real(psat)*std::exp(std::log(tr)*xai)*std::exp(xbi*(Real(1.0)-tr))
                         : Real(psat)*std::exp(std::log(tr)*xa )*std::exp(xb *(Real(1.0)-tr));
                     qsi = amrex::min(qsi, Real(0.99)*p_arr(i,j,k));
                     qsi = Real(ep2)*qsi / (p_arr(i,j,k) - qsi);
                     qsi = amrex::max(qsi, Real(qmin));
                     qsati_arr(i,j,k) = qsi;
                     rhi_arr(i,j,k)   = amrex::max(qv_arr(i,j,k)/qsi, Real(qmin));
                 });
             }
             // G2: zero all process rates each sub-step  [lines 555-594]
             // WSM6-CPP TAG: RATES_ZERO
             //   legacy_group: G2
             //   process: Zero all process rates each sub-step
             //   compare_vars: prevp, psdep, pgdep, praut, psaut, pgaut, pracw, praci, psaci, pracs, pidep, pcond, psmlt, pgmlt, pseml, psevp, fall_r, fall_s, fall_g, fallc
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 prevp_arr(i,j,k) = Real(0.0); psdep_arr(i,j,k) = Real(0.0);
                 pgdep_arr(i,j,k) = Real(0.0); praut_arr(i,j,k) = Real(0.0);
                 psaut_arr(i,j,k) = Real(0.0); pgaut_arr(i,j,k) = Real(0.0);
                 pracw_arr(i,j,k) = Real(0.0); praci_arr(i,j,k) = Real(0.0);
                 piacr_arr(i,j,k) = Real(0.0); psaci_arr(i,j,k) = Real(0.0);
                 psacw_arr(i,j,k) = Real(0.0); pracs_arr(i,j,k) = Real(0.0);
                 psacr_arr(i,j,k) = Real(0.0); pgacw_arr(i,j,k) = Real(0.0);
                 paacw_arr(i,j,k) = Real(0.0); pgaci_arr(i,j,k) = Real(0.0);
                 pgacr_arr(i,j,k) = Real(0.0); pgacs_arr(i,j,k) = Real(0.0);
                 pigen_arr(i,j,k) = Real(0.0); pidep_arr(i,j,k) = Real(0.0);
                 pcond_arr(i,j,k) = Real(0.0); psmlt_arr(i,j,k) = Real(0.0);
                 pgmlt_arr(i,j,k) = Real(0.0); pseml_arr(i,j,k) = Real(0.0);
                 pgeml_arr(i,j,k) = Real(0.0); psevp_arr(i,j,k) = Real(0.0);
                 pgevp_arr(i,j,k) = Real(0.0);
                 fall_r_arr(i,j,k) = Real(0.0); fall_s_arr(i,j,k) = Real(0.0);
                 fall_g_arr(i,j,k) = Real(0.0); fallc_arr(i,j,k) = Real(0.0);
             });
             // G3: xni ice crystal number concentration  [lines 598-604]
             // WSM6-CPP TAG: XNI
             //   legacy_group: G3
             //   process: Ice crystal number concentration
             //   compare_vars: xni, qi, den
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real tmp = den_arr(i,j,k)*amrex::max(qi_arr(i,j,k), Real(qmin));
                 xni_arr(i,j,k) = amrex::min(
                     amrex::max(Real(5.38e7)*std::sqrt(std::sqrt(tmp*tmp*tmp)), Real(1.e3)),
                     Real(1.e6));
             });
             // G4: pack qrs_tmp, first slope_wsm6 [lines 610-618]
             // WSM6-CPP TAG: SLOPE1
             //   legacy_group: G4
             //   process: First slope calculation
             //   compare_vars: rslope, rslope2, rslope3, rslopeb, falk, fall, work1
             const Real pidn0r_loc      = m_pidn0r;
             const Real rslopermax_loc  = m_rslopermax;
             const Real rsloperbmax_loc = m_rsloperbmax;
             const Real rsloper2max_loc = m_rsloper2max;
             const Real rsloper3max_loc = m_rsloper3max;
             const Real pidn0s_loc      = m_pidn0s;
             const Real rslopesmax_loc  = m_rslopesmax;
             const Real rslopesbmax_loc = m_rslopesbmax;
             const Real rslopes2max_loc = m_rslopes2max;
             const Real rslopes3max_loc = m_rslopes3max;
             const Real pidn0g_loc      = m_pidn0g;
             const Real rslopegmax_loc  = m_rslopegmax;
             const Real rslopegbmax_loc = m_rslopegbmax;
             const Real rslopeg2max_loc = m_rslopeg2max;
             const Real rslopeg3max_loc = m_rslopeg3max;
             const Real bvtg_loc        = m_bvtg;
             const Real pi_wsm6_loc     = m_pi_wsm6;
             const Real n0g_loc         = m_n0g;
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 qrs_tmp_r_arr(i,j,k) = qr_arr(i,j,k);
                 qrs_tmp_s_arr(i,j,k) = qs_arr(i,j,k);
                 qrs_tmp_g_arr(i,j,k) = qg_arr(i,j,k);
                 Real dummy_n0sfac;
                 wsm6_slope_rain_cell(
                     qrs_tmp_r_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     pidn0r_loc, Real(qcrmin), rslopermax_loc, rsloperbmax_loc,
                     rsloper2max_loc, rsloper3max_loc, Real(bvtr), Real(pvtr),
                     rslope_r_arr(i,j,k), rslopeb_r_arr(i,j,k),
                     rslope2_r_arr(i,j,k), rslope3_r_arr(i,j,k),
                     work1_r_arr(i,j,k));
                 wsm6_slope_snow_cell(
                     qrs_tmp_s_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     t_arr(i,j,k), pidn0s_loc, Real(alpha_wsm6),
                     Real(n0smax), Real(n0s), Real(t0c), Real(qcrmin),
                     rslopesmax_loc, rslopesbmax_loc,
                     rslopes2max_loc, rslopes3max_loc,
                     Real(bvts), Real(pvts),
                     rslope_s_arr(i,j,k), rslopeb_s_arr(i,j,k),
                     rslope2_s_arr(i,j,k), rslope3_s_arr(i,j,k),
                     work1_s_arr(i,j,k), dummy_n0sfac);
             wsm6_slope_graup_cell(
                     qrs_tmp_g_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     pidn0g_loc, Real(qcrmin),
                     rslopegmax_loc, rslopegbmax_loc,
                     rslopeg2max_loc, rslopeg3max_loc,
                     bvtg_loc, Real(pvtg),
                     rslope_g_arr(i,j,k), rslopeb_g_arr(i,j,k),
                     rslope2_g_arr(i,j,k), rslope3_g_arr(i,j,k),
                     work1_g_arr(i,j,k));
                 n0sfac_arr(i,j,k) = dummy_n0sfac;
             });
             // G5a-G5e: sedimentation setup, nislfv calls, and flux updates
             ParallelFor(box2d, [=] AMREX_GPU_DEVICE (int i, int j, int) {
                 const int km_local = khi - klo + 1;
                 constexpr Real qsum_min = Real(1.0e-15);
                 auto den_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::den);
                 };
                 auto denfac_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::denfac);
                 };
                 auto t_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::tk);
                 };
                 auto dz_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::dz);
                 };
                 auto workr_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::workr_col);
                 };
                 auto worka_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::worka_col);
                 };
                 auto denqrs1_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::denqrs1_col);
                 };
                 auto denqrs2_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::denqrs2_col);
                 };
                 auto denqrs3_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::denqrs3_col);
                 };
                 auto qsum_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::qsum_col);
                 };
                 Real delqrs1_col = Real(0.0);
                 Real delqrs2_col = Real(0.0);
                 Real delqrs3_col = Real(0.0);
                 // G5a: pack sedimentation work arrays
                 for (int k = klo; k <= khi; ++k) {
                     const int kk = k - klo;
                     den_col(kk)    = den_arr(i,j,k);
                     denfac_col(kk) = denfac_arr(i,j,k);
                     t_col(kk)      = t_arr(i,j,k);
                     dz_col(kk)     = delz_tmp_arr(i,j,k);
                     workr_col(kk)  = work1_r_arr(i,j,k);
                     qsum_col(kk)   = amrex::max(qs_arr(i,j,k) + qg_arr(i,j,k), qsum_min);
                     if (qsum_col(kk) > qsum_min) {
                         worka_col(kk) = (work1_s_arr(i,j,k) * qs_arr(i,j,k)
                                        + work1_g_arr(i,j,k) * qg_arr(i,j,k))
                                       / qsum_col(kk);
                     } else {
                         worka_col(kk) = Real(0.0);
                     }
                     denqrs1_col(kk) = den_col(kk) * qr_arr(i,j,k);
                     denqrs2_col(kk) = den_col(kk) * qs_arr(i,j,k);
                     denqrs3_col(kk) = den_col(kk) * qg_arr(i,j,k);
                     if (qr_arr(i,j,k) <= Real(0.0)) {
                         workr_col(kk) = Real(0.0);
                     }
                 }
                 // G5b: rain sedimentation
                 wsm6_nislfv_rain_plm_scratch(
                     km_local,
                     WSM6SedCellScratch::workr_col,
                     WSM6SedCellScratch::denqrs1_col,
                     &delqrs1_col, dtcld, 1,
                     sed_cell_scratch_arr, sed_node_scratch_arr, i, j, klo);
                 // Strict Rule 30 snapshot: immediately after G5b
                 for (int k = klo; k <= khi; ++k) {
                     const int kk = k - klo;
                     nislfv_r_diag_arr(i,j,k,0) = amrex::max(denqrs1_col(kk) / den_col(kk), Real(0.0));
                     nislfv_r_diag_arr(i,j,k,1) = denqrs1_col(kk) * workr_col(kk) / delz_arr(i,j,k);
                     nislfv_r_diag_arr(i,j,k,2) = workr_col(kk);
                     nislfv_r_diag_arr(i,j,k,3) = denqrs1_col(kk);
                     nislfv_r_diag_arr(i,j,k,4) = den_col(kk);
                     nislfv_r_diag_arr(i,j,k,5) = denfac_col(kk);
                 }
                 // G5c: snow + graupel sedimentation
                 wsm6_nislfv_rain_plm6_scratch(
                     km_local,
                     WSM6SedCellScratch::worka_col,
                     WSM6SedCellScratch::denqrs2_col,
                     WSM6SedCellScratch::denqrs3_col,
                     &delqrs2_col, &delqrs3_col, dtcld, 1,
                     sed_cell_scratch_arr, sed_node_scratch_arr, i, j, klo);
                 // Strict Rule 30 snapshot: immediately after G5c
                 for (int k = klo; k <= khi; ++k) {
                     const int kk = k - klo;
                     nislfv_sg_diag_arr(i,j,k,0) = amrex::max(denqrs2_col(kk) / den_col(kk), Real(0.0));
                     nislfv_sg_diag_arr(i,j,k,1) = amrex::max(denqrs3_col(kk) / den_col(kk), Real(0.0));
                     nislfv_sg_diag_arr(i,j,k,2) = denqrs2_col(kk) * worka_col(kk) / delz_arr(i,j,k);
                     nislfv_sg_diag_arr(i,j,k,3) = denqrs3_col(kk) * worka_col(kk) / delz_arr(i,j,k);
                     nislfv_sg_diag_arr(i,j,k,4) = denqrs2_col(kk);
                     nislfv_sg_diag_arr(i,j,k,5) = denqrs3_col(kk);
                 }
                 // G5d: update species and fall speeds
                 for (int k = klo; k <= khi; ++k) {
                     const int kk = k - klo;
                     qsum_arr(i,j,k) = qsum_col(kk);
                     workr_arr(i,j,k) = workr_col(kk);
                     worka_arr(i,j,k) = worka_col(kk);
                     denqrs1_arr(i,j,k) = denqrs1_col(kk);
                     denqrs2_arr(i,j,k) = denqrs2_col(kk);
                     denqrs3_arr(i,j,k) = denqrs3_col(kk);
                     qr_arr(i,j,k) = amrex::max(denqrs1_col(kk) / den_col(kk), Real(0.0));
                     qs_arr(i,j,k) = amrex::max(denqrs2_col(kk) / den_col(kk), Real(0.0));
                     qg_arr(i,j,k) = amrex::max(denqrs3_col(kk) / den_col(kk), Real(0.0));
                     fall_r_arr(i,j,k) = denqrs1_col(kk) * workr_col(kk) / delz_arr(i,j,k);
                     fall_s_arr(i,j,k) = denqrs2_col(kk) * worka_col(kk) / delz_arr(i,j,k);
                     fall_g_arr(i,j,k) = denqrs3_col(kk) * worka_col(kk) / delz_arr(i,j,k);
                 }
                 // G5e: slab fall fluxes at the lower boundary
                 delqrs1_arr(i,j,0) = delqrs1_col / delz_arr(i,j,klo) / dtcld;
                 delqrs2_arr(i,j,0) = delqrs2_col / delz_arr(i,j,klo) / dtcld;
                 delqrs3_arr(i,j,0) = delqrs3_col / delz_arr(i,j,klo) / dtcld;
                 fall_r_arr(i,j,klo) = delqrs1_arr(i,j,0);
                 fall_s_arr(i,j,klo) = delqrs2_arr(i,j,0);
                 fall_g_arr(i,j,klo) = delqrs3_arr(i,j,0);
             });
             // G6: repack qrs_tmp, second slope_wsm6 [lines 655-663]
             // slope params updated after sedimentation moved mass
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 qrs_tmp_r_arr(i,j,k) = qr_arr(i,j,k);
                 qrs_tmp_s_arr(i,j,k) = qs_arr(i,j,k);
                 qrs_tmp_g_arr(i,j,k) = qg_arr(i,j,k);
                 Real dummy_n0sfac;
                 wsm6_slope_rain_cell(
                     qrs_tmp_r_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     pidn0r_loc, Real(qcrmin), rslopermax_loc, rsloperbmax_loc,
                     rsloper2max_loc, rsloper3max_loc, Real(bvtr), Real(pvtr),
                     rslope_r_arr(i,j,k), rslopeb_r_arr(i,j,k),
                     rslope2_r_arr(i,j,k), rslope3_r_arr(i,j,k),
                     work1_r_arr(i,j,k));
                 wsm6_slope_snow_cell(
                     qrs_tmp_s_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     t_arr(i,j,k), pidn0s_loc, Real(alpha_wsm6),
                     Real(n0smax), Real(n0s), Real(t0c), Real(qcrmin),
                     rslopesmax_loc, rslopesbmax_loc,
                     rslopes2max_loc, rslopes3max_loc,
                     Real(bvts), Real(pvts),
                     rslope_s_arr(i,j,k), rslopeb_s_arr(i,j,k),
                     rslope2_s_arr(i,j,k), rslope3_s_arr(i,j,k),
                     work1_s_arr(i,j,k), dummy_n0sfac);
                 wsm6_slope_graup_cell(
                     qrs_tmp_g_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     pidn0g_loc, Real(qcrmin),
                     rslopegmax_loc, rslopegbmax_loc,
                     rslopeg2max_loc, rslopeg3max_loc,
                     bvtg_loc, Real(pvtg),
                     rslope_g_arr(i,j,k), rslopeb_g_arr(i,j,k),
                     rslope2_g_arr(i,j,k), rslope3_g_arr(i,j,k),
                     work1_g_arr(i,j,k));
             });
             // G7: melting (T>T0 only) [lines 665-704]
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real supcol = Real(t0c) - t_arr(i,j,k);
                 n0sfac_arr(i,j,k) = amrex::max(
                     amrex::min(std::exp(Real(alpha_wsm6) * supcol),
                                Real(n0smax) / Real(n0s)),
                     Real(1.0));
                 if (t_arr(i,j,k) > Real(t0c)) {
                     const Real xlf = Real(xlf0);
                     work2_arr(i,j,k) = wsm6_venfac(
                         p_arr(i,j,k), t_arr(i,j,k), den_arr(i,j,k), Real(den0));
                     if (qs_arr(i,j,k) > Real(0.0)) {
                         const Real coeres =
                             rslope2_s_arr(i,j,k) *
                             std::sqrt(rslope_s_arr(i,j,k) * rslopeb_s_arr(i,j,k));
                         psmlt_arr(i,j,k) =
                             wsm6_xka(t_arr(i,j,k), den_arr(i,j,k)) / xlf *
                             (Real(t0c) - t_arr(i,j,k)) * pi_wsm6_loc * Real(0.5) *
                             n0sfac_arr(i,j,k) *
                             (Real(precs1) * rslope2_s_arr(i,j,k) +
                              Real(precs2) * work2_arr(i,j,k) * coeres) /
                             den_arr(i,j,k);
                         psmlt_arr(i,j,k) = amrex::min(
                             amrex::max(psmlt_arr(i,j,k) * dtcld,
                                        -qs_arr(i,j,k)),
                             Real(0.0));
                         qs_arr(i,j,k) = qs_arr(i,j,k) + psmlt_arr(i,j,k);
                         qr_arr(i,j,k) = qr_arr(i,j,k) - psmlt_arr(i,j,k);
                         t_arr(i,j,k) = t_arr(i,j,k) + xlf / cpm_arr(i,j,k) * psmlt_arr(i,j,k);
                     }
                     if (qg_arr(i,j,k) > Real(0.0)) {
                         const Real coeres =
                             rslope2_g_arr(i,j,k) *
                             std::sqrt(rslope_g_arr(i,j,k) * rslopeb_g_arr(i,j,k));
                         pgmlt_arr(i,j,k) =
                             wsm6_xka(t_arr(i,j,k), den_arr(i,j,k)) / xlf *
                             (Real(t0c) - t_arr(i,j,k)) *
                             (Real(precg1) * rslope2_g_arr(i,j,k) +
                              Real(precg2) * work2_arr(i,j,k) * coeres) /
                             den_arr(i,j,k);
                         pgmlt_arr(i,j,k) = amrex::min(
                             amrex::max(pgmlt_arr(i,j,k) * dtcld,
                                        -qg_arr(i,j,k)),
                             Real(0.0));
                         qg_arr(i,j,k) = qg_arr(i,j,k) + pgmlt_arr(i,j,k);
                         qr_arr(i,j,k) = qr_arr(i,j,k) - pgmlt_arr(i,j,k);
                         t_arr(i,j,k) = t_arr(i,j,k) + xlf / cpm_arr(i,j,k) * pgmlt_arr(i,j,k);
                     }
                 }
             });
             // G8: cloud ice sedimentation/fallout [lines 708-735]
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 if (qi_arr(i,j,k) <= Real(0.0)) {
                     work1c_arr(i,j,k) = Real(0.0);
                 } else {
                     const Real tmp = den_arr(i,j,k) *
                         amrex::max(qi_arr(i,j,k), Real(qmin));
                     const Real xni = amrex::min(
                         amrex::max(Real(5.38e7) *
                                    std::sqrt(std::sqrt(tmp*tmp*tmp)),
                                    Real(1.0e3)),
                         Real(1.0e6));
                     const Real xmi = den_arr(i,j,k) * qi_arr(i,j,k) / xni;
                     const Real diameter = amrex::max(
                         amrex::min(Real(dicon) * std::sqrt(xmi), Real(dimax)),
                         Real(1.0e-25));
                     work1c_arr(i,j,k) = Real(1.49e4) *
                         std::exp(std::log(diameter) * Real(1.31));
                 }
                 denqci_arr(i,j,k) = den_arr(i,j,k) * qi_arr(i,j,k);
             });
             ParallelFor(box2d, [=] AMREX_GPU_DEVICE (int i, int j, int) {
                 const int km_local = khi - klo + 1;
                 auto den_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::den);
                 };
                 auto denfac_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::denfac);
                 };
                 auto t_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::tk);
                 };
                 auto dz_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::dz);
                 };
                 auto work1c_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::work1c_col);
                 };
                 auto denqci_col = [&](int k) -> amrex::Real& {
                     return sed_cell_scratch_arr(i, j, klo + k, WSM6SedCellScratch::denqci_col);
                 };
                 Real delqi_col = Real(0.0);
                 for (int k = klo; k <= khi; ++k) {
                     const int kk = k - klo;
                     den_col(kk)    = den_arr(i,j,k);
                     denfac_col(kk) = denfac_arr(i,j,k);
                     t_col(kk)      = t_arr(i,j,k);
                     dz_col(kk)     = delz_tmp_arr(i,j,k);
                     work1c_col(kk) = work1c_arr(i,j,k);
                     denqci_col(kk) = denqci_arr(i,j,k);
                 }
                 wsm6_nislfv_rain_plm_scratch(
                     km_local,
                     WSM6SedCellScratch::work1c_col,
                     WSM6SedCellScratch::denqci_col,
                     &delqi_col, dtcld, 0,
                     sed_cell_scratch_arr, sed_node_scratch_arr, i, j, klo);
                 for (int k = klo; k <= khi; ++k) {
                     const int kk = k - klo;
                     work1c_arr(i,j,k) = work1c_col(kk);
                     denqci_arr(i,j,k) = denqci_col(kk);
                     qi_arr(i,j,k) = amrex::max(
                         denqci_col(kk) / den_col(kk), Real(0.0));
                 }
                 delqi_arr(i,j,0) = delqi_col / delz_arr(i,j,klo) / dtcld;
                 fallc_arr(i,j,klo) = delqi_arr(i,j,0);
             });
             // G9: surface precipitation accumulation [lines 741-770]
             ParallelFor(box2d, [=] AMREX_GPU_DEVICE (int i, int j, int) {
                 const Real fallsum =
                     fall_r_arr(i,j,klo) + fall_s_arr(i,j,klo) +
                     fall_g_arr(i,j,klo) + fallc_arr(i,j,klo);
                 const Real fallsum_qsi = fall_s_arr(i,j,klo) + fallc_arr(i,j,klo);
                 const Real fallsum_qg = fall_g_arr(i,j,klo);
                 const Real precip = delz_arr(i,j,klo) / denr * dtcld * Real(1000.0);
                 if (fallsum > Real(0.0)) {
                     rainncv_arr(i,j,0) += fallsum * precip;
                     rainacc_arr(i,j,0) += fallsum * precip;
                 }
                 if (fallsum_qsi > Real(0.0)) {
                     tstepsnow_arr(i,j,0) += fallsum_qsi * precip;
                     snowncv_arr(i,j,0) += fallsum_qsi * precip;
                     snowacc_arr(i,j,0) += fallsum_qsi * precip;
                 }
                 if (fallsum_qg > Real(0.0)) {
                     tstepgraup_arr(i,j,0) += fallsum_qg * precip;
                     graupelncv_arr(i,j,0) += fallsum_qg * precip;
                     graupacc_arr(i,j,0) += fallsum_qg * precip;
                 }
                 if (fallsum > Real(0.0)) {
                     sr_arr(i,j,0) =
                         (snowncv_arr(i,j,0) + graupelncv_arr(i,j,0)) /
                         (rainncv_arr(i,j,0) + Real(1.0e-12));
                 }
             });
             constexpr Real pi = Real(3.141592653589793238462643383279502884);
             // G10: instantaneous phase changes [lines 774-830]
             // WSM6-CPP TAG: PHASE
             //   legacy_group: G10
             //   process: Instantaneous phase changes
             //   compare_vars: t, q, qci, qrs
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real supcol = Real(t0c) - t_arr(i,j,k);
                 const Real xlf = (supcol < Real(0.0))
                     ? Real(xlf0)
                     : Real(xls) - xl_arr(i,j,k);
                 pimlt_arr(i,j,k) = Real(0.0);
                 pihmf_arr(i,j,k) = Real(0.0);
                 pihtf_arr(i,j,k) = Real(0.0);
                 pgfrz_arr(i,j,k) = Real(0.0);
                 if (supcol < Real(0.0) && qi_arr(i,j,k) > Real(0.0)) {
                     pimlt_arr(i,j,k) = qi_arr(i,j,k);
                     qc_arr(i,j,k) = qc_arr(i,j,k) + qi_arr(i,j,k);
                     t_arr(i,j,k) = t_arr(i,j,k) - xlf / cpm_arr(i,j,k) * qi_arr(i,j,k);
                     qi_arr(i,j,k) = Real(0.0);
                 }
                 if (supcol > Real(40.0) && qc_arr(i,j,k) > Real(0.0)) {
                     pihmf_arr(i,j,k) = qc_arr(i,j,k);
                     qi_arr(i,j,k) = qi_arr(i,j,k) + qc_arr(i,j,k);
                     t_arr(i,j,k) = t_arr(i,j,k) + xlf / cpm_arr(i,j,k) * qc_arr(i,j,k);
                     qc_arr(i,j,k) = Real(0.0);
                 }
                 if (supcol > Real(0.0) && qc_arr(i,j,k) > Real(qmin)) {
                     const Real supcolt = amrex::min(supcol, Real(50.0));
                     const Real pfrzdtc = amrex::min(
                         Real(pfrz1) *
                         (std::exp(Real(pfrz2) * supcolt) - Real(1.0)) *
                         den_arr(i,j,k) / Real(denr) / Real(WSM6::xncr) *
                         qc_arr(i,j,k) * qc_arr(i,j,k) * dtcld,
                         qc_arr(i,j,k));
                     pihtf_arr(i,j,k) = pfrzdtc;
                     qi_arr(i,j,k) = qi_arr(i,j,k) + pfrzdtc;
                     t_arr(i,j,k) = t_arr(i,j,k) + xlf / cpm_arr(i,j,k) * pfrzdtc;
                     qc_arr(i,j,k) = qc_arr(i,j,k) - pfrzdtc;
                 }
                 if (supcol > Real(0.0) && qr_arr(i,j,k) > Real(0.0)) {
                     Real temp = rslope3_r_arr(i,j,k);
                     temp = temp * temp * rslope_r_arr(i,j,k);
                     const Real supcolt = amrex::min(supcol, Real(50.0));
                     const Real pfrzdtr = amrex::min(
                         Real(20.0) * pi * pi * Real(pfrz1) * Real(WSM6::n0r) *
                         Real(denr) / den_arr(i,j,k) *
                         (std::exp(Real(pfrz2) * supcolt) - Real(1.0)) *
                         temp * dtcld,
                         qr_arr(i,j,k));
                     pgfrz_arr(i,j,k) = pfrzdtr;
                     qg_arr(i,j,k) = qg_arr(i,j,k) + pfrzdtr;
                     t_arr(i,j,k) = t_arr(i,j,k) + xlf / cpm_arr(i,j,k) * pfrzdtr;
                     qr_arr(i,j,k) = qr_arr(i,j,k) - pfrzdtr;
                 }
             });
             // G11: third slope_wsm6 call [lines 836-844]
             // WSM6-CPP TAG: SLOPE3
             //   legacy_group: G11
             //   process: Third slope calculation
             //   compare_vars: rslope, rslope2, rslope3, rslopeb, falk, fall, work1
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 qrs_tmp_r_arr(i,j,k) = qr_arr(i,j,k);
                 qrs_tmp_s_arr(i,j,k) = qs_arr(i,j,k);
                 qrs_tmp_g_arr(i,j,k) = qg_arr(i,j,k);
                 Real dummy_n0sfac;
                 wsm6_slope_rain_cell(
                     qrs_tmp_r_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     pidn0r_loc, Real(qcrmin), rslopermax_loc, rsloperbmax_loc,
                     rsloper2max_loc, rsloper3max_loc, Real(bvtr), Real(pvtr),
                     rslope_r_arr(i,j,k), rslopeb_r_arr(i,j,k),
                     rslope2_r_arr(i,j,k), rslope3_r_arr(i,j,k),
                     work1_r_arr(i,j,k));
                 wsm6_slope_snow_cell(
                     qrs_tmp_s_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     t_arr(i,j,k), pidn0s_loc, Real(alpha_wsm6),
                     Real(n0smax), Real(n0s), Real(t0c), Real(qcrmin),
                     rslopesmax_loc, rslopesbmax_loc,
                     rslopes2max_loc, rslopes3max_loc,
                     Real(bvts), Real(pvts),
                     rslope_s_arr(i,j,k), rslopeb_s_arr(i,j,k),
                     rslope2_s_arr(i,j,k), rslope3_s_arr(i,j,k),
                     work1_s_arr(i,j,k), dummy_n0sfac);
                 wsm6_slope_graup_cell(
                     qrs_tmp_g_arr(i,j,k), den_arr(i,j,k), denfac_arr(i,j,k),
                     pidn0g_loc, Real(qcrmin),
                     rslopegmax_loc, rslopegbmax_loc,
                     rslopeg2max_loc, rslopeg3max_loc,
                     bvtg_loc, Real(pvtg),
                     rslope_g_arr(i,j,k), rslopeb_g_arr(i,j,k),
                     rslope2_g_arr(i,j,k), rslope3_g_arr(i,j,k),
                     work1_g_arr(i,j,k));
                 n0sfac_arr(i,j,k) = dummy_n0sfac;
             });
             // G12: workdiffw, workdiffi, work2 [lines 851-857]
             // WSM6-CPP TAG: DIFF_PREP
             //   legacy_group: G12
             //   process: Prepare diffusion/work terms
             //   compare_vars: workdiffw, workdiffi, work2
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 workdiffw_arr(i,j,k) = wsm6_diffac(
                     xl_arr(i,j,k), p_arr(i,j,k), t_arr(i,j,k),
                     den_arr(i,j,k), qsatw_arr(i,j,k), Real(rv));
                 workdiffi_arr(i,j,k) = wsm6_diffac(
                     Real(xls), p_arr(i,j,k), t_arr(i,j,k),
                     den_arr(i,j,k), qsati_arr(i,j,k), Real(rv));
                 work2_arr(i,j,k) = wsm6_venfac(
                     p_arr(i,j,k), t_arr(i,j,k), den_arr(i,j,k), Real(den0));
             });
             // G13a: warm rain — praut, pracw, prevp [lines 867-903]
             {
                 const Real dtcld_l = dtcld;
                 const Real qmin_l  = Real(qmin);
                 const Real qcrmin_l= Real(qcrmin);
                 ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                     Real supsat = amrex::max(qv_arr(i,j,k), qmin_l)
                                 - qsatw_arr(i,j,k);
                     Real satdt  = supsat / dtcld_l;
                     // praut: C->R autoconversion
                     if (qc_arr(i,j,k) > Real(qc0)) {
                         praut_arr(i,j,k) = amrex::min(
                             Real(qck1)*std::pow(qc_arr(i,j,k), Real(7.0/3.0)),
                             qc_arr(i,j,k)/dtcld_l);
                     }
                     // pracw: C->R accretion by rain
                     if (qr_arr(i,j,k) > qcrmin_l && qc_arr(i,j,k) > qmin_l) {
                         pracw_arr(i,j,k) = amrex::min(
                             Real(pacrr)*rslope3_r_arr(i,j,k)
                             *rslopeb_r_arr(i,j,k)
                             *qc_arr(i,j,k)*denfac_arr(i,j,k),
                             qc_arr(i,j,k)/dtcld_l);
                     }
                     // prevp: R evaporation/condensation
                     if (qr_arr(i,j,k) > Real(0.0)) {
                         Real coeres = rslope2_r_arr(i,j,k)*std::sqrt(
                             rslope_r_arr(i,j,k)*rslopeb_r_arr(i,j,k));
                         Real rate = (rhw_arr(i,j,k)-Real(1.0))
                             *(Real(precr1)*rslope2_r_arr(i,j,k)
                             + Real(precr2)*work2_arr(i,j,k)*coeres)
                             / workdiffw_arr(i,j,k);
                         if (rate < Real(0.0)) {
                             rate = amrex::max(rate, -qr_arr(i,j,k)/dtcld_l);
                             rate = amrex::max(rate, satdt/Real(2.0));
                         } else {
                             rate = amrex::min(rate, satdt/Real(2.0));
                         }
                         prevp_arr(i,j,k) = rate;
                     }
                 });
             }
             // G13b: cold-rain, mixed-phase, and ice deposition/nucleation
             // [lines 904-1062, 1075-1192]
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real supcol = Real(t0c) - t_arr(i,j,k);
                 n0sfac_arr(i,j,k) = amrex::max(
                     amrex::min(std::exp(Real(alpha_wsm6) * supcol),
                                Real(n0smax) / Real(n0s)),
                     Real(1.0));
                 const Real supsat = amrex::max(qv_arr(i,j,k), Real(qmin))
                                   - qsati_arr(i,j,k);
                 const Real satdt = supsat / dtcld;
                 int ifsat = 0;
                 const Real tmp = den_arr(i,j,k)
                                * amrex::max(qi_arr(i,j,k), Real(qmin));
                 const Real temp = std::sqrt(std::sqrt(tmp * tmp * tmp));
                 xni_arr(i,j,k) = amrex::min(
                     amrex::max(Real(5.38e7) * temp, Real(1.0e3)),
                     Real(1.0e6));
                 const Real xni = xni_arr(i,j,k);
                 const Real eacrs = std::exp(Real(0.07) * (-supcol));
                 const Real xmi = den_arr(i,j,k) * qi_arr(i,j,k) / xni;
                 const Real diameter = amrex::min(
                     Real(dicon) * std::sqrt(xmi), Real(dimax));
                 const Real vt2i = Real(1.49e4) * std::pow(diameter, Real(1.31));
                 const Real vt2r = Real(pvtr) * rslopeb_r_arr(i,j,k)
                                 * denfac_arr(i,j,k);
                 const Real vt2s = Real(pvts) * rslopeb_s_arr(i,j,k)
                                 * denfac_arr(i,j,k);
                 const Real vt2g = Real(pvtg) * rslopeb_g_arr(i,j,k)
                                 * denfac_arr(i,j,k);
                 const Real qsum = amrex::max(qsum_arr(i,j,k), Real(1.0e-15));
                 const Real vt2ave = (qsum > Real(1.0e-15))
                     ? (vt2s * qs_arr(i,j,k) + vt2g * qg_arr(i,j,k)) / qsum
                     : Real(0.0);
                 if (supcol > Real(0.0) && qi_arr(i,j,k) > Real(qmin)) {
                     if (qr_arr(i,j,k) > Real(qcrmin)) {
                         const Real acrfac =
                             Real(2.0) * rslope3_r_arr(i,j,k)
                           + Real(2.0) * diameter * rslope2_r_arr(i,j,k)
                           + diameter * diameter * rslope_r_arr(i,j,k);
                         // WSM6-CPP TAG: PRACI
                         //   legacy_group: G13b
                         //   process: Accretion of cloud ice by rain
                         //   compare_vars: praci, qi, qr, den
                         praci_arr(i,j,k) = Real(pi) * qi_arr(i,j,k) * Real(n0r)
                             * std::abs(vt2r - vt2i) * acrfac / Real(4.0);
                         praci_arr(i,j,k) *= std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qr_arr(i,j,k) / qi_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0));
                         praci_arr(i,j,k) = amrex::min(
                             praci_arr(i,j,k), qi_arr(i,j,k) / dtcld);
                         piacr_arr(i,j,k) = Real(pi) * Real(pi) * Real(avtr)
                             * Real(n0r) * Real(denr) * xni * denfac_arr(i,j,k)
                             * Real(g6pbr) * rslope3_r_arr(i,j,k)
                             * rslope3_r_arr(i,j,k) * rslopeb_r_arr(i,j,k)
                             / Real(24.0) / den_arr(i,j,k);
                         piacr_arr(i,j,k) *= std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qi_arr(i,j,k) / qr_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0));
                         piacr_arr(i,j,k) = amrex::min(
                             piacr_arr(i,j,k), qr_arr(i,j,k) / dtcld);
                     }
                     if (qs_arr(i,j,k) > Real(qcrmin)) {
                         const Real acrfac =
                             Real(2.0) * rslope3_s_arr(i,j,k)
                           + Real(2.0) * diameter * rslope2_s_arr(i,j,k)
                           + diameter * diameter * rslope_s_arr(i,j,k);
                         // WSM6-CPP TAG: PSACI
                         //   legacy_group: G13e
                         //   process: Accretion of cloud ice by snow
                         //   compare_vars: psaci, qi, qs, den
                         psaci_arr(i,j,k) = Real(pi) * qi_arr(i,j,k) * eacrs
                             * Real(n0s) * n0sfac_arr(i,j,k)
                             * std::abs(vt2ave - vt2i) * acrfac / Real(4.0);
                         psaci_arr(i,j,k) = amrex::min(
                             psaci_arr(i,j,k), qi_arr(i,j,k) / dtcld);
                     }
                     if (qg_arr(i,j,k) > Real(qcrmin)) {
                         const Real egi = std::exp(Real(0.07) * (-supcol));
                         const Real acrfac =
                             Real(2.0) * rslope3_g_arr(i,j,k)
                           + Real(2.0) * diameter * rslope2_g_arr(i,j,k)
                           + diameter * diameter * rslope_g_arr(i,j,k);
                         pgaci_arr(i,j,k) = Real(pi) * egi * qi_arr(i,j,k)
                               * n0g_loc * std::abs(vt2ave - vt2i) * acrfac
                              / Real(4.0);
                         pgaci_arr(i,j,k) = amrex::min(
                             pgaci_arr(i,j,k), qi_arr(i,j,k) / dtcld);
                     }
                 }
                 if (qs_arr(i,j,k) > Real(qcrmin) && qc_arr(i,j,k) > Real(qmin)) {
                     psacw_arr(i,j,k) = amrex::min(
                         Real(pacrc) * n0sfac_arr(i,j,k) * rslope3_s_arr(i,j,k)
                         * rslopeb_s_arr(i,j,k)
                         * std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qs_arr(i,j,k) / qc_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0))
                         * qc_arr(i,j,k) * denfac_arr(i,j,k),
                         qc_arr(i,j,k) / dtcld);
                 }
                 if (qg_arr(i,j,k) > Real(qcrmin) && qc_arr(i,j,k) > Real(qmin)) {
                     pgacw_arr(i,j,k) = amrex::min(
                         Real(pacrg) * rslope3_g_arr(i,j,k) * rslopeb_g_arr(i,j,k)
                         * std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qg_arr(i,j,k) / qc_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0))
                         * qc_arr(i,j,k) * denfac_arr(i,j,k),
                         qc_arr(i,j,k) / dtcld);
                 }
                 if (qsum > Real(1.0e-15)) {
                     paacw_arr(i,j,k) = (qs_arr(i,j,k) * psacw_arr(i,j,k)
                                       + qg_arr(i,j,k) * pgacw_arr(i,j,k))
                                      / qsum;
                 }
                 if (qs_arr(i,j,k) > Real(qcrmin) && qr_arr(i,j,k) > Real(qcrmin)) {
                     if (supcol > Real(0.0)) {
                         const Real acrfac =
                             Real(5.0) * rslope3_s_arr(i,j,k) * rslope3_s_arr(i,j,k)
                                 * rslope_r_arr(i,j,k)
                           + Real(2.0) * rslope3_s_arr(i,j,k) * rslope2_s_arr(i,j,k)
                                 * rslope2_r_arr(i,j,k)
                           + Real(0.5) * rslope2_s_arr(i,j,k) * rslope2_s_arr(i,j,k)
                                 * rslope3_r_arr(i,j,k);
                         // WSM6-CPP TAG: PRACS
                         //   legacy_group: G13f
                         //   process: Accretion of snow by rain / rain-snow interaction
                         //   compare_vars: pracs, qr, qs, den
                         pracs_arr(i,j,k) = Real(pi) * Real(pi) * Real(n0r)
                             * Real(n0s) * n0sfac_arr(i,j,k)
                             * std::abs(vt2r - vt2ave) * (Real(dens_snow) / den_arr(i,j,k))
                             * acrfac;
                         pracs_arr(i,j,k) *= std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qr_arr(i,j,k) / qs_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0));
                         pracs_arr(i,j,k) = amrex::min(
                             pracs_arr(i,j,k), qs_arr(i,j,k) / dtcld);
                     }
                     {
                         const Real acrfac =
                             Real(5.0) * rslope3_r_arr(i,j,k) * rslope3_r_arr(i,j,k)
                                 * rslope_s_arr(i,j,k)
                           + Real(2.0) * rslope3_r_arr(i,j,k) * rslope2_r_arr(i,j,k)
                                 * rslope2_s_arr(i,j,k)
                           + Real(0.5) * rslope2_r_arr(i,j,k) * rslope2_r_arr(i,j,k)
                                 * rslope3_s_arr(i,j,k);
                         psacr_arr(i,j,k) = Real(pi) * Real(pi) * Real(n0r)
                             * Real(n0s) * n0sfac_arr(i,j,k)
                             * std::abs(vt2ave - vt2r) * (Real(denr) / den_arr(i,j,k))
                             * acrfac;
                         psacr_arr(i,j,k) *= std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qs_arr(i,j,k) / qr_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0));
                         psacr_arr(i,j,k) = amrex::min(
                             psacr_arr(i,j,k), qr_arr(i,j,k) / dtcld);
                     }
                     if (qg_arr(i,j,k) > Real(qcrmin)) {
                         const Real acrfac =
                             Real(5.0) * rslope3_r_arr(i,j,k) * rslope3_r_arr(i,j,k)
                                 * rslope_g_arr(i,j,k)
                           + Real(2.0) * rslope3_r_arr(i,j,k) * rslope2_r_arr(i,j,k)
                                 * rslope2_g_arr(i,j,k)
                           + Real(0.5) * rslope2_r_arr(i,j,k) * rslope2_r_arr(i,j,k)
                                 * rslope3_g_arr(i,j,k);
                         pgacr_arr(i,j,k) = Real(pi) * Real(pi) * Real(n0r)
                             * n0g_loc * std::abs(vt2ave - vt2r)
                             * (Real(denr) / den_arr(i,j,k)) * acrfac;
                         pgacr_arr(i,j,k) *= std::pow(
                             amrex::min(
                                 amrex::max(Real(0.0), qg_arr(i,j,k) / qr_arr(i,j,k)),
                                 Real(1.0)),
                             Real(2.0));
                         pgacr_arr(i,j,k) = amrex::min(
                             pgacr_arr(i,j,k), qr_arr(i,j,k) / dtcld);
                     }
                 }
                 if (qg_arr(i,j,k) > Real(qcrmin) && qs_arr(i,j,k) > Real(qcrmin)) {
                     pgacs_arr(i,j,k) = Real(0.0);
                 }
                 if (supcol <= Real(0.0)) {
                     const Real xlf = Real(xlf0);
                     if (qs_arr(i,j,k) > Real(0.0)) {
                         // WSM6-CPP TAG: PSEML
                         //   legacy_group: G13g
                         //   process: Snow evaporation/sublimation
                         //   compare_vars: pseml, qs, qv, qsat, den
                         pseml_arr(i,j,k) = amrex::min(
                             amrex::max(
                                 Real(cliq) * supcol
                                 * (paacw_arr(i,j,k) + psacr_arr(i,j,k)) / xlf,
                                 -qs_arr(i,j,k) / dtcld),
                             Real(0.0));
                     }
                     if (qg_arr(i,j,k) > Real(0.0)) {
                         pgeml_arr(i,j,k) = amrex::min(
                             amrex::max(
                                 Real(cliq) * supcol
                                 * (paacw_arr(i,j,k) + pgacr_arr(i,j,k)) / xlf,
                                 -qg_arr(i,j,k) / dtcld),
                             Real(0.0));
                     }
                 }
                 if (supcol > Real(0.0)) {
                     if (qi_arr(i,j,k) > Real(0.0) && ifsat != 1) {
                         // WSM6-CPP TAG: PIDEP
                         //   legacy_group: G13h
                         //   process: Ice deposition/sublimation
                         //   compare_vars: pidep, qi, qv, qsat, den, t
                         pidep_arr(i,j,k) = Real(4.0) * diameter * xni
                             * (rhi_arr(i,j,k) - Real(1.0))
                             / workdiffi_arr(i,j,k);
                         Real supice = satdt - prevp_arr(i,j,k);
                         if (pidep_arr(i,j,k) < Real(0.0)) {
                             pidep_arr(i,j,k) = amrex::max(
                                 amrex::max(pidep_arr(i,j,k), satdt / Real(2.0)),
                                 supice);
                             pidep_arr(i,j,k) = amrex::max(
                                 pidep_arr(i,j,k), -qi_arr(i,j,k) / dtcld);
                         } else {
                             pidep_arr(i,j,k) = amrex::min(
                                 amrex::min(pidep_arr(i,j,k), satdt / Real(2.0)),
                                 supice);
                         }
                         if (std::abs(prevp_arr(i,j,k) + pidep_arr(i,j,k))
                             >= std::abs(satdt)) {
                             ifsat = 1;
                         }
                     }
                     if (qs_arr(i,j,k) > Real(0.0) && ifsat != 1) {
                         const Real coeres = rslope2_s_arr(i,j,k)
                                           * std::sqrt(rslope_s_arr(i,j,k)
                                                       * rslopeb_s_arr(i,j,k));
                         psdep_arr(i,j,k) = (rhi_arr(i,j,k) - Real(1.0))
                             * n0sfac_arr(i,j,k)
                             * (Real(precs1) * rslope2_s_arr(i,j,k)
                                + Real(precs2) * work2_arr(i,j,k) * coeres)
                             / workdiffi_arr(i,j,k);
                         Real supice = satdt - prevp_arr(i,j,k) - pidep_arr(i,j,k);
                         if (psdep_arr(i,j,k) < Real(0.0)) {
                             psdep_arr(i,j,k) = amrex::max(
                                 psdep_arr(i,j,k), -qs_arr(i,j,k) / dtcld);
                             psdep_arr(i,j,k) = amrex::max(
                                 amrex::max(psdep_arr(i,j,k), satdt / Real(2.0)),
                                 supice);
                         } else {
                             psdep_arr(i,j,k) = amrex::min(
                                 amrex::min(psdep_arr(i,j,k), satdt / Real(2.0)),
                                 supice);
                         }
                         if (std::abs(prevp_arr(i,j,k) + pidep_arr(i,j,k)
                                      + psdep_arr(i,j,k))
                             >= std::abs(satdt)) {
                             ifsat = 1;
                         }
                     }
                     if (qg_arr(i,j,k) > Real(0.0) && ifsat != 1) {
                         const Real coeres = rslope2_g_arr(i,j,k)
                                           * std::sqrt(rslope_g_arr(i,j,k)
                                                       * rslopeb_g_arr(i,j,k));
                         pgdep_arr(i,j,k) = (rhi_arr(i,j,k) - Real(1.0))
                             * (Real(precg1) * rslope2_g_arr(i,j,k)
                                + Real(precg2) * work2_arr(i,j,k) * coeres)
                             / workdiffi_arr(i,j,k);
                         Real supice = satdt - prevp_arr(i,j,k)
                                     - pidep_arr(i,j,k) - psdep_arr(i,j,k);
                         if (pgdep_arr(i,j,k) < Real(0.0)) {
                             pgdep_arr(i,j,k) = amrex::max(
                                 pgdep_arr(i,j,k), -qg_arr(i,j,k) / dtcld);
                             pgdep_arr(i,j,k) = amrex::max(
                                 amrex::max(pgdep_arr(i,j,k), satdt / Real(2.0)),
                                 supice);
                         } else {
                             pgdep_arr(i,j,k) = amrex::min(
                                 amrex::min(pgdep_arr(i,j,k), satdt / Real(2.0)),
                                 supice);
                         }
                         if (std::abs(prevp_arr(i,j,k) + pidep_arr(i,j,k)
                                      + psdep_arr(i,j,k) + pgdep_arr(i,j,k))
                             >= std::abs(satdt)) {
                             ifsat = 1;
                         }
                     }
                     if (supsat > Real(0.0) && ifsat != 1) {
                         const Real supice = satdt - prevp_arr(i,j,k)
                                            - pidep_arr(i,j,k)
                                            - psdep_arr(i,j,k)
                                            - pgdep_arr(i,j,k);
                         const Real xni0 = Real(1.0e3) * std::exp(Real(0.1) * supcol);
                         const Real roqi0 = Real(4.92e-11) * std::pow(xni0, Real(1.33));
                         pigen_arr(i,j,k) = amrex::max(
                             Real(0.0),
                             (roqi0 / den_arr(i,j,k)
                              - amrex::max(qi_arr(i,j,k), Real(0.0))) / dtcld);
                         pigen_arr(i,j,k) = amrex::min(
                             amrex::min(pigen_arr(i,j,k), satdt), supice);
                     }
                     if (qi_arr(i,j,k) > Real(0.0)) {
                         const Real qimax = Real(roqimax) / den_arr(i,j,k);
                         // WSM6-CPP TAG: PSAUT
                         //   legacy_group: G13i
                         //   process: Autoconversion to snow
                         //   compare_vars: psaut, qi, qs, den
                         psaut_arr(i,j,k) = amrex::max(
                             Real(0.0), (qi_arr(i,j,k) - qimax) / dtcld);
                     }
                     if (qs_arr(i,j,k) > Real(0.0)) {
                         const Real alpha2 = Real(1.0e-3)
                             * std::exp(Real(0.09) * (-supcol));
                         pgaut_arr(i,j,k) = amrex::min(
                             amrex::max(
                                 Real(0.0), alpha2 * (qs_arr(i,j,k) - Real(qs0))),
                             qs_arr(i,j,k) / dtcld);
                     }
                 }
                 if (supcol < Real(0.0)) {
                     if (qs_arr(i,j,k) > Real(0.0)
                         && rhw_arr(i,j,k) < Real(1.0)) {
                         const Real coeres = rslope2_s_arr(i,j,k)
                                           * std::sqrt(rslope_s_arr(i,j,k)
                                                       * rslopeb_s_arr(i,j,k));
                         // WSM6-CPP TAG: PSEVP
                         //   legacy_group: G13j
                         //   process: Graupel evaporation/sublimation
                         //   compare_vars: psevp, qg, qv, qsat, den
                         psevp_arr(i,j,k) = (rhw_arr(i,j,k) - Real(1.0))
                             * n0sfac_arr(i,j,k)
                             * (Real(precs1) * rslope2_s_arr(i,j,k)
                                + Real(precs2) * work2_arr(i,j,k) * coeres)
                             / workdiffw_arr(i,j,k);
                         psevp_arr(i,j,k) = amrex::min(
                             amrex::max(psevp_arr(i,j,k),
                                        -qs_arr(i,j,k) / dtcld),
                             Real(0.0));
                     }
                     if (qg_arr(i,j,k) > Real(0.0)
                         && rhw_arr(i,j,k) < Real(1.0)) {
                         const Real coeres = rslope2_g_arr(i,j,k)
                                           * std::sqrt(rslope_g_arr(i,j,k)
                                                       * rslopeb_g_arr(i,j,k));
                         pgevp_arr(i,j,k) = (rhw_arr(i,j,k) - Real(1.0))
                             * (Real(precg1) * rslope2_g_arr(i,j,k)
                                + Real(precg2) * work2_arr(i,j,k) * coeres)
                             / workdiffw_arr(i,j,k);
                         pgevp_arr(i,j,k) = amrex::min(
                             amrex::max(pgevp_arr(i,j,k),
                                        -qg_arr(i,j,k) / dtcld),
                             Real(0.0));
                     }
                 }
             });
             // G14: mass conservation check and state update [lines 1200-1388]
             // WSM6-CPP TAG: UPDATE
             //   legacy_group: G14
             //   process: Mass conservation and state update
             //   compare_vars: t, q, qci, qrs, qv
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real qmin_l  = Real(qmin);
                 const Real qcrmin_l= Real(qcrmin);
                 const Real t0c_l   = Real(t0c);
                 const Real delta2 =
                     (qr_arr(i,j,k) < Real(1.0e-4) && qs_arr(i,j,k) < Real(1.0e-4))
                     ? Real(1.0) : Real(0.0);
                 const Real delta3 =
                     (qr_arr(i,j,k) < Real(1.0e-4)) ? Real(1.0) : Real(0.0);
                 if (t_arr(i,j,k) <= t0c_l) {
                     Real value, source, factor, xlf, xlwork2;
                     value = amrex::max(qmin_l, qc_arr(i,j,k));
                     source = (praut_arr(i,j,k) + pracw_arr(i,j,k)
                             + paacw_arr(i,j,k) + paacw_arr(i,j,k)) * dtcld;
 //                            + paacw_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         praut_arr(i,j,k) = praut_arr(i,j,k) * factor;
                         pracw_arr(i,j,k) = pracw_arr(i,j,k) * factor;
                         paacw_arr(i,j,k) = paacw_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qmin_l, qi_arr(i,j,k));
                     source = (psaut_arr(i,j,k) - pigen_arr(i,j,k)
                             - pidep_arr(i,j,k) + praci_arr(i,j,k)
                             + psaci_arr(i,j,k) + pgaci_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         psaut_arr(i,j,k) = psaut_arr(i,j,k) * factor;
                         pigen_arr(i,j,k) = pigen_arr(i,j,k) * factor;
                         pidep_arr(i,j,k) = pidep_arr(i,j,k) * factor;
                         praci_arr(i,j,k) = praci_arr(i,j,k) * factor;
                         psaci_arr(i,j,k) = psaci_arr(i,j,k) * factor;
                         pgaci_arr(i,j,k) = pgaci_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qmin_l, qr_arr(i,j,k));
                     source = (-praut_arr(i,j,k) - prevp_arr(i,j,k)
                             - pracw_arr(i,j,k) + piacr_arr(i,j,k)
                             + psacr_arr(i,j,k) + pgacr_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         praut_arr(i,j,k) = praut_arr(i,j,k) * factor;
                         prevp_arr(i,j,k) = prevp_arr(i,j,k) * factor;
                         pracw_arr(i,j,k) = pracw_arr(i,j,k) * factor;
                         piacr_arr(i,j,k) = piacr_arr(i,j,k) * factor;
                         psacr_arr(i,j,k) = psacr_arr(i,j,k) * factor;
                         pgacr_arr(i,j,k) = pgacr_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qmin_l, qs_arr(i,j,k));
                     source = -(psdep_arr(i,j,k) + psaut_arr(i,j,k)
                              - pgaut_arr(i,j,k) + paacw_arr(i,j,k)
                              + piacr_arr(i,j,k) * delta3
                              + praci_arr(i,j,k) * delta3
                              - pracs_arr(i,j,k) * (Real(1.0) - delta2)
                              + psacr_arr(i,j,k) * delta2
                              + psaci_arr(i,j,k) - pgacs_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         psdep_arr(i,j,k) = psdep_arr(i,j,k) * factor;
                         psaut_arr(i,j,k) = psaut_arr(i,j,k) * factor;
                         pgaut_arr(i,j,k) = pgaut_arr(i,j,k) * factor;
                         paacw_arr(i,j,k) = paacw_arr(i,j,k) * factor;
                         piacr_arr(i,j,k) = piacr_arr(i,j,k) * factor;
                         praci_arr(i,j,k) = praci_arr(i,j,k) * factor;
                         psaci_arr(i,j,k) = psaci_arr(i,j,k) * factor;
                         pracs_arr(i,j,k) = pracs_arr(i,j,k) * factor;
                         psacr_arr(i,j,k) = psacr_arr(i,j,k) * factor;
                         pgacs_arr(i,j,k) = pgacs_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qmin_l, qg_arr(i,j,k));
                     source = -(pgdep_arr(i,j,k) + pgaut_arr(i,j,k)
                              + piacr_arr(i,j,k) * (Real(1.0) - delta3)
                              + praci_arr(i,j,k) * (Real(1.0) - delta3)
                              + psacr_arr(i,j,k) * (Real(1.0) - delta2)
                              + pracs_arr(i,j,k) * (Real(1.0) - delta2)
                              + pgaci_arr(i,j,k) + paacw_arr(i,j,k)
                              + pgacr_arr(i,j,k) + pgacs_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         pgdep_arr(i,j,k) = pgdep_arr(i,j,k) * factor;
                         pgaut_arr(i,j,k) = pgaut_arr(i,j,k) * factor;
                         piacr_arr(i,j,k) = piacr_arr(i,j,k) * factor;
                         praci_arr(i,j,k) = praci_arr(i,j,k) * factor;
                         psacr_arr(i,j,k) = psacr_arr(i,j,k) * factor;
                         pracs_arr(i,j,k) = pracs_arr(i,j,k) * factor;
                         paacw_arr(i,j,k) = paacw_arr(i,j,k) * factor;
                         pgaci_arr(i,j,k) = pgaci_arr(i,j,k) * factor;
                         pgacr_arr(i,j,k) = pgacr_arr(i,j,k) * factor;
                         pgacs_arr(i,j,k) = pgacs_arr(i,j,k) * factor;
                     }
                     work2_arr(i,j,k) = -(prevp_arr(i,j,k) + psdep_arr(i,j,k)
                                        + pgdep_arr(i,j,k) + pigen_arr(i,j,k)
                                        + pidep_arr(i,j,k));
                     qv_arr(i,j,k) = qv_arr(i,j,k) + work2_arr(i,j,k) * dtcld;
 //                                       + paacw_arr(i,j,k))
                     qc_arr(i,j,k) = amrex::max(
                         qc_arr(i,j,k) - (praut_arr(i,j,k) + pracw_arr(i,j,k)
                                        + paacw_arr(i,j,k) + paacw_arr(i,j,k))
                                        * dtcld,
                         Real(0.0));
                     qr_arr(i,j,k) = amrex::max(
                         qr_arr(i,j,k) + (praut_arr(i,j,k) + pracw_arr(i,j,k)
                                        + prevp_arr(i,j,k) - piacr_arr(i,j,k)
                                        - pgacr_arr(i,j,k) - psacr_arr(i,j,k))
                                        * dtcld,
                         Real(0.0));
                     qi_arr(i,j,k) = amrex::max(
                         qi_arr(i,j,k) - (psaut_arr(i,j,k) + praci_arr(i,j,k)
                                        + psaci_arr(i,j,k) + pgaci_arr(i,j,k)
                                        - pigen_arr(i,j,k) - pidep_arr(i,j,k))
                                        * dtcld,
                         Real(0.0));
                     qs_arr(i,j,k) = amrex::max(
                         qs_arr(i,j,k) + (psdep_arr(i,j,k) + psaut_arr(i,j,k)
                                        + paacw_arr(i,j,k) - pgaut_arr(i,j,k)
                                        + piacr_arr(i,j,k) * delta3
                                        + praci_arr(i,j,k) * delta3
                                        + psaci_arr(i,j,k) - pgacs_arr(i,j,k)
                                        - pracs_arr(i,j,k) * (Real(1.0) - delta2)
                                        + psacr_arr(i,j,k) * delta2) * dtcld,
                         Real(0.0));
                     qg_arr(i,j,k) = amrex::max(
                         qg_arr(i,j,k) + (pgdep_arr(i,j,k) + pgaut_arr(i,j,k)
                                        + piacr_arr(i,j,k) * (Real(1.0) - delta3)
                                        + praci_arr(i,j,k) * (Real(1.0) - delta3)
                                        + psacr_arr(i,j,k) * (Real(1.0) - delta2)
                                        + pracs_arr(i,j,k) * (Real(1.0) - delta2)
                                        + pgaci_arr(i,j,k) + paacw_arr(i,j,k)
                                        + pgacr_arr(i,j,k) + pgacs_arr(i,j,k))
                                        * dtcld,
                         Real(0.0));
                     xlf = Real(xls) - xl_arr(i,j,k);
                     xlwork2 = -Real(xls) * (psdep_arr(i,j,k) + pgdep_arr(i,j,k)
                                           + pidep_arr(i,j,k) + pigen_arr(i,j,k))
                             - xl_arr(i,j,k) * prevp_arr(i,j,k)
                             - xlf * (piacr_arr(i,j,k) + paacw_arr(i,j,k)
                                    + paacw_arr(i,j,k) + pgacr_arr(i,j,k)
                                    + psacr_arr(i,j,k));
                     t_arr(i,j,k) = t_arr(i,j,k) - xlwork2 / cpm_arr(i,j,k) * dtcld;
                 } else {
                     Real value, source, factor, xlf, xlwork2;
                     value = amrex::max(qmin_l, qc_arr(i,j,k));
                     source = (praut_arr(i,j,k) + pracw_arr(i,j,k)
                             + paacw_arr(i,j,k) + paacw_arr(i,j,k)) * dtcld;
 //                            + paacw_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         praut_arr(i,j,k) = praut_arr(i,j,k) * factor;
                         pracw_arr(i,j,k) = pracw_arr(i,j,k) * factor;
                         paacw_arr(i,j,k) = paacw_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qmin_l, qr_arr(i,j,k));
                     source = (-paacw_arr(i,j,k) - praut_arr(i,j,k)
                             + pseml_arr(i,j,k) + pgeml_arr(i,j,k)
                             - pracw_arr(i,j,k) - paacw_arr(i,j,k)
                             - prevp_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         praut_arr(i,j,k) = praut_arr(i,j,k) * factor;
                         prevp_arr(i,j,k) = prevp_arr(i,j,k) * factor;
                         pracw_arr(i,j,k) = pracw_arr(i,j,k) * factor;
                         paacw_arr(i,j,k) = paacw_arr(i,j,k) * factor;
                         pseml_arr(i,j,k) = pseml_arr(i,j,k) * factor;
                         pgeml_arr(i,j,k) = pgeml_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qcrmin_l, qs_arr(i,j,k));
                     source = (pgacs_arr(i,j,k) - pseml_arr(i,j,k)
                             - psevp_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         pgacs_arr(i,j,k) = pgacs_arr(i,j,k) * factor;
                         psevp_arr(i,j,k) = psevp_arr(i,j,k) * factor;
                         pseml_arr(i,j,k) = pseml_arr(i,j,k) * factor;
                     }
                     value = amrex::max(qcrmin_l, qg_arr(i,j,k));
                     source = -(pgacs_arr(i,j,k) + pgevp_arr(i,j,k)
                              + pgeml_arr(i,j,k)) * dtcld;
                     if (source > value) {
                         factor = value / source;
                         pgacs_arr(i,j,k) = pgacs_arr(i,j,k) * factor;
                         pgevp_arr(i,j,k) = pgevp_arr(i,j,k) * factor;
                         pgeml_arr(i,j,k) = pgeml_arr(i,j,k) * factor;
                     }
                     work2_arr(i,j,k) = -(prevp_arr(i,j,k) + psevp_arr(i,j,k)
                                        + pgevp_arr(i,j,k));
                     qv_arr(i,j,k) = qv_arr(i,j,k) + work2_arr(i,j,k) * dtcld;
 //                                       + paacw_arr(i,j,k))
                     qc_arr(i,j,k) = amrex::max(
                         qc_arr(i,j,k) - (praut_arr(i,j,k) + pracw_arr(i,j,k)
                                        + paacw_arr(i,j,k) + paacw_arr(i,j,k))
                                        * dtcld,
                         Real(0.0));
                     qr_arr(i,j,k) = amrex::max(
                         qr_arr(i,j,k) + (praut_arr(i,j,k) + pracw_arr(i,j,k)
                                        + prevp_arr(i,j,k) + paacw_arr(i,j,k)
                                        + paacw_arr(i,j,k) - pseml_arr(i,j,k)
                                        - pgeml_arr(i,j,k)) * dtcld,
                         Real(0.0));
                     qs_arr(i,j,k) = amrex::max(
                         qs_arr(i,j,k) + (psevp_arr(i,j,k) - pgacs_arr(i,j,k)
                                        + pseml_arr(i,j,k)) * dtcld,
                         Real(0.0));
                     qg_arr(i,j,k) = amrex::max(
                         qg_arr(i,j,k) + (pgacs_arr(i,j,k) + pgevp_arr(i,j,k)
                                        + pgeml_arr(i,j,k)) * dtcld,
                         Real(0.0));
                     xlf = Real(xls) - xl_arr(i,j,k);
                     xlwork2 = -xl_arr(i,j,k) * (prevp_arr(i,j,k)
                                               + psevp_arr(i,j,k)
                                               + pgevp_arr(i,j,k))
                             - xlf * (pseml_arr(i,j,k) + pgeml_arr(i,j,k));
                     t_arr(i,j,k) = t_arr(i,j,k) - xlwork2 / cpm_arr(i,j,k) * dtcld;
                 }
             });
             // G15: second qsat computation [lines 1390-1420]
             // WSM6-CPP TAG: QSAT2
             //   legacy_group: G15
             //   process: Second saturation mixing ratio computation
             //   compare_vars: qs, qvs, den, denfac, t, p
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 const Real ttp   = Real(t0c) + Real(0.01);
                 const Real dldt  = Real(cpv) - Real(cliq);
                 const Real xa    = -dldt / Real(rv);
                 const Real xb    = xa + Real(xlv0) / (Real(rv) * ttp);
                 Real tr = ttp / t_arr(i,j,k);
                 Real qsw = Real(psat) * std::exp(std::log(tr) * xa)
                                      * std::exp(xb * (Real(1.0) - tr));
                 qsw = amrex::min(qsw, Real(0.99) * p_arr(i,j,k));
                 qsatw_arr(i,j,k) = Real(ep2) * qsw / (p_arr(i,j,k) - qsw);
                 qsatw_arr(i,j,k) = amrex::max(qsatw_arr(i,j,k), Real(qmin));
             });
             // G16: pcond condensational/evaporational update [lines 1427-1437]
             // WSM6-CPP TAG: PCOND
             //   legacy_group: G16
             //   process: Condensation/evaporation update
             //   compare_vars: pcond, t, qv, qc, qsat
             if (m_do_cond) {
                 ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                     const Real workcond = wsm6_conden(
                         t_arr(i,j,k), qv_arr(i,j,k), qsatw_arr(i,j,k),
                         xl_arr(i,j,k), cpm_arr(i,j,k), Real(qmin), Real(rv));
                     const Real work2loc = qc_arr(i,j,k) + workcond;
                     static_cast<void>(work2loc);
                     pcond_arr(i,j,k) = amrex::min(
                         amrex::max(workcond / dtcld, Real(0.0)),
                         amrex::max(qv_arr(i,j,k), Real(0.0)) / dtcld);
                     if (qc_arr(i,j,k) > Real(0.0) && workcond < Real(0.0)) {
                         pcond_arr(i,j,k) = amrex::max(workcond, -qc_arr(i,j,k)) / dtcld;
                     }
                     qv_arr(i,j,k) = qv_arr(i,j,k) - pcond_arr(i,j,k) * dtcld;
                     qc_arr(i,j,k) = amrex::max(
                         qc_arr(i,j,k) + pcond_arr(i,j,k) * dtcld,
                         Real(0.0));
                     t_arr(i,j,k) = t_arr(i,j,k)
                                  + pcond_arr(i,j,k) * xl_arr(i,j,k)
                                  / cpm_arr(i,j,k) * dtcld;
                 });
             }
             // G17: padding for small values [lines 1444-1449]
             // WSM6-CPP TAG: CLIP
             //   legacy_group: G17
             //   process: Padding/clipping for small values
             //   compare_vars: qv, qc, qr, qi, qs, qg
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 if (qc_arr(i,j,k) <= Real(qmin)) qc_arr(i,j,k) = Real(0.0);
                 if (qi_arr(i,j,k) <= Real(qmin)) qi_arr(i,j,k) = Real(0.0);
             });
         }
 #ifdef ERF_USE_WSM6_FORT
         }
 #endif
         ParallelFor(box2d, [=] AMREX_GPU_DEVICE (int i, int j, int) {
             rain_arr(i,j,klo) = rainacc_arr(i,j,0);
             snow_arr(i,j,klo) = snowacc_arr(i,j,0);
             graup_arr(i,j,klo) = graupacc_arr(i,j,0);
         });
     }
 }
Copy_Micro_to_State()
void WSM6::Copy_Micro_to_State (amrex::MultiFab & cons_in) override virtual
Reimplemented from NullMoist.
 {
     for (MFIter mfi(cons, TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const auto& box3d = mfi.tilebox();
         auto states = cons.array(mfi);
         auto rho = mic_fab_vars[MicVar_WSM6::rho]->array(mfi);
         auto theta = mic_fab_vars[MicVar_WSM6::theta]->array(mfi);
         auto tabs = mic_fab_vars[MicVar_WSM6::tabs]->array(mfi);
         auto qv = mic_fab_vars[MicVar_WSM6::qv]->array(mfi);
         auto qc = mic_fab_vars[MicVar_WSM6::qc]->array(mfi);
         auto qi = mic_fab_vars[MicVar_WSM6::qi]->array(mfi);
         auto qr = mic_fab_vars[MicVar_WSM6::qr]->array(mfi);
         auto qs = mic_fab_vars[MicVar_WSM6::qs]->array(mfi);
         auto qg = mic_fab_vars[MicVar_WSM6::qg]->array(mfi);
         ParallelFor(box3d, [=] AMREX_GPU_DEVICE(int i, int j, int k) {
             theta(i,j,k) = getThgivenRandT(rho(i,j,k), tabs(i,j,k), R_d / Cp_d, qv(i,j,k));
             states(i,j,k,RhoTheta_comp) = rho(i,j,k) * theta(i,j,k);
             states(i,j,k,RhoQ1_comp) = rho(i,j,k) * amrex::max(Real(0), qv(i,j,k));
             states(i,j,k,RhoQ2_comp) = rho(i,j,k) * amrex::max(Real(0), qc(i,j,k));
             states(i,j,k,RhoQ3_comp) = rho(i,j,k) * amrex::max(Real(0), qi(i,j,k));
             states(i,j,k,RhoQ4_comp) = rho(i,j,k) * amrex::max(Real(0), qr(i,j,k));
             states(i,j,k,RhoQ5_comp) = rho(i,j,k) * amrex::max(Real(0), qs(i,j,k));
             states(i,j,k,RhoQ6_comp) = rho(i,j,k) * amrex::max(Real(0), qg(i,j,k));
         });
     }
     cons.FillBoundary(m_geom.periodicity());
 }
Referenced by Update_State_Vars().
Copy_State_to_Micro()
void WSM6::Copy_State_to_Micro (const amrex::MultiFab & cons_in) override virtual
Reimplemented from NullMoist.
 {
     for (MFIter mfi(cons_in); mfi.isValid(); ++mfi) {
         // Match Morrison behavior: refresh microphysics ghost zones from state.
         // WSM6 Fortran reads the full (ims:ime, jms:jme, kms:kme) slab.
         const auto& box3d = mfi.growntilebox();
         auto states = cons_in.array(mfi);
         auto rho = mic_fab_vars[MicVar_WSM6::rho]->array(mfi);
         auto theta = mic_fab_vars[MicVar_WSM6::theta]->array(mfi);
         auto tabs = mic_fab_vars[MicVar_WSM6::tabs]->array(mfi);
         auto pres = mic_fab_vars[MicVar_WSM6::pres]->array(mfi);
         auto qv = mic_fab_vars[MicVar_WSM6::qv]->array(mfi);
         auto qc = mic_fab_vars[MicVar_WSM6::qc]->array(mfi);
         auto qi = mic_fab_vars[MicVar_WSM6::qi]->array(mfi);
         auto qr = mic_fab_vars[MicVar_WSM6::qr]->array(mfi);
         auto qs = mic_fab_vars[MicVar_WSM6::qs]->array(mfi);
         auto qg = mic_fab_vars[MicVar_WSM6::qg]->array(mfi);
         ParallelFor(box3d, [=] AMREX_GPU_DEVICE(int i, int j, int k) {
             rho(i,j,k) = states(i,j,k,Rho_comp);
             theta(i,j,k) = states(i,j,k,RhoTheta_comp) / states(i,j,k,Rho_comp);
             qv(i,j,k) = amrex::max(Real(0.0), states(i,j,k,RhoQ1_comp) / states(i,j,k,Rho_comp));
             qc(i,j,k) = amrex::max(Real(0.0), states(i,j,k,RhoQ2_comp) / states(i,j,k,Rho_comp));
             qi(i,j,k) = amrex::max(Real(0.0), states(i,j,k,RhoQ3_comp) / states(i,j,k,Rho_comp));
             qr(i,j,k) = amrex::max(Real(0.0), states(i,j,k,RhoQ4_comp) / states(i,j,k,Rho_comp));
             qs(i,j,k) = amrex::max(Real(0.0), states(i,j,k,RhoQ5_comp) / states(i,j,k,Rho_comp));
             qg(i,j,k) = amrex::max(Real(0.0), states(i,j,k,RhoQ6_comp) / states(i,j,k,Rho_comp));
             tabs(i,j,k) = getTgivenRandRTh(states(i,j,k,Rho_comp),
                                            states(i,j,k,RhoTheta_comp),
                                            qv(i,j,k));
             pres(i,j,k) = getPgivenRTh(states(i,j,k,RhoTheta_comp), qv(i,j,k));
         });
     }
 }
Referenced by Update_Micro_Vars().
Define()
void WSM6::Define (SolverChoice & sc) inline override virtual
Reimplemented from NullMoist.
     {
         m_axis = sc.ave_plane;
         m_do_cond = (!sc.use_shoc);
     }
Init()
void WSM6::Init (const amrex::MultiFab & cons_in, const amrex::BoxArray & grids, const amrex::Geometry & geom, const amrex::Real & dt_advance, std::unique_ptr< amrex::MultiFab > & z_phys_nd, std::unique_ptr< amrex::MultiFab > & detJ_cc) override virtual
Reimplemented from NullMoist.
 {
     dt = dt_advance;
     m_geom = geom;
     m_z_phys_nd = z_phys_nd.get();
     m_detJ_cc = detJ_cc.get();
     MicVarMap.resize(m_qmoist_size);
     MicVarMap = {MicVar_WSM6::rain_accum, MicVar_WSM6::snow_accum, MicVar_WSM6::graup_accum};
     for (int ivar = 0; ivar < MicVar_WSM6::NumVars; ++ivar) {
         mic_fab_vars[ivar] = std::make_shared<MultiFab>(cons_in.boxArray(), cons_in.DistributionMap(),
                                                         1, cons_in.nGrowVect());
         mic_fab_vars[ivar]->setVal(0.0);
     }
     nlev = m_geom.Domain().length(2);
     zlo = m_geom.Domain().smallEnd(2);
     zhi = m_geom.Domain().bigEnd(2);
     initialize_coeffs();
 }
initialize_coeffs()
void WSM6::initialize_coeffs () private
 {
     using amrex::Real;
     // Exact port of Fortran rgmma() — ERF_module_mp_wsm6.F90 lines 1472-1495
     // Weierstrass infinite product form for Gamma(x).
     // Special case x==1 returns 0.0 matching Fortran exactly.
     // Never triggered in practice (bvtr1=1.8, bvts1=1.41, etc.)
     // but preserved for bit-compatible validation against Fortran reference.
     // CPU-only: called from initialize_coeffs(), not from GPU kernels.
     auto rgmma = [](Real x) -> Real {
         if (x == Real(1.0)) return Real(0.0);
         constexpr Real euler = Real(0.577215664901532);
         Real result = x * std::exp(euler * x);
         for (int i = 1; i <= 10000; ++i) {
             Real y = Real(i);
             result = result * (Real(1.0) + x/y) * std::exp(-x/y);
         }
         return Real(1.0) / result;
     };
     // Physical constants matching mp_wsm6_init argument list
     // den0: reference air density at 850mb (kg/m^3)
     // denr: liquid water density — rhoh2o from ERF_Constants.H
     // dens_arg: snow density — dens_snow constexpr = 100.0
     // cl: specific heat liquid water — Cp_l from ERF_Constants.H
     // cpv: specific heat water vapor — Cp_v from ERF_Constants.H
     const Real den0     = Real(1.28);
     const Real denr     = Real(rhoh2o);
     const Real dens_arg = dens_snow;
     const Real cl       = Real(Cp_l);
     const Real cpv_loc  = Real(Cp_v);
     // hail_opt branch: 5 regime-dependent coefficients
     if (m_hail_opt) {
         m_n0g       = Real(4.0e4);
         m_deng      = Real(700.0);
         m_avtg      = Real(285.0);
         m_bvtg      = Real(0.8);
         m_lamdagmax = Real(2.0e4);
     } else {
         m_n0g       = Real(4.0e6);
         m_deng      = Real(500.0);
         m_avtg      = Real(330.0);
         m_bvtg      = Real(0.8);
         m_lamdagmax = Real(6.0e4);
     }
     m_pi_wsm6 = Real(4.0) * std::atan(Real(1.0));
     m_xlv1    = cl - cpv_loc;
     m_qc0  = Real(4.0)/Real(3.0) * m_pi_wsm6 * denr
               * std::pow(r0, Real(3.0)) * xncr / den0;
     m_qck1 = Real(0.104) * Real(9.8) * peaut
               / std::pow(xncr * denr, Real(1.0)/Real(3.0))
               / xmyu * std::pow(den0, Real(4.0)/Real(3.0));
     m_pidnc = m_pi_wsm6 * denr / Real(6.0);
     // Rain coefficients
     m_bvtr1   = Real(1.0) + bvtr;
     m_bvtr2   = Real(2.5) + Real(0.5) * bvtr;
     m_bvtr3   = Real(3.0) + bvtr;
     m_bvtr4   = Real(4.0) + bvtr;
     m_bvtr6   = Real(6.0) + bvtr;
     m_g1pbr   = rgmma(m_bvtr1);
     m_g3pbr   = rgmma(m_bvtr3);
     m_g4pbr   = rgmma(m_bvtr4);
     m_g6pbr   = rgmma(m_bvtr6);
     m_g5pbro2 = rgmma(m_bvtr2);
     m_pvtr    = avtr * m_g4pbr / Real(6.0);
     m_eacrr   = Real(1.0);
     m_pacrr   = m_pi_wsm6 * n0r * avtr * m_g3pbr * Real(0.25) * m_eacrr;
     m_precr1  = Real(2.0) * m_pi_wsm6 * n0r * Real(0.78);
     m_precr2  = Real(2.0) * m_pi_wsm6 * n0r * Real(0.31)
                 * std::pow(avtr, Real(0.5)) * m_g5pbro2;
     m_roqimax = Real(2.08e22) * std::pow(dimax, Real(8.0));
     // Snow coefficients
     m_bvts1   = Real(1.0) + bvts;
     m_bvts2   = Real(2.5) + Real(0.5) * bvts;
     m_bvts3   = Real(3.0) + bvts;
     m_bvts4   = Real(4.0) + bvts;
     m_g1pbs   = rgmma(m_bvts1);
     m_g3pbs   = rgmma(m_bvts3);
     m_g4pbs   = rgmma(m_bvts4);
     m_g5pbso2 = rgmma(m_bvts2);
     m_pvts    = avts * m_g4pbs / Real(6.0);
     m_pacrs   = m_pi_wsm6 * n0s * avts * m_g3pbs * Real(0.25);
     m_precs1  = Real(4.0) * n0s * Real(0.65);
     m_precs2  = Real(4.0) * n0s * Real(0.44)
                 * std::pow(avts, Real(0.5)) * m_g5pbso2;
     m_pidn0r  = m_pi_wsm6 * denr * n0r;
     m_pidn0s  = m_pi_wsm6 * dens_arg * n0s;
     m_pacrc   = m_pi_wsm6 * n0s * avts * m_g3pbs * Real(0.25) * eacrc;
     // Graupel/hail coefficients
     m_bvtg1   = Real(1.0) + m_bvtg;
     m_bvtg2   = Real(2.5) + Real(0.5) * m_bvtg;
     m_bvtg3   = Real(3.0) + m_bvtg;
     m_bvtg4   = Real(4.0) + m_bvtg;
     m_g1pbg   = rgmma(m_bvtg1);
     m_g3pbg   = rgmma(m_bvtg3);
     m_g4pbg   = rgmma(m_bvtg4);
     m_pacrg   = m_pi_wsm6 * m_n0g * m_avtg * m_g3pbg * Real(0.25);
     m_g5pbgo2 = rgmma(m_bvtg2);
     m_pvtg    = m_avtg * m_g4pbg / Real(6.0);
     m_precg1  = Real(2.0) * m_pi_wsm6 * m_n0g * Real(0.78);
     m_precg2  = Real(2.0) * m_pi_wsm6 * m_n0g * Real(0.31)
                 * std::pow(m_avtg, Real(0.5)) * m_g5pbgo2;
     m_pidn0g  = m_pi_wsm6 * m_deng * m_n0g;
     // Slope parameter limits
     m_rslopermax  = Real(1.0) / lamdarmax;
     m_rslopesmax  = Real(1.0) / lamdasmax;
     m_rslopegmax  = Real(1.0) / m_lamdagmax;
     m_rsloperbmax = std::pow(m_rslopermax, bvtr);
     m_rslopesbmax = std::pow(m_rslopesmax, bvts);
     m_rslopegbmax = std::pow(m_rslopegmax, m_bvtg);
     m_rsloper2max = m_rslopermax * m_rslopermax;
     m_rslopes2max = m_rslopesmax * m_rslopesmax;
     m_rslopeg2max = m_rslopegmax * m_rslopegmax;
     m_rsloper3max = m_rsloper2max * m_rslopermax;
     m_rslopes3max = m_rslopes2max * m_rslopesmax;
     m_rslopeg3max = m_rslopeg2max * m_rslopegmax;
 }
Qmoist_Ptr()
amrex::MultiFab* WSM6::Qmoist_Ptr (const int & varIdx) inline override virtual
Reimplemented from NullMoist.
     {
         AMREX_ALWAYS_ASSERT(varIdx < m_qmoist_size);
         return mic_fab_vars[MicVarMap[varIdx]].get();
     }
Qmoist_Restart_Vars()
void WSM6::Qmoist_Restart_Vars (const SolverChoice & , std::vector< int > & a_idx, std::vector< std::string > & a_names) const inline override virtual
Reimplemented from NullMoist.
     {
         a_idx = {0, 1, 2};
         a_names = {"RainAccum", "SnowAccum", "GraupAccum"};
     }
Qmoist_Size()
int WSM6::Qmoist_Size () inline override virtual
Reimplemented from NullMoist.
 { return m_qmoist_size; }
Qstate_Moist_NumConc_Size()
int WSM6::Qstate_Moist_NumConc_Size () inline override virtual
Reimplemented from NullMoist.
 { return n_qstate_moist_numconc_size; }
Qstate_Moist_Size()
int WSM6::Qstate_Moist_Size () inline override virtual
Reimplemented from NullMoist.
 { return n_qstate_moist_size; }
Set_dzmin()
void WSM6::Set_dzmin (const amrex::Real dz_min) inline override virtual
Reimplemented from NullMoist.
 { m_dzmin = dz_min; }
Update_Micro_Vars()
void WSM6::Update_Micro_Vars (amrex::MultiFab & cons_in) inline override virtual
Reimplemented from NullMoist.
     {
         Copy_State_to_Micro(cons_in);
     }
Update_State_Vars()
void WSM6::Update_State_Vars (amrex::MultiFab & cons_in, const amrex::MultiFab &) inline override virtual
Reimplemented from NullMoist.
     {
         Copy_Micro_to_State(cons_in);
     }
Member Data Documentation
alpha_wsm6
constexpr amrex::Real WSM6::alpha_wsm6 = amrex::Real(0.12) static constexpr
avtr
constexpr amrex::Real WSM6::avtr = amrex::Real(841.9) static constexpr
Referenced by wsm6_nislfv_rain_plm_scratch().
avts
constexpr amrex::Real WSM6::avts = amrex::Real(11.72) static constexpr
Referenced by wsm6_nislfv_rain_plm6_scratch().
bvtr
constexpr amrex::Real WSM6::bvtr = amrex::Real(0.8) static constexpr
Referenced by wsm6_nislfv_rain_plm_scratch().
bvts
constexpr amrex::Real WSM6::bvts = amrex::Real(0.41) static constexpr
Referenced by wsm6_nislfv_rain_plm6_scratch().
dens_snow
constexpr amrex::Real WSM6::dens_snow = amrex::Real(100.0) static constexpr
Referenced by wsm6_nislfv_rain_plm6_scratch().
dicon
constexpr amrex::Real WSM6::dicon = amrex::Real(11.9) static constexpr
dimax
constexpr amrex::Real WSM6::dimax = amrex::Real(500.0e-6) static constexpr
dt
amrex::Real WSM6::dt {0.0} private
dtcldcr
constexpr amrex::Real WSM6::dtcldcr = amrex::Real(120.0) static constexpr
eacrc
constexpr amrex::Real WSM6::eacrc = amrex::Real(1.0) static constexpr
lamdarmax
constexpr amrex::Real WSM6::lamdarmax = amrex::Real(8.0e4) static constexpr
Referenced by wsm6_nislfv_rain_plm_scratch().
lamdasmax
constexpr amrex::Real WSM6::lamdasmax = amrex::Real(1.0e5) static constexpr
Referenced by wsm6_nislfv_rain_plm6_scratch().
m_avtg
amrex::Real WSM6::m_avtg {0} private
m_axis
int WSM6::m_axis {2} private
Referenced by Define().
m_bvtg
amrex::Real WSM6::m_bvtg {0} private
m_bvtg1
amrex::Real WSM6::m_bvtg1 {0} private
m_bvtg2
amrex::Real WSM6::m_bvtg2 {0} private
m_bvtg3
amrex::Real WSM6::m_bvtg3 {0} private
m_bvtg4
amrex::Real WSM6::m_bvtg4 {0} private
m_bvtr1
amrex::Real WSM6::m_bvtr1 {0} private
m_bvtr2
amrex::Real WSM6::m_bvtr2 {0} private
m_bvtr3
amrex::Real WSM6::m_bvtr3 {0} private
m_bvtr4
amrex::Real WSM6::m_bvtr4 {0} private
m_bvtr6
amrex::Real WSM6::m_bvtr6 {0} private
m_bvts1
amrex::Real WSM6::m_bvts1 {0} private
m_bvts2
amrex::Real WSM6::m_bvts2 {0} private
m_bvts3
amrex::Real WSM6::m_bvts3 {0} private
m_bvts4
amrex::Real WSM6::m_bvts4 {0} private
m_deng
amrex::Real WSM6::m_deng {0} private
m_detJ_cc
amrex::MultiFab* WSM6::m_detJ_cc {nullptr} private
m_do_cond
bool WSM6::m_do_cond {true} private
Referenced by Define().
m_dzmin
amrex::Real WSM6::m_dzmin {0.0} private
Referenced by Set_dzmin().
m_eacrr
amrex::Real WSM6::m_eacrr {0} private
m_g1pbg
amrex::Real WSM6::m_g1pbg {0} private
m_g1pbr
amrex::Real WSM6::m_g1pbr {0} private
m_g1pbs
amrex::Real WSM6::m_g1pbs {0} private
m_g3pbg
amrex::Real WSM6::m_g3pbg {0} private
m_g3pbr
amrex::Real WSM6::m_g3pbr {0} private
m_g3pbs
amrex::Real WSM6::m_g3pbs {0} private
m_g4pbg
amrex::Real WSM6::m_g4pbg {0} private
m_g4pbr
amrex::Real WSM6::m_g4pbr {0} private
m_g4pbs
amrex::Real WSM6::m_g4pbs {0} private
m_g5pbgo2
amrex::Real WSM6::m_g5pbgo2 {0} private
m_g5pbro2
amrex::Real WSM6::m_g5pbro2 {0} private
m_g5pbso2
amrex::Real WSM6::m_g5pbso2 {0} private
m_g6pbr
amrex::Real WSM6::m_g6pbr {0} private
m_geom
amrex::Geometry WSM6::m_geom private
m_hail_opt
bool WSM6::m_hail_opt {false} private
m_lamdagmax
amrex::Real WSM6::m_lamdagmax {0} private
m_n0g
amrex::Real WSM6::m_n0g {0} private
m_pacrc
amrex::Real WSM6::m_pacrc {0} private
m_pacrg
amrex::Real WSM6::m_pacrg {0} private
m_pacrr
amrex::Real WSM6::m_pacrr {0} private
m_pacrs
amrex::Real WSM6::m_pacrs {0} private
m_pi_wsm6
amrex::Real WSM6::m_pi_wsm6 {0} private
m_pidn0g
amrex::Real WSM6::m_pidn0g {0} private
m_pidn0r
amrex::Real WSM6::m_pidn0r {0} private
m_pidn0s
amrex::Real WSM6::m_pidn0s {0} private
m_pidnc
amrex::Real WSM6::m_pidnc {0} private
m_precg1
amrex::Real WSM6::m_precg1 {0} private
m_precg2
amrex::Real WSM6::m_precg2 {0} private
m_precr1
amrex::Real WSM6::m_precr1 {0} private
m_precr2
amrex::Real WSM6::m_precr2 {0} private
m_precs1
amrex::Real WSM6::m_precs1 {0} private
m_precs2
amrex::Real WSM6::m_precs2 {0} private
m_pvtg
amrex::Real WSM6::m_pvtg {0} private
m_pvtr
amrex::Real WSM6::m_pvtr {0} private
m_pvts
amrex::Real WSM6::m_pvts {0} private
m_qc0
amrex::Real WSM6::m_qc0 {0} private
m_qck1
amrex::Real WSM6::m_qck1 {0} private
m_qmoist_size
int WSM6::m_qmoist_size = 3 private
Referenced by Qmoist_Ptr(), and Qmoist_Size().
m_roqimax
amrex::Real WSM6::m_roqimax {0} private
m_rslopeg2max
amrex::Real WSM6::m_rslopeg2max {0} private
m_rslopeg3max
amrex::Real WSM6::m_rslopeg3max {0} private
m_rslopegbmax
amrex::Real WSM6::m_rslopegbmax {0} private
m_rslopegmax
amrex::Real WSM6::m_rslopegmax {0} private
m_rsloper2max
amrex::Real WSM6::m_rsloper2max {0} private
m_rsloper3max
amrex::Real WSM6::m_rsloper3max {0} private
m_rsloperbmax
amrex::Real WSM6::m_rsloperbmax {0} private
m_rslopermax
amrex::Real WSM6::m_rslopermax {0} private
m_rslopes2max
amrex::Real WSM6::m_rslopes2max {0} private
m_rslopes3max
amrex::Real WSM6::m_rslopes3max {0} private
m_rslopesbmax
amrex::Real WSM6::m_rslopesbmax {0} private
m_rslopesmax
amrex::Real WSM6::m_rslopesmax {0} private
m_xlv1
amrex::Real WSM6::m_xlv1 {0} private
m_z_phys_nd
amrex::MultiFab* WSM6::m_z_phys_nd {nullptr} private
mic_fab_vars
amrex::Array<FabPtr, MicVar_WSM6::NumVars> WSM6::mic_fab_vars private
Referenced by Qmoist_Ptr().
MicVarMap
amrex::Vector<int> WSM6::MicVarMap private
Referenced by Qmoist_Ptr().
n0r
constexpr amrex::Real WSM6::n0r = amrex::Real(8.0e6) static constexpr
Referenced by Advance(), and wsm6_nislfv_rain_plm_scratch().
n0s
constexpr amrex::Real WSM6::n0s = amrex::Real(2.0e6) static constexpr
Referenced by wsm6_nislfv_rain_plm6_scratch().
n0smax
constexpr amrex::Real WSM6::n0smax = amrex::Real(1.0e11) static constexpr
n_qstate_moist_numconc_size
int WSM6::n_qstate_moist_numconc_size = 0 private
Referenced by Qstate_Moist_NumConc_Size().
n_qstate_moist_size
int WSM6::n_qstate_moist_size = 6 private
Referenced by Qstate_Moist_Size().
nlev
int WSM6::nlev {0} private
peaut
constexpr amrex::Real WSM6::peaut = amrex::Real(0.55) static constexpr
pfrz1
constexpr amrex::Real WSM6::pfrz1 = amrex::Real(100.0) static constexpr
pfrz2
constexpr amrex::Real WSM6::pfrz2 = amrex::Real(0.66) static constexpr
qcrmin
constexpr amrex::Real WSM6::qcrmin = amrex::Real(1.0e-9) static constexpr
Referenced by wsm6_nislfv_rain_plm6_scratch(), and wsm6_nislfv_rain_plm_scratch().
qs0
constexpr amrex::Real WSM6::qs0 = amrex::Real(6.0e-4) static constexpr
r0
constexpr amrex::Real WSM6::r0 = amrex::Real(0.8e-5) static constexpr
xmyu
constexpr amrex::Real WSM6::xmyu = amrex::Real(1.718e-5) static constexpr
xncr
constexpr amrex::Real WSM6::xncr = amrex::Real(3.0e8) static constexpr
Referenced by Advance().
zhi
int WSM6::zhi {0} private
zlo
int WSM6::zlo {0} private
The documentation for this class was generated from the following files:
Source/Microphysics/WSM6/ERF_WSM6.H
Source/Microphysics/WSM6/ERF_AdvanceWSM6.cpp
Source/Microphysics/WSM6/ERF_InitWSM6.cpp
Source/Microphysics/WSM6/ERF_UpdateWSM6.cpp