ERF: Microphysics Class Reference
Microphysics Class Reference abstract
Base class for microphysics interface.
#include <ERF_Microphysics.H>
Public Member Functions
Microphysics ()
Null constructor.
virtual ~Microphysics ()=default
default destructor
virtual void Define (const int &, SolverChoice &)=0
define the microphysics object
virtual void Init (const int &, const amrex::MultiFab &, const amrex::BoxArray &, const amrex::Geometry &, const amrex::Real &, std::unique_ptr< amrex::MultiFab > &, std::unique_ptr< amrex::MultiFab > &)=0
initialize the microphysics object
virtual void FinishInit (const int &, amrex::MultiFab &, const amrex::Vector< std::unique_ptr< amrex::MultiFab >> &)=0
finish initializations steps that require flow variables
virtual void Advance (const int &, const amrex::Real &, const int &, const amrex::Real &, const SolverChoice &, amrex::Vector< amrex::Vector< amrex::MultiFab >> &, const amrex::Vector< std::unique_ptr< amrex::MultiFab >> &, const amrex::GpuArray< ERF_BC, AMREX_SPACEDIM *2 > &)=0
advance microphysics for one time step
virtual void Update_Micro_Vars_Lev (const int &, amrex::MultiFab &)=0
update microphysics variables from ERF state variables
virtual void Update_State_Vars_Lev (const int &, amrex::MultiFab &)=0
update ERF state variables from microphysics variables
virtual amrex::MultiFab * Get_Qmoist_Ptr (const int &, const int &)=0
get pointer to a moisture variable
virtual int Get_Qmoist_Size (const int &)=0
get the number of moisture model variables
virtual int Get_Qstate_Moist_Size ()=0
get the number of microphysics conserved moist (water-related) state variables
virtual int Get_Qstate_NonMoist_Size ()=0
get the number of microphysics conserved non-moist (non-water, i.e., other vapor/condensed species) state variables
int Get_Qstate_Size ()
get total number of conserved state variables
virtual void Get_Qmoist_Restart_Vars (int, const SolverChoice &, std::vector< int > &, std::vector< std::string > &) const =0
get the indices and names of moisture model variables for restart at a given level
virtual void GetPlotVarNames (amrex::Vector< std::string > &a_vec) const =0
Returns a list of additional plot variable names.
virtual void GetPlotVar (const std::string &a_name, amrex::MultiFab &a_mf, const int a_lev) const =0
Fills in a MultiFab for plotting.
virtual void Set_dzmin (const int lev, const amrex::Real dz_min) const =0
Import minimum dz at this level.
virtual void Set_RealWidth (const int lev, const int real_width) const =0
Define the nudging+set width for real BCs.
Static Public Member Functions
static MoistureModelType modelType (const MoistureType a_moisture_type)
query if a specified moisture model is Eulerian or Lagrangian
Detailed Description
Base class for microphysics interface.
Constructor & Destructor Documentation
Microphysics()
Microphysics::Microphysics () inline
Null constructor.
 { }
~Microphysics()
virtual Microphysics::~Microphysics () virtual default
default destructor
Member Function Documentation
Advance()
virtual void Microphysics::Advance (const int & , const amrex::Real & , const int & , const amrex::Real & , const SolverChoice & , amrex::Vector< amrex::Vector< amrex::MultiFab >> & , const amrex::Vector< std::unique_ptr< amrex::MultiFab >> & , const amrex::GpuArray< ERF_BC, AMREX_SPACEDIM *2 > &) pure virtual
advance microphysics for one time step
Implemented in EulerianMicrophysics.
Define()
virtual void Microphysics::Define (const int & , SolverChoice &) pure virtual
define the microphysics object
Implemented in EulerianMicrophysics.
FinishInit()
virtual void Microphysics::FinishInit (const int & , amrex::MultiFab & , const amrex::Vector< std::unique_ptr< amrex::MultiFab >> &) pure virtual
finish initializations steps that require flow variables
Implemented in EulerianMicrophysics.
Get_Qmoist_Ptr()
virtual amrex::MultiFab* Microphysics::Get_Qmoist_Ptr (const int & , const int &) pure virtual
get pointer to a moisture variable
Implemented in EulerianMicrophysics.
Get_Qmoist_Restart_Vars()
virtual void Microphysics::Get_Qmoist_Restart_Vars (int , const SolverChoice & , std::vector< int > & , std::vector< std::string > &) const pure virtual
get the indices and names of moisture model variables for restart at a given level
Implemented in EulerianMicrophysics.
Get_Qmoist_Size()
virtual int Microphysics::Get_Qmoist_Size (const int &) pure virtual
get the number of moisture model variables
Implemented in EulerianMicrophysics.
Get_Qstate_Moist_Size()
virtual int Microphysics::Get_Qstate_Moist_Size () pure virtual
get the number of microphysics conserved moist (water-related) state variables
Implemented in EulerianMicrophysics.
Referenced by Get_Qstate_Size().
Get_Qstate_NonMoist_Size()
virtual int Microphysics::Get_Qstate_NonMoist_Size () pure virtual
get the number of microphysics conserved non-moist (non-water, i.e., other vapor/condensed species) state variables
Implemented in EulerianMicrophysics.
Referenced by Get_Qstate_Size().
Get_Qstate_Size()
int Microphysics::Get_Qstate_Size () inline
get total number of conserved state variables
     {
         return Get_Qstate_Moist_Size() + Get_Qstate_NonMoist_Size();
     }
GetPlotVar()
virtual void Microphysics::GetPlotVar (const std::string & a_name, amrex::MultiFab & a_mf, const int a_lev) const pure virtual
Fills in a MultiFab for plotting.
Implemented in EulerianMicrophysics.
GetPlotVarNames()
virtual void Microphysics::GetPlotVarNames (amrex::Vector< std::string > & a_vec) const pure virtual
Returns a list of additional plot variable names.
Implemented in EulerianMicrophysics.
Init()
virtual void Microphysics::Init (const int & , const amrex::MultiFab & , const amrex::BoxArray & , const amrex::Geometry & , const amrex::Real & , std::unique_ptr< amrex::MultiFab > & , std::unique_ptr< amrex::MultiFab > &) pure virtual
initialize the microphysics object
Implemented in EulerianMicrophysics.
modelType()
static MoistureModelType Microphysics::modelType (const MoistureType a_moisture_type) inline static
query if a specified moisture model is Eulerian or Lagrangian
     {
         if (    (a_moisture_type == MoistureType::SAM)
              || (a_moisture_type == MoistureType::SAM_NoIce)
              || (a_moisture_type == MoistureType::SAM_NoPrecip_NoIce)
              || (a_moisture_type == MoistureType::Morrison)
              || (a_moisture_type == MoistureType::Morrison_NoIce)
              || (a_moisture_type == MoistureType::Kessler)
              || (a_moisture_type == MoistureType::Kessler_NoRain)
              || (a_moisture_type == MoistureType::SatAdj)
              || (a_moisture_type == MoistureType::None) ) {
             return MoistureModelType::Eulerian;
         } else if ( (a_moisture_type == MoistureType::SuperDroplets) ) {
             return MoistureModelType::Lagrangian;
         } else {
             amrex::Abort("Dont know this moisture_type!") ;
             return MoistureModelType::Undefined;
         }
     }
Referenced by EulerianMicrophysics::EulerianMicrophysics(), ERF::InitData_post(), ERF::initializeMicrophysics(), and ERF::ReadCheckpointFile().
Set_dzmin()
virtual void Microphysics::Set_dzmin (const int lev, const amrex::Real dz_min) const pure virtual
Import minimum dz at this level.
Implemented in EulerianMicrophysics.
Set_RealWidth()
virtual void Microphysics::Set_RealWidth (const int lev, const int real_width) const pure virtual
Define the nudging+set width for real BCs.
Implemented in EulerianMicrophysics.
Update_Micro_Vars_Lev()
virtual void Microphysics::Update_Micro_Vars_Lev (const int & , amrex::MultiFab &) pure virtual
update microphysics variables from ERF state variables
Implemented in EulerianMicrophysics.
Update_State_Vars_Lev()
virtual void Microphysics::Update_State_Vars_Lev (const int & , amrex::MultiFab &) pure virtual
update ERF state variables from microphysics variables
Implemented in EulerianMicrophysics.
The documentation for this class was generated from the following file:
Source/Microphysics/ERF_Microphysics.H