ERF: SatMethods Class Reference
SatMethods Class Reference
#include <ERF_SatMethods.H>
Static Public Member Functions
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real wv_sat_svp_to_qsat (const amrex::Real &es, const amrex::Real &p)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void wv_sat_qsat_water (const amrex::Real &t, const amrex::Real &p, amrex::Real &es, amrex::Real &qs, const int idx=1)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void wv_sat_qsat_ice (const amrex::Real &t, const amrex::Real &p, amrex::Real &es, amrex::Real &qs, const int idx=1)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void wv_sat_qsat_trans (const amrex::Real &t, const amrex::Real &p, amrex::Real &es, amrex::Real &qs, const int idx=1)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real wv_sat_svp_water (const amrex::Real &t, const int idx=1)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real wv_sat_svp_ice (const amrex::Real &t, const int idx=1)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real wv_sat_svp_trans (const amrex::Real &t, const int idx=1)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real GoffGratch_svp_water (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real GoffGratch_svp_ice (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real MurphyKoop_svp_water (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real MurphyKoop_svp_ice (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real OldGoffGratch_svp_water (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real OldGoffGratch_svp_ice (const amrex::Real &t)
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real Bolton_svp_water (const amrex::Real &t)
Private Types
enum Type {
Invalid = -1 , OldGoffGratch = 0 , GoffGratch = 1 , MurphyKoop = 2 ,
Bolton = 3
}
Member Enumeration Documentation
Type
enum SatMethods::Type private
Enumerator
Invalid
OldGoffGratch
GoffGratch
MurphyKoop
Bolton
               {
                Invalid = -1,
                OldGoffGratch = 0,
                GoffGratch = 1,
                MurphyKoop = 2,
                Bolton = 3
     };
Member Function Documentation
Bolton_svp_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::Bolton_svp_water (const amrex::Real & t) inline static
{
         constexpr auto c1 = 611.2;
         constexpr auto c2 = 17.67;
         constexpr auto c3 = 243.5;
         return c1*exp( (c2*(t - tmelt))/((t - tmelt)+c3) );
     }
Referenced by wv_sat_svp_ice(), and wv_sat_svp_water().
GoffGratch_svp_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::GoffGratch_svp_ice (const amrex::Real & t) inline static
{
         // good down to -100 C
         return pow(10., (-9.09718*(h2otrip/t-1.)-3.56654*
                          log10(h2otrip/t)+0.876793*(1.-t/h2otrip)+
                          log10(6.1071)))*100.;
     }
Referenced by wv_sat_svp_ice().
GoffGratch_svp_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::GoffGratch_svp_water (const amrex::Real & t) inline static
{
         // uncertain below -70 C
         return pow(10., (-7.90298*(tboil/t-1.)+
                          5.02808*std::log10(tboil/t)-
                          1.3816e-7*(pow(10., (11.344*(1.-t/tboil)))-1.)+
                          8.1328e-3*(pow(10., (-3.49149*(tboil/t-1.)))-1.)+
                          std::log10(1013.246)))*100.;
     }
Referenced by wv_sat_svp_water().
MurphyKoop_svp_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::MurphyKoop_svp_ice (const amrex::Real & t) inline static
{
         // (good down to 110 K)
         return exp(9.550426 - (5723.265 / t) + (3.53068 * log(t))
                    - (0.00728332 * t));
     }
Referenced by wv_sat_svp_ice().
MurphyKoop_svp_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::MurphyKoop_svp_water (const amrex::Real & t) inline static
{
         // (good for 123 < T < 332 K)
         return exp(54.842763 - (6763.22 / t) - (4.210 * log(t)) +
                    (0.000367 * t) + (tanh(0.0415 * (t - 218.8)) *
                                      (53.878 - (1331.22 / t) - (9.44523 * log(t)) +
                                       0.014025 * t)));
     }
Referenced by wv_sat_svp_water().
OldGoffGratch_svp_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::OldGoffGratch_svp_ice (const amrex::Real & t) inline static
{
         auto term1 = 2.01889049/(tmelt/t);
         auto term2 = 3.56654*log(tmelt/t);
         auto term3 = 20.947031*(tmelt/t);
         return 575.185606e10*exp(-(term1 + term2 + term3));
     }
Referenced by wv_sat_svp_ice().
OldGoffGratch_svp_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::OldGoffGratch_svp_water (const amrex::Real & t) inline static
{
         auto ps = 1013.246;
         auto e1 = 11.344*(1.0 - t/tboil);
         auto e2 = -3.49149*(tboil/t - 1.0);
         auto f1 = -7.90298*(tboil/t - 1.0);
         auto f2 = 5.02808*log10(tboil/t);
         auto f3 = -1.3816*(pow(10.0, e1) - 1.0)/10000000.0;
         auto f4 = 8.1328*(pow(10.0, e2) - 1.0)/1000.0;
         auto f5 = log10(ps);
         auto f  = f1 + f2 + f3 + f4 + f5;
         return (pow(10.0, f))*100.0;
     }
Referenced by wv_sat_svp_water().
wv_sat_qsat_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void SatMethods::wv_sat_qsat_ice (const amrex::Real & t, const amrex::Real & p, amrex::Real & es, amrex::Real & qs, const int idx = 1) inline static
{
         // Purpose:
         //   Calculate SVP over ice at a given temperature, and then
         //   calculate and return saturation specific humidity.
         es = wv_sat_svp_ice(t, idx);
         qs = wv_sat_svp_to_qsat(es, p);
         // Ensures returned es is consistent with limiters on qs.
         es = std::min(es, p);
     }
Referenced by WaterVaporSat::qsat_ice().
wv_sat_qsat_trans()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void SatMethods::wv_sat_qsat_trans (const amrex::Real & t, const amrex::Real & p, amrex::Real & es, amrex::Real & qs, const int idx = 1) inline static
{
         // Purpose:
         //   Calculate SVP over ice at a given temperature, and then
         //   calculate and return saturation specific humidity.
         es = wv_sat_svp_trans(t, idx);
         qs = wv_sat_svp_to_qsat(es, p);
         // Ensures returned es is consistent with limiters on qs.
         es = std::min(es, p);
     }
wv_sat_qsat_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE void SatMethods::wv_sat_qsat_water (const amrex::Real & t, const amrex::Real & p, amrex::Real & es, amrex::Real & qs, const int idx = 1) inline static
{
         // Purpose:
         //   Calculate SVP over water at a given temperature, and then
         //   calculate and return saturation specific humidity.
         es = wv_sat_svp_water(t, idx);
         qs = wv_sat_svp_to_qsat(es, p);
         // Ensures returned es is consistent with limiters on qs.
         es = std::min(es, p);
     }
Referenced by WaterVaporSat::qsat_water().
wv_sat_svp_ice()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::wv_sat_svp_ice (const amrex::Real & t, const int idx = 1) inline static
{
         amrex::Real es;
         switch(idx)
             {
             case GoffGratch:
                 es = GoffGratch_svp_ice(t); break;
             case MurphyKoop:
                 es = MurphyKoop_svp_ice(t); break;
             case OldGoffGratch:
                 es = OldGoffGratch_svp_ice(t); break;
             case Bolton:
                 es = Bolton_svp_water(t); break;
             }
         return es;
     }
Referenced by WaterVaporSat::svp_ice(), wv_sat_qsat_ice(), and wv_sat_svp_trans().
wv_sat_svp_to_qsat()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::wv_sat_svp_to_qsat (const amrex::Real & es, const amrex::Real & p) inline static
{
         // If pressure is less than SVP, set qs to maximum of 1.
         if ( (p - es) <= 0. )
             return 1.0;
         else
             return epsilo*es / (p - omeps*es);
     }
Referenced by WaterVaporSat::qsat(), wv_sat_qsat_ice(), wv_sat_qsat_trans(), and wv_sat_qsat_water().
wv_sat_svp_trans()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::wv_sat_svp_trans (const amrex::Real & t, const int idx = 1) inline static
{
         amrex::Real esice;      // Saturation vapor pressure over ice
         amrex::Real weight;     // Intermediate scratch variable for es transition
         amrex::Real es;
         // Water
         if (t >= (tmelt - ttrice))
             es = wv_sat_svp_water(t,idx);
         else
             es = 0.0;
         // Ice
         if (t < tmelt) {
             esice = wv_sat_svp_ice(t,idx);
             if ( (tmelt - t) > ttrice )
                 weight = 1.0;
             else
                 weight = (tmelt - t)/ttrice;
             es = weight*esice + (1.0 - weight)*es;
         }
         return es;
     }
Referenced by WaterVaporSat::svp_trans(), and wv_sat_qsat_trans().
wv_sat_svp_water()
AMREX_GPU_HOST_DEVICE static AMREX_FORCE_INLINE amrex::Real SatMethods::wv_sat_svp_water (const amrex::Real & t, const int idx = 1) inline static
{
         amrex::Real es;
         switch(idx)
             {
             case GoffGratch:
                 es = GoffGratch_svp_water(t); break;
             case MurphyKoop:
                 es = MurphyKoop_svp_water(t); break;
             case OldGoffGratch:
                 es = OldGoffGratch_svp_water(t); break;
             case Bolton:
                 es = Bolton_svp_water(t); break;
             }
         return es;
     }
Referenced by WaterVaporSat::svp_water(), wv_sat_qsat_water(), and wv_sat_svp_trans().
The documentation for this class was generated from the following file:
Source/Utils/ERF_SatMethods.H