ERF: /home/runner/work/ERF/ERF/Source/Diffusion/ComputeTurbulentViscosity.cpp File Reference
ComputeTurbulentViscosity.cpp File Reference
#include <ABLMost.H>
#include <EddyViscosity.H>
#include <Diffusion.H>
Functions
void ComputeTurbulentViscosityPBL (const amrex::MultiFab &xvel, const amrex::MultiFab &yvel, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, const amrex::Geometry &geom, const SolverChoice &solverChoice, std::unique_ptr< ABLMost > &most, bool)
void ComputeTurbulentViscosityLES (const amrex::MultiFab &Tau11, const amrex::MultiFab &Tau22, const amrex::MultiFab &Tau33, const amrex::MultiFab &Tau12, const amrex::MultiFab &Tau13, const amrex::MultiFab &Tau23, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, const amrex::Geometry &geom, const SolverChoice &solverChoice)
void ComputeTurbulentViscosity (const amrex::MultiFab &xvel, const amrex::MultiFab &yvel, const amrex::MultiFab &Tau11, const amrex::MultiFab &Tau22, const amrex::MultiFab &Tau33, const amrex::MultiFab &Tau12, const amrex::MultiFab &Tau13, const amrex::MultiFab &Tau23, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, const amrex::Geometry &geom, const SolverChoice &solverChoice, std::unique_ptr< ABLMost > &most, bool vert_only)
Function Documentation
ComputeTurbulentViscosity()
void ComputeTurbulentViscosity (const amrex::MultiFab & xvel, const amrex::MultiFab & yvel, const amrex::MultiFab & Tau11, const amrex::MultiFab & Tau22, const amrex::MultiFab & Tau33, const amrex::MultiFab & Tau12, const amrex::MultiFab & Tau13, const amrex::MultiFab & Tau23, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, const amrex::Geometry & geom, const SolverChoice & solverChoice, std::unique_ptr< ABLMost > & most, bool vert_only)
 {
     BL_PROFILE_VAR("ComputeTurbulentViscosity()",ComputeTurbulentViscosity);
     //
     // In LES mode, the turbulent viscosity is isotropic, so the LES model sets both horizontal and vertical viscosities
     // In PBL mode, the primary purpose of the PBL model is to control vertical transport, so the PBL model sets the vertical viscosity.
     // Optionally, the PBL model can be run in conjunction with an LES model that sets the horizontal viscosity
     // (this isn’t truly LES, but the model form is the same as Smagorinsky).
     //
     // ComputeTurbulentViscosityLES populates the LES viscosity for both horizontal and vertical components.
     // ComputeTurbulentViscosityPBL computes the PBL viscosity just for the vertical component.
     //
     // We must initialize all the components to 0 because we may not set all of them below
     //    (which ones depends on which LES / PBL scheme we are using)
     eddyViscosity.setVal(0.0);
     if (most) {
         bool l_use_turb = ( solverChoice.les_type == LESType::Smagorinsky ||
                             solverChoice.les_type == LESType::Deardorff   ||
                             solverChoice.pbl_type == PBLType::MYNN25 );
         AMREX_ALWAYS_ASSERT_WITH_MESSAGE(l_use_turb,
           "An LES or PBL model must be utilized with MOST boundaries to compute the turbulent viscosity");
     } else {
         AMREX_ALWAYS_ASSERT(!vert_only);
     }
     if (solverChoice.les_type != LESType::None) {
         ComputeTurbulentViscosityLES(Tau11, Tau22, Tau33,
                                      Tau12, Tau13, Tau23,
                                      cons_in, eddyViscosity,
                                      geom, solverChoice);
     }
     if (solverChoice.pbl_type != PBLType::None) {
         ComputeTurbulentViscosityPBL(xvel, yvel, cons_in, eddyViscosity,
                                      geom, solverChoice, most, vert_only);
     }
 }
Referenced by ComputeTurbulentViscosity(), and ERF::erf_advance().
ComputeTurbulentViscosityLES()
void ComputeTurbulentViscosityLES (const amrex::MultiFab & Tau11, const amrex::MultiFab & Tau22, const amrex::MultiFab & Tau33, const amrex::MultiFab & Tau12, const amrex::MultiFab & Tau13, const amrex::MultiFab & Tau23, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, const amrex::Geometry & geom, const SolverChoice & solverChoice)
Compute Eddy Viscosity
 {
     const amrex::GpuArray<amrex::Real, AMREX_SPACEDIM> dxInv = geom.InvCellSizeArray();
     const Real cellVol = 1.0 / (dxInv[0] * dxInv[1] * dxInv[2]);
     const Real Delta   = std::pow(cellVol,1.0/3.0);
     // SMAGORINSKY: Fill Kturb for momentum in horizontal and vertical
     //***********************************************************************************
     if (solverChoice.les_type == LESType::Smagorinsky)
     {
       Real Cs = solverChoice.Cs;
       Real CsDeltaSqr = Cs*Cs*Delta*Delta;
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
       for (amrex::MFIter mfi(eddyViscosity,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
       {
           Box bxcc  = mfi.tilebox();
         const Array4<Real>& mu_turb = eddyViscosity.array(mfi);
         const amrex::Array4<amrex::Real const > &cell_data = cons_in.array(mfi);
         Array4<Real const> tau11 = Tau11.array(mfi);
         Array4<Real const> tau22 = Tau22.array(mfi);
         Array4<Real const> tau33 = Tau33.array(mfi);
         Array4<Real const> tau12 = Tau12.array(mfi);
         Array4<Real const> tau13 = Tau13.array(mfi);
         Array4<Real const> tau23 = Tau23.array(mfi);
         ParallelFor(bxcc, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
         {
           Real s11bar = tau11(i,j,k);
           Real s22bar = tau22(i,j,k);
           Real s33bar = tau33(i,j,k);
           Real s12bar = 0.25 * ( tau12(i  , j  , k  ) + tau12(i  , j+1, k  )
                                + tau12(i+1, j  , k  ) + tau12(i+1, j+1, k  ) );
           Real s13bar = 0.25 * ( tau13(i  , j  , k  ) + tau13(i  , j  , k+1)
                                + tau13(i+1, j  , k  ) + tau13(i+1, j  , k+1) );
           Real s23bar = 0.25 * ( tau23(i  , j  , k  ) + tau23(i  , j  , k+1)
                                + tau23(i  , j+1, k  ) + tau23(i  , j+1, k+1) );
           Real SmnSmn = s11bar*s11bar + s22bar*s22bar + s33bar*s33bar
                       + 2.0*s12bar*s12bar + 2.0*s13bar*s13bar + 2.0*s23bar*s23bar;
           mu_turb(i, j, k, EddyDiff::Mom_h) = CsDeltaSqr * cell_data(i, j, k, Rho_comp) * std::sqrt(2.0*SmnSmn);
           mu_turb(i, j, k, EddyDiff::Mom_v) = mu_turb(i, j, k, EddyDiff::Mom_h);
         });
       }
     }
     // DEARDORFF: Fill Kturb for momentum in horizontal and vertical
     //***********************************************************************************
     else if (solverChoice.les_type == LESType::Deardorff)
     {
       amrex::Real l_C_k = solverChoice.Ck;
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
       for ( amrex::MFIter mfi(eddyViscosity,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
       {
           Box bxcc  = mfi.tilebox();
         const Array4<Real>& mu_turb = eddyViscosity.array(mfi);
         const amrex::Array4<amrex::Real const > &cell_data = cons_in.array(mfi);
         ParallelFor(bxcc, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
         {
           // K = rho * C_k * Delta * KE^(1/2) = C_k * Delta * (rho * RhoKE)^1/2
           mu_turb(i,j,k,EddyDiff::Mom_h) = l_C_k * Delta *
             std::sqrt(cell_data(i,j,k,RhoKE_comp) * cell_data(i,j,k,Rho_comp));
           mu_turb(i, j, k, EddyDiff::Mom_v) = mu_turb(i, j, k, EddyDiff::Mom_h);
         });
       }
     }
     // Extrapolate Kturb in extrap x/y, fill remaining elements
     //***********************************************************************************
     int ngc(1);
     Real inv_Pr_t    = solverChoice.Pr_t_inv;
     Real inv_Sc_t    = solverChoice.Sc_t_inv;
     Real inv_sigma_k = 1.0 / solverChoice.sigma_k;
     Vector<Real> Factors = {inv_Pr_t, inv_Sc_t, inv_sigma_k, inv_sigma_k}; // alpha = mu/Pr
     Gpu::AsyncVector<Real> d_Factors; d_Factors.resize(Factors.size());
     Gpu::copy(Gpu::hostToDevice, Factors.begin(), Factors.end(), d_Factors.begin());
     Real* fac_ptr = d_Factors.data();
     bool use_KE  = (solverChoice.les_type == LESType::Deardorff);
     bool use_QKE = (solverChoice.use_QKE && solverChoice.diffuse_QKE_3D);
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
     for ( amrex::MFIter mfi(eddyViscosity,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         Box bxcc   = mfi.tilebox();
         Box planex = bxcc; planex.setSmall(0, 1); planex.setBig(0, ngc);
         Box planey = bxcc; planey.setSmall(1, 1); planey.setBig(1, ngc);
         int i_lo   = bxcc.smallEnd(0); int i_hi = bxcc.bigEnd(0);
         int j_lo   = bxcc.smallEnd(1); int j_hi = bxcc.bigEnd(1);
         bxcc.growLo(0,ngc); bxcc.growHi(0,ngc);
         bxcc.growLo(1,ngc); bxcc.growHi(1,ngc);
         const Array4<Real>& mu_turb = eddyViscosity.array(mfi);
         // Extrapolate x & y (over-written on interior ghost cells by FillBoundary)
         amrex::ParallelFor(planex, planey,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
         {
             mu_turb(i_lo-i, j, k, EddyDiff::Mom_h) = mu_turb(i_lo, j, k, EddyDiff::Mom_h);
             mu_turb(i_lo-i, j, k, EddyDiff::Mom_v) = mu_turb(i_lo, j, k, EddyDiff::Mom_v);
             mu_turb(i_hi+i, j, k, EddyDiff::Mom_h) = mu_turb(i_hi, j, k, EddyDiff::Mom_h);
             mu_turb(i_hi+i, j, k, EddyDiff::Mom_v) = mu_turb(i_hi, j, k, EddyDiff::Mom_v);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
         {
             mu_turb(i, j_lo-j, k, EddyDiff::Mom_h) = mu_turb(i, j_lo, k, EddyDiff::Mom_h);
             mu_turb(i, j_lo-j, k, EddyDiff::Mom_v) = mu_turb(i, j_lo, k, EddyDiff::Mom_v);
             mu_turb(i, j_hi+j, k, EddyDiff::Mom_h) = mu_turb(i, j_hi, k, EddyDiff::Mom_h);
             mu_turb(i, j_hi+j, k, EddyDiff::Mom_v) = mu_turb(i, j_hi, k, EddyDiff::Mom_v);
         });
         int ntot   = 5;
         int offset = EddyDiff::Theta_h;
         // Populate element other than mom_h/v on the whole grid
         if(use_QKE) {
           int ncomp  = 4;
           ParallelFor(bxcc,ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
           {
             int indx   = n + offset;
             int indx_v = indx + ntot;
             mu_turb(i,j,k,indx)   = mu_turb(i,j,k,EddyDiff::Mom_h) * fac_ptr[indx];
             mu_turb(i,j,k,indx_v) = mu_turb(i,j,k,indx);
           });
         } else if (use_KE) {
           int ncomp  = 3;
           ParallelFor(bxcc,ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
           {
             int indx   = n + offset;
             int indx_v = indx + ntot;
             mu_turb(i,j,k,indx)   = mu_turb(i,j,k,EddyDiff::Mom_h) * fac_ptr[indx];
             mu_turb(i,j,k,indx_v) = mu_turb(i,j,k,indx);
           });
         } else {
           int ncomp  = 2;
           ParallelFor(bxcc,ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
           {
             int indx   = n + offset;
             int indx_v = indx + ntot;
             mu_turb(i,j,k,indx)   = mu_turb(i,j,k,EddyDiff::Mom_h) * fac_ptr[indx];
             mu_turb(i,j,k,indx_v) = mu_turb(i,j,k,indx);
           });
         }
     }
     // Fill interior ghost cells and any ghost cells outside a periodic domain
     //***********************************************************************************
     eddyViscosity.FillBoundary(geom.periodicity());
     // Extrapolate top & bottom
     //***********************************************************************************
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
     for ( amrex::MFIter mfi(eddyViscosity,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         Box bxcc   = mfi.tilebox();
         Box planez = bxcc; planez.setSmall(2, 1); planez.setBig(2, ngc);
         int k_lo   = bxcc.smallEnd(2); int k_hi = bxcc.bigEnd(2);
         planez.growLo(0,ngc); planez.growHi(0,ngc);
         planez.growLo(1,ngc); planez.growHi(1,ngc);
         const Array4<Real>& mu_turb = eddyViscosity.array(mfi);
         int ntot   = 5;
         int offset = EddyDiff::Mom_h;
         // Extrap all components at top & bottom
         if(use_QKE) {
           int ncomp  = 4;
           ParallelFor(planez,ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
           {
             int indx = n + offset;
             int indx_v = indx + ntot;
             mu_turb(i, j, k_lo-k, indx  ) = mu_turb(i, j, k_lo, indx  );
             mu_turb(i, j, k_hi+k, indx  ) = mu_turb(i, j, k_hi, indx  );
             mu_turb(i, j, k_lo-k, indx_v) = mu_turb(i, j, k_lo, indx_v);
             mu_turb(i, j, k_hi+k, indx_v) = mu_turb(i, j, k_hi, indx_v);
           });
         } else if (use_KE) {
           int ncomp  = 3;
           ParallelFor(planez,ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
           {
             int indx   = n + offset;
             int indx_v = indx + ntot;
             mu_turb(i, j, k_lo-k, indx  ) = mu_turb(i, j, k_lo, indx  );
             mu_turb(i, j, k_hi+k, indx  ) = mu_turb(i, j, k_hi, indx  );
             mu_turb(i, j, k_lo-k, indx_v) = mu_turb(i, j, k_lo, indx_v);
             mu_turb(i, j, k_hi+k, indx_v) = mu_turb(i, j, k_hi, indx_v);
           });
         } else {
           int ncomp  = 2;
           ParallelFor(planez,ncomp, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
           {
             int indx   = n + offset;
             int indx_v = indx + ntot;
             mu_turb(i, j, k_lo-k, indx  ) = mu_turb(i, j, k_lo, indx  );
             mu_turb(i, j, k_hi+k, indx  ) = mu_turb(i, j, k_hi, indx  );
             mu_turb(i, j, k_lo-k, indx_v) = mu_turb(i, j, k_lo, indx_v);
             mu_turb(i, j, k_hi+k, indx_v) = mu_turb(i, j, k_hi, indx_v);
           });
         }
     }
 }
Referenced by ComputeTurbulentViscosity().
ComputeTurbulentViscosityPBL()
void ComputeTurbulentViscosityPBL (const amrex::MultiFab & xvel, const amrex::MultiFab & yvel, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, const amrex::Geometry & geom, const SolverChoice & solverChoice, std::unique_ptr< ABLMost > & most, bool)
 {
   // MYNN Level 2.5 PBL Model
   if (solverChoice.pbl_type == PBLType::MYNN25) {
     const amrex::Real A1 = solverChoice.pbl_A1;
     const amrex::Real A2 = solverChoice.pbl_A2;
     //const amrex::Real B1 = solverChoice.pbl_B1;
     const amrex::Real B2 = solverChoice.pbl_B2;
     const amrex::Real C1 = solverChoice.pbl_C1;
     const amrex::Real C2 = solverChoice.pbl_C2;
     const amrex::Real C3 = solverChoice.pbl_C3;
     //const amrex::Real C4 = solverChoice.pbl_C4;
     const amrex::Real C5 = solverChoice.pbl_C5;
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
     for ( amrex::MFIter mfi(eddyViscosity,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi) {
       const amrex::Box &bx = mfi.growntilebox(1);
       const amrex::Array4<amrex::Real const > &cell_data = cons_in.array(mfi);
       const amrex::Array4<amrex::Real> &K_turb = eddyViscosity.array(mfi);
       const amrex::Array4<amrex::Real const> &uvel = xvel.array(mfi);
       const amrex::Array4<amrex::Real const> &vvel = yvel.array(mfi);
       // Compute some quantities that are constant in each column
       // Sbox is shrunk to only include the interior of the domain in the vertical direction to compute integrals
       // NOTE: Here we requite that sbx covers the entire vertical domain
       const amrex::Box &dbx = geom.Domain();
       amrex::Box sbx(bx.smallEnd(), bx.bigEnd());
       sbx.grow(2,-1);
       AMREX_ALWAYS_ASSERT(sbx.smallEnd(2) == dbx.smallEnd(2) && sbx.bigEnd(2) == dbx.bigEnd(2));
       const amrex::GeometryData gdata = geom.data();
       const amrex::Box xybx = PerpendicularBox<ZDir>(bx, amrex::IntVect{0,0,0});
       amrex::FArrayBox qintegral(xybx,2);
       qintegral.setVal<amrex::RunOn::Device>(0.0);
       amrex::FArrayBox qturb(bx,1);
       const amrex::Array4<amrex::Real> qint = qintegral.array();
       const amrex::Array4<amrex::Real> qvel= qturb.array();
       amrex::ParallelFor(amrex::Gpu::KernelInfo().setReduction(true), bx,
                          [=] AMREX_GPU_DEVICE (int i, int j, int k, amrex::Gpu::Handler const& handler) noexcept
       {
           const amrex::Real Zval = gdata.ProbLo(2) + (k + 0.5)*gdata.CellSize(2);
           const amrex::Real rho = cell_data(i,j,k,Rho_comp);
           qvel(i,j,k) = std::sqrt(cell_data(i,j,k,RhoQKE_comp) / rho);
           // We will divide by qvel later
           AMREX_ASSERT_WITH_MESSAGE(qvel(i,j,k) > 0.0, "QKE must have a positive value");
           if (sbx.contains(i,j,k)) {
               amrex::Gpu::deviceReduceSum(&qint(i,j,0,0), Zval*qvel(i,j,k), handler);
               amrex::Gpu::deviceReduceSum(&qint(i,j,0,1), qvel(i,j,k), handler);
           }
       });
       amrex::Real dz_inv = geom.InvCellSize(2);
       int izmin = geom.Domain().smallEnd(2);
       int izmax = geom.Domain().bigEnd(2);
       // Spatially varying MOST
       amrex::Real eps       = 1.0e-16;
       amrex::Real d_kappa   = most->kappa;
       amrex::Real d_gravity = most->gravity;
       const auto& t_mean_mf = most->get_mac_avg(0,2); // TODO: IS THIS ACTUALLY RHOTHETA
       const auto& u_star_mf = most->get_u_star(0);    // Use coarsest level
       const auto& t_star_mf = most->get_t_star(0);    // Use coarsest level
       const auto& tm_arr     = t_mean_mf->array(mfi); // TODO: IS THIS ACTUALLY RHOTHETA
       const auto& u_star_arr = u_star_mf->array(mfi);
       const auto& t_star_arr = t_star_mf->array(mfi);
       amrex::ParallelFor(bx, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
       {
           // Compute some partial derivatives that we will need (1st order at domain boundary)
           // U and V derivatives are interpolated to account for staggered grid
           amrex::Real dthetadz, dudz, dvdz;
           if (k == izmax) {
               dthetadz = (cell_data(i,j,k,RhoTheta_comp)/cell_data(i,j,k,Rho_comp) -
                           cell_data(i,j,k-1,RhoTheta_comp)/cell_data(i,j,k-1,Rho_comp))*dz_inv;
               dudz = 0.5*(uvel(i,j,k) - uvel(i,j,k-1) + uvel(i+1,j,k) - uvel(i+1,j,k-1))*dz_inv;
               dvdz = 0.5*(vvel(i,j,k) - vvel(i,j,k-1) + vvel(i,j+1,k) - vvel(i,j+1,k-1))*dz_inv;
           } else if (k == izmin){
               dthetadz = (cell_data(i,j,k+1,RhoTheta_comp)/cell_data(i,j,k+1,Rho_comp) -
                           cell_data(i,j,k,RhoTheta_comp)/cell_data(i,j,k,Rho_comp))*dz_inv;
               dudz = 0.5*(uvel(i,j,k+1) - uvel(i,j,k) + uvel(i+1,j,k+1) - uvel(i+1,j,k))*dz_inv;
               dvdz = 0.5*(vvel(i,j,k+1) - vvel(i,j,k) + vvel(i,j+1,k+1) - vvel(i,j+1,k))*dz_inv;
           } else {
               dthetadz = 0.5*(cell_data(i,j,k+1,RhoTheta_comp)/cell_data(i,j,k+1,Rho_comp) -
                               cell_data(i,j,k-1,RhoTheta_comp)/cell_data(i,j,k-1,Rho_comp))*dz_inv;
               dudz = 0.25*(uvel(i,j,k+1) - uvel(i,j,k-1) + uvel(i+1,j,k+1) - uvel(i+1,j,k-1))*dz_inv;
               dvdz = 0.25*(vvel(i,j,k+1) - vvel(i,j,k-1) + vvel(i,j+1,k+1) - vvel(i,j+1,k-1))*dz_inv;
           }
           // Spatially varying MOST
           amrex::Real surface_heat_flux = u_star_arr(i,k,0) * t_star_arr(i,j,0);
           amrex::Real theta0            = tm_arr(i,j,0); // TODO: IS THIS ACTUALLY RHOTHETA
           amrex::Real l_obukhov;
           if (std::abs(surface_heat_flux) > eps) {
               l_obukhov = ( theta0 * u_star_arr(i,j,0) * u_star_arr(i,j,0) ) /
                           ( d_kappa * d_gravity * t_star_arr(i,j,0) );
           } else {
               l_obukhov = std::numeric_limits<amrex::Real>::max();
           }
           // First Length Scale
           AMREX_ASSERT(l_obukhov != 0);
           const amrex::Real zval = gdata.ProbLo(2) + (k + 0.5)*gdata.CellSize(2);
           const amrex::Real zeta = zval/l_obukhov;
           amrex::Real l_S;
           if (zeta >= 1.0) {
               l_S = KAPPA*zval/3.7;
           } else if (zeta >= 0) {
               l_S = KAPPA*zval/(1+2.7*zeta);
           } else {
               l_S = KAPPA*zval*std::pow(1.0 - 100.0 * zeta, 0.2);
           }
           // Second Length Scale
           amrex::Real l_T;
           if (qint(i,j,0,1) > 0.0) {
               l_T = 0.23*qint(i,j,0,0)/qint(i,j,0,1);
           } else {
               l_T = std::numeric_limits<amrex::Real>::max();
           }
           // Third Length Scale
           amrex::Real l_B;
           if (dthetadz > 0) {
               amrex::Real N_brunt_vaisala = CONST_GRAV/theta0 * std::sqrt(dthetadz);
               if (zeta < 0) {
                   amrex::Real qc = CONST_GRAV/theta0 * surface_heat_flux * l_T;
                   qc = std::pow(qc,1.0/3.0);
                   l_B = (1.0 + 5.0*std::sqrt(qc/(N_brunt_vaisala * l_T))) * qvel(i,j,k)/N_brunt_vaisala;
               } else {
                   l_B = qvel(i,j,k) / N_brunt_vaisala;
               }
           } else {
               l_B = std::numeric_limits<amrex::Real>::max();
           }
           // Overall Length Scale
           amrex::Real l_comb = 1.0 / (1.0/l_S + 1.0/l_T + 1.0/l_B);
           // Compute non-dimensional parameters
           amrex::Real l2_over_q2 = l_comb*l_comb/(qvel(i,j,k)*qvel(i,j,k));
           amrex::Real GM = l2_over_q2 * (dudz*dudz + dvdz*dvdz);
           amrex::Real GH = -l2_over_q2 / theta0 * dthetadz;
           amrex::Real E1 = 1.0 + 6.0*A1*A1*GM - 9.0*A1*A2*(1.0-C2)*GH;
           amrex::Real E2 = -3.0*A1*(4.0*A1 + 3.0*A2*(1.0-C5))*(1.0-C2)*GH;
           amrex::Real E3 = 6.0*A2*A1*GM;
           amrex::Real E4 = 1.0 - 12.0*A2*A1*(1.0-C2)*GH -3.0*A2*B2*(1.0-C3)*GH;
           amrex::Real R1 = A1*(1.0-3.0*C1);
           amrex::Real SM = (A2*E2 - R1*E4)/(E2*E3 - E1*E4);
           amrex::Real SH = (R1*E3 - A2*E1)/(E2*E3 - E1*E4);
           amrex::Real SQ = 3.0 * SM;
           // Finally, compute the eddy viscosity/diffusivities
           const amrex::Real rho = cell_data(i,j,k,Rho_comp);
           K_turb(i,j,k,EddyDiff::Mom_v)   = rho * l_comb * qvel(i,j,k) * SM * 0.5;
           K_turb(i,j,k,EddyDiff::Theta_v) = rho * l_comb * qvel(i,j,k) * SH;
           K_turb(i,j,k,EddyDiff::QKE_v)   = rho * l_comb * qvel(i,j,k) * 3.0 * SQ;
           K_turb(i,j,k,EddyDiff::PBL_lengthscale) = l_comb;
           // TODO: How should this be done for other components (scalars, moisture)
       });
     }
   }
 }
Referenced by ComputeTurbulentViscosity().