var dir_4c48f420b74c1f1cc31b316243ca788c =
[
    [ "ERF_Checkpoint.cpp", "ERF__Checkpoint_8cpp.html", null ],
    [ "ERF_ConsoleIO.cpp", "ERF__ConsoleIO_8cpp.html", "ERF__ConsoleIO_8cpp" ],
    [ "ERF_NCColumnFile.cpp", "ERF__NCColumnFile_8cpp.html", null ],
    [ "ERF_NCInterface.cpp", "ERF__NCInterface_8cpp.html", "ERF__NCInterface_8cpp" ],
    [ "ERF_NCInterface.H", "ERF__NCInterface_8H.html", [
      [ "NCDType", "structncutils_1_1NCDType.html", "structncutils_1_1NCDType" ],
      [ "NCDim", "structncutils_1_1NCDim.html", "structncutils_1_1NCDim" ],
      [ "NCVar", "structncutils_1_1NCVar.html", "structncutils_1_1NCVar" ],
      [ "NCGroup", "classncutils_1_1NCGroup.html", "classncutils_1_1NCGroup" ],
      [ "NCFile", "classncutils_1_1NCFile.html", "classncutils_1_1NCFile" ]
    ] ],
    [ "ERF_NCPlotFile.cpp", "ERF__NCPlotFile_8cpp.html", "ERF__NCPlotFile_8cpp" ],
    [ "ERF_NCPlotFile.H", "ERF__NCPlotFile_8H.html", null ],
    [ "ERF_NCWpsFile.H", "ERF__NCWpsFile_8H.html", "ERF__NCWpsFile_8H" ],
    [ "ERF_Plotfile.cpp", "ERF__Plotfile_8cpp.html", "ERF__Plotfile_8cpp" ],
    [ "ERF_Plotfile2D.cpp", "ERF__Plotfile2D_8cpp.html", null ],
    [ "ERF_Plotfile2DCatalog.cpp", "ERF__Plotfile2DCatalog_8cpp.html", "ERF__Plotfile2DCatalog_8cpp" ],
    [ "ERF_Plotfile2DCatalog.H", "ERF__Plotfile2DCatalog_8H.html", "ERF__Plotfile2DCatalog_8H" ],
    [ "ERF_Plotfile2DFill.cpp", "ERF__Plotfile2DFill_8cpp.html", "ERF__Plotfile2DFill_8cpp" ],
    [ "ERF_Plotfile2DFill.H", "ERF__Plotfile2DFill_8H.html", "ERF__Plotfile2DFill_8H" ],
    [ "ERF_Plotfile2DInterpolator.cpp", "ERF__Plotfile2DInterpolator_8cpp.html", "ERF__Plotfile2DInterpolator_8cpp" ],
    [ "ERF_Plotfile2DInterpolator.H", "ERF__Plotfile2DInterpolator_8H.html", "ERF__Plotfile2DInterpolator_8H" ],
    [ "ERF_Plotfile2DMetadata.cpp", "ERF__Plotfile2DMetadata_8cpp.html", "ERF__Plotfile2DMetadata_8cpp" ],
    [ "ERF_Plotfile2DMetadata.H", "ERF__Plotfile2DMetadata_8H.html", "ERF__Plotfile2DMetadata_8H" ],
    [ "ERF_Plotfile2DSampledField.cpp", "ERF__Plotfile2DSampledField_8cpp.html", "ERF__Plotfile2DSampledField_8cpp" ],
    [ "ERF_Plotfile2DSampledField.H", "ERF__Plotfile2DSampledField_8H.html", "ERF__Plotfile2DSampledField_8H" ],
    [ "ERF_Plotfile2DSampledLevel.cpp", "ERF__Plotfile2DSampledLevel_8cpp.html", "ERF__Plotfile2DSampledLevel_8cpp" ],
    [ "ERF_Plotfile2DSampledLevel.H", "ERF__Plotfile2DSampledLevel_8H.html", "ERF__Plotfile2DSampledLevel_8H" ],
    [ "ERF_Plotfile2DUtils.cpp", "ERF__Plotfile2DUtils_8cpp.html", "ERF__Plotfile2DUtils_8cpp" ],
    [ "ERF_Plotfile2DUtils.H", "ERF__Plotfile2DUtils_8H.html", "ERF__Plotfile2DUtils_8H" ],
    [ "ERF_Plotfile2DWaterPath.cpp", "ERF__Plotfile2DWaterPath_8cpp.html", "ERF__Plotfile2DWaterPath_8cpp" ],
    [ "ERF_Plotfile2DWaterPath.H", "ERF__Plotfile2DWaterPath_8H.html", "ERF__Plotfile2DWaterPath_8H" ],
    [ "ERF_ReadBndryPlanes.cpp", "ERF__ReadBndryPlanes_8cpp.html", "ERF__ReadBndryPlanes_8cpp" ],
    [ "ERF_ReadBndryPlanes.H", "ERF__ReadBndryPlanes_8H.html", "ERF__ReadBndryPlanes_8H" ],
    [ "ERF_ReadFromERFBdy.cpp", "ERF__ReadFromERFBdy_8cpp.html", "ERF__ReadFromERFBdy_8cpp" ],
    [ "ERF_ReadFromERFBdy.H", "ERF__ReadFromERFBdy_8H.html", "ERF__ReadFromERFBdy_8H" ],
    [ "ERF_ReadFromMetgrid.cpp", "ERF__ReadFromMetgrid_8cpp.html", null ],
    [ "ERF_ReadFromWRFBdy.cpp", "ERF__ReadFromWRFBdy_8cpp.html", null ],
    [ "ERF_ReadFromWRFBdy.H", "ERF__ReadFromWRFBdy_8H.html", null ],
    [ "ERF_ReadFromWRFInput.cpp", "ERF__ReadFromWRFInput_8cpp.html", null ],
    [ "ERF_ReadFromWRFInput.H", "ERF__ReadFromWRFInput_8H.html", null ],
    [ "ERF_ReadFromWRFLow.cpp", "ERF__ReadFromWRFLow_8cpp.html", null ],
    [ "ERF_SampleData.H", "ERF__SampleData_8H.html", [
      [ "LineSampler", "structLineSampler.html", "structLineSampler" ],
      [ "PlaneSampler", "structPlaneSampler.html", "structPlaneSampler" ]
    ] ],
    [ "ERF_TrackerOutput.cpp", "ERF__TrackerOutput_8cpp.html", null ],
    [ "ERF_Write1DProfiles.cpp", "ERF__Write1DProfiles_8cpp.html", null ],
    [ "ERF_Write1DProfiles_stag.cpp", "ERF__Write1DProfiles__stag_8cpp.html", null ],
    [ "ERF_WriteBndryPlanes.cpp", "ERF__WriteBndryPlanes_8cpp.html", "ERF__WriteBndryPlanes_8cpp" ],
    [ "ERF_WriteBndryPlanes.H", "ERF__WriteBndryPlanes_8H.html", [
      [ "WriteBndryPlanes", "classWriteBndryPlanes.html", "classWriteBndryPlanes" ]
    ] ],
    [ "ERF_WriteERFBdy.cpp", "ERF__WriteERFBdy_8cpp.html", "ERF__WriteERFBdy_8cpp" ],
    [ "ERF_WriteERFBdy.H", "ERF__WriteERFBdy_8H.html", "ERF__WriteERFBdy_8H" ],
    [ "ERF_WriteJobInfo.cpp", "ERF__WriteJobInfo_8cpp.html", null ],
    [ "ERF_WriteScalarProfiles.cpp", "ERF__WriteScalarProfiles_8cpp.html", null ],
    [ "ERF_WriteSubvolume.cpp", "ERF__WriteSubvolume_8cpp.html", null ]
];