ERF: Source/Utils/ERF_TileNoZ.H File Reference
ERF_TileNoZ.H File Reference
#include <AMReX.H>
Functions
AMREX_FORCE_INLINE amrex::IntVect TileNoZ ()
Function Documentation
TileNoZ()
AMREX_FORCE_INLINE amrex::IntVect TileNoZ ()
Function returns explicit tile size that prevents tiling in z
 {
     if (amrex::TilingIfNotGPU()) {
         return amrex::IntVect{amrex::FabArrayBase::mfiter_tile_size[0],
                               amrex::FabArrayBase::mfiter_tile_size[1],
                               1024000};
     }
     else {
         return amrex::IntVect::TheZeroVector();
     }
 }
Referenced by add_thin_body_sources(), Morrison::Advance(), WSM6::Advance(), ERF::Advance(), ERF::advance_dycore(), TurbulentPerturbation::calc_tpi_meanMag_perBox(), MOSTAverage::compute_eb_averages(), MYNNPBLH::compute_pblh(), MOSTAverage::compute_plane_averages(), MOSTAverage::compute_region_averages(), ComputeDiffusivityMRF(), ComputeDiffusivityYSUNew(), copy_surface_tau_for_implicit(), ERF::erf_enforce_hse(), erf_init_dens_hse_dry(), erf_make_tau_terms(), erf_slow_rhs_pre(), erf_substep_NS(), erf_substep_T(), FillZeroAreaFaceFluxes(), SAM::IceFall(), if(), Kessler::Init(), ERF::init_custom(), ERF::init_from_hse(), ERF::init_immersed_forcing(), make_fast_coeffs(), make_sources(), TurbulentPerturbation::netZeroBuoyantAdd(), TurbulentPerturbation::netZeroBuoyantAdjust(), ERF::poisson_wall_dist(), SAM::PrecipFall(), TurbulentPerturbation::pseudoRandomPert(), rebalance_columns(), MOSTAverage::set_eb_normalization(), MOSTAverage::set_k_indices_T(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_rotated_fields(), MOSTAverage::set_z_positions_T(), ERF::turbPert_amplitude(), ERF::turbPert_amplitude_w(), MOSTAverage::write_averages(), MOSTAverage::write_k_indices(), MOSTAverage::write_norm_indices(), MOSTAverage::write_xz_positions(), and TurbulentPerturbation::zero_amp().