ERF: Source/Utils/ERF_Wstar.H File Reference
ERF_Wstar.H File Reference
#include <ERF_Constants.H>
Functions
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real calc_wstar (const amrex::Real &ust, const amrex::Real &tst, const amrex::Real &qst, const amrex::Real &pblh, const amrex::Real &th, const amrex::Real &thv, const amrex::Real &qv=0.0)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real calc_wstar (const amrex::Real &hfx, const amrex::Real &pblh, const amrex::Real &thv)
Function Documentation
calc_wstar() [1/2]
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real calc_wstar (const amrex::Real & hfx, const amrex::Real & pblh, const amrex::Real & thv)
 {
     if (hfx <= 0) {
         return 0.0;
     } else {
         return std::cbrt(CONST_GRAV / thv * pblh * hfx);
     }
 }
calc_wstar() [2/2]
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real calc_wstar (const amrex::Real & ust, const amrex::Real & tst, const amrex::Real & qst, const amrex::Real & pblh, const amrex::Real & th, const amrex::Real & thv, const amrex::Real & qv = 0.0)
 {
     amrex::Real hfx = -ust*tst; // <theta'w'>
     if (hfx <= 0) {
         return 0.0;
     }
     if (qv > 0) {
         // have moisture -- estimate buoyancy flux, <thetav'w'> (Stull 4.4.5d)
         hfx = hfx*(1 + 0.61*qv) + 0.61*th*(-ust*qst);
     }
     return std::cbrt(CONST_GRAV / thv * pblh * hfx);
 }
Referenced by surface_flux_charnock::iterate_flux(), surface_flux_mod_charnock::iterate_flux(), surface_flux_donelan::iterate_flux(), surface_temp_charnock::iterate_flux(), surface_temp_mod_charnock::iterate_flux(), surface_temp_donelan::iterate_flux(), surface_flux_wave_coupled::iterate_flux(), surface_temp_wave_coupled::iterate_flux(), surface_flux::iterate_flux(), and surface_temp::iterate_flux().