ERF: Source/Microphysics/ERF_SurfacePrecipitation.H File Reference
ERF_SurfacePrecipitation.H File Reference
#include <AMReX_GpuQualifiers.H>
#include <AMReX_MultiFab.H>
#include <AMReX_REAL.H>
Classes
struct SurfacePrecipAccumulationSource
struct SurfacePrecipAccumulationSources
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_source (const SurfacePrecipAccumulationSource &src) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_total_source (const SurfacePrecipAccumulationSources &src) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_explicit_rain_source (const SurfacePrecipAccumulationSources &src) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_any_source (const SurfacePrecipAccumulationSources &src) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_any_frozen_source (const SurfacePrecipAccumulationSources &src) noexcept
Function Documentation
surface_precip_has_any_frozen_source()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_any_frozen_source (const SurfacePrecipAccumulationSources & src) noexcept
 {
     // Public frozen precipitation is available whenever the scheme has any
     // precipitation source, because the IO layer can derive the frozen field
     // from the total or species accumulators and fill zero for warm-rain cases.
     return surface_precip_has_any_source(src);
 }
Referenced by plotfile2d::selected_precipitation_accumulation_components().
surface_precip_has_any_source()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_any_source (const SurfacePrecipAccumulationSources & src) noexcept
 {
     return surface_precip_has_source(src.total)
         || surface_precip_has_source(src.rain)
         || surface_precip_has_source(src.snow)
         || surface_precip_has_source(src.graupel)
         || surface_precip_has_source(src.hail);
 }
Referenced by NOAHMP::collect_precip_sources(), plotfile2d::fill_precipitation_accumulations(), plotfile2d::selected_precipitation_accumulation_components(), and surface_precip_has_any_frozen_source().
surface_precip_has_explicit_rain_source()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_explicit_rain_source (const SurfacePrecipAccumulationSources & src) noexcept
 {
     return surface_precip_has_source(src.rain);
 }
surface_precip_has_source()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_source (const SurfacePrecipAccumulationSource & src) noexcept
 {
     return src.accum != nullptr;
 }
Referenced by plotfile2d::fill_precipitation_accumulations(), plotfile2d::selected_precipitation_accumulation_components(), surface_precip_has_any_source(), surface_precip_has_explicit_rain_source(), and surface_precip_has_total_source().
surface_precip_has_total_source()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_precip_has_total_source (const SurfacePrecipAccumulationSources & src) noexcept
 {
     return surface_precip_has_source(src.total);
 }
Referenced by plotfile2d::selected_precipitation_accumulation_components().