ERF: Source/Prob/ERF_UpdateRhoThetaSources_SDMCongestus3D.H File Reference
ERF_UpdateRhoThetaSources_SDMCongestus3D.H File Reference
Functions
ParmParse pp_prob ("prob")
pp_prob query ("advection_heating_rate", advection_heating_rate)
pp_prob query ("advection_heating_rate_base", advection_heating_rate_base)
for (MFIter mfi(*src, TilingIfNotGPU());mfi.isValid();++mfi)
Variables
Real advection_heating_rate = 5.4e-5
Real advection_heating_rate_base = 5.4e-5
auto prob_lo = geom.ProbLoArray()
auto prob_hi = geom.ProbHiArray()
auto dx = geom.CellSizeArray()
const Real xc = 0.5 * (prob_lo[0] + prob_hi[0])
const Real yc = 0.5 * (prob_lo[1] + prob_hi[1])
Function Documentation
for()
for (MFIter mfi(*, TilingIfNotGPU)
     {
         const auto &box = mfi.tilebox();
         const Array4<Real>& src_arr = src->array(mfi);
         if (box.length(0) != 1)
         {
             // if z dimension size is 1, then src is a spatially varying function over x,y at k=0
             ParallelFor( box, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
             {
                 auto x = prob_lo[0] + (i + 0.5) * dx[0];
                 auto y = prob_lo[1] + (j + 0.5) * dx[1];
                 auto z = prob_lo[2] + (k + 0.5) * dx[2];
                 auto c = 2890000.0;
                 auto r  = std::sqrt((x-xc)*(x-xc) + (y-yc)*(y-yc));
                 auto rsqr = r*r;
                 if (time < 3600) {
                    src_arr(i, j, k) = (advection_heating_rate_base)*exp(-z/100);
                 } else {
                    src_arr(i, j, k) = (advection_heating_rate*exp(-rsqr / c))*exp(-z/100);
                 }
             });
         } else {
             // src is a function over Z
             ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
                 src_arr(i, j, k) = advection_heating_rate;
             });
         }
     }
pp_prob()
ParmParse pp_prob ("prob")
query() [1/2]
pp_prob query ("advection_heating_rate" , advection_heating_rate)
query() [2/2]
pp_prob query ("advection_heating_rate_base" , advection_heating_rate_base)
Variable Documentation
advection_heating_rate
Real advection_heating_rate = 5.4e-5
Referenced by for().
advection_heating_rate_base
Real advection_heating_rate_base = 5.4e-5
Referenced by for().
dx
auto dx = geom.CellSizeArray()
Referenced by for().
prob_hi
auto prob_hi = geom.ProbHiArray()
prob_lo
auto prob_lo = geom.ProbLoArray()
Referenced by for().
xc
const Real xc = 0.5 * (prob_lo[0] + prob_hi[0])
Referenced by for().
yc
const Real yc = 0.5 * (prob_lo[1] + prob_hi[1])
Referenced by for().