ERF: Source/TimeIntegration/ERF_Implicit.H File Reference
ERF_Implicit.H File Reference
Functions
for (int ori=0;ori< 2 *AMREX_SPACEDIM;ori++)
if (l_vert_implicit_fac > 0.)
Variables
const GpuArray< Real, AMREX_SPACEDIM > dxInv = fine_geom.InvCellSizeArray()
GpuArray< Real, AMREX_SPACEDIM *2 > l_bc_neumann_vals_d
const int bc_comp = RhoTheta_comp
Function Documentation
for()
for ()
{
                 l_bc_neumann_vals_d[ori] = m_bc_neumann_vals[bc_comp][ori];
             }
Referenced by ComputeTurbulentViscosity(), fine_compute_interior_ghost_rhs(), and ERF::Write3DPlotFile().
if()
if (l_vert_implicit_fac , 0.)
{
                 const bool l_use_stretched_dz = (solverChoice.mesh_type == MeshType::StretchedDz);
                 const bool l_use_SurfLayer = (m_SurfaceLayer != nullptr);
                 const BCRec* bc_ptr_h = domain_bcs_type.data();
                 const bool l_use_turb       = solverChoice.turbChoice[level].use_kturb;
                 std::unique_ptr<MultiFab> dflux_z;
                 dflux_z = std::make_unique<MultiFab>(convert(ba,IntVect(0,0,1)), dm, 1, 0);
                 for ( MFIter mfi(S_old[IntVars::cons],TileNoZ()); mfi.isValid(); ++mfi)
                 {
                     Box bx  = mfi.tilebox();
                     const Array4<      Real> & cell_data  = scratch.array(mfi);
                     const Array4<const Real>& z_nd_arr = z_phys_nd[level]->const_array(mfi);
                     const Array4<const Real>& detJ_arr = detJ_cc[level]->const_array(mfi);
                     const Array4<Real const>& mu_turb = l_use_turb ? eddyDiffs->const_array(mfi) : Array4<const Real>{};
                     const Array4<Real>& hfx_z   = Hfx3->array(mfi);
                     if (l_use_stretched_dz) {
                         ImplicitDiffForState_S(bx, fine_geom.Domain(), level, slow_dt,
                                                l_bc_neumann_vals_d,
                                                cell_data,
                                                stretched_dz_d[level], hfx_z,
                                                mu_turb, solverChoice,
                                                bc_ptr_h, l_use_SurfLayer, l_vert_implicit_fac);
                     } else if (l_use_terrain_fitted_coords) {
                         ImplicitDiffForState_T(bx, fine_geom.Domain(), level, slow_dt,
                                                l_bc_neumann_vals_d,
                                                cell_data,
                                                z_nd_arr, detJ_arr, dxInv, hfx_z,
                                                mu_turb, solverChoice,
                                                bc_ptr_h, l_use_SurfLayer, l_vert_implicit_fac);
                     } else {
                         ImplicitDiffForState_N(bx, fine_geom.Domain(), level, slow_dt,
                                                l_bc_neumann_vals_d,
                                                cell_data,
                                                dxInv, hfx_z,
                                                mu_turb, solverChoice,
                                                bc_ptr_h, l_use_SurfLayer, l_vert_implicit_fac);
                     }
                 } // mfi
             } // if do implicit solve for diffusive contribution to (rho theta) update
Variable Documentation
bc_comp
const int bc_comp = RhoTheta_comp
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), ERF::fill_from_bndryregs(), for(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), ImplicitDiffForState_T(), ERFPhysBCFunct_base::impose_lateral_basestate_bcs(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), and ERFPhysBCFunct_cons::impose_vertical_cons_bcs().
dxInv
const GpuArray<Real, AMREX_SPACEDIM> dxInv = fine_geom.InvCellSizeArray()
Referenced by ERF::advance_dycore(), AdvectionSrcForMom_ConstantDz(), AdvectionSrcForMom_EB(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMom_TF(), AdvectionSrcForMomWrapper_N(), AdvectionSrcForOpenBC_Normal(), AdvectionSrcForOpenBC_Tangent(), AdvectionSrcForOpenBC_Tangent_Cons(), AdvectionSrcForOpenBC_Tangent_Xmom(), AdvectionSrcForOpenBC_Tangent_Ymom(), AdvectionSrcForOpenBC_Tangent_Zmom(), AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForXMom(), AdvectionSrcForXMom_N(), AdvectionSrcForYMom(), AdvectionSrcForYMom_N(), AdvectionSrcForZMom(), AdvectionSrcForZMom_N(), ERF::compute_divergence(), compute_gradp(), compute_gradp_interpz(), Compute_h_xi_AtCellCenter(), Compute_h_xi_AtEdgeCenterI(), Compute_h_xi_AtEdgeCenterJ(), Compute_h_xi_AtEdgeCenterK(), MOSTAverage::compute_plane_averages(), MOSTAverage::compute_region_averages(), SurfaceLayer::compute_SurfaceLayer_bcs(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ComputeStressConsVisc_T(), ComputeStressVarVisc_T(), ComputeTurbulentViscosityLES(), DiffusionSrcForMom(), DiffusionSrcForMom_EB(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), erf_make_tau_terms(), erf_slow_rhs_post(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), if(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), make_fast_coeffs(), make_mom_sources(), make_sources(), OmegaFromW(), ERFPhysBCFunct_u::operator()(), ERFPhysBCFunct_v::operator()(), ERFPhysBCFunct_w::operator()(), ERFPhysBCFunct_cons::operator()(), ERF::project_momenta(), rotate_scalar_flux(), rotate_stress_tensor(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_rotated_fields(), and WFromOmega().
l_bc_neumann_vals_d
GpuArray<Real, AMREX_SPACEDIM*2> l_bc_neumann_vals_d
Referenced by for(), if(), and ERFPhysBCFunct_cons::impose_vertical_cons_bcs().