ERF: Source/Diffusion/ERF_SetupDiff.H File Reference
ERF_SetupDiff.H File Reference
#include "ERF_SetupVertDiff.H"
Functions
eddy_diff_idx_d resize (eddy_diff_idx.size())
eddy_diff_idy_d resize (eddy_diff_idy.size())
Variables
const Real dx_inv = cellSizeInv[0]
const Real dy_inv = cellSizeInv[1]
const Box xbx = surroundingNodes(bx,0)
const Box ybx = surroundingNodes(bx,1)
const Box zbx = surroundingNodes(bx,2)
const int end_comp = start_comp + num_comp - 1
bool l_use_keqn = turbChoice.use_keqn
bool l_use_mynn = turbChoice.use_pbl_tke
Real l_inv_theta0 = (turbChoice.theta_ref > 0) ? 1.0 / turbChoice.theta_ref : 1.0
Vector< int > eddy_diff_idx
Vector< int > eddy_diff_idy
Gpu::AsyncVector< int > eddy_diff_idx_d
Gpu::AsyncVector< int > eddy_diff_idy_d
int * d_eddy_diff_idx = eddy_diff_idx_d.data()
int * d_eddy_diff_idy = eddy_diff_idy_d.data()
Function Documentation
resize() [1/2]
eddy_diff_idx_d resize (eddy_diff_idx. size())
resize() [2/2]
eddy_diff_idy_d resize (eddy_diff_idy. size())
Variable Documentation
d_eddy_diff_idx
int* d_eddy_diff_idx = eddy_diff_idx_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
d_eddy_diff_idy
int* d_eddy_diff_idy = eddy_diff_idy_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
dx_inv
const Real dx_inv = cellSizeInv[0]
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
dy_inv
const Real dy_inv = cellSizeInv[1]
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
eddy_diff_idx
Vector<int> eddy_diff_idx
Initial value:
{EddyDiff::Theta_h, EddyDiff::KE_h, EddyDiff::Scalar_h,
                              EddyDiff::Q_h    , EddyDiff::Q_h,  EddyDiff::Q_h ,
                              EddyDiff::Q_h    , EddyDiff::Q_h,  EddyDiff::Q_h }
eddy_diff_idx_d
Gpu::AsyncVector<int> eddy_diff_idx_d
eddy_diff_idy
Vector<int> eddy_diff_idy
Initial value:
{EddyDiff::Theta_h, EddyDiff::KE_h, EddyDiff::Scalar_h,
                              EddyDiff::Q_h    , EddyDiff::Q_h,  EddyDiff::Q_h ,
                              EddyDiff::Q_h    , EddyDiff::Q_h,  EddyDiff::Q_h }
eddy_diff_idy_d
Gpu::AsyncVector<int> eddy_diff_idy_d
end_comp
const int end_comp = start_comp + num_comp - 1
l_inv_theta0
Real l_inv_theta0 = (turbChoice.theta_ref > 0) ? 1.0 / turbChoice.theta_ref : 1.0
Referenced by ComputeTurbulentViscosityLES(), and if().
l_use_keqn
bool l_use_keqn = turbChoice.use_keqn
l_use_mynn
bool l_use_mynn = turbChoice.use_pbl_tke
xbx
const Box xbx = surroundingNodes(bx,0)
Referenced by AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), FillZeroAreaFaceFluxes(), init_bx_velocities_from_input_sounding(), ERF::init_custom(), ERF::init_immersed_forcing(), ERF::init_thin_body(), ERF::project_momenta(), ERF::solve_with_gmres(), and ERF::Write3DPlotFile().
ybx
const Box ybx = surroundingNodes(bx,1)
Referenced by AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), FillZeroAreaFaceFluxes(), init_bx_velocities_from_input_sounding(), ERF::init_custom(), ERF::init_immersed_forcing(), ERF::init_thin_body(), ERF::project_momenta(), and ERF::solve_with_gmres().
zbx
const Box zbx = surroundingNodes(bx,2)
Referenced by AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), ERF::derive_diag_profiles_stag(), ERF::derive_stress_profiles_stag(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), FillZeroAreaFaceFluxes(), ERF::ImposeBCsOnPhi(), init_bx_velocities_from_input_sounding(), ERF::init_custom(), ERF::init_immersed_forcing(), ERF::init_thin_body(), ERFPhysBCFunct_w::operator()(), ERF::project_momenta(), and ProblemBase::read_custom_terrain().