ERF: Source/Utils/ERF_Container.H File Reference
ERF_Container.H File Reference
Functions
template<typename V , typename T >
bool containerHasElement (const V &iterable, const T &query)
Function Documentation
containerHasElement()
template<typename V , typename T > bool containerHasElement (const V & iterable, const T & query)
{
     return std::find(iterable.begin(), iterable.end(), query) != iterable.end();
 }
Referenced by ERF::appendPlotVariables(), LineSampler::get_sample_data(), PlaneSampler::get_sample_data(), LineSampler::LineSampler(), PlaneSampler::PlaneSampler(), ERF::setPlotVariables(), ERF::setSubVolVariables(), ERF::Write2DPlotFile(), ERF::Write3DPlotFile(), and ERF::WriteSubvolume().