ERF: Source/IO/ERF_Plotfile.cpp File Reference
ERF_Plotfile.cpp File Reference
#include <ERF_EOS.H>
#include <ERF.H>
#include "AMReX_Interp_3D_C.H"
#include "AMReX_PlotFileUtil.H"
#include "ERF_TerrainMetrics.H"
#include "ERF_Constants.H"
Functions
template<typename V , typename T >
bool containerHasElement (const V &iterable, const T &query)
Variables
PhysBCFunctNoOp null_bc_for_fill
Function Documentation
containerHasElement()
template<typename V , typename T > bool containerHasElement (const V & iterable, const T & query)
{
     return std::find(iterable.begin(), iterable.end(), query) != iterable.end();
 }
Referenced by ERF::appendPlotVariables(), ERF::setPlotVariables(), and ERF::WritePlotFile().
Variable Documentation
null_bc_for_fill
PhysBCFunctNoOp null_bc_for_fill
Referenced by ERF::WritePlotFile().