ERF: Source/EB/ERF_EBAdvection.H File Reference
ERF_EBAdvection.H File Reference
#include "AMReX.H"
#include "AMReX_MultiFab.H"
#include "AMReX_BCRec.H"
#include "AMReX_YAFluxRegister.H"
#include "ERF_DataStruct.H"
#include "ERF_IndexDefines.H"
#include "ERF_SurfaceLayer.H"
Functions
void EBAdvectionSrcForRho (const amrex::Box &bx, const amrex::Array4< amrex::Real > &src, const amrex::Array4< const amrex::Real > &rho_u, const amrex::Array4< const amrex::Real > &rho_v, const amrex::Array4< const amrex::Real > &omega, const amrex::Array4< amrex::Real > &avg_xmom, const amrex::Array4< amrex::Real > &avg_ymom, const amrex::Array4< amrex::Real > &avg_zmom, const amrex::Array4< const int > &mask_arr, const amrex::Array4< const amrex::EBCellFlag > &cfg_arr, const amrex::Array4< const amrex::Real > &ax_arr, const amrex::Array4< const amrex::Real > &ay_arr, const amrex::Array4< const amrex::Real > &az_arr, const amrex::Array4< const amrex::Real > &fcx_arr, const amrex::Array4< const amrex::Real > &fcy_arr, const amrex::Array4< const amrex::Real > &fcz_arr, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::GpuArray< const amrex::Array4< amrex::Real >, AMREX_SPACEDIM > &flx_arr, const bool fixed_rho, bool already_on_centroids)
void EBAdvectionSrcForScalars (const amrex::Box &bx, const int icomp, const int ncomp, const amrex::Array4< const amrex::Real > &avg_xmom, const amrex::Array4< const amrex::Real > &avg_ymom, const amrex::Array4< const amrex::Real > &avg_zmom, const amrex::Array4< const amrex::Real > &cell_prim, const amrex::Array4< amrex::Real > &src, const amrex::Array4< const int > &mask_arr, const amrex::Array4< const amrex::EBCellFlag > &cfg_arr, const amrex::Array4< const amrex::Real > &ax_arr, const amrex::Array4< const amrex::Real > &ay_arr, const amrex::Array4< const amrex::Real > &az_arr, const amrex::Array4< const amrex::Real > &fcx_arr, const amrex::Array4< const amrex::Real > &fcy_arr, const amrex::Array4< const amrex::Real > &fcz_arr, const amrex::Array4< const amrex::Real > &vf_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_my, const AdvType horiz_adv_type, const AdvType vert_adv_type, const amrex::Real horiz_upw_frac, const amrex::Real vert_upw_frac, const amrex::GpuArray< const amrex::Array4< amrex::Real >, AMREX_SPACEDIM > &flx_arr, const amrex::Box &domain, const amrex::BCRec *bc_ptr_h, bool already_on_centroids)
Function Documentation
EBAdvectionSrcForRho()
void EBAdvectionSrcForRho (const amrex::Box & bx, const amrex::Array4< amrex::Real > & src, const amrex::Array4< const amrex::Real > & rho_u, const amrex::Array4< const amrex::Real > & rho_v, const amrex::Array4< const amrex::Real > & omega, const amrex::Array4< amrex::Real > & avg_xmom, const amrex::Array4< amrex::Real > & avg_ymom, const amrex::Array4< amrex::Real > & avg_zmom, const amrex::Array4< const int > & mask_arr, const amrex::Array4< const amrex::EBCellFlag > & cfg_arr, const amrex::Array4< const amrex::Real > & ax_arr, const amrex::Array4< const amrex::Real > & ay_arr, const amrex::Array4< const amrex::Real > & az_arr, const amrex::Array4< const amrex::Real > & fcx_arr, const amrex::Array4< const amrex::Real > & fcy_arr, const amrex::Array4< const amrex::Real > & fcz_arr, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::GpuArray< const amrex::Array4< amrex::Real >, AMREX_SPACEDIM > & flx_arr, const bool fixed_rho, bool already_on_centroids)
Compute advection tendency for density and potential temperature
Referenced by erf_slow_rhs_pre().
EBAdvectionSrcForScalars()
void EBAdvectionSrcForScalars (const amrex::Box & bx, const int icomp, const int ncomp, const amrex::Array4< const amrex::Real > & avg_xmom, const amrex::Array4< const amrex::Real > & avg_ymom, const amrex::Array4< const amrex::Real > & avg_zmom, const amrex::Array4< const amrex::Real > & cell_prim, const amrex::Array4< amrex::Real > & src, const amrex::Array4< const int > & mask_arr, const amrex::Array4< const amrex::EBCellFlag > & cfg_arr, const amrex::Array4< const amrex::Real > & ax_arr, const amrex::Array4< const amrex::Real > & ay_arr, const amrex::Array4< const amrex::Real > & az_arr, const amrex::Array4< const amrex::Real > & fcx_arr, const amrex::Array4< const amrex::Real > & fcy_arr, const amrex::Array4< const amrex::Real > & fcz_arr, const amrex::Array4< const amrex::Real > & vf_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_my, const AdvType horiz_adv_type, const AdvType vert_adv_type, const amrex::Real horiz_upw_frac, const amrex::Real vert_upw_frac, const amrex::GpuArray< const amrex::Array4< amrex::Real >, AMREX_SPACEDIM > & flx_arr, const amrex::Box & domain, const amrex::BCRec * bc_ptr_h, bool already_on_centroids)
Compute advection tendency for all scalars other than density and potential temperature
Referenced by erf_slow_rhs_post(), and erf_slow_rhs_pre().