ERF: Source/Utils/ERF_Utils.H File Reference
ERF_Utils.H File Reference
#include "AMReX.H"
#include "AMReX_MultiFab.H"
#include "AMReX_BCRec.H"
#include "ERF_DataStruct.H"
#include "ERF_IndexDefines.H"
#include "ERF_SurfaceLayer.H"
#include "ERF_FillPatcher.H"
Functions
void ChopGrids2D (amrex::BoxArray &ba, const amrex::Box &domain, int target_size)
amrex::BoxArray ERFPostProcessBaseGrids (const amrex::Box &domain, bool decompose_in_z)
void make_J (const amrex::Geometry &geom, amrex::MultiFab &z_phys_nd, amrex::MultiFab &detJ_cc)
void make_areas (const amrex::Geometry &geom, amrex::MultiFab &z_phys_nd, amrex::MultiFab &ax, amrex::MultiFab &ay, amrex::MultiFab &az)
void make_zcc (const amrex::Geometry &geom, amrex::MultiFab &z_phys_nd, amrex::MultiFab &z_phys_cc)
void MomentumToVelocity (amrex::MultiFab &xvel_out, amrex::MultiFab &yvel_out, amrex::MultiFab &zvel_out, const amrex::MultiFab &cons_in, const amrex::MultiFab &xmom_in, const amrex::MultiFab &ymom_in, const amrex::MultiFab &zmom_in, const amrex::Box &domain, const amrex::Vector< amrex::BCRec > &domain_bcs_type_h, const amrex::MultiFab *c_vfrac=nullptr)
void VelocityToMomentum (const amrex::MultiFab &xvel_in, const amrex::IntVect &xvel_ngrow, const amrex::MultiFab &yvel_in, const amrex::IntVect &yvel_ngrow, const amrex::MultiFab &zvel_in, const amrex::IntVect &zvel_ngrow, const amrex::MultiFab &cons_in, amrex::MultiFab &xmom_out, amrex::MultiFab &ymom_out, amrex::MultiFab &zmom_out, const amrex::Box &domain, const amrex::Vector< amrex::BCRec > &domain_bcs_type_h, const amrex::MultiFab *c_vfrac=nullptr)
void ConvertForProjection (const amrex::MultiFab &den_div, const amrex::MultiFab &den_mlt, amrex::MultiFab &xmom, amrex::MultiFab &ymom, amrex::MultiFab &zmom, const amrex::Box &domain, const amrex::Vector< amrex::BCRec > &domain_bcs_type_h)
void enforceInOutSolvability (int lev, amrex::Array< amrex::MultiFab *, AMREX_SPACEDIM > &vels_vec, amrex::Array< amrex::MultiFab *, AMREX_SPACEDIM > &area_vec, const amrex::Geometry &geom)
void realbdy_interior_bxs_xy (const amrex::Box &bx, const amrex::Box &domain, const int &width, amrex::Box &bx_xlo, amrex::Box &bx_xhi, amrex::Box &bx_ylo, amrex::Box &bx_yhi, const int &set_width=0, const amrex::IntVect &ng_vect=amrex::IntVect(0, 0, 0), const bool get_int_ng=false)
void realbdy_bc_bxs_xy (const amrex::Box &bx, const amrex::Box &domain, const int &set_width, amrex::Box &bx_xlo, amrex::Box &bx_xhi, amrex::Box &bx_ylo, amrex::Box &bx_yhi, const amrex::IntVect &ng_vect=amrex::IntVect(0, 0, 0))
void realbdy_compute_interior_ghost_rhs (const amrex::Real &bdy_time_interval, const amrex::Real &time, const amrex::Real &delta_t, const amrex::Real &stop_time_elapsed, int width, int set_width, bool do_upwind, const amrex::Geometry &geom, amrex::Vector< amrex::MultiFab > &S_rhs, amrex::Vector< amrex::MultiFab > &S_old_data, amrex::Vector< amrex::MultiFab > &S_cur_data, amrex::Vector< amrex::Vector< amrex::FArrayBox >> &bdy_data_xlo, amrex::Vector< amrex::Vector< amrex::FArrayBox >> &bdy_data_xhi, amrex::Vector< amrex::Vector< amrex::FArrayBox >> &bdy_data_ylo, amrex::Vector< amrex::Vector< amrex::FArrayBox >> &bdy_data_yhi)
void fine_compute_interior_ghost_rhs (const amrex::Real &time, const amrex::Real &delta_t, const int &width, const int &set_width, const amrex::Geometry &geom, ERFFillPatcher *FPr_c, ERFFillPatcher *FPr_u, ERFFillPatcher *FPr_v, ERFFillPatcher *FPr_w, amrex::Vector< amrex::BCRec > &domain_bcs_type, amrex::Vector< amrex::MultiFab > &S_rhs_f, amrex::Vector< amrex::MultiFab > &S_data_f)
void Time_Avg_Vel_atCC (const amrex::Real &dt, amrex::Real &t_avg_cnt, amrex::MultiFab *vel_t_avg, amrex::MultiFab &xvel, amrex::MultiFab &yvel, amrex::MultiFab &zvel)
AMREX_GPU_HOST AMREX_FORCE_INLINE void realbdy_set_rhs_in_spec_region (const amrex::Real &dt, const int &icomp, const int &num_var, const int &width, const int &set_width_x, const int &set_width_y, const amrex::Box &domain, const amrex::Box &domain_cc, const amrex::Box &bx_xlo, const amrex::Box &bx_xhi, const amrex::Box &bx_ylo, const amrex::Box &bx_yhi, const amrex::Array4< const amrex::Real > &arr_xlo, const amrex::Array4< const amrex::Real > &arr_xhi, const amrex::Array4< const amrex::Real > &arr_ylo, const amrex::Array4< const amrex::Real > &arr_yhi, const amrex::Array4< const amrex::Real > &u_xlo, const amrex::Array4< const amrex::Real > &u_xhi, const amrex::Array4< const amrex::Real > &v_xlo, const amrex::Array4< const amrex::Real > &v_xhi, const amrex::Array4< const amrex::Real > &v_ylo, const amrex::Array4< const amrex::Real > &v_yhi, const amrex::Array4< const amrex::Real > &data_arr, const amrex::Array4< amrex::Real > &rhs_arr, const bool &do_upwind)
AMREX_GPU_HOST AMREX_FORCE_INLINE void realbdy_compute_relaxation (const int &icomp, const int &num_var, const int &width, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dx, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &ProbLo, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &ProbHi, const amrex::Real &F1, const amrex::Box &domain_cc, const amrex::Box &bx_xlo, const amrex::Box &bx_xhi, const amrex::Box &bx_ylo, const amrex::Box &bx_yhi, const amrex::Array4< const amrex::Real > &arr_xlo, const amrex::Array4< const amrex::Real > &arr_xhi, const amrex::Array4< const amrex::Real > &arr_ylo, const amrex::Array4< const amrex::Real > &arr_yhi, const amrex::Array4< const amrex::Real > &u_xlo, const amrex::Array4< const amrex::Real > &u_xhi, const amrex::Array4< const amrex::Real > &v_xlo, const amrex::Array4< const amrex::Real > &v_xhi, const amrex::Array4< const amrex::Real > &v_ylo, const amrex::Array4< const amrex::Real > &v_yhi, const amrex::Array4< const amrex::Real > &data_arr, const amrex::Array4< amrex::Real > &rhs_arr, const bool &do_upwind)
AMREX_GPU_HOST AMREX_FORCE_INLINE void ApplyMask (amrex::MultiFab &dst, const amrex::iMultiFab &imask, const int nghost=0)
AMREX_GPU_HOST AMREX_FORCE_INLINE void ApplyInvertedMask (amrex::MultiFab &dst, const amrex::iMultiFab &imask, const int nghost=0)
void thinbody_wall_dist (std::unique_ptr< amrex::MultiFab > &wdist, amrex::Vector< amrex::IntVect > &xfaces, amrex::Vector< amrex::IntVect > &yfaces, amrex::Vector< amrex::IntVect > &zfaces, const amrex::Geometry &geomdata, std::unique_ptr< amrex::MultiFab > &z_phys_cc)
void WeatherDataInterpolation (const amrex::Real time)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real quad_interp_1d (amrex::Real z, amrex::Real z0, amrex::Real p0, amrex::Real z1, amrex::Real p1, amrex::Real z2, amrex::Real p2)
Function Documentation
ApplyInvertedMask()
AMREX_GPU_HOST AMREX_FORCE_INLINE void ApplyInvertedMask (amrex::MultiFab & dst, const amrex::iMultiFab & imask, const int nghost = 0)
 {
     for (amrex::MFIter mfi(dst,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const amrex::Box& bx = mfi.growntilebox(nghost);
         if (bx.ok())
         {
             auto        dstFab = dst.array(mfi);
             const auto maskFab = imask.const_array(mfi);
             ParallelFor(bx, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
             {
                 dstFab(i,j,k) *= (1-maskFab(i,j,k));
             });
         }
     }
 }
Referenced by add_thin_body_sources(), and ERF::project_velocity_tb().
ApplyMask()
AMREX_GPU_HOST AMREX_FORCE_INLINE void ApplyMask (amrex::MultiFab & dst, const amrex::iMultiFab & imask, const int nghost = 0)
 {
     for (amrex::MFIter mfi(dst,amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const amrex::Box& bx = mfi.growntilebox(nghost);
         if (bx.ok())
         {
             auto        dstFab = dst.array(mfi);
             const auto maskFab = imask.const_array(mfi);
             ParallelFor(bx, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
             {
                 dstFab(i,j,k) *= maskFab(i,j,k);
             });
         }
     }
 }
Referenced by ERF::FillIntermediatePatch(), and ERF::project_velocity_tb().
ChopGrids2D()
void ChopGrids2D (amrex::BoxArray & ba, const amrex::Box & domain, int target_size)
ConvertForProjection()
void ConvertForProjection (const amrex::MultiFab & den_div, const amrex::MultiFab & den_mlt, amrex::MultiFab & xmom, amrex::MultiFab & ymom, amrex::MultiFab & zmom, const amrex::Box & domain, const amrex::Vector< amrex::BCRec > & domain_bcs_type_h)
enforceInOutSolvability()
void enforceInOutSolvability (int lev, amrex::Array< amrex::MultiFab *, AMREX_SPACEDIM > & vels_vec, amrex::Array< amrex::MultiFab *, AMREX_SPACEDIM > & area_vec, const amrex::Geometry & geom)
ERFPostProcessBaseGrids()
amrex::BoxArray ERFPostProcessBaseGrids (const amrex::Box & domain, bool decompose_in_z)
fine_compute_interior_ghost_rhs()
void fine_compute_interior_ghost_rhs (const amrex::Real & time, const amrex::Real & delta_t, const int & width, const int & set_width, const amrex::Geometry & geom, ERFFillPatcher * FPr_c, ERFFillPatcher * FPr_u, ERFFillPatcher * FPr_v, ERFFillPatcher * FPr_w, amrex::Vector< amrex::BCRec > & domain_bcs_type, amrex::Vector< amrex::MultiFab > & S_rhs_f, amrex::Vector< amrex::MultiFab > & S_data_f)
make_areas()
void make_areas (const amrex::Geometry & geom, amrex::MultiFab & z_phys_nd, amrex::MultiFab & ax, amrex::MultiFab & ay, amrex::MultiFab & az)
make_J()
void make_J (const amrex::Geometry & geom, amrex::MultiFab & z_phys_nd, amrex::MultiFab & detJ_cc)
make_zcc()
void make_zcc (const amrex::Geometry & geom, amrex::MultiFab & z_phys_nd, amrex::MultiFab & z_phys_cc)
MomentumToVelocity()
void MomentumToVelocity (amrex::MultiFab & xvel_out, amrex::MultiFab & yvel_out, amrex::MultiFab & zvel_out, const amrex::MultiFab & cons_in, const amrex::MultiFab & xmom_in, const amrex::MultiFab & ymom_in, const amrex::MultiFab & zmom_in, const amrex::Box & domain, const amrex::Vector< amrex::BCRec > & domain_bcs_type_h, const amrex::MultiFab * c_vfrac = nullptr)
quad_interp_1d()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real quad_interp_1d (amrex::Real z, amrex::Real z0, amrex::Real p0, amrex::Real z1, amrex::Real p1, amrex::Real z2, amrex::Real p2)
 {
     return p0 * ( (z - z1) * (z - z2) ) / ( (z0 - z1) * (z0 - z2) )
          + p1 * ( (z - z0) * (z - z2) ) / ( (z1 - z0) * (z1 - z2) )
          + p2 * ( (z - z0) * (z - z1) ) / ( (z2 - z0) * (z2 - z1) );
 }
Referenced by compute_gradp_interpz().
realbdy_bc_bxs_xy()
void realbdy_bc_bxs_xy (const amrex::Box & bx, const amrex::Box & domain, const int & set_width, amrex::Box & bx_xlo, amrex::Box & bx_xhi, amrex::Box & bx_ylo, amrex::Box & bx_yhi, const amrex::IntVect & ng_vect = amrex::IntVect(0, 0, 0))
realbdy_compute_interior_ghost_rhs()
void realbdy_compute_interior_ghost_rhs (const amrex::Real & bdy_time_interval, const amrex::Real & time, const amrex::Real & delta_t, const amrex::Real & stop_time_elapsed, int width, int set_width, bool do_upwind, const amrex::Geometry & geom, amrex::Vector< amrex::MultiFab > & S_rhs, amrex::Vector< amrex::MultiFab > & S_old_data, amrex::Vector< amrex::MultiFab > & S_cur_data, amrex::Vector< amrex::Vector< amrex::FArrayBox >> & bdy_data_xlo, amrex::Vector< amrex::Vector< amrex::FArrayBox >> & bdy_data_xhi, amrex::Vector< amrex::Vector< amrex::FArrayBox >> & bdy_data_ylo, amrex::Vector< amrex::Vector< amrex::FArrayBox >> & bdy_data_yhi)
realbdy_compute_relaxation()
AMREX_GPU_HOST AMREX_FORCE_INLINE void realbdy_compute_relaxation (const int & icomp, const int & num_var, const int & width, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dx, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & ProbLo, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & ProbHi, const amrex::Real & F1, const amrex::Box & domain_cc, const amrex::Box & bx_xlo, const amrex::Box & bx_xhi, const amrex::Box & bx_ylo, const amrex::Box & bx_yhi, const amrex::Array4< const amrex::Real > & arr_xlo, const amrex::Array4< const amrex::Real > & arr_xhi, const amrex::Array4< const amrex::Real > & arr_ylo, const amrex::Array4< const amrex::Real > & arr_yhi, const amrex::Array4< const amrex::Real > & u_xlo, const amrex::Array4< const amrex::Real > & u_xhi, const amrex::Array4< const amrex::Real > & v_xlo, const amrex::Array4< const amrex::Real > & v_xhi, const amrex::Array4< const amrex::Real > & v_ylo, const amrex::Array4< const amrex::Real > & v_yhi, const amrex::Array4< const amrex::Real > & data_arr, const amrex::Array4< amrex::Real > & rhs_arr, const bool & do_upwind)
Compute the nudging relaxation
Parameters
[in] delta_t time step
[in] icomp component offset
[in] num_var number of variables to loop
[in] width width of wrf bdy file
[in] set_width width the set region
[in] dom_lo low bound of domain
[in] dom_hi high bound of domain
[in] F1 drift relaxation parameter
[in] F2 Laplacian relaxation parameter
[in] bx_xlo box for low x relaxation
[in] bx_xhi box for high x relaxation
[in] bx_ylo box for low y relaxation
[in] bx_yhi box for high y relaxation
[in] arr_xlo array for low x relaxation
[in] arr_xhi array for high x relaxation
[in] arr_ylo array for low y relaxation
[in] arr_yhi array for high y relaxation
[in] data_arr data array
[out] rhs_arr RHS array
 {
     amrex::IntVect iv = bx_xlo.type();
     amrex::Real ioff  = (iv[0]==1) ? 0.0 : 0.5;
     amrex::Real joff  = (iv[1]==1) ? 0.0 : 0.5;
     const auto& dom_cc_lo = lbound(domain_cc);
     const auto& dom_cc_hi = ubound(domain_cc);
     amrex::ParallelFor(bx_xlo, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // Corners with x boxes
         amrex::Real x = ProbLo[0] + (i + ioff) * dx[0];
         amrex::Real y = ProbLo[1] + (j + joff) * dx[1];
         amrex::Real x_end  = ProbLo[0] + (width + ioff) * dx[0];
         amrex::Real y_end  = ProbLo[1] + (width + joff) * dx[1];
         amrex::Real y_strt = ProbHi[1] - (width + joff) * dx[1];
         amrex::Real xi     = (x_end - x) / (x_end - ProbLo[0]);
         amrex::Real eta_lo = (y < y_end ) ? (y_end  - y) / (y_end  - ProbLo[1]) : 0.0;
         amrex::Real eta_hi = (y > y_strt) ? (y - y_strt) / (ProbHi[1] - y_strt) : 0.0;
         amrex::Real eta    = std::max(eta_lo,eta_hi);
         amrex::Real Factor = std::max(xi*xi,eta*eta);
         amrex::Real delta = arr_xlo(i  ,j  ,k,n) - data_arr(i  ,j  ,k  ,n+icomp);
         amrex::Real Temp  = Factor*F1*delta;
         if (!do_upwind) {
             rhs_arr(i,j,k,n+icomp) += Temp;
         } else {
             int jju = std::min(std::max(j,dom_cc_lo.y),dom_cc_hi.y);
             int iiv = std::min(std::max(i,dom_cc_lo.x),dom_cc_hi.x);
             if ( (u_xlo(dom_cc_lo.x,jju,k) >= 0.0) ||
                  ((j == dom_cc_lo.y      ) && (v_xlo(iiv,dom_cc_lo.y  ,k) >= 0.0)) ||
                  ((j == dom_cc_hi.y+iv[1]) && (v_xlo(iiv,dom_cc_hi.y+1,k) <= 0.0)) ) {
                 rhs_arr(i,j,k,n+icomp) += Temp;
             }
         }
     },
     bx_xhi, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // Corners with x boxes
         amrex::Real x = ProbLo[0] + (i + ioff) * dx[0];
         amrex::Real y = ProbLo[1] + (j + joff) * dx[1];
         amrex::Real x_strt = ProbHi[0] - (width + ioff) * dx[0];
         amrex::Real y_strt = ProbHi[1] - (width + joff) * dx[1];
         amrex::Real y_end  = ProbLo[1] + (width + joff) * dx[1];
         amrex::Real xi     = (x - x_strt) / (ProbHi[0] - x_strt);
         amrex::Real eta_lo = (y < y_end ) ? (y_end  - y) / (y_end  - ProbLo[1]) : 0.0;
         amrex::Real eta_hi = (y > y_strt) ? (y - y_strt) / (ProbHi[1] - y_strt) : 0.0;
         amrex::Real eta    = std::max(eta_lo,eta_hi);
         amrex::Real Factor = std::max(xi*xi,eta*eta);
         amrex::Real delta = arr_xhi(i  ,j  ,k,n) - data_arr(i  ,j  ,k  ,n+icomp);
         amrex::Real Temp  = Factor*F1*delta;
         if (!do_upwind) {
             rhs_arr(i,j,k,n+icomp) += Temp;
         } else {
             int jju = std::min(std::max(j,dom_cc_lo.y),dom_cc_hi.y);
             int iiv = std::min(std::max(i,dom_cc_lo.x),dom_cc_hi.x);
             if ( (u_xhi(dom_cc_hi.x+1,jju,k) <= 0.0) ||
                  ((j == dom_cc_lo.y      ) && (v_xhi(iiv,dom_cc_lo.y  ,k) >= 0.0)) ||
                  ((j == dom_cc_hi.y+iv[1]) && (v_xhi(iiv,dom_cc_hi.y+1,k) <= 0.0)) ) {
                 rhs_arr(i,j,k,n+icomp) += Temp;
             }
         }
     });
     amrex::ParallelFor(bx_ylo, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // No corners for y boxes
         amrex::Real y      = ProbLo[1] + (j + joff) * dx[1];
         amrex::Real y_end  = ProbLo[1] + (width + joff) * dx[1];
         amrex::Real eta    = (y_end - y) / (y_end - ProbLo[1]);
         amrex::Real Factor = eta*eta;
         amrex::Real delta = arr_ylo(i  ,j  ,k,n) - data_arr(i  ,j  ,k  ,n+icomp);
         amrex::Real Temp  = Factor*F1*delta;
         if (!do_upwind) {
             rhs_arr(i,j,k,n+icomp) += Temp;
         } else {
             int iiv = std::min(std::max(i,dom_cc_lo.x+width),dom_cc_hi.x-width);
             if (v_ylo(iiv,dom_cc_lo.y,k) >= 0.0) {
                 rhs_arr(i,j,k,n+icomp) += Temp;
             }
         }
     },
     bx_yhi, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // No corners for y boxes
         amrex::Real y      = ProbLo[1] + (j + joff) * dx[1];
         amrex::Real y_strt = ProbHi[1] - (width + joff) * dx[1];
         amrex::Real eta    = (y - y_strt) / (ProbHi[1] - y_strt);
         amrex::Real Factor = eta*eta;
         amrex::Real delta = arr_yhi(i  ,j  ,k,n) - data_arr(i  ,j  ,k  ,n+icomp);
         amrex::Real Temp  = Factor*F1*delta;
         if (!do_upwind) {
             rhs_arr(i,j,k,n+icomp) += Temp;
         } else {
             int iiv = std::min(std::max(i,dom_cc_lo.x+width),dom_cc_hi.x-width);
             if (v_yhi(iiv,dom_cc_hi.y+1,k) >= 0.0) {
                 rhs_arr(i,j,k,n+icomp) += Temp;
             }
         }
     });
 }
Referenced by realbdy_compute_interior_ghost_rhs().
realbdy_interior_bxs_xy()
void realbdy_interior_bxs_xy (const amrex::Box & bx, const amrex::Box & domain, const int & width, amrex::Box & bx_xlo, amrex::Box & bx_xhi, amrex::Box & bx_ylo, amrex::Box & bx_yhi, const int & set_width = 0, const amrex::IntVect & ng_vect = amrex::IntVect(0, 0, 0), const bool get_int_ng = false)
realbdy_set_rhs_in_spec_region()
AMREX_GPU_HOST AMREX_FORCE_INLINE void realbdy_set_rhs_in_spec_region (const amrex::Real & dt, const int & icomp, const int & num_var, const int & width, const int & set_width_x, const int & set_width_y, const amrex::Box & domain, const amrex::Box & domain_cc, const amrex::Box & bx_xlo, const amrex::Box & bx_xhi, const amrex::Box & bx_ylo, const amrex::Box & bx_yhi, const amrex::Array4< const amrex::Real > & arr_xlo, const amrex::Array4< const amrex::Real > & arr_xhi, const amrex::Array4< const amrex::Real > & arr_ylo, const amrex::Array4< const amrex::Real > & arr_yhi, const amrex::Array4< const amrex::Real > & u_xlo, const amrex::Array4< const amrex::Real > & u_xhi, const amrex::Array4< const amrex::Real > & v_xlo, const amrex::Array4< const amrex::Real > & v_xhi, const amrex::Array4< const amrex::Real > & v_ylo, const amrex::Array4< const amrex::Real > & v_yhi, const amrex::Array4< const amrex::Real > & data_arr, const amrex::Array4< amrex::Real > & rhs_arr, const bool & do_upwind)
Zero RHS in the set region
Parameters
[in] icomp component offset
[in] num_var number of variables to loop
[in] bx_xlo box for low x relaxation
[in] bx_xhi box for high x relaxation
[in] bx_ylo box for low y relaxation
[in] bx_yhi box for high y relaxation
[out] rhs_arr RHS array
 {
     int Spec_z_x = set_width_x;
     int Spec_z_y = set_width_y;
     amrex::IntVect iv = bx_xlo.type();
     const auto& dom_lo    = lbound(domain);
     const auto& dom_hi    = ubound(domain);
     const auto& dom_cc_lo = lbound(domain_cc);
     const auto& dom_cc_hi = ubound(domain_cc);
     amrex::ParallelFor(bx_xlo, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // Corners with x boxes
         int j_lo  = std::min(j-dom_lo.y,width-1);
         int j_hi  = std::min(dom_hi.y-j,width-1);
         int jj    = std::min(j_lo,j_hi);
         int n_ind_y = jj + 1;
         int n_ind_x = i - dom_lo.x + 1;
         if ((n_ind_x <= Spec_z_x) || (n_ind_y <= Spec_z_y)) {
             amrex::Real tend = ( arr_xlo(i,j,k) - data_arr(i,j,k,n+icomp) ) / dt;
             if (!do_upwind) {
                 rhs_arr(i,j,k,n+icomp) = tend;
             } else {
                 int jju = std::min(std::max(j,dom_cc_lo.y),dom_cc_hi.y);
                 int iiv = std::min(std::max(i,dom_cc_lo.x),dom_cc_hi.x);
                 if ( (u_xlo(dom_cc_lo.x,jju,k) >= 0.0) ||
                      ((j == dom_cc_lo.y      ) && (v_xlo(iiv,dom_cc_lo.y  ,k) >= 0.0)) ||
                      ((j == dom_cc_hi.y+iv[1]) && (v_xlo(iiv,dom_cc_hi.y+1,k) <= 0.0)) ) {
                     rhs_arr(i,j,k,n+icomp) = tend;
                 }
             }
         }
     },
     bx_xhi, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // Corners with x boxes
         int j_lo  = std::min(j-dom_lo.y,width-1);
         int j_hi  = std::min(dom_hi.y-j,width-1);
         int jj    = std::min(j_lo,j_hi);
         int n_ind_y = jj + 1;
         int n_ind_x = dom_hi.x - i + 1;
         if ((n_ind_x <= Spec_z_x) || (n_ind_y <= Spec_z_y)) {
             amrex::Real tend = ( arr_xhi(i,j,k) - data_arr(i,j,k,n+icomp) ) / dt;
             if (!do_upwind) {
                 rhs_arr(i,j,k,n+icomp) = tend;
             } else {
                 int jju = std::min(std::max(j,dom_cc_lo.y),dom_cc_hi.y);
                 int iiv = std::min(std::max(i,dom_cc_lo.x),dom_cc_hi.x);
                 if ( (u_xhi(dom_cc_hi.x+1,jju,k) <= 0.0) ||
                      ((j == dom_cc_lo.y      ) && (v_xhi(iiv,dom_cc_lo.y  ,k) >= 0.0)) ||
                      ((j == dom_cc_hi.y+iv[1]) && (v_xhi(iiv,dom_cc_hi.y+1,k) <= 0.0)) ) {
                     rhs_arr(i,j,k,n+icomp) = tend;
                 }
             }
         }
     });
     amrex::ParallelFor(bx_ylo, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // No corners for y boxes
         int n_ind = j - dom_lo.y + 1;
         if (n_ind <= Spec_z_y) {
             amrex::Real tend = ( arr_ylo(i,j,k) - data_arr(i,j,k,n+icomp) ) / dt;
             if (!do_upwind) {
                 rhs_arr(i,j,k,n+icomp) = tend;
             } else {
                 int iiv = std::min(std::max(i,dom_cc_lo.x+width),dom_cc_hi.x-width);
                 if (v_ylo(iiv,dom_cc_lo.y,k) >= 0.0) {
                     rhs_arr(i,j,k,n+icomp) = tend;
                 }
             }
         }
     },
     bx_yhi, num_var, [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
     {
         // No corners for y boxes
         int n_ind = dom_hi.y - j + 1;
         if (n_ind <= Spec_z_y) {
             amrex::Real tend = ( arr_yhi(i,j,k) - data_arr(i,j,k,n+icomp) ) / dt;
             if (!do_upwind) {
                 rhs_arr(i,j,k,n+icomp) = tend;
             } else {
                 int iiv = std::min(std::max(i,dom_cc_lo.x+width),dom_cc_hi.x-width);
                 if (v_yhi(iiv,dom_cc_hi.y+1,k) >= 0.0) {
                     rhs_arr(i,j,k,n+icomp) = tend;
                 }
             }
         }
     });
 }
Referenced by realbdy_compute_interior_ghost_rhs().
thinbody_wall_dist()
void thinbody_wall_dist (std::unique_ptr< amrex::MultiFab > & wdist, amrex::Vector< amrex::IntVect > & xfaces, amrex::Vector< amrex::IntVect > & yfaces, amrex::Vector< amrex::IntVect > & zfaces, const amrex::Geometry & geomdata, std::unique_ptr< amrex::MultiFab > & z_phys_cc)
Time_Avg_Vel_atCC()
void Time_Avg_Vel_atCC (const amrex::Real & dt, amrex::Real & t_avg_cnt, amrex::MultiFab * vel_t_avg, amrex::MultiFab & xvel, amrex::MultiFab & yvel, amrex::MultiFab & zvel)
VelocityToMomentum()
void VelocityToMomentum (const amrex::MultiFab & xvel_in, const amrex::IntVect & xvel_ngrow, const amrex::MultiFab & yvel_in, const amrex::IntVect & yvel_ngrow, const amrex::MultiFab & zvel_in, const amrex::IntVect & zvel_ngrow, const amrex::MultiFab & cons_in, amrex::MultiFab & xmom_out, amrex::MultiFab & ymom_out, amrex::MultiFab & zmom_out, const amrex::Box & domain, const amrex::Vector< amrex::BCRec > & domain_bcs_type_h, const amrex::MultiFab * c_vfrac = nullptr)
Referenced by ERF::Advance(), ERF::advance_dycore(), ERF::AverageDownTo(), ERF::FillCoarsePatch(), ERF::FillIntermediatePatch(), ERF::FillPatchFineLevel(), ERF::project_initial_velocity(), and ERF::project_momenta().
WeatherDataInterpolation()
void WeatherDataInterpolation (const amrex::Real time)
Referenced by ERF::Evolve(), and ERF::init_stuff().