ERF: Source/Utils/ERF_EOS.H File Reference
ERF_EOS.H File Reference
#include <ERF_Constants.H>
#include <AMReX.H>
#include <AMReX_IntVect.H>
#include <AMReX_MFIter.H>
#include <cmath>
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getThgivenTandP (const amrex::Real T, const amrex::Real P, const amrex::Real rdOcp)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getTgivenPandTh (const amrex::Real P, const amrex::Real th, const amrex::Real rdOcp)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getTgivenRandRTh (const amrex::Real rho, const amrex::Real rhotheta, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getThgivenRandT (const amrex::Real rho, const amrex::Real T, const amrex::Real rdOcp, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getPgivenRTh (const amrex::Real rhotheta, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getRhogivenThetaPress (const amrex::Real th, const amrex::Real p, const amrex::Real rdOcp, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getRhogivenTandPress (const amrex::Real T, const amrex::Real p, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getdPdRgivenConstantTheta (const amrex::Real rho, const amrex::Real theta, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getExnergivenP (const amrex::Real P, const amrex::Real rdOcp)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getExnergivenRTh (const amrex::Real rhotheta, const amrex::Real rdOcp, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getRhoThetagivenP (const amrex::Real p, const amrex::Real qv=amrex::Real(0))
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real compute_vapor_pressure (const amrex::Real p_s, const amrex::Real RH)
Function Documentation
compute_vapor_pressure()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real compute_vapor_pressure (const amrex::Real p_s, const amrex::Real RH)
 {
     return p_s*RH;
 }
Referenced by HSEutils::compute_F_for_temp_in_zone(), and HSEutils::vapor_mixing_ratio().
getdPdRgivenConstantTheta()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getdPdRgivenConstantTheta (const amrex::Real rho, const amrex::Real theta, const amrex::Real qv = amrex::Real(0))
Function to return dP/drho at constant theta
@params[in ] rho density @params[in ] theta potential temperature @params[in ] qv water vapor @params[ out] pressure
 {
     // We should be using moist value of theta when using moisture
     // theta_m = theta * (1 + R_v/R_d*qv)
     return Gamma * p_0 * std::pow( (R_d * theta * (amrex::Real(1) + R_v/R_d*qv) * ip_0), Gamma) * std::pow(rho, Gamma-amrex::Real(1)) ;
 }
Referenced by HSEutils::init_isentropic_hse_constant_dz(), HSEutils::init_isentropic_hse_stretched_dz(), and HSEutils::init_isentropic_hse_terrain().
getExnergivenP()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getExnergivenP (const amrex::Real P, const amrex::Real rdOcp)
Function to return the Exner function pi given pressure @params[in ] p pressure @params[in ] rdOcp ratio of R_d to c_p @params[ out] Exner function
 {
     // Exner function pi in terms of P
     return std::pow(P * ip_0, rdOcp);
 }
Referenced by ERF::erf_enforce_hse(), and Radiation::kokkos_buffers_to_mf().
getExnergivenRTh()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getExnergivenRTh (const amrex::Real rhotheta, const amrex::Real rdOcp, const amrex::Real qv = amrex::Real(0))
Function to return the Exner function pi given density times potential temperature
@params[in ] rhotheta density times potential temperature @params[in ] rdOcp ratio of R_d to c_p @params[in ] qv water vapor @params[ out] Exner function
 {
     // Exner function pi in terms of (rho theta)
     // We should be using moist value of theta when using moisture
     // theta_m = theta * (1 + R_v/R_d*qv)
     return std::pow(R_d * rhotheta *  (amrex::Real(1) + R_v/R_d*qv) * ip_0, Gamma * rdOcp);
 }
Referenced by erf_init_const_dens_and_linear_th_hse(), erf_init_const_dens_and_th_hse(), ERF::init_from_input_sounding(), init_state_from_input_sounding_hse(), make_sources(), and realbdy_compute_relaxation().
getPgivenRTh()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getPgivenRTh (const amrex::Real rhotheta, const amrex::Real qv = amrex::Real(0))
Function to return pressure given density times theta
@params[in ] rhotheta density times potential temperature @params[in ] qv water vapor @params[ out] pressure
 {
     return p_0 * std::pow(R_d * rhotheta * ( amrex::Real(1) + (R_v/R_d)*qv) * ip_0, Gamma);
 }
Referenced by NOAHMP::Advance_With_State(), SAM::Compute_Coefficients(), ERF::compute_max_pressure_gradient_diagnostic(), ComputeDiffusivityMRF(), ComputeMoistStratification(), Kessler::Copy_State_to_Micro(), Morrison::Copy_State_to_Micro(), SatAdj::Copy_State_to_Micro(), WSM6::Copy_State_to_Micro(), ERF::derive_diag_profiles(), ERF::derive_diag_profiles_stag(), derived::erf_dermucape(), derived::erf_dersoundspeed(), erf_init_const_dens_and_linear_th_hse(), erf_init_const_dens_and_th_hse(), ERF::estTimeStep(), ShocPreprocess::fill_columns(), SurfaceLayer::fill_qsurf_with_qsat(), LineSampler::get_sample_data(), PlaneSampler::get_sample_data(), HurricaneEyeTrackerNotInitial(), ERF::HurricaneEyeTrackerNotInitial_WRF(), HurricaneMinPressureTracker(), ERF::HurricaneMinPressureTracker_WRF(), ERF::init_from_input_sounding(), HSEutils::init_isentropic_hse_constant_dz(), HSEutils::init_isentropic_hse_stretched_dz(), HSEutils::init_isentropic_hse_terrain(), init_state_from_input_sounding_hse(), make_gradp_pert(), ERF::MakeHorizontalAverages(), SHOCInterface::mf_to_kokkos_buffers(), Radiation::mf_to_kokkos_buffers(), ERF::PackAtmosphericStates(), ParallelForRNG(), rebalance_columns(), sam_cons_to_primitive(), plotfile2d::sampled_field_value(), ERF::Write2DPlotFile(), and ERF::Write3DPlotFile().
getRhogivenTandPress()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getRhogivenTandPress (const amrex::Real T, const amrex::Real p, const amrex::Real qv = amrex::Real(0))
Function to return density given temperature and pressure
@params[in ] theta potential temperature @params[in ] p pressure @params[in ] rdOcp ratio of R_d to c_p @params[in ] qv water vapor @params[ out] density
 {
     return p / ( R_d * T * (amrex::Real(1) + (R_v/R_d)*qv) );
 }
Referenced by HSEutils::compute_rho(), and ParallelFor().
getRhogivenThetaPress()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getRhogivenThetaPress (const amrex::Real th, const amrex::Real p, const amrex::Real rdOcp, const amrex::Real qv = amrex::Real(0))
Function to return density given theta and pressure
@params[in ] theta potential temperature @params[in ] p pressure @params[in ] rdOcp ratio of R_d to c_p @params[in ] qv water vapor @params[ out] density
 {
     // We should be using moist value of theta when using moisture
     // theta_m = theta * (1 + R_v/R_d*qv)
     return std::pow(p_0, rdOcp) * std::pow(p, iGamma) / (R_d * th * (amrex::Real(1) + R_v/R_d*qv) );
 }
Referenced by InputSoundingData::calc_rho_p(), InputSoundingData::calc_rho_p_isentropic(), HSEutils::Newton_Raphson_hse(), ParallelForRNG(), and rebalance_columns().
getRhoThetagivenP()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getRhoThetagivenP (const amrex::Real p, const amrex::Real qv = amrex::Real(0))
Function to return (rho theta) given pressure
@params[in ] p pressure @params[in ] qv water vapor @params[ out] density times potential temperature
 {
     // diagnostic relation for the full pressure
     // see https://erf.readthedocs.io/en/latest/theory/NavierStokesEquations.html
     // For cases with moisture, theta = theta_m / (1 + R_v/R_d*qv)
     return std::pow(p*std::pow(p_0, Gamma-1), iGamma) * iR_d / (amrex::Real(1) + R_v/R_d*qv) ;
 }
Referenced by buoyancy_dry_anelastic_T(), ERF::erf_enforce_hse(), ERF::init_from_hse(), init_state_from_input_sounding_hse(), ParallelFor(), and ERF::ReadCheckpointFile().
getTgivenPandTh()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getTgivenPandTh (const amrex::Real P, const amrex::Real th, const amrex::Real rdOcp)
Function to return temperature given pressure and potential temperature
@params[in ] P pressure @params[in ] th potential temperature @params[in ] rdOcp ratio of R_d to c_p @params[ out] temperature
 {
     return th / std::pow(p_0/P, rdOcp);
 }
Referenced by buoyancy_dry_anelastic_T(), buoyancy_dry_Tpert(), buoyancy_moist_Tpert(), HSEutils::compute_rho(), derived::erf_dermucape(), if(), and ParallelFor().
getTgivenRandRTh()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getTgivenRandRTh (const amrex::Real rho, const amrex::Real rhotheta, const amrex::Real qv = amrex::Real(0))
Function to return temperature given density and potential temperature
@params[in ] rho density @params[in ] rhotheta (density times potential temperature) @params[in ] qv water vapor @params[ out] temperature
 {
     // rho and rhotheta are dry values. We use moist theta when using moisture
     // theta_m = theta * (1 + R_v/R_d*qv)
     amrex::Real p_loc = p_0 * std::pow(R_d * rhotheta * (amrex::Real(1) + R_v/R_d*qv) * ip_0, Gamma);
     return p_loc / (R_d * rho * (amrex::Real(1) + R_v/R_d*qv));
 }
Referenced by NOAHMP::Advance_With_State(), ApplySurfaceTreatment_BulkCoeff_CC(), buoyancy_dry_Tpert(), buoyancy_moist_Tpert(), ERF::check_for_low_temp(), SAM::Compute_Coefficients(), ComputeDiffusivityMRF(), ComputeMoistStratification(), Kessler::Copy_State_to_Micro(), Morrison::Copy_State_to_Micro(), SatAdj::Copy_State_to_Micro(), WSM6::Copy_State_to_Micro(), derived::erf_dermoisttemp(), derived::erf_dermucape(), derived::erf_derreflectivity(), derived::erf_dertemp(), ShocPreprocess::fill_columns(), GetThetal(), SHOCInterface::mf_to_kokkos_buffers(), Radiation::mf_to_kokkos_buffers(), ERF::PackAtmosphericStates(), ParallelForRNG(), sam_cons_to_primitive(), plotfile2d::sampled_field_value(), ERF::sum_energy_quantities(), and ERF::Write3DPlotFile().
getThgivenRandT()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getThgivenRandT (const amrex::Real rho, const amrex::Real T, const amrex::Real rdOcp, const amrex::Real qv = amrex::Real(0))
Function to return potential temperature given density and temperature
@params[in ] rho density @params[in ] T temperature @params[in ] rdOcp ratio of R_d to c_p @params[in ] qv water vapor @params[ out] potential temperature
 {
     // p = rho_d * R_d * T_moist
     amrex::Real p_loc = rho * R_d * T * (amrex::Real(1) + R_v/R_d*qv);
     // theta_d = T * (p0/p)^(R_d/C_p)
     return T * std::pow((p_0/p_loc),rdOcp);
 }
Referenced by WSM6::Copy_Micro_to_State(), and ReadBndryPlanes::read_file().
getThgivenTandP()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real getThgivenTandP (const amrex::Real T, const amrex::Real P, const amrex::Real rdOcp)
Function to return potential temperature given pressure and temperature
@params[in ] P pressure @params[in ] T temperature @params[in ] rdOcp ratio of R_d to c_p @params[ out] potential temperature
 {
     return T * std::pow(p_0/P, rdOcp);
 }
Referenced by SatAdj::AdjustSatAdjCell(), HSEutils::compute_rho(), derived::erf_dermucape(), ParallelForRNG(), and sam_theta_from_stored_mbar_converted_to_pa().