ERF: Source/Microphysics/Morrison/ERF_Morrison_Fortran_Interface.H File Reference
ERF_Morrison_Fortran_Interface.H File Reference
#include <stdbool.h>
Functions
void morr_two_moment_init_c (int morr_rimed_ice, int morr_noice)
void set_morrison_ndcnst_c (double ndcnst_in)
void mp_morr_two_moment_c (int itimestep, double *th, double *qv, double *qc, double *qr, double *qi, double *qs, double *qg, double *ni, double *ns, double *nr, double *ng, double *rho, double *pii, double *p, double dt_in, double *dz, double *w, double *rainnc, double *rainncv, double *sr, double *snownc, double *snowncv, double *graupelnc, double *graupelncv, double *refl_10cm, bool diagflag, int do_radar_ref, double *qrcuten, double *qscuten, double *qicuten, bool f_qndrop, double *qndrop, double *ht, int ids, int ide, int jds, int jde, int kds, int kde, int ims, int ime, int jms, int jme, int kms, int kme, int its, int ite, int jts, int jte, int kts, int kte, bool wetscav_on, double *rainprod, double *evapprod, double *qlsink, double *precr, double *preci, double *precs, double *precg)
Function Documentation
morr_two_moment_init_c()
void morr_two_moment_init_c (int morr_rimed_ice, int morr_noice)
Initialize the Morrison microphysics scheme
Parameters
morr_rimed_ice 0 for graupel, 1 for hail configuration
Referenced by Morrison::Init().
mp_morr_two_moment_c()
void mp_morr_two_moment_c (int itimestep, double * th, double * qv, double * qc, double * qr, double * qi, double * qs, double * qg, double * ni, double * ns, double * nr, double * ng, double * rho, double * pii, double * p, double dt_in, double * dz, double * w, double * rainnc, double * rainncv, double * sr, double * snownc, double * snowncv, double * graupelnc, double * graupelncv, double * refl_10cm, bool diagflag, int do_radar_ref, double * qrcuten, double * qscuten, double * qicuten, bool f_qndrop, double * qndrop, double * ht, int ids, int ide, int jds, int jde, int kds, int kde, int ims, int ime, int jms, int jme, int kms, int kme, int its, int ite, int jts, int jte, int kts, int kte, bool wetscav_on, double * rainprod, double * evapprod, double * qlsink, double * precr, double * preci, double * precs, double * precg)
C interface to the Fortran MP_MORR_TWO_MOMENT routine.
Note
: All array dimensions must match between C++ and Fortran calls.
: Arrays must be allocated in C++ before passing to this routine.
Referenced by Morrison::Advance().
set_morrison_ndcnst_c()
void set_morrison_ndcnst_c (double ndcnst_in)
Set the constant droplet concentration (NDCNST) for Morrison microphysics
Parameters
ndcnst_in Droplet number concentration in cm^-3
Referenced by Morrison::Advance().