ERF: Source/IO/ERF_ReadBndryPlanes.cpp File Reference
ERF_ReadBndryPlanes.cpp File Reference
#include "AMReX_Gpu.H"
#include "AMReX_ParmParse.H"
#include <AMReX_PlotFileUtil.H>
#include "ERF_ReadBndryPlanes.H"
#include "ERF_IndexDefines.H"
#include "AMReX_MultiFabUtil.H"
#include "ERF_EOS.H"
Functions
AMREX_FORCE_INLINE int closest_index (const Vector< Real > &vec, const Real value)
AMREX_FORCE_INLINE IntVect offset (const int face_dir, const int normal)
Function Documentation
closest_index()
AMREX_FORCE_INLINE int closest_index (const Vector< Real > & vec, const Real value)
Return closest index (from lower) of value in vector
 {
     auto const it = std::upper_bound(vec.begin(), vec.end(), value);
     AMREX_ALWAYS_ASSERT(it != vec.end());
     const int idx = std::distance(vec.begin(), it);
     return std::max(idx - 1, 0);
 }
Referenced by ReadBndryPlanes::read_input_files().
offset()
AMREX_FORCE_INLINE IntVect offset (const int face_dir, const int normal)
Return offset vector
 {
     IntVect offset(IntVect::TheDimensionVector(normal));
     if (face_dir == 1) {
         for (auto& o : offset) {
             o *= -1;
         }
     }
     return offset;
 }
Referenced by PlaneAverage::compute_averages(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityRANS(), Radiation::kokkos_buffers_to_mf(), SHOCInterface::kokkos_buffers_to_mf(), eb_::make_box(), make_mom_sources(), make_sources(), SHOCInterface::mf_to_kokkos_buffers(), Radiation::mf_to_kokkos_buffers(), Radiation::populateDatalogMF(), ERF::project_velocity_tb(), ReadBndryPlanes::read_file(), realbdy_compute_interior_ghost_rhs(), SHOCInterface::set_eddy_diffs(), ERF::Write3DPlotFile(), LineSampler::write_line_plotfile(), Radiation::write_rrtmgp_fluxes(), and ERF::WriteSubvolume().