ERF: Source/Diffusion/ERF_EddyViscosity.H File Reference
ERF_EddyViscosity.H File Reference
#include "AMReX_BCRec.H"
#include "ERF_SurfaceLayer.H"
#include "ERF_DataStruct.H"
#include "ERF_IndexDefines.H"
#include "ERF_Constants.H"
#include "ERF_EOS.H"
#include "ERF_EB.H"
Functions
void ComputeTurbulentViscosity (amrex::Real dt, const amrex::MultiFab &xvel, const amrex::MultiFab &yvel, amrex::Vector< std::unique_ptr< amrex::MultiFab >> &Tau_lev, amrex::MultiFab &cons_in, const amrex::MultiFab &wdist, amrex::MultiFab &eddyViscosity, amrex::MultiFab &Hfx1, amrex::MultiFab &Hfx2, amrex::MultiFab &Hfx3, amrex::MultiFab &Diss, const amrex::Geometry &geom, amrex::Vector< std::unique_ptr< amrex::MultiFab >> &mapfac, const std::unique_ptr< amrex::MultiFab > &z_phys_nd, const SolverChoice &solverChoice, std::unique_ptr< SurfaceLayer > &SurfLayer, const amrex::MultiFab *z_0, const bool &use_terrain_fitted_coords, const bool &use_moisture, int level, const amrex::BCRec *bc_ptr, const eb_ &ebfact, bool vert_only=false)
void ComputeTurbulentViscosityLES (amrex::Vector< std::unique_ptr< amrex::MultiFab >> &Tau_lev, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, amrex::MultiFab &Hfx1, amrex::MultiFab &Hfx2, amrex::MultiFab &Hfx3, amrex::MultiFab &Diss, const amrex::Geometry &geom, bool use_terrain_fitted_coords, amrex::Vector< std::unique_ptr< amrex::MultiFab >> &mapfac, const std::unique_ptr< amrex::MultiFab > &z_phys_nd, const TurbChoice &turbChoice, const amrex::Real const_grav, std::unique_ptr< SurfaceLayer > &SurfLayer, const MoistureComponentIndices &moisture_indices, const amrex::MultiFab *xvel=nullptr, const amrex::MultiFab *yvel=nullptr)
void ComputeTurbulentViscosityLES_EB (amrex::Vector< std::unique_ptr< amrex::MultiFab >> &Tau_lev, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, amrex::MultiFab &Hfx1, amrex::MultiFab &Hfx2, amrex::MultiFab &Hfx3, const amrex::Geometry &geom, amrex::Vector< std::unique_ptr< amrex::MultiFab >> &mapfac, const TurbChoice &turbChoice, const amrex::Real const_grav, const SolverChoice &solverChoice, std::unique_ptr< SurfaceLayer > &SurfLayer, const MoistureComponentIndices &moisture_indices, const eb_ &ebfact, const amrex::MultiFab *xvel=nullptr, const amrex::MultiFab *yvel=nullptr)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeSmnSmn (int &i, int &j, int &k, const amrex::Array4< amrex::Real const > &tau11, const amrex::Array4< amrex::Real const > &tau22, const amrex::Array4< amrex::Real const > &tau33, const amrex::Array4< amrex::Real const > &tau12, const amrex::Array4< amrex::Real const > &tau13, const amrex::Array4< amrex::Real const > &tau23)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeSmnSmn_EB (int &i, int &j, int &k, const amrex::Array4< amrex::Real const > &tau11, const amrex::Array4< amrex::Real const > &tau22, const amrex::Array4< amrex::Real const > &tau33, const amrex::Array4< amrex::Real const > &tau12, const amrex::Array4< amrex::Real const > &tau13, const amrex::Array4< amrex::Real const > &tau23, const amrex::Array4< const amrex::EBCellFlag > &c_cflag, const amrex::Array4< const amrex::EBCellFlag > &u_cflag, const amrex::Array4< const amrex::EBCellFlag > &v_cflag, const amrex::Array4< const amrex::EBCellFlag > &w_cflag)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeSmnSmn2D (int &i, int &j, int &k, const amrex::Array4< amrex::Real const > &tau11, const amrex::Array4< amrex::Real const > &tau22, const amrex::Array4< amrex::Real const > &tau12)
Function Documentation
ComputeSmnSmn()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeSmnSmn (int & i, int & j, int & k, const amrex::Array4< amrex::Real const > & tau11, const amrex::Array4< amrex::Real const > & tau22, const amrex::Array4< amrex::Real const > & tau33, const amrex::Array4< amrex::Real const > & tau12, const amrex::Array4< amrex::Real const > & tau13, const amrex::Array4< amrex::Real const > & tau23)
 {
     amrex::Real s11bar = tau11(i,j,k);
     amrex::Real s22bar = tau22(i,j,k);
     amrex::Real s33bar = tau33(i,j,k);
     amrex::Real s12bar = fourth * ( tau12(i  , j  , k  ) + tau12(i  , j+1, k  )
                                   + tau12(i+1, j  , k  ) + tau12(i+1, j+1, k  ) );
     amrex::Real s13bar = fourth * ( tau13(i  , j  , k  ) + tau13(i  , j  , k+1)
                                   + tau13(i+1, j  , k  ) + tau13(i+1, j  , k+1) );
     amrex::Real s23bar = fourth * ( tau23(i  , j  , k  ) + tau23(i  , j  , k+1)
                                   + tau23(i  , j+1, k  ) + tau23(i  , j+1, k+1) );
     amrex::Real SmnSmn = s11bar*s11bar + s22bar*s22bar + s33bar*s33bar
                        + two*s12bar*s12bar + two*s13bar*s13bar + two*s23bar*s23bar;
     return SmnSmn;
 }
Referenced by ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityLES_EB(), and erf_make_tau_terms().
ComputeSmnSmn2D()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeSmnSmn2D (int & i, int & j, int & k, const amrex::Array4< amrex::Real const > & tau11, const amrex::Array4< amrex::Real const > & tau22, const amrex::Array4< amrex::Real const > & tau12)
 {
     amrex::Real sdiff = tau11(i,j,k) - tau22(i,j,k);
     amrex::Real s12bar = fourth * ( tau12(i  , j  , k  ) + tau12(i  , j+1, k  )
                                   + tau12(i+1, j  , k  ) + tau12(i+1, j+1, k  ) );
     return myhalf * sdiff*sdiff + two*s12bar*s12bar;
 }
Referenced by ComputeTurbulentViscosityLES().
ComputeSmnSmn_EB()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeSmnSmn_EB (int & i, int & j, int & k, const amrex::Array4< amrex::Real const > & tau11, const amrex::Array4< amrex::Real const > & tau22, const amrex::Array4< amrex::Real const > & tau33, const amrex::Array4< amrex::Real const > & tau12, const amrex::Array4< amrex::Real const > & tau13, const amrex::Array4< amrex::Real const > & tau23, const amrex::Array4< const amrex::EBCellFlag > & c_cflag, const amrex::Array4< const amrex::EBCellFlag > & u_cflag, const amrex::Array4< const amrex::EBCellFlag > & v_cflag, const amrex::Array4< const amrex::EBCellFlag > & w_cflag)
 {
     amrex::Real SmnSmn = zero;
     if (!c_cflag(i,j,k).isCovered()) {
         amrex::Real s11bar = tau11(i,j,k);
         amrex::Real s22bar = tau22(i,j,k);
         amrex::Real s33bar = tau33(i,j,k);
         amrex::Real s12bar = zero;
         amrex::Real s13bar = zero;
         amrex::Real s23bar = zero;
         amrex::Real count_s12 = zero;
         if (!u_cflag(i,j,k).isCovered() || !v_cflag(i,j,k).isCovered()) {
             s12bar += tau12(i,j,k);
             count_s12 += one;
         }
         if (!u_cflag(i+1,j,k).isCovered() || !v_cflag(i,j,k).isCovered()) {
             s12bar += tau12(i+1,j,k);
             count_s12 += one;
         }
         if (!u_cflag(i,j,k).isCovered() || !v_cflag(i,j+1,k).isCovered()) {
             s12bar += tau12(i,j+1,k);
             count_s12 += one;
         }
         if (!u_cflag(i+1,j,k).isCovered() || !v_cflag(i,j+1,k).isCovered()) {
             s12bar += tau12(i+1,j+1,k);
             count_s12 += one;
         }
         if (count_s12 > zero) {
             s12bar /= count_s12;
         }
         amrex::Real count_s13 = zero;
         if (!u_cflag(i,j,k).isCovered() || !w_cflag(i,j,k).isCovered()) {
             s13bar += tau13(i, j, k);
             count_s13 += one;
         }
         if (!u_cflag(i,j,k).isCovered() || !w_cflag(i,j,k+1).isCovered()) {
             s13bar += tau13(i, j, k+1);
             count_s13 += one;
         }
         if (!u_cflag(i+1,j,k).isCovered() || !w_cflag(i,j,k).isCovered()) {
             s13bar += tau13(i+1, j, k);
             count_s13 += one;
         }
         if (!u_cflag(i+1,j,k).isCovered() || !w_cflag(i,j,k+1).isCovered()) {
             s13bar += tau13(i+1, j, k+1);
             count_s13 += one;
         }
         if (count_s13 > zero) {
             s13bar /= count_s13;
         }
         amrex::Real count_s23 = zero;
         if (!v_cflag(i,j,k).isCovered() || !w_cflag(i,j,k).isCovered()) {
             s23bar += tau23(i, j, k);
             count_s23 += one;
         }
         if (!v_cflag(i,j,k).isCovered() || !w_cflag(i,j,k+1).isCovered()) {
             s23bar += tau23(i, j, k+1);
             count_s23 += one;
         }
         if (!v_cflag(i,j+1,k).isCovered() || !w_cflag(i,j,k).isCovered()) {
             s23bar += tau23(i, j+1, k);
             count_s23 += one;
         }
         if (!v_cflag(i,j+1,k).isCovered() || !w_cflag(i,j,k+1).isCovered()) {
             s23bar += tau23(i, j+1, k+1);
             count_s23 += one;
         }
         if (count_s23 > zero) {
             s23bar /= count_s23;
         }
         SmnSmn = s11bar*s11bar + s22bar*s22bar + s33bar*s33bar
                + two*s12bar*s12bar + two*s13bar*s13bar + two*s23bar*s23bar;
     }
     return SmnSmn;
 }
Referenced by ComputeTurbulentViscosityLES_EB().
ComputeTurbulentViscosity()
void ComputeTurbulentViscosity (amrex::Real dt, const amrex::MultiFab & xvel, const amrex::MultiFab & yvel, amrex::Vector< std::unique_ptr< amrex::MultiFab >> & Tau_lev, amrex::MultiFab & cons_in, const amrex::MultiFab & wdist, amrex::MultiFab & eddyViscosity, amrex::MultiFab & Hfx1, amrex::MultiFab & Hfx2, amrex::MultiFab & Hfx3, amrex::MultiFab & Diss, const amrex::Geometry & geom, amrex::Vector< std::unique_ptr< amrex::MultiFab >> & mapfac, const std::unique_ptr< amrex::MultiFab > & z_phys_nd, const SolverChoice & solverChoice, std::unique_ptr< SurfaceLayer > & SurfLayer, const amrex::MultiFab * z_0, const bool & use_terrain_fitted_coords, const bool & use_moisture, int level, const amrex::BCRec * bc_ptr, const eb_ & ebfact, bool vert_only = false)
ComputeTurbulentViscosityLES()
void ComputeTurbulentViscosityLES (amrex::Vector< std::unique_ptr< amrex::MultiFab >> & Tau_lev, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, amrex::MultiFab & Hfx1, amrex::MultiFab & Hfx2, amrex::MultiFab & Hfx3, amrex::MultiFab & Diss, const amrex::Geometry & geom, bool use_terrain_fitted_coords, amrex::Vector< std::unique_ptr< amrex::MultiFab >> & mapfac, const std::unique_ptr< amrex::MultiFab > & z_phys_nd, const TurbChoice & turbChoice, const amrex::Real const_grav, std::unique_ptr< SurfaceLayer > & SurfLayer, const MoistureComponentIndices & moisture_indices, const amrex::MultiFab * xvel = nullptr, const amrex::MultiFab * yvel = nullptr)
ComputeTurbulentViscosityLES_EB()
void ComputeTurbulentViscosityLES_EB (amrex::Vector< std::unique_ptr< amrex::MultiFab >> & Tau_lev, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, amrex::MultiFab & Hfx1, amrex::MultiFab & Hfx2, amrex::MultiFab & Hfx3, const amrex::Geometry & geom, amrex::Vector< std::unique_ptr< amrex::MultiFab >> & mapfac, const TurbChoice & turbChoice, const amrex::Real const_grav, const SolverChoice & solverChoice, std::unique_ptr< SurfaceLayer > & SurfLayer, const MoistureComponentIndices & moisture_indices, const eb_ & ebfact, const amrex::MultiFab * xvel = nullptr, const amrex::MultiFab * yvel = nullptr)