ERF: Source/Prob/ERF_InitCustomPert_MovingTerrain.H File Reference
ERF_InitCustomPert_MovingTerrain.H File Reference
Functions
ParmParse pp ("prob")
pp query ("Ampl", Ampl)
pp get ("wavelength", wavelength)
ParallelFor (bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const auto prob_lo=geomdata.ProbLo();const auto dx=geomdata.CellSize();const Real x=prob_lo[0]+(i+0.5) *dx[0];Real z=z_cc(i, j, k);Real z_base=Ampl *std::sin(kp *x);z -=z_base;Real fac=std::cosh(kp *(z - H))/std::sinh(kp *H);Real p_prime=-(Ampl *omega *omega/kp) *fac *std::sin(kp *x) *r_hse(i, j, k);Real p_total=p_hse(i, j, k)+p_prime;state_pert(i, j, k, RhoTheta_comp)=getRhoThetagivenP(p_total) - getRhoThetagivenP(p_hse(i, j, k));state_pert(i, j, k, RhoScalar_comp)=state_pert(i, j, k, Rho_comp);})
Variables
Real Ampl = 0.
Real wavelength = 1.0
Real H = geomdata.ProbHi()[2]
Real kp = 2.0 * PI / wavelength
Real g = CONST_GRAV
Real omega = std::sqrt(g * kp)
Function Documentation
get()
pp get ("wavelength" , wavelength)
Referenced by ERF::Advance(), ERF::advance_dycore(), ERF::advance_lsm(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), SurfaceLayer::compute_fluxes(), SurfaceLayer::compute_pblh(), if(), ERF::init_stuff(), ERF::InitData_post(), ERF::Interp2DArrays(), SurfaceLayer::make_SurfaceLayer_at_level(), ERF::MakeNewLevelFromCoarse(), ERF::MakeNewLevelFromScratch(), ERF::RemakeLevel(), ERF::volWgtSumMF(), and ERF::Write3DPlotFile().
ParallelFor()
ParallelFor (bx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const auto prob_lo=geomdata.ProbLo();const auto dx=geomdata.CellSize();const Real x=prob_lo[0]+(i+0.5) *dx[0];Real z=z_cc(i, j, k);Real z_base=Ampl *std::sin(kp *x);z -=z_base;Real fac=std::cosh(kp *(z - H))/std::sinh(kp *H);Real p_prime=-(Ampl *omega *omega/kp) *fac *std::sin(kp *x) *r_hse(i, j, k);Real p_total=p_hse(i, j, k)+p_prime;state_pert(i, j, k, RhoTheta_comp)=getRhoThetagivenP(p_total) - getRhoThetagivenP(p_hse(i, j, k));state_pert(i, j, k, RhoScalar_comp)=state_pert(i, j, k, Rho_comp);})
pp()
ParmParse pp ("prob")
query()
pp query ("Ampl" , Ampl)
Variable Documentation
Ampl
Real Ampl = 0.
Referenced by init_my_custom_terrain(), ParallelFor(), and ERF::Write3DPlotFile().
g
Real g = CONST_GRAV
H
Real H = geomdata.ProbHi()[2]
Referenced by ParallelFor(), and ERF::Write3DPlotFile().
kp
Real kp = 2.0 * PI / wavelength
Referenced by init_my_custom_terrain(), ParallelFor(), and ERF::Write3DPlotFile().
omega
Real omega = std::sqrt(g * kp)
Referenced by ParallelFor().
wavelength
Real wavelength = 1.0
Referenced by rrtmgp::get_wavelength_index(), rrtmgp::get_wavelength_index_lw(), rrtmgp::get_wavelength_index_sw(), init_my_custom_terrain(), and ERF::Write3DPlotFile().