ERF: Source/Diffusion/ERF_DiffSetup.H File Reference
ERF_DiffSetup.H File Reference
Functions
Vector< Real > alpha_eff (NPRIMVAR_max, 0.0)
if (l_consA)
alpha_eff_d resize (alpha_eff.size())
eddy_diff_idx_d resize (eddy_diff_idx.size())
eddy_diff_idy_d resize (eddy_diff_idy.size())
eddy_diff_idz_d resize (eddy_diff_idz.size())
Variables
DiffChoice diffChoice = solverChoice.diffChoice
TurbChoice turbChoice = solverChoice.turbChoice[level]
const Real dx_inv = cellSizeInv[0]
const Real dy_inv = cellSizeInv[1]
const auto & dom_lo = lbound(domain)
const auto & dom_hi = ubound(domain)
Real l_inv_theta0 = (turbChoice.theta_ref > 0) ? 1.0 / turbChoice.theta_ref : 1.0
Real l_abs_g = std::abs(grav_gpu[2])
bool l_use_keqn = turbChoice.use_keqn
bool l_use_mynn = turbChoice.use_pbl_tke
bool l_consA = (diffChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
bool l_turb = turbChoice.use_kturb
const Box xbx = surroundingNodes(bx,0)
const Box ybx = surroundingNodes(bx,1)
const Box zbx = surroundingNodes(bx,2)
const int end_comp = start_comp + num_comp - 1
else
Vector< int > eddy_diff_idy
Vector< int > eddy_diff_idz
Gpu::AsyncVector< Real > alpha_eff_d
Gpu::AsyncVector< int > eddy_diff_idx_d
Gpu::AsyncVector< int > eddy_diff_idy_d
Gpu::AsyncVector< int > eddy_diff_idz_d
Real * d_alpha_eff = alpha_eff_d.data()
int * d_eddy_diff_idx = eddy_diff_idx_d.data()
int * d_eddy_diff_idy = eddy_diff_idy_d.data()
int * d_eddy_diff_idz = eddy_diff_idz_d.data()
Function Documentation
alpha_eff()
Vector<Real> alpha_eff (NPRIMVAR_max , 0. 0)
Referenced by if().
if()
if (l_consA)
                  {
         for (int i = 0; i < NPRIMVAR_max; ++i) {
            switch (i) {
                case PrimTheta_comp:
                     alpha_eff[PrimTheta_comp] = diffChoice.alpha_T;
                     break;
                case PrimScalar_comp:
                     alpha_eff[PrimScalar_comp] = diffChoice.alpha_C;
                     break;
                case PrimQ1_comp:
                     alpha_eff[PrimQ1_comp] = diffChoice.alpha_C;
                     break;
                case PrimQ2_comp:
                     alpha_eff[PrimQ2_comp] = diffChoice.alpha_C;
                     break;
                case PrimQ3_comp:
                    alpha_eff[PrimQ3_comp] = diffChoice.alpha_C;
                    break;
                case PrimQ4_comp:
                    alpha_eff[PrimQ4_comp] = diffChoice.alpha_C;
                    break;
                case PrimQ5_comp:
                    alpha_eff[PrimQ5_comp] = diffChoice.alpha_C;
                    break;
                case PrimQ6_comp:
                    alpha_eff[PrimQ6_comp] = diffChoice.alpha_C;
                    break;
                default:
                     alpha_eff[i] = 0.0;
                     break;
           }
        }
     } else {
resize() [1/4]
alpha_eff_d resize (alpha_eff. size())
resize() [2/4]
eddy_diff_idx_d resize (eddy_diff_idx. size())
resize() [3/4]
eddy_diff_idy_d resize (eddy_diff_idy. size())
resize() [4/4]
eddy_diff_idz_d resize (eddy_diff_idz. size())
Variable Documentation
alpha_eff_d
Gpu::AsyncVector<Real> alpha_eff_d
d_alpha_eff
Real* d_alpha_eff = alpha_eff_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
d_eddy_diff_idx
int* d_eddy_diff_idx = eddy_diff_idx_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
d_eddy_diff_idy
int* d_eddy_diff_idy = eddy_diff_idy_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
d_eddy_diff_idz
int* d_eddy_diff_idz = eddy_diff_idz_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
diffChoice
DiffChoice diffChoice = solverChoice.diffChoice
Referenced by if().
dom_hi
const auto& dom_hi = ubound(domain)
Referenced by MOSTAverage::compute_plane_averages(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ERF::CreateWeatherDataGeomBoxArrayDistMap(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), ERF::fill_from_bndryregs(), ERFPhysBCFunct_base::impose_lateral_basestate_bcs(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_base::impose_vertical_basestate_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), ERF::ImposeBCsOnPhi(), make_terrain_fitted_coords(), PlaneAverage::PlaneAverage(), ERF::poisson_wall_dist(), realbdy_bc_bxs_xy(), realbdy_compute_interior_ghost_rhs(), realbdy_interior_bxs_xy(), realbdy_set_rhs_in_spec_region(), ERF::solve_with_EB_mlmg(), ERF::solve_with_gmres(), and ERF::solve_with_mlmg().
dom_lo
const auto& dom_lo = lbound(domain)
Referenced by ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ERF::CreateWeatherDataGeomBoxArrayDistMap(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), ERF::fill_from_bndryregs(), ERFPhysBCFunct_base::impose_lateral_basestate_bcs(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_base::impose_vertical_basestate_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), ERF::ImposeBCsOnPhi(), make_terrain_fitted_coords(), PlaneAverage::PlaneAverage(), ERF::poisson_wall_dist(), realbdy_bc_bxs_xy(), realbdy_compute_interior_ghost_rhs(), realbdy_interior_bxs_xy(), realbdy_set_rhs_in_spec_region(), ERF::solve_with_EB_mlmg(), ERF::solve_with_gmres(), and ERF::solve_with_mlmg().
dx_inv
const Real dx_inv = cellSizeInv[0]
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
dy_inv
const Real dy_inv = cellSizeInv[1]
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
eddy_diff_idx_d
Gpu::AsyncVector<int> eddy_diff_idx_d
eddy_diff_idy
Vector<int> eddy_diff_idy
Initial value:
{EddyDiff::Theta_h, EddyDiff::KE_h, EddyDiff::Scalar_h,
                              EddyDiff::Q_h    , EddyDiff::Q_h,  EddyDiff::Q_h ,
                              EddyDiff::Q_h    , EddyDiff::Q_h,  EddyDiff::Q_h }
eddy_diff_idy_d
Gpu::AsyncVector<int> eddy_diff_idy_d
eddy_diff_idz
Vector<int> eddy_diff_idz
Initial value:
{EddyDiff::Theta_v, EddyDiff::KE_v, EddyDiff::Scalar_v,
                              EddyDiff::Q_v    , EddyDiff::Q_v,  EddyDiff::Q_v ,
                              EddyDiff::Q_v    , EddyDiff::Q_v,  EddyDiff::Q_v }
eddy_diff_idz_d
Gpu::AsyncVector<int> eddy_diff_idz_d
else
else
end_comp
const int end_comp = start_comp + num_comp - 1
l_abs_g
Real l_abs_g = std::abs(grav_gpu[2])
Referenced by ComputeTurbulentViscosityLES(), and if().
l_consA
bool l_consA = (diffChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
l_inv_theta0
Real l_inv_theta0 = (turbChoice.theta_ref > 0) ? 1.0 / turbChoice.theta_ref : 1.0
Referenced by ComputeTurbulentViscosityLES(), and if().
l_turb
bool l_turb = turbChoice.use_kturb
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), and DiffusionSrcForState_T().
l_use_keqn
bool l_use_keqn = turbChoice.use_keqn
l_use_mynn
bool l_use_mynn = turbChoice.use_pbl_tke
turbChoice
TurbChoice turbChoice = solverChoice.turbChoice[level]
Referenced by ComputeDiffusivityMRF(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeTurbulentViscosity(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityRANS(), and if().
xbx
const Box xbx = surroundingNodes(bx,0)
Referenced by AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), init_bx_velocities_from_input_sounding(), ERF::init_custom(), ERF::init_thin_body(), and ERF::Write3DPlotFile().
ybx
const Box ybx = surroundingNodes(bx,1)
Referenced by AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), init_bx_velocities_from_input_sounding(), ERF::init_custom(), and ERF::init_thin_body().
zbx
const Box zbx = surroundingNodes(bx,2)
Referenced by AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), ERF::derive_diag_profiles_stag(), ERF::derive_stress_profiles_stag(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), ERF::ImposeBCsOnPhi(), init_bx_velocities_from_input_sounding(), ERF::init_custom(), ERF::init_thin_body(), ERFPhysBCFunct_w::operator()(), and ProblemBase::read_custom_terrain().