ERF: Source/Diffusion/ERF_Diffusion.H File Reference
ERF_Diffusion.H File Reference
#include "AMReX.H"
#include "AMReX_MultiFab.H"
#include "AMReX_BCRec.H"
#include "ERF_DataStruct.H"
#include "ERF_IndexDefines.H"
#include "ERF_SurfaceLayer.H"
#include "ERF_EB.H"
Functions
void DiffusionSrcForMom (const amrex::Box &bxx, const amrex::Box &bxy, const amrex::Box &bxz, const amrex::Array4< amrex::Real > &rho_u_rhs, const amrex::Array4< amrex::Real > &rho_v_rhs, const amrex::Array4< amrex::Real > &rho_w_rhs, const amrex::Array4< const amrex::Real > &tau11, const amrex::Array4< const amrex::Real > &tau22, const amrex::Array4< const amrex::Real > &tau33, const amrex::Array4< const amrex::Real > &tau12, const amrex::Array4< const amrex::Real > &tau21, const amrex::Array4< const amrex::Real > &tau13, const amrex::Array4< const amrex::Real > &tau31, const amrex::Array4< const amrex::Real > &tau23, const amrex::Array4< const amrex::Real > &tau32, const amrex::Array4< const amrex::Real > &detJ_arr, const amrex::Gpu::DeviceVector< amrex::Real > &stretched_dz_d, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, const bool use_stretched_dz, const bool use_variable_dz)
void DiffusionSrcForMom_EB (const amrex::MFIter &mfi, [[maybe_unused]] const amrex::Box &domain, const amrex::Box &bxx, const amrex::Box &bxy, const amrex::Box &bxz, const amrex::Array4< amrex::Real > &rho_u_rhs, const amrex::Array4< amrex::Real > &rho_v_rhs, const amrex::Array4< amrex::Real > &rho_w_rhs, const amrex::Array4< const amrex::Real > &u_arr, const amrex::Array4< const amrex::Real > &v_arr, const amrex::Array4< const amrex::Real > &w_arr, const amrex::Array4< const amrex::Real > &tau11, const amrex::Array4< const amrex::Real > &tau22, const amrex::Array4< const amrex::Real > &tau33, const amrex::Array4< const amrex::Real > &tau12, const amrex::Array4< const amrex::Real > &tau13, const amrex::Array4< const amrex::Real > &tau23, const amrex::Real *dx_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, const SolverChoice &solverChoice, const eb_ &ebfact, [[maybe_unused]] const amrex::BCRec *bc_ptr)
void DiffusionSrcForState_N (const amrex::Box &bx, const amrex::Box &domain, int start_comp, int num_comp, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< const amrex::Real > &cell_prim, const amrex::Array4< amrex::Real > &cell_rhs, const amrex::Array4< amrex::Real > &xflux, const amrex::Array4< amrex::Real > &yflux, const amrex::Array4< amrex::Real > &zflux, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &SmnSmn_a, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &hfx_z, amrex::Array4< amrex::Real > &qfx1_z, amrex::Array4< amrex::Real > &qfx2_z, amrex::Array4< amrex::Real > &diss, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const int level, const amrex::Array4< const amrex::Real > &tm_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > grav_gpu, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
void DiffusionSrcForState_S (const amrex::Box &bx, const amrex::Box &domain, int start_comp, int num_comp, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< const amrex::Real > &cell_prim, const amrex::Array4< amrex::Real > &cell_rhs, const amrex::Array4< amrex::Real > &xflux, const amrex::Array4< amrex::Real > &yflux, const amrex::Array4< amrex::Real > &zflux, const amrex::Gpu::DeviceVector< amrex::Real > &stretched_dz_d, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &SmnSmn_a, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &hfx_z, amrex::Array4< amrex::Real > &qfx1_z, amrex::Array4< amrex::Real > &qfx2_z, amrex::Array4< amrex::Real > &diss, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const int level, const amrex::Array4< const amrex::Real > &tm_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > grav_gpu, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
void DiffusionSrcForState_T (const amrex::Box &bx, const amrex::Box &domain, int start_comp, int num_comp, const bool &rotate, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< const amrex::Real > &cell_prim, const amrex::Array4< amrex::Real > &cell_rhs, const amrex::Array4< amrex::Real > &xflux, const amrex::Array4< amrex::Real > &yflux, const amrex::Array4< amrex::Real > &zflux, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Array4< const amrex::Real > &z_cc, const amrex::Array4< const amrex::Real > &ax, const amrex::Array4< const amrex::Real > &ay, const amrex::Array4< const amrex::Real > &az, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &SmnSmn_a, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &hfx_x, amrex::Array4< amrex::Real > &hfx_y, amrex::Array4< amrex::Real > &hfx_z, amrex::Array4< amrex::Real > &qfx1_x, amrex::Array4< amrex::Real > &qfx1_y, amrex::Array4< amrex::Real > &qfx1_z, amrex::Array4< amrex::Real > &qfx2_z, amrex::Array4< amrex::Real > &diss, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const int level, const amrex::Array4< const amrex::Real > &tm_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > grav_gpu, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
void ComputeStressConsVisc_N (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > &cell_data, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau23, const amrex::Array4< const amrex::Real > &er_arr, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i, amrex::Array4< amrex::Real > &tau33i)
void ComputeStressConsVisc_S (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > &cell_data, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau21, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau31, amrex::Array4< amrex::Real > &tau23, amrex::Array4< amrex::Real > &tau32, const amrex::Array4< const amrex::Real > &er_arr, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i, amrex::Array4< amrex::Real > &tau33i)
void ComputeStressConsVisc_T (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > &cell_data, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau21, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau31, amrex::Array4< amrex::Real > &tau23, amrex::Array4< amrex::Real > &tau32, const amrex::Array4< const amrex::Real > &er_arr, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i, amrex::Array4< amrex::Real > &tau33i)
void ComputeStressVarVisc_N (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > &mu_turb, const amrex::Array4< const amrex::Real > &cell_data, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau23, const amrex::Array4< const amrex::Real > &er_arr, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i, amrex::Array4< amrex::Real > &tau33i)
void ComputeStressVarVisc_S (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > &mu_turb, const amrex::Array4< const amrex::Real > &cell_data, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau21, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau31, amrex::Array4< amrex::Real > &tau23, amrex::Array4< amrex::Real > &tau32, const amrex::Array4< const amrex::Real > &er_arr, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i, amrex::Array4< amrex::Real > &tau33i)
void ComputeStressVarVisc_T (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > &mu_turb, const amrex::Array4< const amrex::Real > &cell_data, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau21, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau31, amrex::Array4< amrex::Real > &tau23, amrex::Array4< amrex::Real > &tau32, const amrex::Array4< const amrex::Real > &er_arr, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i, amrex::Array4< amrex::Real > &tau33i)
void ComputeStrain_N (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Box domain, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &w, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau23, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, const amrex::BCRec *bc_ptr, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i)
void ComputeStrain_S (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Box domain, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &w, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau21, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau31, amrex::Array4< amrex::Real > &tau23, amrex::Array4< amrex::Real > &tau32, const amrex::Gpu::DeviceVector< amrex::Real > &stretched_dz_d, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, const amrex::BCRec *bc_ptr, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i)
void ComputeStrain_T (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Box domain, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &w, amrex::Array4< amrex::Real > &tau11, amrex::Array4< amrex::Real > &tau22, amrex::Array4< amrex::Real > &tau33, amrex::Array4< amrex::Real > &tau12, amrex::Array4< amrex::Real > &tau21, amrex::Array4< amrex::Real > &tau13, amrex::Array4< amrex::Real > &tau31, amrex::Array4< amrex::Real > &tau23, amrex::Array4< amrex::Real > &tau32, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv, const amrex::Array4< const amrex::Real > &mf_mx, const amrex::Array4< const amrex::Real > &mf_ux, const amrex::Array4< const amrex::Real > &mf_vx, const amrex::Array4< const amrex::Real > &mf_my, const amrex::Array4< const amrex::Real > &mf_uy, const amrex::Array4< const amrex::Real > &mf_vy, const amrex::BCRec *bc_ptr, amrex::Array4< amrex::Real > &tau13i, amrex::Array4< amrex::Real > &tau23i)
void ImplicitDiffForState_N (const amrex::Box &bx, const amrex::Box &domain, const int level, const amrex::Real dt, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM *2 > &bc_neumann_vals, const amrex::Array4< amrex::Real > &cell_data, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &hfx_z, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
void ImplicitDiffForState_S (const amrex::Box &bx, const amrex::Box &domain, const int level, const amrex::Real dt, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM *2 > &bc_neumann_vals, const amrex::Array4< amrex::Real > &cell_data, const amrex::Gpu::DeviceVector< amrex::Real > &stretched_dz_d, const amrex::Array4< const amrex::Real > &hfx_z, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
void ImplicitDiffForState_T (const amrex::Box &bx, const amrex::Box &domain, const int level, const amrex::Real dt, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM *2 > &bc_neumann_vals, const amrex::Array4< amrex::Real > &cell_data, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &hfx_z, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
template<int stagdir>
void ImplicitDiffForMom_N (const amrex::Box &bx, const amrex::Box &domain, const int level, const amrex::Real dt, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< amrex::Real > &face_data, const amrex::Array4< const amrex::Real > &tau_corr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
template<int stagdir>
void ImplicitDiffForMom_S (const amrex::Box &bx, const amrex::Box &domain, const int level, const amrex::Real dt, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< amrex::Real > &face_data, const amrex::Array4< const amrex::Real > &tau_corr, const amrex::Gpu::DeviceVector< amrex::Real > &stretched_dz_d, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
template<int stagdir>
void ImplicitDiffForMom_T (const amrex::Box &bx, const amrex::Box &domain, const int level, const amrex::Real dt, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< amrex::Real > &face_data, const amrex::Array4< const amrex::Real > &tau_corr, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Array4< const amrex::Real > &detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &mu_turb, const SolverChoice &solverChoice, const amrex::BCRec *bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Function Documentation
ComputeStrain_N()
void ComputeStrain_N (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Box domain, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & w, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau23, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, const amrex::BCRec * bc_ptr, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i)
ComputeStrain_S()
void ComputeStrain_S (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Box domain, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & w, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau21, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau31, amrex::Array4< amrex::Real > & tau23, amrex::Array4< amrex::Real > & tau32, const amrex::Gpu::DeviceVector< amrex::Real > & stretched_dz_d, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, const amrex::BCRec * bc_ptr, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i)
ComputeStrain_T()
void ComputeStrain_T (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Box domain, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & w, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau21, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau31, amrex::Array4< amrex::Real > & tau23, amrex::Array4< amrex::Real > & tau32, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, const amrex::BCRec * bc_ptr, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i)
ComputeStressConsVisc_N()
void ComputeStressConsVisc_N (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > & cell_data, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau23, const amrex::Array4< const amrex::Real > & er_arr, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i, amrex::Array4< amrex::Real > & tau33i)
ComputeStressConsVisc_S()
void ComputeStressConsVisc_S (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > & cell_data, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau21, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau31, amrex::Array4< amrex::Real > & tau23, amrex::Array4< amrex::Real > & tau32, const amrex::Array4< const amrex::Real > & er_arr, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i, amrex::Array4< amrex::Real > & tau33i)
ComputeStressConsVisc_T()
void ComputeStressConsVisc_T (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > & cell_data, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau21, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau31, amrex::Array4< amrex::Real > & tau23, amrex::Array4< amrex::Real > & tau32, const amrex::Array4< const amrex::Real > & er_arr, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i, amrex::Array4< amrex::Real > & tau33i)
ComputeStressVarVisc_N()
void ComputeStressVarVisc_N (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > & mu_turb, const amrex::Array4< const amrex::Real > & cell_data, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau23, const amrex::Array4< const amrex::Real > & er_arr, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i, amrex::Array4< amrex::Real > & tau33i)
ComputeStressVarVisc_S()
void ComputeStressVarVisc_S (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > & mu_turb, const amrex::Array4< const amrex::Real > & cell_data, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau21, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau31, amrex::Array4< amrex::Real > & tau23, amrex::Array4< amrex::Real > & tau32, const amrex::Array4< const amrex::Real > & er_arr, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i, amrex::Array4< amrex::Real > & tau33i)
ComputeStressVarVisc_T()
void ComputeStressVarVisc_T (amrex::Box bxcc, amrex::Box tbxxy, amrex::Box tbxxz, amrex::Box tbxyz, amrex::Real mu_eff, const amrex::Array4< const amrex::Real > & mu_turb, const amrex::Array4< const amrex::Real > & cell_data, amrex::Array4< amrex::Real > & tau11, amrex::Array4< amrex::Real > & tau22, amrex::Array4< amrex::Real > & tau33, amrex::Array4< amrex::Real > & tau12, amrex::Array4< amrex::Real > & tau21, amrex::Array4< amrex::Real > & tau13, amrex::Array4< amrex::Real > & tau31, amrex::Array4< amrex::Real > & tau23, amrex::Array4< amrex::Real > & tau32, const amrex::Array4< const amrex::Real > & er_arr, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & tau13i, amrex::Array4< amrex::Real > & tau23i, amrex::Array4< amrex::Real > & tau33i)
DiffusionSrcForMom()
void DiffusionSrcForMom (const amrex::Box & bxx, const amrex::Box & bxy, const amrex::Box & bxz, const amrex::Array4< amrex::Real > & rho_u_rhs, const amrex::Array4< amrex::Real > & rho_v_rhs, const amrex::Array4< amrex::Real > & rho_w_rhs, const amrex::Array4< const amrex::Real > & tau11, const amrex::Array4< const amrex::Real > & tau22, const amrex::Array4< const amrex::Real > & tau33, const amrex::Array4< const amrex::Real > & tau12, const amrex::Array4< const amrex::Real > & tau21, const amrex::Array4< const amrex::Real > & tau13, const amrex::Array4< const amrex::Real > & tau31, const amrex::Array4< const amrex::Real > & tau23, const amrex::Array4< const amrex::Real > & tau32, const amrex::Array4< const amrex::Real > & detJ_arr, const amrex::Gpu::DeviceVector< amrex::Real > & stretched_dz_d, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, const bool use_stretched_dz, const bool use_variable_dz)
Referenced by erf_slow_rhs_pre().
DiffusionSrcForMom_EB()
void DiffusionSrcForMom_EB (const amrex::MFIter & mfi, [[maybe_unused] ] const amrex::Box & domain, const amrex::Box & bxx, const amrex::Box & bxy, const amrex::Box & bxz, const amrex::Array4< amrex::Real > & rho_u_rhs, const amrex::Array4< amrex::Real > & rho_v_rhs, const amrex::Array4< amrex::Real > & rho_w_rhs, const amrex::Array4< const amrex::Real > & u_arr, const amrex::Array4< const amrex::Real > & v_arr, const amrex::Array4< const amrex::Real > & w_arr, const amrex::Array4< const amrex::Real > & tau11, const amrex::Array4< const amrex::Real > & tau22, const amrex::Array4< const amrex::Real > & tau33, const amrex::Array4< const amrex::Real > & tau12, const amrex::Array4< const amrex::Real > & tau13, const amrex::Array4< const amrex::Real > & tau23, const amrex::Real * dx_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, const SolverChoice & solverChoice, const eb_ & ebfact, [[maybe_unused] ] const amrex::BCRec * bc_ptr)
Referenced by erf_slow_rhs_pre().
DiffusionSrcForState_N()
void DiffusionSrcForState_N (const amrex::Box & bx, const amrex::Box & domain, int start_comp, int num_comp, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< const amrex::Real > & cell_prim, const amrex::Array4< amrex::Real > & cell_rhs, const amrex::Array4< amrex::Real > & xflux, const amrex::Array4< amrex::Real > & yflux, const amrex::Array4< amrex::Real > & zflux, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & SmnSmn_a, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & hfx_z, amrex::Array4< amrex::Real > & qfx1_z, amrex::Array4< amrex::Real > & qfx2_z, amrex::Array4< amrex::Real > & diss, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const int level, const amrex::Array4< const amrex::Real > & tm_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > grav_gpu, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Referenced by erf_slow_rhs_post(), and erf_slow_rhs_pre().
DiffusionSrcForState_S()
void DiffusionSrcForState_S (const amrex::Box & bx, const amrex::Box & domain, int start_comp, int num_comp, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< const amrex::Real > & cell_prim, const amrex::Array4< amrex::Real > & cell_rhs, const amrex::Array4< amrex::Real > & xflux, const amrex::Array4< amrex::Real > & yflux, const amrex::Array4< amrex::Real > & zflux, const amrex::Gpu::DeviceVector< amrex::Real > & stretched_dz_d, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & SmnSmn_a, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & hfx_z, amrex::Array4< amrex::Real > & qfx1_z, amrex::Array4< amrex::Real > & qfx2_z, amrex::Array4< amrex::Real > & diss, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const int level, const amrex::Array4< const amrex::Real > & tm_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > grav_gpu, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Referenced by erf_slow_rhs_post(), and erf_slow_rhs_pre().
DiffusionSrcForState_T()
void DiffusionSrcForState_T (const amrex::Box & bx, const amrex::Box & domain, int start_comp, int num_comp, const bool & rotate, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< const amrex::Real > & cell_prim, const amrex::Array4< amrex::Real > & cell_rhs, const amrex::Array4< amrex::Real > & xflux, const amrex::Array4< amrex::Real > & yflux, const amrex::Array4< amrex::Real > & zflux, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Array4< const amrex::Real > & z_cc, const amrex::Array4< const amrex::Real > & ax, const amrex::Array4< const amrex::Real > & ay, const amrex::Array4< const amrex::Real > & az, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv, const amrex::Array4< const amrex::Real > & SmnSmn_a, const amrex::Array4< const amrex::Real > & mf_mx, const amrex::Array4< const amrex::Real > & mf_ux, const amrex::Array4< const amrex::Real > & mf_vx, const amrex::Array4< const amrex::Real > & mf_my, const amrex::Array4< const amrex::Real > & mf_uy, const amrex::Array4< const amrex::Real > & mf_vy, amrex::Array4< amrex::Real > & hfx_x, amrex::Array4< amrex::Real > & hfx_y, amrex::Array4< amrex::Real > & hfx_z, amrex::Array4< amrex::Real > & qfx1_x, amrex::Array4< amrex::Real > & qfx1_y, amrex::Array4< amrex::Real > & qfx1_z, amrex::Array4< amrex::Real > & qfx2_z, amrex::Array4< amrex::Real > & diss, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const int level, const amrex::Array4< const amrex::Real > & tm_arr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > grav_gpu, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Referenced by erf_slow_rhs_post(), and erf_slow_rhs_pre().
ImplicitDiffForMom_N()
template<int stagdir> void ImplicitDiffForMom_N (const amrex::Box & bx, const amrex::Box & domain, const int level, const amrex::Real dt, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< amrex::Real > & face_data, const amrex::Array4< const amrex::Real > & tau_corr, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
ImplicitDiffForMom_S()
template<int stagdir> void ImplicitDiffForMom_S (const amrex::Box & bx, const amrex::Box & domain, const int level, const amrex::Real dt, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< amrex::Real > & face_data, const amrex::Array4< const amrex::Real > & tau_corr, const amrex::Gpu::DeviceVector< amrex::Real > & stretched_dz_d, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
ImplicitDiffForMom_T()
template<int stagdir> void ImplicitDiffForMom_T (const amrex::Box & bx, const amrex::Box & domain, const int level, const amrex::Real dt, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< amrex::Real > & face_data, const amrex::Array4< const amrex::Real > & tau_corr, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
ImplicitDiffForState_N()
void ImplicitDiffForState_N (const amrex::Box & bx, const amrex::Box & domain, const int level, const amrex::Real dt, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM *2 > & bc_neumann_vals, const amrex::Array4< amrex::Real > & cell_data, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & hfx_z, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Referenced by if().
ImplicitDiffForState_S()
void ImplicitDiffForState_S (const amrex::Box & bx, const amrex::Box & domain, const int level, const amrex::Real dt, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM *2 > & bc_neumann_vals, const amrex::Array4< amrex::Real > & cell_data, const amrex::Gpu::DeviceVector< amrex::Real > & stretched_dz_d, const amrex::Array4< const amrex::Real > & hfx_z, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Referenced by if().
ImplicitDiffForState_T()
void ImplicitDiffForState_T (const amrex::Box & bx, const amrex::Box & domain, const int level, const amrex::Real dt, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM *2 > & bc_neumann_vals, const amrex::Array4< amrex::Real > & cell_data, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Array4< const amrex::Real > & detJ, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & hfx_z, const amrex::Array4< const amrex::Real > & mu_turb, const SolverChoice & solverChoice, const amrex::BCRec * bc_ptr, const bool use_SurfLayer, const amrex::Real implicit_fac)
Referenced by if().