ERF: Source/BoundaryConditions/ERF_MOSTStress.H File Reference
ERF_MOSTStress.H File Reference
#include <ERF_Constants.H>
#include <ERF_IndexDefines.H>
#include <ERF_MOSTRoughness.H>
#include <ERF_Wstar.H>
Classes
struct most_data
struct similarity_funs
struct adiabatic
struct adiabatic_charnock
struct adiabatic_mod_charnock
struct adiabatic_donelan
struct adiabatic_wave_coupled
struct surface_flux
struct surface_flux_charnock
struct surface_flux_mod_charnock
struct surface_flux_donelan
struct surface_flux_wave_coupled
struct surface_temp
struct surface_temp_charnock
struct surface_temp_mod_charnock
struct surface_temp_donelan
struct surface_temp_wave_coupled
struct moeng_flux
struct donelan_flux
struct custom_flux
struct bulk_coeff_flux
struct rico_flux
struct rotate_flux
Functions
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real air_viscosity (amrex::Real T_degK)
Function Documentation
air_viscosity()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real air_viscosity (amrex::Real T_degK)
Empirical kinematic viscosity [m2/s] formula from Andreas (1989) CRREL Rep. 89-11, valid between -173 and 277 deg C.
 {
     amrex::Real TC = T_degK - amrex::Real(273.15);
     return amrex::Real(1.326e-5)*(one + amrex::Real(6.542e-3)*TC + amrex::Real(8.301e-6)*TC*TC - amrex::Real(4.84e-9)*TC*TC*TC);
 }
Referenced by adiabatic_charnock::iterate_flux(), surface_flux_charnock::iterate_flux(), and surface_temp_charnock::iterate_flux().