ERF: Source/PBL/Shoc/ERF_ShocDriver.H File Reference
ERF_ShocDriver.H File Reference
#include "ERF_ShocDiagnostics.H"
#include "ERF_ShocTypes.H"
#include "ERF_ShocPreprocess.H"
#include "ERF_ShocColumnData.H"
#include <AMReX_BoxArray.H>
#include <AMReX_MultiFab.H>
#include <memory>
Classes
class ShocDriver
Functions
bool shoc_boxarray_spans_full_height (const amrex::BoxArray &ba, const amrex::Box &domain)
bool shoc_layout_requires_number_closure (const MoistureComponentIndices &indices, int ncomp) noexcept
bool shoc_driver_host_diffusion_moisture_supported (const ShocRuntimeOptions &opts, MoistureType moisture_type, std::string &error_message)
bool shoc_driver_state_update_layout_supported (const ShocRuntimeOptions &opts, const MoistureComponentIndices &indices, int ncomp, std::string &error_message)
Function Documentation
shoc_boxarray_spans_full_height()
bool shoc_boxarray_spans_full_height (const amrex::BoxArray & ba, const amrex::Box & domain)
shoc_driver_host_diffusion_moisture_supported()
bool shoc_driver_host_diffusion_moisture_supported (const ShocRuntimeOptions & opts, MoistureType moisture_type, std::string & error_message) inline
 {
     if (!shoc_uses_host_diffusion(opts.transport_mode) || moisture_type == MoistureType::None) {
         return true;
     }
     error_message =
         "Native SHOC host_diffusion with moisture is not yet supported because SHOC does not own cloud macrophysics in this mode while SHOC-family microphysics condensation is suppressed. Use state_update for moist SHOC runs, or run host_diffusion only for dry cases until a transport-aware microphysics ownership predicate is implemented.";
     return false;
 }
Referenced by ShocDriver::ShocDriver().
shoc_driver_state_update_layout_supported()
bool shoc_driver_state_update_layout_supported (const ShocRuntimeOptions & opts, const MoistureComponentIndices & indices, int ncomp, std::string & error_message) inline
 {
     if (!shoc_uses_state_update(opts.transport_mode) ||
         !shoc_layout_requires_number_closure(indices, ncomp)) {
         return true;
     }
     error_message =
         "Native SHOC state_update does not yet support number-aware microphysics layouts with cloud/ice number concentrations. A number closure is required before SHOC can update cloud mass in these layouts.";
     return false;
 }
Referenced by ShocDriver::advance().
shoc_layout_requires_number_closure()
bool shoc_layout_requires_number_closure (const MoistureComponentIndices & indices, int ncomp) inline noexcept
 {
     return shoc_valid_comp(indices.nc, ncomp) || shoc_valid_comp(indices.ni, ncomp);
 }
Referenced by shoc_driver_state_update_layout_supported().