ERF: Source/Prob/ERF_InitCustomPertVels_IsentropicVortex.H File Reference
ERF_InitCustomPertVels_IsentropicVortex.H File Reference
Functions
ParmParse pp_for_pert_vels ("prob")
pp_for_pert_vels query ("M_inf", M_inf)
pp_for_pert_vels query ("T_inf", T_inf)
pp_for_pert_vels query ("alpha", alpha)
pp_for_pert_vels query ("gamma", gamma)
pp_for_pert_vels query ("beta", beta)
pp_for_pert_vels query ("sigma", sigma)
pp_for_pert_vels query ("R", R)
pp_for_pert_vels query ("xc", xc_frac)
pp_for_pert_vels query ("yc", yc_frac)
ParallelFor (xbx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const Real *dx=geomdata.CellSize();const Real x=i *dx[0];const Real y=(j+myhalf) *dx[1];const Real Omg=erf_vortex_Gaussian(x, y, xc, yc, R, beta, sigma);x_vel_pert(i, j, k)=(M_inf *std::cos(alpha) -(y - yc)/R *Omg) *a_inf;})
ParallelFor (ybx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const Real *dx=geomdata.CellSize();const Real x=(i+myhalf) *dx[0];const Real y=j *dx[1];const Real Omg=erf_vortex_Gaussian(x, y, xc, yc, R, beta, sigma);y_vel_pert(i, j, k)=(M_inf *std::sin(alpha)+(x - xc)/R *Omg) *a_inf;})
Variables
amrex::Real M_inf = amrex::Real(0.2)
amrex::Real T_inf = amrex::Real(300.0)
amrex::Real alpha = zero
amrex::Real gamma = Gamma
amrex::Real beta = amrex::Real(0.01)
amrex::Real sigma = one
amrex::Real R = two
amrex::Real xc_frac = myhalf
amrex::Real yc_frac = myhalf
const amrex::Real * prob_lo = geomdata.ProbLo()
const amrex::Real * prob_hi = geomdata.ProbHi()
amrex::Real xc = xc_frac * (prob_hi[0] - prob_lo[0])
amrex::Real yc = yc_frac * (prob_hi[1] - prob_lo[1])
amrex::Real a_inf = std::sqrt(gamma * R_d * T_inf)
Function Documentation
ParallelFor() [1/2]
ParallelFor (xbx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const Real *dx=geomdata.CellSize();const Real x=i *dx[0];const Real y=(j+myhalf) *dx[1];const Real Omg=erf_vortex_Gaussian(x, y, xc, yc, R, beta, sigma);x_vel_pert(i, j, k)=(M_inf *std::cos(alpha) -(y - yc)/R *Omg) *a_inf;})
ParallelFor() [2/2]
ParallelFor (ybx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const Real *dx=geomdata.CellSize();const Real x=(i+myhalf) *dx[0];const Real y=j *dx[1];const Real Omg=erf_vortex_Gaussian(x, y, xc, yc, R, beta, sigma);y_vel_pert(i, j, k)=(M_inf *std::sin(alpha)+(x - xc)/R *Omg) *a_inf;})
pp_for_pert_vels()
ParmParse pp_for_pert_vels ("prob")
query() [1/9]
pp_for_pert_vels query ("alpha" , alpha)
query() [2/9]
pp_for_pert_vels query ("beta" , beta)
query() [3/9]
pp_for_pert_vels query ("gamma" , gamma)
query() [4/9]
pp_for_pert_vels query ("M_inf" , M_inf)
query() [5/9]
pp_for_pert_vels query ("R" , R)
query() [6/9]
pp_for_pert_vels query ("sigma" , sigma)
query() [7/9]
pp_for_pert_vels query ("T_inf" , T_inf)
query() [8/9]
pp_for_pert_vels query ("xc" , xc_frac)
query() [9/9]
pp_for_pert_vels query ("yc" , yc_frac)
Variable Documentation
a_inf
amrex::Real a_inf = std::sqrt(gamma * R_d * T_inf)
Referenced by ParallelFor().
alpha
amrex::Real alpha = zero
Referenced by ParallelFor().
beta
amrex::Real beta = amrex::Real(0.01)
Referenced by ParallelFor().
gamma
amrex::Real gamma = Gamma
M_inf
amrex::Real M_inf = amrex::Real(0.2)
Referenced by ParallelFor().
prob_hi
const amrex::Real* prob_hi = geomdata.ProbHi()
prob_lo
const amrex::Real* prob_lo = geomdata.ProbLo()
R
amrex::Real R = two
Referenced by ParallelFor().
sigma
amrex::Real sigma = one
Referenced by ParallelFor().
T_inf
amrex::Real T_inf = amrex::Real(300.0)
xc
amrex::Real xc = xc_frac * (prob_hi[0] - prob_lo[0])
Referenced by ParallelFor().
xc_frac
amrex::Real xc_frac = myhalf
yc
amrex::Real yc = yc_frac * (prob_hi[1] - prob_lo[1])
Referenced by ParallelFor().
yc_frac
amrex::Real yc_frac = myhalf