ERF: Source/Prob/ERF_InitCustomPertVels_CouettePoiseuille.H File Reference
ERF_InitCustomPertVels_CouettePoiseuille.H File Reference
Functions
ParmParse pp ("prob")
pp query ("U_0", U_0)
pp query ("V_0", V_0)
pp query ("W_0", W_0)
pp get ("prob_type", prob_type)
AMREX_ALWAYS_ASSERT (prob_type==1||prob_type==10||prob_type==11||prob_type==20||prob_type==21)
pp query ("pert_periods_u", pert_periods_u)
pp query ("pert_periods_v", pert_periods_v)
pp query ("pert_delta_u", pert_delta_u)
pp query ("pert_delta_u", pert_delta_v)
pp query ("pert_lo", pert_lo)
pp query ("pert_hi", pert_hi)
if (prob_type==1)
Variables
Real U_0 = 0.0
Real V_0 = 0.0
Real W_0 = 0.0
int prob_type
Real pert_periods_u = 5.0
Real pert_periods_v = 5.0
Real pert_delta_u = 0.0
Real pert_delta_v = 0.0
Real pert_lo = -1e34
Real pert_hi = 1e34
auto problo = geomdata.ProbLo()
auto probhi = geomdata.ProbHi()
Real aval = pert_periods_u * 2.0 * PI / (probhi[1] - problo[1])
Real bval = pert_periods_v * 2.0 * PI / (probhi[0] - problo[0])
Function Documentation
AMREX_ALWAYS_ASSERT()
AMREX_ALWAYS_ASSERT (prob_type = =1||prob_type==10||prob_type==11||prob_type==20||prob_type==21)
get()
pp get ("prob_type" , prob_type)
Referenced by ERF::Advance(), ERF::advance_dycore(), ERF::advance_lsm(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), SurfaceLayer::compute_fluxes(), SurfaceLayer::compute_pblh(), if(), ERF::init_stuff(), ERF::InitData_post(), ERF::Interp2DArrays(), SurfaceLayer::make_SurfaceLayer_at_level(), ERF::MakeNewLevelFromCoarse(), ERF::MakeNewLevelFromScratch(), ERF::RemakeLevel(), ERF::volWgtSumMF(), and ERF::Write3DPlotFile().
if()
else if (prob_type = = 1)
{
         ParallelFor(xbx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept {
             const auto *const prob_hi  = geomdata.ProbHi();
             const auto *const dx       = geomdata.CellSize();
             const Real z = (k + 0.5) * dx[2];
             x_vel_pert(i, j, k) = U_0 * z / prob_hi[2];
         });
         ParallelFor(ybx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept {
             const auto *const prob_hi  = geomdata.ProbHi();
             const auto *const dx       = geomdata.CellSize();
             const Real z = (k + 0.5) * dx[2];
             y_vel_pert(i, j, k) = V_0 * z / prob_hi[2];
         });
         ParallelFor(zbx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept {
             z_vel_pert(i, j, k) = W_0;
         });
     // Poiseuille flow
     } else if (prob_type == 10 || prob_type == 11) {
pp()
ParmParse pp ("prob")
query() [1/9]
pp query ("pert_delta_u" , pert_delta_u)
query() [2/9]
pp query ("pert_delta_u" , pert_delta_v)
query() [3/9]
pp query ("pert_hi" , pert_hi)
query() [4/9]
pp query ("pert_lo" , pert_lo)
query() [5/9]
pp query ("pert_periods_u" , pert_periods_u)
query() [6/9]
pp query ("pert_periods_v" , pert_periods_v)
query() [7/9]
pp query ("U_0" , U_0)
query() [8/9]
pp query ("V_0" , V_0)
query() [9/9]
pp query ("W_0" , W_0)
Variable Documentation
aval
Real aval = pert_periods_u * 2.0 * PI / (probhi[1] - problo[1])
Referenced by ncutils::NCVar::get_attr(), and ncutils::NCGroup::get_attr().
bval
Real bval = pert_periods_v * 2.0 * PI / (probhi[0] - problo[0])
pert_delta_u
Real pert_delta_u = 0.0
pert_delta_v
Real pert_delta_v = 0.0
pert_hi
Real pert_hi = 1e34
pert_lo
Real pert_lo = -1e34
pert_periods_u
Real pert_periods_u = 5.0
pert_periods_v
Real pert_periods_v = 5.0
prob_type
int prob_type
probhi
auto probhi = geomdata.ProbHi()
problo
auto problo = geomdata.ProbLo()
U_0
Real U_0 = 0.0
Referenced by if().
V_0
Real V_0 = 0.0
Referenced by if().
W_0
Real W_0 = 0.0
Referenced by if().