ERF: Source/Diffusion/ERF_SetupVertDiff.H File Reference
ERF_SetupVertDiff.H File Reference
Functions
Vector< Real > alpha_eff (NPRIMVAR_max, 0.0)
if (l_consA)
alpha_eff_d resize (alpha_eff.size())
eddy_diff_idz_d resize (eddy_diff_idz.size())
Variables
const auto & dom_lo = lbound(domain)
const auto & dom_hi = ubound(domain)
DiffChoice diffChoice = solverChoice.diffChoice
TurbChoice turbChoice = solverChoice.turbChoice[level]
bool l_consA = (diffChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
bool l_turb = turbChoice.use_kturb
else
Gpu::AsyncVector< Real > alpha_eff_d
Gpu::AsyncVector< int > eddy_diff_idz_d
Real * d_alpha_eff = alpha_eff_d.data()
int * d_eddy_diff_idz = eddy_diff_idz_d.data()
Function Documentation
alpha_eff()
Vector<Real> alpha_eff (NPRIMVAR_max , 0. 0)
Referenced by if().
if()
if (l_consA)
                  {
         for (int i = 0; i < NPRIMVAR_max; ++i) {
            switch (i) {
                case PrimTheta_comp:
                     alpha_eff[PrimTheta_comp] = diffChoice.alpha_T;
                     break;
                case PrimScalar_comp:
                     alpha_eff[PrimScalar_comp] = diffChoice.alpha_C;
                     break;
                case PrimQ1_comp:
                     alpha_eff[PrimQ1_comp] = diffChoice.alpha_C;
                     break;
                case PrimQ2_comp:
                     alpha_eff[PrimQ2_comp] = diffChoice.alpha_C;
                     break;
                case PrimQ3_comp:
                    alpha_eff[PrimQ3_comp] = diffChoice.alpha_C;
                    break;
                case PrimQ4_comp:
                    alpha_eff[PrimQ4_comp] = diffChoice.alpha_C;
                    break;
                case PrimQ5_comp:
                    alpha_eff[PrimQ5_comp] = diffChoice.alpha_C;
                    break;
                case PrimQ6_comp:
                    alpha_eff[PrimQ6_comp] = diffChoice.alpha_C;
                    break;
                default:
                     alpha_eff[i] = 0.0;
                     break;
           }
        }
     } else {
resize() [1/2]
alpha_eff_d resize (alpha_eff. size())
resize() [2/2]
eddy_diff_idz_d resize (eddy_diff_idz. size())
Variable Documentation
alpha_eff_d
Gpu::AsyncVector<Real> alpha_eff_d
d_alpha_eff
Real* d_alpha_eff = alpha_eff_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), getRhoAlpha(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), and ImplicitDiffForState_T().
d_eddy_diff_idz
int* d_eddy_diff_idz = eddy_diff_idz_d.data()
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), getRhoAlpha(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), and ImplicitDiffForState_T().
diffChoice
DiffChoice diffChoice = solverChoice.diffChoice
Referenced by if().
dom_hi
const auto& dom_hi = ubound(domain)
Referenced by MOSTAverage::compute_plane_averages(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), ERF::fill_from_bndryregs(), ImplicitDiffForMom_N(), ImplicitDiffForMom_S(), ImplicitDiffForMom_T(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), ImplicitDiffForState_T(), ERFPhysBCFunct_base::impose_lateral_basestate_bcs(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_base::impose_vertical_basestate_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), ERF::ImposeBCsOnPhi(), make_terrain_fitted_coords(), PlaneAverage::PlaneAverage(), ERF::poisson_wall_dist(), realbdy_bc_bxs_xy(), realbdy_compute_interior_ghost_rhs(), realbdy_interior_bxs_xy(), realbdy_set_rhs_in_spec_region(), ERF::solve_with_EB_mlmg(), ERF::solve_with_gmres(), and ERF::solve_with_mlmg().
dom_lo
const auto& dom_lo = lbound(domain)
Referenced by ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), ERF::fill_from_bndryregs(), ImplicitDiffForMom_N(), ImplicitDiffForMom_S(), ImplicitDiffForMom_T(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), ImplicitDiffForState_T(), ERFPhysBCFunct_base::impose_lateral_basestate_bcs(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_base::impose_vertical_basestate_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), ERF::ImposeBCsOnPhi(), make_terrain_fitted_coords(), PlaneAverage::PlaneAverage(), ERF::poisson_wall_dist(), realbdy_bc_bxs_xy(), realbdy_compute_interior_ghost_rhs(), realbdy_interior_bxs_xy(), realbdy_set_rhs_in_spec_region(), ERF::solve_with_EB_mlmg(), ERF::solve_with_gmres(), and ERF::solve_with_mlmg().
eddy_diff_idz_d
Gpu::AsyncVector<int> eddy_diff_idz_d
else
else
l_consA
bool l_consA = (diffChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), getRhoAlpha(), getRhoAlphaForFaces(), ImplicitDiffForMom_N(), ImplicitDiffForMom_S(), ImplicitDiffForMom_T(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), and ImplicitDiffForState_T().
l_turb
bool l_turb = turbChoice.use_kturb
Referenced by DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), getRhoAlpha(), getRhoAlphaForFaces(), ImplicitDiffForMom_N(), ImplicitDiffForMom_S(), ImplicitDiffForMom_T(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), and ImplicitDiffForState_T().
turbChoice
TurbChoice turbChoice = solverChoice.turbChoice[level]
Referenced by ComputeDiffusivityMRF(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeTurbulentViscosity(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityRANS(), and if().