ERF: Source/ERF_Constants.H File Reference
ERF_Constants.H File Reference
#include <AMReX_REAL.H>
Variables
constexpr amrex::Real zero = amrex::Real(0.0)
constexpr amrex::Real one = amrex::Real(1.0)
constexpr amrex::Real two = amrex::Real(2.0)
constexpr amrex::Real three = amrex::Real(3.0)
constexpr amrex::Real four = amrex::Real(4.0)
constexpr amrex::Real myhalf = amrex::Real(0.5)
constexpr amrex::Real fourth = amrex::Real(0.25)
constexpr amrex::Real third = amrex::Real(1.0/3.0)
constexpr amrex::Real eightthirds = amrex::Real(8.0/3.0)
constexpr amrex::Real PI = amrex::Real(3.14159265358979323846264338327950288)
constexpr amrex::Real PIoTwo = PI/two
constexpr amrex::Real four_thirds_pi = four/three*PI
constexpr amrex::Real R_d = amrex::Real(287.0)
constexpr amrex::Real R_v = amrex::Real(461.505)
constexpr amrex::Real Cp_d = amrex::Real(1004.5)
constexpr amrex::Real Cp_v = amrex::Real(1859.0)
constexpr amrex::Real Cp_l = amrex::Real(4200.0)
constexpr amrex::Real L_v = amrex::Real(2.5e6)
constexpr amrex::Real p_0 = amrex::Real(1.0e5)
constexpr amrex::Real Gamma = amrex::Real(1.4)
constexpr amrex::Real KAPPA = amrex::Real(0.41)
constexpr amrex::Real CONST_GRAV = amrex::Real(9.81)
constexpr amrex::Real ip_0 = one/p_0
constexpr amrex::Real iR_d = one/R_d
constexpr amrex::Real iGamma = one/Gamma
constexpr amrex::Real rhor = amrex::Real(1000.)
constexpr amrex::Real rhos = amrex::Real(100.)
constexpr amrex::Real rhog = amrex::Real(400.)
constexpr amrex::Real tbgmin = amrex::Real(253.16)
constexpr amrex::Real tbgmax = amrex::Real(273.16)
constexpr amrex::Real tprmin = amrex::Real(268.16)
constexpr amrex::Real tprmax = amrex::Real(283.16)
constexpr amrex::Real tgrmin = amrex::Real(223.16)
constexpr amrex::Real tgrmax = amrex::Real(283.16)
constexpr amrex::Real a_rain = amrex::Real(842.)
constexpr amrex::Real b_rain = amrex::Real(0.8)
constexpr amrex::Real a_snow = amrex::Real(4.84)
constexpr amrex::Real b_snow = fourth
constexpr amrex::Real a_grau = amrex::Real(94.5)
constexpr amrex::Real b_grau = amrex::Real(0.5)
constexpr amrex::Real qcw0 = amrex::Real(1.e-3)
constexpr amrex::Real qci0 = amrex::Real(1.e-4)
constexpr amrex::Real alphaelq = amrex::Real(1.e-3)
constexpr amrex::Real betaelq = amrex::Real(1.e-3)
constexpr amrex::Real erccoef = one
constexpr amrex::Real esccoef = one
constexpr amrex::Real esicoef = amrex::Real(0.1)
constexpr amrex::Real egccoef = one
constexpr amrex::Real egicoef = amrex::Real(0.1)
constexpr amrex::Real nzeror = amrex::Real(8.e6)
constexpr amrex::Real nzeros = amrex::Real(3.e6)
constexpr amrex::Real nzerog = amrex::Real(4.e6)
constexpr amrex::Real qp_threshold = amrex::Real(1.e-8)
constexpr amrex::Real boltz = amrex::Real(1.38065e-23)
constexpr amrex::Real avogadro = amrex::Real(6.02214e26)
constexpr amrex::Real mwdair = amrex::Real(28.966)
constexpr amrex::Real mwwv = amrex::Real(18.016)
constexpr amrex::Real lcond = amrex::Real(2.501e6)
constexpr amrex::Real lfus = amrex::Real(3.337e5)
constexpr amrex::Real lsub = lcond+lfus
constexpr amrex::Real rair = boltz*avogadro/mwdair
constexpr amrex::Real rh20 = rair/mwwv
constexpr amrex::Real rga = one/CONST_GRAV
constexpr amrex::Real diffelq = amrex::Real(2.21e-05)
constexpr amrex::Real therco = amrex::Real(2.40e-02)
constexpr amrex::Real muelq = amrex::Real(1.717e-05)
constexpr amrex::Real a_bg = one/(tbgmax-tbgmin)
constexpr amrex::Real a_pr = one/(tprmax-tprmin)
constexpr amrex::Real a_gr = one/(tgrmax-tgrmin)
constexpr amrex::Real crain = b_rain / amrex::Real(4.0)
constexpr amrex::Real csnow = b_snow / amrex::Real(4.0)
constexpr amrex::Real cgrau = b_grau / amrex::Real(4.0)
constexpr amrex::Real lat_vap = amrex::Real(2.5e6)
constexpr amrex::Real lat_ice = amrex::Real(3.337e5)
constexpr amrex::Real Rd_on_Rv = R_d/R_v
constexpr amrex::Real tmelt = amrex::Real(273.15)
constexpr amrex::Real h2otrip = amrex::Real(273.15)
constexpr amrex::Real tboil = amrex::Real(373.16)
constexpr amrex::Real ttrice = amrex::Real(20.00)
constexpr amrex::Real epsilo = Rd_on_Rv
constexpr amrex::Real omeps = one - epsilo
constexpr amrex::Real rhoh2o = amrex::Real(1.000e3)
static constexpr int ORB_UNDEF_INT = 2000000000
Variable Documentation
a_bg
constexpr amrex::Real a_bg = one/(tbgmax-tbgmin) constexpr
Referenced by if(), and SAM::Precip().
a_gr
constexpr amrex::Real a_gr = one/(tgrmax-tgrmin) constexpr
Referenced by SAM::Precip(), SAM::PrecipFall(), and term_vel_qp().
a_grau
constexpr amrex::Real a_grau = amrex::Real(94.5) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
a_pr
constexpr amrex::Real a_pr = one/(tprmax-tprmin) constexpr
Referenced by SAM::Precip(), SAM::PrecipFall(), and term_vel_qp().
a_rain
constexpr amrex::Real a_rain = amrex::Real(842.) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
a_snow
constexpr amrex::Real a_snow = amrex::Real(4.84) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
alphaelq
constexpr amrex::Real alphaelq = amrex::Real(1.e-3) constexpr
Referenced by Kessler::AdvanceKessler(), and SAM::Precip().
avogadro
constexpr amrex::Real avogadro = amrex::Real(6.02214e26) constexpr
b_grau
constexpr amrex::Real b_grau = amrex::Real(0.5) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), SAM::Precip(), and SAM::PrecipFall().
b_rain
constexpr amrex::Real b_rain = amrex::Real(0.8) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), SAM::Precip(), and SAM::PrecipFall().
b_snow
constexpr amrex::Real b_snow = fourth constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), SAM::Precip(), and SAM::PrecipFall().
betaelq
constexpr amrex::Real betaelq = amrex::Real(1.e-3) constexpr
Referenced by SAM::Precip().
boltz
constexpr amrex::Real boltz = amrex::Real(1.38065e-23) constexpr
cgrau
constexpr amrex::Real cgrau = b_grau / amrex::Real(4.0) constexpr
Referenced by SAM::PrecipFall(), and term_vel_qp().
CONST_GRAV
constexpr amrex::Real CONST_GRAV = amrex::Real(9.81) constexpr
Referenced by WSM6::Advance(), calc_p_isothermal(), InputSoundingData::calc_rho_p(), InputSoundingData::calc_rho_p_isentropic(), TurbulentPerturbation::calc_tpi_amp(), calc_wstar(), TerminalVelocity< RT >::CloudRainShima(), COARE3_roughness(), rrtmgp::compute_aerocom_cloudtop(), HSEutils::compute_F(), HSEutils::compute_theta(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeQKESourceTerms(), Donelan_roughness(), derived::erf_dermucape(), SurfaceLayer::fill_qsurf_with_qsat(), HSEutils::init_isentropic_hse(), HSEutils::init_isentropic_hse_terrain(), init_my_custom_terrain(), SolverChoice::init_params(), make_mom_sources(), make_sources(), SHOCInterface::mf_to_kokkos_buffers(), ERF::sum_energy_quantities(), SurfaceLayer::update_fluxes(), and ERF::Write3DPlotFile().
Cp_d
constexpr amrex::Real Cp_d = amrex::Real(1004.5) constexpr
Referenced by WSM6::Advance(), NOAHMP::Advance_With_State(), Kessler::AdvanceKessler(), InputSoundingData::calc_rho_p(), InputSoundingData::calc_rho_p_isentropic(), HSEutils::compute_F_for_temp(), rrtmgp::compute_heating_rate(), HSEutils::compute_rho(), HSEutils::compute_theta(), ComputeLiquidWaterPotentialTemperature(), ComputeMoistStratification(), WaterVaporSat::deriv_outputs(), derived::erf_dermucape(), WaterVaporSat::findsp(), if(), Radiation::kokkos_buffers_to_mf(), lagrange_setup(), make_sources(), ParallelFor(), ERF::sum_energy_quantities(), WaterVaporSat::tq_enthalpy(), and ERF::Write3DPlotFile().
Cp_l
constexpr amrex::Real Cp_l = amrex::Real(4200.0) constexpr
Referenced by WSM6::Advance(), HSEutils::compute_F_for_temp(), and ERF::Write3DPlotFile().
Cp_v
constexpr amrex::Real Cp_v = amrex::Real(1859.0) constexpr
Referenced by WSM6::Advance(), and ERF::sum_energy_quantities().
crain
constexpr amrex::Real crain = b_rain / amrex::Real(4.0) constexpr
Referenced by SAM::PrecipFall(), and term_vel_qp().
csnow
constexpr amrex::Real csnow = b_snow / amrex::Real(4.0) constexpr
Referenced by SAM::PrecipFall(), and term_vel_qp().
diffelq
constexpr amrex::Real diffelq = amrex::Real(2.21e-05) constexpr
Referenced by MaterialPropertiesCore::coeffMolecularDiffusion(), Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
egccoef
constexpr amrex::Real egccoef = one constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
egicoef
constexpr amrex::Real egicoef = amrex::Real(0.1) constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
eightthirds
constexpr amrex::Real eightthirds = amrex::Real(8.0/3.0) constexpr
Referenced by ComputeStrain_N().
epsilo
constexpr amrex::Real epsilo = Rd_on_Rv constexpr
Referenced by SatMethods::wv_sat_svp_to_qsat().
erccoef
constexpr amrex::Real erccoef = one constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
esccoef
constexpr amrex::Real esccoef = one constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
esicoef
constexpr amrex::Real esicoef = amrex::Real(0.1) constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
four
constexpr amrex::Real four = amrex::Real(4.0) constexpr
Referenced by ComputeN2_EB(), and ComputeVerticalShear2_EB().
four_thirds_pi
constexpr amrex::Real four_thirds_pi = four/three*PI constexpr
Referenced by SDInitProperties::getDistribution(), SD_sample_mass_gpu(), and SDInitProperties::volume().
fourth
constexpr amrex::Real fourth = amrex::Real(0.25) constexpr
Referenced by Morrison::Advance(), AdvectionSrcForMom_ConstantDz(), AdvectionSrcForMom_EB(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMom_TF(), AdvectionSrcForOpenBC_Tangent_Xmom(), AdvectionSrcForOpenBC_Tangent_Ymom(), AdvectionSrcForOpenBC_Tangent_Zmom(), AdvectionSrcForZMom(), similarity_funs::calc_psi_m2(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), Compute_h_eta_AtCellCenter(), Compute_h_eta_AtEdgeCenterI(), Compute_h_eta_AtEdgeCenterK(), Compute_h_xi_AtCellCenter(), Compute_h_xi_AtEdgeCenterJ(), Compute_h_xi_AtEdgeCenterK(), Compute_h_zeta_AtCellCenter(), Compute_h_zeta_AtEdgeCenterI(), Compute_h_zeta_AtEdgeCenterJ(), compute_max_reflectivity_dbz(), HSEutils::compute_relative_humidity(), bulk_coeff_flux::compute_u_flux(), custom_flux::compute_u_flux(), rico_flux::compute_u_flux(), donelan_flux::compute_u_flux(), moeng_flux::compute_u_flux(), bulk_coeff_flux::compute_v_flux(), custom_flux::compute_v_flux(), rico_flux::compute_v_flux(), donelan_flux::compute_v_flux(), moeng_flux::compute_v_flux(), Compute_Z_AtWFace(), Compute_Zrel_AtCellCenter(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityYSU(), ComputeSmnSmn(), ComputeSmnSmn2D(), ComputeStrain_T(), ComputeStressConsVisc_EB(), ComputeStressConsVisc_N(), ComputeStressConsVisc_S(), ComputeStressConsVisc_T(), ComputeStressVarVisc_EB(), ComputeStressVarVisc_N(), ComputeStressVarVisc_S(), ComputeStressVarVisc_T(), ComputeVerticalDerivativesPBL(), ForestDrag::define_drag_field(), ERF::derive_diag_profiles_stag(), DiffusionSrcForState_T(), erf_substep_MT(), erf_substep_T(), getRhoAlphaForFaces(), init_bx_velocities_from_input_sounding(), SurfaceLayer::init_tke_from_ustar(), interpolate_column_metgrid(), interpolate_column_metgrid_linear(), make_mom_sources(), HSEutils::Newton_Raphson_hse(), NumericalDiffusion_Xmom(), NumericalDiffusion_Ymom(), orbital_decl(), ParallelFor(), ParallelForRNG(), ERF::poisson_wall_dist(), MOSTAverage::set_k_indices_T(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_z_positions_T(), terrpoisson_adotx(), terrpoisson_flux_x(), terrpoisson_flux_y(), terrpoisson_flux_z(), terrpoisson_flux_zlo_dir(), MOSTAverage::trilinear_interp_T(), and ERF::Write3DPlotFile().
Gamma
constexpr amrex::Real Gamma = amrex::Real(1.4) constexpr
Referenced by InputSoundingData::calc_rho_p_isentropic(), derived::erf_dersoundspeed(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), ERF::estTimeStep(), getdPdRgivenConstantTheta(), getExnergivenRTh(), getPgivenRTh(), getRhoThetagivenP(), getTgivenRandRTh(), make_fast_coeffs(), and ParallelFor().
h2otrip
constexpr amrex::Real h2otrip = amrex::Real(273.15) constexpr
Referenced by SatMethods::GoffGratch_svp_ice().
iGamma
constexpr amrex::Real iGamma = one/Gamma constexpr
Referenced by getRhogivenThetaPress(), and getRhoThetagivenP().
ip_0
constexpr amrex::Real ip_0 = one/p_0 constexpr
Referenced by getdPdRgivenConstantTheta(), getExnergivenP(), getExnergivenRTh(), getPgivenRTh(), and getTgivenRandRTh().
iR_d
constexpr amrex::Real iR_d = one/R_d constexpr
Referenced by getRhoThetagivenP().
KAPPA
constexpr amrex::Real KAPPA = amrex::Real(0.41) constexpr
Referenced by ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeTurbulentViscosityRANS(), make_mom_sources(), make_sources(), and SurfaceLayer::update_fluxes().
L_v
constexpr amrex::Real L_v = amrex::Real(2.5e6) constexpr
Referenced by NOAHMP::Advance_With_State(), Kessler::AdvanceKessler(), HSEutils::compute_F_for_temp(), ComputeLiquidWaterPotentialTemperature(), ComputeMoistStratification(), MaterialProperties::setProperties_H2O(), ERF::sum_energy_quantities(), and ERF::Write3DPlotFile().
lat_ice
constexpr amrex::Real lat_ice = amrex::Real(3.337e5) constexpr
Referenced by WSM6::Advance(), WaterVaporSat::calc_hltalt(), ComputeMoistStratification(), and WaterVaporSat::qsat_ice().
lat_vap
constexpr amrex::Real lat_vap = amrex::Real(2.5e6) constexpr
Referenced by WSM6::Advance(), WaterVaporSat::no_ip_hltalt(), and WaterVaporSat::qsat_ice().
lcond
constexpr amrex::Real lcond = amrex::Real(2.501e6) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), Kessler::Define(), SAM::Define(), and SatAdj::Define().
lfus
constexpr amrex::Real lfus = amrex::Real(3.337e5) constexpr
Referenced by SAM::Define().
lsub
constexpr amrex::Real lsub = lcond+lfus constexpr
Referenced by WSM6::Advance(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::Define().
muelq
constexpr amrex::Real muelq = amrex::Real(1.717e-05) constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
mwdair
constexpr amrex::Real mwdair = amrex::Real(28.966) constexpr
Referenced by Radiation::run_impl().
mwwv
constexpr amrex::Real mwwv = amrex::Real(18.016) constexpr
myhalf
constexpr amrex::Real myhalf = amrex::Real(0.5) constexpr
Referenced by Morrison::Advance(), MRISplitIntegrator< T >::advance(), NOAHMP::Advance_With_State(), Kessler::AdvanceKessler(), AdvectionSrcForMom_TF(), AdvectionSrcForOpenBC_Normal(), AdvectionSrcForOpenBC_Tangent(), AdvectionSrcForOpenBC_Tangent_Cons(), AdvectionSrcForOpenBC_Tangent_Xmom(), AdvectionSrcForOpenBC_Tangent_Ymom(), AdvectionSrcForOpenBC_Tangent_Zmom(), AdvectionSrcForScalars(), AdvectionSrcForXMom(), AdvectionSrcForXMom_N(), AdvectionSrcForYMom(), AdvectionSrcForYMom_N(), AdvectionSrcForZMom(), AdvectionSrcForZMom_N(), ApplyBndryForcing_Forecast(), ApplySpongeZoneBCsForCC(), ApplySpongeZoneBCsForMom(), ApplySpongeZoneBCsForMom_ReadFromFile(), buoyancy_dry_anelastic(), buoyancy_dry_anelastic_eb(), buoyancy_dry_anelastic_T(), buoyancy_dry_Thpert(), buoyancy_dry_Tpert(), buoyancy_moist_anelastic(), buoyancy_moist_Thpert(), buoyancy_moist_Tpert(), buoyancy_rhopert(), buoyancy_rhopert_eb(), similarity_funs::calc_psi_h(), similarity_funs::calc_psi_h2(), similarity_funs::calc_psi_m(), similarity_funs::calc_psi_m2(), InputSoundingData::calc_rho_p(), InputSoundingData::calc_rho_p_isentropic(), TurbulentPerturbation::calc_tpi_meanMag_perBox(), eb_cut_cell_::centVol(), MaterialPropertiesCore::coeffMolecularDiffusion(), rrtmgp::compute_band_by_band_surface_albedos(), rrtmgp::compute_broadband_surface_fluxes(), HSEutils::compute_F(), GeneralAD::compute_freestream_velocity(), SimpleAD::compute_freestream_velocity(), compute_gradp(), compute_gradp_interpz(), Compute_h_eta_AtIface(), Compute_h_eta_AtKface(), Compute_h_xi_AtJface(), Compute_h_xi_AtKface(), Compute_h_zeta_AtIface(), Compute_h_zeta_AtJface(), MYNNPBLH::compute_pblh(), MOSTAverage::compute_plane_averages(), Fitch::compute_power_output(), EWP::compute_power_output(), bulk_coeff_flux::compute_q_flux(), rico_flux::compute_q_flux(), moeng_flux::compute_q_flux(), MOSTAverage::compute_region_averages(), compute_source_terms_Fn_Ft(), SurfaceLayer::compute_SurfaceLayer_bcs(), bulk_coeff_flux::compute_t_flux(), rico_flux::compute_t_flux(), moeng_flux::compute_t_flux(), rotate_flux::compute_u_flux(), bulk_coeff_flux::compute_u_flux(), custom_flux::compute_u_flux(), rico_flux::compute_u_flux(), donelan_flux::compute_u_flux(), moeng_flux::compute_u_flux(), bulk_coeff_flux::compute_v_flux(), custom_flux::compute_v_flux(), rico_flux::compute_v_flux(), donelan_flux::compute_v_flux(), moeng_flux::compute_v_flux(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeGlobalMinLocation(), ComputeMoistStratification(), ComputeN2(), ComputeN2_EB(), ComputeSmnSmn2D(), ComputeStrain_EB(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ComputeStratificationForSmagorinsky(), ComputeStressConsVisc_S(), ComputeStressConsVisc_T(), ComputeStressVarVisc_S(), ComputeStressVarVisc_T(), MM5::ComputeTsurf(), SLM::ComputeTsurf(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityLES_EB(), ComputeTurbulentViscosityRANS(), ComputeVerticalDerivativesPBL(), ComputeVerticalShear2(), ComputeVerticalShear2_EB(), polygon_::define(), eb_aux_::define(), ForestDrag::define_drag_field(), ERF::derive_diag_profiles(), ERF::derive_diag_profiles_stag(), ERF::derive_stress_profiles(), ERF::derive_stress_profiles_stag(), DiffusionSrcForMom(), DiffusionSrcForMom_EB(), DiffusionSrcForState_EB(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForMomWrapper(), EBAdvectionSrcForScalars(), erf_calc_slopes_eb_Dirichlet_staggered(), erf_calc_slopes_eb_staggered(), erf_calc_slopes_eb_staggered_upwind(), ERF::erf_enforce_hse(), ERF::ERF_shared(), erf_slow_rhs_post(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), ERF::ErrorEst(), UPWIND3SL::Evaluate(), UPWINDALL::Evaluate(), expand_and_interpolate_1d(), SurfaceLayer::fill_qsurf_with_qsat(), WindFarm::fill_SMark_multifab(), ERF::FillForecastStateMultiFabs(), ERF::FillSurfaceStateMultiFabs(), NullWindFarm::find_if_marked(), ERF::FindInitialEye(), WaterVaporSat::findsp(), fine_compute_interior_ghost_rhs(), for(), polygon_::get_centroid(), getRhoAlpha(), HurricaneEyeTrackerNotInitial(), HurricaneMaxVelTracker(), HurricaneMinPressureTracker(), SAM::IceFall(), if(), ImplicitDiffForMomLU_S(), ImplicitDiffForMomLU_T(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), init_bx_scalars_from_input_sounding(), init_bx_scalars_from_input_sounding_hse(), init_bx_velocities_from_input_sounding(), MYNNLevel2::init_coeffs(), init_default_zphys(), ERF::init_Dirichlet_bc_data(), ERF::init_geo_wind_profile(), ERF::init_immersed_forcing(), HSEutils::init_isentropic_hse(), HSEutils::init_isentropic_hse_no_terrain(), HSEutils::init_isentropic_hse_terrain(), init_my_custom_terrain(), init_which_terrain_grid(), ERF::initRayleigh_at_level(), interpolate_column_metgrid(), interpolate_column_metgrid_linear(), interpolatedVal(), InterpolateInX(), InterpolateInY(), UPWINDALL::InterpolateInZ(), InterpolateInZ(), surface_temp_donelan::iterate_flux(), surface_temp_wave_coupled::iterate_flux(), lagrange_setup(), PlaneAverage::line_average_interpolated(), make_fast_coeffs(), make_mom_sources(), make_sources(), SDInitProperties::makeDistributionParams(), HSEutils::Newton_Raphson_hse(), NumericalDiffusion_Scal(), OmegaFromW(), orbital_params(), ParallelFor(), ParallelForRNG(), PlaneAverage::PlaneAverage(), ERF::poisson_wall_dist(), SAM::PrecipFall(), ReadBndryPlanes::read_file(), InputSpongeData::read_from_file(), InputSoundingData::read_from_file(), WindFarm::read_windfarm_spec_table(), ERF::ReadCheckpointFile(), realbdy_compute_interior_ghost_rhs(), realbdy_compute_relaxation(), rrtmgp::rrtmgp_lw(), MOSTAverage::set_k_indices_EB(), MOSTAverage::set_k_indices_N(), MOSTAverage::set_k_indices_T(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_z_positions_T(), ERF::setSpongeRefFromSounding(), EWP::source_terms_cellcentered(), Fitch::source_terms_cellcentered(), GeneralAD::source_terms_cellcentered(), SimpleAD::source_terms_cellcentered(), ERF::sum_energy_quantities(), tag_on_distance_from_eye(), terrpoisson_adotx(), terrpoisson_flux_x(), terrpoisson_flux_y(), terrpoisson_flux_z(), terrpoisson_flux_zlo_dir(), Time_Avg_Vel_atCC(), MOSTAverage::trilinear_interp_T(), VelocityToMomentum(), WFromOmega(), wrf_gamma(), ERF::Write3DPlotFile(), ERF::write_1D_profiles(), ERF::write_1D_profiles_stag(), WindFarm::write_actuator_disks_vtk(), LineSampler::write_line_plotfile(), and PlaneSampler::write_sample_data().
nzerog
constexpr amrex::Real nzerog = amrex::Real(4.e6) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
nzeror
constexpr amrex::Real nzeror = amrex::Real(8.e6) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
nzeros
constexpr amrex::Real nzeros = amrex::Real(3.e6) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
omeps
constexpr amrex::Real omeps = one - epsilo constexpr
Referenced by WaterVaporSat::deriv_outputs(), and SatMethods::wv_sat_svp_to_qsat().
one
constexpr amrex::Real one = amrex::Real(1.0) constexpr
Referenced by add_thin_body_sources(), EWP::advance(), Fitch::advance(), GeneralAD::advance(), Morrison::Advance(), WSM6::Advance(), ERF::Advance(), MRISplitIntegrator< T >::advance(), AdvectionSrcForMom(), AdvectionSrcForMom_ConstantDz(), AdvectionSrcForMom_EB(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMom_TF(), AdvectionSrcForMomWrapper_N(), AdvectionSrcForScalars(), AdvectionSrcForXMom(), AdvectionSrcForYMom(), air_viscosity(), ApplySurfaceTreatment_BulkCoeff_CC(), ApplySurfaceTreatment_BulkCoeff_Mom(), eb_cut_cell_::areaHi(), eb_cut_cell_::areaLo(), ERF::AverageDownTo(), buoyancy_moist_anelastic(), buoyancy_rhopert(), buoyancy_rhopert_eb(), similarity_funs::calc_psi_h(), similarity_funs::calc_psi_h2(), similarity_funs::calc_psi_m(), similarity_funs::calc_psi_m2(), InputSoundingData::calc_rho_p(), calc_saturation_vapor_pressure(), MYNNLevel2::calc_SH(), MYNNLevel25::calc_stability_funcs(), TurbulentPerturbation::calc_tpi_amp(), TurbulentPerturbation::calc_tpi_meanMag_perBox(), TurbulentPerturbation::calc_tpi_update(), eb_cut_cell_::centHi(), eb_cut_cell_::centLo(), SHOCInterface::check_flux_state_consistency(), SAM::Cloud(), rrtmgp::compute_aerocom_cloudtop(), PlaneAverage::compute_averages(), rrtmgp::compute_cloud_area(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), ERF::compute_divergence(), GeneralAD::compute_freestream_velocity(), SimpleAD::compute_freestream_velocity(), compute_max_reflectivity_dbz(), MYNNPBLH::compute_pblh(), MOSTAverage::compute_plane_averages(), Fitch::compute_power_output(), EWP::compute_power_output(), custom_flux::compute_q_flux(), MOSTAverage::compute_region_averages(), HSEutils::compute_relative_humidity(), HSEutils::compute_rho(), compute_source_terms_Fn_Ft(), custom_flux::compute_t_flux(), HSEutils::compute_theta(), custom_flux::compute_u_flux(), custom_flux::compute_v_flux(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ERF::ComputeDt(), ComputeMoistStratification(), ComputeN2(), ComputeN2_EB(), ComputeSmnSmn_EB(), ComputeStrain_S(), ComputeStrain_T(), ComputeStressConsVisc_EB(), ComputeStressConsVisc_N(), ComputeStressConsVisc_S(), ComputeStressConsVisc_T(), ComputeStressVarVisc_EB(), ComputeStressVarVisc_N(), ComputeStressVarVisc_S(), ComputeStressVarVisc_T(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityLES_EB(), ComputeTurbulentViscosityRANS(), ComputeVerticalDerivativesPBL(), ComputeVirtualPotentialTemperature(), polygon_::define(), eb_aux_::define(), ForestDrag::define_drag_field(), DiffusionSrcForMom(), DiffusionSrcForState_EB(), DiffusionSrcForState_N(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), erf_init_dens_hse_moist(), erf_init_rayleigh(), erf_make_tau_terms(), ERF::ERF_shared(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), ERF::ErrorEst(), ERF::estTimeStep(), WindFarm::fill_SMark_multifab_mesoscale_models(), SurfaceLayer::fill_tsurf_with_sst_and_tsk(), ERF::FillBdyCCVels(), fine_compute_interior_ghost_rhs(), rrtmgp::get_subcolumn_mask(), SDInitProperties::getDistribution(), SAM::IceFall(), if(), ImplicitDiffForMomLU_N(), ImplicitDiffForMomLU_S(), ImplicitDiffForMomLU_T(), ImplicitDiffForStateLU_S(), ImplicitDiffForStateLU_T(), ERFPhysBCFunct_base::impose_lateral_basestate_bcs(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERF::init_bcs(), init_bx_scalars_from_input_sounding(), init_bx_scalars_from_input_sounding_hse(), MYNNLevel2::init_coeffs(), ERF::init_immersed_forcing(), init_my_custom_terrain(), TurbChoice::init_params(), SolverChoice::init_params(), AdvChoice::init_params(), ERF::init_phys_bcs(), TurbulentPerturbation::init_tpi(), init_which_terrain_grid(), ERF::InitData_post(), ERF::initRayleigh_at_level(), surface_temp_charnock::iterate_flux(), surface_temp::iterate_flux(), Radiation::kokkos_buffers_to_mf(), SHOCInterface::kokkos_buffers_to_mf(), lagrange_interp(), lagrange_setup(), PlaneAverage::line_average_interpolated(), make_areas(), make_fast_coeffs(), make_J(), make_mom_sources(), MOSTAverage::make_MOSTAverage_at_level(), make_sources(), SDInitProperties::makeDistributionParams(), ERF::MakeNewLevelFromCoarse(), MaterialPropertiesCore::molarHeatCapacity(), TurbulentPerturbation::netZeroBuoyantAdd(), HSEutils::Newton_Raphson_hse(), SatAdj::NewtonIterSat(), Morrison::NewtonIterSat(), SAM::NewtonIterSat(), NumericalDiffusion_Scal(), orbital_avg_cos_zenith(), orbital_decl(), orbital_params(), ParallelFor(), ParallelForRNG(), ERF::ParameterSanityChecks(), ERF::poisson_wall_dist(), ERF::post_timestep(), SAM::Precip(), SAM::PrecipFall(), ERF::project_momenta(), ERF::project_velocity_tb(), TurbulentPerturbation::pseudoRandomPert(), WindFarm::read_windfarm_spec_table(), ReadBndryPlanes::ReadBndryPlanes(), SDInjection::readInputs(), ERF::ReadParameters(), realbdy_compute_interior_ghost_rhs(), rotate_scalar_flux(), rotate_stress_tensor(), Radiation::run_impl(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_rotated_fields(), SHOCInterface::SHOCInterface(), solve_with_EB_mlmg(), SolveTridiag(), GeneralAD::source_terms_cellcentered(), SimpleAD::source_terms_cellcentered(), ERF::sum_energy_quantities(), ERF::SurfaceDataInterpolation(), SurfaceLayer::SurfaceLayer(), MOSTAverage::trilinear_interp_T(), SurfaceLayer::update_fluxes(), SDInjection::updateDt(), eb_cut_cell_::volume(), ERF::WeatherDataInterpolation(), and wrf_gamma().
ORB_UNDEF_INT
constexpr int ORB_UNDEF_INT = 2000000000 static constexpr
Referenced by orbital_params(), and Radiation::run_impl().
p_0
constexpr amrex::Real p_0 = amrex::Real(1.0e5) constexpr
Referenced by calc_p_isothermal(), InputSoundingData::calc_rho_p_isentropic(), HSEutils::compute_F_for_temp(), ERF::erf_enforce_hse(), erf_init_dens_hse(), getdPdRgivenConstantTheta(), getPgivenRTh(), getRhogivenThetaPress(), getRhoThetagivenP(), getTgivenPandTh(), getTgivenRandRTh(), getThgivenRandT(), getThgivenTandP(), HSEutils::init_isentropic_hse(), HSEutils::init_isentropic_hse_no_terrain(), HSEutils::init_isentropic_hse_terrain(), ParallelFor(), and ERF::Write3DPlotFile().
PI
constexpr amrex::Real PI = amrex::Real(3.14159265358979323846264338327950288) constexpr
Referenced by SolverChoice::build_coriolis_forcings_const_lat(), similarity_funs::calc_psi_h2(), similarity_funs::calc_psi_m2(), TurbulentPerturbation::calc_tpi_update(), MaterialPropertiesCore::coeffMolecularDiffusion(), MaterialPropertiesCore::coeffVPSolute(), compute_A(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), compute_source_terms_Fn_Ft(), polygon_::define(), SDInitProperties::getDistribution(), if(), init_my_custom_terrain(), init_which_terrain_grid(), make_mom_sources(), orbital_avg_cos_zenith(), orbital_cos_zenith(), orbital_decl(), orbital_params(), ParallelFor(), SAM::PrecipFall(), Radiation::run_impl(), SD_erfinv(), SD_erfinv_gpu(), SD_sample_mass_gpu(), EWP::source_terms_cellcentered(), GeneralAD::source_terms_cellcentered(), and ERF::Write3DPlotFile().
PIoTwo
constexpr amrex::Real PIoTwo = PI/two constexpr
Referenced by similarity_funs::calc_psi_m(), similarity_funs::calc_psi_m2(), ERF::initRayleigh_at_level(), and orbital_avg_cos_zenith().
qci0
constexpr amrex::Real qci0 = amrex::Real(1.e-4) constexpr
Referenced by SAM::Precip().
qcw0
constexpr amrex::Real qcw0 = amrex::Real(1.e-3) constexpr
Referenced by Kessler::AdvanceKessler(), and SAM::Precip().
qp_threshold
constexpr amrex::Real qp_threshold = amrex::Real(1.e-8) constexpr
Referenced by SAM::PrecipFall(), and term_vel_qp().
R_d
constexpr amrex::Real R_d = amrex::Real(287.0) constexpr
Referenced by WSM6::Advance(), calc_p_isothermal(), InputSoundingData::calc_rho_p(), InputSoundingData::calc_rho_p_isentropic(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), HSEutils::compute_F_for_temp(), HSEutils::compute_rho(), ComputeMoistStratification(), derived::erf_dermucape(), erf_init_dens_hse(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), getdPdRgivenConstantTheta(), getExnergivenRTh(), getPgivenRTh(), getRhogivenTandPress(), getRhogivenThetaPress(), getRhoThetagivenP(), getTgivenRandRTh(), getThgivenRandT(), if(), SolverChoice::init_params(), Radiation::kokkos_buffers_to_mf(), lagrange_setup(), make_fast_coeffs(), make_sources(), ParallelFor(), ERF::sum_energy_quantities(), and ERF::Write3DPlotFile().
R_v
constexpr amrex::Real R_v = amrex::Real(461.505) constexpr
Referenced by WSM6::Advance(), InputSoundingData::calc_rho_p_isentropic(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), ComputeMoistStratification(), WaterVaporSat::deriv_outputs(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), getdPdRgivenConstantTheta(), getExnergivenRTh(), getPgivenRTh(), getRhogivenTandPress(), getRhogivenThetaPress(), getRhoThetagivenP(), getTgivenRandRTh(), getThgivenRandT(), if(), make_fast_coeffs(), ParallelFor(), MaterialProperties::setProperties_H2O(), and ERF::sum_energy_quantities().
rair
constexpr amrex::Real rair = boltz*avogadro/mwdair constexpr
Rd_on_Rv
constexpr amrex::Real Rd_on_Rv = R_d/R_v constexpr
Referenced by HSEutils::compute_relative_humidity(), erf_dtqsati(), erf_dtqsatw(), erf_qsati(), erf_qsatw(), and HSEutils::vapor_mixing_ratio().
rga
constexpr amrex::Real rga = one/CONST_GRAV constexpr
rh20
constexpr amrex::Real rh20 = rair/mwwv constexpr
rhog
constexpr amrex::Real rhog = amrex::Real(400.) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
rhoh2o
constexpr amrex::Real rhoh2o = amrex::Real(1.000e3) constexpr
Referenced by WSM6::Advance().
rhor
constexpr amrex::Real rhor = amrex::Real(1000.) constexpr
Referenced by Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), SAM::PrecipFall(), and MaterialProperties::setProperties_H2O().
rhos
constexpr amrex::Real rhos = amrex::Real(100.) constexpr
Referenced by WSM6::Advance(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), and SAM::PrecipFall().
tbgmax
constexpr amrex::Real tbgmax = amrex::Real(273.16) constexpr
Referenced by SAM::Cloud(), Morrison::NewtonIterSat(), and SAM::NewtonIterSat().
tbgmin
constexpr amrex::Real tbgmin = amrex::Real(253.16) constexpr
Referenced by SAM::Cloud(), if(), Morrison::NewtonIterSat(), SAM::NewtonIterSat(), and SAM::Precip().
tboil
constexpr amrex::Real tboil = amrex::Real(373.16) constexpr
Referenced by SatMethods::GoffGratch_svp_water(), and SatMethods::OldGoffGratch_svp_water().
tgrmax
constexpr amrex::Real tgrmax = amrex::Real(283.16) constexpr
tgrmin
constexpr amrex::Real tgrmin = amrex::Real(223.16) constexpr
Referenced by SAM::Precip(), SAM::PrecipFall(), and term_vel_qp().
therco
constexpr amrex::Real therco = amrex::Real(2.40e-02) constexpr
Referenced by Morrison::Compute_Coefficients(), and SAM::Compute_Coefficients().
third
constexpr amrex::Real third = amrex::Real(1.0/3.0) constexpr
Referenced by ComputeStrain_EB(), and ComputeStrain_N().
three
constexpr amrex::Real three = amrex::Real(3.0) constexpr
Referenced by Morrison::Advance(), MRISplitIntegrator< T >::advance(), buoyancy_dry_anelastic_eb(), buoyancy_rhopert_eb(), similarity_funs::calc_psi_h2(), similarity_funs::calc_psi_m2(), MYNNLevel2::calc_SH(), MYNNLevel25::calc_stability_funcs(), TerminalVelocity< RT >::CloudRainShima(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), compute_gradp(), compute_source_terms_Fn_Ft(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeN2_EB(), ComputeStrain_EB(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ComputeStressConsVisc_EB(), ComputeStressConsVisc_N(), ComputeStressConsVisc_S(), ComputeStressConsVisc_T(), ComputeStressVarVisc_EB(), ComputeStressVarVisc_N(), ComputeStressVarVisc_S(), ComputeStressVarVisc_T(), ComputeTurbulentViscosityLES_EB(), ComputeVerticalDerivativesPBL(), ComputeVerticalShear2_EB(), DiffusionSrcForMom_EB(), DiffusionSrcForState_EB(), DiffusionSrcForState_N(), UPWIND3::Evaluate(), UPWINDALL::Evaluate(), FillZeroAreaFaceFluxes(), polygon_::get_centroid(), ImplicitDiffForMomLU_N(), ImplicitDiffForMomLU_S(), ImplicitDiffForMomLU_T(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), MYNNLevel2::init_coeffs(), ERF::InitData_post(), make_mom_sources(), make_sources(), orbital_decl(), orbital_params(), SAM::Precip(), EWP::source_terms_cellcentered(), GeneralAD::source_terms_cellcentered(), SurfaceLayer::update_fluxes(), eb_cut_cell_::volume(), and z0_est().
tmelt
constexpr amrex::Real tmelt = amrex::Real(273.15) constexpr
Referenced by SatMethods::Bolton_svp_water(), WaterVaporSat::calc_hltalt(), WaterVaporSat::no_ip_hltalt(), SatMethods::OldGoffGratch_svp_ice(), and SatMethods::wv_sat_svp_trans().
tprmax
constexpr amrex::Real tprmax = amrex::Real(283.16) constexpr
tprmin
constexpr amrex::Real tprmin = amrex::Real(268.16) constexpr
Referenced by SAM::Precip(), SAM::PrecipFall(), and term_vel_qp().
ttrice
constexpr amrex::Real ttrice = amrex::Real(20.00) constexpr
Referenced by WaterVaporSat::calc_hltalt(), and SatMethods::wv_sat_svp_trans().
two
constexpr amrex::Real two = amrex::Real(2.0) constexpr
Referenced by MRISplitIntegrator< T >::advance(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMomWrapper_N(), ApplySurfaceTreatment_BulkCoeff_Mom(), SolverChoice::build_coriolis_forcings_const_lat(), similarity_funs::calc_psi_h(), similarity_funs::calc_psi_h2(), similarity_funs::calc_psi_m(), similarity_funs::calc_psi_m2(), compute_A(), Morrison::Compute_Coefficients(), SAM::Compute_Coefficients(), HSEutils::compute_F(), compute_gradp(), compute_max_reflectivity_dbz(), MYNNPBLH::compute_pblh(), compute_source_terms_Fn_Ft(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeQKESourceTerms(), ComputeSmnSmn(), ComputeSmnSmn2D(), ComputeSmnSmn_EB(), ComputeStrain_EB(), ComputeStrain_S(), ComputeStrain_T(), ComputeStressVarVisc_EB(), ComputeStressVarVisc_N(), ComputeStressVarVisc_S(), ComputeStressVarVisc_T(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityLES_EB(), polygon_::define(), DiffusionSrcForMom(), DiffusionSrcForMom_EB(), DiffusionSrcForState_EB(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), derived::erf_derenstrophysq(), derived::erf_dervortx(), derived::erf_dervorty(), derived::erf_dervortz(), erf_init_rayleigh(), erf_make_tau_terms(), erf_vortex_Gaussian(), WindFarm::fill_SMark_multifab(), ERF::FillForecastStateMultiFabs(), FillZeroAreaFaceFluxes(), find_rad_loc_index(), SDInitProperties::getDistribution(), HurricaneTrackerCircle(), if(), ImplicitDiffForMomLU_N(), ImplicitDiffForMomLU_S(), ImplicitDiffForMomLU_T(), ImplicitDiffForStateLU_S(), MYNNLevel2::init_coeffs(), init_my_custom_terrain(), SolverChoice::init_params(), init_which_terrain_grid(), WindFarm::init_windfarm_lat_lon(), ERF::InitData_post(), make_mom_sources(), make_sources(), SDInitProperties::makeDistributionParams(), MomentumToVelocity(), NumericalDiffusion_Scal(), NumericalDiffusion_Xmom(), NumericalDiffusion_Ymom(), orbital_avg_cos_zenith(), orbital_cos_zenith(), orbital_decl(), orbital_params(), ParallelFor(), ParallelForRNG(), TurbulentPerturbation::pseudoRandomPert(), rotate_stress_tensor(), SD_erfinv(), SDInitProperties::setDefaults(), EWP::source_terms_cellcentered(), GeneralAD::source_terms_cellcentered(), SimpleAD::source_terms_cellcentered(), GeneralAD::update(), SimpleAD::update(), EWP::update(), Fitch::update(), SurfaceLayer::update_fluxes(), ERF::Write3DPlotFile(), WindFarm::write_actuator_disks_vtk(), and z0_est().
zero
constexpr amrex::Real zero = amrex::Real(0.0) constexpr
Referenced by NOAHMP::Advance_With_State(), SatAdj::AdvanceSatAdj(), AdvectionSrcForMom_EB(), AdvectionSrcForOpenBC_Normal(), AdvectionSrcForOpenBC_Tangent(), AdvectionSrcForOpenBC_Tangent_Cons(), AdvectionSrcForOpenBC_Tangent_Xmom(), AdvectionSrcForOpenBC_Tangent_Ymom(), AdvectionSrcForOpenBC_Tangent_Zmom(), AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForScalarsWrapper(), AdvectionSrcForXMom(), AdvectionSrcForXMom_N(), AdvectionSrcForYMom(), AdvectionSrcForYMom_N(), AdvectionSrcForZMom(), AdvectionSrcForZMom_N(), ApplyBndryForcing_Forecast(), ApplySpongeZoneBCsForCC(), ApplySpongeZoneBCsForMom(), ApplySurfaceTreatment_BulkCoeff_CC(), ApplySurfaceTreatment_BulkCoeff_Mom(), eb_cut_cell_::areaHi(), eb_cut_cell_::areaLo(), ERF::AverageDownTo(), buoyancy_dry_anelastic_eb(), buoyancy_moist_Thpert(), buoyancy_moist_Tpert(), buoyancy_rhopert_eb(), InputSoundingData::calc_rho_p_isentropic(), TurbulentPerturbation::calc_tpi_amp(), TurbulentPerturbation::calc_tpi_meanMag_perBox(), TurbulentPerturbation::calc_tpi_update(), eb_cut_cell_::centBoun(), eb_cut_cell_::centHi(), eb_cut_cell_::centLo(), ERF::check_for_negative_theta(), SolverChoice::check_params(), TimeInterpolatedData::clear(), SAM::Cloud(), rrtmgp::compute_aerocom_cloudtop(), PlaneAverage::compute_averages(), rrtmgp::compute_cloud_area(), GeneralAD::compute_freestream_velocity(), SimpleAD::compute_freestream_velocity(), compute_gradp(), compute_influx_outflux(), MOSTAverage::compute_plane_averages(), Fitch::compute_power_output(), EWP::compute_power_output(), GeneralAD::compute_power_output(), SimpleAD::compute_power_output(), donelan_flux::compute_q_flux(), custom_flux::compute_q_flux(), rotate_flux::compute_q_flux(), rico_flux::compute_q_flux(), moeng_flux::compute_q_flux(), MOSTAverage::compute_region_averages(), SurfaceLayer::compute_SurfaceLayer_bcs(), custom_flux::compute_t_flux(), rotate_flux::compute_t_flux(), rico_flux::compute_t_flux(), moeng_flux::compute_t_flux(), rotate_flux::compute_v_flux(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeGlobalMinLocation(), ComputeMoistStratification(), ComputeQKESourceTerms(), ComputeSmnSmn_EB(), ComputeStrain_EB(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ComputeStressConsVisc_EB(), ComputeStressVarVisc_EB(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityLES_EB(), ComputeTurbulentViscosityRANS(), ConvertForProjection(), polygon_::define(), eb_aux_::define(), ForestDrag::define_drag_field(), ERF::derive_diag_profiles(), ERF::derive_diag_profiles_stag(), ERF::derive_stress_profiles(), ERF::derive_stress_profiles_stag(), DiffusionSrcForMom_EB(), DiffusionSrcForState_EB(), DiffusionSrcForState_N(), eb_cut_cell_::eb_cut_cell_(), EBAdvectionSrcForMomWrapper(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsWrapper(), enforceInOutSolvability(), erf_calc_slopes_eb_Dirichlet(), erf_calc_slopes_eb_Dirichlet_staggered(), erf_calc_slopes_eb_staggered(), erf_calc_slopes_eb_staggered_upwind(), erf_init_const_dens_and_linear_th_hse(), erf_init_const_dens_and_th_hse(), erf_init_dens_hse_moist(), erf_init_rayleigh(), erf_make_tau_terms(), ERF::ERF_shared(), erf_slow_rhs_post(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), ERF::estTimeStep(), ERF::Evolve(), WindFarm::fill_Nturb_multifab(), SurfaceLayer::fill_tsurf_with_sst_and_tsk(), ERF::FillForecastStateMultiFabs(), FillZeroAreaFaceFluxes(), find_rad_loc_index(), ERF::FindInitialEye(), fine_compute_interior_ghost_rhs(), for(), polygon_::get_centroid(), rrtmgp::get_subsampled_clouds(), SDInitProperties::getDistribution(), GetMoistureVars(), HurricaneMaxVelTracker(), ERF::HurricaneTracker(), if(), ImplicitDiffForMomLU_S(), ImplicitDiffForMomLU_T(), ImplicitDiffForStateLU_S(), ImplicitDiffForStateLU_T(), ERFPhysBCFunct_cons::impose_lateral_cons_bcs(), ERFPhysBCFunct_u::impose_lateral_xvel_bcs(), ERFPhysBCFunct_v::impose_lateral_yvel_bcs(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), NOAHMP::Init(), ERF::init_bcs(), init_bx_scalars_from_input_sounding_hse(), init_bx_velocities_from_input_sounding(), ERF::init_Dirichlet_bc_data(), init_my_custom_terrain(), ERF::init_only(), SolverChoice::init_params(), AdvChoice::init_params(), ERF::init_phys_bcs(), ERF::init_stuff(), TurbulentPerturbation::init_tpi(), init_which_terrain_grid(), WindFarm::init_windfarm_lat_lon(), ERF::InitData_post(), ERF::InitData_pre(), ERF::initRayleigh_at_level(), InputSoundingData::InputSoundingData(), ERF::Interp2DArrays(), interpolate_column_metgrid_linear(), intersect_plane_edge(), ERF::is_it_time_for_action(), adiabatic::iterate_flux(), adiabatic_mod_charnock::iterate_flux(), adiabatic_donelan::iterate_flux(), adiabatic_wave_coupled::iterate_flux(), adiabatic_charnock::iterate_flux(), surface_flux_charnock::iterate_flux(), surface_flux_mod_charnock::iterate_flux(), surface_flux_donelan::iterate_flux(), surface_temp_charnock::iterate_flux(), surface_temp_mod_charnock::iterate_flux(), surface_temp_donelan::iterate_flux(), surface_flux_wave_coupled::iterate_flux(), surface_temp_wave_coupled::iterate_flux(), surface_flux::iterate_flux(), surface_temp::iterate_flux(), lagrange_interp(), lagrange_setup(), PlaneAverage::line_average_interpolated(), make_buoyancy(), make_fast_coeffs(), make_gradp_pert(), make_mom_sources(), MOSTAverage::make_MOSTAverage_at_level(), make_sources(), SDInitProperties::makeDistributionParams(), ERF::MakeHorizontalAverages(), ERF::MakeNewLevelFromCoarse(), ERF::MakeNewLevelFromScratch(), Radiation::mf_to_kokkos_buffers(), MaterialPropertiesCore::molarHeatCapacity(), MomentumToVelocity(), TurbulentPerturbation::netZeroBuoyantAdd(), Morrison::NewtonIterSat(), SAM::NewtonIterSat(), eb_cut_cell_::normBoun(), NumericalDiffusion_Scal(), NumericalDiffusion_Xmom(), NumericalDiffusion_Ymom(), SDInjection::numParticlesPerCell(), SDInitialization::numParticlesPerCell(), polygon_::ok(), PlaneAverage::operator()(), SHOCInterface::SHOCPostprocess::operator()(), orbital_avg_cos_zenith(), orbital_cos_zenith(), orbital_params(), ParallelFor(), ParallelForRNG(), ERF::ParameterSanityChecks(), PlaneAverage::PlaneAverage(), PlotMultiFab(), ERF::poisson_wall_dist(), polygon_::polygon_(), SAM::Precip(), SAM::PrecipFall(), SDInitProperties::printParameters(), ERF::project_momenta(), SurfaceLayer::read_custom_roughness(), ReadBndryPlanes::read_file(), ERF::ReadCheckpointFile(), ERF::ReadParameters(), realbdy_compute_interior_ghost_rhs(), realbdy_compute_relaxation(), ERF::RemakeLevel(), ERF::restart(), rh_to_mxrat(), rotate_stress_tensor(), rrtmgp::rrtmgp_lw(), Radiation::run_impl(), eb_::set_connection_flags(), MOSTAverage::set_k_indices_EB(), MOSTAverage::set_plane_normalization(), SDInitProperties::setDefaults(), ERF::setRayleighRefFromSounding(), solve_with_EB_mlmg(), SolveTridiag(), EWP::source_terms_cellcentered(), Fitch::source_terms_cellcentered(), GeneralAD::source_terms_cellcentered(), SimpleAD::source_terms_cellcentered(), ERF::sum_derived_quantities(), ERF::sum_energy_quantities(), ERF::sum_integrated_quantities(), ERF::SurfaceDataInterpolation(), terrpoisson_adotx(), terrpoisson_flux_z(), terrpoisson_flux_zlo_dir(), MOSTAverage::trilinear_interp_T(), ProblemBase::update_geostrophic_profile(), ProblemBase::update_rhoqt_sources(), ProblemBase::update_rhotheta_sources(), ProblemBase::update_w_subsidence(), SDInjection::updateDt(), VelocityToMomentum(), eb_cut_cell_::volume(), SDInitProperties::volume(), ERF::volWgtSumMF(), ERF::WeatherDataInterpolation(), ERF::Write2DPlotFile(), ERF::Write3DPlotFile(), ERF::write_1D_profiles(), ERF::write_1D_profiles_stag(), Radiation::WriteDataLog(), ERF::writeNow(), and TurbulentPerturbation::zero_amp().