ERF: Source/Diffusion/ERF_DiffQKEAdjustment.H File Reference
ERF_DiffQKEAdjustment.H File Reference
Functions
if (l_use_mynn &&start_comp<=RhoKE_comp &&end_comp >=RhoKE_comp)
Function Documentation
if()
if (l_use_mynn &&start_comp<=RhoKE_comp &&end_comp >= RhoKE_comp)
{
         int qty_index = RhoKE_comp;
         auto pbl_mynn_B1_l = turbChoice.pbl_mynn.B1;
         ParallelFor(bx,[=,moist_indices=solverChoice.moisture_indices] AMREX_GPU_DEVICE (int i, int j, int k) noexcept
         {
             bool c_ext_dir_on_zlo = ( (bc_ptr[BCVars::cons_bc].lo(2) == ERFBCType::ext_dir) );
             bool c_ext_dir_on_zhi = ( (bc_ptr[BCVars::cons_bc].lo(5) == ERFBCType::ext_dir) );
             bool u_ext_dir_on_zlo = ( (bc_ptr[BCVars::xvel_bc].lo(2) == ERFBCType::ext_dir) );
             bool u_ext_dir_on_zhi = ( (bc_ptr[BCVars::xvel_bc].lo(5) == ERFBCType::ext_dir) );
             bool v_ext_dir_on_zlo = ( (bc_ptr[BCVars::yvel_bc].lo(2) == ERFBCType::ext_dir) );
             bool v_ext_dir_on_zhi = ( (bc_ptr[BCVars::yvel_bc].lo(5) == ERFBCType::ext_dir) );
             // This computes shear production, buoyancy production, and dissipation terms only.
             cell_rhs(i, j, k, qty_index) += ComputeQKESourceTerms(i,j,k,u,v,cell_data,cell_prim,
                                                                   mu_turb,cellSizeInv,domain,
                                                                   pbl_mynn_B1_l,tm_arr(i,j,0),
                                                                   moist_indices,
                                                                   c_ext_dir_on_zlo, c_ext_dir_on_zhi,
                                                                   u_ext_dir_on_zlo, u_ext_dir_on_zhi,
                                                                   v_ext_dir_on_zlo, v_ext_dir_on_zhi);
         });
     }
Referenced by ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityRANS(), and ERF::poisson_wall_dist().