ERF: Source/Prob/ERF_UpdateWSubsidence_Bomex.H File Reference
ERF_UpdateWSubsidence_Bomex.H File Reference
Functions
ParmParse pp_prob ("prob")
pp_prob query ("wbar_sub_max", wbar_sub_max)
pp_prob query ("wbar_cutoff_max", wbar_cutoff_max)
pp_prob query ("wbar_cutoff_min", wbar_cutoff_min)
AMREX_ASSERT_WITH_MESSAGE (wbar_cutoff_min > wbar_cutoff_max, "ERROR: wbar_cutoff_min < wbar_cutoff_max")
for (int k=1;k<=khi+1;k++)
Variables
Real wbar_sub_max = -0.65
Real wbar_cutoff_max = 1500.0
Real wbar_cutoff_min = 2100.0
Real z_0 = zlevels[0]
Real slope1 = wbar_sub_max / (wbar_cutoff_max - z_0)
Real slope2 = -wbar_sub_max / (wbar_cutoff_min - wbar_cutoff_max)
wbar [0] = 0.0
Function Documentation
AMREX_ASSERT_WITH_MESSAGE()
AMREX_ASSERT_WITH_MESSAGE (wbar_cutoff_min , wbar_cutoff_max)
Referenced by AdvectionSrcForMom_ConstantDz(), AdvectionSrcForMom_EB(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMom_TF(), AdvectionSrcForMomVert(), AdvectionSrcForMomVert_N(), AdvectionSrcForScalars(), AdvectionSrcForScalarsVert(), ComputeDiffusivityMYNNEDMF(), EBAdvectionSrcForMomVert(), EBAdvectionSrcForScalars(), EBAdvectionSrcForScalarsVert(), ImplicitDiffForMomLU_N(), ImplicitDiffForMomLU_S(), ImplicitDiffForMomLU_T(), ImplicitDiffForStateLU_N(), ImplicitDiffForStateLU_S(), ImplicitDiffForStateLU_T(), SolverChoice::init_params(), AdvChoice::init_params(), ERF::init_phys_bcs(), make_gradp_pert(), SurfaceLayer::read_custom_roughness(), SurfaceLayer::SurfaceLayer(), and AdvChoice::validate_weno_momentum_compatibility().
for()
for (int k = 1; k <= khi+1; k++)
{
         const Real z = zlevels[k];
         if (z <= wbar_cutoff_max) {
             wbar[k] = slope1 * (z - z_0);
         } else if (z <= wbar_cutoff_min) {
             wbar[k] = slope2 * (z - wbar_cutoff_max) + wbar_sub_max;
         } else {
             wbar[k] = 0.0;
         }
     }
pp_prob()
ParmParse pp_prob ("prob")
query() [1/3]
pp_prob query ("wbar_cutoff_max" , wbar_cutoff_max)
query() [2/3]
pp_prob query ("wbar_cutoff_min" , wbar_cutoff_min)
query() [3/3]
pp_prob query ("wbar_sub_max" , wbar_sub_max)
Variable Documentation
slope1
Real slope1 = wbar_sub_max / (wbar_cutoff_max - z_0)
Referenced by for().
slope2
Real slope2 = -wbar_sub_max / (wbar_cutoff_min - wbar_cutoff_max)
Referenced by for().
wbar
wbar[0] = 0.0
Referenced by for().
wbar_cutoff_max
Real wbar_cutoff_max = 1500.0
Referenced by for().
wbar_cutoff_min
Real wbar_cutoff_min = 2100.0
Referenced by for().
wbar_sub_max
Real wbar_sub_max = -0.65
Referenced by for().
z_0
Real z_0 = zlevels[0]
Referenced by ERF::advance_dycore(), SurfaceLayer::compute_fluxes(), ComputeTurbulentViscosity(), ComputeTurbulentViscosityRANS(), for(), and SurfaceLayer::read_custom_roughness().