ERF: Source/Prob/ERF_InitCustomPertVels_SDMCongestus3D.H File Reference
ERF_InitCustomPertVels_SDMCongestus3D.H File Reference
Functions
ParmParse pp_prob ("prob")
pp_prob query ("U_0", U_0)
pp_prob query ("V_0", V_0)
pp_prob query ("W_0", W_0)
pp_prob query ("U_0_Pert_Mag", U_0_Pert_Mag)
pp_prob query ("V_0_Pert_Mag", V_0_Pert_Mag)
pp_prob query ("W_0_Pert_Mag", W_0_Pert_Mag)
pp_prob query ("pert_deltaU", pert_deltaU)
pp_prob query ("pert_deltaV", pert_deltaV)
pp_prob query ("pert_periods_U", pert_periods_U)
pp_prob query ("pert_periods_V", pert_periods_V)
pp_prob query ("pert_ref_height", pert_ref_height)
ParallelForRNG (xbx, [=] AMREX_GPU_DEVICE(int i, int j, int k, const amrex::RandomEngine &engine) noexcept { const Real *prob_lo=geomdata.ProbLo();const Real *dx=geomdata.CellSize();const Real y=prob_lo[1]+(j+myhalf) *dx[1];const Real z=prob_lo[2]+(k+myhalf) *dx[2];x_vel_pert(i, j, k)=U_0;if((z<=pert_ref_height) &&(U_0_Pert_Mag !=zero)) { Real rand_double=amrex::Random(engine);Real x_vel_prime=(rand_double *two - one) *U_0_Pert_Mag;x_vel_pert(i, j, k)+=x_vel_prime;} if(pert_deltaU !=zero) { const amrex::Real yl=y - prob_lo[1];const amrex::Real zl=z/pert_ref_height;const amrex::Real damp=std::exp(-myhalf *zl *zl);x_vel_pert(i, j, k)+=ufac *damp *z *std::cos(aval *yl);} })
ParallelForRNG (ybx, [=] AMREX_GPU_DEVICE(int i, int j, int k, const amrex::RandomEngine &engine) noexcept { const Real *prob_lo=geomdata.ProbLo();const Real *dx=geomdata.CellSize();const Real x=prob_lo[0]+(i+myhalf) *dx[0];const Real z=prob_lo[2]+(k+myhalf) *dx[2];y_vel_pert(i, j, k)=V_0;if((z<=pert_ref_height) &&(V_0_Pert_Mag !=zero)) { Real rand_double=amrex::Random(engine);Real y_vel_prime=(rand_double *two - one) *V_0_Pert_Mag;y_vel_pert(i, j, k)+=y_vel_prime;} if(pert_deltaV !=zero) { const amrex::Real xl=x - prob_lo[0];const amrex::Real zl=z/pert_ref_height;const amrex::Real damp=std::exp(-myhalf *zl *zl);y_vel_pert(i, j, k)+=vfac *damp *z *std::cos(bval *xl);} })
ParallelForRNG (zbx, [=] AMREX_GPU_DEVICE(int i, int j, int k, const amrex::RandomEngine &engine) noexcept { const int dom_lo_z=geomdata.Domain().smallEnd()[2];const int dom_hi_z=geomdata.Domain().bigEnd()[2];if(k==dom_lo_z||k==dom_hi_z+1) { z_vel_pert(i, j, k)=zero;} else if(W_0_Pert_Mag !=zero) { Real rand_double=amrex::Random(engine);Real z_vel_prime=(rand_double *two - one) *W_0_Pert_Mag;z_vel_pert(i, j, k)=W_0+z_vel_prime;} })
Variables
Real U_0 = zero
Real V_0 = zero
Real W_0 = zero
Real U_0_Pert_Mag = zero
Real V_0_Pert_Mag = zero
Real W_0_Pert_Mag = zero
Real pert_deltaU = zero
Real pert_deltaV = zero
Real pert_periods_U = amrex::Real(5.0)
Real pert_periods_V = amrex::Real(5.0)
Real pert_ref_height = amrex::Real(100.0)
Real prob_lo_x = geomdata.ProbLo(0)
Real prob_lo_y = geomdata.ProbLo(1)
Real prob_hi_x = geomdata.ProbHi(0)
Real prob_hi_y = geomdata.ProbHi(1)
Real aval = pert_periods_U * two * PI / (prob_hi_y - prob_lo_y)
Real bval = pert_periods_V * two * PI / (prob_hi_x - prob_lo_x)
Real ufac = pert_deltaU * std::exp(myhalf) / pert_ref_height
Real vfac = pert_deltaV * std::exp(myhalf) / pert_ref_height
Function Documentation
ParallelForRNG() [1/3]
ParallelForRNG (xbx , [=] AMREX_GPU_DEVICE(int i, int j, int k, const amrex::RandomEngine &engine) noexcept { const Real *prob_lo=geomdata.ProbLo();const Real *dx=geomdata.CellSize();const Real y=prob_lo[1]+(j+myhalf) *dx[1];const Real z=prob_lo[2]+(k+myhalf) *dx[2];x_vel_pert(i, j, k)=U_0;if((z<=pert_ref_height) &&(U_0_Pert_Mag !=zero)) { Real rand_double=amrex::Random(engine);Real x_vel_prime=(rand_double *two - one) *U_0_Pert_Mag;x_vel_pert(i, j, k)+=x_vel_prime;} if(pert_deltaU !=zero) { const amrex::Real yl=y - prob_lo[1];const amrex::Real zl=z/pert_ref_height;const amrex::Real damp=std::exp(-myhalf *zl *zl);x_vel_pert(i, j, k)+=ufac *damp *z *std::cos(aval *yl);} })
ParallelForRNG() [2/3]
ParallelForRNG (ybx , [=] AMREX_GPU_DEVICE(int i, int j, int k, const amrex::RandomEngine &engine) noexcept { const Real *prob_lo=geomdata.ProbLo();const Real *dx=geomdata.CellSize();const Real x=prob_lo[0]+(i+myhalf) *dx[0];const Real z=prob_lo[2]+(k+myhalf) *dx[2];y_vel_pert(i, j, k)=V_0;if((z<=pert_ref_height) &&(V_0_Pert_Mag !=zero)) { Real rand_double=amrex::Random(engine);Real y_vel_prime=(rand_double *two - one) *V_0_Pert_Mag;y_vel_pert(i, j, k)+=y_vel_prime;} if(pert_deltaV !=zero) { const amrex::Real xl=x - prob_lo[0];const amrex::Real zl=z/pert_ref_height;const amrex::Real damp=std::exp(-myhalf *zl *zl);y_vel_pert(i, j, k)+=vfac *damp *z *std::cos(bval *xl);} })
ParallelForRNG() [3/3]
ParallelForRNG (zbx , [=] AMREX_GPU_DEVICE(int i, int j, int k, const amrex::RandomEngine &engine) noexcept { const int dom_lo_z=geomdata.Domain().smallEnd()[2];const int dom_hi_z=geomdata.Domain().bigEnd()[2];if(k==dom_lo_z||k==dom_hi_z+1) { z_vel_pert(i, j, k)=zero;} else if(W_0_Pert_Mag !=zero) { Real rand_double=amrex::Random(engine);Real z_vel_prime=(rand_double *two - one) *W_0_Pert_Mag;z_vel_pert(i, j, k)=W_0+z_vel_prime;} })
pp_prob()
ParmParse pp_prob ("prob")
query() [1/11]
pp_prob query ("pert_deltaU" , pert_deltaU)
query() [2/11]
pp_prob query ("pert_deltaV" , pert_deltaV)
query() [3/11]
pp_prob query ("pert_periods_U" , pert_periods_U)
query() [4/11]
pp_prob query ("pert_periods_V" , pert_periods_V)
query() [5/11]
pp_prob query ("pert_ref_height" , pert_ref_height)
query() [6/11]
pp_prob query ("U_0" , U_0)
query() [7/11]
pp_prob query ("U_0_Pert_Mag" , U_0_Pert_Mag)
query() [8/11]
pp_prob query ("V_0" , V_0)
query() [9/11]
pp_prob query ("V_0_Pert_Mag" , V_0_Pert_Mag)
query() [10/11]
pp_prob query ("W_0" , W_0)
query() [11/11]
pp_prob query ("W_0_Pert_Mag" , W_0_Pert_Mag)
Variable Documentation
aval
Real aval = pert_periods_U * two * PI / (prob_hi_y - prob_lo_y)
Referenced by ParallelForRNG().
bval
Real bval = pert_periods_V * two * PI / (prob_hi_x - prob_lo_x)
Referenced by ParallelForRNG().
pert_deltaU
Real pert_deltaU = zero
Referenced by ParallelForRNG().
pert_deltaV
Real pert_deltaV = zero
Referenced by ParallelForRNG().
pert_periods_U
Real pert_periods_U = amrex::Real(5.0)
pert_periods_V
Real pert_periods_V = amrex::Real(5.0)
pert_ref_height
Real pert_ref_height = amrex::Real(100.0)
Referenced by ParallelForRNG().
prob_hi_x
Real prob_hi_x = geomdata.ProbHi(0)
prob_hi_y
Real prob_hi_y = geomdata.ProbHi(1)
prob_lo_x
Real prob_lo_x = geomdata.ProbLo(0)
prob_lo_y
Real prob_lo_y = geomdata.ProbLo(1)
U_0
Real U_0 = zero
Referenced by ParallelForRNG().
U_0_Pert_Mag
Real U_0_Pert_Mag = zero
Referenced by ParallelForRNG().
ufac
Real ufac = pert_deltaU * std::exp(myhalf) / pert_ref_height
Referenced by ParallelForRNG().
V_0
Real V_0 = zero
Referenced by ParallelForRNG().
V_0_Pert_Mag
Real V_0_Pert_Mag = zero
Referenced by ParallelForRNG().
vfac
Real vfac = pert_deltaV * std::exp(myhalf) / pert_ref_height
Referenced by ParallelForRNG().
W_0
Real W_0 = zero
Referenced by ParallelForRNG().
W_0_Pert_Mag
Real W_0_Pert_Mag = zero
Referenced by ParallelForRNG().