ERF: Source/IO/ERF_Plotfile2DInterpolator.cpp File Reference
ERF_Plotfile2DInterpolator.cpp File Reference
#include "ERF_Plotfile2DInterpolator.H"
#include "ERF_Plotfile2DFill.H"
#include <cmath>
#include <sstream>
Namespaces
plotfile2d
Functions
void plotfile2d::fill_sampled_level_component (MultiFab &dst, int dst_comp, const Plotfile2DOutputDescriptor &descriptor, const MultiFab &cons, const MultiFab *z_phys_cc, const MultiFab &z_phys_nd, bool have_z_phys_cc, const MoistureComponentIndices &moisture_indices, int klo, int khi, const SampledWindSources &wind_sources)
Variable Documentation
cos_alpha
Real cos_alpha = Real(1.0)
sin_alpha
Real sin_alpha = Real(0.0)
u_east
Real u_east = Real(0.0)
v_north
Real v_north = Real(0.0)
w
Real w = Real(0.0)
Referenced by ERF::advance_dycore(), AdvectionSrcForMom(), AdvectionSrcForMom_ConstantDz(), AdvectionSrcForMom_EB(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMom_TF(), AdvectionSrcForMomVert(), AdvectionSrcForMomVert_N(), AdvectionSrcForMomWrapper(), AdvectionSrcForMomWrapper_N(), AdvectionSrcForOpenBC_Tangent_Zmom(), AdvectionSrcForZMom(), AdvectionSrcForZMom_N(), ERF::apply_gaussian_smoothing_to_perturbations(), ComputeStrain_EB(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), EBAdvectionSrcForMomVert(), EBAdvectionSrcForMomWrapper(), derived::erf_derhelicity(), derived::erf_derlocalhelicity(), derived::erf_dermagvel(), derived::erf_dermagvelsq(), erf_make_tau_terms(), erf_slow_rhs_pre(), ERF::init_Dirichlet_bc_data(), ERFFillPatcher::InterpFace(), make_mom_sources(), OmegaFromW(), and WFromOmega().