ERF: Source/Prob/ERF_InitCustomPertVels_ParticleTests.H File Reference
ERF_InitCustomPertVels_ParticleTests.H File Reference
Functions
ParmParse pp ("prob")
pp query ("U_0", U_0)
ParallelFor (xbx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { Real ztop=z_nd(i, j, khi+1);Real zht=z_nd(i, j, klo);x_vel_pert(i, j, k)=U_0 *ztop/(ztop - zht);})
ParallelFor (zbx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { z_vel_pert(i, j, k)=WFromOmega(i, j, k, 0.0, x_vel_pert, y_vel_pert, mf_u, mf_v, z_nd, dxInv);})
Variables
Real U_0 = 0.0
const int klo = geomdata.Domain().smallEnd()[2]
const int khi = geomdata.Domain().bigEnd()[2]
const auto dx = geomdata.CellSize()
amrex::GpuArray< Real, AMREX_SPACEDIM > dxInv = 1. / dx[0]
Function Documentation
ParallelFor() [1/2]
ParallelFor (xbx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { Real ztop=z_nd(i, j, khi+1);Real zht=z_nd(i, j, klo);x_vel_pert(i, j, k)=U_0 *ztop/(ztop - zht);})
ParallelFor() [2/2]
ParallelFor (zbx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { z_vel_pert(i, j, k)=WFromOmega(i, j, k, 0.0, x_vel_pert, y_vel_pert, mf_u, mf_v, z_nd, dxInv);})
pp()
ParmParse pp ("prob")
query()
pp query ("U_0" , U_0)
Variable Documentation
dx
const auto dx = geomdata.CellSize()
Referenced by ERF::apply_gaussian_smoothing_to_perturbations(), ApplyBndryForcing_Forecast(), ApplySpongeZoneBCsForCC(), ApplySpongeZoneBCsForMom(), ApplySpongeZoneBCsForMom_ReadFromFile(), compute_gradp(), MOSTAverage::compute_region_averages(), ComputeGlobalMinLocation(), eb_aux_::define(), ForestDrag::define_drag_field(), DiffusionSrcForMom_EB(), erf_calc_slopes_eb_Dirichlet(), erf_calc_slopes_eb_Dirichlet_staggered(), erf_calc_slopes_eb_staggered(), erf_calc_slopes_eb_staggered_upwind(), derived::erf_derenstrophysq(), derived::erf_dervorty(), derived::erf_dervortz(), erf_slow_rhs_post(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), ERF::ErrorEst(), WindFarm::fill_Nturb_multifab(), WindFarm::fill_SMark_multifab(), WindFarm::fill_SMark_multifab_mesoscale_models(), ERF::FillForecastStateMultiFabs(), ERF::FillSurfaceStateMultiFabs(), ERF::FindInitialEye(), HurricaneEyeTrackerNotInitial(), HurricaneMaxVelTracker(), HurricaneMinPressureTracker(), if(), init_bx_scalars_from_input_sounding(), init_bx_scalars_from_input_sounding_hse(), init_bx_velocities_from_input_sounding(), init_default_zphys(), init_my_custom_terrain(), TurbulentPerturbation::init_tpi(), init_zlevels(), interpolate_from_coarse(), make_areas(), make_J(), MOSTAverage::make_MOSTAverage_at_level(), make_sources(), ParallelFor(), ParallelForRNG(), ERF::poisson_wall_dist(), ERF::project_momenta(), SurfaceLayer::read_custom_roughness(), ProblemBase::read_custom_terrain(), realbdy_compute_interior_ghost_rhs(), realbdy_compute_relaxation(), ERF::refinement_criteria_setup(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_z_positions_T(), ERF::setSpongeRefFromSounding(), ERF::solve_with_gmres(), EWP::source_terms_cellcentered(), Fitch::source_terms_cellcentered(), GeneralAD::source_terms_cellcentered(), SimpleAD::source_terms_cellcentered(), ERF::sum_derived_quantities(), ERF::sum_energy_quantities(), tag_on_distance_from_eye(), thinbody_wall_dist(), ERF::volWgtColumnSum(), ERF::volWgtSumMF(), ERF::Write2DPlotFile(), ERF::Write3DPlotFile(), ERF::write_1D_profiles(), ERF::write_1D_profiles_stag(), LineSampler::write_line_plotfile(), and writeNCPlotFile().
dxInv
dxInv[2] = 1. / dx[0]
Referenced by ERF::advance_dycore(), AdvectionSrcForMom_ConstantDz(), AdvectionSrcForMom_EB(), AdvectionSrcForMom_StretchedDz(), AdvectionSrcForMom_TF(), AdvectionSrcForMomWrapper_N(), AdvectionSrcForOpenBC_Normal(), AdvectionSrcForOpenBC_Tangent(), AdvectionSrcForOpenBC_Tangent_Cons(), AdvectionSrcForOpenBC_Tangent_Xmom(), AdvectionSrcForOpenBC_Tangent_Ymom(), AdvectionSrcForOpenBC_Tangent_Zmom(), AdvectionSrcForRho(), AdvectionSrcForScalars(), AdvectionSrcForXMom(), AdvectionSrcForXMom_N(), AdvectionSrcForYMom(), AdvectionSrcForYMom_N(), AdvectionSrcForZMom(), AdvectionSrcForZMom_N(), ERF::compute_divergence(), compute_gradp(), compute_gradp_interpz(), Compute_h_xi_AtCellCenter(), Compute_h_xi_AtEdgeCenterI(), Compute_h_xi_AtEdgeCenterJ(), Compute_h_xi_AtEdgeCenterK(), MOSTAverage::compute_plane_averages(), MOSTAverage::compute_region_averages(), SurfaceLayer::compute_SurfaceLayer_bcs(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeDiffusivityYSU(), ComputeStrain_EB(), ComputeStrain_N(), ComputeStrain_S(), ComputeStrain_T(), ComputeStressConsVisc_T(), ComputeStressVarVisc_T(), ComputeTurbulentViscosityLES(), DiffusionSrcForMom(), DiffusionSrcForMom_EB(), EBAdvectionSrcForRho(), EBAdvectionSrcForScalars(), erf_make_tau_terms(), erf_slow_rhs_post(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), FillZeroAreaFaceFluxes(), if(), ERFPhysBCFunct_w::impose_lateral_zvel_bcs(), ERFPhysBCFunct_cons::impose_vertical_cons_bcs(), ERFPhysBCFunct_u::impose_vertical_xvel_bcs(), ERFPhysBCFunct_v::impose_vertical_yvel_bcs(), ERFPhysBCFunct_w::impose_vertical_zvel_bcs(), make_fast_coeffs(), make_mom_sources(), make_sources(), OmegaFromW(), ERFPhysBCFunct_u::operator()(), ERFPhysBCFunct_v::operator()(), ERFPhysBCFunct_w::operator()(), ERFPhysBCFunct_cons::operator()(), ParallelFor(), ERF::project_momenta(), rotate_scalar_flux(), rotate_stress_tensor(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_rotated_fields(), and WFromOmega().
khi
const int khi = geomdata.Domain().bigEnd()[2]
Referenced by ParallelFor().
klo
const int klo = geomdata.Domain().smallEnd()[2]
Referenced by Morrison::Advance(), SurfaceLayer::compute_SurfaceLayer_bcs(), ComputeDiffusivityMRF(), ComputeDiffusivityMYJ(), copy_surface_tau_for_implicit(), DiffusionSrcForState_S(), ERF::erf_enforce_hse(), erf_init_dens_hse(), erf_slow_rhs_pre(), erf_substep_MT(), erf_substep_NS(), erf_substep_T(), ImplicitDiffForMom_N(), ImplicitDiffForMom_S(), ImplicitDiffForMom_T(), ImplicitDiffForState_N(), ImplicitDiffForState_S(), ImplicitDiffForState_T(), Radiation::Init(), ERF::init_Dirichlet_bc_data(), ERF::init_geo_wind_profile(), HSEutils::init_isentropic_hse(), HSEutils::init_isentropic_hse_terrain(), make_buoyancy(), make_fast_coeffs(), make_sources(), ParallelFor(), SurfaceLayer::read_custom_roughness(), ProblemBase::read_custom_terrain(), InputSpongeData::read_from_file(), InputSoundingData::read_from_file(), ERF::ReadCheckpointFile(), ERF::refinement_criteria_setup(), rotate_scalar_flux(), rotate_stress_tensor(), ERF::sample_lines(), SHOCInterface::set_grids(), ERF::setRayleighRefFromSounding(), SolveTridiag(), and ERF::Write2DPlotFile().
U_0
Real U_0 = 0.0
Referenced by ParallelFor().