ERF: Source/Utils/ERF_ParFunctions.H File Reference
ERF_ParFunctions.H File Reference
Functions
AMREX_FORCE_INLINE void reduce_to_max_per_height (amrex::Vector< amrex::Real > &v, std::unique_ptr< amrex::MultiFab > &mf)
Function Documentation
reduce_to_max_per_height()
AMREX_FORCE_INLINE void reduce_to_max_per_height (amrex::Vector< amrex::Real > & v, std::unique_ptr< amrex::MultiFab > & mf)
Reduce a multifab to a vector of max values at each height
 {
     amrex::MultiArray4<const amrex::Real> const& ma = mf->const_arrays();
     for (int k = 0; k < v.size(); k++) {
         v[k] = amrex::ParReduce(amrex::TypeList<amrex::ReduceOpMax>{},
                                 amrex::TypeList<amrex::Real>{},
                                 *mf,
                                 amrex::IntVect(0),
         [=] AMREX_GPU_DEVICE (int box_no, int i, int j, int) noexcept
             -> amrex::GpuTuple<amrex::Real>
         {
             return { ma[box_no](i,j,k) };
         });
     }
     amrex::ParallelDescriptor::ReduceRealMax(v.data(), v.size());
 }
Referenced by erf_init_rayleigh(), ERF::setRayleighRefFromSounding(), and ERF::setSpongeRefFromSounding().