ERF: Source/Microphysics/WSM6/ERF_AdvanceWSM6.cpp File Reference
ERF_AdvanceWSM6.cpp File Reference
#include "ERF_WSM6.H"
#include "ERF_WSM6_Fortran_Interface.H"
#include <AMReX_Reduce.H>
#include <algorithm>
#include <array>
#include <cctype>
#include <cstdio>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_cpmcal (Real x, Real qmin_arg, Real cpd_arg, Real cpv_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_xlcal (Real x, Real xlv0_arg, Real xlv1_arg, Real t0c_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_diffus (Real x, Real y)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_viscos (Real x, Real y)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_xka (Real x, Real y)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_diffac (Real a, Real b, Real c, Real d, Real e, Real rv_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_venfac (Real a, Real b, Real c, Real den0_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_conden (Real a, Real b, Real c, Real d, Real e, Real qmin_arg, Real rv_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_lamdar (Real x, Real y, Real pidn0r_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_lamdas (Real x, Real y, Real z, Real pidn0s_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_lamdag (Real x, Real y, Real pidn0g_arg)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_slope_rain_cell (Real qr, Real den, Real denfac, Real pidn0r_arg, Real qcrmin_arg, Real rslopermax_arg, Real rsloperbmax_arg, Real rsloper2max_arg, Real rsloper3max_arg, Real bvtr_arg, Real pvtr_arg, Real &rslope, Real &rslopeb, Real &rslope2, Real &rslope3, Real &vt)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_slope_snow_cell (Real qs, Real den, Real denfac, Real t, Real pidn0s_arg, Real alpha_arg, Real n0smax_arg, Real n0s_arg, Real t0c_arg, Real qcrmin_arg, Real rslopesmax_arg, Real rslopesbmax_arg, Real rslopes2max_arg, Real rslopes3max_arg, Real bvts_arg, Real pvts_arg, Real &rslope, Real &rslopeb, Real &rslope2, Real &rslope3, Real &vt, Real &n0sfac)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_slope_graup_cell (Real qg, Real den, Real denfac, Real pidn0g_arg, Real qcrmin_arg, Real rslopegmax_arg, Real rslopegbmax_arg, Real rslopeg2max_arg, Real rslopeg3max_arg, Real bvtg_arg, Real pvtg_arg, Real &rslope, Real &rslopeb, Real &rslope2, Real &rslope3, Real &vt)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_nislfv_rain_plm (int im, int km, const Real *denl, const Real *denfacl, const Real *tkl, const Real *dzl, Real *wwl, Real *rql, Real *precip, Real dt, int id, int iter, int, Real *dbg_zi=nullptr, Real *dbg_za=nullptr, Real *dbg_dza=nullptr, Real *dbg_wi=nullptr, Real *dbg_ww=nullptr, Real *dbg_wa=nullptr, Real *dbg_was=nullptr, Real *dbg_qa=nullptr, Real *dbg_qmi=nullptr, Real *dbg_qpi=nullptr, Real *dbg_kb_before_backstep=nullptr, Real *dbg_kt_before_backstep=nullptr, Real *dbg_kb_after_backstep=nullptr, Real *dbg_kt_after_backstep=nullptr, Real *dbg_kb_after_search=nullptr, Real *dbg_kt_after_search=nullptr, Real *dbg_zsum=nullptr, Real *dbg_qsum=nullptr, Real *dbg_qn=nullptr, Real *dbg_denqrs1_after_kernel=nullptr)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_nislfv_rain_plm6 (int im, int km, const Real *denl, const Real *denfacl, const Real *tkl, const Real *dzl, Real *wwl, Real *rql, Real *rql2, Real *precip1, Real *precip2, Real dt, int id, int iter)
Function Documentation
wsm6_conden()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_conden (Real a, Real b, Real c, Real d, Real e, Real qmin_arg, Real rv_arg)
{
     return (amrex::max(b,qmin_arg)-c)
           /(Real(1.0)+d*d/(rv_arg*e)*c/(a*a));
 }
Referenced by WSM6::Advance().
wsm6_cpmcal()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_cpmcal (Real x, Real qmin_arg, Real cpd_arg, Real cpv_arg)
{
     return cpd_arg*(Real(1.0)-amrex::max(x,qmin_arg))
           +amrex::max(x,qmin_arg)*cpv_arg;
 }
Referenced by WSM6::Advance().
wsm6_diffac()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_diffac (Real a, Real b, Real c, Real d, Real e, Real rv_arg)
{
     return d*a*a/(wsm6_xka(c,d)*rv_arg*c*c)
           +Real(1.0)/(e*wsm6_diffus(c,b));
 }
Referenced by WSM6::Advance().
wsm6_diffus()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_diffus (Real x, Real y)
{
     return Real(8.794e-5)*std::exp(std::log(x)*Real(1.81))/y;
 }
Referenced by wsm6_diffac(), and wsm6_venfac().
wsm6_lamdag()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_lamdag (Real x, Real y, Real pidn0g_arg)
{
     return std::sqrt(std::sqrt(pidn0g_arg/(x*y)));
 }
Referenced by wsm6_slope_graup_cell().
wsm6_lamdar()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_lamdar (Real x, Real y, Real pidn0r_arg)
{
     return std::sqrt(std::sqrt(pidn0r_arg/(x*y)));
 }
Referenced by wsm6_slope_rain_cell().
wsm6_lamdas()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_lamdas (Real x, Real y, Real z, Real pidn0s_arg)
{
     return std::sqrt(std::sqrt(pidn0s_arg*z/(x*y)));
 }
Referenced by wsm6_slope_snow_cell().
wsm6_nislfv_rain_plm()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_nislfv_rain_plm (int im, int km, const Real * denl, const Real * denfacl, const Real * tkl, const Real * dzl, Real * wwl, Real * rql, Real * precip, Real dt, int id, int iter, int , Real * dbg_zi = nullptr, Real * dbg_za = nullptr, Real * dbg_dza = nullptr, Real * dbg_wi = nullptr, Real * dbg_ww = nullptr, Real * dbg_wa = nullptr, Real * dbg_was = nullptr, Real * dbg_qa = nullptr, Real * dbg_qmi = nullptr, Real * dbg_qpi = nullptr, Real * dbg_kb_before_backstep = nullptr, Real * dbg_kt_before_backstep = nullptr, Real * dbg_kb_after_backstep = nullptr, Real * dbg_kt_after_backstep = nullptr, Real * dbg_kb_after_search = nullptr, Real * dbg_kt_after_search = nullptr, Real * dbg_zsum = nullptr, Real * dbg_qsum = nullptr, Real * dbg_qn = nullptr, Real * dbg_denqrs1_after_kernel = nullptr)
 {
     static_cast<void>(id);
     if (km > WSM6_MAX_LEVELS) return;
     constexpr Real pi = Real(3.141592653589793238462643383279502884);
     auto rgmma = [](Real x) -> Real {
         // Match Fortran rgmma() semantics used in WSM6 rain setup.
         if (x == Real(1.0)) return Real(0.0);
         constexpr Real euler = Real(0.577215664901532);
         Real rg = x * std::exp(euler * x);
         for (int ii = 1; ii <= 10000; ++ii) {
             const Real y = static_cast<Real>(ii);
             rg = rg * (Real(1.0) + x / y) * std::exp(-x / y);
         }
         return Real(1.0) / rg;
     };
     const Real pidn0r = pi * Real(rhoh2o) * WSM6::n0r;
     const Real rslopermax = Real(1.0) / WSM6::lamdarmax;
     const Real rsloperbmax = std::pow(rslopermax, WSM6::bvtr);
     const Real rsloper2max = rslopermax * rslopermax;
     const Real rsloper3max = rsloper2max * rslopermax;
     const Real pvtr = WSM6::avtr * rgmma(Real(4.0) + WSM6::bvtr) / Real(6.0);
     for (int i = 0; i < im; ++i) {
         Real dz[WSM6_MAX_LEVELS];
         Real ww[WSM6_MAX_LEVELS];
         Real qq[WSM6_MAX_LEVELS];
         Real wd[WSM6_MAX_LEVELS];
         Real wa[WSM6_MAX_LEVELS];
         Real was[WSM6_MAX_LEVELS];
         Real den[WSM6_MAX_LEVELS];
         Real denfac[WSM6_MAX_LEVELS];
         Real tk[WSM6_MAX_LEVELS];
         Real qn[WSM6_MAX_LEVELS];
         Real qr[WSM6_MAX_LEVELS];
         Real tmp[WSM6_MAX_LEVELS];
         Real tmp1[WSM6_MAX_LEVELS];
         Real tmp2[WSM6_MAX_LEVELS];
         Real tmp3[WSM6_MAX_LEVELS];
         Real wi[WSM6_MAX_LEVELS + 1];
         Real zi[WSM6_MAX_LEVELS + 1];
         Real za[WSM6_MAX_LEVELS + 1];
         Real dza[WSM6_MAX_LEVELS + 1];
         Real qa[WSM6_MAX_LEVELS + 1];
         Real qmi[WSM6_MAX_LEVELS + 1];
         Real qpi[WSM6_MAX_LEVELS + 1];
         const bool emit_search_dbg = (dbg_qn != nullptr);
         Real allold = Real(0.0);
         for (int k = 0; k < km; ++k) {
             const int idx = i * km + k;
             dz[k] = dzl[idx];
             qq[k] = rql[idx];
             ww[k] = wwl[idx];
             wd[k] = ww[k];
             den[k] = denl[idx];
             denfac[k] = denfacl[idx];
             tk[k] = tkl[idx];
             allold += qq[k];
         }
         precip[i] = Real(0.0);
         if (allold <= Real(0.0)) {
             continue;
         }
         zi[0] = Real(0.0);
         for (int k = 0; k < km; ++k) {
             zi[k + 1] = zi[k] + dz[k];
             if (emit_search_dbg) {
                 dbg_zi[k] = zi[k];
             }
         }
         auto update_wind_and_state = [&](void) {
             wi[0] = ww[0];
             wi[km] = ww[km - 1];
             for (int k = 1; k < km; ++k) {
                 wi[k] = (ww[k] * dz[k - 1] + ww[k - 1] * dz[k]) / (dz[k - 1] + dz[k]);
             }
             wi[0] = ww[0];
             wi[1] = Real(0.5) * (ww[1] + ww[0]);
             for (int k = 2; k < km - 1; ++k) {
                 wi[k] = Real(9.0) / Real(16.0) * (ww[k] + ww[k - 1])
                       - Real(1.0) / Real(16.0) * (ww[k + 1] + ww[k - 2]);
             }
             if (km > 1) {
                 wi[km - 1] = Real(0.5) * (ww[km - 1] + ww[km - 2]);
                 wi[km] = ww[km - 1];
             }
             for (int k = 1; k < km; ++k) {
                 if (ww[k] == Real(0.0)) wi[k] = ww[k - 1];
             }
             const Real con1 = Real(0.05);
             for (int k = km - 1; k >= 0; --k) {
                 const Real decfl = (wi[k + 1] - wi[k]) * dt / dz[k];
                 if (decfl > con1) {
                     wi[k] = wi[k + 1] - con1 * dz[k] / dt;
                 }
             }
             for (int k = 0; k <= km; ++k) {
                 za[k] = zi[k] - wi[k] * dt;
             }
             for (int k = 0; k < km; ++k) {
                 dza[k] = za[k + 1] - za[k];
                 if (dza[k] <= Real(0.0)) dza[k] = dz[k]; // divergence guard
             }
             dza[km] = zi[km] - za[km]; // Fortran: dza(km+1) = zi(km+1)-za(km+1)
             if (dza[km] <= Real(0.0)) dza[km] = dz[km > 0 ? km - 1 : 0];
             for (int k = 0; k < km; ++k) {
                 qa[k] = qq[k] * dz[k] / dza[k];
                 qr[k] = qa[k] / den[k];
                 if (emit_search_dbg) {
                     dbg_za[k] = za[k];
                     dbg_dza[k] = dza[k];
                     dbg_wi[k] = wi[k];
                     dbg_ww[k] = ww[k];
                     dbg_wa[k] = wa[k];
                     dbg_was[k] = was[k];
                     dbg_qa[k] = qa[k];
                 }
             }
             qa[km] = Real(0.0);
         };
         update_wind_and_state();
         if (iter > 0) {
             for (int k = 0; k < km; ++k) {
                 wsm6_slope_rain_cell(qr[k], den[k], denfac[k], pidn0r,
                                      WSM6::qcrmin,
                                      rslopermax, rsloperbmax, rsloper2max,
                                      rsloper3max, WSM6::bvtr, pvtr,
                                      tmp[k], tmp1[k], tmp2[k], tmp3[k], wa[k]);
             }
             for (int k = 0; k < km; ++k) {
                 ww[k] = Real(0.5) * (wd[k] + wa[k]);
                 was[k] = wa[k];
             }
             update_wind_and_state();
         }
         for (int k = 1; k < km; ++k) {
             const Real dip = (qa[k + 1] - qa[k]) / (dza[k + 1] + dza[k]);
             const Real dim = (qa[k] - qa[k - 1]) / (dza[k - 1] + dza[k]);
             if (dip * dim <= Real(0.0)) {
                 qmi[k] = qa[k];
                 qpi[k] = qa[k];
             } else {
                 qpi[k] = qa[k] + Real(0.5) * (dip + dim) * dza[k];
                 qmi[k] = Real(2.0) * qa[k] - qpi[k];
                 if (qpi[k] < Real(0.0) || qmi[k] < Real(0.0)) {
                     qpi[k] = qa[k];
                     qmi[k] = qa[k];
                 }
             }
             if (emit_search_dbg) {
                 dbg_qmi[k] = qmi[k];
                 dbg_qpi[k] = qpi[k];
             }
         }
         qpi[0] = qa[0];
         qmi[0] = qa[0];
         qmi[km] = qa[km];
         qpi[km] = qa[km];
         if (emit_search_dbg) {
             dbg_qmi[0] = qmi[0];
             dbg_qpi[0] = qpi[0];
         }
         for (int k = 0; k < km; ++k) {
             qn[k] = Real(0.0);
             if (emit_search_dbg) {
                 dbg_kb_before_backstep[k] = Real(-1.0);
                 dbg_kt_before_backstep[k] = Real(-1.0);
                 dbg_kb_after_backstep[k] = Real(-1.0);
                 dbg_kt_after_backstep[k] = Real(-1.0);
                 dbg_kb_after_search[k] = Real(-1.0);
                 dbg_kt_after_search[k] = Real(-1.0);
                 dbg_zsum[k] = Real(0.0);
                 dbg_qsum[k] = Real(0.0);
                 dbg_qn[k] = Real(0.0);
             }
         }
         int kb = 0;
         int kt = 0;
         for (int k = 0; k < km; ++k) {
             if (emit_search_dbg) {
                 dbg_kb_before_backstep[k] = Real(kb);
                 dbg_kt_before_backstep[k] = Real(kt);
             }
             kb = amrex::max(kb - 1, 0);
             kt = amrex::max(kt - 1, 0);
             if (emit_search_dbg) {
                 dbg_kb_after_backstep[k] = Real(kb);
                 dbg_kt_after_backstep[k] = Real(kt);
             }
             if (zi[k] >= za[km]) {
                 break;
             }
             for (int kk = kb; kk < km; ++kk) {
                 if (zi[k] <= za[kk + 1]) {
                     kb = kk;
                     break;
                 }
             }
             for (int kk = kt; kk < km; ++kk) {
                 if (zi[k + 1] <= za[kk]) {
                     kt = kk;
                     break;
                 }
             }
             kt = amrex::max(kt - 1, 0);
             if (emit_search_dbg) {
                 dbg_kb_after_search[k] = Real(kb);
                 dbg_kt_after_search[k] = Real(kt);
             }
             if (kt == kb) {
                 const Real tl = (zi[k] - za[kb]) / dza[kb];
                 const Real th = (zi[k + 1] - za[kb]) / dza[kb];
                 const Real tl2 = tl * tl;
                 const Real th2 = th * th;
                 const Real qqd = Real(0.5) * (qpi[kb] - qmi[kb]);
                 const Real qqh = qqd * th2 + qmi[kb] * th;
                 const Real qql = qqd * tl2 + qmi[kb] * tl;
                 qn[k] = (qqh - qql) / (th - tl);
                 if (emit_search_dbg) {
                     dbg_zsum[k] = dza[kb];
                     dbg_qsum[k] = qn[k] * dza[kb];
                 }
             } else if (kt > kb) {
                 const Real tl = (zi[k] - za[kb]) / dza[kb];
                 const Real tl2 = tl * tl;
                 const Real qqd = Real(0.5) * (qpi[kb] - qmi[kb]);
                 const Real qql = qqd * tl2 + qmi[kb] * tl;
                 const Real dql = qa[kb] - qql;
                 Real zsum = (Real(1.0) - tl) * dza[kb];
                 Real qsum = dql * dza[kb];
                 if (kt - kb > 1) {
                     for (int m = kb + 1; m < kt; ++m) {
                         zsum += dza[m];
                         qsum += qa[m] * dza[m];
                     }
                 }
                 const Real th = (zi[k + 1] - za[kt]) / dza[kt];
                 const Real th2 = th * th;
                 const Real dqh = Real(0.5) * (qpi[kt] - qmi[kt]) * th2 + qmi[kt] * th;
                 zsum += th * dza[kt];
                 qsum += dqh * dza[kt];
                 qn[k] = qsum / zsum;
                 if (emit_search_dbg) {
                     dbg_zsum[k] = zsum;
                     dbg_qsum[k] = qsum;
                 }
             }
             if (emit_search_dbg) {
                 dbg_qn[k] = qn[k];
             }
         }
         for (int k = 0; k < km; ++k) {
             if (za[k] < Real(0.0) && za[k + 1] < Real(0.0)) {
                 precip[i] += qa[k] * dza[k];
             } else if (za[k] < Real(0.0) && za[k + 1] >= Real(0.0)) {
                 precip[i] += qa[k] * (Real(0.0) - za[k]);
                 break;
             } else {
                 break;
             }
         }
         for (int k = 0; k < km; ++k) {
             rql[i * km + k] = qn[k];
             wwl[i * km + k] = ww[k];
             if (emit_search_dbg) {
                 dbg_denqrs1_after_kernel[k] = qn[k];
             }
         }
     }
 }
Referenced by WSM6::Advance().
wsm6_nislfv_rain_plm6()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_nislfv_rain_plm6 (int im, int km, const Real * denl, const Real * denfacl, const Real * tkl, const Real * dzl, Real * wwl, Real * rql, Real * rql2, Real * precip1, Real * precip2, Real dt, int id, int iter)
 {
     static_cast<void>(id);
     if (km > WSM6_MAX_LEVELS) return;
     constexpr Real pi = Real(3.141592653589793238462643383279502884);
     auto rgmma = [](Real x) -> Real {
         if (x == Real(1.0)) return Real(0.0);
         constexpr Real euler = Real(0.577215664901532);
         Real rg = x * std::exp(euler * x);
         for (int ii = 1; ii <= 10000; ++ii) {
             const Real y = static_cast<Real>(ii);
             rg = rg * (Real(1.0) + x / y) * std::exp(-x / y);
         }
         return Real(1.0) / rg;
     };
     // Match Fortran mp_wsm6_init graupel-mode coefficient definitions.
     const Real dens = WSM6::dens_snow;
     const Real n0g = Real(4.0e6);
     const Real deng = Real(500.0);
     const Real avtg = Real(330.0);
     const Real bvtg = Real(0.8);
     const Real lamdagmax = Real(6.0e4);
     const Real pidn0s = pi * dens * WSM6::n0s;
     const Real pidn0g = pi * deng * n0g;
     const Real rslopesmax = Real(1.0) / WSM6::lamdasmax;
     const Real rslopesbmax = std::pow(rslopesmax, WSM6::bvts);
     const Real rslopes2max = rslopesmax * rslopesmax;
     const Real rslopes3max = rslopes2max * rslopesmax;
     const Real rslopegmax = Real(1.0) / lamdagmax;
     const Real rslopegbmax = std::pow(rslopegmax, bvtg);
     const Real rslopeg2max = rslopegmax * rslopegmax;
     const Real rslopeg3max = rslopeg2max * rslopegmax;
     const Real pvts = WSM6::avts * rgmma(Real(4.0) + WSM6::bvts) / Real(6.0);
     const Real pvtg = avtg * rgmma(Real(4.0) + bvtg) / Real(6.0);
     for (int i = 0; i < im; ++i) {
         Real dz[WSM6_MAX_LEVELS];
         Real ww[WSM6_MAX_LEVELS];
         Real qq[WSM6_MAX_LEVELS];
         Real qq2[WSM6_MAX_LEVELS];
         Real wd[WSM6_MAX_LEVELS];
         Real wa[WSM6_MAX_LEVELS];
         Real wa2[WSM6_MAX_LEVELS];
         Real was[WSM6_MAX_LEVELS];
         Real den[WSM6_MAX_LEVELS];
         Real denfac[WSM6_MAX_LEVELS];
         Real tk[WSM6_MAX_LEVELS];
         Real qn[WSM6_MAX_LEVELS];
         Real qn2[WSM6_MAX_LEVELS];
         Real qr[WSM6_MAX_LEVELS];
         Real qr2[WSM6_MAX_LEVELS];
         Real tmp[WSM6_MAX_LEVELS];
         Real tmp1[WSM6_MAX_LEVELS];
         Real tmp2[WSM6_MAX_LEVELS];
         Real tmp3[WSM6_MAX_LEVELS];
         Real wi[WSM6_MAX_LEVELS + 1];
         Real zi[WSM6_MAX_LEVELS + 1];
         Real za[WSM6_MAX_LEVELS + 1];
         Real dza[WSM6_MAX_LEVELS + 1];
         Real qa[WSM6_MAX_LEVELS + 1];
         Real qa2[WSM6_MAX_LEVELS + 1];
         Real qmi[WSM6_MAX_LEVELS + 1];
         Real qpi[WSM6_MAX_LEVELS + 1];
         Real allold = Real(0.0);
         for (int k = 0; k < km; ++k) {
             const int idx = i * km + k;
             dz[k] = dzl[idx];
             qq[k] = rql[idx];
             qq2[k] = rql2[idx];
             ww[k] = wwl[idx];
             wd[k] = ww[k];
             den[k] = denl[idx];
             denfac[k] = denfacl[idx];
             tk[k] = tkl[idx];
             allold += qq[k] + qq2[k];
         }
         precip1[i] = Real(0.0);
         precip2[i] = Real(0.0);
         if (allold <= Real(0.0)) {
             continue;
         }
         zi[0] = Real(0.0);
         for (int k = 0; k < km; ++k) {
             zi[k + 1] = zi[k] + dz[k];
         }
         auto update_wind_and_state = [&](void) {
             wi[0] = ww[0];
             wi[km] = ww[km - 1];
             for (int k = 1; k < km; ++k) {
                 wi[k] = (ww[k] * dz[k - 1] + ww[k - 1] * dz[k]) / (dz[k - 1] + dz[k]);
             }
             wi[0] = ww[0];
             wi[1] = Real(0.5) * (ww[1] + ww[0]);
             for (int k = 2; k < km - 1; ++k) {
                 wi[k] = Real(9.0) / Real(16.0) * (ww[k] + ww[k - 1])
                       - Real(1.0) / Real(16.0) * (ww[k + 1] + ww[k - 2]);
             }
             if (km > 1) {
                 wi[km - 1] = Real(0.5) * (ww[km - 1] + ww[km - 2]);
                 wi[km] = ww[km - 1];
             }
             for (int k = 1; k < km; ++k) {
                 if (ww[k] == Real(0.0)) wi[k] = ww[k - 1];
             }
             const Real con1 = Real(0.05);
             for (int k = km - 1; k >= 0; --k) {
                 const Real decfl = (wi[k + 1] - wi[k]) * dt / dz[k];
                 if (decfl > con1) {
                     wi[k] = wi[k + 1] - con1 * dz[k] / dt;
                 }
             }
             for (int k = 0; k <= km; ++k) {
                 za[k] = zi[k] - wi[k] * dt;
             }
             for (int k = 0; k < km; ++k) {
                 dza[k] = za[k + 1] - za[k];
                 if (dza[k] <= Real(0.0)) dza[k] = dz[k]; // divergence guard
             }
             dza[km] = zi[km] - za[km]; // Fortran: dza(km+1) = zi(km+1)-za(km+1)
             if (dza[km] <= Real(0.0)) dza[km] = dz[km > 0 ? km - 1 : 0];
             for (int k = 0; k < km; ++k) {
                 qa[k] = qq[k] * dz[k] / dza[k];
                 qa2[k] = qq2[k] * dz[k] / dza[k];
                 qr[k] = qa[k] / den[k];
                 qr2[k] = qa2[k] / den[k];
             }
             qa[km] = Real(0.0);
             qa2[km] = Real(0.0);
         };
         update_wind_and_state();
         if (iter > 0) {
             Real n0sfac_dummy;
             for (int k = 0; k < km; ++k) {
                 wsm6_slope_snow_cell(qr[k], den[k], denfac[k], tk[k], pidn0s,
                                      Real(0.12), Real(1.0e11), Real(2.0e6),
                                      Real(273.15), Real(WSM6::qcrmin),
                                      rslopesmax, rslopesbmax, rslopes2max,
                                      rslopes3max, WSM6::bvts, pvts,
                                      tmp[k], tmp1[k], tmp2[k], tmp3[k],
                                      wa[k], n0sfac_dummy);
                 wsm6_slope_graup_cell(qr2[k], den[k], denfac[k], pidn0g,
                                       Real(WSM6::qcrmin), rslopegmax,
                                       rslopegbmax, rslopeg2max, rslopeg3max,
                                       Real(0.8), pvtg,
                                       tmp[k], tmp1[k], tmp2[k], tmp3[k],
                                       wa2[k]);
             }
             for (int k = 0; k < km; ++k) {
                 const Real tmpq = amrex::max(qr[k] + qr2[k], Real(1.0e-15));
                 if (tmpq > Real(1.0e-15)) {
                     wa[k] = (wa[k] * qr[k] + wa2[k] * qr2[k]) / tmpq;
                 } else {
                     wa[k] = Real(0.0);
                 }
             }
             for (int k = 0; k < km; ++k) {
                 ww[k] = Real(0.5) * (wd[k] + wa[k]);
                 was[k] = wa[k];
             }
             update_wind_and_state();
         }
         for (int ist = 0; ist < 2; ++ist) {
             Real* qn_dst = (ist == 0) ? qn : qn2;
             Real* precip_dst = (ist == 0) ? &precip1[i] : &precip2[i];
             Real* qasrc = (ist == 0) ? qa : qa2;
             for (int k = 1; k < km; ++k) {
                 const Real dip = (qasrc[k + 1] - qasrc[k]) / (dza[k + 1] + dza[k]);
                 const Real dim = (qasrc[k] - qasrc[k - 1]) / (dza[k - 1] + dza[k]);
                 if (dip * dim <= Real(0.0)) {
                     qmi[k] = qasrc[k];
                     qpi[k] = qasrc[k];
                 } else {
                     qpi[k] = qasrc[k] + Real(0.5) * (dip + dim) * dza[k];
                     qmi[k] = Real(2.0) * qasrc[k] - qpi[k];
                     if (qpi[k] < Real(0.0) || qmi[k] < Real(0.0)) {
                         qpi[k] = qasrc[k];
                         qmi[k] = qasrc[k];
                     }
                 }
             }
             qpi[0] = qasrc[0];
             qmi[0] = qasrc[0];
             qmi[km] = qasrc[km];
             qpi[km] = qasrc[km];
             for (int k = 0; k < km; ++k) {
                 qn_dst[k] = Real(0.0);
             }
             int kb = 0;
             int kt = 0;
             for (int k = 0; k < km; ++k) {
                 if (zi[k] >= za[km]) {
                     break;
                 }
                 for (int kk = kb; kk < km; ++kk) {
                     if (zi[k] <= za[kk + 1]) {
                         kb = kk;
                         break;
                     }
                 }
                 for (int kk = kt; kk < km; ++kk) {
                     if (zi[k + 1] <= za[kk]) {
                         kt = kk;
                         break;
                     }
                 }
                 kt = amrex::max(kt - 1, 0);
                 if (kt == kb) {
                     const Real tl = (zi[k] - za[kb]) / dza[kb];
                     const Real th = (zi[k + 1] - za[kb]) / dza[kb];
                     const Real tl2 = tl * tl;
                     const Real th2 = th * th;
                     const Real qqd = Real(0.5) * (qpi[kb] - qmi[kb]);
                     const Real qqh = qqd * th2 + qmi[kb] * th;
                     const Real qql = qqd * tl2 + qmi[kb] * tl;
                     qn_dst[k] = (qqh - qql) / (th - tl);
                 } else if (kt > kb) {
                     const Real tl = (zi[k] - za[kb]) / dza[kb];
                     const Real tl2 = tl * tl;
                     const Real qqd = Real(0.5) * (qpi[kb] - qmi[kb]);
                     const Real qql = qqd * tl2 + qmi[kb] * tl;
                     const Real dql = qasrc[kb] - qql;
                     Real zsum = (Real(1.0) - tl) * dza[kb];
                     Real qsum = dql * dza[kb];
                     if (kt - kb > 1) {
                         for (int m = kb + 1; m < kt; ++m) {
                             zsum += dza[m];
                             qsum += qasrc[m] * dza[m];
                         }
                     }
                     const Real th = (zi[k + 1] - za[kt]) / dza[kt];
                     const Real th2 = th * th;
                     const Real dqh = Real(0.5) * (qpi[kt] - qmi[kt]) * th2 + qmi[kt] * th;
                     zsum += th * dza[kt];
                     qsum += dqh * dza[kt];
                     qn_dst[k] = qsum / zsum;
                 }
             }
             Real precip = Real(0.0);
             for (int k = 0; k < km; ++k) {
                 if (za[k] < Real(0.0) && za[k + 1] < Real(0.0)) {
                     precip += qasrc[k] * dza[k];
                 } else if (za[k] < Real(0.0) && za[k + 1] >= Real(0.0)) {
                     precip += qasrc[k] * (Real(0.0) - za[k]);
                     break;
                 } else {
                     break;
                 }
             }
             *precip_dst = precip;
         }
         for (int k = 0; k < km; ++k) {
             rql[i * km + k] = qn[k];
             rql2[i * km + k] = qn2[k];
             wwl[i * km + k] = ww[k];
         }
     }
 }
Referenced by WSM6::Advance().
wsm6_slope_graup_cell()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_slope_graup_cell (Real qg, Real den, Real denfac, Real pidn0g_arg, Real qcrmin_arg, Real rslopegmax_arg, Real rslopegbmax_arg, Real rslopeg2max_arg, Real rslopeg3max_arg, Real bvtg_arg, Real pvtg_arg, Real & rslope, Real & rslopeb, Real & rslope2, Real & rslope3, Real & vt)
 {
     if (qg <= qcrmin_arg) {
         rslope  = rslopegmax_arg;
         rslopeb = rslopegbmax_arg;
         rslope2 = rslopeg2max_arg;
         rslope3 = rslopeg3max_arg;
     } else {
         rslope  = Real(1.0)/wsm6_lamdag(qg,den,pidn0g_arg);
         rslopeb = std::pow(rslope,bvtg_arg);
         rslope2 = rslope*rslope;
         rslope3 = rslope2*rslope;
     }
     vt = pvtg_arg*rslopeb*denfac;
     if (qg <= Real(0.0)) vt = Real(0.0);
 }
Referenced by WSM6::Advance(), and wsm6_nislfv_rain_plm6().
wsm6_slope_rain_cell()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_slope_rain_cell (Real qr, Real den, Real denfac, Real pidn0r_arg, Real qcrmin_arg, Real rslopermax_arg, Real rsloperbmax_arg, Real rsloper2max_arg, Real rsloper3max_arg, Real bvtr_arg, Real pvtr_arg, Real & rslope, Real & rslopeb, Real & rslope2, Real & rslope3, Real & vt)
 {
     if (qr <= qcrmin_arg) {
         rslope  = rslopermax_arg;
         rslopeb = rsloperbmax_arg;
         rslope2 = rsloper2max_arg;
         rslope3 = rsloper3max_arg;
     } else {
         rslope  = Real(1.0)/wsm6_lamdar(qr,den,pidn0r_arg);
         rslopeb = std::pow(rslope,bvtr_arg);
         rslope2 = rslope*rslope;
         rslope3 = rslope2*rslope;
     }
     vt = pvtr_arg*rslopeb*denfac;
     if (qr <= Real(0.0)) vt = Real(0.0);
 }
Referenced by WSM6::Advance(), and wsm6_nislfv_rain_plm().
wsm6_slope_snow_cell()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void wsm6_slope_snow_cell (Real qs, Real den, Real denfac, Real t, Real pidn0s_arg, Real alpha_arg, Real n0smax_arg, Real n0s_arg, Real t0c_arg, Real qcrmin_arg, Real rslopesmax_arg, Real rslopesbmax_arg, Real rslopes2max_arg, Real rslopes3max_arg, Real bvts_arg, Real pvts_arg, Real & rslope, Real & rslopeb, Real & rslope2, Real & rslope3, Real & vt, Real & n0sfac)
 {
     Real supcol = t0c_arg - t;
     n0sfac = amrex::max(amrex::min(std::exp(alpha_arg*supcol),
                                     n0smax_arg/n0s_arg), Real(1.0));
     if (qs <= qcrmin_arg) {
         rslope  = rslopesmax_arg;
         rslopeb = rslopesbmax_arg;
         rslope2 = rslopes2max_arg;
         rslope3 = rslopes3max_arg;
     } else {
         rslope  = Real(1.0)/wsm6_lamdas(qs,den,n0sfac,pidn0s_arg);
         rslopeb = std::pow(rslope,bvts_arg);
         rslope2 = rslope*rslope;
         rslope3 = rslope2*rslope;
     }
     vt = pvts_arg*rslopeb*denfac;
     if (qs <= Real(0.0)) vt = Real(0.0);
 }
Referenced by WSM6::Advance(), and wsm6_nislfv_rain_plm6().
wsm6_venfac()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_venfac (Real a, Real b, Real c, Real den0_arg)
{
     return std::exp(std::log(wsm6_viscos(b,c)/wsm6_diffus(b,a))
                    *Real(0.3333333))
           /std::sqrt(wsm6_viscos(b,c))
           *std::sqrt(std::sqrt(den0_arg/c));
 }
Referenced by WSM6::Advance().
wsm6_viscos()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_viscos (Real x, Real y)
{
     return Real(1.496e-6)*(x*std::sqrt(x))/(x+Real(120.0))/y;
 }
Referenced by wsm6_venfac(), and wsm6_xka().
wsm6_xka()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_xka (Real x, Real y)
{
     return Real(1.414e3)*wsm6_viscos(x,y)*y;
 }
Referenced by wsm6_diffac().
wsm6_xlcal()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE Real wsm6_xlcal (Real x, Real xlv0_arg, Real xlv1_arg, Real t0c_arg)
{
     return xlv0_arg - xlv1_arg*(x - t0c_arg);
 }
Referenced by WSM6::Advance().