ERF: Source/Prob/ERF_InitCustomPert_MultiSpeciesBubble.H File Reference
ERF_InitCustomPert_MultiSpeciesBubble.H File Reference
Functions
ParmParse pp_prob ("prob")
pp_prob query ("T_0", T_0)
pp_prob query ("x_c", x_c)
pp_prob query ("y_c", y_c)
pp_prob query ("z_c", z_c)
pp_prob query ("x_r", x_r)
pp_prob query ("y_r", y_r)
pp_prob query ("z_r", z_r)
pp_prob query ("T_pert", T_pert)
pp_prob query ("T_pert_is_airtemp", T_pert_is_airtemp)
pp_prob query ("perturb_rho", perturb_rho)
pp_prob query ("do_moist_bubble", do_moist_bubble)
pp_prob query ("theta_pert", theta_pert)
pp_prob query ("eq_pot_temp", eq_pot_temp)
pp_prob query ("qt_init", qt_init)
pp_prob query ("use_empircal_psat", use_empirical)
m_species clear ()
ParmParse pp_sdm ("super_droplets_moisture")
if (pp_sdm.contains(species_input.c_str()))
for (int i=0;i< m_num_species;i++)
AMREX_ALWAYS_ASSERT (sc.moisture_type==MoistureType::SuperDroplets)
if (T_0<=0)
if (do_moist_bubble)
AMREX_ALWAYS_ASSERT (n_sp *m_ncomp_per_species==ncomp_species)
Gpu::DeviceVector< Real > qv_init_d (n_sp)
ParallelFor (bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const auto prob_lo=geomdata.ProbLo();const auto dx=geomdata.CellSize();const Real x=prob_lo[0]+(i+myhalf) *dx[0];const Real y=prob_lo[1]+(j+myhalf) *dx[1];const Real z=prob_lo[2]+(k+myhalf) *dx[2];amrex::Real L=zero;if(x_r > 0) L+=std::pow((x - x_c)/x_r, 2);if(y_r > 0) L+=std::pow((y - y_c)/y_r, 2);if(z_r > 0) L+=std::pow((z - z_c)/z_r, 2);L=std::sqrt(L);if(L< one) { auto rho=state(i, j, k, Rho_comp)+state_pert(i, j, k, Rho_comp);for(int ns=0;ns< n_sp;ns++) { state_pert(i, j, k, nstart+2 *ns)=rho *qv_arr[ns];state_pert(i, j, k, nstart+2 *ns+1)=zero;} } })
Variables
Real T_0 = amrex::Real(300.0)
Real x_c = zero
Real y_c = zero
Real z_c = zero
Real x_r = zero
Real y_r = zero
Real z_r = zero
Real T_pert = -amrex::Real(15.0)
bool T_pert_is_airtemp = true
bool perturb_rho = true
bool do_moist_bubble = false
Real theta_pert = two
Real eq_pot_temp = amrex::Real(320.0)
Real qt_init = amrex::Real(0.02)
bool use_empirical = false
std::vector< std::string > m_species
int m_num_species = 0
const int m_ncomp_per_species = 2
const int m_nstart_sp = RhoQ3_comp+1
std::string species_input = "species"
std::vector< amrex::Real > m_qv_init_species = std::vector<amrex::Real>(m_num_species,zero)
const auto khi = geomdata.Domain().bigEnd()[2]
const Real dz = geomdata.CellSize()[2]
const Real rdOcp = sc.rdOcp
else
auto n_sp = m_num_species
auto nstart = m_nstart_sp
int ncomp_species = state_pert.nComp() - nstart
auto qv_arr = qv_init_d.data()
Function Documentation
AMREX_ALWAYS_ASSERT() [1/2]
AMREX_ALWAYS_ASSERT (n_sp * m_ncomp_per_species = =ncomp_species)
AMREX_ALWAYS_ASSERT() [2/2]
AMREX_ALWAYS_ASSERT (sc. moisture_type = =MoistureType::SuperDroplets)
clear()
m_species clear ()
for()
for ()
{
         std::string key_str = "qv_init_" + m_species[i];
         pp_prob.query(key_str.c_str(), m_qv_init_species[i]);
     }
Referenced by ComputeTurbulentViscosity(), derived::erf_dermaxreflectivity(), and fine_compute_interior_ghost_rhs().
if() [1/3]
if (do_moist_bubble)
{
         Vector<Real> h_r(khi+2);
         Vector<Real> h_p(khi+2);
         Vector<Real> h_t(khi+2);
         Vector<Real> h_q_v(khi+2);
         Gpu::DeviceVector<Real> d_r(khi+2);
         Gpu::DeviceVector<Real> d_p(khi+2);
         Gpu::DeviceVector<Real> d_t(khi+2);
         Gpu::DeviceVector<Real> d_q_v(khi+2);
         HSEutils::init_isentropic_hse_no_terrain(h_t.data(), h_r.data(), h_p.data(),
                                                  h_q_v.data(), dz, khi, qt_init, eq_pot_temp, use_empirical);
         Gpu::copy(Gpu::hostToDevice, h_r.begin(), h_r.end(), d_r.begin());
         Gpu::copy(Gpu::hostToDevice, h_p.begin(), h_p.end(), d_p.begin());
         Gpu::copy(Gpu::hostToDevice, h_t.begin(), h_t.end(), d_t.begin());
         Gpu::copy(Gpu::hostToDevice, h_q_v.begin(), h_q_v.end(), d_q_v.begin());
         Real* theta_back   = d_t.data();
         Real* p_back   = d_p.data();
         Real* q_v_back = d_q_v.data();
         int which_zone = -1;
         ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k)
         {
             // Geometry (note we must include these here to get the data on device)
             const auto prob_lo         = geomdata.ProbLo();
             const auto dx              = geomdata.CellSize();
             const auto x = prob_lo[0] + (i + myhalf) * dx[0];
             const auto y = prob_lo[1] + (j + myhalf) * dx[1];
             const auto z = prob_lo[2] + (k + myhalf) * dx[2];
             Real rad, delta_theta, theta_total, rho, RH;
             // Introduce the warm bubble.
             // Assume that the bubble is pressure matched with the background
             rad = zero;
             if (x_r > 0) rad += std::pow((x - x_c)/x_r, 2);
             if (y_r > 0) rad += std::pow((y - y_c)/y_r, 2);
             if (z_r > 0) rad += std::pow((z - z_c)/z_r, 2);
             rad = std::sqrt(rad);
             if (rad <= one){
                 delta_theta = theta_pert*std::pow(cos(PI*rad/two),2);
             } else {
                 delta_theta = zero;
             }
             theta_total  = theta_back[k]*(delta_theta/amrex::Real(300.0) + 1);
             Real T = getTgivenPandTh(p_back[k], theta_total, (R_d/Cp_d));
             rho    = p_back[k]/(R_d*T*(one + (R_v/R_d)*q_v_back[k]));
             RH     = one; // compute_relative_humidity();
             Real q_v_hot = HSEutils::vapor_mixing_ratio(p_back[k], T, RH, use_empirical, which_zone);
             // Compute background quantities
             Real T_back   = getTgivenPandTh(p_back[k], theta_back[k], (R_d/Cp_d));
             Real rho_back = p_back[k]/(R_d*T_back*(one + (R_v/R_d)*q_v_back[k]));
             // This version perturbs rho but not p
             state_pert(i, j, k, RhoTheta_comp) = rho*theta_total - rho_back*theta_back[k]*(one + (R_v/R_d)*q_v_back[k]);
             state_pert(i, j, k, Rho_comp)      = rho - rho_back*(one + qt_init);
             // mean states
             state_pert(i, j, k, RhoQ1_comp) = rho*q_v_hot;
         });
     } else {
if() [2/3]
if (pp_sdm. containsspecies_input.c_str())
{
         int num_species = pp_sdm.countval(species_input.c_str());
         std::string sp_name;
         for (int i = 0; i < num_species; i++) {
             pp_sdm.get(species_input.c_str(), sp_name, i);
             m_species.push_back(sp_name);
         }
     }
if() [3/3]
if (T_0<= 0)
     {
         amrex::Print() << "Ignoring T_0 = " << T_0
                        << ", background fields should have been initialized with erf.init_type"
                        << std::endl;
     }
ParallelFor()
ParallelFor (bx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const auto prob_lo=geomdata.ProbLo();const auto dx=geomdata.CellSize();const Real x=prob_lo[0]+(i+myhalf) *dx[0];const Real y=prob_lo[1]+(j+myhalf) *dx[1];const Real z=prob_lo[2]+(k+myhalf) *dx[2];amrex::Real L=zero;if(x_r > 0) L+=std::pow((x - x_c)/x_r, 2);if(y_r > 0) L+=std::pow((y - y_c)/y_r, 2);if(z_r > 0) L+=std::pow((z - z_c)/z_r, 2);L=std::sqrt(L);if(L< one) { auto rho=state(i, j, k, Rho_comp)+state_pert(i, j, k, Rho_comp);for(int ns=0;ns< n_sp;ns++) { state_pert(i, j, k, nstart+2 *ns)=rho *qv_arr[ns];state_pert(i, j, k, nstart+2 *ns+1)=zero;} } })
Referenced by if().
pp_prob()
ParmParse pp_prob ("prob")
Referenced by for().
pp_sdm()
ParmParse pp_sdm ("super_droplets_moisture")
Referenced by if().
query() [1/15]
pp_prob query ("do_moist_bubble" , do_moist_bubble)
query() [2/15]
pp_prob query ("eq_pot_temp" , eq_pot_temp)
query() [3/15]
pp_prob query ("perturb_rho" , perturb_rho)
query() [4/15]
pp_prob query ("qt_init" , qt_init)
query() [5/15]
pp_prob query ("T_0" , T_0)
query() [6/15]
pp_prob query ("T_pert" , T_pert)
query() [7/15]
pp_prob query ("T_pert_is_airtemp" , T_pert_is_airtemp)
query() [8/15]
pp_prob query ("theta_pert" , theta_pert)
query() [9/15]
pp_prob query ("use_empircal_psat" , use_empirical)
query() [10/15]
pp_prob query ("x_c" , x_c)
query() [11/15]
pp_prob query ("x_r" , x_r)
query() [12/15]
pp_prob query ("y_c" , y_c)
query() [13/15]
pp_prob query ("y_r" , y_r)
query() [14/15]
pp_prob query ("z_c" , z_c)
query() [15/15]
pp_prob query ("z_r" , z_r)
qv_init_d()
Gpu::DeviceVector<Real> qv_init_d (n_sp)
Variable Documentation
do_moist_bubble
bool do_moist_bubble = false
dz
const Real dz = geomdata.CellSize()[2]
Referenced by if().
else
else
eq_pot_temp
Real eq_pot_temp = amrex::Real(320.0)
Referenced by HSEutils::compute_F(), HSEutils::compute_F_for_temp(), HSEutils::compute_p_k(), HSEutils::compute_rho(), HSEutils::compute_temperature(), erf_init_dens_hse_moist(), if(), and HSEutils::init_isentropic_hse_no_terrain().
khi
const auto khi = geomdata.Domain().bigEnd()[2]
Referenced by if().
m_ncomp_per_species
const int m_ncomp_per_species = 2
m_nstart_sp
const int m_nstart_sp = RhoQ3_comp+1
m_num_species
m_num_species = 0
m_qv_init_species
std::vector<amrex::Real> m_qv_init_species = std::vector<amrex::Real>(m_num_species,zero)
Referenced by for().
m_species
std::vector<std::string> m_species
Referenced by for(), and if().
n_sp
auto n_sp = m_num_species
Referenced by ParallelFor().
ncomp_species
int ncomp_species = state_pert.nComp() - nstart
nstart
auto nstart = m_nstart_sp
Referenced by ParallelFor().
perturb_rho
bool perturb_rho = true
qt_init
Real qt_init = amrex::Real(0.02)
Referenced by if().
qv_arr
auto qv_arr = qv_init_d.data()
Referenced by Morrison::Advance(), WSM6::Advance(), Kessler::Copy_Micro_to_State(), Morrison::Copy_Micro_to_State(), SAM::Copy_Micro_to_State(), SatAdj::Copy_Micro_to_State(), and ParallelFor().
rdOcp
const Real rdOcp = sc.rdOcp
species_input
std::string species_input = "species"
Referenced by if().
T_0
Real T_0 = amrex::Real(300.0)
Referenced by if().
T_pert
Real T_pert = -amrex::Real(15.0)
T_pert_is_airtemp
bool T_pert_is_airtemp = true
theta_pert
Real theta_pert = two
Referenced by if().
use_empirical
bool use_empirical = false
Referenced by HSEutils::compute_F(), HSEutils::compute_F_for_temp(), HSEutils::compute_p_k(), HSEutils::compute_relative_humidity(), HSEutils::compute_rho(), HSEutils::compute_saturation_pressure(), HSEutils::compute_temperature(), erf_esatw(), erf_init_dens_hse_moist(), if(), HSEutils::init_isentropic_hse_no_terrain(), and HSEutils::vapor_mixing_ratio().
x_c
Real x_c = zero
Referenced by if(), and ParallelFor().
x_r
Real x_r = zero
Referenced by if(), and ParallelFor().
y_c
Real y_c = zero
Referenced by if(), and ParallelFor().
y_r
Real y_r = zero
Referenced by if(), and ParallelFor().
z_c
Real z_c = zero
Referenced by if(), and ParallelFor().
z_r
Real z_r = zero
Referenced by if(), and ParallelFor().