ERF: Source/Prob/ERF_UpdateWSubsidence_SineMassFlux.H File Reference
ERF_UpdateWSubsidence_SineMassFlux.H File Reference
Functions
Gpu::DeviceVector< Real > rho_d (khi+1, zero)
for (MFIter mfi(state, TilingIfNotGPU());mfi.isValid();++mfi)
Vector< Real > rho_h (khi+1, zero)
Vector< Real > rho_stag (khi+2, zero)
for (int k=1;k<=khi;k++)
Variables
auto rho_arr = rho_d.data()
rho_stag [0] = amrex::Real(1.5)*rho_h[0] - myhalf*rho_h[1]
Function Documentation
for() [1/2]
for (int k = 1; k <= khi; k++)
{
         rho_stag[k] = myhalf*(rho_h[k-1]+rho_h[k]);
     }
for() [2/2]
for (MFIter mfi(state, TilingIfNotGPU());mfi.isValid();++ mfi)
{
         const auto &box = mfi.tilebox();
         auto state_arr = state.const_array(mfi);
         ParallelFor(box, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept {
             rho_arr[k] = state_arr(i, j, k, Rho_comp);
         });
     }
rho_d()
Gpu::DeviceVector<Real> rho_d (khi+ 1, zero)
Referenced by SAM::Compute_Coefficients(), and ERF::FillForecastStateMultiFabs().
rho_h()
Vector<Real> rho_h (khi+ 1, zero)
Referenced by SAM::Compute_Coefficients(), ERF::FillForecastStateMultiFabs(), for(), and ReadCustomBinaryIC().
rho_stag()
Vector<Real> rho_stag (khi+ 2, zero)
Variable Documentation
rho_arr
auto rho_arr = rho_d.data()
Referenced by Morrison::Advance(), Kessler::AdvanceKessler(), Kessler::Copy_Micro_to_State(), Morrison::Copy_Micro_to_State(), SAM::Copy_Micro_to_State(), SatAdj::Copy_Micro_to_State(), ShocDriver::debug_check_bad_column(), ERF::derive_stress_profiles(), ERF::derive_stress_profiles_stag(), ERF::erf_enforce_hse(), erf_init_dens_hse_dry(), ShocPreprocess::fill_columns(), fine_compute_interior_ghost_rhs(), for(), and rebalance_columns().
rho_stag
rho_stag[khi+1] = amrex::Real(1.5)*rho_h[0] - myhalf*rho_h[1]
Referenced by for().