ERF: Source/ERF_ProbCommon.H File Reference
ERF_ProbCommon.H File Reference
#include <AMReX_ParmParse.H>
#include <AMReX_Geometry.H>
#include <AMReX_FArrayBox.H>
#include <AMReX_MultiFab.H>
#include "ERF_DataStruct.H"
#include "ERF_EOS.H"
#include "ERF_HSEUtils.H"
#include "ERF_TileNoZ.H"
Classes
struct ProbParmDefaults
class ProblemBase
Functions
template<typename T >
T erf_get_single_value (std::istream &is, int n)
void init_my_custom_terrain (const amrex::Geometry &geom, amrex::FArrayBox &terrain_fab, const amrex::Real &time)
std::unique_ptr< ProblemBase > amrex_probinit (const amrex_real *problo, const amrex_real *probhi) AMREX_ATTRIBUTE_WEAK
Function Documentation
amrex_probinit()
std::unique_ptr<ProblemBase> amrex_probinit (const amrex_real * problo, const amrex_real * probhi)
Function to init the physical bounds of the domain and instantiate a Problem derived from ProblemBase
Referenced by ERF::ERF_shared().
erf_get_single_value()
template<typename T > T erf_get_single_value (std::istream & is, int n)
 {
   T r = 0;
   std::string line;
   if (std::getline(is, line)) {
     std::stringstream ss(line);
     ss >> r;
     if (ss.fail()) {
       amrex::Abort("Failed to read");
     }
     if (ss >> r) {
       amrex::Print() << "Trying to read line " << n << " in this file " << std::endl;
       amrex::Abort("Wrong format: more than one number in this line");
     }
   } else {
     amrex::Abort("Unable to read this line");
   }
   return r;
 }
init_my_custom_terrain()
void init_my_custom_terrain (const amrex::Geometry & geom, amrex::FArrayBox & terrain_fab, const amrex::Real & time)
Referenced by ProblemBase::init_buildings_surface(), ProblemBase::init_custom_terrain(), and ProblemBase::init_terrain_surface().