ERF: Source/SourceTerms/ERF_NumericalDiffusion.H File Reference
ERF_NumericalDiffusion.H File Reference
#include <AMReX.H>
#include <ERF_DataStruct.H>
#include <AMReX_MultiFab.H>
Functions
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real calc_fifth_order_deriv (const amrex::Real &dnp2, const amrex::Real &dnp1, const amrex::Real &dn, const amrex::Real &dnm1, const amrex::Real &dnm2, const amrex::Real &dnm3)
void NumericalDiffusion_Scal (const amrex::Box &bx, const int start_comp, const int num_comp, const amrex::Real dt, const amrex::Real num_diff_coeff, const amrex::Array4< const amrex::Real > &prim_data, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< amrex::Real > &rhs, const amrex::Array4< const amrex::Real > &mf)
void NumericalDiffusion_Xmom (const amrex::Box &bx, const amrex::Real dt, const amrex::Real num_diff_coeff, const amrex::Array4< const amrex::Real > &prim_data, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< amrex::Real > &rhs, const amrex::Array4< const amrex::Real > &mf)
void NumericalDiffusion_Ymom (const amrex::Box &bx, const amrex::Real dt, const amrex::Real num_diff_coeff, const amrex::Array4< const amrex::Real > &prim_data, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< amrex::Real > &rhs, const amrex::Array4< const amrex::Real > &mf)
Function Documentation
calc_fifth_order_deriv()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real calc_fifth_order_deriv (const amrex::Real & dnp2, const amrex::Real & dnp1, const amrex::Real & dn, const amrex::Real & dnm1, const amrex::Real & dnm2, const amrex::Real & dnm3)
 {
     amrex::Real interp = 10. * (dn   - dnm1)
                         - 5. * (dnp1 - dnm2)
                              + (dnp2 - dnm3);
     return interp;
 }
Referenced by NumericalDiffusion_Scal(), NumericalDiffusion_Xmom(), and NumericalDiffusion_Ymom().
NumericalDiffusion_Scal()
void NumericalDiffusion_Scal (const amrex::Box & bx, const int start_comp, const int num_comp, const amrex::Real dt, const amrex::Real num_diff_coeff, const amrex::Array4< const amrex::Real > & prim_data, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< amrex::Real > & rhs, const amrex::Array4< const amrex::Real > & mf)
NumericalDiffusion_Xmom()
void NumericalDiffusion_Xmom (const amrex::Box & bx, const amrex::Real dt, const amrex::Real num_diff_coeff, const amrex::Array4< const amrex::Real > & prim_data, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< amrex::Real > & rhs, const amrex::Array4< const amrex::Real > & mf)
NumericalDiffusion_Ymom()
void NumericalDiffusion_Ymom (const amrex::Box & bx, const amrex::Real dt, const amrex::Real num_diff_coeff, const amrex::Array4< const amrex::Real > & prim_data, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< amrex::Real > & rhs, const amrex::Array4< const amrex::Real > & mf)