ERF: Source/Prob/ERF_InitCustomPert_SquallLine.H File Reference
ERF_InitCustomPert_SquallLine.H File Reference
Functions
AMREX_ALWAYS_ASSERT (bx.length()[2]==khi+1)
Vector< Real > h_r (khi+2)
Vector< Real > h_p (khi+2)
Vector< Real > h_t (khi+2)
Vector< Real > h_q_v (khi+2)
Gpu::DeviceVector< Real > d_r (khi+2)
Gpu::DeviceVector< Real > d_p (khi+2)
Gpu::DeviceVector< Real > d_t (khi+2)
Gpu::DeviceVector< Real > d_q_v (khi+2)
ParmParse pp_prob ("prob")
pp_prob query ("qt_init", q_t)
pp_prob query ("eq_pot_temp", eq_pot_temp)
pp_prob query ("use_empirical_psat", use_empirical)
pp_prob query ("height", height)
pp_prob query ("z_tr", z_tr)
pp_prob query ("x_c", x_c)
pp_prob query ("z_c", z_c)
pp_prob query ("x_r", x_r)
pp_prob query ("z_r", z_r)
pp_prob query ("T_tr", T_tr)
pp_prob query ("theta_c", theta_c)
pp_prob query ("theta_0", theta_0)
pp_prob query ("theta_tr", theta_tr)
ParallelFor (bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const auto prob_lo=geomdata.ProbLo();const auto dx=geomdata.CellSize();const Real z=prob_lo[2]+(k+myhalf) *dx[2];const Real x=prob_lo[0]+(i+myhalf) *dx[0];Real rad, delta_theta, theta_total, temperature, rho, RH, scalar;Real scaled_height=z/z_tr;int which_zone=-1;if(z<=height) { which_zone=1;} else if(z<=z_tr) { which_zone=2;} else { which_zone=3;} rad=std::pow(std::pow((x - x_c)/x_r, 2)+std::pow((z - z_c)/z_r, 2), myhalf);if(rad<=r_c){ delta_theta=theta_c *std::pow(cos(PI *rad/two), 2);scalar=std::pow(cos(PI *rad/two), 2);} else{ delta_theta=zero;scalar=zero;} theta_total=t[k]+delta_theta;temperature=getTgivenPandTh(p[k], theta_total,(R_d/Cp_d));Real T_b=getTgivenPandTh(p[k], t[k],(R_d/Cp_d));RH=HSEutils::compute_relative_humidity(p[k], T_b, use_empirical, which_zone, scaled_height);Real q_v_hot;if(z< height) { q_v_hot=amrex::Real(0.014);} else { q_v_hot=HSEutils::vapor_mixing_ratio(p[k], T_b, RH, use_empirical, which_zone);} rho=p[k]/(R_d *temperature *(one+(R_v/R_d) *q_v_hot));Real temperature_back=getTgivenPandTh(p[k], t[k],(R_d/Cp_d));Real T_back=getTgivenPandTh(p[k], t[k],(R_d/Cp_d));Real RH_back=HSEutils::compute_relative_humidity(p[k], T_back, use_empirical, which_zone, scaled_height);Real q_v_back;if(z< height) { q_v_back=amrex::Real(0.014);} else { q_v_back=HSEutils::vapor_mixing_ratio(p[k], T_back, RH_back, use_empirical, which_zone);} Real rho_back=p[k]/(R_d *temperature_back *(one+(R_v/R_d) *q_v_back));state_pert(i, j, k, RhoTheta_comp)=rho *theta_total - rho_back *t[k] *(one+(R_v/R_d) *q_v_back);state_pert(i, j, k, Rho_comp)=rho - rho_back *(one+q_v_back);state_pert(i, j, k, RhoScalar_comp)=rho *scalar;if(use_moisture) { state_pert(i, j, k, RhoQ1_comp)=rho *q_v_hot;state_pert(i, j, k, RhoQ2_comp)=zero;} })
Variables
const bool use_moisture = (sc.moisture_type != MoistureType::None)
const int khi = geomdata.Domain().bigEnd()[2]
const Real & dz = geomdata.CellSize()[2]
Real q_t = amrex::Real(0.02)
Real eq_pot_temp = amrex::Real(320.0)
bool use_empirical = false
Real height = amrex::Real(1200.0)
Real z_tr = amrex::Real(12000.0)
Real x_c = zero
Real z_c = amrex::Real(1.5e3)
Real x_r = amrex::Real(4.0e3)
Real z_r = amrex::Real(1.5e3)
Real T_tr = amrex::Real(213.0)
Real theta_c = three
Real theta_0 = amrex::Real(300.0)
Real theta_tr = amrex::Real(343.0)
Real r_c = one
Real * t = d_t.data()
Real * p = d_p.data()
Function Documentation
AMREX_ALWAYS_ASSERT()
AMREX_ALWAYS_ASSERT (bx. length()[2] = =khi+1)
d_p()
Gpu::DeviceVector<Real> d_p (khi+ 2)
Referenced by erf_init_dens_hse(), and if().
d_q_v()
Gpu::DeviceVector<Real> d_q_v (khi+ 2)
Referenced by if().
d_r()
Gpu::DeviceVector<Real> d_r (khi+ 2)
Referenced by erf_init_dens_hse(), erf_init_dens_hse_moist(), and if().
d_t()
Gpu::DeviceVector<Real> d_t (khi+ 2)
Referenced by if().
h_p()
Vector<Real> h_p (khi+ 2)
Referenced by erf_init_dens_hse(), erf_init_dens_hse_moist(), and if().
h_q_v()
Vector<Real> h_q_v (khi+ 2)
Referenced by erf_init_dens_hse_moist(), and if().
h_r()
Vector<Real> h_r (khi+ 2)
Referenced by erf_init_dens_hse(), erf_init_dens_hse_moist(), and if().
h_t()
Vector<Real> h_t (khi+ 2)
Referenced by erf_init_dens_hse_moist(), and if().
ParallelFor()
ParallelFor (bx , [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept { const auto prob_lo=geomdata.ProbLo();const auto dx=geomdata.CellSize();const Real z=prob_lo[2]+(k+myhalf) *dx[2];const Real x=prob_lo[0]+(i+myhalf) *dx[0];Real rad, delta_theta, theta_total, temperature, rho, RH, scalar;Real scaled_height=z/z_tr;int which_zone=-1;if(z<=height) { which_zone=1;} else if(z<=z_tr) { which_zone=2;} else { which_zone=3;} rad=std::pow(std::pow((x - x_c)/x_r, 2)+std::pow((z - z_c)/z_r, 2), myhalf);if(rad<=r_c){ delta_theta=theta_c *std::pow(cos(PI *rad/two), 2);scalar=std::pow(cos(PI *rad/two), 2);} else{ delta_theta=zero;scalar=zero;} theta_total=t[k]+delta_theta;temperature=getTgivenPandTh(p[k], theta_total,(R_d/Cp_d));Real T_b=getTgivenPandTh(p[k], t[k],(R_d/Cp_d));RH=HSEutils::compute_relative_humidity(p[k], T_b, use_empirical, which_zone, scaled_height);Real q_v_hot;if(z< height) { q_v_hot=amrex::Real(0.014);} else { q_v_hot=HSEutils::vapor_mixing_ratio(p[k], T_b, RH, use_empirical, which_zone);} rho=p[k]/(R_d *temperature *(one+(R_v/R_d) *q_v_hot));Real temperature_back=getTgivenPandTh(p[k], t[k],(R_d/Cp_d));Real T_back=getTgivenPandTh(p[k], t[k],(R_d/Cp_d));Real RH_back=HSEutils::compute_relative_humidity(p[k], T_back, use_empirical, which_zone, scaled_height);Real q_v_back;if(z< height) { q_v_back=amrex::Real(0.014);} else { q_v_back=HSEutils::vapor_mixing_ratio(p[k], T_back, RH_back, use_empirical, which_zone);} Real rho_back=p[k]/(R_d *temperature_back *(one+(R_v/R_d) *q_v_back));state_pert(i, j, k, RhoTheta_comp)=rho *theta_total - rho_back *t[k] *(one+(R_v/R_d) *q_v_back);state_pert(i, j, k, Rho_comp)=rho - rho_back *(one+q_v_back);state_pert(i, j, k, RhoScalar_comp)=rho *scalar;if(use_moisture) { state_pert(i, j, k, RhoQ1_comp)=rho *q_v_hot;state_pert(i, j, k, RhoQ2_comp)=zero;} })
pp_prob()
ParmParse pp_prob ("prob")
query() [1/13]
pp_prob query ("eq_pot_temp" , eq_pot_temp)
query() [2/13]
pp_prob query ("height" , height)
query() [3/13]
pp_prob query ("qt_init" , q_t)
query() [4/13]
pp_prob query ("T_tr" , T_tr)
query() [5/13]
pp_prob query ("theta_0" , theta_0)
query() [6/13]
pp_prob query ("theta_c" , theta_c)
query() [7/13]
pp_prob query ("theta_tr" , theta_tr)
query() [8/13]
pp_prob query ("use_empirical_psat" , use_empirical)
query() [9/13]
pp_prob query ("x_c" , x_c)
query() [10/13]
pp_prob query ("x_r" , x_r)
query() [11/13]
pp_prob query ("z_c" , z_c)
query() [12/13]
pp_prob query ("z_r" , z_r)
query() [13/13]
pp_prob query ("z_tr" , z_tr)
Variable Documentation
dz
const Real& dz = geomdata.CellSize()[2]
eq_pot_temp
Real eq_pot_temp = amrex::Real(320.0)
height
Real height = amrex::Real(1200.0)
Referenced by init_my_custom_terrain(), and ParallelFor().
khi
const int khi = geomdata.Domain().bigEnd()[2]
p
Real* p = d_p.data()
Referenced by calc_p_isothermal(), ERF::cloud_fraction(), compute_gradp(), compute_gradp_interpz(), WaterVaporSat::deriv_outputs(), ERF::derive_diag_profiles(), ERF::derive_diag_profiles_stag(), erf_dtqsati(), erf_dtqsatw(), erf_init_dens_hse(), erf_qsati(), erf_qsatw(), WaterVaporSat::findsp(), getRhogivenTandPress(), getRhogivenThetaPress(), getRhoThetagivenP(), HSEutils::init_isentropic_hse(), HSEutils::init_isentropic_hse_no_terrain(), HSEutils::init_isentropic_hse_terrain(), ERF::Interpolation::interpolateFields(), make_gradp_pert(), TerrainIF::operator()(), ParallelFor(), WaterVaporSat::qsat(), WaterVaporSat::qsat_ice(), WaterVaporSat::qsat_water(), PlaneAverage::set_precision(), wrf_gamma(), ERF::Write3DPlotFile(), ERF::WriteLinePlot(), SatMethods::wv_sat_qsat_ice(), SatMethods::wv_sat_qsat_trans(), SatMethods::wv_sat_qsat_water(), and SatMethods::wv_sat_svp_to_qsat().
q_t
Real q_t = amrex::Real(0.02)
Referenced by HSEutils::compute_F(), HSEutils::compute_F_for_temp(), HSEutils::compute_p_k(), HSEutils::compute_rho(), HSEutils::compute_temperature(), erf_init_dens_hse_moist(), and HSEutils::init_isentropic_hse_no_terrain().
r_c
Real r_c = one
Referenced by ParallelFor().
t
Real* t = d_t.data()
Referenced by SatMethods::Bolton_svp_water(), WaterVaporSat::calc_hltalt(), WaterVaporSat::deriv_outputs(), erf_dtesati(), erf_dtesatw(), erf_dtesatw_cc(), erf_dtqsati(), erf_dtqsatw(), erf_esati(), erf_esatw(), erf_esatw_cc(), erf_qsati(), erf_qsatw(), WaterVaporSat::findsp(), SatMethods::GoffGratch_svp_ice(), SatMethods::GoffGratch_svp_water(), SatMethods::MurphyKoop_svp_ice(), SatMethods::MurphyKoop_svp_water(), WaterVaporSat::no_ip_hltalt(), SatMethods::OldGoffGratch_svp_ice(), SatMethods::OldGoffGratch_svp_water(), ParallelFor(), WaterVaporSat::qsat(), WaterVaporSat::qsat_ice(), WaterVaporSat::qsat_water(), WaterVaporSat::svp_ice(), WaterVaporSat::svp_trans(), WaterVaporSat::svp_water(), WaterVaporSat::tq_enthalpy(), SatMethods::wv_sat_qsat_ice(), SatMethods::wv_sat_qsat_trans(), SatMethods::wv_sat_qsat_water(), SatMethods::wv_sat_svp_ice(), SatMethods::wv_sat_svp_trans(), and SatMethods::wv_sat_svp_water().
T_tr
Real T_tr = amrex::Real(213.0)
Referenced by HSEutils::compute_F(), HSEutils::compute_p_k(), HSEutils::compute_rho(), HSEutils::compute_theta(), erf_init_dens_hse_moist(), and HSEutils::init_isentropic_hse_no_terrain().
theta_0
Real theta_0 = amrex::Real(300.0)
Referenced by HSEutils::compute_F(), HSEutils::compute_p_k(), HSEutils::compute_rho(), HSEutils::compute_theta(), erf_init_dens_hse_moist(), MM5::Init(), SLM::Init(), HSEutils::init_isentropic_hse_no_terrain(), and ParallelFor().
theta_c
Real theta_c = three
Referenced by ParallelFor().
theta_tr
Real theta_tr = amrex::Real(343.0)
Referenced by HSEutils::compute_F(), HSEutils::compute_p_k(), HSEutils::compute_rho(), HSEutils::compute_theta(), erf_init_dens_hse_moist(), and HSEutils::init_isentropic_hse_no_terrain().
use_empirical
bool use_empirical = false
Referenced by ParallelFor().
use_moisture
const bool use_moisture = (sc.moisture_type != MoistureType::None)
Referenced by ParallelFor().
x_c
Real x_c = zero
Referenced by ParallelFor().
x_r
Real x_r = amrex::Real(4.0e3)
Referenced by ParallelFor().
z_c
Real z_c = amrex::Real(1.5e3)
Referenced by ParallelFor().
z_r
Real z_r = amrex::Real(1.5e3)
Referenced by ParallelFor().
z_tr
Real z_tr = amrex::Real(12000.0)
Referenced by HSEutils::compute_F(), HSEutils::compute_p_k(), HSEutils::compute_rho(), HSEutils::compute_theta(), and ParallelFor().