var hierarchy =
[
    [ "ABLFieldInit", "structABLFieldInit.html", null ],
    [ "ABLMost", "structABLMost.html", null ],
    [ "math_bcs::ablmostwall< IDIR, Bound >", "structmath__bcs_1_1ablmostwall.html", null ],
    [ "math_bcs::ablmostwall< IDIR, BCBound::lower >", "structmath__bcs_1_1ablmostwall_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::ablmostwall< IDIR, BCBound::upper >", "structmath__bcs_1_1ablmostwall_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "phys_bcs::BCBase", "classphys__bcs_1_1BCBase.html", [
      [ "phys_bcs::BCDummy", "classphys__bcs_1_1BCDummy.html", null ],
      [ "phys_bcs::BCInterior", "classphys__bcs_1_1BCInterior.html", null ],
      [ "phys_bcs::BCMostWall< IDIR, Bound >", "classphys__bcs_1_1BCMostWall.html", null ],
      [ "phys_bcs::BCNoSlipWall< IDIR, Bound >", "classphys__bcs_1_1BCNoSlipWall.html", null ],
      [ "phys_bcs::BCOutflow< IDIR, Bound >", "classphys__bcs_1_1BCOutflow.html", null ],
      [ "phys_bcs::BCSimSlipWall< IDIR, Bound >", "classphys__bcs_1_1BCSimSlipWall.html", null ],
      [ "phys_bcs::BCSlipWall< IDIR, Bound >", "classphys__bcs_1_1BCSlipWall.html", null ]
    ] ],
    [ "DirectionSelector< Index >", "structDirectionSelector.html", null ],
    [ "DirectionSelector< 0 >", "structDirectionSelector_3_010_01_4.html", null ],
    [ "DirectionSelector< 1 >", "structDirectionSelector_3_011_01_4.html", null ],
    [ "DirectionSelector< 2 >", "structDirectionSelector_3_012_01_4.html", null ],
    [ "math_bcs::dirichlet< IDIR, Bound >", "structmath__bcs_1_1dirichlet.html", null ],
    [ "math_bcs::dirichlet< IDIR, BCBound::lower >", "structmath__bcs_1_1dirichlet_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::dirichlet< IDIR, BCBound::upper >", "structmath__bcs_1_1dirichlet_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "EmptyProbDeriveStruct", "structEmptyProbDeriveStruct.html", null ],
    [ "ERFHypFillExtDir", "structERFHypFillExtDir.html", null ],
    [ "FCFillExtDirDummy", "structFCFillExtDirDummy.html", null ],
    [ "GetViscosity", "structGetViscosity.html", null ],
    [ "IOManager", "classIOManager.html", null ],
    [ "LevelBld", null, [
      [ "ERFBld", "classERFBld.html", null ]
    ] ],
    [ "math_bcs::lin_extrap< IDIR, Bound >", "structmath__bcs_1_1lin__extrap.html", null ],
    [ "math_bcs::lin_extrap< IDIR, BCBound::lower >", "structmath__bcs_1_1lin__extrap_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::lin_extrap< IDIR, BCBound::upper >", "structmath__bcs_1_1lin__extrap_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "ncutils::NCDim", "structncutils_1_1NCDim.html", null ],
    [ "ncutils::NCDType", "structncutils_1_1NCDType.html", null ],
    [ "ncutils::NCGroup", "classncutils_1_1NCGroup.html", [
      [ "ncutils::NCFile", "classncutils_1_1NCFile.html", null ]
    ] ],
    [ "ncutils::NCVar", "structncutils_1_1NCVar.html", null ],
    [ "math_bcs::pc_extrap< IDIR, Bound >", "structmath__bcs_1_1pc__extrap.html", null ],
    [ "math_bcs::pc_extrap< IDIR, BCBound::lower >", "structmath__bcs_1_1pc__extrap_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::pc_extrap< IDIR, BCBound::upper >", "structmath__bcs_1_1pc__extrap_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "PlaneAverage", "classPlaneAverage.html", null ],
    [ "math_bcs::quad_extrap< IDIR, Bound >", "structmath__bcs_1_1quad__extrap.html", null ],
    [ "math_bcs::quad_extrap< IDIR, BCBound::lower >", "structmath__bcs_1_1quad__extrap_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::quad_extrap< IDIR, BCBound::upper >", "structmath__bcs_1_1quad__extrap_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "math_bcs::reflect_even< IDIR, Bound >", "structmath__bcs_1_1reflect__even.html", null ],
    [ "math_bcs::reflect_even< IDIR, BCBound::lower >", "structmath__bcs_1_1reflect__even_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::reflect_even< IDIR, BCBound::upper >", "structmath__bcs_1_1reflect__even_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "math_bcs::reflect_odd< IDIR, Bound >", "structmath__bcs_1_1reflect__odd.html", null ],
    [ "math_bcs::reflect_odd< IDIR, BCBound::lower >", "structmath__bcs_1_1reflect__odd_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::reflect_odd< IDIR, BCBound::upper >", "structmath__bcs_1_1reflect__odd_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "math_bcs::sim_bc< IDIR, Bound >", "structmath__bcs_1_1sim__bc.html", null ],
    [ "math_bcs::sim_bc< IDIR, BCBound::lower >", "structmath__bcs_1_1sim__bc_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::sim_bc< IDIR, BCBound::upper >", "structmath__bcs_1_1sim__bc_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ],
    [ "SolverChoice", "structSolverChoice.html", null ],
    [ "VelPlaneAverage", "classVelPlaneAverage.html", null ],
    [ "math_bcs::wall_scalars< IDIR, Bound >", "structmath__bcs_1_1wall__scalars.html", null ],
    [ "math_bcs::wall_scalars< IDIR, BCBound::lower >", "structmath__bcs_1_1wall__scalars_3_01IDIR_00_01BCBound_1_1lower_01_4.html", null ],
    [ "math_bcs::wall_scalars< IDIR, BCBound::upper >", "structmath__bcs_1_1wall__scalars_3_01IDIR_00_01BCBound_1_1upper_01_4.html", null ]
];