var hierarchy =
[
    [ "adiabatic", "structadiabatic.html", null ],
    [ "adiabatic_charnock", "structadiabatic__charnock.html", null ],
    [ "adiabatic_donelan", "structadiabatic__donelan.html", null ],
    [ "adiabatic_mod_charnock", "structadiabatic__mod__charnock.html", null ],
    [ "adiabatic_wave_coupled", "structadiabatic__wave__coupled.html", null ],
    [ "AdvChoice", "structAdvChoice.html", null ],
    [ "amrex::AmrCore", null, [
      [ "ERF", "classERF.html", null ]
    ] ],
    [ "SHOCInterface::Buffer", "structSHOCInterface_1_1Buffer.html", null ],
    [ "CENTERED2", "structCENTERED2.html", null ],
    [ "CENTERED4", "structCENTERED4.html", null ],
    [ "CENTERED6", "structCENTERED6.html", null ],
    [ "custom_flux", "structcustom__flux.html", null ],
    [ "DiffChoice", "structDiffChoice.html", null ],
    [ "DirectionSelector< Index >", "structDirectionSelector.html", null ],
    [ "DirectionSelector< 0 >", "structDirectionSelector_3_010_01_4.html", null ],
    [ "DirectionSelector< 1 >", "structDirectionSelector_3_011_01_4.html", null ],
    [ "DirectionSelector< 2 >", "structDirectionSelector_3_012_01_4.html", null ],
    [ "donelan_flux", "structdonelan__flux.html", null ],
    [ "eb_", "classeb__.html", null ],
    [ "eb_aux_", "classeb__aux__.html", null ],
    [ "eb_cut_cell_", "classeb__cut__cell__.html", null ],
    [ "eb_::EBToPVD", "classeb___1_1EBToPVD.html", null ],
    [ "ERFFillPatcher", "classERFFillPatcher.html", null ],
    [ "ERFPhysBCFunct_base", "classERFPhysBCFunct__base.html", null ],
    [ "ERFPhysBCFunct_cons", "classERFPhysBCFunct__cons.html", null ],
    [ "ERFPhysBCFunct_u", "classERFPhysBCFunct__u.html", null ],
    [ "ERFPhysBCFunct_v", "classERFPhysBCFunct__v.html", null ],
    [ "ERFPhysBCFunct_w", "classERFPhysBCFunct__w.html", null ],
    [ "ForestDrag", "classForestDrag.html", null ],
    [ "amrex::GPUable", null, [
      [ "TerrainIF", "classTerrainIF.html", null ]
    ] ],
    [ "InputSoundingData", "structInputSoundingData.html", null ],
    [ "InputSpongeData", "structInputSpongeData.html", null ],
    [ "IRadiation", "classIRadiation.html", [
      [ "Radiation", "classRadiation.html", null ]
    ] ],
    [ "LandSurface", "classLandSurface.html", null ],
    [ "LineSampler", "structLineSampler.html", null ],
    [ "Microphysics", "classMicrophysics.html", [
      [ "EulerianMicrophysics", "classEulerianMicrophysics.html", null ]
    ] ],
    [ "moeng_flux", "structmoeng__flux.html", null ],
    [ "MoistureComponentIndices", "structMoistureComponentIndices.html", null ],
    [ "most_data", "structmost__data.html", null ],
    [ "MOSTAverage", "classMOSTAverage.html", null ],
    [ "MRISplitIntegrator< T >", "classMRISplitIntegrator.html", null ],
    [ "MYNNLevel2", "structMYNNLevel2.html", null ],
    [ "MYNNLevel25", "structMYNNLevel25.html", null ],
    [ "MYNNPBLH", "structMYNNPBLH.html", null ],
    [ "ncutils::NCDim", "structncutils_1_1NCDim.html", null ],
    [ "ncutils::NCDType", "structncutils_1_1NCDType.html", null ],
    [ "ncutils::NCGroup", "classncutils_1_1NCGroup.html", [
      [ "ncutils::NCFile", "classncutils_1_1NCFile.html", null ]
    ] ],
    [ "ncutils::NCVar", "structncutils_1_1NCVar.html", null ],
    [ "NDArray< DataType >", "structNDArray.html", null ],
    [ "NullMoist", "classNullMoist.html", [
      [ "Kessler", "classKessler.html", null ],
      [ "Morrison", "classMorrison.html", null ],
      [ "SAM", "classSAM.html", null ],
      [ "SatAdj", "classSatAdj.html", null ]
    ] ],
    [ "NullSurf", "classNullSurf.html", [
      [ "MM5", "classMM5.html", null ],
      [ "NOAHMP", "classNOAHMP.html", null ],
      [ "SLM", "classSLM.html", null ]
    ] ],
    [ "NullWindFarm", "classNullWindFarm.html", [
      [ "EWP", "classEWP.html", null ],
      [ "Fitch", "classFitch.html", null ],
      [ "GeneralAD", "classGeneralAD.html", null ],
      [ "SimpleAD", "classSimpleAD.html", null ],
      [ "WindFarm", "classWindFarm.html", null ]
    ] ],
    [ "PlaneAverage", "classPlaneAverage.html", null ],
    [ "PlaneSampler", "structPlaneSampler.html", null ],
    [ "polygon_", "classpolygon__.html", null ],
    [ "ProblemBase", "classProblemBase.html", null ],
    [ "ProbParmDefaults", "structProbParmDefaults.html", null ],
    [ "ReadBndryPlanes", "classReadBndryPlanes.html", null ],
    [ "rotate_flux", "structrotate__flux.html", null ],
    [ "SampleData", "classSampleData.html", null ],
    [ "SatMethods", "classSatMethods.html", null ],
    [ "SHOCInterface", "classSHOCInterface.html", null ],
    [ "SHOCInterface::SHOCPostprocess", "structSHOCInterface_1_1SHOCPostprocess.html", null ],
    [ "SHOCInterface::SHOCPreprocess", "structSHOCInterface_1_1SHOCPreprocess.html", null ],
    [ "similarity_funs", "structsimilarity__funs.html", null ],
    [ "SolverChoice", "structSolverChoice.html", null ],
    [ "SpongeChoice", "structSpongeChoice.html", null ],
    [ "surface_flux", "structsurface__flux.html", null ],
    [ "surface_flux_charnock", "structsurface__flux__charnock.html", null ],
    [ "surface_flux_donelan", "structsurface__flux__donelan.html", null ],
    [ "surface_flux_mod_charnock", "structsurface__flux__mod__charnock.html", null ],
    [ "surface_flux_wave_coupled", "structsurface__flux__wave__coupled.html", null ],
    [ "surface_temp", "structsurface__temp.html", null ],
    [ "surface_temp_charnock", "structsurface__temp__charnock.html", null ],
    [ "surface_temp_donelan", "structsurface__temp__donelan.html", null ],
    [ "surface_temp_mod_charnock", "structsurface__temp__mod__charnock.html", null ],
    [ "surface_temp_wave_coupled", "structsurface__temp__wave__coupled.html", null ],
    [ "SurfaceLayer", "classSurfaceLayer.html", null ],
    [ "TimeInterpolatedData", "structTimeInterpolatedData.html", null ],
    [ "TurbChoice", "structTurbChoice.html", null ],
    [ "TurbulentPerturbation", "structTurbulentPerturbation.html", null ],
    [ "UnionListIF< F >", "classUnionListIF.html", null ],
    [ "UPWIND3", "structUPWIND3.html", null ],
    [ "UPWIND3SL", "structUPWIND3SL.html", null ],
    [ "UPWIND5", "structUPWIND5.html", null ],
    [ "UPWINDALL", "structUPWINDALL.html", null ],
    [ "WaterVaporSat", "classWaterVaporSat.html", null ],
    [ "WENO3", "structWENO3.html", null ],
    [ "WENO5", "structWENO5.html", null ],
    [ "WENO7", "structWENO7.html", null ],
    [ "WENO_MZQ3", "structWENO__MZQ3.html", null ],
    [ "WENO_Z3", "structWENO__Z3.html", null ],
    [ "WENO_Z5", "structWENO__Z5.html", null ],
    [ "WENO_Z7", "structWENO__Z7.html", null ],
    [ "WriteBndryPlanes", "classWriteBndryPlanes.html", null ]
];