ERF: Source/Radiation/Modal_aero_wateruptake.H File Reference
Modal_aero_wateruptake.H File Reference
#include <string>
#include <vector>
#include <memory>
#include <AMReX_FArrayBox.H>
#include <AMReX_Geometry.H>
#include <AMReX_TableData.H>
#include <AMReX_MultiFabUtil.H>
#include "ERF_Constants.H"
#include "Aero_rad_props.H"
#include "Cloud_rad_props.H"
Classes
class ModalAeroWateruptake
Functions
class ModalAeroWateruptake modal_aero_wateruptake_sub (ncol, nmodes, real1d &rhcrystal, reaal1d &rhdeliques, real3d &dryrad, real3d &hygro, real2d &rh, real3d &dryvol, real3d &wetrad, real3d &wetvol, real3d &wtrvol)
static void modal_aero_wateruptake_dr (int list_idx_in, real3d &dgnumdry_m, real3d &dgnumwet_m, real3d &qaerwat_m, real3d &wetdens_m, real2d &clear_rh_in) int list_idx
optional input relative humidty (overrides clearsky RH estimate below)
real2d h2ommr (:,:)
real2d t (:,:)
real2d pmid (:,:)
real2d raer (:,:)
real2d cldn (:,:)
real3d dgncur_a (:,:,:)
real3d dgncur_awet (:,:,:)
real3d wetdens (:,:,:)
real3d qaerwat (:,:,:)
real2d dryvolmr ("dryvolmr", pcols, pver)
real2d rh ("rh", pcols, pver)
real1d es ("es", pcols)
real1d qs ("qs", pcols)
real2d aerosol_water ("aerosol_water", pcols, pver)
real3d naer ("naer", pcols, pver, nmodes)
real3d dryvol ("dryvol", pcols, pver, nmodes)
real3d drymass ("drymass", pcols, pver, nmodes)
real3d dryrad ("dryrad", pcols, pver, nmodes)
real3d wetrad ("wetrad", pcol, pver, nmodes)
real3d wetvol ("wetvol", pcol, pver, nmodes)
real3d wtrvol ("wtrvol", pcol, pver, nmodes)
real1d rhcrystal ("rhcrystal", nmodes)
real1d rhdeliques ("rhdeliques", nmodes)
real1d specdens_1 ("specdens_1", nmodes)
real3d maer ("maer", pcol, pver, nmodes)
real3d hygro ("hygro", pcol, pver, nmodes)
if (list_idx_in)
if (wetdens_m)
for (auto m=0;m< nmodes;++m)
void modal_aero_kohler (real1d &rdry_in, real1d &hygro, real1d &s, real1d &rwet_out, int im)
void makoh_cubic (cx, p2, p1, p0, im) real eps
real1d q ("q", imx)
real1d r ("r", imx)
complex crad (imx)
complex cy (imx)
complex cz (imx) const expr real eps
return void makoh_quartic (cx, p3, p2, p1, p0, im)
Variables
constexpr real third = 1./3.
constexpr real pi43 = pi*4.0/3.0
constexpr real huge_real = numeric_limits<real>::max()
constexpr int imax = 200
int itim_old
int nmodes
int nspec
real specdens
real spechygro
real spechygro_1
real duma
real dumb
real sigmag
real alnsg
real v2ncur_a
real drydens
real cldn_thresh
bool history_aerosol
bool history_verbose
bool compute_wetdens = true
std::string trnum
list_idx
else
dgncur_awet = dgnumwet_m
qaerwat = qaerwat_m
void sqrt3 =sqrt(3.)
complex ci =cmplx(0.,1.)
complex cq
complex cw =0.5*(-1+ci*sqrt3)
complex cwsq =0.5*(-1-ci*sqrt3)
Function Documentation
aerosol_water()
real2d modal_aero_wateruptake_sub::aerosol_water ("aerosol_water" , pcols , pver)
cldn()
real2d modal_aero_wateruptake_sub::cldn (: , :)
Referenced by EbertCurry::ec_ice_optics_sw(), and Slingo::slingo_liq_optics_sw().
crad()
complex crad (imx)
cy()
complex cy (imx)
cz()
complex cz (imx) const
dgncur_a()
real3d modal_aero_wateruptake_sub::dgncur_a (: , : , :)
Referenced by Mam4_aer::modal_aero_calcsize_diag().
dgncur_awet()
real3d modal_aero_wateruptake_sub::dgncur_awet (: , : , :)
drymass()
real3d modal_aero_wateruptake_sub::drymass ("drymass" , pcols , pver , nmodes)
dryrad()
real3d modal_aero_wateruptake_sub::dryrad ("dryrad" , pcols , pver , nmodes)
dryvol()
real3d modal_aero_wateruptake_sub::dryvol ("dryvol" , pcols , pver , nmodes)
Referenced by Mam4_aer::modal_aero_lw(), and Mam4_aer::modal_aero_sw().
dryvolmr()
real2d modal_aero_wateruptake_sub::dryvolmr ("dryvolmr" , pcols , pver)
es()
real1d modal_aero_wateruptake_sub::es ("es" , pcols)
Referenced by AerRadProps::aer_rad_props_lw(), AerRadProps::aer_rad_props_sw(), WaterVaporSat::deriv_outputs(), WaterVaporSat::findsp(), WaterVaporSat::qsat(), WaterVaporSat::qsat_ice(), WaterVaporSat::qsat_water(), rh_to_mxrat(), SatMethods::wv_sat_qsat_ice(), SatMethods::wv_sat_qsat_trans(), SatMethods::wv_sat_qsat_water(), SatMethods::wv_sat_svp_ice(), SatMethods::wv_sat_svp_to_qsat(), SatMethods::wv_sat_svp_trans(), and SatMethods::wv_sat_svp_water().
for()
for ()
{
         q(i)=-p2(i)*p2(i)/36.+(p3(i)*p1(i)-4*p0(i))/12.;
         r(i)=-(p2(i)/6)**3+p2(i)*(p3(i)*p1(i)-4*p0(i))/48.
             +(4*p0(i)*p2(i)-p0(i)*p3(i)*p3(i)-p1(i)*p1(i))/16;
         crad(i)=r(i)*r(i)+q(i)*q(i)*q(i);
         crad(i)=sqrt(crad(i));
         cb(i)=r(i)-crad(i);
Referenced by fine_compute_interior_ghost_rhs().
h2ommr()
real2d modal_aero_wateruptake_sub::h2ommr (: , :)
hygro()
real3d modal_aero_wateruptake_sub::hygro ("hygro" , pcol , pver , nmodes)
if() [1/2]
modal_aero_wateruptake_sub::if (list_idx_in)
{
            rdry(i) = rdry_in(i)*1.0e6;   // convert (m) to (microns)
            vol(i) = rdry(i)**3;          // vol is r**3, not volume
Referenced by erf_init_rayleigh(), erf_slow_rhs_inc(), fine_compute_interior_ghost_rhs(), and LinInterp::init().
if() [2/2]
modal_aero_wateruptake_sub::if (wetdens_m)
{
maer()
real3d modal_aero_wateruptake_sub::maer ("maer" , pcol , pver , nmodes)
makoh_cubic()
void makoh_cubic (cx , p2 , p1 , p0 , im)
makoh_quartic()
return void makoh_quartic (cx , p3 , p2 , p1 , p0 , im)
{
         constexpr int imx=200;
       //real(r8) :: p0(imx), p1(imx), p2(imx), p3(imx)
       //complex(r8) :: cx(4,imx)
       real third;
       real1d q("q",imx), r("r",imx);
       complex cb(imx), cb0(imx), cb1(imx);
       complex crad(imx), cy(imx), czero;
       czero=cmplx(0.0,0.0);
       third=1./3.;
       for(auto i=0; i<im; ++i) {
         q(i)=-p2(i)*p2(i)/36.+(p3(i)*p1(i)-4*p0(i))/12.;
         r(i)=-(p2(i)/6)**3+p2(i)*(p3(i)*p1(i)-4*p0(i))/48.
             +(4*p0(i)*p2(i)-p0(i)*p3(i)*p3(i)-p1(i)*p1(i))/16;
         crad(i)=r(i)*r(i)+q(i)*q(i)*q(i);
         crad(i)=sqrt(crad(i));
         cb(i)=r(i)-crad(i);
         if(cb(i) == czero) {
            //insoluble particle
            cx(1,i)=(-p1(i))**third;
            cx(2,i)=cx(1,i);
            cx(3,i)=cx(1,i);
            cx(4,i)=cx(1,i);
         }
         cb(i)=cb(i)**third;
         cy(i)=-cb(i)+q(i)/cb(i)+p2(i)/6;
         cb0(i)=sqrt(cy(i)*cy(i)-p0(i));
         cb1(i)=(p3(i)*cy(i)-p1(i))/(2*cb0(i));
          cb(i)=p3(i)/2+cb1(i);
          crad(i)=cb(i)*cb(i)-4*(cy(i)+cb0(i));
          crad(i)=sqrt(crad(i));
          cx(1,i)=(-cb(i)+crad(i))/2.;
          cx(2,i)=(-cb(i)-crad(i))/2.;
          cb(i)=p3(i)/2-cb1(i);
          crad(i)=cb(i)*cb(i)-4*(cy(i)-cb0(i));
          crad(i)=sqrt(crad(i));
          cx(3,i)=(-cb(i)+crad(i))/2.;
          cx(4,i)=(-cb(i)-crad(i))/2.;
       }
    10 continue
       return;
     }
modal_aero_kohler()
void modal_aero_kohler (real1d & rdry_in, real1d & hygro, real1d & s, real1d & rwet_out, int im)
{
 #if 0
 ! arguments
       integer :: im         ! number of grid points to be processed
       real(r8) :: rdry_in(:)    ! aerosol dry radius (m)
       real(r8) :: hygro(:)      ! aerosol volume-mean hygroscopicity (--)
       real(r8) :: s(:)          ! relative humidity (1 = saturated)
       real(r8) :: rwet_out(:)   ! aerosol wet radius (m)
 #endif
       real a, b;
       real1d p40("p40",imax),p41("p41",imax),p42("p42",imax),p43("p43",imax); // coefficients of polynomial
       real1d p30("p30",imax),p31("p31",imax),p32("p32",imax); // coefficients of polynomial
       real p;
       real r3, r4;
       real1d r("r",im);         // wet radius (microns)
       real1d rdry("rdry",imax);    // radius of dry particle (microns)
       real ss;            // relative humidity (1 = saturated)
       real1d slog("slog",imax);   // log relative humidity
       real1d vol("vol",imax);     // total volume of particle (microns**3)
       real xi, xr;
       complex cx4(4,imax),cx3(3,imax);
       constexpr real eps = 1.e-4;
       constexpr real mw = 18.;
       constexpr real pi = 3.14159;
       constexpr real rhow = 1.;
       constexpr real surften = 76.;
       constexpr real tair = 273.;
       constexpr real third = 1./3.;
       constexpr real ugascon = 8.3e7;
      //effect of organics on surface tension is neglected
       a=2.e4*mw*surften/(ugascon*tair*rhow);
       for(auto i=0; i<im; ++i) {
            rdry(i) = rdry_in(i)*1.0e6;   // convert (m) to (microns)
            vol(i) = rdry(i)**3;          // vol is r**3, not volume
            b = vol(i)*hygro(i);
           //quartic
            ss=min(s(i),1.-eps);
            ss=max(ss,1.e-10;)
            slog(i)=log(ss);
            p43(i)=-a/slog(i);
            p42(i)=0.;
            p41(i)=b/slog(i)-vol(i);
            p40(i)=a*vol(i)/slog(i);
          // cubic for rh=1
            p32(i)=0.;
            p31(i)=-b/a;
            p30(i)=-vol(i);
       }
        do 100 i=1,im
         if(vol(i) <= 1.e-12) {
            r(i)=rdry(i);
            goto 100;
         }
         p=abs(p31(i))/(rdry(i)*rdry(i));
         if(p < eps) {
           //approximate solution for small particles
            r(i)=rdry(i)*(1.+p*third/(1.-slog(i)*rdry(i)/a));
         } else {
            makoh_quartic(cx4(1,i),p43(i),p42(i),p41(i),p40(i),1);
            //find smallest real(r8) solution
            r(i)=1000.*rdry(i);
            nsol=0;
            for(auto n=1; n<=4; ++n) {
               xr=real(cx4(n,i));
               xi=aimag(cx4(n,i));
               if(abs(xi) > abs(xr)*eps) continue;
               if(xr > r(i)) continue;
               if(xr < rdry(i)*(1._r8-eps)) continue
               if(xr != xr) continue
               r(i)=xr;
               nsol=n;
            }
            if(nsol != 0) {
               amrex::PRINT << "ccm kohlerc - no real(r8) solution found (quartic)\n";
               r(i)=rdry(i);
            }
         }
         if(s(i) > 1.-eps) {
          // save quartic solution at s=1-eps
            r4=r(i);
         //  cubic for rh=1
            p=abs(p31(i))/(rdry(i)*rdry(i));
            if(p < eps) {
               r(i)=rdry(i)*(1._r8+p*third);
            }
            else {
               makoh_cubic(cx3,p32,p31,p30,im);
              //find smallest real(r8) solution
               r(i)=1000.*rdry(i);
               nsol=0;
               for(auto n=1; n<=3; ++n) {
                  xr=real(cx3(n,i));
                  xi=aimag(cx3(n,i));
                  if(abs(xi) > abs(xr)*eps) continue;
                  if(xr > r(i)) continue;
                  if(xr < rdry(i)*(1.-eps)) continue;
                  if(xr != xr) continue;
                  r(i)=xr;
                  nsol=n;
               }
               if(nsol == 0) {
                  amrex::PRINT << "ccm kohlerc - no real(r8) solution found (cubic)\n";
                  r(i)=rdry(i);
               }
            }
            r3=r(i);
            //now interpolate between quartic, cubic solutions
            r(i)=(r4*(1.-s(i))+r3*(s(i)-1.+eps))/eps;
         }
   100 continue
      // bound and convert from microns to m
       for(auto i=0; i<im; ++i) {
          r(i) = min(r(i),30.); // upper bound based on 1 day lifetime
          rwet_out(i) = r(i)*1.e-6;
       }
       return;
    }
modal_aero_wateruptake_dr()
static void modal_aero_wateruptake_sub::modal_aero_wateruptake_dr (int list_idx_in, real3d & dgnumdry_m, real3d & dgnumwet_m, real3d & qaerwat_m, real3d & wetdens_m, real2d & clear_rh_in) static
optional input relative humidty (overrides clearsky RH estimate below)
modal_aero_wateruptake_sub()
class ModalAeroWateruptake modal_aero_wateruptake_sub (ncol , nmodes , real1d & rhcrystal, reaal1d & rhdeliques, real3d & dryrad, real3d & hygro, real2d & rh, real3d & dryvol, real3d & wetrad, real3d & wetvol, real3d & wtrvol)
                    {
 #if 0
    ! Arguments
    integer, intent(in)  :: ncol                    ! number of columns
    integer, intent(in)  :: nmodes
    real(r8), intent(in) :: rhcrystal(:)
    real(r8), intent(in) :: rhdeliques(:)
    real(r8), intent(in) :: dryrad(:,:,:)         ! dry volume mean radius of aerosol (m)
    real(r8), intent(in) :: hygro(:,:,:)          ! volume-weighted mean hygroscopicity (--)
    real(r8), intent(in) :: rh(:,:)               ! relative humidity (0-1)
    real(r8), intent(in) :: dryvol(:,:,:)
    real(r8), intent(out) :: wetrad(:,:,:)        ! wet radius of aerosol (m)
    real(r8), intent(out) :: wetvol(:,:,:)        ! single-particle-mean wet volume (m3)
    real(r8), intent(out) :: wtrvol(:,:,:)        ! single-particle-mean water volume in wet aerosol (m3)
 #endif
    // local variables
    real hystfac;      // working variable for hysteresis
    // loop over all aerosol modes
    for(auto m = 0; m < nmodes; ++m) {
       hystfac = 1.0 / max(1.0e-5, (rhdeliques(m) - rhcrystal(m)));
       for(auto k = top_lev; k > pver; --k) {
          for(auto i = 0; i < ncol; ++i) {
             // compute wet radius for each mode
             modal_aero_kohler(dryrad(i:i,k,m), hygro(i:i,k,m), rh(i:i,k), wetrad(i:i,k,m), 1);
             wetrad(i,k,m) = max(wetrad(i,k,m), dryrad(i,k,m));
             wetvol(i,k,m) = pi43*wetrad(i,k,m)**3;
             wetvol(i,k,m) = max(wetvol(i,k,m), dryvol(i,k,m));
             wtrvol(i,k,m) = wetvol(i,k,m) - dryvol(i,k,m);
             wtrvol(i,k,m) = max(wtrvol(i,k,m), 0.0);
             // apply simple treatment of deliquesence/crystallization hysteresis
             // for rhcrystal < rh < rhdeliques, aerosol water is a fraction of
             // the "upper curve" value, and the fraction is a linear function of rh
             if (rh(i,k) < rhcrystal(m)) {
                wetrad(i,k,m) = dryrad(i,k,m);
                wetvol(i,k,m) = dryvol(i,k,m);
                wtrvol(i,k,m) = 0.0;
             } else if (rh(i,k) < rhdeliques(m)) {
                wtrvol(i,k,m) = wtrvol(i,k,m)*hystfac*(rh(i,k) - rhcrystal(m));
                wtrvol(i,k,m) = max(wtrvol(i,k,m), 0.0);
                wetvol(i,k,m) = dryvol(i,k,m) + wtrvol(i,k,m);
                wetrad(i,k,m) = (wetvol(i,k,m)/pi43)**third;
             }
          } // columns
       } // levels
    } // modes
 }
naer()
real3d modal_aero_wateruptake_sub::naer ("naer" , pcols , pver , nmodes)
Referenced by MamConstituents::rad_cnst_out().
pmid()
real2d modal_aero_wateruptake_sub::pmid (: , :)
Referenced by Radiation::initialize(), Radiation::radiation_driver_lw(), Radiation::radiation_driver_sw(), Radiation::run(), Rrtmgp::run_longwave_rrtmgp(), and Rrtmgp::run_shortwave_rrtmgp().
q()
real1d q ("q" , imx)
Referenced by erf_fast_rhs_MT(), erf_fast_rhs_N(), erf_fast_rhs_T(), erf_slow_rhs_pre(), WaterVaporSat::findsp(), make_fast_coeffs(), and WaterVaporSat::tq_enthalpy().
qaerwat()
real3d modal_aero_wateruptake_sub::qaerwat (: , : , :)
qs()
real1d modal_aero_wateruptake_sub::qs ("qs" , pcols)
Referenced by AerRadProps::aer_rad_props_lw(), AerRadProps::aer_rad_props_sw(), WaterVaporSat::deriv_outputs(), WaterVaporSat::findsp(), WaterVaporSat::qsat(), WaterVaporSat::qsat_ice(), WaterVaporSat::qsat_water(), SatMethods::wv_sat_qsat_ice(), SatMethods::wv_sat_qsat_trans(), and SatMethods::wv_sat_qsat_water().
r()
real1d r ("r" , imx)
Referenced by erf_init_dens_hse(), HSEutils::init_isentropic_hse(), HSEutils::init_isentropic_hse_terrain(), and TerrainFittedPC::InitParticles().
raer()
real2d modal_aero_wateruptake_sub::raer (: , :)
rh()
real2d modal_aero_wateruptake_sub::rh ("rh" , pcols , pver)
Referenced by PhysProp::aer_optics_log_rh(), AerRadProps::aer_rad_props_lw(), AerRadProps::aer_rad_props_sw(), PhysProp::hygro_optics_init(), and PhysProp::hygroscopic_optics_init().
rhcrystal()
real1d modal_aero_wateruptake_sub::rhcrystal ("rhcrystal" , nmodes)
Referenced by MamConstituents::get_mode_props(), and PhysProp::get_rhcrystal().
rhdeliques()
real1d modal_aero_wateruptake_sub::rhdeliques ("rhdeliques" , nmodes)
Referenced by MamConstituents::get_mode_props(), and PhysProp::get_rhdeliques().
specdens_1()
real1d modal_aero_wateruptake_sub::specdens_1 ("specdens_1" , nmodes)
t()
real2d modal_aero_wateruptake_sub::t (: , :)
Referenced by Mam4_aer::binterp(), SatMethods::Bolton_svp_water(), WaterVaporSat::calc_hltalt(), WaterVaporSat::deriv_outputs(), erf_dtesati(), erf_dtesatw(), erf_dtqsati(), erf_dtqsatw(), erf_esati(), erf_esatw(), erf_qsati(), erf_qsatw(), WaterVaporSat::findsp(), SatMethods::GoffGratch_svp_ice(), SatMethods::GoffGratch_svp_water(), SatMethods::MurphyKoop_svp_ice(), SatMethods::MurphyKoop_svp_water(), WaterVaporSat::no_ip_hltalt(), SatMethods::OldGoffGratch_svp_ice(), SatMethods::OldGoffGratch_svp_water(), WaterVaporSat::qsat(), WaterVaporSat::qsat_ice(), WaterVaporSat::qsat_water(), WaterVaporSat::svp_ice(), WaterVaporSat::svp_trans(), WaterVaporSat::svp_water(), WaterVaporSat::tq_enthalpy(), SatMethods::wv_sat_qsat_ice(), SatMethods::wv_sat_qsat_trans(), SatMethods::wv_sat_qsat_water(), SatMethods::wv_sat_svp_ice(), SatMethods::wv_sat_svp_trans(), and SatMethods::wv_sat_svp_water().
wetdens()
real3d modal_aero_wateruptake_sub::wetdens (: , : , :)
wetrad()
real3d modal_aero_wateruptake_sub::wetrad ("wetrad" , pcol , pver , nmodes)
wetvol()
real3d modal_aero_wateruptake_sub::wetvol ("wetvol" , pcol , pver , nmodes)
Referenced by Mam4_aer::modal_aero_lw(), and Mam4_aer::modal_aero_sw().
wtrvol()
real3d modal_aero_wateruptake_sub::wtrvol ("wtrvol" , pcol , pver , nmodes)
Variable Documentation
alnsg
real alnsg
Referenced by Mam4_aer::modal_aero_calcsize_diag().
ci
ci =cmplx(0.,1.)
cldn_thresh
real cldn_thresh
compute_wetdens
compute_wetdens = true
cq
complex cq
cw
cw =0.5*(-1+ci*sqrt3)
cwsq
cwsq =0.5*(-1-ci*sqrt3)
dgncur_awet
dgncur_awet = dgnumwet_m
drydens
real drydens
duma
real duma
dumb
real dumb
else
else
Initial value:
{
      dgncur_a    = dgnumdry_m
history_aerosol
bool history_aerosol
history_verbose
bool history_verbose
huge_real
constexpr real huge_real = numeric_limits<real>::max() constexpr
imax
constexpr int imax = 200 constexpr
Referenced by init_terrain_grid().
itim_old
int itim_old
list_idx
list_idx
Initial value:
= 0
   if (list_idx_in)
      list_idx = list_idx_in
Referenced by AerRadProps::aer_rad_props_lw(), AerRadProps::aer_rad_props_sw(), MamConstituents::get_aer_lw_abs(), MamConstituents::get_aer_lw_hygro_abs(), MamConstituents::get_aer_mu(), MamConstituents::get_aer_opticstype(), MamConstituents::get_aer_r_lw_abs(), MamConstituents::get_aer_r_sw_ascat(), MamConstituents::get_aer_r_sw_ext(), MamConstituents::get_aer_r_sw_scat(), MamConstituents::get_aer_refindex_aer_lw(), MamConstituents::get_aer_refindex_aer_sw(), MamConstituents::get_aer_sw_hygro_asm(), MamConstituents::get_aer_sw_hygro_ext(), MamConstituents::get_aer_sw_hygro_ssa(), MamConstituents::get_aer_sw_nonhygro_ascat(), MamConstituents::get_aer_sw_nonhygro_asm(), MamConstituents::get_aer_sw_nonhygro_ext(), MamConstituents::get_aer_sw_nonhygro_scat(), MamConstituents::get_aer_sw_nonhygro_ssa(), MamConstituents::get_aername(), MamConstituents::get_aero_names(), MamConstituents::get_density_aer(), MamConstituents::get_dispersion_aer(), MamConstituents::get_dryrad_aer(), MamConstituents::get_gas_names(), MamConstituents::get_hygro_aer(), MamConstituents::get_mam_props(), MamConstituents::get_mam_props_lw(), MamConstituents::get_mam_props_sw(), MamConstituents::get_mode_nspec(), MamConstituents::get_mode_props(), MamConstituents::get_naero(), MamConstituents::get_ngas(), MamConstituents::get_nmodes(), MamConstituents::get_num_to_mass_aer(), Mam4_aer::modal_aero_calcsize_diag(), Mam4_aer::modal_aero_lw(), Mam4_aer::modal_aero_sw(), MamConstituents::rad_cnst_get_aer_idx(), MamConstituents::rad_cnst_get_aer_mmr_by_idx(), MamConstituents::rad_cnst_get_gas(), MamConstituents::rad_cnst_get_info_by_mode(), MamConstituents::rad_cnst_get_info_by_mode_spec(), MamConstituents::rad_cnst_get_info_by_spectype(), MamConstituents::rad_cnst_get_mam_mmr_by_idx(), MamConstituents::rad_cnst_get_mode_idx(), MamConstituents::rad_cnst_get_mode_num(), MamConstituents::rad_cnst_get_spec_idx(), and MamConstituents::rad_cnst_out().
nmodes
int nmodes
Referenced by MamConstituents::get_nmodes(), MamConstituents::MamConstituents(), MamConstituents::rad_cnst_get_info_by_mode(), MamConstituents::rad_cnst_get_info_by_mode_spec(), MamConstituents::rad_cnst_get_info_by_spectype(), and MamConstituents::rad_cnst_get_mode_idx().
nspec
int nspec
Referenced by MamConstituents::get_mode_nspec(), MamConstituents::rad_cnst_get_info_by_mode(), MamConstituents::rad_cnst_get_info_by_mode_spec(), MamConstituents::rad_cnst_get_info_by_spectype(), and MamConstituents::rad_cnst_get_spec_idx().
pi43
constexpr real pi43 = pi*4.0/3.0 constexpr
qaerwat
qaerwat = qaerwat_m
Referenced by Mam4_aer::modal_aero_lw(), and Mam4_aer::modal_aero_sw().
sigmag
real sigmag
Referenced by MamConstituents::get_mode_props(), PhysProp::get_sigmag(), and Mam4_aer::modal_aero_calcsize_diag().
specdens
real specdens
Referenced by Mam4_aer::modal_aero_calcsize_diag(), Mam4_aer::modal_aero_lw(), and Mam4_aer::modal_aero_sw().
spechygro
real spechygro
spechygro_1
real spechygro_1
sqrt3
sqrt3 =sqrt(3.)
third
void third = 1./3. constexpr
trnum
std::string trnum
v2ncur_a
real v2ncur_a