var MOSTStress_8H =
[
    [ "most_data", "structmost__data.html", "structmost__data" ],
    [ "similarity_funs", "structsimilarity__funs.html", "structsimilarity__funs" ],
    [ "adiabatic", "structadiabatic.html", "structadiabatic" ],
    [ "adiabatic_charnock", "structadiabatic__charnock.html", "structadiabatic__charnock" ],
    [ "adiabatic_mod_charnock", "structadiabatic__mod__charnock.html", "structadiabatic__mod__charnock" ],
    [ "adiabatic_donelan", "structadiabatic__donelan.html", "structadiabatic__donelan" ],
    [ "adiabatic_wave_coupled", "structadiabatic__wave__coupled.html", "structadiabatic__wave__coupled" ],
    [ "surface_flux", "structsurface__flux.html", "structsurface__flux" ],
    [ "surface_flux_charnock", "structsurface__flux__charnock.html", "structsurface__flux__charnock" ],
    [ "surface_flux_mod_charnock", "structsurface__flux__mod__charnock.html", "structsurface__flux__mod__charnock" ],
    [ "surface_flux_donelan", "structsurface__flux__donelan.html", "structsurface__flux__donelan" ],
    [ "surface_flux_wave_coupled", "structsurface__flux__wave__coupled.html", "structsurface__flux__wave__coupled" ],
    [ "surface_temp", "structsurface__temp.html", "structsurface__temp" ],
    [ "surface_temp_charnock", "structsurface__temp__charnock.html", "structsurface__temp__charnock" ],
    [ "surface_temp_mod_charnock", "structsurface__temp__mod__charnock.html", "structsurface__temp__mod__charnock" ],
    [ "surface_temp_donelan", "structsurface__temp__donelan.html", "structsurface__temp__donelan" ],
    [ "surface_temp_wave_coupled", "structsurface__temp__wave__coupled.html", "structsurface__temp__wave__coupled" ],
    [ "moeng_flux", "structmoeng__flux.html", "structmoeng__flux" ],
    [ "donelan_flux", "structdonelan__flux.html", "structdonelan__flux" ],
    [ "custom_flux", "structcustom__flux.html", "structcustom__flux" ],
    [ "rotate_flux", "structrotate__flux.html", "structrotate__flux" ],
    [ "air_viscosity", "MOSTStress_8H.html#a83577688af6d1136ab7a0be1b16f4674", null ],
    [ "WSMIN", "MOSTStress_8H.html#a267a6d14795f9c46a0845fc44c93c0f2", null ]
];