ERF: derived Namespace Reference
derived Namespace Reference
Functions
void erf_derrhodivide (const Box &bx, FArrayBox &derfab, const FArrayBox &datfab, const int scalar_index)
void erf_dernull (const Box &, FArrayBox &, int, int, const FArrayBox &, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dersoundspeed (const Box &bx, FArrayBox &derfab, int, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dertemp (const Box &bx, FArrayBox &derfab, int, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dermoisttemp (const Box &bx, FArrayBox &derfab, int, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dertheta (const Box &bx, FArrayBox &derfab, int, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_derscalar (const Box &bx, FArrayBox &derfab, int, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_derKE (const Box &bx, FArrayBox &derfab, int, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dervortx (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &zcc_fab, const Geometry &geomdata, Real, const int *, const int)
void erf_dervorty (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &zcc_fab, const Geometry &geomdata, Real, const int *, const int)
void erf_dervortz (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &, const Geometry &geomdata, Real, const int *, const int)
void erf_derenstrophysq (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &zcc_fab, const Geometry &geomdata, Real, const int *, const int)
void erf_dermagvel (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dermagvelsq (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_derreflectivity (const Box &bx, FArrayBox &derfab, int dcomp, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_dermaxreflectivity (const Box &bx, FArrayBox &derfab, int dcomp, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &, Real, const int *, const int)
void erf_derlocalhelicity (const Box &bx, FArrayBox &derfab, int dcomp, int, const FArrayBox &datfab, const FArrayBox &, const Geometry &geomdata, Real, const int *, const int)
void erf_derhelicity (const Box &bx, FArrayBox &derfab, int dcomp, int, const FArrayBox &datfab, const FArrayBox &zcc_fab, const Geometry &geomdata, Real, const int *, const int)
void erf_derprecipitable (const Box &bx, FArrayBox &derfab, int dcomp, int, const FArrayBox &datfab, const FArrayBox &zcc_fab, const Geometry &, Real, const int *, const int)
void erf_dermucape (const Box &bx, FArrayBox &derfab, int dcomp, int ncomp, const FArrayBox &datfab, const FArrayBox &zcc_fab, const Geometry &, Real, const int *, const int)
void erf_derrhodivide (const amrex::Box &bx, amrex::FArrayBox &derfab, const amrex::FArrayBox &datfab, const int scalar_index)
void erf_dernull (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dersoundspeed (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dertemp (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dermoisttemp (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dertheta (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derscalar (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derKE (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dervortx (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dervorty (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dervortz (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derenstrophysq (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dermagvel (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dermagvelsq (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derreflectivity (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dermaxreflectivity (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derhelicity (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derlocalhelicity (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_derprecipitable (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
void erf_dermucape (const amrex::Box &bx, amrex::FArrayBox &derfab, int dcomp, int ncomp, const amrex::FArrayBox &datfab, const amrex::FArrayBox &zfab, const amrex::Geometry &geomdata, amrex::Real time, const int *bcrec, const int level)
Function Documentation
erf_derenstrophysq() [1/2]
void derived::erf_derenstrophysq (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derenstrophysq() [2/2]
void derived::erf_derenstrophysq (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & zcc_fab, const Geometry & geomdata, Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array(); // cell-centered velocity
     auto tfab      = derfab.array(); // cell-centered vorticity x-component
     auto z_arr     = zcc_fab.array(); // cell-centered height z
     const Real two_dx = two * geomdata.CellSize(0);
     const Real two_dy = two * geomdata.CellSize(1);
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real two_dz = z_arr(i,j,k+1) - z_arr(i,j,k-1);
         Real vortx = (dat(i,j+1,k,2) - dat(i,j-1,k,2)) / two_dy  // dw/dy
                     -(dat(i,j,k+1,1) - dat(i,j,k-1,1)) / two_dz; // dv/dz
         Real vorty = (dat(i,j,k+1,0) - dat(i,j,k-1,0)) / two_dz  // du/dz
                     -(dat(i+1,j,k,2) - dat(i-1,j,k,2)) / two_dx; // dw/dx
         Real vortz = (dat(i+1,j,k,1) - dat(i-1,j,k,1)) / two_dx  // dv/dx
                     -(dat(i,j+1,k,0) - dat(i,j-1,k,0)) / two_dy; // du/dy
         tfab(i,j,k,dcomp) = vortx*vortx + vorty*vorty + vortz*vortz;
     });
 }
Referenced by ERF::sum_derived_quantities().
erf_derhelicity() [1/2]
void derived::erf_derhelicity (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derhelicity() [2/2]
void derived::erf_derhelicity (const Box & bx, FArrayBox & derfab, int dcomp, int , const FArrayBox & datfab, const FArrayBox & zcc_fab, const Geometry & geomdata, Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     auto const dat = datfab.array();  // cell-centered velocity
     auto dfab      = derfab.array();  // integral of local helicity
     auto z_arr     = zcc_fab.array(); // cell-centered height z
     const Real dx = geomdata.CellSize(0);
     const Real dy = geomdata.CellSize(1);
     // Collapse to i,j box (ignore vertical for now)
     Box b2d = bx;
     b2d.setSmall(2,0);
     b2d.setBig(2,0);
     ParallelFor(b2d, [=] AMREX_GPU_DEVICE(int i, int j, int ) noexcept
     {
         Real int_hel = Real(0.0);
         for (int k = bx.smallEnd(2); k <= bx.bigEnd(2); ++k)
         {
             Real z = z_arr(i,j,k);
             // Helicity is defined as integral from 2km to 5km in vertical
             if (z > Real(2000.0) && z < Real(5000.0)) {
                 Real z_hi = Real(0.5) * (z_arr(i,j,k) + z_arr(i,j,k+1));
                 Real z_lo = Real(0.5) * (z_arr(i,j,k) + z_arr(i,j,k-1));
                 Real dz = z_hi - z_lo;
                 Real vortz = (dat(i+1,j,k,1) - dat(i-1,j,k,1)) / (2.0*dx)  // dv/dx
                            - (dat(i,j+1,k,0) - dat(i,j-1,k,0)) / (2.0*dy); // du/dy
                 Real w     = dat(i,j,k,2); // vertical velocity
                 int_hel += vortz * w * dz;
             }
         }
         // Store vertical integral into *all* levels for this (i,j)
         for (int k = bx.smallEnd(2); k <= bx.bigEnd(2); ++k) {
             dfab(i, j, k, dcomp) = int_hel;
         }
     });
 }
Referenced by ERF::Write3DPlotFile().
erf_derKE() [1/2]
void derived::erf_derKE (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derKE() [2/2]
void derived::erf_derKE (const Box & bx, FArrayBox & derfab, int , int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
Function to define the kinetic energy KE by dividing (rho KE) by rho
@params[in] bx box on which to divide by density @params[out] derfab array of derived quantity – here it holds KE @params[in] datfab array of data used to construct derived quantity
 {
     erf_derrhodivide(bx, derfab, datfab, RhoKE_comp);
 }
Referenced by ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_derlocalhelicity() [1/2]
void derived::erf_derlocalhelicity (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derlocalhelicity() [2/2]
void derived::erf_derlocalhelicity (const Box & bx, FArrayBox & derfab, int dcomp, int , const FArrayBox & datfab, const FArrayBox & , const Geometry & geomdata, Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     auto const dat = datfab.array(); // cell-centered velocity
     auto dfab      = derfab.array(); // cell-centered local helicity
     const Real two_dx = Real(2.0)*geomdata.CellSize(0);
     const Real two_dy = Real(2.0)*geomdata.CellSize(1);
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real vortz = (dat(i+1,j,k,1) - dat(i-1,j,k,1)) / two_dx  // dv/dx
                    - (dat(i,j+1,k,0) - dat(i,j-1,k,0)) / two_dy; // du/dy
         Real w     = dat(i,j,k,2);
         // Helicity
         dfab(i,j,k,dcomp) = vortz * w;
     });
 }
Referenced by ERF::Write3DPlotFile().
erf_dermagvel() [1/2]
void derived::erf_dermagvel (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dermagvel() [2/2]
void derived::erf_dermagvel (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array(); // cell-centered velocity
     auto tfab      = derfab.array(); // cell-centered magvel
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real u = dat(i,j,k,0);
         Real v = dat(i,j,k,1);
         Real w = dat(i,j,k,2);
         tfab(i,j,k,dcomp) = std::sqrt(u*u + v*v + w*w);
     });
 }
Referenced by ERF::ErrorEst(), and ERF::Write3DPlotFile().
erf_dermagvelsq() [1/2]
void derived::erf_dermagvelsq (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dermagvelsq() [2/2]
void derived::erf_dermagvelsq (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array(); // cell-centered velocity
     auto tfab      = derfab.array(); // cell-centered magvel
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real u = dat(i,j,k,0);
         Real v = dat(i,j,k,1);
         Real w = dat(i,j,k,2);
         tfab(i,j,k,dcomp) = u*u + v*v + w*w;
     });
 }
Referenced by ERF::sum_derived_quantities().
erf_dermaxreflectivity() [1/2]
void derived::erf_dermaxreflectivity (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dermaxreflectivity() [2/2]
void derived::erf_dermaxreflectivity (const Box & bx, FArrayBox & derfab, int dcomp, int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     auto const dat = datfab.array(); // cell-centered state vector
     auto rfab      = derfab.array(); // cell-centered max reflectivity
     // Collapse to i,j box (ignore vertical for now)
     Box b2d = bx;
     b2d.setSmall(2,0);
     b2d.setBig(2,0);
     ParallelFor(b2d, [=] AMREX_GPU_DEVICE(int i, int j, int) noexcept {
         Real max_dbz = -1.0e30;
         // find max reflectivity over k
         for (int k = bx.smallEnd(2); k <= bx.bigEnd(2); ++k) {
             Real rho = dat(i,j,k,Rho_comp);
             Real qv  = std::max(Real(0.0),dat(i,j,k,RhoQ1_comp)/rho);
             Real qpr = std::max(Real(0.0),dat(i,j,k,RhoQ4_comp)/rho);
             Real qps = std::max(Real(0.0),dat(i,j,k,RhoQ5_comp)/rho);
             Real qpg = std::max(Real(0.0),dat(i,j,k,RhoQ6_comp)/rho);
             Real temp = getTgivenRandRTh(rho, dat(i,j,k,RhoTheta_comp), qv);
             Real dbz = compute_max_reflectivity_dbz(rho, temp, qpr, qps, qpg,
                                                     1, 1, 1, 1);
             max_dbz = amrex::max(max_dbz, dbz);
         }
         // Store max_dbz into *all* levels for this (i,j)
         for (int k = bx.smallEnd(2); k <= bx.bigEnd(2); ++k) {
             rfab(i, j, k, dcomp) = max_dbz;
         }
     });
 }
Referenced by ERF::Write3DPlotFile().
erf_dermoisttemp() [1/2]
void derived::erf_dermoisttemp (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dermoisttemp() [2/2]
void derived::erf_dermoisttemp (const Box & bx, FArrayBox & derfab, int , int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
 {
     auto const dat = datfab.array();
     auto tfab      = derfab.array();
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         const Real rho = dat(i, j, k, Rho_comp);
         const Real rhotheta = dat(i, j, k, RhoTheta_comp);
         AMREX_ALWAYS_ASSERT(rhotheta > Real(0.0));
         const Real qv = dat(i, j, k, RhoQ1_comp) / rho;
         tfab(i,j,k) = getTgivenRandRTh(rho,rhotheta,qv);
     });
 }
Referenced by ERF::Write3DPlotFile(), WriteBndryPlanes::write_planes(), and ERF::WriteSubvolume().
erf_dermucape() [1/2]
void derived::erf_dermucape (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dermucape() [2/2]
void derived::erf_dermucape (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & zcc_fab, const Geometry & , Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array();
     auto dfab      = derfab.array();
     auto z_arr     = zcc_fab.array();
     const int ncons = datfab.nComp();
     Box b2d = bx;
     b2d.setSmall(2,0);
     b2d.setBig(2,0);
     ParallelFor(b2d, [=] AMREX_GPU_DEVICE(int i, int j, int) noexcept
     {
         Real mucape = Real(0);
         int klo = bx.smallEnd(2);
         int khi = bx.bigEnd(2);
         if (ncons > RhoQ1_comp) {
             Real p_sfc = Real(0);
             for (int k = klo; k <= khi; ++k) {
                 Real rho = dat(i,j,k,Rho_comp);
                 if (rho <= Real(0)) { continue; }
                 Real qv = amrex::max(Real(0), dat(i,j,k,RhoQ1_comp) / rho);
                 p_sfc = amrex::max(p_sfc, getPgivenRTh(dat(i,j,k,RhoTheta_comp), qv));
             }
             if (p_sfc > mucape_search_depth_pa()) {
                 Real p_search_min = p_sfc - mucape_search_depth_pa();
                 for (int ks = klo; ks < khi; ++ks) {
                     Real rho_src = dat(i,j,ks,Rho_comp);
                     if (rho_src <= Real(0)) { continue; }
                     Real qv_src = amrex::max(Real(0), dat(i,j,ks,RhoQ1_comp) / rho_src);
                     Real rt_src = dat(i,j,ks,RhoTheta_comp);
                     Real p_src  = getPgivenRTh(rt_src, qv_src);
                     if (p_src < p_search_min) { continue; }
                     Real T_src = getTgivenRandRTh(rho_src, rt_src, qv_src);
                     if (T_src <= Real(0)) { continue; }
                     Real Td_src = mucape_dewpoint_temperature(p_src, qv_src, T_src);
                     Real Tlcl   = mucape_lcl_temperature(T_src, Td_src);
                     Real plcl   = p_src * std::pow(Tlcl / T_src, Cp_d / R_d);
                     plcl = amrex::min(p_src, amrex::max(plcl, mucape_min_pressure_pa()));
                     Real theta_src = getThgivenTandP(T_src, p_src, R_d / Cp_d);
                     Real candidate_cape = Real(0);
                     Real z_prev = z_arr(i,j,ks);
                     Real b_prev = Real(0);
                     bool saturated = false;
                     Real T_sat_prev = Tlcl;
                     Real p_sat_prev = plcl;
                     for (int k = ks + 1; k <= khi; ++k) {
                         Real rho_env = dat(i,j,k,Rho_comp);
                         if (rho_env <= Real(0)) { continue; }
                         Real qv_env = amrex::max(Real(0), dat(i,j,k,RhoQ1_comp) / rho_env);
                         Real rt_env = dat(i,j,k,RhoTheta_comp);
                         Real p_env  = getPgivenRTh(rt_env, qv_env);
                         Real T_env  = getTgivenRandRTh(rho_env, rt_env, qv_env);
                         Real Tv_env = mucape_virtual_temperature(T_env, qv_env);
                         Real z_env  = z_arr(i,j,k);
                         Real T_parcel;
                         Real qv_parcel;
                         if (p_env >= plcl) {
                             T_parcel  = getTgivenPandTh(p_env, theta_src, R_d / Cp_d);
                             qv_parcel = qv_src;
                         } else {
                             if (!saturated) {
                                 saturated = true;
                                 T_sat_prev = Tlcl;
                                 p_sat_prev = plcl;
                             }
                             if (p_env < p_sat_prev) {
                                 T_sat_prev = mucape_integrate_saturated_temperature(T_sat_prev, p_sat_prev, p_env);
                                 p_sat_prev = p_env;
                             }
                             T_parcel  = T_sat_prev;
                             qv_parcel = mucape_qsat(T_parcel, p_env);
                         }
                         Real Tv_parcel = mucape_virtual_temperature(T_parcel, qv_parcel);
                         Real buoyancy = CONST_GRAV * (Tv_parcel - Tv_env) /
                                         amrex::max(Tv_env, mucape_min_temperature());
                         candidate_cape += mucape_positive_area(b_prev, buoyancy, z_env - z_prev);
                         b_prev = buoyancy;
                         z_prev = z_env;
                     }
                     mucape = amrex::max(mucape, candidate_cape);
                 }
             }
         }
         for (int k = klo; k <= khi; ++k) {
             dfab(i,j,k,dcomp) = mucape;
         }
     });
 }
Referenced by ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_dernull() [1/2]
void derived::erf_dernull (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dernull() [2/2]
void derived::erf_dernull (const Box & , FArrayBox & , int , int , const FArrayBox & , const FArrayBox & , const Geometry & , Real , const int * , const int)
Placeholder function that does nothing
 { }
Referenced by ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_derprecipitable() [1/2]
void derived::erf_derprecipitable (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derprecipitable() [2/2]
void derived::erf_derprecipitable (const Box & bx, FArrayBox & derfab, int dcomp, int , const FArrayBox & datfab, const FArrayBox & zcc_fab, const Geometry & , Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     auto const dat = datfab.array(); // cell-centered state vector
     auto dfab      = derfab.array(); // integral of qv to define precipitable water
     // Collapse to i,j box (ignore vertical for now)
     Box b2d = bx;
     b2d.setSmall(2,0);
     b2d.setBig(2,0);
     auto z_arr     = zcc_fab.array(); // cell-centered height z
     ParallelFor(b2d, [=] AMREX_GPU_DEVICE(int i, int j, int) noexcept
     {
         Real int_qv = Real(0.0);
         for (int k = bx.smallEnd(2); k <= bx.bigEnd(2); ++k)
         {
             Real z_hi = Real(0.5) * (z_arr(i,j,k) + z_arr(i,j,k+1));
             Real z_lo = Real(0.5) * (z_arr(i,j,k) + z_arr(i,j,k-1));
             Real dz = z_hi - z_lo;
             Real rhoQ1 = dat(i, j, k, RhoQ1_comp);
             int_qv += rhoQ1 * dz;
         }
         // Store vertical integral into *all* levels for this (i,j)
         for (int k = bx.smallEnd(2); k <= bx.bigEnd(2); ++k) {
             dfab(i, j, k, dcomp) = int_qv;
         }
     });
 }
Referenced by ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_derreflectivity() [1/2]
void derived::erf_derreflectivity (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derreflectivity() [2/2]
void derived::erf_derreflectivity (const Box & bx, FArrayBox & derfab, int dcomp, int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     auto const dat = datfab.array(); // cell-centered state vector
     auto rfab      = derfab.array(); // cell-centered reflectivity
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real rho = dat(i,j,k,Rho_comp);
         Real qv  = std::max(Real(0.0),dat(i,j,k,RhoQ1_comp)/rho);
         Real qpr = std::max(Real(0.0),dat(i,j,k,RhoQ4_comp)/rho);
         Real qps = std::max(Real(0.0),dat(i,j,k,RhoQ5_comp)/rho);
         Real qpg = std::max(Real(0.0),dat(i,j,k,RhoQ6_comp)/rho);
         Real temp  = getTgivenRandRTh(rho, dat(i,j,k,RhoTheta_comp), qv);
         rfab(i, j, k, dcomp) = compute_max_reflectivity_dbz(rho, temp, qpr, qps, qpg,
                                                             1, 1, 1, 1);
     });
 }
Referenced by ERF::Write3DPlotFile().
erf_derrhodivide() [1/2]
void derived::erf_derrhodivide (const amrex::Box & bx, amrex::FArrayBox & derfab, const amrex::FArrayBox & datfab, const int scalar_index)
erf_derrhodivide() [2/2]
void derived::erf_derrhodivide (const Box & bx, FArrayBox & derfab, const FArrayBox & datfab, const int scalar_index)
Function to define a derived quantity by dividing by density (analogous to cons_to_prim)
@params[in] bx box on which to divide by density @params[out] derfab array of derived quantity @params[in] datfab array of data used to construct derived quantity @params[in] scalar_index index of quantity to be divided by density
 {
     // This routine divides any cell-centered conserved quantity by density
     auto const dat = datfab.array();
     auto primitive  = derfab.array();
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         const Real rho       = dat(i, j, k, Rho_comp);
         const Real conserved = dat(i, j, k, scalar_index);
         primitive(i,j,k) = conserved / rho;
     });
 }
Referenced by erf_derKE(), erf_derscalar(), erf_dertheta(), and WriteBndryPlanes::write_planes().
erf_derscalar() [1/2]
void derived::erf_derscalar (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_derscalar() [2/2]
void derived::erf_derscalar (const Box & bx, FArrayBox & derfab, int , int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
Function to define a scalar s by dividing (rho s) by rho
@params[in] bx box on which to divide by density @params[out] derfab array of derived quantity – here it holds scalar s @params[in] datfab array of data used to construct derived quantity
 {
     erf_derrhodivide(bx, derfab, datfab, RhoScalar_comp);
 }
Referenced by ERF::ErrorEst(), ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_dersoundspeed() [1/2]
void derived::erf_dersoundspeed (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dersoundspeed() [2/2]
void derived::erf_dersoundspeed (const Box & bx, FArrayBox & derfab, int , int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
Function to define the sound speed by calling an EOS routine
@params[in] bx box on which to divide by density @params[out] derfab array of derived quantity – here it holds pressure @params[in] datfab array of data used to construct derived quantity
 {
     auto const dat = datfab.array();
     auto cfab      = derfab.array();
     // NOTE: we compute the soundspeed of dry air -- we do not account for any moisture effects here
     Real qv = Real(0.0);
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         const Real rhotheta = dat(i, j, k, RhoTheta_comp);
         const Real rho      = dat(i, j, k, Rho_comp);
         AMREX_ALWAYS_ASSERT(rhotheta > 0);
         cfab(i,j,k) = std::sqrt(Gamma * getPgivenRTh(rhotheta,qv) / rho);
     });
 }
Referenced by ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_dertemp() [1/2]
void derived::erf_dertemp (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dertemp() [2/2]
void derived::erf_dertemp (const Box & bx, FArrayBox & derfab, int , int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
Function to define the temperature by calling an EOS routine
@params[in] bx box on which to divide by density @params[out] derfab array of derived quantity – here it holds pressure @params[in] datfab array of data used to construct derived quantity
 {
     auto const dat = datfab.array();
     auto tfab      = derfab.array();
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         const Real rho = dat(i, j, k, Rho_comp);
         const Real rhotheta = dat(i, j, k, RhoTheta_comp);
         AMREX_ALWAYS_ASSERT(rhotheta > Real(0.0));
         tfab(i,j,k) = getTgivenRandRTh(rho,rhotheta);
     });
 }
Referenced by ERF::Write3DPlotFile(), WriteBndryPlanes::write_planes(), and ERF::WriteSubvolume().
erf_dertheta() [1/2]
void derived::erf_dertheta (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dertheta() [2/2]
void derived::erf_dertheta (const Box & bx, FArrayBox & derfab, int , int , const FArrayBox & datfab, const FArrayBox & , const Geometry & , Real , const int * , const int)
Function to define the potential temperature by calling an EOS routine
@params[in] bx box on which to divide by density @params[out] derfab array of derived quantity – here it holds pressure @params[in] datfab array of data used to construct derived quantity
 {
     erf_derrhodivide(bx, derfab, datfab, RhoTheta_comp);
 }
Referenced by ERF::ErrorEst(), ERF::Write3DPlotFile(), and ERF::WriteSubvolume().
erf_dervortx() [1/2]
void derived::erf_dervortx (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dervortx() [2/2]
void derived::erf_dervortx (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & zcc_fab, const Geometry & geomdata, Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array(); // cell-centered velocity
     auto tfab      = derfab.array(); // cell-centered vorticity x-component
     auto z_arr     = zcc_fab.array(); // cell-centered height z
     const Real two_dy = two * geomdata.CellSize(1);
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real two_dz = z_arr(i,j,k+1) - z_arr(i,j,k-1);
         tfab(i,j,k,dcomp) = (dat(i,j+1,k,2) - dat(i,j-1,k,2)) / two_dy  // dw/dy
                           - (dat(i,j,k+1,1) - dat(i,j,k-1,1)) / two_dz; // dv/dz
     });
 }
Referenced by ERF::Write3DPlotFile().
erf_dervorty() [1/2]
void derived::erf_dervorty (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dervorty() [2/2]
void derived::erf_dervorty (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & zcc_fab, const Geometry & geomdata, Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array(); // cell-centered velocity
     auto tfab      = derfab.array(); // cell-centered vorticity y-component
     auto z_arr     = zcc_fab.array(); // cell-centered height z
     const Real two_dx = two * geomdata.CellSize(0);
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         Real two_dz = z_arr(i,j,k+1) - z_arr(i,j,k-1);
         tfab(i,j,k,dcomp) = (dat(i,j,k+1,0) - dat(i,j,k-1,0)) / two_dz  // du/dz
                           - (dat(i+1,j,k,2) - dat(i-1,j,k,2)) / two_dx; // dw/dx
     });
 }
Referenced by ERF::Write3DPlotFile().
erf_dervortz() [1/2]
void derived::erf_dervortz (const amrex::Box & bx, amrex::FArrayBox & derfab, int dcomp, int ncomp, const amrex::FArrayBox & datfab, const amrex::FArrayBox & zfab, const amrex::Geometry & geomdata, amrex::Real time, const int * bcrec, const int level)
erf_dervortz() [2/2]
void derived::erf_dervortz (const Box & bx, FArrayBox & derfab, int dcomp, int ncomp, const FArrayBox & datfab, const FArrayBox & , const Geometry & geomdata, Real , const int * , const int)
 {
     AMREX_ALWAYS_ASSERT(dcomp == 0);
     AMREX_ALWAYS_ASSERT(ncomp == 1);
     auto const dat = datfab.array(); // cell-centered velocity
     auto tfab      = derfab.array(); // cell-centered vorticity z-component
     const Real dx = geomdata.CellSize(0);
     const Real dy = geomdata.CellSize(2);
     ParallelFor(bx, [=] AMREX_GPU_DEVICE(int i, int j, int k) noexcept
     {
         tfab(i,j,k,dcomp) = (dat(i+1,j,k,1) - dat(i-1,j,k,1)) / (two*dx)  // dv/dx
                           - (dat(i,j+1,k,0) - dat(i,j-1,k,0)) / (two*dy); // du/dy
     });
 }
Referenced by ERF::ErrorEst(), and ERF::Write3DPlotFile().