ERF: shoc::constants Namespace Reference
shoc::constants Namespace Reference
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real min_tke () noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real latent_ice () noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real min_temp () noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real freezing_temp () noexcept
Function Documentation
freezing_temp()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::constants::freezing_temp () noexcept
 { return amrex::Real(273.15); }
latent_ice()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::constants::latent_ice () noexcept
 { return amrex::Real(3.34e5); }
Referenced by shoc::apply_energy_fix_column(), shoc::latent_sublimation(), and shoc::moist_energy().
min_temp()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::constants::min_temp () noexcept
 { return amrex::Real(180.0); }
Referenced by shoc::temperature_from_thetal().
min_tke()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::constants::min_tke () noexcept
 { return amrex::Real(4.0e-4); }
Referenced by shoc::diagnose_active_top().