ERF: surface_layer_stress Namespace Reference
surface_layer_stress Namespace Reference
Classes
struct FaceStressResult
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real conservative_to_kinematic_stress (amrex::Real conservative_stress, amrex::Real rho)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool lsm_flux_is_valid (bool has_flux, bool is_land, amrex::Real flux, amrex::Real undefined)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE FaceStressResult combine_lsm_and_most_stress (amrex::Real rho_low, amrex::Real rho_high, amrex::Real kinematic_low, amrex::Real kinematic_high, bool low_valid, bool high_valid, amrex::Real most_face_stress)
Function Documentation
combine_lsm_and_most_stress()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE FaceStressResult surface_layer_stress::combine_lsm_and_most_stress (amrex::Real rho_low, amrex::Real rho_high, amrex::Real kinematic_low, amrex::Real kinematic_high, bool low_valid, bool high_valid, amrex::Real most_face_stress)
Combine cell-centered kinematic LSM stresses with a conservative MOST fallback stress at one face. The returned cache values are always kinematic, while face_stress is always conservative.
 {
   const amrex::Real half = amrex::Real(0.5);
   FaceStressResult result{
     amrex::Real(0.0),
     low_valid ? kinematic_low
               : conservative_to_kinematic_stress(most_face_stress, rho_low),
     high_valid ? kinematic_high
                : conservative_to_kinematic_stress(most_face_stress, rho_high)};
   if (low_valid && high_valid) {
     result.face_stress =
       half * rho_low * kinematic_low + half * rho_high * kinematic_high;
   } else if (low_valid) {
     result.face_stress =
       half * rho_low * kinematic_low + half * most_face_stress;
   } else if (high_valid) {
     result.face_stress =
       half * rho_high * kinematic_high + half * most_face_stress;
   } else {
     result.face_stress = most_face_stress;
   }
   return result;
 }
Referenced by SurfaceLayer::compute_SurfaceLayer_bcs().
conservative_to_kinematic_stress()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real surface_layer_stress::conservative_to_kinematic_stress (amrex::Real conservative_stress, amrex::Real rho)
LSM cache value from a conservative face stress.
 {
   return conservative_stress / rho;
 }
Referenced by combine_lsm_and_most_stress(), and SurfaceLayer::compute_SurfaceLayer_bcs().
lsm_flux_is_valid()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE bool surface_layer_stress::lsm_flux_is_valid (bool has_flux, bool is_land, amrex::Real flux, amrex::Real undefined)
Test one LSM side without coupling validity to another component's handle.
 {
   return has_flux && is_land && flux < undefined;
 }
Referenced by surface_diagnostics::classify_scalar_source(), and SurfaceLayer::compute_SurfaceLayer_bcs().