ERF: module_mp_morr_two_moment Module Reference
module_mp_morr_two_moment Module Reference
Functions/Subroutines
subroutine morr_two_moment_init (morr_rimed_ice, morr_noice)
subroutine, public mp_morr_two_moment (ITIMESTEP, TH, QV, QC, QR, QI, QS, QG, NI, NS, NR, NG, RHO, PII, P, DT_IN, DZ, HT, W, RAINNC, RAINNCV, SR, SNOWNC, SNOWNCV, GRAUPELNC, GRAUPELNCV, refl_10cm, diagflag, do_radar_ref, qrcuten, qscuten, qicuten, F_QNDROP, qndrop, IDS, IDE, JDS, JDE, KDS, KDE, IMS, IME, JMS, JME, KMS, KME, ITS, ITE, JTS, JTE, KTS, KTE, wetscav_on, rainprod, evapprod, QLSINK, PRECR, PRECI, PRECS, PRECG)
subroutine, private morr_two_moment_micro (i, j, istep, kts, kte, QC3DTEN, QI3DTEN, QNI3DTEN, QR3DTEN, NI3DTEN, NS3DTEN, NR3DTEN, QC3D, QI3D, QNI3D, QR3D, NI3D, NS3D, NR3D, T3DTEN, QV3DTEN, T3D, QV3D, PRES, DZQ, W3D, PRECRT, SNOWRT, SNOWPRT, GRPLPRT, EFFC, EFFI, EFFS, EFFR, DT, QG3DTEN, NG3DTEN, QG3D, NG3D, EFFG, qrcu1d, qscu1d, qicu1d, QGSTEN, QRSTEN, QISTEN, QNISTEN, QCSTEN, nc3d, nc3dten, iinum, c2prec, CSED, ISED, SSED, GSED, RSED)
real(c_double) function, public polysvp (T, TYPE)
real(c_double) function, private gamma (X)
Variables
real(c_double), parameter, private pi = 3.1415926535897932384626434
real(c_double), parameter, private xxx = 0.9189385332046727417803297
integer, private iact
integer, private inum
real(c_double), private ndcnst
integer, private iliq
integer, private inuc
integer, private ibase
integer, private isub
integer, private igraup
integer, private ihail
real(c_double), private ai
real(c_double), private ac
real(c_double), private as
real(c_double), private ar
real(c_double), private ag
real(c_double), private bi
real(c_double), private bc
real(c_double), private bs
real(c_double), private br
real(c_double), private bg
real(c_double), private rhosu
real(c_double), private rhow
real(c_double), private rhoi
real(c_double), private rhosn
real(c_double), private rhog
real(c_double), private aimm
real(c_double), private bimm
real(c_double), private ecr
real(c_double), private dcs
real(c_double), private mi0
real(c_double), private mg0
real(c_double), private f1s
real(c_double), private f2s
real(c_double), private f1r
real(c_double), private f2r
real(c_double), private qsmall
real(c_double), private ci
real(c_double), private di
real(c_double), private cs
real(c_double), private ds
real(c_double), private cg
real(c_double), private dg
real(c_double), private eii
real(c_double), private eci
real(c_double), private rin
real(c_double), private cpw
real(c_double), private c1
real(c_double), private k1
real(c_double), private mw
real(c_double), private osm
real(c_double), private vi
real(c_double), private epsm
real(c_double), private rhoa
real(c_double), private map
real(c_double), private ma
real(c_double), private rr
real(c_double), private bact
real(c_double), private rm1
real(c_double), private rm2
real(c_double), private nanew1
real(c_double), private nanew2
real(c_double), private sig1
real(c_double), private sig2
real(c_double), private f11
real(c_double), private f12
real(c_double), private f21
real(c_double), private f22
real(c_double), private mmult
real(c_double), private lammaxi
real(c_double), private lammini
real(c_double), private lammaxr
real(c_double), private lamminr
real(c_double), private lammaxs
real(c_double), private lammins
real(c_double), private lammaxg
real(c_double), private lamming
real(c_double), private cons1
real(c_double), private cons2
real(c_double), private cons3
real(c_double), private cons4
real(c_double), private cons5
real(c_double), private cons6
real(c_double), private cons7
real(c_double), private cons8
real(c_double), private cons9
real(c_double), private cons10
real(c_double), private cons11
real(c_double), private cons12
real(c_double), private cons13
real(c_double), private cons14
real(c_double), private cons15
real(c_double), private cons16
real(c_double), private cons17
real(c_double), private cons18
real(c_double), private cons19
real(c_double), private cons20
real(c_double), private cons21
real(c_double), private cons22
real(c_double), private cons23
real(c_double), private cons24
real(c_double), private cons25
real(c_double), private cons26
real(c_double), private cons27
real(c_double), private cons28
real(c_double), private cons29
real(c_double), private cons30
real(c_double), private cons31
real(c_double), private cons32
real(c_double), private cons33
real(c_double), private cons34
real(c_double), private cons35
real(c_double), private cons36
real(c_double), private cons37
real(c_double), private cons38
real(c_double), private cons39
real(c_double), private cons40
real(c_double), private cons41
Function/Subroutine Documentation
gamma()
real(c_double) function, private module_mp_morr_two_moment::gamma (real(c_double) X) private
 !----------------------------------------------------------------------
 !
 ! THIS ROUTINE CALCULATES THE GAMMA FUNCTION FOR A REAL(C_DOUBLE) ARGUMENT X.
 !   COMPUTATION IS BASED ON AN ALGORITHM OUTLINED IN REFERENCE 1.
 !   THE PROGRAM USES RATIONAL FUNCTIONS THAT APPROXIMATE THE GAMMA
 !   FUNCTION TO AT LEAST 20 SIGNIFICANT DECIMAL DIGITS.  COEFFICIENTS
 !   FOR THE APPROXIMATION OVER THE INTERVAL (1,2) ARE UNPUBLISHED.
 !   THOSE FOR THE APPROXIMATION FOR X .GE. 12 ARE FROM REFERENCE 2.
 !   THE ACCURACY ACHIEVED DEPENDS ON THE ARITHMETIC SYSTEM, THE
 !   COMPILER, THE INTRINSIC FUNCTIONS, AND PROPER SELECTION OF THE
 !   MACHINE-DEPENDENT CONSTANTS.
 !
 !
 !*******************************************************************
 !*******************************************************************
 !
 ! EXPLANATION OF MACHINE-DEPENDENT CONSTANTS
 !
 ! BETA   - RADIX FOR THE FLOATING-POINT REPRESENTATION
 ! MAXEXP - THE SMALLEST POSITIVE POWER OF BETA THAT OVERFLOWS
 ! XBIG   - THE LARGEST ARGUMENT FOR WHICH GAMMA(X) IS REPRESENTABLE
 !          IN THE MACHINE, I.E., THE SOLUTION TO THE EQUATION
 !                  GAMMA(XBIG) = BETA**MAXEXP
 ! XINF   - THE LARGEST MACHINE REPRESENTABLE FLOATING-POINT NUMBER;
 !          APPROXIMATELY BETA**MAXEXP
 ! EPS    - THE SMALLEST POSITIVE FLOATING-POINT NUMBER SUCH THAT
 !          1.0+EPS .GT. 1.0
 ! XMININ - THE SMALLEST POSITIVE FLOATING-POINT NUMBER SUCH THAT
 !          1/XMININ IS MACHINE REPRESENTABLE
 !
 !     APPROXIMATE VALUES FOR SOME IMPORTANT MACHINES ARE:
 !
 !                            BETA       MAXEXP        XBIG
 !
 ! CRAY-1         (S.P.)        2         8191        966.961
 ! CYBER 180/855
 !   UNDER NOS    (S.P.)        2         1070        177.803
 ! IEEE (IBM/XT,
 !   SUN, ETC.)   (S.P.)        2          128        35.040
 ! IEEE (IBM/XT,
 !   SUN, ETC.)   (D.P.)        2         1024        171.624
 ! IBM 3033       (D.P.)       16           63        57.574
 ! VAX D-FORMAT   (D.P.)        2          127        34.844
 ! VAX G-FORMAT   (D.P.)        2         1023        171.489
 !
 !                            XINF         EPS        XMININ
 !
 ! CRAY-1         (S.P.)   5.45E+2465   7.11E-15    1.84E-2466
 ! CYBER 180/855
 !   UNDER NOS    (S.P.)   1.26E+322    3.55E-15    3.14E-294
 ! IEEE (IBM/XT,
 !   SUN, ETC.)   (S.P.)   3.40E+38     1.19E-7     1.18E-38
 ! IEEE (IBM/XT,
 !   SUN, ETC.)   (D.P.)   1.79D+308    2.22D-16    2.23D-308
 ! IBM 3033       (D.P.)   7.23D+75     2.22D-16    1.39D-76
 ! VAX D-FORMAT   (D.P.)   1.70D+38     1.39D-17    5.88D-39
 ! VAX G-FORMAT   (D.P.)   8.98D+307    1.11D-16    1.12D-308
 !
 !*******************************************************************
 !*******************************************************************
 !
 ! ERROR RETURNS
 !
 !  THE PROGRAM RETURNS THE VALUE XINF FOR SINGULARITIES OR
 !     WHEN OVERFLOW WOULD OCCUR.  THE COMPUTATION IS BELIEVED
 !     TO BE FREE OF UNDERFLOW AND OVERFLOW.
 !
 !
 !  INTRINSIC FUNCTIONS REQUIRED ARE:
 !
 !     INT, DBLE, EXP, LOG, REAL(C_DOUBLE), SIN
 !
 !
 ! REFERENCES:  AN OVERVIEW OF SOFTWARE DEVELOPMENT FOR SPECIAL
 !              FUNCTIONS   W. J. CODY, LECTURE NOTES IN MATHEMATICS,
 !              506, NUMERICAL ANALYSIS DUNDEE, 1975, G. A. WATSON
 !              (ED.), SPRINGER VERLAG, BERLIN, 1976.
 !
 !              COMPUTER APPROXIMATIONS, HART, ET. AL., WILEY AND
 !              SONS, NEW YORK, 1968.
 !
 !  LATEST MODIFICATION: OCTOBER 12, 1989
 !
 !  AUTHORS: W. J. CODY AND L. STOLTZ
 !           APPLIED MATHEMATICS DIVISION
 !           ARGONNE NATIONAL LABORATORY
 !           ARGONNE, IL 60439
 !
 !----------------------------------------------------------------------
       implicit none
       INTEGER I,N
       LOGICAL PARITY
       REAL(C_DOUBLE)                                                          &
           conv,eps,fact,half,one,res,sum,twelve,                    &
           two,x,xbig,xden,xinf,xminin,xnum,y,y1,ysq,z,zero
       REAL(C_DOUBLE), DIMENSION(7) :: C
       REAL(C_DOUBLE), DIMENSION(8) :: P
       REAL(C_DOUBLE), DIMENSION(8) :: Q
 !----------------------------------------------------------------------
 !  MATHEMATICAL CONSTANTS
 !----------------------------------------------------------------------
       DATA one,half,twelve,two,zero/1.0e0,0.5e0,12.0e0,2.0e0,0.0e0/
 !----------------------------------------------------------------------
 !  MACHINE DEPENDENT PARAMETERS
 !----------------------------------------------------------------------
       DATA xbig,xminin,eps/35.040e0,1.18e-38,1.19e-7/,xinf/3.4e38/
 !----------------------------------------------------------------------
 !  NUMERATOR AND DENOMINATOR COEFFICIENTS FOR RATIONAL MINIMAX
 !     APPROXIMATION OVER (1,2).
 !----------------------------------------------------------------------
       DATA p/-1.71618513886549492533811e+0,2.47656508055759199108314e+1,  &
              -3.79804256470945635097577e+2,6.29331155312818442661052e+2,  &
              8.66966202790413211295064e+2,-3.14512729688483675254357e+4,  &
              -3.61444134186911729807069e+4,6.64561438202405440627855e+4/
       DATA q/-3.08402300119738975254353e+1,3.15350626979604161529144e+2,  &
              -1.01515636749021914166146e+3,-3.10777167157231109440444e+3, &
               2.25381184209801510330112e+4,4.75584627752788110767815e+3,  &
             -1.34659959864969306392456e+5,-1.15132259675553483497211e+5/
 !----------------------------------------------------------------------
 !  COEFFICIENTS FOR MINIMAX APPROXIMATION OVER (12, INF).
 !----------------------------------------------------------------------
       DATA c/-1.910444077728e-03,8.4171387781295e-04,                      &
            -5.952379913043012e-04,7.93650793500350248e-04,                                 &
            -2.777777777777681622553e-03,8.333333333333333331554247e-02,    &
             5.7083835261e-03/
 !----------------------------------------------------------------------
 !  STATEMENT FUNCTIONS FOR CONVERSION BETWEEN INTEGER AND FLOAT
 !----------------------------------------------------------------------
       conv(i) = real(i)
       parity=.false.
       fact=one
       n=0
       y=x
       IF(y.LE.zero)THEN
 !----------------------------------------------------------------------
 !  ARGUMENT IS NEGATIVE
 !----------------------------------------------------------------------
         y=-x
         y1=aint(y)
         res=y-y1
         IF(res.NE.zero)THEN
           IF(y1.NE.aint(y1*half)*two)parity=.true.
           fact=-pi/sin(pi*res)
           y=y+one
         ELSE
           res=xinf
           GOTO 900
         ENDIF
       ENDIF
 !----------------------------------------------------------------------
 !  ARGUMENT IS POSITIVE
 !----------------------------------------------------------------------
       IF(y.LT.eps)THEN
 !----------------------------------------------------------------------
 !  ARGUMENT .LT. EPS
 !----------------------------------------------------------------------
         IF(y.GE.xminin)THEN
           res=one/y
         ELSE
           res=xinf
           GOTO 900
         ENDIF
       ELSEIF(y.LT.twelve)THEN
         y1=y
         IF(y.LT.one)THEN
 !----------------------------------------------------------------------
 !  0.0 .LT. ARGUMENT .LT. 1.0
 !----------------------------------------------------------------------
           z=y
           y=y+one
         ELSE
 !----------------------------------------------------------------------
 !  1.0 .LT. ARGUMENT .LT. 12.0, REDUCE ARGUMENT IF NECESSARY
 !----------------------------------------------------------------------
           n=int(y)-1
           y=y-conv(n)
           z=y-one
         ENDIF
 !----------------------------------------------------------------------
 !  EVALUATE APPROXIMATION FOR 1.0 .LT. ARGUMENT .LT. 2.0
 !----------------------------------------------------------------------
         xnum=zero
         xden=one
         DO i=1,8
           xnum=(xnum+p(i))*z
           xden=xden*z+q(i)
         END DO
         res=xnum/xden+one
         IF(y1.LT.y)THEN
 !----------------------------------------------------------------------
 !  ADJUST RESULT FOR CASE  0.0 .LT. ARGUMENT .LT. 1.0
 !----------------------------------------------------------------------
           res=res/y1
         ELSEIF(y1.GT.y)THEN
 !----------------------------------------------------------------------
 !  ADJUST RESULT FOR CASE  2.0 .LT. ARGUMENT .LT. 12.0
 !----------------------------------------------------------------------
           DO i=1,n
             res=res*y
             y=y+one
           END DO
         ENDIF
       ELSE
 !----------------------------------------------------------------------
 !  EVALUATE FOR ARGUMENT .GE. 12.0,
 !----------------------------------------------------------------------
         IF(y.LE.xbig)THEN
           ysq=y*y
           sum=c(7)
           DO i=1,6
             sum=sum/ysq+c(i)
           END DO
           sum=sum/y-y+xxx
           sum=sum+(y-half)*log(y)
           res=exp(sum)
         ELSE
           res=xinf
           GOTO 900
         ENDIF
       ENDIF
 !----------------------------------------------------------------------
 !  FINAL ADJUSTMENTS AND RETURN
 !----------------------------------------------------------------------
       IF(parity)res=-res
       IF(fact.NE.one)res=fact/res
   900 gamma=res
       RETURN
 ! ---------- LAST LINE OF GAMMA ----------
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
morr_two_moment_init()
subroutine module_mp_morr_two_moment::morr_two_moment_init (integer, intent(in) morr_rimed_ice, integer, intent(in) morr_noice)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! THIS SUBROUTINE INITIALIZES ALL PHYSICAL CONSTANTS AMND PARAMETERS
 ! NEEDED BY THE MICROPHYSICS SCHEME.
 ! NEEDS TO BE CALLED AT FIRST TIME STEP, PRIOR TO CALL TO MAIN MICROPHYSICS INTERFACE
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
       IMPLICIT NONE
       INTEGER, INTENT(IN):: morr_rimed_ice ! RAS
       INTEGER, INTENT(IN):: morr_noice
       integer n,i
       print *,'IN MORR_TWO_MOMENT_INIT ',"with noice = ",morr_noice
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! THE FOLLOWING PARAMETERS ARE USER-DEFINED SWITCHES AND NEED TO BE
 ! SET PRIOR TO CODE COMPILATION
 ! INUM IS AUTOMATICALLY SET TO 0 FOR WRF-CHEM BELOW,
 ! ALLOWING PREDICTION OF DROPLET CONCENTRATION
 ! THUS, THIS PARAMETER SHOULD NOT BE CHANGED HERE
 ! AND SHOULD BE LEFT TO 1
       inum = 1
 ! SET CONSTANT DROPLET CONCENTRATION (UNITS OF CM-3)
 ! IF NO COUPLING WITH WRF-CHEM
       ndcnst = 250.
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! NOTE, THE FOLLOWING OPTIONS RELATED TO DROPLET ACTIVATION
 ! (IACT, IBASE, ISUB) ARE NOT AVAILABLE IN CURRENT VERSION
 ! FOR WRF-CHEM, DROPLET ACTIVATION IS PERFORMED
 ! IN 'MIX_ACTIVATE', NOT IN MICROPHYSICS SCHEME
 ! IACT = 1, USE POWER-LAW CCN SPECTRA, NCCN = CS^K
 ! IACT = 2, USE LOGNORMAL AEROSOL SIZE DIST TO DERIVE CCN SPECTRA
       iact = 2
 ! IBASE = 1, NEGLECT DROPLET ACTIVATION AT LATERAL CLOUD EDGES DUE TO
 !             UNRESOLVED ENTRAINMENT AND MIXING, ACTIVATE
 !             AT CLOUD BASE OR IN REGION WITH LITTLE CLOUD WATER USING
 !             NON-EQULIBRIUM SUPERSATURATION ASSUMING NO INITIAL CLOUD WATER,
 !             IN CLOUD INTERIOR ACTIVATE USING EQUILIBRIUM SUPERSATURATION
 ! IBASE = 2, ASSUME DROPLET ACTIVATION AT LATERAL CLOUD EDGES DUE TO
 !             UNRESOLVED ENTRAINMENT AND MIXING DOMINATES,
 !             ACTIVATE DROPLETS EVERYWHERE IN THE CLOUD USING NON-EQUILIBRIUM
 !             SUPERSATURATION ASSUMING NO INITIAL CLOUD WATER, BASED ON THE
 !             LOCAL SUB-GRID AND/OR GRID-SCALE VERTICAL VELOCITY
 !             AT THE GRID POINT
 ! NOTE: ONLY USED FOR PREDICTED DROPLET CONCENTRATION (INUM = 0)
       ibase = 2
 ! INCLUDE SUB-GRID VERTICAL VELOCITY (standard deviation of w) IN DROPLET ACTIVATION
 ! ISUB = 0, INCLUDE SUB-GRID W (RECOMMENDED FOR LOWER RESOLUTION)
 ! currently, sub-grid w is constant of 0.5 m/s (not coupled with PBL/turbulence scheme)
 ! ISUB = 1, EXCLUDE SUB-GRID W, ONLY USE GRID-SCALE W
 ! NOTE: ONLY USED FOR PREDICTED DROPLET CONCENTRATION (INUM = 0)
       isub = 0
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
       if(morr_noice .eq. 1) then
 ! SWITCH FOR LIQUID-ONLY RUN
 ! ILIQ = 0, INCLUDE ICE
 ! ILIQ = 1, LIQUID ONLY, NO ICE
       iliq = 1
 ! SWITCH FOR ICE NUCLEATION
 ! INUC = 0, USE FORMULA FROM RASMUSSEN ET AL. 2002 (MID-LATITUDE)
 !      = 1, USE MPACE OBSERVATIONS (ARCTIC ONLY)
       inuc = 0
 ! SWITCH FOR GRAUPEL/HAIL NO GRAUPEL/HAIL
 ! IGRAUP = 0, INCLUDE GRAUPEL/HAIL
 ! IGRAUP = 1, NO GRAUPEL/HAIL
       igraup = 1
 ! HM ADDED 11/7/07
 ! SWITCH FOR HAIL/GRAUPEL
 ! IHAIL = 0, DENSE PRECIPITATING ICE IS GRAUPEL
 ! IHAIL = 1, DENSE PRECIPITATING ICE IS HAIL
 ! NOTE ---> RECOMMEND IHAIL = 1 FOR CONTINENTAL DEEP CONVECTION
       !IHAIL = 0 !changed to namelist option (morr_rimed_ice) by RAS
       ! Check if namelist option is feasible, otherwise default to graupel - RAS
       IF (morr_rimed_ice .eq. 1) THEN
          ihail = 1
       ELSE
          ihail = 0
       ENDIF
 else
 ! SWITCH FOR LIQUID-ONLY RUN
 ! ILIQ = 0, INCLUDE ICE
 ! ILIQ = 1, LIQUID ONLY, NO ICE
       iliq = 0
 ! SWITCH FOR ICE NUCLEATION
 ! INUC = 0, USE FORMULA FROM RASMUSSEN ET AL. 2002 (MID-LATITUDE)
 !      = 1, USE MPACE OBSERVATIONS (ARCTIC ONLY)
       inuc = 0
 ! SWITCH FOR GRAUPEL/HAIL NO GRAUPEL/HAIL
 ! IGRAUP = 0, INCLUDE GRAUPEL/HAIL
 ! IGRAUP = 1, NO GRAUPEL/HAIL
       igraup = 0
 ! HM ADDED 11/7/07
 ! SWITCH FOR HAIL/GRAUPEL
 ! IHAIL = 0, DENSE PRECIPITATING ICE IS GRAUPEL
 ! IHAIL = 1, DENSE PRECIPITATING ICE IS HAIL
 ! NOTE ---> RECOMMEND IHAIL = 1 FOR CONTINENTAL DEEP CONVECTION
       !IHAIL = 0 !changed to namelist option (morr_rimed_ice) by RAS
       ! Check if namelist option is feasible, otherwise default to graupel - RAS
       IF (morr_rimed_ice .eq. 1) THEN
          ihail = 1
       ELSE
          ihail = 0
       ENDIF
 endif
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! SET PHYSICAL CONSTANTS
 ! FALLSPEED PARAMETERS (V=AD^B)
          ai = 700.
          ac = 3.e7
          as = 11.72
          ar = 841.99667
          bi = 1.
          bc = 2.
          bs = 0.41
          br = 0.8
          IF (ihail.EQ.0) THEN
              ag = 19.3
              bg = 0.37
          ELSE ! (MATSUN AND HUGGINS 1980)
              ag = 114.5
              bg = 0.5
          END IF
 ! CONSTANTS AND PARAMETERS
 !        R = 287.15
 !        RV = 461.5
 !        CP = 1005.
          rhosu = 85000./(287.15*273.15)
          rhow = 997.
          rhoi = 500.
          rhosn = 100.
          IF (ihail.EQ.0) THEN
              rhog = 400.
          ELSE
              rhog = 900.
          END IF
          aimm = 0.66
          bimm = 100.
          ecr = 1.
          dcs = 125.e-6
          mi0 = 4./3.*pi*rhoi*(10.e-6)**3
          mg0 = 1.6e-10
          f1s = 0.86
          f2s = 0.28
          f1r = 0.78
 !        F2R = 0.32
 ! fix 053011
          f2r = 0.308
 !        G = 9.806
          qsmall = 1.d-14
          print *,'SETTING SMALL TO ',qsmall
          eii = 0.1
          eci = 0.7
 ! HM, ADD FOR V3.2
 ! hm, 7/23/13
 !         CPW = 4218.
          cpw = 4187.
 ! SIZE DISTRIBUTION PARAMETERS
          ci = rhoi*pi/6.
          di = 3.
          cs = rhosn*pi/6.
          ds = 3.
          cg = rhog*pi/6.
          dg = 3.
 ! RADIUS OF CONTACT NUCLEI
          rin = 0.1e-6
          mmult = 4./3.*pi*rhoi*(5.e-6)**3
 ! SIZE LIMITS FOR LAMBDA
          lammaxi = 1./1.e-6
          lammini = 1./(2.*dcs+100.e-6)
          lammaxr = 1./20.e-6
 !         LAMMINR = 1./500.E-6
          lamminr = 1./2800.e-6
          lammaxs = 1./10.e-6
          lammins = 1./2000.e-6
          lammaxg = 1./20.e-6
          lamming = 1./2000.e-6
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! note: these parameters only used by the non-wrf-chem version of the
 !       scheme with predicted droplet number
 ! CCN SPECTRA FOR IACT = 1
 ! MARITIME
 ! MODIFIED FROM RASMUSSEN ET AL. 2002
 ! NCCN = C*S^K, NCCN IS IN CM-3, S IS SUPERSATURATION RATIO IN %
               k1 = 0.4
               c1 = 120.
 ! CONTINENTAL
 !              K1 = 0.5
 !              C1 = 1000.
 ! AEROSOL ACTIVATION PARAMETERS FOR IACT = 2
 ! PARAMETERS CURRENTLY SET FOR AMMONIUM SULFATE
          mw = 0.018
          osm = 1.
          vi = 3.
          epsm = 0.7
          rhoa = 1777.
          map = 0.132
          ma = 0.0284
 ! hm fix 6/23/16
 !         RR = 8.3187
          rr = 8.3145
          bact = vi*osm*epsm*mw*rhoa/(map*rhow)
 ! AEROSOL SIZE DISTRIBUTION PARAMETERS CURRENTLY SET FOR MPACE
 ! (see morrison et al. 2007, JGR)
 ! MODE 1
          rm1 = 0.052e-6
          sig1 = 2.04
          nanew1 = 72.2e6
          f11 = 0.5*exp(2.5*(log(sig1))**2)
          f21 = 1.+0.25*log(sig1)
 ! MODE 2
          rm2 = 1.3e-6
          sig2 = 2.5
          nanew2 = 1.8e6
          f12 = 0.5*exp(2.5*(log(sig2))**2)
          f22 = 1.+0.25*log(sig2)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! CONSTANTS FOR EFFICIENCY
          cons1=gamma(1.+ds)*cs
          cons2=gamma(1.+dg)*cg
          cons3=gamma(4.+bs)/6.
          cons4=gamma(4.+br)/6.
          cons5=gamma(1.+bs)
          cons6=gamma(1.+br)
          cons7=gamma(4.+bg)/6.
          cons8=gamma(1.+bg)
          cons9=gamma(5./2.+br/2.)
          cons10=gamma(5./2.+bs/2.)
          cons11=gamma(5./2.+bg/2.)
          cons12=gamma(1.+di)*ci
          cons13=gamma(bs+3.)*pi/4.*eci
          cons14=gamma(bg+3.)*pi/4.*eci
          cons15=-1108.*eii*pi**((1.-bs)/3.)*rhosn**((-2.-bs)/3.)/(4.*720.)
          cons16=gamma(bi+3.)*pi/4.*eci
          cons17=4.*2.*3.*rhosu*pi*eci*eci*gamma(2.*bs+2.)/(8.*(rhog-rhosn))
          cons18=rhosn*rhosn
          cons19=rhow*rhow
          cons20=20.*pi*pi*rhow*bimm
          cons21=4./(dcs*rhoi)
          cons22=pi*rhoi*dcs**3/6.
          cons23=pi/4.*eii*gamma(bs+3.)
          cons24=pi/4.*ecr*gamma(br+3.)
          cons25=pi*pi/24.*rhow*ecr*gamma(br+6.)
          cons26=pi/6.*rhow
          cons27=gamma(1.+bi)
          cons28=gamma(4.+bi)/6.
          cons29=4./3.*pi*rhow*(25.e-6)**3
          cons30=4./3.*pi*rhow
          cons31=pi*pi*ecr*rhosn
          cons32=pi/2.*ecr
          cons33=pi*pi*ecr*rhog
          cons34=5./2.+br/2.
          cons35=5./2.+bs/2.
          cons36=5./2.+bg/2.
          cons37=4.*pi*1.38e-23/(6.*pi*rin)
          cons38=pi*pi/3.*rhow
          cons39=pi*pi/36.*rhow*bimm
          cons40=pi/6.*bimm
          cons41=pi*pi*ecr*rhow
Referenced by mp_morr_two_moment_isohelper::morr_two_moment_init_c().
morr_two_moment_micro()
subroutine, private module_mp_morr_two_moment::morr_two_moment_micro (integer, intent(in) i, integer, intent(in) j, integer, intent(in) istep, integer, intent(in) kts, integer, intent(in) kte, real(c_double), dimension(kts:kte) QC3DTEN, real(c_double), dimension(kts:kte) QI3DTEN, real(c_double), dimension(kts:kte) QNI3DTEN, real(c_double), dimension(kts:kte) QR3DTEN, real(c_double), dimension(kts:kte) NI3DTEN, real(c_double), dimension(kts:kte) NS3DTEN, real(c_double), dimension(kts:kte) NR3DTEN, real(c_double), dimension(kts:kte) QC3D, real(c_double), dimension(kts:kte) QI3D, real(c_double), dimension(kts:kte) QNI3D, real(c_double), dimension(kts:kte) QR3D, real(c_double), dimension(kts:kte) NI3D, real(c_double), dimension(kts:kte) NS3D, real(c_double), dimension(kts:kte) NR3D, real(c_double), dimension(kts:kte) T3DTEN, real(c_double), dimension(kts:kte) QV3DTEN, real(c_double), dimension(kts:kte) T3D, real(c_double), dimension(kts:kte) QV3D, real(c_double), dimension(kts:kte) PRES, real(c_double), dimension(kts:kte) DZQ, real(c_double), dimension(kts:kte) W3D, real(c_double) PRECRT, real(c_double) SNOWRT, real(c_double) SNOWPRT, real(c_double) GRPLPRT, real(c_double), dimension(kts:kte) EFFC, real(c_double), dimension(kts:kte) EFFI, real(c_double), dimension(kts:kte) EFFS, real(c_double), dimension(kts:kte) EFFR, real(c_double) DT, real(c_double), dimension(kts:kte) QG3DTEN, real(c_double), dimension(kts:kte) NG3DTEN, real(c_double), dimension(kts:kte) QG3D, real(c_double), dimension(kts:kte) NG3D, real(c_double), dimension(kts:kte) EFFG, real(c_double), dimension(kts:kte) qrcu1d, real(c_double), dimension(kts:kte) qscu1d, real(c_double), dimension(kts:kte) qicu1d, real(c_double), dimension(kts:kte) QGSTEN, real(c_double), dimension(kts:kte) QRSTEN, real(c_double), dimension(kts:kte) QISTEN, real(c_double), dimension(kts:kte) QNISTEN, real(c_double), dimension(kts:kte) QCSTEN, real(c_double), dimension(kts:kte) nc3d, real(c_double), dimension(kts:kte) nc3dten, integer, intent(in) iinum, real(c_double), dimension(kts:kte) c2prec, real(c_double), dimension(kts:kte) CSED, real(c_double), dimension(kts:kte) ISED, real(c_double), dimension(kts:kte) SSED, real(c_double), dimension(kts:kte) GSED, real(c_double), dimension(kts:kte) RSED) private
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! THIS PROGRAM IS THE MAIN TWO-MOMENT MICROPHYSICS SUBROUTINE DESCRIBED BY
 ! MORRISON ET AL. 2005 JAS AND MORRISON ET AL. 2009 MWR
 ! THIS SCHEME IS A BULK DOUBLE-MOMENT SCHEME THAT PREDICTS MIXING
 ! RATIOS AND NUMBER CONCENTRATIONS OF FIVE HYDROMETEOR SPECIES:
 ! CLOUD DROPLETS, CLOUD (SMALL) ICE, RAIN, SNOW, AND GRAUPEL/HAIL.
 ! CODE STRUCTURE: MAIN SUBROUTINE IS 'MORR_TWO_MOMENT'. ALSO INCLUDED IN THIS FILE IS
 ! 'FUNCTION POLYSVP', 'FUNCTION DERF1', AND
 ! 'FUNCTION GAMMA'.
 ! NOTE: THIS SUBROUTINE USES 1D ARRAY IN VERTICAL (COLUMN), EVEN THOUGH VARIABLES ARE CALLED '3D'......
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! DECLARATIONS
       IMPLICIT NONE
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! THESE VARIABLES BELOW MUST BE LINKED WITH THE MAIN MODEL.
 ! DEFINE ARRAY SIZES
 ! INPUT NUMBER OF GRID CELLS
 ! INPUT/OUTPUT PARAMETERS                                 ! DESCRIPTION (UNITS)
       INTEGER, INTENT( IN)  :: i,j,istep,kts,kte
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QC3DTEN            ! CLOUD WATER MIXING RATIO TENDENCY (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QI3DTEN            ! CLOUD ICE MIXING RATIO TENDENCY (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QNI3DTEN           ! SNOW MIXING RATIO TENDENCY (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QR3DTEN            ! RAIN MIXING RATIO TENDENCY (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NI3DTEN            ! CLOUD ICE NUMBER CONCENTRATION (1/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NS3DTEN            ! SNOW NUMBER CONCENTRATION (1/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NR3DTEN            ! RAIN NUMBER CONCENTRATION (1/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QC3D               ! CLOUD WATER MIXING RATIO (KG/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QI3D               ! CLOUD ICE MIXING RATIO (KG/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QNI3D              ! SNOW MIXING RATIO (KG/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QR3D               ! RAIN MIXING RATIO (KG/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NI3D               ! CLOUD ICE NUMBER CONCENTRATION (1/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NS3D               ! SNOW NUMBER CONCENTRATION (1/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NR3D               ! RAIN NUMBER CONCENTRATION (1/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  T3DTEN             ! TEMPERATURE TENDENCY (K/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QV3DTEN            ! WATER VAPOR MIXING RATIO TENDENCY (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  T3D                ! TEMPERATURE (K)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QV3D               ! WATER VAPOR MIXING RATIO (KG/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRES               ! ATMOSPHERIC PRESSURE (PA)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  DZQ                ! DIFFERENCE IN HEIGHT ACROSS LEVEL (m)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  W3D                ! GRID-SCALE VERTICAL VELOCITY (M/S)
 ! below for wrf-chem
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  nc3d
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  nc3dten
       integer, intent(in) :: iinum
 ! HM ADDED GRAUPEL VARIABLES
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QG3DTEN            ! GRAUPEL MIX RATIO TENDENCY (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NG3DTEN            ! GRAUPEL NUMB CONC TENDENCY (1/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QG3D            ! GRAUPEL MIX RATIO (KG/KG)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NG3D            ! GRAUPEL NUMBER CONC (1/KG)
 ! HM, ADD 1/16/07, SEDIMENTATION TENDENCIES FOR MIXING RATIO
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QGSTEN            ! GRAUPEL SED TEND (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QRSTEN            ! RAIN SED TEND (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QISTEN            ! CLOUD ICE SED TEND (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QNISTEN           ! SNOW SED TEND (KG/KG/S)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QCSTEN            ! CLOUD WAT SED TEND (KG/KG/S)
 ! hm add cumulus tendencies for precip
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   qrcu1d
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   qscu1d
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   qicu1d
 ! OUTPUT VARIABLES
         REAL(C_DOUBLE) PRECRT                ! TOTAL PRECIP PER TIME STEP (mm)
         REAL(C_DOUBLE) SNOWRT                ! SNOW PER TIME STEP (mm)
 ! hm added 7/13/13
         REAL(C_DOUBLE) SNOWPRT      ! TOTAL CLOUD ICE PLUS SNOW PER TIME STEP (mm)
         REAL(C_DOUBLE) GRPLPRT      ! TOTAL GRAUPEL PER TIME STEP (mm)
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EFFC            ! DROPLET EFFECTIVE RADIUS (MICRON)
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EFFI            ! CLOUD ICE EFFECTIVE RADIUS (MICRON)
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EFFS            ! SNOW EFFECTIVE RADIUS (MICRON)
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EFFR            ! RAIN EFFECTIVE RADIUS (MICRON)
         REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EFFG            ! GRAUPEL EFFECTIVE RADIUS (MICRON)
 ! MODEL INPUT PARAMETERS (FORMERLY IN COMMON BLOCKS)
         REAL(C_DOUBLE) DT         ! MODEL TIME STEP (SEC)
 !.....................................................................................................
 ! LOCAL VARIABLES: ALL PARAMETERS BELOW ARE LOCAL TO SCHEME AND DON'T NEED TO COMMUNICATE WITH THE
 ! REST OF THE MODEL.
 ! SIZE PARAMETER VARIABLES
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: LAMC          ! SLOPE PARAMETER FOR DROPLETS (M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: LAMI          ! SLOPE PARAMETER FOR CLOUD ICE (M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: LAMS          ! SLOPE PARAMETER FOR SNOW (M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: LAMR          ! SLOPE PARAMETER FOR RAIN (M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: LAMG          ! SLOPE PARAMETER FOR GRAUPEL (M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: CDIST1        ! PSD PARAMETER FOR DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: N0I           ! INTERCEPT PARAMETER FOR CLOUD ICE (KG-1 M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: N0S           ! INTERCEPT PARAMETER FOR SNOW (KG-1 M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: N0RR          ! INTERCEPT PARAMETER FOR RAIN (KG-1 M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: N0G           ! INTERCEPT PARAMETER FOR GRAUPEL (KG-1 M-1)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) :: PGAM          ! SPECTRAL SHAPE PARAMETER FOR DROPLETS
 ! MICROPHYSICAL PROCESSES
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSUBC     ! LOSS OF NC DURING EVAP
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSUBI     ! LOSS OF NI DURING SUB.
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSUBS     ! LOSS OF NS DURING SUB.
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSUBR     ! LOSS OF NR DURING EVAP
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRD       ! DEP CLOUD ICE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRE       ! EVAP OF RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRDS      ! DEP SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NNUCCC    ! CHANGE N DUE TO CONTACT FREEZ DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  MNUCCC    ! CHANGE Q DUE TO CONTACT FREEZ DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRA       ! ACCRETION DROPLETS BY RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRC       ! AUTOCONVERSION DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PCC       ! COND/EVAP DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NNUCCD    ! CHANGE N FREEZING AEROSOL (PRIM ICE NUCLEATION)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  MNUCCD    ! CHANGE Q FREEZING AEROSOL (PRIM ICE NUCLEATION)
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  MNUCCR    ! CHANGE Q DUE TO CONTACT FREEZ RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NNUCCR    ! CHANGE N DUE TO CONTACT FREEZ RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRA      ! CHANGE IN N DUE TO DROPLET ACC BY RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NRAGG     ! SELF-COLLECTION/BREAKUP OF RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSAGG     ! SELF-COLLECTION OF SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRC      ! CHANGE NC AUTOCONVERSION DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRC1      ! CHANGE NR AUTOCONVERSION DROPLETS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRAI      ! CHANGE Q ACCRETION CLOUD ICE BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRCI      ! CHANGE Q AUTOCONVERSIN CLOUD ICE TO SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PSACWS    ! CHANGE Q DROPLET ACCRETION BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPSACWS   ! CHANGE N DROPLET ACCRETION BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PSACWI    ! CHANGE Q DROPLET ACCRETION BY CLOUD ICE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPSACWI   ! CHANGE N DROPLET ACCRETION BY CLOUD ICE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRCI     ! CHANGE N AUTOCONVERSION CLOUD ICE BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRAI     ! CHANGE N ACCRETION CLOUD ICE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NMULTS    ! ICE MULT DUE TO RIMING DROPLETS BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NMULTR    ! ICE MULT DUE TO RIMING RAIN BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QMULTS    ! CHANGE Q DUE TO ICE MULT DROPLETS/SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QMULTR    ! CHANGE Q DUE TO ICE RAIN/SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRACS     ! CHANGE Q RAIN-SNOW COLLECTION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRACS    ! CHANGE N RAIN-SNOW COLLECTION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PCCN      ! CHANGE Q DROPLET ACTIVATION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PSMLT     ! CHANGE Q MELTING SNOW TO RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  EVPMS     ! CHNAGE Q MELTING SNOW EVAPORATING
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSMLTS    ! CHANGE N MELTING SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSMLTR    ! CHANGE N MELTING SNOW TO RAIN
 ! HM ADDED 12/13/06
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PIACR     ! CHANGE QR, ICE-RAIN COLLECTION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NIACR     ! CHANGE N, ICE-RAIN COLLECTION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRACI     ! CHANGE QI, ICE-RAIN COLLECTION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PIACRS     ! CHANGE QR, ICE RAIN COLLISION, ADDED TO SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NIACRS     ! CHANGE N, ICE RAIN COLLISION, ADDED TO SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRACIS     ! CHANGE QI, ICE RAIN COLLISION, ADDED TO SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  EPRD      ! SUBLIMATION CLOUD ICE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  EPRDS     ! SUBLIMATION SNOW
 ! HM ADDED GRAUPEL PROCESSES
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRACG    ! CHANGE IN Q COLLECTION RAIN BY GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PSACWG    ! CHANGE IN Q COLLECTION DROPLETS BY GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PGSACW    ! CONVERSION Q TO GRAUPEL DUE TO COLLECTION DROPLETS BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PGRACS    ! CONVERSION Q TO GRAUPEL DUE TO COLLECTION RAIN BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PRDG    ! DEP OF GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  EPRDG    ! SUB OF GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  EVPMG    ! CHANGE Q MELTING OF GRAUPEL AND EVAPORATION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PGMLT    ! CHANGE Q MELTING OF GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPRACG    ! CHANGE N COLLECTION RAIN BY GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NPSACWG    ! CHANGE N COLLECTION DROPLETS BY GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSCNG    ! CHANGE N CONVERSION TO GRAUPEL DUE TO COLLECTION DROPLETS BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NGRACS    ! CHANGE N CONVERSION TO GRAUPEL DUE TO COLLECTION RAIN BY SNOW
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NGMLTG    ! CHANGE N MELTING GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NGMLTR    ! CHANGE N MELTING GRAUPEL TO RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NSUBG    ! CHANGE N SUB/DEP OF GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  PSACR    ! CONVERSION DUE TO COLL OF SNOW BY RAIN
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NMULTG    ! ICE MULT DUE TO ACC DROPLETS BY GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NMULTRG    ! ICE MULT DUE TO ACC RAIN BY GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QMULTG    ! CHANGE Q DUE TO ICE MULT DROPLETS/GRAUPEL
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  QMULTRG    ! CHANGE Q DUE TO ICE MULT RAIN/GRAUPEL
 ! TIME-VARYING ATMOSPHERIC PARAMETERS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   KAP   ! THERMAL CONDUCTIVITY OF AIR
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EVS   ! SATURATION VAPOR PRESSURE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   EIS   ! ICE SATURATION VAPOR PRESSURE
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   QVS   ! SATURATION MIXING RATIO
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   QVI   ! ICE SATURATION MIXING RATIO
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   QVQVS ! SAUTRATION RATIO
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   QVQVSI! ICE SATURAION RATIO
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   DV    ! DIFFUSIVITY OF WATER VAPOR IN AIR
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   XXLS  ! LATENT HEAT OF SUBLIMATION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   XXLV  ! LATENT HEAT OF VAPORIZATION
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   CPM   ! SPECIFIC HEAT AT CONST PRESSURE FOR MOIST AIR
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   MU    ! VISCOCITY OF AIR
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   SC    ! SCHMIDT NUMBER
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   XLF   ! LATENT HEAT OF FREEZING
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   RHO   ! AIR DENSITY
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   AB    ! CORRECTION TO CONDENSATION RATE DUE TO LATENT HEATING
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   ABI    ! CORRECTION TO DEPOSITION RATE DUE TO LATENT HEATING
 ! TIME-VARYING MICROPHYSICS PARAMETERS
      REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   DAP    ! DIFFUSIVITY OF AEROSOL
      REAL(C_DOUBLE)    NACNT                    ! NUMBER OF CONTACT IN
      REAL(C_DOUBLE)    FMULT                    ! TEMP.-DEP. PARAMETER FOR RIME-SPLINTERING
      REAL(C_DOUBLE)    COFFI                    ! ICE AUTOCONVERSION PARAMETER
 ! FALL SPEED WORKING VARIABLES (DEFINED IN CODE)
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::    DUMI,DUMR,DUMFNI,DUMG,DUMFNG
       REAL(C_DOUBLE) UNI, UMI,UMR
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::    FR, FI, FNI,FG,FNG
       REAL(C_DOUBLE) RGVM
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   FALOUTR,FALOUTI,FALOUTNI
       REAL(C_DOUBLE) FALTNDR,FALTNDI,FALTNDNI,RHO2
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   DUMQS,DUMFNS
       REAL(C_DOUBLE) UMS,UNS
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   FS,FNS, FALOUTS,FALOUTNS,FALOUTG,FALOUTNG
       REAL(C_DOUBLE) FALTNDS,FALTNDNS,UNR,FALTNDG,FALTNDNG
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::    DUMC,DUMFNC
       REAL(C_DOUBLE) UNC,UMC,UNG,UMG
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   FC,FALOUTC,FALOUTNC
       REAL(C_DOUBLE) FALTNDC,FALTNDNC
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   FNC,DUMFNR,FALOUTNR
       REAL(C_DOUBLE) FALTNDNR
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::   FNR
 ! FALL-SPEED PARAMETER 'A' WITH AIR DENSITY CORRECTION
       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::    AIN,ARN,ASN,ACN,AGN
 ! EXTERNAL FUNCTION CALL RETURN VARIABLES
 !      REAL(C_DOUBLE) GAMMA,      ! EULER GAMMA FUNCTION
 !      REAL(C_DOUBLE) POLYSVP,    ! SAT. PRESSURE FUNCTION
 !      REAL(C_DOUBLE) DERF1        ! ERROR FUNCTION
 ! DUMMY VARIABLES
      REAL(C_DOUBLE) DUM,DUM1,DUM2,DUMT,DUMQV,DUMQSS,DUMQSI,DUMS
 ! PROGNOSTIC SUPERSATURATION
      REAL(C_DOUBLE) DQSDT    ! CHANGE OF SAT. MIX. RAT. WITH TEMPERATURE
      REAL(C_DOUBLE) DQSIDT   ! CHANGE IN ICE SAT. MIXING RAT. WITH T
      REAL(C_DOUBLE) EPSI     ! 1/PHASE REL. TIME (SEE M2005), ICE
      REAL(C_DOUBLE) EPSS     ! 1/PHASE REL. TIME (SEE M2005), SNOW
      REAL(C_DOUBLE) EPSR     ! 1/PHASE REL. TIME (SEE M2005), RAIN
      REAL(C_DOUBLE) EPSG     ! 1/PHASE REL. TIME (SEE M2005), GRAUPEL
 ! NEW DROPLET ACTIVATION VARIABLES
      REAL(C_DOUBLE) TAUC     ! PHASE REL. TIME (SEE M2005), DROPLETS
      REAL(C_DOUBLE) TAUR     ! PHASE REL. TIME (SEE M2005), RAIN
      REAL(C_DOUBLE) TAUI     ! PHASE REL. TIME (SEE M2005), CLOUD ICE
      REAL(C_DOUBLE) TAUS     ! PHASE REL. TIME (SEE M2005), SNOW
      REAL(C_DOUBLE) TAUG     ! PHASE REL. TIME (SEE M2005), GRAUPEL
      REAL(C_DOUBLE) DUMACT,DUM3
 ! COUNTING/INDEX VARIABLES
      INTEGER K,NSTEP,N ! ,I
 ! LTRUE IS ONLY USED TO SPEED UP THE CODE !!
 ! LTRUE, SWITCH = 0, NO HYDROMETEORS IN COLUMN,
 !               = 1, HYDROMETEORS IN COLUMN
       INTEGER LTRUE
 ! DROPLET ACTIVATION/FREEZING AEROSOL
      REAL(C_DOUBLE)    CT      ! DROPLET ACTIVATION PARAMETER
      REAL(C_DOUBLE)    TEMP1   ! DUMMY TEMPERATURE
      REAL(C_DOUBLE)    SAT1    ! DUMMY SATURATION
      REAL(C_DOUBLE)    SIGVL   ! SURFACE TENSION LIQ/VAPOR
      REAL(C_DOUBLE)    KEL     ! KELVIN PARAMETER
      REAL(C_DOUBLE)    KC2     ! TOTAL ICE NUCLEATION RATE
        REAL(C_DOUBLE) CRY,KRY   ! AEROSOL ACTIVATION PARAMETERS
 ! MORE WORKING/DUMMY VARIABLES
      REAL(C_DOUBLE) DUMQI,DUMNI,DC0,DS0,DG0
      REAL(C_DOUBLE) DUMQC,DUMQR,RATIO,SUM_DEP,FUDGEF
 ! EFFECTIVE VERTICAL VELOCITY  (M/S)
      REAL(C_DOUBLE) WEF
 ! WORKING PARAMETERS FOR ICE NUCLEATION
       REAL(C_DOUBLE) ANUC,BNUC
 ! WORKING PARAMETERS FOR AEROSOL ACTIVATION
         REAL(C_DOUBLE) AACT,GAMM,GG,PSI,ETA1,ETA2,SM1,SM2,SMAX,UU1,UU2,ALPHA
 ! DUMMY SIZE DISTRIBUTION PARAMETERS
         REAL(C_DOUBLE) DLAMS,DLAMR,DLAMI,DLAMC,DLAMG,LAMMAX,LAMMIN
         INTEGER IDROP
 ! FOR WRF-CHEM
         REAL(C_DOUBLE), DIMENSION(KTS:KTE)::C2PREC,CSED,ISED,SSED,GSED,RSED
     REAL(C_DOUBLE), DIMENSION(KTS:KTE)                :: tqimelt ! melting of cloud ice (tendency)
 ! comment lines for wrf-chem since these are intent(in) in that case
 !       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NC3DTEN            ! CLOUD DROPLET NUMBER CONCENTRATION (1/KG/S)
 !       REAL(C_DOUBLE), DIMENSION(KTS:KTE) ::  NC3D               ! CLOUD DROPLET NUMBER CONCENTRATION (1/KG)
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
         ! print *,'IN MICRO KTS:KTE ', i,j,kts, kte
 ! SET LTRUE INITIALLY TO 0
          ltrue = 0
 ! ATMOSPHERIC PARAMETERS THAT VARY IN TIME AND HEIGHT
          DO k = kts,kte
 ! NC3DTEN LOCAL ARRAY INITIALIZED
                nc3dten(k) = 0.
 ! INITIALIZE VARIABLES FOR WRF-CHEM OUTPUT TO ZERO
                 c2prec(k)=0.
                 csed(k)=0.
                 ised(k)=0.
                 ssed(k)=0.
                 gsed(k)=0.
                 rsed(k)=0.
 ! LATENT HEAT OF VAPORATION
             xxlv(k) = 3.1484e6-2370.*t3d(k)
 ! LATENT HEAT OF SUBLIMATION
             xxls(k) = 3.15e6-2370.*t3d(k)+0.3337e6
             cpm(k) = cp*(1.+0.887*qv3d(k))
 ! SATURATION VAPOR PRESSURE AND MIXING RATIO
 ! hm, add fix for low pressure, 5/12/10
             evs(k) = min(0.99*pres(k),polysvp(t3d(k),0))   ! PA
             eis(k) = min(0.99*pres(k),polysvp(t3d(k),1))   ! PA
 ! Fortran version
 ! MAKE SURE ICE SATURATION DOESN'T EXCEED WATER SAT. NEAR FREEZING
             IF (eis(k).GT.evs(k)) eis(k) = evs(k)
             qvs(k) = ep_2*evs(k)/(pres(k)-evs(k))
             qvi(k) = ep_2*eis(k)/(pres(k)-eis(k))
             qvqvs(k) = qv3d(k)/qvs(k)
             qvqvsi(k) = qv3d(k)/qvi(k)
 ! AIR DENSITY
             rho(k) = pres(k)/(r*t3d(k))
 ! ADD NUMBER CONCENTRATION DUE TO CUMULUS TENDENCY
 ! ASSUME N0 ASSOCIATED WITH CUMULUS PARAM RAIN IS 10^7 M^-4
 ! ASSUME N0 ASSOCIATED WITH CUMULUS PARAM SNOW IS 2 X 10^7 M^-4
 ! FOR DETRAINED CLOUD ICE, ASSUME MEAN VOLUME DIAM OF 80 MICRON
             IF (qrcu1d(k).GE.1.e-10) THEN
             dum=1.8e5*(qrcu1d(k)*dt/(pi*rhow*rho(k)**3))**0.25
             nr3d(k)=nr3d(k)+dum
             END IF
             IF (qscu1d(k).GE.1.e-10) THEN
             dum=3.e5*(qscu1d(k)*dt/(cons1*rho(k)**3))**(1./(ds+1.))
             ns3d(k)=ns3d(k)+dum
             END IF
             IF (qicu1d(k).GE.1.e-10) THEN
             dum=qicu1d(k)*dt/(ci*(80.e-6)**di)
             ni3d(k)=ni3d(k)+dum
             END IF
 ! AT SUBSATURATION, REMOVE SMALL AMOUNTS OF CLOUD/PRECIP WATER
 ! hm modify 7/0/09 change limit to 1.e-8
              IF (qvqvs(k).LT.0.9) THEN
                IF (qr3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qr3d(k)
                   t3d(k)=t3d(k)-qr3d(k)*xxlv(k)/cpm(k)
                   qr3d(k)=0.
                END IF
                IF (qc3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qc3d(k)
                   t3d(k)=t3d(k)-qc3d(k)*xxlv(k)/cpm(k)
                   qc3d(k)=0.
                END IF
              END IF
 ! Fortran version
              IF (qvqvsi(k).LT.0.9) THEN
                IF (qi3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qi3d(k)
                   t3d(k)=t3d(k)-qi3d(k)*xxls(k)/cpm(k)
                   qi3d(k)=0.
                END IF
                IF (qni3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qni3d(k)
                   t3d(k)=t3d(k)-qni3d(k)*xxls(k)/cpm(k)
                   qni3d(k)=0.
                END IF
                IF (qg3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qg3d(k)
                   t3d(k)=t3d(k)-qg3d(k)*xxls(k)/cpm(k)
                   qg3d(k)=0.
                END IF
             END IF
             ! Fortran version
 ! HEAT OF FUSION
             xlf(k) = xxls(k)-xxlv(k)
 !..................................................................
 ! IF MIXING RATIO < QSMALL SET MIXING RATIO AND NUMBER CONC TO ZERO
        IF (qc3d(k).LT.qsmall) THEN
          qc3d(k) = 0.
          nc3d(k) = 0.
          effc(k) = 0.
        END IF
        IF (qr3d(k).LT.qsmall) THEN
          qr3d(k) = 0.
          nr3d(k) = 0.
          effr(k) = 0.
        END IF
        IF (qi3d(k).LT.qsmall) THEN
          qi3d(k) = 0.
          ni3d(k) = 0.
          effi(k) = 0.
        END IF
        IF (qni3d(k).LT.qsmall) THEN
          qni3d(k) = 0.
          ns3d(k) = 0.
          effs(k) = 0.
        END IF
        IF (qg3d(k).LT.qsmall) THEN
          qg3d(k) = 0.
          ng3d(k) = 0.
          effg(k) = 0.
        END IF
 ! Fortran version
 ! INITIALIZE SEDIMENTATION TENDENCIES FOR MIXING RATIO
       qrsten(k) = 0.
       qisten(k) = 0.
       qnisten(k) = 0.
       qcsten(k) = 0.
       qgsten(k) = 0.
 !..................................................................
 ! MICROPHYSICS PARAMETERS VARYING IN TIME/HEIGHT
 ! fix 053011
             mu(k) = 1.496e-6*t3d(k)**1.5/(t3d(k)+120.)
 ! FALL SPEED WITH DENSITY CORRECTION (HEYMSFIELD AND BENSSEMER 2006)
             dum = (rhosu/rho(k))**0.54
 ! fix 053011
 !            AIN(K) = DUM*AI
 ! AA revision 4/1/11: Ikawa and Saito 1991 air-density correction
             ain(k) = (rhosu/rho(k))**0.35*ai
             arn(k) = dum*ar
             asn(k) = dum*as
 !            ACN(K) = DUM*AC
 ! AA revision 4/1/11: temperature-dependent Stokes fall speed
             acn(k) = g*rhow/(18.*mu(k))
 ! HM ADD GRAUPEL 8/28/06
             agn(k) = dum*ag
 !hm 4/7/09 bug fix, initialize lami to prevent later division by zero
             lami(k)=0.
 !..................................
 ! IF THERE IS NO CLOUD/PRECIP WATER, AND IF SUBSATURATED, THEN SKIP MICROPHYSICS
 ! FOR THIS LEVEL
             IF ( qc3d(k).LT.qsmall.AND. &
                  qi3d(k).LT.qsmall.AND. &
                 qni3d(k).LT.qsmall.AND. &
                  qr3d(k).LT.qsmall.AND. &
                  qg3d(k).LT.qsmall) THEN
             IF (t3d(k).LT.273.15.AND.qvqvsi(k).LT.0.999) then
                GOTO 200
             endif
             IF (t3d(k).GE.273.15.AND.qvqvs(k).LT.0.999) then
                GOTO 200
             endif
             END IF
 ! THERMAL CONDUCTIVITY FOR AIR
 ! fix 053011
             kap(k) = 1.414e3*mu(k)
 ! DIFFUSIVITY OF WATER VAPOR
             dv(k) = 8.794e-5*t3d(k)**1.81/pres(k)
 ! SCHMIT NUMBER
 ! fix 053011
             sc(k) = mu(k)/(rho(k)*dv(k))
 ! PSYCHOMETIC CORRECTIONS
 ! RATE OF CHANGE SAT. MIX. RATIO WITH TEMPERATURE
             dum = (rv*t3d(k)**2)
             dqsdt = xxlv(k)*qvs(k)/dum
             dqsidt =  xxls(k)*qvi(k)/dum
             abi(k) = 1.+dqsidt*xxls(k)/cpm(k)
             ab(k) = 1.+dqsdt*xxlv(k)/cpm(k)
 !
 !.....................................................................
 !.....................................................................
 ! CASE FOR TEMPERATURE ABOVE FREEZING
             IF (t3d(k).GE.273.15) THEN
 !......................................................................
 !HM ADD, ALLOW FOR CONSTANT DROPLET NUMBER
 ! INUM = 0, PREDICT DROPLET NUMBER
 ! INUM = 1, SET CONSTANT DROPLET NUMBER
          IF (iinum.EQ.1) THEN
 ! CONVERT NDCNST FROM CM-3 TO KG-1
             nc3d(k)=ndcnst*1.e6/rho(k)
          END IF
 ! GET SIZE DISTRIBUTION PARAMETERS
 ! MELT VERY SMALL SNOW AND GRAUPEL MIXING RATIOS, ADD TO RAIN
        IF (qni3d(k).LT.1.e-6) THEN
           qr3d(k)=qr3d(k)+qni3d(k)
           nr3d(k)=nr3d(k)+ns3d(k)
           t3d(k)=t3d(k)-qni3d(k)*xlf(k)/cpm(k)
           qni3d(k) = 0.
           ns3d(k) = 0.
        END IF
        IF (qg3d(k).LT.1.e-6) THEN
           qr3d(k)=qr3d(k)+qg3d(k)
           nr3d(k)=nr3d(k)+ng3d(k)
           t3d(k)=t3d(k)-qg3d(k)*xlf(k)/cpm(k)
           qg3d(k) = 0.
           ng3d(k) = 0.
        END IF
        IF (qc3d(k).LT.qsmall.AND.qni3d(k).LT.1.e-8.AND.qr3d(k).LT.qsmall.AND.qg3d(k).LT.1.e-8) THEN
           GOTO 300
        ENDIF
 ! MAKE SURE NUMBER CONCENTRATIONS AREN'T NEGATIVE
       ns3d(k) = max(0.,ns3d(k))
       nc3d(k) = max(0.,nc3d(k))
       nr3d(k) = max(0.,nr3d(k))
       ng3d(k) = max(0.,ng3d(k))
 !......................................................................
 ! RAIN
       IF (qr3d(k).GE.qsmall) THEN
       lamr(k) = (pi*rhow*nr3d(k)/qr3d(k))**(1./3.)
       n0rr(k) = nr3d(k)*lamr(k)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lamr(k).LT.lamminr) THEN
       lamr(k) = lamminr
       n0rr(k) = lamr(k)**4*qr3d(k)/(pi*rhow)
       nr3d(k) = n0rr(k)/lamr(k)
       ELSE IF (lamr(k).GT.lammaxr) THEN
       lamr(k) = lammaxr
       n0rr(k) = lamr(k)**4*qr3d(k)/(pi*rhow)
       nr3d(k) = n0rr(k)/lamr(k)
       END IF
       END IF
 !......................................................................
 ! CLOUD DROPLETS
 ! MARTIN ET AL. (1994) FORMULA FOR PGAM
       IF (qc3d(k).GE.qsmall) THEN
          dum = pres(k)/(287.15*t3d(k))
          pgam(k)=0.0005714*(nc3d(k)/1.e6*dum)+0.2714
          pgam(k)=1./(pgam(k)**2)-1.
          pgam(k)=max(pgam(k),2.)
          pgam(k)=min(pgam(k),10.)
 ! CALCULATE LAMC
       lamc(k) = (cons26*nc3d(k)*gamma(pgam(k)+4.)/   &
                  (qc3d(k)*gamma(pgam(k)+1.)))**(1./3.)
 ! LAMMIN, 60 MICRON DIAMETER
 ! LAMMAX, 1 MICRON
       lammin = (pgam(k)+1.)/60.e-6
       lammax = (pgam(k)+1.)/1.e-6
       IF (lamc(k).LT.lammin) THEN
       lamc(k) = lammin
       nc3d(k) = exp(3.*log(lamc(k))+log(qc3d(k))+              &
                 log(gamma(pgam(k)+1.))-log(gamma(pgam(k)+4.)))/cons26
       ELSE IF (lamc(k).GT.lammax) THEN
       lamc(k) = lammax
       nc3d(k) = exp(3.*log(lamc(k))+log(qc3d(k))+              &
                 log(gamma(pgam(k)+1.))-log(gamma(pgam(k)+4.)))/cons26
       END IF
       END IF
 !......................................................................
 ! SNOW
       IF (qni3d(k).GE.qsmall) THEN
       lams(k) = (cons1*ns3d(k)/qni3d(k))**(1./ds)
       n0s(k) = ns3d(k)*lams(k)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lams(k).LT.lammins) THEN
       lams(k) = lammins
       n0s(k) = lams(k)**4*qni3d(k)/cons1
       ns3d(k) = n0s(k)/lams(k)
       ELSE IF (lams(k).GT.lammaxs) THEN
       lams(k) = lammaxs
       n0s(k) = lams(k)**4*qni3d(k)/cons1
       ns3d(k) = n0s(k)/lams(k)
       END IF
       END IF
 !......................................................................
 ! GRAUPEL
       IF (qg3d(k).GE.qsmall) THEN
       lamg(k) = (cons2*ng3d(k)/qg3d(k))**(1./dg)
       n0g(k) = ng3d(k)*lamg(k)
 ! ADJUST VARS
       IF (lamg(k).LT.lamming) THEN
       lamg(k) = lamming
       n0g(k) = lamg(k)**4*qg3d(k)/cons2
       ng3d(k) = n0g(k)/lamg(k)
       ELSE IF (lamg(k).GT.lammaxg) THEN
       lamg(k) = lammaxg
       n0g(k) = lamg(k)**4*qg3d(k)/cons2
       ng3d(k) = n0g(k)/lamg(k)
       END IF
       END IF
 !.....................................................................
 ! ZERO OUT PROCESS RATES
             prc(k) = 0.
             nprc(k) = 0.
             nprc1(k) = 0.
             pra(k) = 0.
             npra(k) = 0.
             nragg(k) = 0.
             nsmlts(k) = 0.
             nsmltr(k) = 0.
             evpms(k) = 0.
             pcc(k) = 0.
             pre(k) = 0.
             nsubc(k) = 0.
             nsubr(k) = 0.
             pracg(k) = 0.
             npracg(k) = 0.
             psmlt(k) = 0.
             pgmlt(k) = 0.
             evpmg(k) = 0.
             pracs(k) = 0.
             npracs(k) = 0.
             ngmltg(k) = 0.
             ngmltr(k) = 0.
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! CALCULATION OF MICROPHYSICAL PROCESS RATES, T > 273.15 K
 !.................................................................
 !.......................................................................
 ! AUTOCONVERSION OF CLOUD LIQUID WATER TO RAIN
 ! FORMULA FROM BEHENG (1994)
 ! USING NUMERICAL SIMULATION OF STOCHASTIC COLLECTION EQUATION
 ! AND INITIAL CLOUD DROPLET SIZE DISTRIBUTION SPECIFIED
 ! AS A GAMMA DISTRIBUTION
 ! USE MINIMUM VALUE OF 1.E-6 TO PREVENT FLOATING POINT ERROR
          IF (qc3d(k).GE.1.e-6) THEN
 ! HM ADD 12/13/06, REPLACE WITH NEWER FORMULA
 ! FROM KHAIROUTDINOV AND KOGAN 2000, MWR
                 prc(k)=1350.*qc3d(k)**2.47*  &
            (nc3d(k)/1.e6*rho(k))**(-1.79)
 ! note: nprc1 is change in Nr,
 ! nprc is change in Nc
         nprc1(k) = prc(k)/cons29
         nprc(k) = prc(k)/(qc3d(k)/nc3d(k))
 ! hm bug fix 3/20/12
                 nprc(k) = min(nprc(k),nc3d(k)/dt)
                 nprc1(k) = min(nprc1(k),nprc(k))
          END IF
 !.......................................................................
 ! HM ADD 12/13/06, COLLECTION OF SNOW BY RAIN ABOVE FREEZING
 ! FORMULA FROM IKAWA AND SAITO (1991)
          IF (qr3d(k).GE.1.e-8.AND.qni3d(k).GE.1.e-8) THEN
             ums = asn(k)*cons3/(lams(k)**bs)
             umr = arn(k)*cons4/(lamr(k)**br)
             uns = asn(k)*cons5/lams(k)**bs
             unr = arn(k)*cons6/lamr(k)**br
 ! SET REASLISTIC LIMITS ON FALLSPEEDS
 ! bug fix, 10/08/09
             dum=(rhosu/rho(k))**0.54
             ums=min(ums,1.2*dum)
             uns=min(uns,1.2*dum)
             umr=min(umr,9.1*dum)
             unr=min(unr,9.1*dum)
 ! hm fix, 2/12/13
 ! for above freezing conditions to get accelerated melting of snow,
 ! we need collection of rain by snow (following Lin et al. 1983)
 !            PRACS(K) = CONS31*(((1.2*UMR-0.95*UMS)**2+              &
 !                  0.08*UMS*UMR)**0.5*RHO(K)*                     &
 !                 N0RR(K)*N0S(K)/LAMS(K)**3*                    &
 !                  (5./(LAMS(K)**3*LAMR(K))+                    &
 !                  2./(LAMS(K)**2*LAMR(K)**2)+                  &
 !                  0.5/(LAMS(K)*LAMR(K)**3)))
             pracs(k) = cons41*(((1.2*umr-0.95*ums)**2+                   &
                   0.08*ums*umr)**0.5*rho(k)*                      &
                   n0rr(k)*n0s(k)/lamr(k)**3*                              &
                   (5./(lamr(k)**3*lams(k))+                    &
                   2./(lamr(k)**2*lams(k)**2)+                  &
                   0.5/(lamr(k)*lams(k)**3)))
 ! fix 053011, npracs no longer subtracted from snow
 !            NPRACS(K) = CONS32*RHO(K)*(1.7*(UNR-UNS)**2+            &
 !                0.3*UNR*UNS)**0.5*N0RR(K)*N0S(K)*              &
 !                (1./(LAMR(K)**3*LAMS(K))+                      &
 !                 1./(LAMR(K)**2*LAMS(K)**2)+                   &
 !                 1./(LAMR(K)*LAMS(K)**3))
          END IF
 ! ADD COLLECTION OF GRAUPEL BY RAIN ABOVE FREEZING
 ! ASSUME ALL RAIN COLLECTION BY GRAUPEL ABOVE FREEZING IS SHED
 ! ASSUME SHED DROPS ARE 1 MM IN SIZE
          IF (qr3d(k).GE.1.e-8.AND.qg3d(k).GE.1.e-8) THEN
             umg = agn(k)*cons7/(lamg(k)**bg)
             umr = arn(k)*cons4/(lamr(k)**br)
             ung = agn(k)*cons8/lamg(k)**bg
             unr = arn(k)*cons6/lamr(k)**br
 ! SET REASLISTIC LIMITS ON FALLSPEEDS
 ! bug fix, 10/08/09
             dum=(rhosu/rho(k))**0.54
             umg=min(umg,20.*dum)
             ung=min(ung,20.*dum)
             umr=min(umr,9.1*dum)
             unr=min(unr,9.1*dum)
 ! PRACG IS MIXING RATIO OF RAIN PER SEC COLLECTED BY GRAUPEL/HAIL
             pracg(k) = cons41*(((1.2*umr-0.95*umg)**2+                   &
                   0.08*umg*umr)**0.5*rho(k)*                      &
                   n0rr(k)*n0g(k)/lamr(k)**3*                              &
                   (5./(lamr(k)**3*lamg(k))+                    &
                   2./(lamr(k)**2*lamg(k)**2)+                              &
                                   0.5/(lamr(k)*lamg(k)**3)))
 ! ASSUME 1 MM DROPS ARE SHED, GET NUMBER SHED PER SEC
             dum = pracg(k)/5.2e-7
             npracg(k) = cons32*rho(k)*(1.7*(unr-ung)**2+            &
                 0.3*unr*ung)**0.5*n0rr(k)*n0g(k)*              &
                 (1./(lamr(k)**3*lamg(k))+                      &
                  1./(lamr(k)**2*lamg(k)**2)+                   &
                  1./(lamr(k)*lamg(k)**3))
 ! hm 7/15/13, remove limit so that the number of collected drops can smaller than
 ! number of shed drops
 !            NPRACG(K)=MAX(NPRACG(K)-DUM,0.)
             npracg(k)=npracg(k)-dum
             END IF
 !.......................................................................
 ! ACCRETION OF CLOUD LIQUID WATER BY RAIN
 ! CONTINUOUS COLLECTION EQUATION WITH
 ! GRAVITATIONAL COLLECTION KERNEL, DROPLET FALL SPEED NEGLECTED
          IF (qr3d(k).GE.1.e-8 .AND. qc3d(k).GE.1.e-8) THEN
 ! 12/13/06 HM ADD, REPLACE WITH NEWER FORMULA FROM
 ! KHAIROUTDINOV AND KOGAN 2000, MWR
            dum=(qc3d(k)*qr3d(k))
            pra(k) = 67.*(dum)**1.15
            npra(k) = pra(k)/(qc3d(k)/nc3d(k))
          END IF
 !.......................................................................
 ! SELF-COLLECTION OF RAIN DROPS
 ! FROM BEHENG(1994)
 ! FROM NUMERICAL SIMULATION OF THE STOCHASTIC COLLECTION EQUATION
 ! AS DESCRINED ABOVE FOR AUTOCONVERSION
          IF (qr3d(k).GE.1.e-8) THEN
 ! include breakup add 10/09/09
             dum1=300.e-6
             if (1./lamr(k).lt.dum1) then
             dum=1.
             else if (1./lamr(k).ge.dum1) then
             dum=2.-exp(2300.*(1./lamr(k)-dum1))
             end if
 !            NRAGG(K) = -8.*NR3D(K)*QR3D(K)*RHO(K)
             nragg(k) = -5.78*dum*nr3d(k)*qr3d(k)*rho(k)
          END IF
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! CALCULATE EVAP OF RAIN (RUTLEDGE AND HOBBS 1983)
       IF (qr3d(k).GE.qsmall) THEN
         epsr = 2.*pi*n0rr(k)*rho(k)*dv(k)*                           &
                    (f1r/(lamr(k)*lamr(k))+                       &
                     f2r*(arn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons9/                   &
                 (lamr(k)**cons34))
       ELSE
       epsr = 0.
       END IF
 ! NO CONDENSATION ONTO RAIN, ONLY EVAP ALLOWED
            IF (qv3d(k).LT.qvs(k)) THEN
               pre(k) = epsr*(qv3d(k)-qvs(k))/ab(k)
               pre(k) = min(pre(k),0.)
            ELSE
               pre(k) = 0.
            END IF
 !.......................................................................
 ! MELTING OF SNOW
 ! SNOW MAY PERSITS ABOVE FREEZING, FORMULA FROM RUTLEDGE AND HOBBS, 1984
 ! IF WATER SUPERSATURATION, SNOW MELTS TO FORM RAIN
           IF (qni3d(k).GE.1.e-8) THEN
 ! fix 053011
 ! HM, MODIFY FOR V3.2, ADD ACCELERATED MELTING DUE TO COLLISION WITH RAIN
 !             DUM = -CPW/XLF(K)*T3D(K)*PRACS(K)
              dum = -cpw/xlf(k)*(t3d(k)-273.15)*pracs(k)
 ! hm fix 1/20/15
 !             PSMLT(K)=2.*PI*N0S(K)*KAP(K)*(273.15-T3D(K))/       &
 !                    XLF(K)*RHO(K)*(F1S/(LAMS(K)*LAMS(K))+        &
 !                    F2S*(ASN(K)*RHO(K)/MU(K))**0.5*                      &
 !                    SC(K)**(1./3.)*CONS10/                   &
 !                   (LAMS(K)**CONS35))+DUM
              psmlt(k)=2.*pi*n0s(k)*kap(k)*(273.15-t3d(k))/       &
                     xlf(k)*(f1s/(lams(k)*lams(k))+        &
                     f2s*(asn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons10/                   &
                    (lams(k)**cons35))+dum
 ! IN WATER SUBSATURATION, SNOW MELTS AND EVAPORATES
       IF (qvqvs(k).LT.1.) THEN
         epss = 2.*pi*n0s(k)*rho(k)*dv(k)*                            &
                    (f1s/(lams(k)*lams(k))+                       &
                     f2s*(asn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons10/                   &
                (lams(k)**cons35))
 ! hm fix 8/4/08
         evpms(k) = (qv3d(k)-qvs(k))*epss/ab(k)
         evpms(k) = max(evpms(k),psmlt(k))
         psmlt(k) = psmlt(k)-evpms(k)
       END IF
       END IF
 !.......................................................................
 ! MELTING OF GRAUPEL
 ! GRAUPEL MAY PERSITS ABOVE FREEZING, FORMULA FROM RUTLEDGE AND HOBBS, 1984
 ! IF WATER SUPERSATURATION, GRAUPEL MELTS TO FORM RAIN
           IF (qg3d(k).GE.1.e-8) THEN
 ! fix 053011
 ! HM, MODIFY FOR V3.2, ADD ACCELERATED MELTING DUE TO COLLISION WITH RAIN
 !             DUM = -CPW/XLF(K)*T3D(K)*PRACG(K)
              dum = -cpw/xlf(k)*(t3d(k)-273.15)*pracg(k)
 ! hm fix 1/20/15
 !             PGMLT(K)=2.*PI*N0G(K)*KAP(K)*(273.15-T3D(K))/              &
 !                    XLF(K)*RHO(K)*(F1S/(LAMG(K)*LAMG(K))+                &
 !                    F2S*(AGN(K)*RHO(K)/MU(K))**0.5*                      &
 !                    SC(K)**(1./3.)*CONS11/                   &
 !                   (LAMG(K)**CONS36))+DUM
              pgmlt(k)=2.*pi*n0g(k)*kap(k)*(273.15-t3d(k))/               &
                     xlf(k)*(f1s/(lamg(k)*lamg(k))+                &
                     f2s*(agn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons11/                   &
                    (lamg(k)**cons36))+dum
 ! IN WATER SUBSATURATION, GRAUPEL MELTS AND EVAPORATES
       IF (qvqvs(k).LT.1.) THEN
         epsg = 2.*pi*n0g(k)*rho(k)*dv(k)*                                &
                    (f1s/(lamg(k)*lamg(k))+                               &
                     f2s*(agn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons11/                   &
                (lamg(k)**cons36))
 ! hm fix 8/4/08
         evpmg(k) = (qv3d(k)-qvs(k))*epsg/ab(k)
         evpmg(k) = max(evpmg(k),pgmlt(k))
         pgmlt(k) = pgmlt(k)-evpmg(k)
       END IF
       END IF
 ! HM, V3.2
 ! RESET PRACG AND PRACS TO ZERO, THIS IS DONE BECAUSE THERE IS NO
 ! TRANSFER OF MASS FROM SNOW AND GRAUPEL TO RAIN DIRECTLY FROM COLLECTION
 ! ABOVE FREEZING, IT IS ONLY USED FOR ENHANCEMENT OF MELTING AND SHEDDING
       pracg(k) = 0.
       pracs(k) = 0.
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! FOR CLOUD ICE, ONLY PROCESSES OPERATING AT T > 273.15 IS
 ! MELTING, WHICH IS ALREADY CONSERVED DURING PROCESS
 ! CALCULATION
 ! CONSERVATION OF QC
       dum = (prc(k)+pra(k))*dt
       IF (dum.GT.qc3d(k).AND.qc3d(k).GE.qsmall) THEN
         ratio = qc3d(k)/dum
         prc(k) = prc(k)*ratio
         pra(k) = pra(k)*ratio
         END IF
 ! CONSERVATION OF SNOW
         dum = (-psmlt(k)-evpms(k)+pracs(k))*dt
         IF (dum.GT.qni3d(k).AND.qni3d(k).GE.qsmall) THEN
 ! NO SOURCE TERMS FOR SNOW AT T > FREEZING
         ratio = qni3d(k)/dum
         psmlt(k) = psmlt(k)*ratio
         evpms(k) = evpms(k)*ratio
         pracs(k) = pracs(k)*ratio
         END IF
 ! CONSERVATION OF GRAUPEL
         dum = (-pgmlt(k)-evpmg(k)+pracg(k))*dt
         IF (dum.GT.qg3d(k).AND.qg3d(k).GE.qsmall) THEN
 ! NO SOURCE TERM FOR GRAUPEL ABOVE FREEZING
         ratio = qg3d(k)/dum
         pgmlt(k) = pgmlt(k)*ratio
         evpmg(k) = evpmg(k)*ratio
         pracg(k) = pracg(k)*ratio
         END IF
 ! CONSERVATION OF QR
 ! HM 12/13/06, ADDED CONSERVATION OF RAIN SINCE PRE IS NEGATIVE
         dum = (-pracs(k)-pracg(k)-pre(k)-pra(k)-prc(k)+psmlt(k)+pgmlt(k))*dt
         IF (dum.GT.qr3d(k).AND.qr3d(k).GE.qsmall) THEN
         ratio = (qr3d(k)/dt+pracs(k)+pracg(k)+pra(k)+prc(k)-psmlt(k)-pgmlt(k))/ &
                         (-pre(k))
         pre(k) = pre(k)*ratio
         END IF
 !....................................
       qv3dten(k) = qv3dten(k)+(-pre(k)-evpms(k)-evpmg(k))
       t3dten(k) = t3dten(k)+(pre(k)*xxlv(k)+(evpms(k)+evpmg(k))*xxls(k)+&
                     (psmlt(k)+pgmlt(k)-pracs(k)-pracg(k))*xlf(k))/cpm(k)
       qc3dten(k) = qc3dten(k)+(-pra(k)-prc(k))
       qr3dten(k) = qr3dten(k)+(pre(k)+pra(k)+prc(k)-psmlt(k)-pgmlt(k)+pracs(k)+pracg(k))
       qni3dten(k) = qni3dten(k)+(psmlt(k)+evpms(k)-pracs(k))
       qg3dten(k) = qg3dten(k)+(pgmlt(k)+evpmg(k)-pracg(k))
 ! fix 053011
 !      NS3DTEN(K) = NS3DTEN(K)-NPRACS(K)
 ! HM, bug fix 5/12/08, npracg is subtracted from nr not ng
 !      NG3DTEN(K) = NG3DTEN(K)
       nc3dten(k) = nc3dten(k)+ (-npra(k)-nprc(k))
       nr3dten(k) = nr3dten(k)+ (nprc1(k)+nragg(k)-npracg(k))
 ! Fortran version
 ! HM ADD, WRF-CHEM, ADD TENDENCIES FOR C2PREC
         c2prec(k) = pra(k)+prc(k)
       IF (pre(k).LT.0.) THEN
          dum = pre(k)*dt/qr3d(k)
            dum = max(-1.,dum)
          nsubr(k) = dum*nr3d(k)/dt
       END IF
         IF (evpms(k)+psmlt(k).LT.0.) THEN
          dum = (evpms(k)+psmlt(k))*dt/qni3d(k)
            dum = max(-1.,dum)
          nsmlts(k) = dum*ns3d(k)/dt
         END IF
         IF (psmlt(k).LT.0.) THEN
           dum = psmlt(k)*dt/qni3d(k)
           dum = max(-1.0,dum)
           nsmltr(k) = dum*ns3d(k)/dt
         END IF
         IF (evpmg(k)+pgmlt(k).LT.0.) THEN
          dum = (evpmg(k)+pgmlt(k))*dt/qg3d(k)
            dum = max(-1.,dum)
          ngmltg(k) = dum*ng3d(k)/dt
         END IF
         IF (pgmlt(k).LT.0.) THEN
           dum = pgmlt(k)*dt/qg3d(k)
           dum = max(-1.0,dum)
           ngmltr(k) = dum*ng3d(k)/dt
         END IF
          ns3dten(k) = ns3dten(k)+(nsmlts(k))
          ng3dten(k) = ng3dten(k)+(ngmltg(k))
          nr3dten(k) = nr3dten(k)+(nsubr(k)-nsmltr(k)-ngmltr(k))
  300  CONTINUE
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! NOW CALCULATE SATURATION ADJUSTMENT TO CONDENSE EXTRA VAPOR ABOVE
 ! WATER SATURATION
       dumt = t3d(k)+dt*t3dten(k)
       dumqv = qv3d(k)+dt*qv3dten(k)
 ! hm, add fix for low pressure, 5/12/10
       dum=min(0.99*pres(k),polysvp(dumt,0))
       dumqss = ep_2*dum/(pres(k)-dum)
       dumqc = qc3d(k)+dt*qc3dten(k)
       dumqc = max(dumqc,0.)
 ! SATURATION ADJUSTMENT FOR LIQUID
       dums = dumqv-dumqss
       pcc(k) = dums/(1.+xxlv(k)**2*dumqss/(cpm(k)*rv*dumt**2))/dt
       IF (pcc(k)*dt+dumqc.LT.0.) THEN
            pcc(k) = -dumqc/dt
       END IF
       qv3dten(k) = qv3dten(k)-pcc(k)
       t3dten(k) = t3dten(k)+pcc(k)*xxlv(k)/cpm(k)
       qc3dten(k) = qc3dten(k)+pcc(k)
 !.......................................................................
 ! ACTIVATION OF CLOUD DROPLETS
 ! ACTIVATION OF DROPLET CURRENTLY NOT CALCULATED
 ! DROPLET CONCENTRATION IS SPECIFIED !!!!!
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! SUBLIMATE, MELT, OR EVAPORATE NUMBER CONCENTRATION
 ! THIS FORMULATION ASSUMES 1:1 RATIO BETWEEN MASS LOSS AND
 ! LOSS OF NUMBER CONCENTRATION
 !     IF (PCC(K).LT.0.) THEN
 !        DUM = PCC(K)*DT/QC3D(K)
 !           DUM = MAX(-1.,DUM)
 !        NSUBC(K) = DUM*NC3D(K)/DT
 !     END IF
 ! UPDATE TENDENCIES
 !        NC3DTEN(K) = NC3DTEN(K)+NSUBC(K)
 !.....................................................................
 !.....................................................................
          ELSE  ! TEMPERATURE < 273.15
 !......................................................................
 !HM ADD, ALLOW FOR CONSTANT DROPLET NUMBER
 ! INUM = 0, PREDICT DROPLET NUMBER
 ! INUM = 1, SET CONSTANT DROPLET NUMBER
          IF (iinum.EQ.1) THEN
 ! CONVERT NDCNST FROM CM-3 TO KG-1
             nc3d(k)=ndcnst*1.e6/rho(k)
          END IF
 ! CALCULATE SIZE DISTRIBUTION PARAMETERS
 ! MAKE SURE NUMBER CONCENTRATIONS AREN'T NEGATIVE
       ni3d(k) = max(0.,ni3d(k))
       ns3d(k) = max(0.,ns3d(k))
       nc3d(k) = max(0.,nc3d(k))
       nr3d(k) = max(0.,nr3d(k))
       ng3d(k) = max(0.,ng3d(k))
 !......................................................................
 ! CLOUD ICE
       IF (qi3d(k).GE.qsmall) THEN
          lami(k) = (cons12*                 &
               ni3d(k)/qi3d(k))**(1./di)
          n0i(k) = ni3d(k)*lami(k)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lami(k).LT.lammini) THEN
       lami(k) = lammini
       n0i(k) = lami(k)**4*qi3d(k)/cons12
       ni3d(k) = n0i(k)/lami(k)
       ELSE IF (lami(k).GT.lammaxi) THEN
       lami(k) = lammaxi
       n0i(k) = lami(k)**4*qi3d(k)/cons12
       ni3d(k) = n0i(k)/lami(k)
       END IF
       END IF
 !......................................................................
 ! RAIN
       IF (qr3d(k).GE.qsmall) THEN
       lamr(k) = (pi*rhow*nr3d(k)/qr3d(k))**(1./3.)
       n0rr(k) = nr3d(k)*lamr(k)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lamr(k).LT.lamminr) THEN
       lamr(k) = lamminr
       n0rr(k) = lamr(k)**4*qr3d(k)/(pi*rhow)
       nr3d(k) = n0rr(k)/lamr(k)
       ELSE IF (lamr(k).GT.lammaxr) THEN
       lamr(k) = lammaxr
       n0rr(k) = lamr(k)**4*qr3d(k)/(pi*rhow)
       nr3d(k) = n0rr(k)/lamr(k)
       END IF
       END IF
 !......................................................................
 ! CLOUD DROPLETS
 ! MARTIN ET AL. (1994) FORMULA FOR PGAM
       IF (qc3d(k).GE.qsmall) THEN
          dum = pres(k)/(287.15*t3d(k))
          pgam(k)=0.0005714*(nc3d(k)/1.e6*dum)+0.2714
          pgam(k)=1./(pgam(k)**2)-1.
          pgam(k)=max(pgam(k),2.)
          pgam(k)=min(pgam(k),10.)
 ! CALCULATE LAMC
       lamc(k) = (cons26*nc3d(k)*gamma(pgam(k)+4.)/   &
                  (qc3d(k)*gamma(pgam(k)+1.)))**(1./3.)
 ! LAMMIN, 60 MICRON DIAMETER
 ! LAMMAX, 1 MICRON
       lammin = (pgam(k)+1.)/60.e-6
       lammax = (pgam(k)+1.)/1.e-6
       IF (lamc(k).LT.lammin) THEN
       lamc(k) = lammin
       nc3d(k) = exp(3.*log(lamc(k))+log(qc3d(k))+              &
                 log(gamma(pgam(k)+1.))-log(gamma(pgam(k)+4.)))/cons26
       ELSE IF (lamc(k).GT.lammax) THEN
       lamc(k) = lammax
       nc3d(k) = exp(3.*log(lamc(k))+log(qc3d(k))+              &
                 log(gamma(pgam(k)+1.))-log(gamma(pgam(k)+4.)))/cons26
       END IF
 ! TO CALCULATE DROPLET FREEZING
         cdist1(k) = nc3d(k)/gamma(pgam(k)+1.)
       END IF
 !......................................................................
 ! SNOW
       IF (qni3d(k).GE.qsmall) THEN
       lams(k) = (cons1*ns3d(k)/qni3d(k))**(1./ds)
       n0s(k) = ns3d(k)*lams(k)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lams(k).LT.lammins) THEN
       lams(k) = lammins
       n0s(k) = lams(k)**4*qni3d(k)/cons1
       ns3d(k) = n0s(k)/lams(k)
       ELSE IF (lams(k).GT.lammaxs) THEN
       lams(k) = lammaxs
       n0s(k) = lams(k)**4*qni3d(k)/cons1
       ns3d(k) = n0s(k)/lams(k)
       END IF
    END IF
 !......................................................................
 ! GRAUPEL
       IF (qg3d(k).GE.qsmall) THEN
       lamg(k) = (cons2*ng3d(k)/qg3d(k))**(1./dg)
       n0g(k) = ng3d(k)*lamg(k)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lamg(k).LT.lamming) THEN
       lamg(k) = lamming
       n0g(k) = lamg(k)**4*qg3d(k)/cons2
       ng3d(k) = n0g(k)/lamg(k)
       ELSE IF (lamg(k).GT.lammaxg) THEN
       lamg(k) = lammaxg
       n0g(k) = lamg(k)**4*qg3d(k)/cons2
       ng3d(k) = n0g(k)/lamg(k)
       END IF
       END IF
 !.....................................................................
 ! ZERO OUT PROCESS RATES
             mnuccc(k) = 0.
             nnuccc(k) = 0.
             prc(k) = 0.
             nprc(k) = 0.
             nprc1(k) = 0.
             nsagg(k) = 0.
             psacws(k) = 0.
             npsacws(k) = 0.
             psacwi(k) = 0.
             npsacwi(k) = 0.
             pracs(k) = 0.
             npracs(k) = 0.
             nmults(k) = 0.
             qmults(k) = 0.
             nmultr(k) = 0.
             qmultr(k) = 0.
             nmultg(k) = 0.
             qmultg(k) = 0.
             nmultrg(k) = 0.
             qmultrg(k) = 0.
             mnuccr(k) = 0.
             nnuccr(k) = 0.
             pra(k) = 0.
             npra(k) = 0.
             nragg(k) = 0.
             prci(k) = 0.
             nprci(k) = 0.
             prai(k) = 0.
             nprai(k) = 0.
             nnuccd(k) = 0.
             mnuccd(k) = 0.
             pcc(k) = 0.
             pre(k) = 0.
             prd(k) = 0.
             prds(k) = 0.
             eprd(k) = 0.
             eprds(k) = 0.
             nsubc(k) = 0.
             nsubi(k) = 0.
             nsubs(k) = 0.
             nsubr(k) = 0.
             piacr(k) = 0.
             niacr(k) = 0.
             praci(k) = 0.
             piacrs(k) = 0.
             niacrs(k) = 0.
             pracis(k) = 0.
 ! HM: ADD GRAUPEL PROCESSES
             pracg(k) = 0.
             psacr(k) = 0.
             psacwg(k) = 0.
             pgsacw(k) = 0.
             pgracs(k) = 0.
             prdg(k) = 0.
             eprdg(k) = 0.
             npracg(k) = 0.
             npsacwg(k) = 0.
             nscng(k) = 0.
             ngracs(k) = 0.
             nsubg(k) = 0.
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! CALCULATION OF MICROPHYSICAL PROCESS RATES
 ! ACCRETION/AUTOCONVERSION/FREEZING/MELTING/COAG.
 !.......................................................................
 ! FREEZING OF CLOUD DROPLETS
 ! ONLY ALLOWED BELOW -4 C
         IF (qc3d(k).GE.qsmall .AND. t3d(k).LT.269.15) THEN
 ! NUMBER OF CONTACT NUCLEI (M^-3) FROM MEYERS ET AL., 1992
 ! FACTOR OF 1000 IS TO CONVERT FROM L^-1 TO M^-3
 ! MEYERS CURVE
            nacnt = exp(-2.80+0.262*(273.15-t3d(k)))*1000.
 ! COOPER CURVE
 !        NACNT =  5.*EXP(0.304*(273.15-T3D(K)))
 ! FLECTHER
 !     NACNT = 0.01*EXP(0.6*(273.15-T3D(K)))
 ! CONTACT FREEZING
 ! MEAN FREE PATH
             dum = 7.37*t3d(k)/(288.*10.*pres(k))/100.
 ! EFFECTIVE DIFFUSIVITY OF CONTACT NUCLEI
 ! BASED ON BROWNIAN DIFFUSION
             dap(k) = cons37*t3d(k)*(1.+dum/rin)/mu(k)
            mnuccc(k) = cons38*dap(k)*nacnt*exp(log(cdist1(k))+   &
                    log(gamma(pgam(k)+5.))-4.*log(lamc(k)))
            nnuccc(k) = 2.*pi*dap(k)*nacnt*cdist1(k)*           &
                     gamma(pgam(k)+2.)/                         &
                     lamc(k)
 ! IMMERSION FREEZING (BIGG 1953)
 !           MNUCCC(K) = MNUCCC(K)+CONS39*                   &
 !                  EXP(LOG(CDIST1(K))+LOG(GAMMA(7.+PGAM(K)))-6.*LOG(LAMC(K)))*             &
 !                   EXP(AIMM*(273.15-T3D(K)))
 !           NNUCCC(K) = NNUCCC(K)+                                  &
 !            CONS40*EXP(LOG(CDIST1(K))+LOG(GAMMA(PGAM(K)+4.))-3.*LOG(LAMC(K)))              &
 !                *EXP(AIMM*(273.15-T3D(K)))
 ! hm 7/15/13 fix for consistency w/ original formula
            mnuccc(k) = mnuccc(k)+cons39*                   &
                   exp(log(cdist1(k))+log(gamma(7.+pgam(k)))-6.*log(lamc(k)))*             &
                    (exp(aimm*(273.15-t3d(k)))-1.)
            nnuccc(k) = nnuccc(k)+                                  &
             cons40*exp(log(cdist1(k))+log(gamma(pgam(k)+4.))-3.*log(lamc(k)))              &
                 *(exp(aimm*(273.15-t3d(k)))-1.)
 ! PUT IN A CATCH HERE TO PREVENT DIVERGENCE BETWEEN NUMBER CONC. AND
 ! MIXING RATIO, SINCE STRICT CONSERVATION NOT CHECKED FOR NUMBER CONC
            nnuccc(k) = min(nnuccc(k),nc3d(k)/dt)
         END IF
 !.................................................................
 !.......................................................................
 ! AUTOCONVERSION OF CLOUD LIQUID WATER TO RAIN
 ! FORMULA FROM BEHENG (1994)
 ! USING NUMERICAL SIMULATION OF STOCHASTIC COLLECTION EQUATION
 ! AND INITIAL CLOUD DROPLET SIZE DISTRIBUTION SPECIFIED
 ! AS A GAMMA DISTRIBUTION
 ! USE MINIMUM VALUE OF 1.E-6 TO PREVENT FLOATING POINT ERROR
          IF (qc3d(k).GE.1.e-6) THEN
 ! HM ADD 12/13/06, REPLACE WITH NEWER FORMULA
 ! FROM KHAIROUTDINOV AND KOGAN 2000, MWR
                 prc(k)=1350.*qc3d(k)**2.47*  &
            (nc3d(k)/1.e6*rho(k))**(-1.79)
 ! note: nprc1 is change in Nr,
 ! nprc is change in Nc
         nprc1(k) = prc(k)/cons29
         nprc(k) = prc(k)/(qc3d(k)/nc3d(k))
 ! hm bug fix 3/20/12
                 nprc(k) = min(nprc(k),nc3d(k)/dt)
                 nprc1(k) = min(nprc1(k),nprc(k))
          END IF
 !.......................................................................
 ! SELF-COLLECTION OF DROPLET NOT INCLUDED IN KK2000 SCHEME
 ! SNOW AGGREGATION FROM PASSARELLI, 1978, USED BY REISNER, 1998
 ! THIS IS HARD-WIRED FOR BS = 0.4 FOR NOW
          IF (qni3d(k).GE.1.e-8) THEN
              nsagg(k) = cons15*asn(k)*rho(k)**            &
             ((2.+bs)/3.)*qni3d(k)**((2.+bs)/3.)*                  &
             (ns3d(k)*rho(k))**((4.-bs)/3.)/                       &
             (rho(k))
          END IF
 !.......................................................................
 ! ACCRETION OF CLOUD DROPLETS ONTO SNOW/GRAUPEL
 ! HERE USE CONTINUOUS COLLECTION EQUATION WITH
 ! SIMPLE GRAVITATIONAL COLLECTION KERNEL IGNORING
 ! SNOW
          IF (qni3d(k).GE.1.e-8 .AND. qc3d(k).GE.qsmall) THEN
            psacws(k) = cons13*asn(k)*qc3d(k)*rho(k)*               &
                   n0s(k)/                        &
                   lams(k)**(bs+3.)
            npsacws(k) = cons13*asn(k)*nc3d(k)*rho(k)*              &
                   n0s(k)/                        &
                   lams(k)**(bs+3.)
          END IF
 !............................................................................
 ! COLLECTION OF CLOUD WATER BY GRAUPEL
          IF (qg3d(k).GE.1.e-8 .AND. qc3d(k).GE.qsmall) THEN
            psacwg(k) = cons14*agn(k)*qc3d(k)*rho(k)*               &
                   n0g(k)/                        &
                   lamg(k)**(bg+3.)
            npsacwg(k) = cons14*agn(k)*nc3d(k)*rho(k)*              &
                   n0g(k)/                        &
                   lamg(k)**(bg+3.)
             END IF
 !.......................................................................
 ! HM, ADD 12/13/06
 ! CLOUD ICE COLLECTING DROPLETS, ASSUME THAT CLOUD ICE MEAN DIAM > 100 MICRON
 ! BEFORE RIMING CAN OCCUR
 ! ASSUME THAT RIME COLLECTED ON CLOUD ICE DOES NOT LEAD
 ! TO HALLET-MOSSOP SPLINTERING
          IF (qi3d(k).GE.1.e-8 .AND. qc3d(k).GE.qsmall) THEN
 ! PUT IN SIZE DEPENDENT COLLECTION EFFICIENCY BASED ON STOKES LAW
 ! FROM THOMPSON ET AL. 2004, MWR
             IF (1./lami(k).GE.100.e-6) THEN
            psacwi(k) = cons16*ain(k)*qc3d(k)*rho(k)*               &
                   n0i(k)/                        &
                   lami(k)**(bi+3.)
            npsacwi(k) = cons16*ain(k)*nc3d(k)*rho(k)*              &
                   n0i(k)/                        &
                   lami(k)**(bi+3.)
            END IF
          END IF
 !.......................................................................
 ! ACCRETION OF RAIN WATER BY SNOW
 ! FORMULA FROM IKAWA AND SAITO, 1991, USED BY REISNER ET AL, 1998
          IF (qr3d(k).GE.1.e-8.AND.qni3d(k).GE.1.e-8) THEN
             ums = asn(k)*cons3/(lams(k)**bs)
             umr = arn(k)*cons4/(lamr(k)**br)
             uns = asn(k)*cons5/lams(k)**bs
             unr = arn(k)*cons6/lamr(k)**br
 ! SET REASLISTIC LIMITS ON FALLSPEEDS
 ! bug fix, 10/08/09
             dum=(rhosu/rho(k))**0.54
             ums=min(ums,1.2*dum)
             uns=min(uns,1.2*dum)
             umr=min(umr,9.1*dum)
             unr=min(unr,9.1*dum)
             pracs(k) = cons41*(((1.2*umr-0.95*ums)**2+                   &
                   0.08*ums*umr)**0.5*rho(k)*                      &
                   n0rr(k)*n0s(k)/lamr(k)**3*                              &
                   (5./(lamr(k)**3*lams(k))+                    &
                   2./(lamr(k)**2*lams(k)**2)+                  &
                   0.5/(lamr(k)*lams(k)**3)))
             npracs(k) = cons32*rho(k)*(1.7*(unr-uns)**2+            &
                 0.3*unr*uns)**0.5*n0rr(k)*n0s(k)*              &
                 (1./(lamr(k)**3*lams(k))+                      &
                  1./(lamr(k)**2*lams(k)**2)+                   &
                  1./(lamr(k)*lams(k)**3))
 ! MAKE SURE PRACS DOESN'T EXCEED TOTAL RAIN MIXING RATIO
 ! AS THIS MAY OTHERWISE RESULT IN TOO MUCH TRANSFER OF WATER DURING
 ! RIME-SPLINTERING
             pracs(k) = min(pracs(k),qr3d(k)/dt)
 ! COLLECTION OF SNOW BY RAIN - NEEDED FOR GRAUPEL CONVERSION CALCULATIONS
 ! ONLY CALCULATE IF SNOW AND RAIN MIXING RATIOS EXCEED 0.1 G/KG
 ! HM MODIFY FOR WRFV3.1
 !            IF (IHAIL.EQ.0) THEN
             IF (qni3d(k).GE.0.1e-3.AND.qr3d(k).GE.0.1e-3) THEN
             psacr(k) = cons31*(((1.2*umr-0.95*ums)**2+              &
                   0.08*ums*umr)**0.5*rho(k)*                     &
                  n0rr(k)*n0s(k)/lams(k)**3*                               &
                   (5./(lams(k)**3*lamr(k))+                    &
                   2./(lams(k)**2*lamr(k)**2)+                  &
                   0.5/(lams(k)*lamr(k)**3)))
             END IF
 !            END IF
          END IF
 !.......................................................................
 ! COLLECTION OF RAINWATER BY GRAUPEL, FROM IKAWA AND SAITO 1990,
 ! USED BY REISNER ET AL 1998
          IF (qr3d(k).GE.1.e-8.AND.qg3d(k).GE.1.e-8) THEN
             umg = agn(k)*cons7/(lamg(k)**bg)
             umr = arn(k)*cons4/(lamr(k)**br)
             ung = agn(k)*cons8/lamg(k)**bg
             unr = arn(k)*cons6/lamr(k)**br
 ! SET REASLISTIC LIMITS ON FALLSPEEDS
 ! bug fix, 10/08/09
             dum=(rhosu/rho(k))**0.54
             umg=min(umg,20.*dum)
             ung=min(ung,20.*dum)
             umr=min(umr,9.1*dum)
             unr=min(unr,9.1*dum)
             pracg(k) = cons41*(((1.2*umr-0.95*umg)**2+                   &
                   0.08*umg*umr)**0.5*rho(k)*                      &
                   n0rr(k)*n0g(k)/lamr(k)**3*                              &
                   (5./(lamr(k)**3*lamg(k))+                    &
                   2./(lamr(k)**2*lamg(k)**2)+                              &
                                   0.5/(lamr(k)*lamg(k)**3)))
             npracg(k) = cons32*rho(k)*(1.7*(unr-ung)**2+            &
                 0.3*unr*ung)**0.5*n0rr(k)*n0g(k)*              &
                 (1./(lamr(k)**3*lamg(k))+                      &
                  1./(lamr(k)**2*lamg(k)**2)+                   &
                  1./(lamr(k)*lamg(k)**3))
 ! MAKE SURE PRACG DOESN'T EXCEED TOTAL RAIN MIXING RATIO
 ! AS THIS MAY OTHERWISE RESULT IN TOO MUCH TRANSFER OF WATER DURING
 ! RIME-SPLINTERING
             pracg(k) = min(pracg(k),qr3d(k)/dt)
             END IF
 !.......................................................................
 ! RIME-SPLINTERING - SNOW
 ! HALLET-MOSSOP (1974)
 ! NUMBER OF SPLINTERS FORMED IS BASED ON MASS OF RIMED WATER
 ! DUM1 = MASS OF INDIVIDUAL SPLINTERS
 ! HM ADD THRESHOLD SNOW AND DROPLET MIXING RATIO FOR RIME-SPLINTERING
 ! TO LIMIT RIME-SPLINTERING IN STRATIFORM CLOUDS
 ! THESE THRESHOLDS CORRESPOND WITH GRAUPEL THRESHOLDS IN RH 1984
 !v1.4
          IF (qni3d(k).GE.0.1e-3) THEN
          IF (qc3d(k).GE.0.5e-3.OR.qr3d(k).GE.0.1e-3) THEN
          IF (psacws(k).GT.0..OR.pracs(k).GT.0.) THEN
             IF (t3d(k).LT.270.16 .AND. t3d(k).GT.265.16) THEN
                IF (t3d(k).GT.270.16) THEN
                   fmult = 0.
                ELSE IF (t3d(k).LE.270.16.AND.t3d(k).GT.268.16)  THEN
                   fmult = (270.16-t3d(k))/2.
                ELSE IF (t3d(k).GE.265.16.AND.t3d(k).LE.268.16)   THEN
                   fmult = (t3d(k)-265.16)/3.
                ELSE IF (t3d(k).LT.265.16) THEN
                   fmult = 0.
                END IF
 ! 1000 IS TO CONVERT FROM KG TO G
 ! SPLINTERING FROM DROPLETS ACCRETED ONTO SNOW
                IF (psacws(k).GT.0.) THEN
                   nmults(k) = 35.e4*psacws(k)*fmult*1000.
                   qmults(k) = nmults(k)*mmult
 ! CONSTRAIN SO THAT TRANSFER OF MASS FROM SNOW TO ICE CANNOT BE MORE MASS
 ! THAN WAS RIMED ONTO SNOW
                   qmults(k) = min(qmults(k),psacws(k))
                   psacws(k) = psacws(k)-qmults(k)
                END IF
 ! RIMING AND SPLINTERING FROM ACCRETED RAINDROPS
                IF (pracs(k).GT.0.) THEN
                    nmultr(k) = 35.e4*pracs(k)*fmult*1000.
                    qmultr(k) = nmultr(k)*mmult
 ! CONSTRAIN SO THAT TRANSFER OF MASS FROM SNOW TO ICE CANNOT BE MORE MASS
 ! THAN WAS RIMED ONTO SNOW
                    qmultr(k) = min(qmultr(k),pracs(k))
                    pracs(k) = pracs(k)-qmultr(k)
                END IF
             END IF
          END IF
          END IF
          END IF
 !.......................................................................
 ! RIME-SPLINTERING - GRAUPEL
 ! HALLET-MOSSOP (1974)
 ! NUMBER OF SPLINTERS FORMED IS BASED ON MASS OF RIMED WATER
 ! DUM1 = MASS OF INDIVIDUAL SPLINTERS
 ! HM ADD THRESHOLD SNOW MIXING RATIO FOR RIME-SPLINTERING
 ! TO LIMIT RIME-SPLINTERING IN STRATIFORM CLOUDS
 !         IF (IHAIL.EQ.0) THEN
 ! v1.4
          IF (qg3d(k).GE.0.1e-3) THEN
          IF (qc3d(k).GE.0.5e-3.OR.qr3d(k).GE.0.1e-3) THEN
          IF (psacwg(k).GT.0..OR.pracg(k).GT.0.) THEN
             IF (t3d(k).LT.270.16 .AND. t3d(k).GT.265.16) THEN
                IF (t3d(k).GT.270.16) THEN
                   fmult = 0.
                ELSE IF (t3d(k).LE.270.16.AND.t3d(k).GT.268.16)  THEN
                   fmult = (270.16-t3d(k))/2.
                ELSE IF (t3d(k).GE.265.16.AND.t3d(k).LE.268.16)   THEN
                   fmult = (t3d(k)-265.16)/3.
                ELSE IF (t3d(k).LT.265.16) THEN
                   fmult = 0.
                END IF
 ! 1000 IS TO CONVERT FROM KG TO G
 ! SPLINTERING FROM DROPLETS ACCRETED ONTO GRAUPEL
                IF (psacwg(k).GT.0.) THEN
                   nmultg(k) = 35.e4*psacwg(k)*fmult*1000.
                   qmultg(k) = nmultg(k)*mmult
 ! CONSTRAIN SO THAT TRANSFER OF MASS FROM GRAUPEL TO ICE CANNOT BE MORE MASS
 ! THAN WAS RIMED ONTO GRAUPEL
                   qmultg(k) = min(qmultg(k),psacwg(k))
                   psacwg(k) = psacwg(k)-qmultg(k)
                END IF
 ! RIMING AND SPLINTERING FROM ACCRETED RAINDROPS
                IF (pracg(k).GT.0.) THEN
                    nmultrg(k) = 35.e4*pracg(k)*fmult*1000.
                    qmultrg(k) = nmultrg(k)*mmult
 ! CONSTRAIN SO THAT TRANSFER OF MASS FROM GRAUPEL TO ICE CANNOT BE MORE MASS
 ! THAN WAS RIMED ONTO GRAUPEL
                    qmultrg(k) = min(qmultrg(k),pracg(k))
                    pracg(k) = pracg(k)-qmultrg(k)
                END IF
                END IF
                END IF
             END IF
             END IF
 !         END IF
 !........................................................................
 ! CONVERSION OF RIMED CLOUD WATER ONTO SNOW TO GRAUPEL/HAIL
 !           IF (IHAIL.EQ.0) THEN
            IF (psacws(k).GT.0.) THEN
 ! ONLY ALLOW CONVERSION IF QNI > 0.1 AND QC > 0.5 G/KG FOLLOWING RUTLEDGE AND HOBBS (1984)
               IF (qni3d(k).GE.0.1e-3.AND.qc3d(k).GE.0.5e-3) THEN
 ! PORTION OF RIMING CONVERTED TO GRAUPEL (REISNER ET AL. 1998, ORIGINALLY IS1991)
              pgsacw(k) = min(psacws(k),cons17*dt*n0s(k)*qc3d(k)*qc3d(k)* &
                           asn(k)*asn(k)/ &
                            (rho(k)*lams(k)**(2.*bs+2.)))
 ! MIX RAT CONVERTED INTO GRAUPEL AS EMBRYO (REISNER ET AL. 1998, ORIG M1990)
              dum = max(rhosn/(rhog-rhosn)*pgsacw(k),0.)
 ! NUMBER CONCENTRAITON OF EMBRYO GRAUPEL FROM RIMING OF SNOW
              nscng(k) = dum/mg0*rho(k)
 ! LIMIT MAX NUMBER CONVERTED TO SNOW NUMBER
              nscng(k) = min(nscng(k),ns3d(k)/dt)
 ! PORTION OF RIMING LEFT FOR SNOW
              psacws(k) = psacws(k) - pgsacw(k)
              END IF
            END IF
 ! CONVERSION OF RIMED RAINWATER ONTO SNOW CONVERTED TO GRAUPEL
            IF (pracs(k).GT.0.) THEN
 ! ONLY ALLOW CONVERSION IF QNI > 0.1 AND QR > 0.1 G/KG FOLLOWING RUTLEDGE AND HOBBS (1984)
               IF (qni3d(k).GE.0.1e-3.AND.qr3d(k).GE.0.1e-3) THEN
 ! PORTION OF COLLECTED RAINWATER CONVERTED TO GRAUPEL (REISNER ET AL. 1998)
               dum = cons18*(4./lams(k))**3*(4./lams(k))**3 &
                    /(cons18*(4./lams(k))**3*(4./lams(k))**3+ &
                    cons19*(4./lamr(k))**3*(4./lamr(k))**3)
               dum=min(dum,1.)
               dum=max(dum,0.)
               pgracs(k) = (1.-dum)*pracs(k)
             ngracs(k) = (1.-dum)*npracs(k)
 ! LIMIT MAX NUMBER CONVERTED TO MIN OF EITHER RAIN OR SNOW NUMBER CONCENTRATION
             ngracs(k) = min(ngracs(k),nr3d(k)/dt)
             ngracs(k) = min(ngracs(k),ns3d(k)/dt)
 ! AMOUNT LEFT FOR SNOW PRODUCTION
             pracs(k) = pracs(k) - pgracs(k)
             npracs(k) = npracs(k) - ngracs(k)
 ! CONVERSION TO GRAUPEL DUE TO COLLECTION OF SNOW BY RAIN
             psacr(k)=psacr(k)*(1.-dum)
             END IF
            END IF
 !           END IF
 !.......................................................................
 ! FREEZING OF RAIN DROPS
 ! FREEZING ALLOWED BELOW -4 C
          IF (t3d(k).LT.269.15.AND.qr3d(k).GE.qsmall) THEN
 ! IMMERSION FREEZING (BIGG 1953)
 !            MNUCCR(K) = CONS20*NR3D(K)*EXP(AIMM*(273.15-T3D(K)))/LAMR(K)**3 &
 !                 /LAMR(K)**3
 !            NNUCCR(K) = PI*NR3D(K)*BIMM*EXP(AIMM*(273.15-T3D(K)))/LAMR(K)**3
 ! hm fix 7/15/13 for consistency w/ original formula
             mnuccr(k) = cons20*nr3d(k)*(exp(aimm*(273.15-t3d(k)))-1.)/lamr(k)**3 &
                  /lamr(k)**3
             nnuccr(k) = pi*nr3d(k)*bimm*(exp(aimm*(273.15-t3d(k)))-1.)/lamr(k)**3
 ! PREVENT DIVERGENCE BETWEEN MIXING RATIO AND NUMBER CONC
             nnuccr(k) = min(nnuccr(k),nr3d(k)/dt)
          END IF
 !.......................................................................
 ! ACCRETION OF CLOUD LIQUID WATER BY RAIN
 ! CONTINUOUS COLLECTION EQUATION WITH
 ! GRAVITATIONAL COLLECTION KERNEL, DROPLET FALL SPEED NEGLECTED
          IF (qr3d(k).GE.1.e-8 .AND. qc3d(k).GE.1.e-8) THEN
 ! 12/13/06 HM ADD, REPLACE WITH NEWER FORMULA FROM
 ! KHAIROUTDINOV AND KOGAN 2000, MWR
            dum=(qc3d(k)*qr3d(k))
            pra(k) = 67.*(dum)**1.15
            npra(k) = pra(k)/(qc3d(k)/nc3d(k))
          END IF
 !.......................................................................
 ! SELF-COLLECTION OF RAIN DROPS
 ! FROM BEHENG(1994)
 ! FROM NUMERICAL SIMULATION OF THE STOCHASTIC COLLECTION EQUATION
 ! AS DESCRINED ABOVE FOR AUTOCONVERSION
          IF (qr3d(k).GE.1.e-8) THEN
 ! include breakup add 10/09/09
             dum1=300.e-6
             if (1./lamr(k).lt.dum1) then
             dum=1.
             else if (1./lamr(k).ge.dum1) then
             dum=2.-exp(2300.*(1./lamr(k)-dum1))
             end if
 !            NRAGG(K) = -8.*NR3D(K)*QR3D(K)*RHO(K)
             nragg(k) = -5.78*dum*nr3d(k)*qr3d(k)*rho(k)
          END IF
 !.......................................................................
 ! AUTOCONVERSION OF CLOUD ICE TO SNOW
 ! FOLLOWING HARRINGTON ET AL. (1995) WITH MODIFICATION
 ! HERE IT IS ASSUMED THAT AUTOCONVERSION CAN ONLY OCCUR WHEN THE
 ! ICE IS GROWING, I.E. IN CONDITIONS OF ICE SUPERSATURATION
          IF (qi3d(k).GE.1.e-8 .AND.qvqvsi(k).GE.1.) THEN
 !           COFFI = 2./LAMI(K)
 !           IF (COFFI.GE.DCS) THEN
               nprci(k) = cons21*(qv3d(k)-qvi(k))*rho(k)                         &
                 *n0i(k)*exp(-lami(k)*dcs)*dv(k)/abi(k)
               prci(k) = cons22*nprci(k)
               nprci(k) = min(nprci(k),ni3d(k)/dt)
 !           END IF
          END IF
 !.......................................................................
 ! ACCRETION OF CLOUD ICE BY SNOW
 ! FOR THIS CALCULATION, IT IS ASSUMED THAT THE VS >> VI
 ! AND DS >> DI FOR CONTINUOUS COLLECTION
          IF (qni3d(k).GE.1.e-8 .AND. qi3d(k).GE.qsmall) THEN
             prai(k) = cons23*asn(k)*qi3d(k)*rho(k)*n0s(k)/     &
                      lams(k)**(bs+3.)
             nprai(k) = cons23*asn(k)*ni3d(k)*                                       &
                   rho(k)*n0s(k)/                                 &
                   lams(k)**(bs+3.)
             nprai(k)=min(nprai(k),ni3d(k)/dt)
          END IF
 !.......................................................................
 ! HM, ADD 12/13/06, COLLISION OF RAIN AND ICE TO PRODUCE SNOW OR GRAUPEL
 ! FOLLOWS REISNER ET AL. 1998
 ! ASSUMED FALLSPEED AND SIZE OF ICE CRYSTAL << THAN FOR RAIN
          IF (qr3d(k).GE.1.e-8.AND.qi3d(k).GE.1.e-8.AND.t3d(k).LE.273.15) THEN
 ! ALLOW GRAUPEL FORMATION FROM RAIN-ICE COLLISIONS ONLY IF RAIN MIXING RATIO > 0.1 G/KG,
 ! OTHERWISE ADD TO SNOW
             IF (qr3d(k).GE.0.1e-3) THEN
             niacr(k)=cons24*ni3d(k)*n0rr(k)*arn(k) &
                 /lamr(k)**(br+3.)*rho(k)
             piacr(k)=cons25*ni3d(k)*n0rr(k)*arn(k) &
                 /lamr(k)**(br+3.)/lamr(k)**3*rho(k)
             praci(k)=cons24*qi3d(k)*n0rr(k)*arn(k)/ &
                 lamr(k)**(br+3.)*rho(k)
             niacr(k)=min(niacr(k),nr3d(k)/dt)
             niacr(k)=min(niacr(k),ni3d(k)/dt)
             ELSE
             niacrs(k)=cons24*ni3d(k)*n0rr(k)*arn(k) &
                 /lamr(k)**(br+3.)*rho(k)
             piacrs(k)=cons25*ni3d(k)*n0rr(k)*arn(k) &
                 /lamr(k)**(br+3.)/lamr(k)**3*rho(k)
             pracis(k)=cons24*qi3d(k)*n0rr(k)*arn(k)/ &
                 lamr(k)**(br+3.)*rho(k)
             niacrs(k)=min(niacrs(k),nr3d(k)/dt)
             niacrs(k)=min(niacrs(k),ni3d(k)/dt)
             END IF
          END IF
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! NUCLEATION OF CLOUD ICE FROM HOMOGENEOUS AND HETEROGENEOUS FREEZING ON AEROSOL
          IF (inuc.EQ.0) THEN
 ! add threshold according to Greg Thomspon
          if ((qvqvs(k).GE.0.999.and.t3d(k).le.265.15).or. &
               qvqvsi(k).ge.1.08) then
 ! hm, modify dec. 5, 2006, replace with cooper curve
       kc2 = 0.005*exp(0.304*(273.15-t3d(k)))*1000. ! convert from L-1 to m-3
 ! limit to 500 L-1
       kc2 = min(kc2,500.e3)
       kc2=max(kc2/rho(k),0.)  ! convert to kg-1
           IF (kc2.GT.ni3d(k)+ns3d(k)+ng3d(k)) THEN
              nnuccd(k) = (kc2-ni3d(k)-ns3d(k)-ng3d(k))/dt
              mnuccd(k) = nnuccd(k)*mi0
           END IF
           END IF
           ELSE IF (inuc.EQ.1) THEN
           IF (t3d(k).LT.273.15.AND.qvqvsi(k).GT.1.) THEN
              kc2 = 0.16*1000./rho(k)  ! CONVERT FROM L-1 TO KG-1
           IF (kc2.GT.ni3d(k)+ns3d(k)+ng3d(k)) THEN
              nnuccd(k) = (kc2-ni3d(k)-ns3d(k)-ng3d(k))/dt
              mnuccd(k) = nnuccd(k)*mi0
           END IF
           END IF
          END IF
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
  101      CONTINUE
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! CALCULATE EVAP/SUB/DEP TERMS FOR QI,QNI,QR
 ! NO VENTILATION FOR CLOUD ICE
         IF (qi3d(k).GE.qsmall) THEN
          epsi = 2.*pi*n0i(k)*rho(k)*dv(k)/(lami(k)*lami(k))
       ELSE
          epsi = 0.
       END IF
       IF (qni3d(k).GE.qsmall) THEN
         epss = 2.*pi*n0s(k)*rho(k)*dv(k)*                            &
                    (f1s/(lams(k)*lams(k))+                       &
                     f2s*(asn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons10/                   &
                (lams(k)**cons35))
       ELSE
       epss = 0.
       END IF
       IF (qg3d(k).GE.qsmall) THEN
         epsg = 2.*pi*n0g(k)*rho(k)*dv(k)*                                &
                    (f1s/(lamg(k)*lamg(k))+                               &
                     f2s*(agn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons11/                   &
                (lamg(k)**cons36))
       ELSE
       epsg = 0.
       END IF
       IF (qr3d(k).GE.qsmall) THEN
         epsr = 2.*pi*n0rr(k)*rho(k)*dv(k)*                           &
                    (f1r/(lamr(k)*lamr(k))+                       &
                     f2r*(arn(k)*rho(k)/mu(k))**0.5*                      &
                     sc(k)**(1./3.)*cons9/                   &
                 (lamr(k)**cons34))
       ELSE
       epsr = 0.
       END IF
 ! ONLY INCLUDE REGION OF ICE SIZE DIST < DCS
 ! DUM IS FRACTION OF D*N(D) < DCS
 ! LOGIC BELOW FOLLOWS THAT OF HARRINGTON ET AL. 1995 (JAS)
               IF (qi3d(k).GE.qsmall) THEN
               dum=(1.-exp(-lami(k)*dcs)*(1.+lami(k)*dcs))
               prd(k) = epsi*(qv3d(k)-qvi(k))/abi(k)*dum
               ELSE
               dum=0.
               END IF
 ! ADD DEPOSITION IN TAIL OF ICE SIZE DIST TO SNOW IF SNOW IS PRESENT
               IF (qni3d(k).GE.qsmall) THEN
               prds(k) = epss*(qv3d(k)-qvi(k))/abi(k)+ &
                 epsi*(qv3d(k)-qvi(k))/abi(k)*(1.-dum)
 ! OTHERWISE ADD TO CLOUD ICE
               ELSE
               prd(k) = prd(k)+epsi*(qv3d(k)-qvi(k))/abi(k)*(1.-dum)
               END IF
 ! VAPOR DPEOSITION ON GRAUPEL
               prdg(k) = epsg*(qv3d(k)-qvi(k))/abi(k)
 ! NO CONDENSATION ONTO RAIN, ONLY EVAP
            IF (qv3d(k).LT.qvs(k)) THEN
               pre(k) = epsr*(qv3d(k)-qvs(k))/ab(k)
               pre(k) = min(pre(k),0.)
            ELSE
               pre(k) = 0.
            END IF
 ! MAKE SURE NOT PUSHED INTO ICE SUPERSAT/SUBSAT
 ! FORMULA FROM REISNER 2 SCHEME
            dum = (qv3d(k)-qvi(k))/dt
            fudgef = 0.9999
            sum_dep = prd(k)+prds(k)+mnuccd(k)+prdg(k)
            IF( (dum.GT.0. .AND. sum_dep.GT.dum*fudgef) .OR.                      &
                (dum.LT.0. .AND. sum_dep.LT.dum*fudgef) ) THEN
                mnuccd(k) = fudgef*mnuccd(k)*dum/sum_dep
                prd(k) = fudgef*prd(k)*dum/sum_dep
                prds(k) = fudgef*prds(k)*dum/sum_dep
                prdg(k) = fudgef*prdg(k)*dum/sum_dep
            ENDIF
 ! IF CLOUD ICE/SNOW/GRAUPEL VAP DEPOSITION IS NEG, THEN ASSIGN TO SUBLIMATION PROCESSES
            IF (prd(k).LT.0.) THEN
               eprd(k)=prd(k)
               prd(k)=0.
            END IF
            IF (prds(k).LT.0.) THEN
               eprds(k)=prds(k)
               prds(k)=0.
            END IF
            IF (prdg(k).LT.0.) THEN
               eprdg(k)=prdg(k)
               prdg(k)=0.
            END IF
 !.......................................................................
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! CONSERVATION OF WATER
 ! THIS IS ADOPTED LOOSELY FROM MM5 RESINER CODE. HOWEVER, HERE WE
 ! ONLY ADJUST PROCESSES THAT ARE NEGATIVE, RATHER THAN ALL PROCESSES.
 ! IF MIXING RATIOS LESS THAN QSMALL, THEN NO DEPLETION OF WATER
 ! THROUGH MICROPHYSICAL PROCESSES, SKIP CONSERVATION
 ! NOTE: CONSERVATION CHECK NOT APPLIED TO NUMBER CONCENTRATION SPECIES. ADDITIONAL CATCH
 ! BELOW WILL PREVENT NEGATIVE NUMBER CONCENTRATION
 ! FOR EACH MICROPHYSICAL PROCESS WHICH PROVIDES A SOURCE FOR NUMBER, THERE IS A CHECK
 ! TO MAKE SURE THAT CAN'T EXCEED TOTAL NUMBER OF DEPLETED SPECIES WITH THE TIME
 ! STEP
 !****SENSITIVITY - NO ICE
       IF (iliq.EQ.1) THEN
       mnuccc(k)=0.
       nnuccc(k)=0.
       mnuccr(k)=0.
       nnuccr(k)=0.
       mnuccd(k)=0.
       nnuccd(k)=0.
       END IF
 ! ****SENSITIVITY - NO GRAUPEL
       IF (igraup.EQ.1) THEN
             pracg(k) = 0.
             psacr(k) = 0.
             psacwg(k) = 0.
             prdg(k) = 0.
             eprdg(k) = 0.
             evpmg(k) = 0.
             pgmlt(k) = 0.
             npracg(k) = 0.
             npsacwg(k) = 0.
             nscng(k) = 0.
             ngracs(k) = 0.
             nsubg(k) = 0.
             ngmltg(k) = 0.
             ngmltr(k) = 0.
 ! fix 053011
             piacrs(k)=piacrs(k)+piacr(k)
             piacr(k) = 0.
 ! fix 070713
             pracis(k)=pracis(k)+praci(k)
             praci(k) = 0.
             psacws(k)=psacws(k)+pgsacw(k)
             pgsacw(k) = 0.
             pracs(k)=pracs(k)+pgracs(k)
             pgracs(k) = 0.
        END IF
 ! CONSERVATION OF QC
       dum = (prc(k)+pra(k)+mnuccc(k)+psacws(k)+psacwi(k)+qmults(k)+psacwg(k)+pgsacw(k)+qmultg(k))*dt
       IF (dum.GT.qc3d(k).AND.qc3d(k).GE.qsmall) THEN
         ratio = qc3d(k)/dum
         prc(k) = prc(k)*ratio
         pra(k) = pra(k)*ratio
         mnuccc(k) = mnuccc(k)*ratio
         psacws(k) = psacws(k)*ratio
         psacwi(k) = psacwi(k)*ratio
         qmults(k) = qmults(k)*ratio
         qmultg(k) = qmultg(k)*ratio
         psacwg(k) = psacwg(k)*ratio
         pgsacw(k) = pgsacw(k)*ratio
         END IF
 ! CONSERVATION OF QI
       dum = (-prd(k)-mnuccc(k)+prci(k)+prai(k)-qmults(k)-qmultg(k)-qmultr(k)-qmultrg(k) &
                 -mnuccd(k)+praci(k)+pracis(k)-eprd(k)-psacwi(k))*dt
       IF (dum.GT.qi3d(k).AND.qi3d(k).GE.qsmall) THEN
         ratio = (qi3d(k)/dt+prd(k)+mnuccc(k)+qmults(k)+qmultg(k)+qmultr(k)+qmultrg(k)+ &
                      mnuccd(k)+psacwi(k))/ &
                       (prci(k)+prai(k)+praci(k)+pracis(k)-eprd(k))
         prci(k) = prci(k)*ratio
         prai(k) = prai(k)*ratio
         praci(k) = praci(k)*ratio
         pracis(k) = pracis(k)*ratio
         eprd(k) = eprd(k)*ratio
         END IF
 ! CONSERVATION OF QR
       dum=((pracs(k)-pre(k))+(qmultr(k)+qmultrg(k)-prc(k))+(mnuccr(k)-pra(k))+ &
              piacr(k)+piacrs(k)+pgracs(k)+pracg(k))*dt
       IF (dum.GT.qr3d(k).AND.qr3d(k).GE.qsmall) THEN
         ratio = (qr3d(k)/dt+prc(k)+pra(k))/ &
              (-pre(k)+qmultr(k)+qmultrg(k)+pracs(k)+mnuccr(k)+piacr(k)+piacrs(k)+pgracs(k)+pracg(k))
         pre(k) = pre(k)*ratio
         pracs(k) = pracs(k)*ratio
         qmultr(k) = qmultr(k)*ratio
         qmultrg(k) = qmultrg(k)*ratio
         mnuccr(k) = mnuccr(k)*ratio
         piacr(k) = piacr(k)*ratio
         piacrs(k) = piacrs(k)*ratio
         pgracs(k) = pgracs(k)*ratio
         pracg(k) = pracg(k)*ratio
         END IF
 ! CONSERVATION OF QNI
 ! CONSERVATION FOR GRAUPEL SCHEME
         IF (igraup.EQ.0) THEN
       dum = (-prds(k)-psacws(k)-prai(k)-prci(k)-pracs(k)-eprds(k)+psacr(k)-piacrs(k)-pracis(k))*dt
       IF (dum.GT.qni3d(k).AND.qni3d(k).GE.qsmall) THEN
         ratio = (qni3d(k)/dt+prds(k)+psacws(k)+prai(k)+prci(k)+pracs(k)+piacrs(k)+pracis(k))/(-eprds(k)+psacr(k))
        eprds(k) = eprds(k)*ratio
        psacr(k) = psacr(k)*ratio
        END IF
 ! FOR NO GRAUPEL, NEED TO INCLUDE FREEZING OF RAIN FOR SNOW
        ELSE IF (igraup.EQ.1) THEN
       dum = (-prds(k)-psacws(k)-prai(k)-prci(k)-pracs(k)-eprds(k)+psacr(k)-piacrs(k)-pracis(k)-mnuccr(k))*dt
       IF (dum.GT.qni3d(k).AND.qni3d(k).GE.qsmall) THEN
        ratio = (qni3d(k)/dt+prds(k)+psacws(k)+prai(k)+prci(k)+pracs(k)+piacrs(k)+pracis(k)+mnuccr(k))/(-eprds(k)+psacr(k))
        eprds(k) = eprds(k)*ratio
        psacr(k) = psacr(k)*ratio
        END IF
        END IF
 ! CONSERVATION OF QG
       dum = (-psacwg(k)-pracg(k)-pgsacw(k)-pgracs(k)-prdg(k)-mnuccr(k)-eprdg(k)-piacr(k)-praci(k)-psacr(k))*dt
       IF (dum.GT.qg3d(k).AND.qg3d(k).GE.qsmall) THEN
         ratio = (qg3d(k)/dt+psacwg(k)+pracg(k)+pgsacw(k)+pgracs(k)+prdg(k)+mnuccr(k)+psacr(k)+&
                   piacr(k)+praci(k))/(-eprdg(k))
        eprdg(k) = eprdg(k)*ratio
       END IF
 ! TENDENCIES
       qv3dten(k) = qv3dten(k)+(-pre(k)-prd(k)-prds(k)-mnuccd(k)-eprd(k)-eprds(k)-prdg(k)-eprdg(k))
 ! BUG FIX HM, 3/1/11, INCLUDE PIACR AND PIACRS
       t3dten(k) = t3dten(k)+(pre(k)                                 &
                *xxlv(k)+(prd(k)+prds(k)+                            &
                 mnuccd(k)+eprd(k)+eprds(k)+prdg(k)+eprdg(k))*xxls(k)+         &
                (psacws(k)+psacwi(k)+mnuccc(k)+mnuccr(k)+                      &
                 qmults(k)+qmultg(k)+qmultr(k)+qmultrg(k)+pracs(k) &
                 +psacwg(k)+pracg(k)+pgsacw(k)+pgracs(k)+piacr(k)+piacrs(k))*xlf(k))/cpm(k)
       qc3dten(k) = qc3dten(k)+                                      &
                  (-pra(k)-prc(k)-mnuccc(k)+pcc(k)-                  &
                   psacws(k)-psacwi(k)-qmults(k)-qmultg(k)-psacwg(k)-pgsacw(k))
       qi3dten(k) = qi3dten(k)+                                      &
          (prd(k)+eprd(k)+psacwi(k)+mnuccc(k)-prci(k)-                                 &
                   prai(k)+qmults(k)+qmultg(k)+qmultr(k)+qmultrg(k)+mnuccd(k)-praci(k)-pracis(k))
       qr3dten(k) = qr3dten(k)+                                      &
                  (pre(k)+pra(k)+prc(k)-pracs(k)-mnuccr(k)-qmultr(k)-qmultrg(k) &
              -piacr(k)-piacrs(k)-pracg(k)-pgracs(k))
       IF (igraup.EQ.0) THEN
       qni3dten(k) = qni3dten(k)+                                    &
            (prai(k)+psacws(k)+prds(k)+pracs(k)+prci(k)+eprds(k)-psacr(k)+piacrs(k)+pracis(k))
       ns3dten(k) = ns3dten(k)+(nsagg(k)+nprci(k)-nscng(k)-ngracs(k)+niacrs(k))
       qg3dten(k) = qg3dten(k)+(pracg(k)+psacwg(k)+pgsacw(k)+pgracs(k)+ &
                     prdg(k)+eprdg(k)+mnuccr(k)+piacr(k)+praci(k)+psacr(k))
       ng3dten(k) = ng3dten(k)+(nscng(k)+ngracs(k)+nnuccr(k)+niacr(k))
 ! FOR NO GRAUPEL, NEED TO INCLUDE FREEZING OF RAIN FOR SNOW
       ELSE IF (igraup.EQ.1) THEN
       qni3dten(k) = qni3dten(k)+                                    &
            (prai(k)+psacws(k)+prds(k)+pracs(k)+prci(k)+eprds(k)-psacr(k)+piacrs(k)+pracis(k)+mnuccr(k))
       ns3dten(k) = ns3dten(k)+(nsagg(k)+nprci(k)-nscng(k)-ngracs(k)+niacrs(k)+nnuccr(k))
       END IF
       nc3dten(k) = nc3dten(k)+(-nnuccc(k)-npsacws(k)                &
             -npra(k)-nprc(k)-npsacwi(k)-npsacwg(k))
       ni3dten(k) = ni3dten(k)+                                      &
        (nnuccc(k)-nprci(k)-nprai(k)+nmults(k)+nmultg(k)+nmultr(k)+nmultrg(k)+ &
                nnuccd(k)-niacr(k)-niacrs(k))
       nr3dten(k) = nr3dten(k)+(nprc1(k)-npracs(k)-nnuccr(k)      &
                    +nragg(k)-niacr(k)-niacrs(k)-npracg(k)-ngracs(k))
 ! HM ADD, WRF-CHEM, ADD TENDENCIES FOR C2PREC
         c2prec(k) = pra(k)+prc(k)+psacws(k)+qmults(k)+qmultg(k)+psacwg(k)+ &
        pgsacw(k)+mnuccc(k)+psacwi(k)
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! NOW CALCULATE SATURATION ADJUSTMENT TO CONDENSE EXTRA VAPOR ABOVE
 ! WATER SATURATION
       dumt = t3d(k)+dt*t3dten(k)
       dumqv = qv3d(k) + dt * qv3dten(k)
       ! hm, add fix for low pressure, 5/12/10
       dum=min(0.99*pres(k),polysvp(dumt,0))
       dumqss = ep_2*dum/(pres(k)-dum)
       dumqc = qc3d(k) + dt * qc3dten(k)
       dumqc = max(dumqc,0.)
 ! SATURATION ADJUSTMENT FOR LIQUID
       dums = dumqv-dumqss
       pcc(k) = dums/(1.+xxlv(k)**2*dumqss/(cpm(k)*rv*dumt**2))/dt
       IF (pcc(k)*dt+dumqc.LT.0.) THEN
            pcc(k) = -dumqc/dt
       END IF
       qv3dten(k) = qv3dten(k)-pcc(k)
       t3dten(k) = t3dten(k)+pcc(k)*xxlv(k)/cpm(k)
       qc3dten(k) = qc3dten(k)+pcc(k)
 ! Fortran version
 !.......................................................................
 ! ACTIVATION OF CLOUD DROPLETS
 ! ACTIVATION OF DROPLET CURRENTLY NOT CALCULATED
 ! DROPLET CONCENTRATION IS SPECIFIED !!!!!
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! SUBLIMATE, MELT, OR EVAPORATE NUMBER CONCENTRATION
 ! THIS FORMULATION ASSUMES 1:1 RATIO BETWEEN MASS LOSS AND
 ! LOSS OF NUMBER CONCENTRATION
 !     IF (PCC(K).LT.0.) THEN
 !        DUM = PCC(K)*DT/QC3D(K)
 !           DUM = MAX(-1.,DUM)
 !        NSUBC(K) = DUM*NC3D(K)/DT
 !     END IF
       IF (eprd(k).LT.0.) THEN
          dum = eprd(k)*dt/qi3d(k)
             dum = max(-1.,dum)
          nsubi(k) = dum*ni3d(k)/dt
       END IF
       IF (eprds(k).LT.0.) THEN
          dum = eprds(k)*dt/qni3d(k)
            dum = max(-1.,dum)
          nsubs(k) = dum*ns3d(k)/dt
       END IF
       IF (pre(k).LT.0.) THEN
          dum = pre(k)*dt/qr3d(k)
            dum = max(-1.,dum)
          nsubr(k) = dum*nr3d(k)/dt
       END IF
       IF (eprdg(k).LT.0.) THEN
          dum = eprdg(k)*dt/qg3d(k)
            dum = max(-1.,dum)
          nsubg(k) = dum*ng3d(k)/dt
       END IF
 !        nsubr(k)=0.
 !        nsubs(k)=0.
 !        nsubg(k)=0.
 ! UPDATE TENDENCIES
 !        NC3DTEN(K) = NC3DTEN(K)+NSUBC(K)
          ni3dten(k) = ni3dten(k)+nsubi(k)
          ns3dten(k) = ns3dten(k)+nsubs(k)
          ng3dten(k) = ng3dten(k)+nsubg(k)
          nr3dten(k) = nr3dten(k)+nsubr(k)
          END IF !!!!!! TEMPERATURE
 ! SWITCH LTRUE TO 1, SINCE HYDROMETEORS ARE PRESENT
          ltrue = 1
  200     CONTINUE
         END DO
 ! INITIALIZE PRECIP AND SNOW RATES
       precrt = 0.
       snowrt = 0.
 ! hm added 7/13/13
       snowprt = 0.
       grplprt = 0.
 ! IF THERE ARE NO HYDROMETEORS, THEN SKIP TO END OF SUBROUTINE
       DO k = kts,kte
 ! Fortran version
      END DO
         IF (ltrue.EQ.0) GOTO 400
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 !.......................................................................
 ! CALCULATE SEDIMENATION
 ! THE NUMERICS HERE FOLLOW FROM REISNER ET AL. (1998)
 ! FALLOUT TERMS ARE CALCULATED ON SPLIT TIME STEPS TO ENSURE NUMERICAL
 ! STABILITY, I.E. COURANT# < 1
 !.......................................................................
       nstep = 1
       DO k = kte,kts,-1
         dumi(k) = qi3d(k)+qi3dten(k)*dt
         dumqs(k) = qni3d(k)+qni3dten(k)*dt
         dumr(k) = qr3d(k)+qr3dten(k)*dt
         dumfni(k) = ni3d(k)+ni3dten(k)*dt
         dumfns(k) = ns3d(k)+ns3dten(k)*dt
         dumfnr(k) = nr3d(k)+nr3dten(k)*dt
         dumc(k) = qc3d(k)+qc3dten(k)*dt
         dumfnc(k) = nc3d(k)+nc3dten(k)*dt
         dumg(k) = qg3d(k)+qg3dten(k)*dt
         dumfng(k) = ng3d(k)+ng3dten(k)*dt
 ! SWITCH FOR CONSTANT DROPLET NUMBER
         IF (iinum.EQ.1) THEN
         dumfnc(k) = nc3d(k)
         END IF
 ! GET DUMMY LAMDA FOR SEDIMENTATION CALCULATIONS
 ! MAKE SURE NUMBER CONCENTRATIONS ARE POSITIVE
       dumfni(k) = max(0.,dumfni(k))
       dumfns(k) = max(0.,dumfns(k))
       dumfnc(k) = max(0.,dumfnc(k))
       dumfnr(k) = max(0.,dumfnr(k))
       dumfng(k) = max(0.,dumfng(k))
 !......................................................................
 ! CLOUD ICE
       IF (dumi(k).GE.qsmall) THEN
         dlami = (cons12*dumfni(k)/dumi(k))**(1./di)
         dlami=max(dlami,lammini)
         dlami=min(dlami,lammaxi)
       END IF
 !......................................................................
 ! RAIN
       IF (dumr(k).GE.qsmall) THEN
         dlamr = (pi*rhow*dumfnr(k)/dumr(k))**(1./3.)
         dlamr=max(dlamr,lamminr)
         dlamr=min(dlamr,lammaxr)
       END IF
 !......................................................................
 ! CLOUD DROPLETS
       IF (dumc(k).GE.qsmall) THEN
          dum = pres(k)/(287.15*t3d(k))
          pgam(k)=0.0005714*(nc3d(k)/1.e6*dum)+0.2714
          pgam(k)=1./(pgam(k)**2)-1.
          pgam(k)=max(pgam(k),2.)
          pgam(k)=min(pgam(k),10.)
         dlamc = (cons26*dumfnc(k)*gamma(pgam(k)+4.)/(dumc(k)*gamma(pgam(k)+1.)))**(1./3.)
         lammin = (pgam(k)+1.)/60.e-6
         lammax = (pgam(k)+1.)/1.e-6
         dlamc=max(dlamc,lammin)
         dlamc=min(dlamc,lammax)
       END IF
 !......................................................................
 ! SNOW
       IF (dumqs(k).GE.qsmall) THEN
         dlams = (cons1*dumfns(k)/ dumqs(k))**(1./ds)
         dlams=max(dlams,lammins)
         dlams=min(dlams,lammaxs)
       END IF
 !......................................................................
 ! GRAUPEL
       IF (dumg(k).GE.qsmall) THEN
         dlamg = (cons2*dumfng(k)/ dumg(k))**(1./dg)
         dlamg=max(dlamg,lamming)
         dlamg=min(dlamg,lammaxg)
       END IF
 !......................................................................
 ! CALCULATE NUMBER-WEIGHTED AND MASS-WEIGHTED TERMINAL FALL SPEEDS
 ! CLOUD WATER
       IF (dumc(k).GE.qsmall) THEN
       unc =  acn(k)*gamma(1.+bc+pgam(k))/ (dlamc**bc*gamma(pgam(k)+1.))
       umc = acn(k)*gamma(4.+bc+pgam(k))/  (dlamc**bc*gamma(pgam(k)+4.))
       ELSE
       umc = 0.
       unc = 0.
       END IF
       IF (dumi(k).GE.qsmall) THEN
       uni =  ain(k)*cons27/dlami**bi
       umi = ain(k)*cons28/(dlami**bi)
       ELSE
       umi = 0.
       uni = 0.
       END IF
       IF (dumr(k).GE.qsmall) THEN
       unr = arn(k)*cons6/dlamr**br
       umr = arn(k)*cons4/(dlamr**br)
       ELSE
       umr = 0.
       unr = 0.
       END IF
       IF (dumqs(k).GE.qsmall) THEN
       ums = asn(k)*cons3/(dlams**bs)
       uns = asn(k)*cons5/dlams**bs
       ELSE
       ums = 0.
       uns = 0.
       END IF
       IF (dumg(k).GE.qsmall) THEN
       umg = agn(k)*cons7/(dlamg**bg)
       ung = agn(k)*cons8/dlamg**bg
       ELSE
       umg = 0.
       ung = 0.
       END IF
 ! SET REALISTIC LIMITS ON FALLSPEED
 ! bug fix, 10/08/09
         dum=(rhosu/rho(k))**0.54
         ums=min(ums,1.2*dum)
         uns=min(uns,1.2*dum)
 ! fix 053011
 ! fix for correction by AA 4/6/11
         umi=min(umi,1.2*(rhosu/rho(k))**0.35)
         uni=min(uni,1.2*(rhosu/rho(k))**0.35)
         umr=min(umr,9.1*dum)
         unr=min(unr,9.1*dum)
         umg=min(umg,20.*dum)
         ung=min(ung,20.*dum)
       fr(k) = umr
       fi(k) = umi
       fni(k) = uni
       fs(k) = ums
       fns(k) = uns
       fnr(k) = unr
       fc(k) = umc
       fnc(k) = unc
       fg(k) = umg
       fng(k) = ung
 ! V3.3 MODIFY FALLSPEED BELOW LEVEL OF PRECIP
         IF (k.LE.kte-1) THEN
         IF (fr(k).LT.1.e-10) THEN
         fr(k)=fr(k+1)
         END IF
         IF (fi(k).LT.1.e-10) THEN
         fi(k)=fi(k+1)
         END IF
         IF (fni(k).LT.1.e-10) THEN
         fni(k)=fni(k+1)
         END IF
         IF (fs(k).LT.1.e-10) THEN
         fs(k)=fs(k+1)
         END IF
         IF (fns(k).LT.1.e-10) THEN
         fns(k)=fns(k+1)
         END IF
         IF (fnr(k).LT.1.e-10) THEN
         fnr(k)=fnr(k+1)
         END IF
         IF (fc(k).LT.1.e-10) THEN
         fc(k)=fc(k+1)
         END IF
         IF (fnc(k).LT.1.e-10) THEN
         fnc(k)=fnc(k+1)
         END IF
         IF (fg(k).LT.1.e-10) THEN
         fg(k)=fg(k+1)
         END IF
         IF (fng(k).LT.1.e-10) THEN
         fng(k)=fng(k+1)
         END IF
         END IF ! K LE KTE-1
 ! CALCULATE NUMBER OF SPLIT TIME STEPS
       rgvm = max(fr(k),fi(k),fs(k),fc(k),fni(k),fnr(k),fns(k),fnc(k),fg(k),fng(k))
 ! VVT CHANGED IFIX -> INT (GENERIC FUNCTION)
       nstep = max(int(rgvm*dt/dzq(k)+1.),nstep)
 ! Fortran version
 ! MULTIPLY VARIABLES BY RHO
       dumr(k) = dumr(k)*rho(k)
       dumi(k) = dumi(k)*rho(k)
       dumfni(k) = dumfni(k)*rho(k)
       dumqs(k) = dumqs(k)*rho(k)
       dumfns(k) = dumfns(k)*rho(k)
       dumfnr(k) = dumfnr(k)*rho(k)
       dumc(k) = dumc(k)*rho(k)
       dumfnc(k) = dumfnc(k)*rho(k)
       dumg(k) = dumg(k)*rho(k)
       dumfng(k) = dumfng(k)*rho(k)
       END DO
       DO n = 1,nstep
       DO k = kts,kte
       faloutr(k) = fr(k)*dumr(k)
       falouti(k) = fi(k)*dumi(k)
       faloutni(k) = fni(k)*dumfni(k)
       falouts(k) = fs(k)*dumqs(k)
       faloutns(k) = fns(k)*dumfns(k)
       faloutnr(k) = fnr(k)*dumfnr(k)
       faloutc(k) = fc(k)*dumc(k)
       faloutnc(k) = fnc(k)*dumfnc(k)
       faloutg(k) = fg(k)*dumg(k)
       faloutng(k) = fng(k)*dumfng(k)
       END DO
 ! TOP OF MODEL
       k = kte
       faltndr = faloutr(k)/dzq(k)
       faltndi = falouti(k)/dzq(k)
       faltndni = faloutni(k)/dzq(k)
       faltnds = falouts(k)/dzq(k)
       faltndns = faloutns(k)/dzq(k)
       faltndnr = faloutnr(k)/dzq(k)
       faltndc = faloutc(k)/dzq(k)
       faltndnc = faloutnc(k)/dzq(k)
       faltndg = faloutg(k)/dzq(k)
       faltndng = faloutng(k)/dzq(k)
 ! ADD FALLOUT TERMS TO EULERIAN TENDENCIES
       qrsten(k) = qrsten(k)-faltndr/nstep/rho(k)
       qisten(k) = qisten(k)-faltndi/nstep/rho(k)
       ni3dten(k) = ni3dten(k)-faltndni/nstep/rho(k)
       qnisten(k) = qnisten(k)-faltnds/nstep/rho(k)
       ns3dten(k) = ns3dten(k)-faltndns/nstep/rho(k)
       nr3dten(k) = nr3dten(k)-faltndnr/nstep/rho(k)
       qcsten(k) = qcsten(k)-faltndc/nstep/rho(k)
       nc3dten(k) = nc3dten(k)-faltndnc/nstep/rho(k)
       qgsten(k) = qgsten(k)-faltndg/nstep/rho(k)
       ng3dten(k) = ng3dten(k)-faltndng/nstep/rho(k)
       dumr(k) = dumr(k)-faltndr*dt/nstep
       dumi(k) = dumi(k)-faltndi*dt/nstep
       dumfni(k) = dumfni(k)-faltndni*dt/nstep
       dumqs(k) = dumqs(k)-faltnds*dt/nstep
       dumfns(k) = dumfns(k)-faltndns*dt/nstep
       dumfnr(k) = dumfnr(k)-faltndnr*dt/nstep
       dumc(k) = dumc(k)-faltndc*dt/nstep
       dumfnc(k) = dumfnc(k)-faltndnc*dt/nstep
       dumg(k) = dumg(k)-faltndg*dt/nstep
       dumfng(k) = dumfng(k)-faltndng*dt/nstep
       DO k = kte-1,kts,-1
       faltndr = (faloutr(k+1)-faloutr(k))/dzq(k)
       faltndi = (falouti(k+1)-falouti(k))/dzq(k)
       faltndni = (faloutni(k+1)-faloutni(k))/dzq(k)
       faltnds = (falouts(k+1)-falouts(k))/dzq(k)
       faltndns = (faloutns(k+1)-faloutns(k))/dzq(k)
       faltndnr = (faloutnr(k+1)-faloutnr(k))/dzq(k)
       faltndc = (faloutc(k+1)-faloutc(k))/dzq(k)
       faltndnc = (faloutnc(k+1)-faloutnc(k))/dzq(k)
       faltndg = (faloutg(k+1)-faloutg(k))/dzq(k)
       faltndng = (faloutng(k+1)-faloutng(k))/dzq(k)
 ! ADD FALLOUT TERMS TO EULERIAN TENDENCIES
       qrsten(k) = qrsten(k)+faltndr/nstep/rho(k)
       qisten(k) = qisten(k)+faltndi/nstep/rho(k)
       ni3dten(k) = ni3dten(k)+faltndni/nstep/rho(k)
       qnisten(k) = qnisten(k)+faltnds/nstep/rho(k)
       ns3dten(k) = ns3dten(k)+faltndns/nstep/rho(k)
       nr3dten(k) = nr3dten(k)+faltndnr/nstep/rho(k)
       qcsten(k) = qcsten(k)+faltndc/nstep/rho(k)
       nc3dten(k) = nc3dten(k)+faltndnc/nstep/rho(k)
       qgsten(k) = qgsten(k)+faltndg/nstep/rho(k)
       ng3dten(k) = ng3dten(k)+faltndng/nstep/rho(k)
 ! Fortran version
       dumr(k) = dumr(k)+faltndr*dt/nstep
       dumi(k) = dumi(k)+faltndi*dt/nstep
       dumfni(k) = dumfni(k)+faltndni*dt/nstep
       dumqs(k) = dumqs(k)+faltnds*dt/nstep
       dumfns(k) = dumfns(k)+faltndns*dt/nstep
       dumfnr(k) = dumfnr(k)+faltndnr*dt/nstep
       dumc(k) = dumc(k)+faltndc*dt/nstep
       dumfnc(k) = dumfnc(k)+faltndnc*dt/nstep
       dumg(k) = dumg(k)+faltndg*dt/nstep
       dumfng(k) = dumfng(k)+faltndng*dt/nstep
 ! FOR WRF-CHEM, NEED PRECIP RATES (UNITS OF KG/M^2/S)
           csed(k)=csed(k)+faloutc(k)/nstep
           ised(k)=ised(k)+falouti(k)/nstep
           ssed(k)=ssed(k)+falouts(k)/nstep
           gsed(k)=gsed(k)+faloutg(k)/nstep
           rsed(k)=rsed(k)+faloutr(k)/nstep
       END DO
 ! GET PRECIPITATION AND SNOWFALL ACCUMULATION DURING THE TIME STEP
 ! FACTOR OF 1000 CONVERTS FROM M TO MM, BUT DIVISION BY DENSITY
 ! OF LIQUID WATER CANCELS THIS FACTOR OF 1000
         precrt = precrt+(faloutr(kts)+faloutc(kts)+falouts(kts)+falouti(kts)+faloutg(kts))  &
                      *dt/nstep
         snowrt = snowrt+(falouts(kts)+falouti(kts)+faloutg(kts))*dt/nstep
 ! hm added 7/13/13
         snowprt = snowprt+(falouti(kts)+falouts(kts))*dt/nstep
         grplprt = grplprt+(faloutg(kts))*dt/nstep
       END DO
         DO k=kts,kte
 ! Fortran version
 ! ADD ON SEDIMENTATION TENDENCIES FOR MIXING RATIO TO REST OF TENDENCIES
         qr3dten(k)=qr3dten(k)+qrsten(k)
         qi3dten(k)=qi3dten(k)+qisten(k)
         qc3dten(k)=qc3dten(k)+qcsten(k)
         qg3dten(k)=qg3dten(k)+qgsten(k)
         qni3dten(k)=qni3dten(k)+qnisten(k)
 ! Fortran version
 ! PUT ALL CLOUD ICE IN SNOW CATEGORY IF MEAN DIAMETER EXCEEDS 2 * dcs
 !hm 4/7/09 bug fix
 !        IF (QI3D(K).GE.QSMALL.AND.T3D(K).LT.273.15) THEN
         IF (qi3d(k).GE.qsmall.AND.t3d(k).LT.273.15.AND.lami(k).GE.1.e-10) THEN
         IF (1./lami(k).GE.2.*dcs) THEN
            qni3dten(k) = qni3dten(k)+qi3d(k)/dt+ qi3dten(k)
            ns3dten(k) = ns3dten(k)+ni3d(k)/dt+   ni3dten(k)
            qi3dten(k) = -qi3d(k)/dt
            ni3dten(k) = -ni3d(k)/dt
         END IF
         END IF
 ! hm add tendencies here, then call sizeparameter
 ! to ensure consisitency between mixing ratio and number concentration
           qc3d(k)        = qc3d(k)+qc3dten(k)*dt
           qi3d(k)        = qi3d(k)+qi3dten(k)*dt
           qni3d(k)        = qni3d(k)+qni3dten(k)*dt
           qr3d(k)        = qr3d(k)+qr3dten(k)*dt
           nc3d(k)        = nc3d(k)+nc3dten(k)*dt
           ni3d(k)        = ni3d(k)+ni3dten(k)*dt
           ns3d(k)        = ns3d(k)+ns3dten(k)*dt
           nr3d(k)        = nr3d(k)+nr3dten(k)*dt
 ! Fortran version
           IF (igraup.EQ.0) THEN
           qg3d(k)        = qg3d(k)+qg3dten(k)*dt
           ng3d(k)        = ng3d(k)+ng3dten(k)*dt
           END IF
 ! ADD TEMPERATURE AND WATER VAPOR TENDENCIES FROM MICROPHYSICS
           t3d(k)         = t3d(k)+t3dten(k)*dt
           qv3d(k)        = qv3d(k)+qv3dten(k)*dt
 ! Fortran version
 ! SATURATION VAPOR PRESSURE AND MIXING RATIO
 ! hm, add fix for low pressure, 5/12/10
             evs(k) = min(0.99*pres(k),polysvp(t3d(k),0))   ! PA
             eis(k) = min(0.99*pres(k),polysvp(t3d(k),1))   ! PA
 ! MAKE SURE ICE SATURATION DOESN'T EXCEED WATER SAT. NEAR FREEZING
             IF (eis(k).GT.evs(k)) eis(k) = evs(k)
             qvs(k) = ep_2*evs(k)/(pres(k)-evs(k))
             qvi(k) = ep_2*eis(k)/(pres(k)-eis(k))
             qvqvs(k) = qv3d(k)/qvs(k)
             qvqvsi(k) = qv3d(k)/qvi(k)
 ! Fortran version
 ! AT SUBSATURATION, REMOVE SMALL AMOUNTS OF CLOUD/PRECIP WATER
 ! hm 7/9/09 change limit to 1.e-8
              IF (qvqvs(k).LT.0.9) THEN
                IF (qr3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qr3d(k)
                   t3d(k)=t3d(k)-qr3d(k)*xxlv(k)/cpm(k)
                   qr3d(k)=0.
                END IF
                IF (qc3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qc3d(k)
                   t3d(k)=t3d(k)-qc3d(k)*xxlv(k)/cpm(k)
                   qc3d(k)=0.
                END IF
              END IF
              IF (qvqvsi(k).LT.0.9) THEN
                IF (qi3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qi3d(k)
                   t3d(k)=t3d(k)-qi3d(k)*xxls(k)/cpm(k)
                   qi3d(k)=0.
                END IF
                IF (qni3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qni3d(k)
                   t3d(k)=t3d(k)-qni3d(k)*xxls(k)/cpm(k)
                   qni3d(k)=0.
                END IF
                IF (qg3d(k).LT.1.e-8) THEN
                   qv3d(k)=qv3d(k)+qg3d(k)
                   t3d(k)=t3d(k)-qg3d(k)*xxls(k)/cpm(k)
                   qg3d(k)=0.
                END IF
              END IF
 ! Fortran version
 !..................................................................
 ! IF MIXING RATIO < QSMALL SET MIXING RATIO AND NUMBER CONC TO ZERO
        IF (qc3d(k).LT.qsmall) THEN
          qc3d(k) = 0.
          nc3d(k) = 0.
          effc(k) = 0.
        END IF
        IF (qr3d(k).LT.qsmall) THEN
          qr3d(k) = 0.
          nr3d(k) = 0.
          effr(k) = 0.
        END IF
        IF (qi3d(k).LT.qsmall) THEN
          qi3d(k) = 0.
          ni3d(k) = 0.
          effi(k) = 0.
        END IF
        IF (qni3d(k).LT.qsmall) THEN
          qni3d(k) = 0.
          ns3d(k) = 0.
          effs(k) = 0.
        END IF
        IF (qg3d(k).LT.qsmall) THEN
          qg3d(k) = 0.
          ng3d(k) = 0.
          effg(k) = 0.
        END IF
 ! Fortran version
 !..................................
 ! IF THERE IS NO CLOUD/PRECIP WATER, THEN SKIP CALCULATIONS
             IF (qc3d(k).LT.qsmall.AND.qi3d(k).LT.qsmall.AND.qni3d(k).LT.qsmall &
                  .AND.qr3d(k).LT.qsmall.AND.qg3d(k).LT.qsmall) GOTO 500
 !CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
 ! CALCULATE INSTANTANEOUS PROCESSES
 ! ADD MELTING OF CLOUD ICE TO FORM RAIN
         IF (qi3d(k).GE.qsmall.AND.t3d(k).GE.273.15) THEN
            qr3d(k) = qr3d(k)+qi3d(k)
            t3d(k) = t3d(k)-qi3d(k)*xlf(k)/cpm(k)
            qi3d(k) = 0.
            nr3d(k) = nr3d(k)+ni3d(k)
            ni3d(k) = 0.
         END IF
 ! Fortran version
 ! ****SENSITIVITY - NO ICE
         IF (iliq.EQ.1) GOTO 778
 ! HOMOGENEOUS FREEZING OF CLOUD WATER
         IF (t3d(k).LE.233.15.AND.qc3d(k).GE.qsmall) THEN
            qi3d(k)=qi3d(k)+qc3d(k)
            t3d(k)=t3d(k)+qc3d(k)*xlf(k)/cpm(k)
            qc3d(k)=0.
            ni3d(k)=ni3d(k)+nc3d(k)
            nc3d(k)=0.
         END IF
 ! Fortran version
 ! HOMOGENEOUS FREEZING OF RAIN
         IF (igraup.EQ.0) THEN
         IF (t3d(k).LE.233.15.AND.qr3d(k).GE.qsmall) THEN
            qg3d(k) = qg3d(k)+qr3d(k)
            t3d(k) = t3d(k)+qr3d(k)*xlf(k)/cpm(k)
            qr3d(k) = 0.
            ng3d(k) = ng3d(k)+ nr3d(k)
            nr3d(k) = 0.
         END IF
         ELSE IF (igraup.EQ.1) THEN
         IF (t3d(k).LE.233.15.AND.qr3d(k).GE.qsmall) THEN
            qni3d(k) = qni3d(k)+qr3d(k)
            t3d(k) = t3d(k)+qr3d(k)*xlf(k)/cpm(k)
            qr3d(k) = 0.
            ns3d(k) = ns3d(k)+nr3d(k)
            nr3d(k) = 0.
         END IF
         END IF
 ! Fortran version
  778    CONTINUE
 ! MAKE SURE NUMBER CONCENTRATIONS AREN'T NEGATIVE
       ni3d(k) = max(0.,ni3d(k))
       ns3d(k) = max(0.,ns3d(k))
       nc3d(k) = max(0.,nc3d(k))
       nr3d(k) = max(0.,nr3d(k))
       ng3d(k) = max(0.,ng3d(k))
 !......................................................................
 ! CLOUD ICE
       IF (qi3d(k).GE.qsmall) THEN
          lami(k) = (cons12*                 &
               ni3d(k)/qi3d(k))**(1./di)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lami(k).LT.lammini) THEN
       lami(k) = lammini
       n0i(k) = lami(k)**4*qi3d(k)/cons12
       ni3d(k) = n0i(k)/lami(k)
       ELSE IF (lami(k).GT.lammaxi) THEN
       lami(k) = lammaxi
       n0i(k) = lami(k)**4*qi3d(k)/cons12
       ni3d(k) = n0i(k)/lami(k)
       END IF
       END IF
 !......................................................................
 ! RAIN
       IF (qr3d(k).GE.qsmall) THEN
       lamr(k) = (pi*rhow*nr3d(k)/qr3d(k))**(1./3.)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lamr(k).LT.lamminr) THEN
       lamr(k) = lamminr
       n0rr(k) = lamr(k)**4*qr3d(k)/(pi*rhow)
       nr3d(k) = n0rr(k)/lamr(k)
       ELSE IF (lamr(k).GT.lammaxr) THEN
       lamr(k) = lammaxr
       n0rr(k) = lamr(k)**4*qr3d(k)/(pi*rhow)
       nr3d(k) = n0rr(k)/lamr(k)
       END IF
       END IF
 !......................................................................
 ! CLOUD DROPLETS
 ! MARTIN ET AL. (1994) FORMULA FOR PGAM
       IF (qc3d(k).GE.qsmall) THEN
          dum = pres(k)/(287.15*t3d(k))
          pgam(k)=0.0005714*(nc3d(k)/1.e6*dum)+0.2714
          pgam(k)=1./(pgam(k)**2)-1.
          pgam(k)=max(pgam(k),2.)
          pgam(k)=min(pgam(k),10.)
 ! CALCULATE LAMC
       lamc(k) = (cons26*nc3d(k)*gamma(pgam(k)+4.)/   &
                  (qc3d(k)*gamma(pgam(k)+1.)))**(1./3.)
 ! LAMMIN, 60 MICRON DIAMETER
 ! LAMMAX, 1 MICRON
       lammin = (pgam(k)+1.)/60.e-6
       lammax = (pgam(k)+1.)/1.e-6
       IF (lamc(k).LT.lammin) THEN
       lamc(k) = lammin
       nc3d(k) = exp(3.*log(lamc(k))+log(qc3d(k))+              &
                 log(gamma(pgam(k)+1.))-log(gamma(pgam(k)+4.)))/cons26
       ELSE IF (lamc(k).GT.lammax) THEN
       lamc(k) = lammax
       nc3d(k) = exp(3.*log(lamc(k))+log(qc3d(k))+              &
                 log(gamma(pgam(k)+1.))-log(gamma(pgam(k)+4.)))/cons26
       END IF
       END IF
 !......................................................................
 ! SNOW
       IF (qni3d(k).GE.qsmall) THEN
       lams(k) = (cons1*ns3d(k)/qni3d(k))**(1./ds)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lams(k).LT.lammins) THEN
       lams(k) = lammins
       n0s(k) = lams(k)**4*qni3d(k)/cons1
       ns3d(k) = n0s(k)/lams(k)
       ELSE IF (lams(k).GT.lammaxs) THEN
       lams(k) = lammaxs
       n0s(k) = lams(k)**4*qni3d(k)/cons1
       ns3d(k) = n0s(k)/lams(k)
       END IF
       END IF
 !......................................................................
 ! GRAUPEL
       IF (qg3d(k).GE.qsmall) THEN
       lamg(k) = (cons2*ng3d(k)/qg3d(k))**(1./dg)
 ! CHECK FOR SLOPE
 ! ADJUST VARS
       IF (lamg(k).LT.lamming) THEN
       lamg(k) = lamming
       n0g(k) = lamg(k)**4*qg3d(k)/cons2
       ng3d(k) = n0g(k)/lamg(k)
       ELSE IF (lamg(k).GT.lammaxg) THEN
       lamg(k) = lammaxg
       n0g(k) = lamg(k)**4*qg3d(k)/cons2
       ng3d(k) = n0g(k)/lamg(k)
       END IF
       END IF
  500  CONTINUE
 ! CALCULATE EFFECTIVE RADIUS
       IF (qi3d(k).GE.qsmall) THEN
          effi(k) = 3./lami(k)/2.*1.e6
       ELSE
          effi(k) = 25.
       END IF
       IF (qni3d(k).GE.qsmall) THEN
          effs(k) = 3./lams(k)/2.*1.e6
       ELSE
          effs(k) = 25.
       END IF
       IF (qr3d(k).GE.qsmall) THEN
          effr(k) = 3./lamr(k)/2.*1.e6
       ELSE
          effr(k) = 25.
       END IF
       IF (qc3d(k).GE.qsmall) THEN
       effc(k) = gamma(pgam(k)+4.)/                        &
              gamma(pgam(k)+3.)/lamc(k)/2.*1.e6
       ELSE
       effc(k) = 25.
       END IF
       IF (qg3d(k).GE.qsmall) THEN
          effg(k) = 3./lamg(k)/2.*1.e6
       ELSE
          effg(k) = 25.
       END IF
 ! HM ADD 1/10/06, ADD UPPER BOUND ON ICE NUMBER, THIS IS NEEDED
 ! TO PREVENT VERY LARGE ICE NUMBER DUE TO HOMOGENEOUS FREEZING
 ! OF DROPLETS, ESPECIALLY WHEN INUM = 1, SET MAX AT 10 CM-3
 !          NI3D(K) = MIN(NI3D(K),10.E6/RHO(K))
 ! HM, 12/28/12, LOWER MAXIMUM ICE CONCENTRATION TO ADDRESS PROBLEM
 ! OF EXCESSIVE AND PERSISTENT ANVIL
 ! NOTE: THIS MAY CHANGE/REDUCE SENSITIVITY TO AEROSOL/CCN CONCENTRATION
           ni3d(k) = min(ni3d(k),0.3e6/rho(k))
 ! ADD BOUND ON DROPLET NUMBER - CANNOT EXCEED AEROSOL CONCENTRATION
           IF (iinum.EQ.0.AND.iact.EQ.2) THEN
           nc3d(k) = min(nc3d(k),(nanew1+nanew2)/rho(k))
           END IF
 ! SWITCH FOR CONSTANT DROPLET NUMBER
           IF (iinum.EQ.1) THEN
 ! CHANGE NDCNST FROM CM-3 TO KG-1
              nc3d(k) = ndcnst*1.e6/rho(k)
           END IF
       END DO !!! K LOOP
  400         CONTINUE
 ! ALL DONE !!!!!!!!!!!
       RETURN
Referenced by mp_morr_two_moment().
mp_morr_two_moment()
subroutine, public module_mp_morr_two_moment::mp_morr_two_moment (integer, intent(in) ITIMESTEP, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) TH, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) QV, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) QC, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) QR, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) QI, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) QS, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) QG, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) NI, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) NS, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) NR, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) NG, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) RHO, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) PII, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) P, real(c_double), intent(in) DT_IN, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) DZ, real(c_double), dimension(ims:ime ,jms:jme), intent(in) HT, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) W, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) RAINNC, real(c_double), dimension(ims:ime, jms:jme), intent(inout) RAINNCV, real(c_double), dimension(ims:ime, jms:jme), intent(inout) SR, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) SNOWNC, real(c_double), dimension(ims:ime, jms:jme), intent(inout) SNOWNCV, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout) GRAUPELNC, real(c_double), dimension(ims:ime, jms:jme), intent(inout) GRAUPELNCV, real(c_double), dimension(ims:ime, jms:kme, kms:jme), intent(inout) refl_10cm, logical, intent(in), optional diagflag, integer, intent(in), optional do_radar_ref, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) qrcuten, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) qscuten, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(in) qicuten, logical, intent(in), optional F_QNDROP, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional qndrop, integer, intent(in) IDS, integer, intent(in) IDE, integer, intent(in) JDS, integer, intent(in) JDE, integer, intent(in) KDS, integer, intent(in) KDE, integer, intent(in) IMS, integer, intent(in) IME, integer, intent(in) JMS, integer, intent(in) JME, integer, intent(in) KMS, integer, intent(in) KME, integer, intent(in) ITS, integer, intent(in) ITE, integer, intent(in) JTS, integer, intent(in) JTE, integer, intent(in) KTS, integer, intent(in) KTE, logical, intent(in), optional wetscav_on, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional rainprod, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional evapprod, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional QLSINK, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional PRECR, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional PRECI, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional PRECS, real(c_double), dimension(ims:ime, jms:jme, kms:kme), intent(inout), optional PRECG)
 ! QV - water vapor mixing ratio (kg/kg)
 ! QC - cloud water mixing ratio (kg/kg)
 ! QR - rain water mixing ratio (kg/kg)
 ! QI - cloud ice mixing ratio (kg/kg)
 ! QS - snow mixing ratio (kg/kg)
 ! QG - graupel mixing ratio (KG/KG)
 ! NI - cloud ice number concentration (1/kg)
 ! NS - Snow Number concentration (1/kg)
 ! NR - Rain Number concentration (1/kg)
 ! NG - Graupel number concentration (1/kg)
 ! NOTE: RHO AND HT NOT USED BY THIS SCHEME AND DO NOT NEED TO BE PASSED INTO SCHEME!!!!
 ! P - AIR PRESSURE (PA)
 ! W - VERTICAL AIR VELOCITY (M/S)
 ! TH - POTENTIAL TEMPERATURE (K)
 ! PII - exner function - used to convert potential temp to temp
 ! DZ - difference in height over interface (m)
 ! DT_IN - model time step (sec)
 ! ITIMESTEP - time step counter
 ! RAINNC - accumulated grid-scale precipitation (mm)
 ! RAINNCV - one time step grid scale precipitation (mm/time step)
 ! SNOWNC - accumulated grid-scale snow plus cloud ice (mm)
 ! SNOWNCV - one time step grid scale snow plus cloud ice (mm/time step)
 ! GRAUPELNC - accumulated grid-scale graupel (mm)
 ! GRAUPELNCV - one time step grid scale graupel (mm/time step)
 ! SR - one time step mass ratio of snow to total precip
 ! qrcuten, rain tendency from parameterized cumulus convection
 ! qscuten, snow tendency from parameterized cumulus convection
 ! qicuten, cloud ice tendency from parameterized cumulus convection
 ! variables below currently not in use, not coupled to PBL or radiation codes
 ! TKE - turbulence kinetic energy (m^2 s-2), NEEDED FOR DROPLET ACTIVATION (SEE CODE BELOW)
 ! NCTEND - droplet concentration tendency from pbl (kg-1 s-1)
 ! NCTEND - CLOUD ICE concentration tendency from pbl (kg-1 s-1)
 ! KZH - heat eddy diffusion coefficient from YSU scheme (M^2 S-1), NEEDED FOR DROPLET ACTIVATION (SEE CODE BELOW)
 ! EFFCS - CLOUD DROPLET EFFECTIVE RADIUS OUTPUT TO RADIATION CODE (micron)
 ! EFFIS - CLOUD DROPLET EFFECTIVE RADIUS OUTPUT TO RADIATION CODE (micron)
 ! HM, ADDED FOR WRF-CHEM COUPLING
 ! QLSINK - TENDENCY OF CLOUD WATER TO RAIN, SNOW, GRAUPEL (KG/KG/S)
 ! CSED,ISED,SSED,GSED,RSED - SEDIMENTATION FLUXES (KG/M^2/S) FOR CLOUD WATER, ICE, SNOW, GRAUPEL, RAIN
 ! PRECI,PRECS,PRECG,PRECR - SEDIMENTATION FLUXES (KG/M^2/S) FOR ICE, SNOW, GRAUPEL, RAIN
 ! rainprod - total tendency of conversion of cloud water/ice and graupel to rain (kg kg-1 s-1)
 ! evapprod - tendency of evaporation of rain (kg kg-1 s-1)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! reflectivity currently not included!!!!
 ! REFL_10CM - CALCULATED RADAR REFLECTIVITY AT 10 CM (DBZ)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 ! EFFC - DROPLET EFFECTIVE RADIUS (MICRON)
 ! EFFR - RAIN EFFECTIVE RADIUS (MICRON)
 ! EFFS - SNOW EFFECTIVE RADIUS (MICRON)
 ! EFFI - CLOUD ICE EFFECTIVE RADIUS (MICRON)
 ! ADDITIONAL OUTPUT FROM MICRO - SEDIMENTATION TENDENCIES, NEEDED FOR LIQUID-ICE STATIC ENERGY
 ! QGSTEN - GRAUPEL SEDIMENTATION TEND (KG/KG/S)
 ! QRSTEN - RAIN SEDIMENTATION TEND (KG/KG/S)
 ! QISTEN - CLOUD ICE SEDIMENTATION TEND (KG/KG/S)
 ! QNISTEN - SNOW SEDIMENTATION TEND (KG/KG/S)
 ! QCSTEN - CLOUD WATER SEDIMENTATION TEND (KG/KG/S)
    IMPLICIT NONE
    INTEGER,      INTENT(IN   )    ::   ids, ide, jds, jde, kds, kde , &
                                        ims, ime, jms, jme, kms, kme , &
                                        its, ite, jts, jte, kts, kte
    REAL(C_DOUBLE), DIMENSION(ims:ime, jms:jme, kms:kme),          INTENT(INOUT) :: qv, qc, qr, qi, qs, qg, ni, ns, nr, TH, NG
    REAL(C_DOUBLE), DIMENSION(ims:ime, jms:jme, kms:kme), optional,INTENT(INOUT) :: qndrop
    REAL(C_DOUBLE), DIMENSION(ims:ime, jms:jme, kms:kme), optional,INTENT(INOUT) :: QLSINK, rainprod, evapprod, PRECI,PRECS,PRECG, &
      & PRECR
    REAL(C_DOUBLE), DIMENSION(ims:ime, jms:jme, kms:kme),          INTENT(IN   ) :: pii, p, dz, rho, w
    REAL(C_DOUBLE), INTENT(IN):: dt_in
    INTEGER, INTENT(IN):: ITIMESTEP
     REAL(C_DOUBLE), INTENT(INOUT), DIMENSION(ims:ime, jms:jme, kms:kme) :: rainnc, snownc, graupelnc
     REAL(C_DOUBLE), INTENT(INOUT), DIMENSION(ims:ime, jms:jme) :: rainncv, sr,  snowncv, graupelncv
 !   REAL(C_DOUBLE), DIMENSION(ims:ime, jms:jme         ), INTENT(INOUT) :: RAINNC, RAINNCV, SR, SNOWNC,SNOWNCV,GRAUPELNC,GRAUPELNCV
    REAL(C_DOUBLE), DIMENSION(ims:ime, jms:kme, kms:jme), INTENT(INOUT) :: refl_10cm
    REAL(C_DOUBLE), DIMENSION(ims:ime ,jms:jme         ), INTENT(IN   ) :: ht
    LOGICAL, optional, INTENT(IN) :: wetscav_on
    ! LOCAL VARIABLES
    REAL(C_DOUBLE), DIMENSION(its:ite, jts:jte, kts:kte) :: effi, effs, effr, EFFG
    REAL(C_DOUBLE), DIMENSION(its:ite, jts:jte, kts:kte) :: T, EFFC
    REAL(C_DOUBLE), DIMENSION(kts:kte) ::                                 &
                             QC_TEND1D, QI_TEND1D, QNI_TEND1D, QR_TEND1D, &
                             NI_TEND1D, NS_TEND1D, NR_TEND1D,             &
                             QC1D, QI1D, QR1D,NI1D, NS1D, NR1D, QS1D,     &
                             T_TEND1D,QV_TEND1D, T1D, QV1D, P1D, W1D,     &
                             EFFC1D, EFFI1D, EFFS1D, EFFR1D,DZ1D,         &
                             QG_TEND1D, NG_TEND1D, QG1D, NG1D, EFFG1D,    &
 ! ADD SEDIMENTATION TENDENCIES (UNITS OF KG/KG/S)
                             qgsten,qrsten, qisten, qnisten, qcsten,      &
 ! ADD CUMULUS TENDENCIES
                             qrcu1d, qscu1d, qicu1d
 ! add cumulus tendencies
    REAL(C_DOUBLE), DIMENSION(ims:ime, jms:jme, kms:kme), INTENT(IN):: qrcuten, qscuten, qicuten
   LOGICAL, INTENT(IN), OPTIONAL :: F_QNDROP
   LOGICAL :: flag_qndrop  ! wrf-chem
   integer :: iinum ! wrf-chem
 ! wrf-chem
    REAL(C_DOUBLE), DIMENSION(kts:kte) :: nc1d, nc_tend1d,C2PREC,CSED,ISED,SSED,GSED,RSED
    REAL(C_DOUBLE), DIMENSION(kts:kte) :: rainprod1d, evapprod1d
 ! HM add reflectivity
    REAL(C_DOUBLE), DIMENSION(kts:kte) :: dBZ
    REAL(C_DOUBLE) PRECPRT1D, SNOWRT1D, SNOWPRT1D, GRPLPRT1D ! hm added 7/13/13
    INTEGER I,J,K
    REAL(C_DOUBLE) DT
    LOGICAL, OPTIONAL, INTENT(IN) :: diagflag
    INTEGER, OPTIONAL, INTENT(IN) :: do_radar_ref
    LOGICAL :: has_wetscav
    ! return
    print *,'IN MORR_TWO_MOMENT MAIN ROUTINE '
 ! below for wrf-chem
    flag_qndrop = .false.
    IF ( PRESENT ( f_qndrop ) ) flag_qndrop = f_qndrop
 !!!!!!!!!!!!!!!!!!!!!!
    IF( PRESENT( wetscav_on ) ) THEN
      has_wetscav = wetscav_on
    ELSE
      has_wetscav = .false.
    ENDIF
    ! Initialize tendencies (all set to 0) and transfer
    ! array to local variables
    dt = dt_in
    ! Currently mixing of number concentrations also is neglected (not coupled with PBL schemes)
    print *,'IMS IME ',ims,ime
    print *,'JMS JME ',jms,jme
    print *,'KMS KME ',kms,kme
    print *,'ITS ITE ',its,ite
    print *,'JTS JTE ',jts,jte
    print *,'KTS KTE ',kts,kte
    DO i=its,ite
    DO j=jts,jte
    DO k=kts,kte
         t(i,j,k) = th(i,j,k) * pii(i,j,k)
    END DO
    END DO
    END DO
    do i=its,ite      ! i loop (east-west)
    do j=jts,jte      ! j loop (north-south)
    !
    ! Transfer 3D arrays into 1D for microphysical calculations
    !
 ! hm , initialize 1d tendency arrays to zero
       do k=kts,kte   ! k loop (vertical)
           qc_tend1d(k)  = 0.
           qi_tend1d(k)  = 0.
           qni_tend1d(k) = 0.
           qr_tend1d(k)  = 0.
           ni_tend1d(k)  = 0.
           ns_tend1d(k)  = 0.
           nr_tend1d(k)  = 0.
           t_tend1d(k)   = 0.
           qv_tend1d(k)  = 0.
           nc_tend1d(k) = 0. ! wrf-chem
           qc1d(k)       = qc(i,j,k)
           qi1d(k)       = qi(i,j,k)
           qs1d(k)       = qs(i,j,k)
           qr1d(k)       = qr(i,j,k)
           ni1d(k)       = ni(i,j,k)
           ns1d(k)       = ns(i,j,k)
           nr1d(k)       = nr(i,j,k)
 ! HM ADD GRAUPEL
           qg1d(k)       = qg(i,j,k)
           ng1d(k)       = ng(i,j,k)
           qg_tend1d(k)  = 0.
           ng_tend1d(k)  = 0.
           t1d(k)        = t(i,j,k)
           qv1d(k)       = qv(i,j,k)
           p1d(k)        = p(i,j,k)
           dz1d(k)       = dz(i,j,k)
           w1d(k)        = w(i,j,k)
 ! add cumulus tendencies, already decoupled
           qrcu1d(k)     = qrcuten(i,j,k)
           qscu1d(k)     = qscuten(i,j,k)
           qicu1d(k)     = qicuten(i,j,k)
       end do  !jdf added this
 ! below for wrf-chem
    IF (flag_qndrop .AND. PRESENT( qndrop )) THEN
       iact = 3
       DO k = kts, kte
          nc1d(k)=qndrop(i,j,k)
          iinum=0
       ENDDO
    ELSE
       DO k = kts, kte
          nc1d(k)=0. ! temporary placeholder, set to constant in microphysics subroutine
          iinum=1
       ENDDO
    ENDIF
 !jdf  end do
       call morr_two_moment_micro(i,j,itimestep,kts,kte,qc_tend1d, qi_tend1d, qni_tend1d, qr_tend1d,   &
                                  ni_tend1d, ns_tend1d, nr_tend1d,               &
                                  qc1d, qi1d, qs1d, qr1d,ni1d, ns1d, nr1d,       &
                                  t_tend1d,qv_tend1d, t1d, qv1d, p1d, dz1d, w1d, &
                                  precprt1d,snowrt1d,                            &
                                  snowprt1d,grplprt1d,                 & ! hm added 7/13/13
                                  effc1d,effi1d,effs1d,effr1d,dt,                &
                                  qg_tend1d,ng_tend1d,qg1d,ng1d,effg1d,          &
                                  qrcu1d, qscu1d, qicu1d,                        &
 ! ADD SEDIMENTATION TENDENCIES
                                  qgsten,qrsten,qisten,qnisten,qcsten, &
                                  nc1d, nc_tend1d, iinum, c2prec,csed,ised,ssed,gsed,rsed)
    !
    ! Transfer 1D arrays back into 3D arrays
    !
       do k=kts,kte
          ! hm, add tendencies to update global variables
          ! HM, TENDENCIES FOR Q AND N NOW ADDED IN M2005MICRO, SO WE
          ! ONLY NEED TO TRANSFER 1D VARIABLES BACK TO 3D
           qc(i,j,k)        = qc1d(k)
           qi(i,j,k)        = qi1d(k)
           qs(i,j,k)        = qs1d(k)
           qr(i,j,k)        = qr1d(k)
           ni(i,j,k)        = ni1d(k)
           ns(i,j,k)        = ns1d(k)
           nr(i,j,k)        = nr1d(k)
           qg(i,j,k)        = qg1d(k)
           ng(i,j,k)        = ng1d(k)
           t(i,j,k)         = t1d(k)
           th(i,j,k)        = t(i,j,k)/pii(i,j,k) ! CONVERT TEMP BACK TO POTENTIAL TEMP
           qv(i,j,k)        = qv1d(k)
           effc(i,j,k)      = effc1d(k)
           effi(i,j,k)      = effi1d(k)
           effs(i,j,k)      = effs1d(k)
           effr(i,j,k)      = effr1d(k)
           effg(i,j,k)      = effg1d(k)
 ! wrf-chem
           IF (flag_qndrop .AND. PRESENT( qndrop )) THEN
              qndrop(i,j,k) = nc1d(k)
 !jdf         CSED3D(i,j,k) = CSED(k)
           END IF
           IF ( PRESENT( qlsink ) ) THEN
              if(qc(i,j,k)>1.e-10) then
                 qlsink(i,j,k)  = c2prec(k)/qc(i,j,k)
              else
                 qlsink(i,j,k)  = 0.0
              endif
           END IF
           IF ( PRESENT( precr ) ) precr(i,j,k) = rsed(k)
           IF ( PRESENT( preci ) ) preci(i,j,k) = ised(k)
           IF ( PRESENT( precs ) ) precs(i,j,k) = ssed(k)
           IF ( PRESENT( precg ) ) precg(i,j,k) = gsed(k)
 ! EFFECTIVE RADIUS FOR RADIATION CODE (currently not coupled)
 ! HM, ADD LIMIT TO PREVENT BLOWING UP OPTICAL PROPERTIES, 8/18/07
 !          EFFCS(I,J,K)     = MIN(EFFC(I,J,K),50.)
 !          EFFCS(I,J,K)     = MAX(EFFCS(I,J,K),1.)
 !          EFFIS(I,J,K)     = MIN(EFFI(I,J,K),130.)
 !          EFFIS(I,J,K)     = MAX(EFFIS(I,J,K),13.)
       end do
 ! hm modified so that m2005 precip variables correctly match wrf precip variables
       rainnc(i,j,kts)     = rainnc(i,j,kts)+precprt1d
       rainncv(i,j)    = precprt1d
       snownc(i,j,kts)     = snownc(i,j,kts)+snowprt1d
       snowncv(i,j)    = snowprt1d
       graupelnc(i,j,kts)  = graupelnc(i,j,kts)+grplprt1d
       graupelncv(i,j) = grplprt1d
       sr(i,j) = snowrt1d/(precprt1d+1.e-12)
    end do
    end do
Referenced by mp_morr_two_moment_isohelper::mp_morr_two_moment_c().
polysvp()
real(c_double) function, public module_mp_morr_two_moment::polysvp (real(c_double) T, integer TYPE)
 !-------------------------------------------
 !  COMPUTE SATURATION VAPOR PRESSURE
 !  POLYSVP RETURNED IN UNITS OF PA.
 !  T IS INPUT IN UNITS OF K.
 !  TYPE REFERS TO SATURATION WITH RESPECT TO LIQUID (0) OR ICE (1)
 ! REPLACE GOFF-GRATCH WITH FASTER FORMULATION FROM FLATAU ET AL. 1992, TABLE 4 (RIGHT-HAND COLUMN)
       IMPLICIT NONE
       REAL(C_DOUBLE) DUM
       REAL(C_DOUBLE) T
       INTEGER TYPE
 ! ice
       real a0i,a1i,a2i,a3i,a4i,a5i,a6i,a7i,a8i
       data a0i,a1i,a2i,a3i,a4i,a5i,a6i,a7i,a8i /&
         6.11147274, 0.503160820, 0.188439774e-1, &
         0.420895665e-3, 0.615021634e-5,0.602588177e-7, &
         0.385852041e-9, 0.146898966e-11, 0.252751365e-14/
 ! liquid
       real a0,a1,a2,a3,a4,a5,a6,a7,a8
 ! V1.7
       data a0,a1,a2,a3,a4,a5,a6,a7,a8 /&
         6.11239921, 0.443987641, 0.142986287e-1, &
         0.264847430e-3, 0.302950461e-5, 0.206739458e-7, &
         0.640689451e-10,-0.952447341e-13,-0.976195544e-15/
       real dt
 ! ICE
       IF (type.EQ.1) THEN
 !         POLYSVP = 10.**(-9.09718*(273.16/T-1.)-3.56654*                &
 !          LOG10(273.16/T)+0.876793*(1.-T/273.16)+                                              &
 !          LOG10(6.1071))*100.
 ! hm 11/16/20, use Goff-Gratch for T < 195.8 K and Flatau et al. equal or above 195.8 K
       if (t.ge.195.8) then
          dt=t-273.15
          polysvp = a0i + dt*(a1i+dt*(a2i+dt*(a3i+dt*(a4i+dt*(a5i+dt*(a6i+dt*(a7i+a8i*dt)))))))
          polysvp = polysvp*100.
       else
          polysvp = 10.**(-9.09718*(273.16/t-1.)-3.56654* &
           dlog10(273.16d0/t)+0.876793*(1.-t/273.16)+ &
           dlog10(6.1071d0))*100.
       end if
       END IF
 ! LIQUID
       IF (type.EQ.0) THEN
 !         POLYSVP = 10.**(-7.90298*(373.16/T-1.)+                        &
 !             5.02808*LOG10(373.16/T)-                                                                  &
 !             1.3816E-7*(10**(11.344*(1.-T/373.16))-1.)+                                &
 !             8.1328E-3*(10**(-3.49149*(373.16/T-1.))-1.)+                              &
 !             LOG10(1013.246))*100.
 ! hm 11/16/20, use Goff-Gratch for T < 202.0 K and Flatau et al. equal or above 202.0 K
       if (t.ge.202.0) then
          dt = t-273.15
          polysvp = a0 + dt*(a1+dt*(a2+dt*(a3+dt*(a4+dt*(a5+dt*(a6+dt*(a7+a8*dt)))))))
          polysvp = polysvp*100.
       else
 ! note: uncertain below -70 C, but produces physical values (non-negative) unlike flatau
          polysvp = 10.**(-7.90298*(373.16/t-1.)+ &
              5.02808*dlog10(373.16d0/t)- &
              1.3816e-7*(10**(11.344*(1.-t/373.16))-1.)+ &
              8.1328e-3*(10**(-3.49149*(373.16/t-1.))-1.)+ &
              dlog10(1013.246d0))*100.
       end if
       END IF
Referenced by calc_saturation_vapor_pressure(), and morr_two_moment_micro().
Variable Documentation
ac
real(c_double), private module_mp_morr_two_moment::ac private
Referenced by erf_slow_rhs_post(), and morr_two_moment_init().
ag
real(c_double), private module_mp_morr_two_moment::ag private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
ai
real(c_double), private module_mp_morr_two_moment::ai private
      REAL(C_DOUBLE), PRIVATE ::      AI,AC,AS,AR,AG ! 'A' PARAMETER IN FALLSPEED-DIAM RELATIONSHIP
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
aimm
real(c_double), private module_mp_morr_two_moment::aimm private
      REAL(C_DOUBLE), PRIVATE ::      AIMM        ! PARAMETER IN BIGG IMMERSION FREEZING
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
ar
real(c_double), private module_mp_morr_two_moment::ar private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
as
real(c_double), private module_mp_morr_two_moment::as private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
bact
real(c_double), private module_mp_morr_two_moment::bact private
      REAL(C_DOUBLE), PRIVATE ::      BACT    ! ACTIVATION PARAMETER
Referenced by morr_two_moment_init().
bc
real(c_double), private module_mp_morr_two_moment::bc private
Referenced by morr_two_moment_init(), morr_two_moment_micro(), and redistribute_term().
bg
real(c_double), private module_mp_morr_two_moment::bg private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
bi
real(c_double), private module_mp_morr_two_moment::bi private
      REAL(C_DOUBLE), PRIVATE ::      BI,BC,BS,BR,BG ! 'B' PARAMETER IN FALLSPEED-DIAM RELATIONSHIP
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
bimm
real(c_double), private module_mp_morr_two_moment::bimm private
      REAL(C_DOUBLE), PRIVATE ::      BIMM        ! PARAMETER IN BIGG IMMERSION FREEZING
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
br
real(c_double), private module_mp_morr_two_moment::br private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
bs
real(c_double), private module_mp_morr_two_moment::bs private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
c1
real(c_double), private module_mp_morr_two_moment::c1 private
      REAL(C_DOUBLE), PRIVATE ::      C1     ! 'C' IN NCCN = CS^K (CM-3)
Referenced by SatMethods::Bolton_svp_water(), ComputeStrain_T(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), WaterVaporSat::findsp(), morr_two_moment_init(), and z0_est().
cg
real(c_double), private module_mp_morr_two_moment::cg private
Referenced by morr_two_moment_init().
ci
real(c_double), private module_mp_morr_two_moment::ci private
      REAL(C_DOUBLE), PRIVATE ::      CI,DI,CS,DS,CG,DG ! SIZE DISTRIBUTION PARAMETERS FOR CLOUD ICE, SNOW, GRAUPEL
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons1
real(c_double), private module_mp_morr_two_moment::cons1 private
      REAL(C_DOUBLE), PRIVATE :: CONS1,CONS2,CONS3,CONS4,CONS5,CONS6,CONS7,CONS8,CONS9,CONS10
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons10
real(c_double), private module_mp_morr_two_moment::cons10 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons11
real(c_double), private module_mp_morr_two_moment::cons11 private
      REAL(C_DOUBLE), PRIVATE :: CONS11,CONS12,CONS13,CONS14,CONS15,CONS16,CONS17,CONS18,CONS19,CONS20
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons12
real(c_double), private module_mp_morr_two_moment::cons12 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons13
real(c_double), private module_mp_morr_two_moment::cons13 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons14
real(c_double), private module_mp_morr_two_moment::cons14 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons15
real(c_double), private module_mp_morr_two_moment::cons15 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons16
real(c_double), private module_mp_morr_two_moment::cons16 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons17
real(c_double), private module_mp_morr_two_moment::cons17 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons18
real(c_double), private module_mp_morr_two_moment::cons18 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons19
real(c_double), private module_mp_morr_two_moment::cons19 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons2
real(c_double), private module_mp_morr_two_moment::cons2 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons20
real(c_double), private module_mp_morr_two_moment::cons20 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons21
real(c_double), private module_mp_morr_two_moment::cons21 private
      REAL(C_DOUBLE), PRIVATE :: CONS21,CONS22,CONS23,CONS24,CONS25,CONS26,CONS27,CONS28,CONS29,CONS30
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons22
real(c_double), private module_mp_morr_two_moment::cons22 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons23
real(c_double), private module_mp_morr_two_moment::cons23 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons24
real(c_double), private module_mp_morr_two_moment::cons24 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons25
real(c_double), private module_mp_morr_two_moment::cons25 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons26
real(c_double), private module_mp_morr_two_moment::cons26 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons27
real(c_double), private module_mp_morr_two_moment::cons27 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons28
real(c_double), private module_mp_morr_two_moment::cons28 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons29
real(c_double), private module_mp_morr_two_moment::cons29 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons3
real(c_double), private module_mp_morr_two_moment::cons3 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons30
real(c_double), private module_mp_morr_two_moment::cons30 private
Referenced by morr_two_moment_init().
cons31
real(c_double), private module_mp_morr_two_moment::cons31 private
      REAL(C_DOUBLE), PRIVATE :: CONS31,CONS32,CONS33,CONS34,CONS35,CONS36,CONS37,CONS38,CONS39,CONS40
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons32
real(c_double), private module_mp_morr_two_moment::cons32 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons33
real(c_double), private module_mp_morr_two_moment::cons33 private
Referenced by morr_two_moment_init().
cons34
real(c_double), private module_mp_morr_two_moment::cons34 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons35
real(c_double), private module_mp_morr_two_moment::cons35 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons36
real(c_double), private module_mp_morr_two_moment::cons36 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons37
real(c_double), private module_mp_morr_two_moment::cons37 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons38
real(c_double), private module_mp_morr_two_moment::cons38 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons39
real(c_double), private module_mp_morr_two_moment::cons39 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons4
real(c_double), private module_mp_morr_two_moment::cons4 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons40
real(c_double), private module_mp_morr_two_moment::cons40 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons41
real(c_double), private module_mp_morr_two_moment::cons41 private
      REAL(C_DOUBLE), PRIVATE :: CONS41
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons5
real(c_double), private module_mp_morr_two_moment::cons5 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons6
real(c_double), private module_mp_morr_two_moment::cons6 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons7
real(c_double), private module_mp_morr_two_moment::cons7 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons8
real(c_double), private module_mp_morr_two_moment::cons8 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cons9
real(c_double), private module_mp_morr_two_moment::cons9 private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cpw
real(c_double), private module_mp_morr_two_moment::cpw private
      REAL(C_DOUBLE), PRIVATE ::      CPW     ! SPECIFIC HEAT OF LIQUID WATER
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
cs
real(c_double), private module_mp_morr_two_moment::cs private
Referenced by morr_two_moment_init(), and ERF::WriteSubvolume().
dcs
real(c_double), private module_mp_morr_two_moment::dcs private
      REAL(C_DOUBLE), PRIVATE ::      DCS         ! THRESHOLD SIZE FOR CLOUD ICE AUTOCONVERSION
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
dg
real(c_double), private module_mp_morr_two_moment::dg private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
di
real(c_double), private module_mp_morr_two_moment::di private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
ds
real(c_double), private module_mp_morr_two_moment::ds private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
eci
real(c_double), private module_mp_morr_two_moment::eci private
      REAL(C_DOUBLE), PRIVATE ::      ECI         ! COLLECTION EFFICIENCY, ICE-DROPLET COLLISIONS
Referenced by morr_two_moment_init().
ecr
real(c_double), private module_mp_morr_two_moment::ecr private
      REAL(C_DOUBLE), PRIVATE ::      ECR         ! COLLECTION EFFICIENCY BETWEEN DROPLETS/RAIN AND SNOW/RAIN
Referenced by morr_two_moment_init().
eii
real(c_double), private module_mp_morr_two_moment::eii private
      REAL(C_DOUBLE), PRIVATE ::      EII         ! COLLECTION EFFICIENCY, ICE-ICE COLLISIONS
Referenced by morr_two_moment_init().
epsm
real(c_double), private module_mp_morr_two_moment::epsm private
      REAL(C_DOUBLE), PRIVATE ::      EPSM    ! AEROSOL SOLUBLE FRACTION
Referenced by morr_two_moment_init().
f11
real(c_double), private module_mp_morr_two_moment::f11 private
      REAL(C_DOUBLE), PRIVATE ::      F11     ! CORRECTION FACTOR FOR ACTIVATION, MODE 1
Referenced by morr_two_moment_init().
f12
real(c_double), private module_mp_morr_two_moment::f12 private
      REAL(C_DOUBLE), PRIVATE ::      F12     ! CORRECTION FACTOR FOR ACTIVATION, MODE 1
Referenced by morr_two_moment_init().
f1r
real(c_double), private module_mp_morr_two_moment::f1r private
      REAL(C_DOUBLE), PRIVATE ::      F1R         ! VENTILATION PARAMETER FOR RAIN
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
f1s
real(c_double), private module_mp_morr_two_moment::f1s private
      REAL(C_DOUBLE), PRIVATE ::      F1S         ! VENTILATION PARAMETER FOR SNOW
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
f21
real(c_double), private module_mp_morr_two_moment::f21 private
      REAL(C_DOUBLE), PRIVATE ::      F21     ! CORRECTION FACTOR FOR ACTIVATION, MODE 2
Referenced by morr_two_moment_init().
f22
real(c_double), private module_mp_morr_two_moment::f22 private
      REAL(C_DOUBLE), PRIVATE ::      F22     ! CORRECTION FACTOR FOR ACTIVATION, MODE 2
Referenced by morr_two_moment_init().
f2r
real(c_double), private module_mp_morr_two_moment::f2r private
      REAL(C_DOUBLE), PRIVATE ::      F2R         ! VENTILATION PARAMETER FOR RAIN
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
f2s
real(c_double), private module_mp_morr_two_moment::f2s private
      REAL(C_DOUBLE), PRIVATE ::      F2S         ! VENTILATION PARAMETER FOR SNOW
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
iact
integer, private module_mp_morr_two_moment::iact private
      INTEGER, PRIVATE ::  IACT
Referenced by morr_two_moment_init(), morr_two_moment_micro(), and mp_morr_two_moment().
ibase
integer, private module_mp_morr_two_moment::ibase private
      INTEGER, PRIVATE ::  IBASE
Referenced by morr_two_moment_init().
igraup
integer, private module_mp_morr_two_moment::igraup private
      INTEGER, PRIVATE ::  IGRAUP
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
ihail
integer, private module_mp_morr_two_moment::ihail private
      INTEGER, PRIVATE ::  IHAIL
Referenced by morr_two_moment_init().
iliq
integer, private module_mp_morr_two_moment::iliq private
      INTEGER, PRIVATE ::  ILIQ
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
inuc
integer, private module_mp_morr_two_moment::inuc private
      INTEGER, PRIVATE ::  INUC
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
inum
integer, private module_mp_morr_two_moment::inum private
      INTEGER, PRIVATE ::  INUM
Referenced by morr_two_moment_init().
isub
integer, private module_mp_morr_two_moment::isub private
      INTEGER, PRIVATE ::  ISUB
Referenced by morr_two_moment_init().
k1
real(c_double), private module_mp_morr_two_moment::k1 private
      REAL(C_DOUBLE), PRIVATE ::      K1     ! 'K' IN NCCN = CS^K
Referenced by morr_two_moment_init(), TerrainIF::operator()(), and writeNCPlotFile().
lammaxg
real(c_double), private module_mp_morr_two_moment::lammaxg private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lammaxi
real(c_double), private module_mp_morr_two_moment::lammaxi private
      REAL(C_DOUBLE), PRIVATE ::      LAMMAXI,LAMMINI,LAMMAXR,LAMMINR,LAMMAXS,LAMMINS,LAMMAXG,LAMMING
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lammaxr
real(c_double), private module_mp_morr_two_moment::lammaxr private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lammaxs
real(c_double), private module_mp_morr_two_moment::lammaxs private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lamming
real(c_double), private module_mp_morr_two_moment::lamming private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lammini
real(c_double), private module_mp_morr_two_moment::lammini private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lamminr
real(c_double), private module_mp_morr_two_moment::lamminr private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
lammins
real(c_double), private module_mp_morr_two_moment::lammins private
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
ma
real(c_double), private module_mp_morr_two_moment::ma private
      REAL(C_DOUBLE), PRIVATE ::      MA      ! MOLECULAR WEIGHT OF 'AIR' (KG/MOL)
Referenced by morr_two_moment_init(), and reduce_to_max_per_height().
map
real(c_double), private module_mp_morr_two_moment::map private
      REAL(C_DOUBLE), PRIVATE ::      MAP     ! MOLECULAR WEIGHT AEROSOL (KG/MOL)
Referenced by morr_two_moment_init().
mg0
real(c_double), private module_mp_morr_two_moment::mg0 private
      REAL(C_DOUBLE), PRIVATE ::      MG0         ! MASS OF EMBRYO GRAUPEL
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
mi0
real(c_double), private module_mp_morr_two_moment::mi0 private
      REAL(C_DOUBLE), PRIVATE ::      MI0         ! INITIAL SIZE OF NUCLEATED CRYSTAL
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
mmult
real(c_double), private module_mp_morr_two_moment::mmult private
      REAL(C_DOUBLE), PRIVATE ::      MMULT   ! MASS OF SPLINTERED ICE PARTICLE
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
mw
real(c_double), private module_mp_morr_two_moment::mw private
      REAL(C_DOUBLE), PRIVATE ::      MW      ! MOLECULAR WEIGHT WATER (KG/MOL)
Referenced by morr_two_moment_init().
nanew1
real(c_double), private module_mp_morr_two_moment::nanew1 private
      REAL(C_DOUBLE), PRIVATE ::      NANEW1  ! TOTAL AEROSOL CONCENTRATION, MODE 1 (M^-3)
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
nanew2
real(c_double), private module_mp_morr_two_moment::nanew2 private
      REAL(C_DOUBLE), PRIVATE ::      NANEW2  ! TOTAL AEROSOL CONCENTRATION, MODE 2 (M^-3)
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
ndcnst
real(c_double), private module_mp_morr_two_moment::ndcnst private
      REAL(C_DOUBLE), PRIVATE ::      NDCNST
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
osm
real(c_double), private module_mp_morr_two_moment::osm private
      REAL(C_DOUBLE), PRIVATE ::      OSM     ! OSMOTIC COEFFICIENT
Referenced by morr_two_moment_init().
pi
real(c_double), parameter, private module_mp_morr_two_moment::pi = 3.1415926535897932384626434 private
    REAL(C_DOUBLE), PARAMETER :: PI = 3.1415926535897932384626434
Referenced by ERF::erf_enforce_hse(), gamma(), morr_two_moment_init(), morr_two_moment_micro(), eb_::EBToPVD::reorder_polygon(), and wrf_gamma().
qsmall
real(c_double), private module_mp_morr_two_moment::qsmall private
      REAL(C_DOUBLE), PRIVATE ::      QSMALL      ! SMALLEST ALLOWED HYDROMETEOR MIXING RATIO
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
rhoa
real(c_double), private module_mp_morr_two_moment::rhoa private
      REAL(C_DOUBLE), PRIVATE ::      RHOA    ! AEROSOL BULK DENSITY (KG/M3)
Referenced by morr_two_moment_init().
rhog
real(c_double), private module_mp_morr_two_moment::rhog private
      REAL(C_DOUBLE), PRIVATE ::      RHOG        ! BULK DENSITY OF GRAUPEL
rhoi
real(c_double), private module_mp_morr_two_moment::rhoi private
      REAL(C_DOUBLE), PRIVATE ::      RHOI        ! BULK DENSITY OF CLOUD ICE
Referenced by morr_two_moment_init().
rhosn
real(c_double), private module_mp_morr_two_moment::rhosn private
      REAL(C_DOUBLE), PRIVATE ::      RHOSN       ! BULK DENSITY OF SNOW
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
rhosu
real(c_double), private module_mp_morr_two_moment::rhosu private
      REAL(C_DOUBLE), PRIVATE ::      RHOSU       ! STANDARD AIR DENSITY AT 850 MB
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
rhow
real(c_double), private module_mp_morr_two_moment::rhow private
      REAL(C_DOUBLE), PRIVATE ::      RHOW        ! DENSITY OF LIQUID WATER
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
rin
real(c_double), private module_mp_morr_two_moment::rin private
      REAL(C_DOUBLE), PRIVATE ::      RIN     ! RADIUS OF CONTACT NUCLEI (M)
Referenced by morr_two_moment_init(), and morr_two_moment_micro().
rm1
real(c_double), private module_mp_morr_two_moment::rm1 private
      REAL(C_DOUBLE), PRIVATE ::      RM1     ! GEOMETRIC MEAN RADIUS, MODE 1 (M)
Referenced by morr_two_moment_init().
rm2
real(c_double), private module_mp_morr_two_moment::rm2 private
      REAL(C_DOUBLE), PRIVATE ::      RM2     ! GEOMETRIC MEAN RADIUS, MODE 2 (M)
Referenced by morr_two_moment_init().
rr
real(c_double), private module_mp_morr_two_moment::rr private
      REAL(C_DOUBLE), PRIVATE ::      RR      ! UNIVERSAL GAS CONSTANT
Referenced by ERF::ErrorEst(), init_zlevels(), morr_two_moment_init(), ERF::WriteMultiLevelPlotfileWithTerrain(), and ERF::WritePlotFile().
sig1
real(c_double), private module_mp_morr_two_moment::sig1 private
      REAL(C_DOUBLE), PRIVATE ::      SIG1    ! STANDARD DEVIATION OF AEROSOL S.D., MODE 1
Referenced by morr_two_moment_init().
sig2
real(c_double), private module_mp_morr_two_moment::sig2 private
      REAL(C_DOUBLE), PRIVATE ::      SIG2    ! STANDARD DEVIATION OF AEROSOL S.D., MODE 2
Referenced by morr_two_moment_init().
vi
real(c_double), private module_mp_morr_two_moment::vi private
      REAL(C_DOUBLE), PRIVATE ::      VI      ! NUMBER OF ION DISSOCIATED IN SOLUTION
Referenced by morr_two_moment_init().
xxx
real(c_double), parameter, private module_mp_morr_two_moment::xxx = 0.9189385332046727417803297 private
    REAL(C_DOUBLE), PARAMETER :: xxx = 0.9189385332046727417803297