ERF: module_model_constants Module Reference
module_model_constants Module Reference
Functions/Subroutines
subroutine init_module_model_constants
Variables
real(c_double), parameter epsilon = 1.E-15
real(c_double), parameter g = 9.81
real(c_double), parameter r_d = 287.
real(c_double), parameter cp = 7.*r_d/2.
real(c_double), parameter r_v = 461.6
real(c_double), parameter cv = cp-r_d
real(c_double), parameter cpv = 4.*r_v
real(c_double), parameter cvv = cpv-r_v
real(c_double), parameter cvpm = -cv/cp
real(c_double), parameter cliq = 4190.
real(c_double), parameter cice = 2106.
real(c_double), parameter psat = 610.78
real(c_double), parameter rcv = r_d/cv
real(c_double), parameter rcp = r_d/cp
real(c_double), parameter rovg = r_d/g
real(c_double), parameter c2 = cp * rcv
real, parameter mwdry = 28.966
real(c_double), parameter p1000mb = 100000.
real(c_double), parameter t0 = 300.
real(c_double), parameter p0 = p1000mb
real(c_double), parameter cpovcv = cp/(cp-r_d)
real(c_double), parameter cvovcp = 1./cpovcv
real(c_double), parameter rvovrd = r_v/r_d
real(c_double), parameter reradius = 1./6370.0e03
real(c_double), parameter asselin = .025
real(c_double), parameter cb = 25.
real(c_double), parameter xlv0 = 3.15E6
real(c_double), parameter xlv1 = 2370.
real(c_double), parameter xls0 = 2.905E6
real(c_double), parameter xls1 = 259.532
real(c_double), parameter xls = 2.85E6
real(c_double), parameter xlv = 2.5E6
real(c_double), parameter xlf = 3.50E5
real(c_double), parameter rhowater = 1000.
real(c_double), parameter rhosnow = 100.
real(c_double), parameter rhoair0 = 1.28
real(c_double), parameter re_qc_bg = 2.49E-6
real(c_double), parameter re_qi_bg = 4.99E-6
real(c_double), parameter re_qs_bg = 9.99E-6
real(c_double), parameter re_qc_max = 50.E-6
real(c_double), parameter re_qi_max = 125.E-6
real(c_double), parameter re_qs_max = 999.E-6
real(c_double), parameter piconst = 3.1415926535897932384626433
real(c_double), parameter degrad = piconst/180.
real(c_double), parameter dpd = 360./365.
real(c_double), parameter svp1 =0.6112
real(c_double), parameter svp2 =17.67
real(c_double), parameter svp3 =29.65
real(c_double), parameter svpt0 =273.15
real(c_double), parameter ep_1 =R_v/R_d-1.
real(c_double), parameter ep_2 =R_d/R_v
real(c_double), parameter karman =0.4
real(c_double), parameter eomeg =7.2921E-5
real(c_double), parameter stbolt =5.67051E-8
real(c_double), parameter prandtl = 1./3.0
real(c_double), parameter w_alpha = 0.3
real(c_double), parameter w_beta = 1.0
real(c_double), parameter pq0 =379.90516
real(c_double), parameter epsq2 =0.2
real(c_double), parameter a2 =17.2693882
real(c_double), parameter a3 =273.16
real(c_double), parameter a4 =35.86
real(c_double), parameter epsq =1.e-12
real(c_double), parameter p608 =rvovrd-1.
real(c_double), parameter climit =1.e-20
real(c_double), parameter cm1 =2937.4
real(c_double), parameter cm2 =4.9283
real(c_double), parameter cm3 =23.5518
real(c_double), parameter defc =0.0
real(c_double), parameter defm =99999.0
real(c_double), parameter epsfc =1./1.05
real(c_double), parameter epswet =0.0
real(c_double), parameter fcdif =1./3.
real(c_double), parameter fcm =0.00003
real(c_double), parameter gma =-r_d*(1.-rcp)*0.5
real(c_double), parameter p400 =40000.0
real(c_double), parameter phitp =15000.0
real(c_double), parameter pi2 =2.*3.1415926
real(c_double), parameter pi1 =3.1415926
real(c_double), parameter plbtm =105000.0
real(c_double), parameter plomd =64200.0
real(c_double), parameter pmdhi =35000.0
real(c_double), parameter q2ini =0.50
real(c_double), parameter rfcp =0.25/cp
real(c_double), parameter rhcrit_land =0.75
real(c_double), parameter rhcrit_sea =0.80
real(c_double), parameter rlag =14.8125
real(c_double), parameter rlx =0.90
real(c_double), parameter scq2 =50.0
real(c_double), parameter slopht =0.001
real(c_double), parameter tlc =2.*0.703972477
real(c_double), parameter wa =0.15
real(c_double), parameter wght =0.35
real(c_double), parameter wpc =0.075
real(c_double), parameter z0land =0.10
real(c_double), parameter z0max =0.008
real(c_double), parameter z0sea =0.001
integer, parameter planet_year = 365
real(c_double), parameter obliquity = 23.5
real(c_double), parameter eccentricity = 0.014
real(c_double), parameter semimajoraxis = 1.0
real(c_double), parameter zero_date = 0.0
real(c_double), parameter equinox_fraction = 0.0
integer, parameter zone_solve_em = 1
integer, parameter zone_sfs = 2
Function/Subroutine Documentation
init_module_model_constants()
subroutine module_model_constants::init_module_model_constants
Variable Documentation
a2
real(c_double), parameter module_model_constants::a2 =17.2693882
        REAL(C_DOUBLE) , PARAMETER ::  a2=17.2693882
Referenced by calc_saturation_vapor_pressure(), erf_dtesati(), erf_dtesatw(), erf_esati(), erf_esatw(), WENO_MZQ3::Evaluate(), CENTERED4::Evaluate(), UPWIND3::Evaluate(), CENTERED6::Evaluate(), UPWIND5::Evaluate(), and UPWINDALL::Evaluate().
a3
real(c_double), parameter module_model_constants::a3 =273.16
        REAL(C_DOUBLE) , PARAMETER ::  a3=273.16
Referenced by calc_saturation_vapor_pressure(), erf_dtesati(), erf_dtesatw(), erf_esati(), erf_esatw(), WENO_MZQ3::Evaluate(), CENTERED6::Evaluate(), UPWIND5::Evaluate(), and UPWINDALL::Evaluate().
a4
real(c_double), parameter module_model_constants::a4 =35.86
        REAL(C_DOUBLE) , PARAMETER ::  a4=35.86
Referenced by calc_saturation_vapor_pressure(), erf_dtesati(), erf_dtesatw(), erf_esati(), and erf_esatw().
asselin
real(c_double), parameter module_model_constants::asselin = .025
    REAL(C_DOUBLE)    , PARAMETER :: asselin      = .025
c2
real(c_double), parameter module_model_constants::c2 = cp * rcv
    REAL(C_DOUBLE)    , PARAMETER :: c2           = cp * rcv
Referenced by SatMethods::Bolton_svp_water(), ComputeStrain_S(), ComputeStrain_T(), DiffusionSrcForState_S(), DiffusionSrcForState_T(), and WaterVaporSat::findsp().
cb
real(c_double), parameter module_model_constants::cb = 25.
    REAL(C_DOUBLE)    , PARAMETER :: cb           = 25.
cice
real(c_double), parameter module_model_constants::cice = 2106.
    REAL(C_DOUBLE)    , PARAMETER :: cice         = 2106.      ! specific heat of ice at 0^oC
climit
real(c_double), parameter module_model_constants::climit =1.e-20
        REAL(C_DOUBLE) , PARAMETER ::  climit=1.e-20
cliq
real(c_double), parameter module_model_constants::cliq = 4190.
    REAL(C_DOUBLE)    , PARAMETER :: cliq         = 4190.      ! specific heat of liquid water at 0^oC
cm1
real(c_double), parameter module_model_constants::cm1 =2937.4
        REAL(C_DOUBLE) , PARAMETER ::  cm1=2937.4
cm2
real(c_double), parameter module_model_constants::cm2 =4.9283
        REAL(C_DOUBLE) , PARAMETER ::  cm2=4.9283
cm3
real(c_double), parameter module_model_constants::cm3 =23.5518
        REAL(C_DOUBLE) , PARAMETER ::  cm3=23.5518
cp
real(c_double), parameter module_model_constants::cp = 7.*r_d/2.
    REAL(C_DOUBLE)    , PARAMETER :: cp           = 7.*r_d/2.  !
Referenced by TurbulentPerturbation::calc_tpi_amp(), and module_mp_morr_two_moment::morr_two_moment_micro().
cpovcv
real(c_double), parameter module_model_constants::cpovcv = cp/(cp-r_d)
    REAL(C_DOUBLE)    , PARAMETER :: cpovcv       = cp/(cp-r_d)
cpv
real(c_double), parameter module_model_constants::cpv = 4.*r_v
    REAL(C_DOUBLE)    , PARAMETER :: cpv          = 4.*r_v
cv
real(c_double), parameter module_model_constants::cv = cp-r_d
    REAL(C_DOUBLE)    , PARAMETER :: cv           = cp-r_d     ! Specific heat of air at contant volume (J deg^-1 kg^-1)
cvovcp
real(c_double), parameter module_model_constants::cvovcp = 1./cpovcv
    REAL(C_DOUBLE)    , PARAMETER :: cvovcp       = 1./cpovcv
cvpm
real(c_double), parameter module_model_constants::cvpm = -cv/cp
    REAL(C_DOUBLE)    , PARAMETER :: cvpm         = -cv/cp
cvv
real(c_double), parameter module_model_constants::cvv = cpv-r_v
    REAL(C_DOUBLE)    , PARAMETER :: cvv          = cpv-r_v    !
defc
real(c_double), parameter module_model_constants::defc =0.0
        REAL(C_DOUBLE) , PARAMETER ::  defc=0.0
defm
real(c_double), parameter module_model_constants::defm =99999.0
        REAL(C_DOUBLE) , PARAMETER ::  defm=99999.0
degrad
real(c_double), parameter module_model_constants::degrad = piconst/180.
    REAL(C_DOUBLE)    , PARAMETER :: DEGRAD       = piconst/180.                   ! radians per degree
Referenced by orbital_params().
dpd
real(c_double), parameter module_model_constants::dpd = 360./365.
    REAL(C_DOUBLE)    , PARAMETER :: DPD          = 360./365.
eccentricity
real(c_double), parameter module_model_constants::eccentricity = 0.014
    REAL(C_DOUBLE) , PARAMETER :: ECCENTRICITY = 0.014   ! Orbital eccentricity
eomeg
real(c_double), parameter module_model_constants::eomeg =7.2921E-5
    REAL(C_DOUBLE)    , PARAMETER ::  EOMEG=7.2921e-5          ! angular velocity of rotation (rad^-1)
ep_1
real(c_double), parameter module_model_constants::ep_1 =R_v/R_d-1.
    REAL(C_DOUBLE)    , PARAMETER ::  EP_1=r_v/r_d-1.  !  constant for virtual temperature (r_v/r_d - 1) (dimensionless)
ep_2
real(c_double), parameter module_model_constants::ep_2 =R_d/R_v
    REAL(C_DOUBLE)    , PARAMETER ::  EP_2=r_d/r_v     ! constant for specific humidity calculation (dimensionless)
Referenced by module_mp_morr_two_moment::morr_two_moment_micro().
epsfc
real(c_double), parameter module_model_constants::epsfc =1./1.05
        REAL(C_DOUBLE) , PARAMETER ::  epsfc=1./1.05
epsilon
real(c_double), parameter module_model_constants::epsilon = 1.E-15
    REAL(C_DOUBLE)    , PARAMETER :: epsilon         = 1.e-15
Referenced by Kessler::AdvanceKessler(), eb_::EBToPVD::calc_alpha(), TurbulentPerturbation::calc_tpi_meanMag_perBox(), ComputeDiffusivityMYNN25(), ComputeDiffusivityMYNNEDMF(), ComputeTurbulentViscosityLES(), ComputeTurbulentViscosityRANS(), eb_aux_::define(), erf_slow_rhs_post(), ERFFillPatcher::Fill(), get_dzmin_terrain(), SAM::IceFall(), ERF::init_immersed_forcing(), init_which_terrain_grid(), utils::intersect_plane_edge(), make_mom_sources(), make_sources(), SAM::Precip(), SAM::PrecipFall(), and SurfaceLayer::SurfaceLayer().
epsq
real(c_double), parameter module_model_constants::epsq =1.e-12
        REAL(C_DOUBLE) , PARAMETER ::  epsq=1.e-12      ! threshold specified for SPECIFIC HUMIDITY calculation in BMJ cumulus scheme (kg kg^-1)
epsq2
real(c_double), parameter module_model_constants::epsq2 =0.2
        REAL(C_DOUBLE) , PARAMETER ::  epsq2=0.2         ! initial TKE for camuw PBL scheme (m2 s^-2)
epswet
real(c_double), parameter module_model_constants::epswet =0.0
        REAL(C_DOUBLE) , PARAMETER ::  epswet=0.0
equinox_fraction
real(c_double), parameter module_model_constants::equinox_fraction = 0.0
    REAL(C_DOUBLE) , PARAMETER :: EQUINOX_FRACTION= 0.0  ! Fraction into the year (from perhelion) of the occurrence of the Northern Spring Equinox
fcdif
real(c_double), parameter module_model_constants::fcdif =1./3.
        REAL(C_DOUBLE) , PARAMETER ::  fcdif=1./3.
fcm
real(c_double), parameter module_model_constants::fcm =0.00003
        REAL(C_DOUBLE) , PARAMETER ::  fcm=0.00003
g
real(c_double), parameter module_model_constants::g = 9.81
    REAL(C_DOUBLE)    , PARAMETER :: g = 9.81  ! acceleration due to gravity (m {s}^-2)
Referenced by TurbulentPerturbation::calc_tpi_amp(), WaterVaporSat::findsp(), module_mp_morr_two_moment::morr_two_moment_micro(), HSEutils::Newton_Raphson_hse(), and ERF::Write3DPlotFile().
gma
real(c_double), parameter module_model_constants::gma =-r_d*(1.-rcp)*0.5
        REAL(C_DOUBLE) , PARAMETER ::  gma=-r_d*(1.-rcp)*0.5
karman
real(c_double), parameter module_model_constants::karman =0.4
    REAL(C_DOUBLE)    , PARAMETER ::  KARMAN=0.4               ! von Karman constant
mwdry
real, parameter module_model_constants::mwdry = 28.966
    real    , parameter :: mwdry        = 28.966     ! molecular weight of dry air (g/mole)
obliquity
real(c_double), parameter module_model_constants::obliquity = 23.5
    REAL(C_DOUBLE) , PARAMETER :: OBLIQUITY = 23.5       ! solar obliquity (degree)
p0
real(c_double), parameter module_model_constants::p0 = p1000mb
    REAL(C_DOUBLE)    , PARAMETER :: p0           = p1000mb    ! base state surface pressure (pa)
Referenced by Morrison::Advance(), ERF::advance_dycore(), ERF::derive_diag_profiles_stag(), make_buoyancy(), make_gradp_pert(), and quad_interp_1d().
p1000mb
real(c_double), parameter module_model_constants::p1000mb = 100000.
    REAL(C_DOUBLE)    , PARAMETER :: p1000mb      = 100000.    ! pressure at 1000 hPa (pa)
p400
real(c_double), parameter module_model_constants::p400 =40000.0
        REAL(C_DOUBLE) , PARAMETER ::  p400=40000.0
p608
real(c_double), parameter module_model_constants::p608 =rvovrd-1.
        REAL(C_DOUBLE) , PARAMETER ::  p608=rvovrd-1.
phitp
real(c_double), parameter module_model_constants::phitp =15000.0
        REAL(C_DOUBLE) , PARAMETER ::  phitp=15000.0
pi1
real(c_double), parameter module_model_constants::pi1 =3.1415926
pi2
real(c_double), parameter module_model_constants::pi2 =2.*3.1415926
        REAL(C_DOUBLE) , PARAMETER ::  pi2=2.*3.1415926, pi1=3.1415926
piconst
real(c_double), parameter module_model_constants::piconst = 3.1415926535897932384626433
    REAL(C_DOUBLE)    , PARAMETER :: piconst      = 3.1415926535897932384626433    ! constant of PI
planet_year
integer, parameter module_model_constants::planet_year = 365
    INTEGER , PARAMETER :: PLANET_YEAR = 365   ! number of days in a calendar year
plbtm
real(c_double), parameter module_model_constants::plbtm =105000.0
        REAL(C_DOUBLE) , PARAMETER ::  plbtm=105000.0
plomd
real(c_double), parameter module_model_constants::plomd =64200.0
        REAL(C_DOUBLE) , PARAMETER ::  plomd=64200.0
pmdhi
real(c_double), parameter module_model_constants::pmdhi =35000.0
        REAL(C_DOUBLE) , PARAMETER ::  pmdhi=35000.0
pq0
real(c_double), parameter module_model_constants::pq0 =379.90516
        REAL(C_DOUBLE) , PARAMETER ::  pq0=379.90516     !
prandtl
real(c_double), parameter module_model_constants::prandtl = 1./3.0
    REAL(C_DOUBLE)    , PARAMETER ::  prandtl = 1./3.0   ! prandtl's mixing length (m)
Referenced by ComputeDiffusivityYSU().
psat
real(c_double), parameter module_model_constants::psat = 610.78
    REAL(C_DOUBLE)    , PARAMETER :: psat         = 610.78
q2ini
real(c_double), parameter module_model_constants::q2ini =0.50
        REAL(C_DOUBLE) , PARAMETER ::  q2ini=0.50
r_d
real(c_double), parameter module_model_constants::r_d = 287.
    REAL(C_DOUBLE)    , PARAMETER :: r_d          = 287.       ! gas constant of dry air (J deg^-1 kg^-1)
r_v
real(c_double), parameter module_model_constants::r_v = 461.6
    REAL(C_DOUBLE)    , PARAMETER :: r_v          = 461.6      ! gas constant for water vapor (J deg^-1 kg^-1)
rcp
real(c_double), parameter module_model_constants::rcp = r_d/cp
    REAL(C_DOUBLE)    , PARAMETER :: rcp          = r_d/cp
rcv
real(c_double), parameter module_model_constants::rcv = r_d/cv
    REAL(C_DOUBLE)    , PARAMETER :: rcv          = r_d/cv     !
re_qc_bg
real(c_double), parameter module_model_constants::re_qc_bg = 2.49E-6
    REAL(C_DOUBLE)    , PARAMETER :: RE_QC_BG     = 2.49e-6     ! effective radius of cloud for background (m)
re_qc_max
real(c_double), parameter module_model_constants::re_qc_max = 50.E-6
    REAL(C_DOUBLE)    , PARAMETER :: RE_QC_MAX    =  50.e-6     ! max effective radius of cloud allowed
re_qi_bg
real(c_double), parameter module_model_constants::re_qi_bg = 4.99E-6
    REAL(C_DOUBLE)    , PARAMETER :: RE_QI_BG     = 4.99e-6     ! effective radius of ice for background (m)
re_qi_max
real(c_double), parameter module_model_constants::re_qi_max = 125.E-6
    REAL(C_DOUBLE)    , PARAMETER :: RE_QI_MAX    = 125.e-6     ! max effective radius of ice allowed
re_qs_bg
real(c_double), parameter module_model_constants::re_qs_bg = 9.99E-6
    REAL(C_DOUBLE)    , PARAMETER :: RE_QS_BG     = 9.99e-6     ! effective radius of snow for background (m)
re_qs_max
real(c_double), parameter module_model_constants::re_qs_max = 999.E-6
    REAL(C_DOUBLE)    , PARAMETER :: RE_QS_MAX    = 999.e-6     ! max effective radius of snow allowed
reradius
real(c_double), parameter module_model_constants::reradius = 1./6370.0e03
    REAL(C_DOUBLE)    , PARAMETER :: reradius     = 1./6370.0e03  ! reciprocal of earth radius (m^-1)
rfcp
real(c_double), parameter module_model_constants::rfcp =0.25/cp
        REAL(C_DOUBLE) , PARAMETER ::  rfcp=0.25/cp
rhcrit_land
real(c_double), parameter module_model_constants::rhcrit_land =0.75
        REAL(C_DOUBLE) , PARAMETER ::  rhcrit_land=0.75
rhcrit_sea
real(c_double), parameter module_model_constants::rhcrit_sea =0.80
        REAL(C_DOUBLE) , PARAMETER ::  rhcrit_sea=0.80
rhoair0
real(c_double), parameter module_model_constants::rhoair0 = 1.28
    REAL(C_DOUBLE)    , PARAMETER :: rhoair0      = 1.28        ! density of dry air at 0^oC and 1000mb pressure (kg m^-3)
rhosnow
real(c_double), parameter module_model_constants::rhosnow = 100.
    REAL(C_DOUBLE)    , PARAMETER :: rhosnow      = 100.        ! density of snow (kg m^-3)
rhowater
real(c_double), parameter module_model_constants::rhowater = 1000.
    REAL(C_DOUBLE)    , PARAMETER :: rhowater     = 1000.       ! density of liquid water at 0^oC (kg m^-3)
rlag
real(c_double), parameter module_model_constants::rlag =14.8125
        REAL(C_DOUBLE) , PARAMETER ::  rlag=14.8125
rlx
real(c_double), parameter module_model_constants::rlx =0.90
        REAL(C_DOUBLE) , PARAMETER ::  rlx=0.90
rovg
real(c_double), parameter module_model_constants::rovg = r_d/g
    REAL(C_DOUBLE)    , PARAMETER :: rovg         = r_d/g
rvovrd
real(c_double), parameter module_model_constants::rvovrd = r_v/r_d
    REAL(C_DOUBLE)    , PARAMETER :: rvovrd       = r_v/r_d
scq2
real(c_double), parameter module_model_constants::scq2 =50.0
        REAL(C_DOUBLE) , PARAMETER ::  scq2=50.0
semimajoraxis
real(c_double), parameter module_model_constants::semimajoraxis = 1.0
    REAL(C_DOUBLE) , PARAMETER :: SEMIMAJORAXIS = 1.0    ! Ratio of semi-major axis of planet / semi-major axis of earth
slopht
real(c_double), parameter module_model_constants::slopht =0.001
        REAL(C_DOUBLE) , PARAMETER ::  slopht=0.001
stbolt
real(c_double), parameter module_model_constants::stbolt =5.67051E-8
    REAL(C_DOUBLE)    , PARAMETER ::  STBOLT=5.67051e-8        ! Stefan-Boltzmann constant (W m^-2 deg^-4)
svp1
real(c_double), parameter module_model_constants::svp1 =0.6112
    REAL(C_DOUBLE)    , PARAMETER ::  SVP1=0.6112      ! constant for saturation vapor pressure calculation (dimensionless)
Referenced by erf_dtesatw_cc(), erf_esatw_cc(), and rh_to_mxrat().
svp2
real(c_double), parameter module_model_constants::svp2 =17.67
    REAL(C_DOUBLE)    , PARAMETER ::  SVP2=17.67       ! constant for saturation vapor pressure calculation (dimensionless)
Referenced by erf_dtesatw_cc(), erf_esatw_cc(), and rh_to_mxrat().
svp3
real(c_double), parameter module_model_constants::svp3 =29.65
    REAL(C_DOUBLE)    , PARAMETER ::  SVP3=29.65       ! constant for saturation vapor pressure calculation (K)
Referenced by erf_dtesatw_cc(), erf_esatw_cc(), and rh_to_mxrat().
svpt0
real(c_double), parameter module_model_constants::svpt0 =273.15
    REAL(C_DOUBLE)    , PARAMETER ::  SVPT0=273.15     ! constant for saturation vapor pressure calculation (K)
Referenced by erf_dtesatw_cc(), erf_esatw_cc(), and rh_to_mxrat().
t0
real(c_double), parameter module_model_constants::t0 = 300.
    REAL(C_DOUBLE)    , PARAMETER :: t0           = 300.       ! base state tempertaure (K)
tlc
real(c_double), parameter module_model_constants::tlc =2.*0.703972477
        REAL(C_DOUBLE) , PARAMETER ::  tlc=2.*0.703972477
w_alpha
real(c_double), parameter module_model_constants::w_alpha = 0.3
    REAL(C_DOUBLE)    , PARAMETER ::  w_alpha = 0.3      ! strength m/s/s
w_beta
real(c_double), parameter module_model_constants::w_beta = 1.0
    REAL(C_DOUBLE)    , PARAMETER ::  w_beta  = 1.0      ! activation cfl number
wa
real(c_double), parameter module_model_constants::wa =0.15
        REAL(C_DOUBLE) , PARAMETER ::  wa=0.15
wght
real(c_double), parameter module_model_constants::wght =0.35
        REAL(C_DOUBLE) , PARAMETER ::  wght=0.35
wpc
real(c_double), parameter module_model_constants::wpc =0.075
        REAL(C_DOUBLE) , PARAMETER ::  wpc=0.075
xlf
real(c_double), parameter module_model_constants::xlf = 3.50E5
    REAL(C_DOUBLE)    , PARAMETER :: XLF          = 3.50e5      ! latent heat of fusion of water at 0^oC (J kg^-1)
xls
real(c_double), parameter module_model_constants::xls = 2.85E6
    REAL(C_DOUBLE)    , PARAMETER :: XLS          = 2.85e6      ! latent heat of sublimation of water at 0^oC (J kg^-1)
xls0
real(c_double), parameter module_model_constants::xls0 = 2.905E6
    REAL(C_DOUBLE)    , PARAMETER :: XLS0         = 2.905e6      !  constant defined for calculation of latent heating
xls1
real(c_double), parameter module_model_constants::xls1 = 259.532
    REAL(C_DOUBLE)    , PARAMETER :: XLS1         = 259.532      !  constant defined for calculation of latent heating
xlv
real(c_double), parameter module_model_constants::xlv = 2.5E6
    REAL(C_DOUBLE)    , PARAMETER :: XLV          = 2.5e6       ! latent heat of vaporization of water at 0^oC (J kg^-1)
xlv0
real(c_double), parameter module_model_constants::xlv0 = 3.15E6
    REAL(C_DOUBLE)    , PARAMETER :: XLV0         = 3.15e6       !  constant defined for calculation of latent heating
xlv1
real(c_double), parameter module_model_constants::xlv1 = 2370.
    REAL(C_DOUBLE)    , PARAMETER :: XLV1         = 2370.        !  constant defined for calculation of latent heating
z0land
real(c_double), parameter module_model_constants::z0land =0.10
        REAL(C_DOUBLE) , PARAMETER ::  z0land=0.10    ! surface roughness length over land (m)
z0max
real(c_double), parameter module_model_constants::z0max =0.008
        REAL(C_DOUBLE) , PARAMETER ::  z0max=0.008    !  maximum roughness length (m)
z0sea
real(c_double), parameter module_model_constants::z0sea =0.001
        REAL(C_DOUBLE) , PARAMETER ::  z0sea=0.001   ! roughness length over ocean (m)
zero_date
real(c_double), parameter module_model_constants::zero_date = 0.0
    REAL(C_DOUBLE) , PARAMETER :: zero_date = 0.0        ! Time of perihelion passage
zone_sfs
integer, parameter module_model_constants::zone_sfs = 2
    INTEGER, PARAMETER :: ZONE_SFS = 2
zone_solve_em
integer, parameter module_model_constants::zone_solve_em = 1
    INTEGER, PARAMETER :: ZONE_SOLVE_EM = 1