ERF: shoc Namespace Reference
shoc Namespace Reference
Namespaces
constants
Classes
struct ShocEnergyFixerView
Enumerations
enum class InitRunOn { Host , Device }
Functions
ShocEnergyFixerView make_energy_fixer_view (ShocColumnData &col)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE int diagnose_active_top (const amrex::Array4< const amrex::Real > &tke, int ic, int nlev) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void apply_energy_fix_column (const ShocEnergyFixerView &v, int ic, double dt_d) noexcept
InitRunOn default_init_run_on ()
void set_fab_val (amrex::FArrayBox &fab, amrex::Real value, InitRunOn)
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real height_agl (amrex::Real z, amrex::Real z_sfc) noexcept
void sync_if_needed ()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real latent_sublimation () noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real condensate_latent_heat (amrex::Real qc, amrex::Real qi) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real theta_from_thetal (amrex::Real thetal, amrex::Real qc, amrex::Real qi, amrex::Real exner) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real temperature_from_thetal (amrex::Real thetal, amrex::Real qc, amrex::Real qi, amrex::Real exner) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real thetal_from_theta (amrex::Real theta, amrex::Real qc, amrex::Real qi, amrex::Real exner) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real moist_energy (amrex::Real tabs, amrex::Real z, amrex::Real qv, amrex::Real qc, amrex::Real qi, amrex::Real u, amrex::Real v, amrex::Real tke) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void reconstruct_pdf_state (amrex::Real thetal, amrex::Real qw, amrex::Real exner, amrex::Real qi_seed, amrex::Real pdf_ql, amrex::Real &tabs, amrex::Real &qv, amrex::Real &qc, amrex::Real &qi) noexcept
Enumeration Type Documentation
InitRunOn
enum shoc::InitRunOn strong
Enumerator
Host
Device
                      {
     Host,
     Device
 };
Function Documentation
apply_energy_fix_column()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void shoc::apply_energy_fix_column (const ShocEnergyFixerView & v, int ic, double dt_d) noexcept
 {
     amrex::Real dt = static_cast<amrex::Real>(dt_d);
     const int shoc_top = diagnose_active_top(v.tke, ic, v.nlev);
     if (shoc_top < 0) {
         return;
     }
     amrex::Real energy_before = amrex::Real(0.0);
     amrex::Real energy_after = amrex::Real(0.0);
     amrex::Real air_mass = amrex::Real(0.0);
     for (int k = 0; k <= shoc_top; ++k) {
         const amrex::Real mass = v.rho(ic,k,0) * v.dz(ic,k,0);
         const amrex::Real tabs_old = shoc::temperature_from_thetal(v.thetal_base(ic,k,0),
                                                                     v.qc_base(ic,k,0),
                                                                     v.qi_base(ic,k,0),
                                                                     v.exner(ic,k,0));
         amrex::Real tabs_new = amrex::Real(0.0);
         amrex::Real qv_new = amrex::Real(0.0);
         amrex::Real qc_new = amrex::Real(0.0);
         amrex::Real qi_new = amrex::Real(0.0);
         shoc::reconstruct_pdf_state(v.thetal(ic,k,0), v.qw(ic,k,0), v.exner(ic,k,0),
                                     v.qi_base(ic,k,0), v.shoc_ql(ic,k,0),
                                     tabs_new, qv_new, qc_new, qi_new);
         energy_before += mass * moist_energy(tabs_old, v.zt(ic,k,0),
                                              v.qv_base(ic,k,0), v.qc_base(ic,k,0), v.qi_base(ic,k,0),
                                              v.u_base(ic,k,0), v.v_base(ic,k,0), v.tke_base(ic,k,0));
         energy_after += mass * moist_energy(tabs_new, v.zt(ic,k,0),
                                             qv_new, qc_new, qi_new,
                                             v.u(ic,k,0), v.v(ic,k,0), v.tke(ic,k,0));
         air_mass += mass;
     }
     if (air_mass <= amrex::Real(0.0)) {
         return;
     }
     const amrex::Real latent_flux_coeff = L_v + constants::latent_ice();
     const amrex::Real energy_target = energy_before
         + dt * v.rho(ic,0,0)
         * (Cp_d * v.exner(ic,0,0) * v.surf_sens_flux(ic,0,0)
            + latent_flux_coeff * v.surf_lat_flux(ic,0,0));
     const amrex::Real delta_tabs = (energy_target - energy_after) / (Cp_d * air_mass);
     for (int k = 0; k <= shoc_top; ++k) {
         v.thetal(ic,k,0) += delta_tabs / amrex::max(v.exner(ic,k,0), amrex::Real(1.0e-12));
     }
 }
Referenced by ShocEnergyFixer::apply_column(), and ShocImplicit::finalize_from_pdf().
condensate_latent_heat()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::condensate_latent_heat (amrex::Real qc, amrex::Real qi) noexcept
 {
     return L_v * amrex::max(amrex::Real(0.0), qc)
          + latent_sublimation() * amrex::max(amrex::Real(0.0), qi);
 }
Referenced by temperature_from_thetal(), theta_from_thetal(), and thetal_from_theta().
default_init_run_on()
InitRunOn shoc::default_init_run_on () inline
 {
 #ifdef AMREX_USE_GPU
     return InitRunOn::Device;
 #else
     return InitRunOn::Host;
 #endif
 }
Referenced by ShocDriver::advance().
diagnose_active_top()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE int shoc::diagnose_active_top (const amrex::Array4< const amrex::Real > & tke, int ic, int nlev) noexcept
 {
     int shoc_top = -1;
     for (int k = nlev - 1; k >= 0; --k) {
         if (tke(ic,k,0) > constants::min_tke()) {
             shoc_top = k;
             break;
         }
     }
     return shoc_top;
 }
Referenced by apply_energy_fix_column(), and ShocEnergyFixer::diagnose_active_top().
height_agl()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::height_agl (amrex::Real z, amrex::Real z_sfc) noexcept
 {
     return amrex::max(amrex::Real(0.0), z - z_sfc);
 }
Referenced by ShocStructure::diagnose_length_and_brunt(), ShocStructure::diagnose_pblh(), ShocStructure::diagnose_surface_layer(), and ShocTKE::diagnose_tke_and_diffusivities().
latent_sublimation()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::latent_sublimation () noexcept
 {
     return L_v + constants::latent_ice();
 }
Referenced by condensate_latent_heat(), and moist_energy().
make_energy_fixer_view()
ShocEnergyFixerView shoc::make_energy_fixer_view (ShocColumnData & col) inline
 {
     return {
         col.rho.const_array(),
         col.dz.const_array(),
         col.zt.const_array(),
         col.exner.const_array(),
         col.surf_sens_flux.const_array(),
         col.surf_lat_flux.const_array(),
         col.thetal_base.const_array(),
         col.qv_base.const_array(),
         col.qc_base.const_array(),
         col.qi_base.const_array(),
         col.u_base.const_array(),
         col.v_base.const_array(),
         col.tke_base_state.const_array(),
         col.thetal.array(),
         col.qw.const_array(),
         col.u.const_array(),
         col.v.const_array(),
         col.tke.const_array(),
         col.shoc_ql.const_array(),
         col.layout.nlev
     };
 }
Referenced by ShocEnergyFixer::apply_column(), and ShocImplicit::finalize_from_pdf().
moist_energy()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::moist_energy (amrex::Real tabs, amrex::Real z, amrex::Real qv, amrex::Real qc, amrex::Real qi, amrex::Real u, amrex::Real v, amrex::Real tke) noexcept
 {
     // Ice-reference moist energy has no explicit qi term; qi is retained in
     // the signature so callers pass a complete vapor/liquid/ice state.
     amrex::ignore_unused(qi);
     return Cp_d * tabs
          + CONST_GRAV * z
          + amrex::Real(0.5) * (u * u + v * v)
          + tke
          + latent_sublimation() * qv
          + constants::latent_ice() * amrex::max(amrex::Real(0.0), qc);
 }
Referenced by apply_energy_fix_column().
reconstruct_pdf_state()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE void shoc::reconstruct_pdf_state (amrex::Real thetal, amrex::Real qw, amrex::Real exner, amrex::Real qi_seed, amrex::Real pdf_ql, amrex::Real & tabs, amrex::Real & qv, amrex::Real & qc, amrex::Real & qi) noexcept
 {
     // Interim native-SHOC contract: preserve any existing ice seed for
     // phase-aware thermodynamics, but do not create or repartition cloud ice.
     const amrex::Real qi_total = shoc_clamp(qi_seed, amrex::Real(0.0), amrex::max(amrex::Real(0.0), qw));
     const amrex::Real ql_total = shoc_clamp(pdf_ql, amrex::Real(0.0), amrex::max(amrex::Real(0.0), qw - qi_total));
     qc = ql_total;
     qi = qi_total;
     tabs = temperature_from_thetal(thetal, qc, qi, exner);
     qv = amrex::max(amrex::Real(0.0), qw - qc - qi);
 }
Referenced by apply_energy_fix_column(), and ShocImplicit::finalize_from_pdf().
set_fab_val()
void shoc::set_fab_val (amrex::FArrayBox & fab, amrex::Real value, InitRunOn) inline
 {
     fab.template setVal<amrex::RunOn::Device>(value);
 }
Referenced by reset_shoc_column_data().
sync_if_needed()
void shoc::sync_if_needed () inline
 {
     // Test-owned helper for host-side assertions. Production SHOC code should
     // keep synchronization out of the runtime path and use this only through
     // shoc_test::run_and_sync or other explicit test utilities.
 #ifdef AMREX_USE_GPU
     amrex::Gpu::streamSynchronize();
 #endif
 }
temperature_from_thetal()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::temperature_from_thetal (amrex::Real thetal, amrex::Real qc, amrex::Real qi, amrex::Real exner) noexcept
 {
     return amrex::max(constants::min_temp(),
                       thetal * amrex::max(exner, amrex::Real(1.0e-12))
                       + condensate_latent_heat(qc, qi) / Cp_d);
 }
Referenced by apply_energy_fix_column(), ShocImplicit::compute_temperature(), and reconstruct_pdf_state().
theta_from_thetal()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::theta_from_thetal (amrex::Real thetal, amrex::Real qc, amrex::Real qi, amrex::Real exner) noexcept
 {
     return thetal
          + condensate_latent_heat(qc, qi)
            / (Cp_d * amrex::max(exner, amrex::Real(1.0e-12)));
 }
thetal_from_theta()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real shoc::thetal_from_theta (amrex::Real theta, amrex::Real qc, amrex::Real qi, amrex::Real exner) noexcept
 {
     return theta
          - condensate_latent_heat(qc, qi)
            / (Cp_d * amrex::max(exner, amrex::Real(1.0e-12)));
 }
Referenced by ShocPreprocess::fill_columns().