ERF: surface_diagnostics Namespace Reference
surface_diagnostics Namespace Reference
Enumerations
enum class SurfaceDiagnosticSource : int {
Missing = 0 , SurfaceLayerLand = 1 , LSMLand = 2 , SurfaceLayerFallback = 3 ,
SurfaceLayerSea = 4 , Custom = 5 , RICO = 6
}
Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE int to_int (SurfaceDiagnosticSource source) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real to_plot_value (SurfaceDiagnosticSource source) noexcept
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE SurfaceDiagnosticSource classify_scalar_source (bool is_custom, bool is_rico, bool is_land, bool has_lsm_flux, bool lsm_flux_is_valid) noexcept
const char * source_name (SurfaceDiagnosticSource source) noexcept
Enumeration Type Documentation
SurfaceDiagnosticSource
enum surface_diagnostics::SurfaceDiagnosticSource : int strong
Enumerator
Missing
SurfaceLayerLand
LSMLand
SurfaceLayerFallback
SurfaceLayerSea
Custom
RICO
 {
     Missing              = 0,
     SurfaceLayerLand     = 1,
     LSMLand              = 2,
     SurfaceLayerFallback = 3,
     SurfaceLayerSea      = 4,
     Custom               = 5,
     RICO                 = 6
 };
Function Documentation
classify_scalar_source()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE SurfaceDiagnosticSource surface_diagnostics::classify_scalar_source (bool is_custom, bool is_rico, bool is_land, bool has_lsm_flux, bool lsm_flux_is_valid) noexcept
 {
     if (is_land && has_lsm_flux && lsm_flux_is_valid) {
         return SurfaceDiagnosticSource::LSMLand;
     }
     if (is_custom) {
         return SurfaceDiagnosticSource::Custom;
     }
     if (is_rico) {
         return SurfaceDiagnosticSource::RICO;
     }
     if (is_land && has_lsm_flux && !lsm_flux_is_valid) {
         return SurfaceDiagnosticSource::SurfaceLayerFallback;
     }
     if (is_land) {
         return SurfaceDiagnosticSource::SurfaceLayerLand;
     }
     return SurfaceDiagnosticSource::SurfaceLayerSea;
 }
Referenced by SurfaceLayer::compute_SurfaceLayer_bcs().
source_name()
const char* surface_diagnostics::source_name (SurfaceDiagnosticSource source) inline noexcept
 {
     switch (source) {
     case SurfaceDiagnosticSource::Missing:              return "missing";
     case SurfaceDiagnosticSource::SurfaceLayerLand:     return "surface_layer_land";
     case SurfaceDiagnosticSource::LSMLand:              return "lsm_land";
     case SurfaceDiagnosticSource::SurfaceLayerFallback: return "surface_layer_fallback";
     case SurfaceDiagnosticSource::SurfaceLayerSea:      return "surface_layer_sea";
     case SurfaceDiagnosticSource::Custom:               return "custom";
     case SurfaceDiagnosticSource::RICO:                 return "rico";
     }
     return "unknown";
 }
to_int()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE int surface_diagnostics::to_int (SurfaceDiagnosticSource source) noexcept
 {
     return static_cast<int>(source);
 }
Referenced by to_plot_value().
to_plot_value()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real surface_diagnostics::to_plot_value (SurfaceDiagnosticSource source) noexcept
 {
     return static_cast<amrex::Real>(to_int(source));
 }
Referenced by SurfaceLayer::compute_SurfaceLayer_bcs(), SurfaceLayer::compute_SurfaceLayer_bcs_EB(), and SurfaceLayer::make_SurfaceLayer_at_level().