ERF: Source/PBL/PBLModels.H File Reference
PBLModels.H File Reference
#include <Thetav.H>
Functions
void ComputeDiffusivityMYNN25 (const amrex::MultiFab &xvel, const amrex::MultiFab &yvel, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, const amrex::Geometry &geom, const TurbChoice &turbChoice, std::unique_ptr< ABLMost > &most, bool use_moisture, int level, const amrex::BCRec *bc_ptr, bool, const std::unique_ptr< amrex::MultiFab > &z_phys_nd)
void ComputeDiffusivityYSU (const amrex::MultiFab &xvel, const amrex::MultiFab &yvel, const amrex::MultiFab &cons_in, amrex::MultiFab &eddyViscosity, const amrex::Geometry &geom, const TurbChoice &turbChoice, std::unique_ptr< ABLMost > &most, bool use_moisture, int level, const amrex::BCRec *bc_ptr, bool, const std::unique_ptr< amrex::MultiFab > &z_phys_nd)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void ComputeVerticalDerivativesPBL (int i, int j, int k, const amrex::Array4< const amrex::Real > &uvel, const amrex::Array4< const amrex::Real > &vvel, const amrex::Array4< const amrex::Real > &cell_data, const int izmin, const int izmax, const amrex::Real &dz_inv, const bool c_ext_dir_on_zlo, const bool c_ext_dir_on_zhi, const bool u_ext_dir_on_zlo, const bool u_ext_dir_on_zhi, const bool v_ext_dir_on_zlo, const bool v_ext_dir_on_zhi, amrex::Real &dthetadz, amrex::Real &dudz, amrex::Real &dvdz, const int moist_flag=0)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeQKESourceTerms (int i, int j, int k, const amrex::Array4< const amrex::Real > &uvel, const amrex::Array4< const amrex::Real > &vvel, const amrex::Array4< const amrex::Real > &cell_data, const amrex::Array4< const amrex::Real > &cell_prim, const amrex::Array4< const amrex::Real > &K_turb, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, amrex::Real pbl_mynn_B1_l, const amrex::Real theta_mean, const int moist_flag, bool c_ext_dir_on_zlo, bool c_ext_dir_on_zhi, bool u_ext_dir_on_zlo, bool u_ext_dir_on_zhi, bool v_ext_dir_on_zlo, bool v_ext_dir_on_zhi, const amrex::Real met_h_zeta=1.0)
Function Documentation
ComputeDiffusivityMYNN25()
void ComputeDiffusivityMYNN25 (const amrex::MultiFab & xvel, const amrex::MultiFab & yvel, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, const amrex::Geometry & geom, const TurbChoice & turbChoice, std::unique_ptr< ABLMost > & most, bool use_moisture, int level, const amrex::BCRec * bc_ptr, bool , const std::unique_ptr< amrex::MultiFab > & z_phys_nd)
Compute eddy diffusivities of momentum (eddy viscosity) and heat using the Mellor-Yamada-Nakanishi-Niino Level 2.5 PBL scheme
Parameters
[in] xvel Velocity in x-dir
[in] yvel Velocity in y-dir
[in] cons_in Cell center conserved quantities
[out] eddyViscosity Holds turbulent viscosity
[in] geom Problem geometry
[in] turbChoice Container with turbulence parameters
[in] most Pointer to Monin-Obukhov class if instantiated
[in] use_moisture If we have microphysics enabled
[in] level Current level
[in] bc_ptr Pointer to array with boundary condition info
[in] vert_only Only compute vertical eddy diffusivities
[in] z_phys_nd Physical location of grid nodes, if terrain (or grid stretching) is enabled
ComputeDiffusivityYSU()
void ComputeDiffusivityYSU (const amrex::MultiFab & xvel, const amrex::MultiFab & yvel, const amrex::MultiFab & cons_in, amrex::MultiFab & eddyViscosity, const amrex::Geometry & geom, const TurbChoice & turbChoice, std::unique_ptr< ABLMost > & most, bool use_moisture, int level, const amrex::BCRec * bc_ptr, bool , const std::unique_ptr< amrex::MultiFab > & z_phys_nd)
Compute eddy diffusivities of momentum (eddy viscosity) and heat using the Yonsei University PBL scheme
Parameters
[in] xvel Velocity in x-dir
[in] yvel Velocity in y-dir
[in] cons_in Cell center conserved quantities
[out] eddyViscosity Holds turbulent viscosity
[in] geom Problem geometry
[in] turbChoice Container with turbulence parameters
[in] most Pointer to Monin-Obukhov class if instantiated
[in] use_moisture If we have microphysics enabled
[in] level Current level
[in] bc_ptr Pointer to array with boundary condition info
[in] vert_only Only compute vertical eddy diffusivities
[in] z_phys_nd Physical location of grid nodes, if terrain (or grid stretching) is enabled
ComputeQKESourceTerms()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real ComputeQKESourceTerms (int i, int j, int k, const amrex::Array4< const amrex::Real > & uvel, const amrex::Array4< const amrex::Real > & vvel, const amrex::Array4< const amrex::Real > & cell_data, const amrex::Array4< const amrex::Real > & cell_prim, const amrex::Array4< const amrex::Real > & K_turb, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, amrex::Real pbl_mynn_B1_l, const amrex::Real theta_mean, const int moist_flag, bool c_ext_dir_on_zlo, bool c_ext_dir_on_zhi, bool u_ext_dir_on_zlo, bool u_ext_dir_on_zhi, bool v_ext_dir_on_zlo, bool v_ext_dir_on_zhi, const amrex::Real met_h_zeta = 1.0)
Function for computing the QKE source terms (NN09, Eqn. 5).
Parameters
[in] u velocity in x-dir
[in] v velocity in y-dir
[in] cell_data conserved cell center vars
[in] cell_prim primitive cell center vars
[in] K_turb turbulent viscosity
[in] cellSizeInv inverse cell size array
[in] domain box of the whole domain
[in] pbl_mynn_B1_l a parameter
[in] theta_mean average theta
 {
     // Compute some relevant derivatives
     amrex::Real dthetadz, dudz, dvdz;
     amrex::Real source_term = 0.0;
     amrex::Real dz_inv = cellSizeInv[2];
     int izmin = domain.smallEnd(2);
     int izmax = domain.bigEnd(2);
     ComputeVerticalDerivativesPBL(i, j, k,
                                   uvel, vvel, cell_data, izmin, izmax, dz_inv/met_h_zeta,
                                   c_ext_dir_on_zlo, c_ext_dir_on_zhi,
                                   u_ext_dir_on_zlo, u_ext_dir_on_zhi,
                                   v_ext_dir_on_zlo, v_ext_dir_on_zhi,
                                   dthetadz, dudz, dvdz,
                                   moist_flag);
     // Note: Transport terms due to turbulence and pressure are included when
     // DiffusionSrcForState_* is called from ERF_slow_rhs_post.
     // Shear Production (Note: We store mu_turb, which is 0.5*K_turb)
     source_term += 4.0*K_turb(i,j,k,EddyDiff::Mom_v) * (dudz*dudz + dvdz*dvdz);
     // Buoyancy Production
     source_term -= 2.0*(CONST_GRAV/theta_mean)*K_turb(i,j,k,EddyDiff::Theta_v)*dthetadz;
     // Dissipation
     amrex::Real qke = cell_prim(i,j,k,PrimQKE_comp);
     if (std::abs(qke) > 0.0) {
         source_term -= 2.0 * cell_data(i,j,k,Rho_comp) * std::pow(qke,1.5) /
             (pbl_mynn_B1_l * K_turb(i,j,k,EddyDiff::PBL_lengthscale));
     }
     return source_term;
 }
Referenced by DiffusionSrcForState_N(), and DiffusionSrcForState_T().
ComputeVerticalDerivativesPBL()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void ComputeVerticalDerivativesPBL (int i, int j, int k, const amrex::Array4< const amrex::Real > & uvel, const amrex::Array4< const amrex::Real > & vvel, const amrex::Array4< const amrex::Real > & cell_data, const int izmin, const int izmax, const amrex::Real & dz_inv, const bool c_ext_dir_on_zlo, const bool c_ext_dir_on_zhi, const bool u_ext_dir_on_zlo, const bool u_ext_dir_on_zhi, const bool v_ext_dir_on_zlo, const bool v_ext_dir_on_zhi, amrex::Real & dthetadz, amrex::Real & dudz, amrex::Real & dvdz, const int moist_flag = 0)
Function for computing vertical derivatives for use in PBL model
Parameters
[in] u velocity in x-dir
[in] v velocity in y-dir
[in] cell_data conserved cell center vars
 {
     if ( k==izmax && c_ext_dir_on_zhi ) {
         dthetadz = (1.0/3.0)*(       -Thetav(i,j,k-1,cell_data,moist_flag)
                               - 3.0 * Thetav(i,j,k  ,cell_data,moist_flag)
                               + 4.0 * Thetav(i,j,k+1,cell_data,moist_flag) )*dz_inv;
     } else if ( k==izmin && c_ext_dir_on_zlo ) {
         dthetadz = (1.0/3.0)*(        Thetav(i,j,k+1,cell_data,moist_flag)
                               + 3.0 * Thetav(i,j,k  ,cell_data,moist_flag)
                               - 4.0 * Thetav(i,j,k-1,cell_data,moist_flag) )*dz_inv;
     } else {
         dthetadz = 0.5*(  Thetav(i,j,k+1,cell_data,moist_flag)
                         - Thetav(i,j,k-1,cell_data,moist_flag) )*dz_inv;
     }
     if ( k==izmax && u_ext_dir_on_zhi ) {
         dudz = (1.0/6.0)*( (-uvel(i  ,j,k-1) - 3.0 * uvel(i  ,j,k  ) + 4.0 * uvel(i  ,j,k+1))
                            + (-uvel(i+1,j,k-1) - 3.0 * uvel(i+1,j,k  ) + 4.0 * uvel(i+1,j,k+1)) )*dz_inv;
     } else if ( k==izmin && u_ext_dir_on_zlo ) {
         dudz = (1.0/6.0)*( (uvel(i  ,j,k+1) + 3.0 * uvel(i  ,j,k  ) - 4.0 * uvel(i  ,j,k-1))
                            + (uvel(i+1,j,k+1) + 3.0 * uvel(i+1,j,k  ) - 4.0 * uvel(i+1,j,k-1)) )*dz_inv;
     } else {
         dudz = 0.25*( uvel(i,j,k+1) - uvel(i,j,k-1) + uvel(i+1,j,k+1) - uvel(i+1,j,k-1) )*dz_inv;
     }
     if ( k==izmax && v_ext_dir_on_zhi ) {
         dvdz = (1.0/6.0)*( (-vvel(i,j  ,k-1) - 3.0 * vvel(i,j  ,k  ) + 4.0 * vvel(i,j  ,k+1))
                            + (-vvel(i,j+1,k-1) - 3.0 * vvel(i,j+1,k  ) + 4.0 * vvel(i,j+1,k+1)) )*dz_inv;
     } else if ( k==izmin && v_ext_dir_on_zlo ) {
         dvdz = (1.0/6.0)*( (vvel(i,j  ,k+1) + 3.0 * vvel(i,j  ,k  ) - 4.0 * vvel(i,j  ,k-1))
                            + (vvel(i,j+1,k+1) + 3.0 * vvel(i,j+1,k  ) - 4.0 * vvel(i,j+1,k-1)) )*dz_inv;
     } else {
         dvdz = 0.25*( vvel(i,j,k+1) - vvel(i,j,k-1) + vvel(i,j+1,k+1) - vvel(i,j+1,k-1) )*dz_inv;
     }
 }
Referenced by ComputeDiffusivityMYNN25(), ComputeDiffusivityYSU(), and ComputeQKESourceTerms().