ERF: /home/runner/work/ERF/ERF/Source/SpatialStencils/SpatialStencils.H File Reference
SpatialStencils.H File Reference
#include <AMReX.H>
#include <AMReX_MultiFab.H>
#include <AMReX_BCRec.H>
#include <AMReX_InterpFaceRegister.H>
#include "DataStruct.H"
#include "IndexDefines.H"
Functions
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real OmegaFromW (int i, int j, int k, Real w, const amrex::Array4< const Real > u, const amrex::Array4< const Real > v, const amrex::Array4< const Real > z_nd, const GpuArray< Real, AMREX_SPACEDIM > &dxInv)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WFromOmega (int i, int j, int k, amrex::Real omega, const amrex::Array4< const Real > &u, const amrex::Array4< const Real > &v, const amrex::Array4< const Real > &z_nd, const GpuArray< Real, AMREX_SPACEDIM > &dxInv)
void MomentumToVelocity (MultiFab &xvel_out, MultiFab &yvel_out, MultiFab &zvel_out, const MultiFab &cons_in, const MultiFab &xmom_in, const MultiFab &ymom_in, const MultiFab &zmom_in, const IntVect &ngrow)
void VelocityToMomentum (const MultiFab &xvel_in, const MultiFab &yvel_in, const MultiFab &zvel_in, const MultiFab &cons_in, MultiFab &xmom_out, MultiFab &ymom_out, MultiFab &zmom_out, const IntVect &ngrow)
AMREX_GPU_DEVICE Real InterpolateFromCellOrFace (const int &i, const int &j, const int &k, const Array4< const Real > &qty, const int &qty_index, const Real &uadv, const enum Coord &coordDir, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolatePertFromCell (const int &i, const int &j, const int &k, const Array4< const Real > &qty, const int &qty_index, const Real &uadv, const enum Coord &coordDir, const int &spatial_order, const amrex::Real *dptr_hse)
AMREX_GPU_DEVICE Real InterpolateDensityPertFromCellToFace (const int &i, const int &j, const int &k, const Array4< const Real > &cons_in, const Real &uadv, const enum Coord &coordDir, const int &spatial_order, const amrex::Real *dptr_hse)
AMREX_GPU_DEVICE Real AdvectionSrcForXMom (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &u, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionSrcForYMom (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &v, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionSrcForZMom (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &w, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionSrcForState (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &cell_prim, const int &qty_index, const Array4< Real > &flux_x, const Array4< Real > &flux_y, const Array4< Real > &flux_z, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolateTurbulentViscosity (const int &i, const int &j, const int &k, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const Array4< Real > &Ksmag)
Compute K_turb (i-1/2, j+1/2, k) etc given K_turb (i, j, k) is known.
AMREX_GPU_DEVICE Real ComputeStressTerm (const int &i, const int &j, const int &k, const Array4< const Real > &u, const Array4< const Real > &v, const Array4< const Real > &w, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &Ksmag, const SolverChoice &solverChoice, const Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE Real DiffusionSrcForMom (const int &i, const int &j, const int &k, const Array4< const Real > &u, const Array4< const Real > &v, const Array4< const Real > &w, const Array4< const Real > &cons, const enum MomentumEqn &momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &Ksmag, const SolverChoice &solverChoice, const Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE Real ComputeDiffusionFluxForState (const int &i, const int &j, const int &k, const Array4< const Real > &cell_data, const Array4< const Real > &cell_prim, const int &prim_index, const amrex::Real invCellWidth, const Array4< Real > &Ksmag, const SolverChoice &solverChoice, const enum Coord &coordDir)
AMREX_GPU_DEVICE Real DiffusionSrcForState (const int &i, const int &j, const int &k, const Array4< const Real > &cell_data, const Array4< const Real > &cell_prim, const int &qty_index, const Array4< Real > &flux_x, const Array4< Real > &flux_y, const Array4< Real > &flux_z, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &Ksmag, const SolverChoice &solverChoice)
Function Documentation
AdvectionSrcForState()
AMREX_GPU_DEVICE Real AdvectionSrcForState (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & cell_prim, const int & qty_index, const Array4< Real > & flux_x, const Array4< Real > & flux_y, const Array4< Real > & flux_z, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
Meant for the continuity, energy, and scalar equations
{
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real advectionSrc;
     if (qty_index == Rho_comp)
     {
         xflux(i+1,j,k,qty_index) = rho_u(i+1,j,k);
         xflux(i  ,j,k,qty_index) = rho_u(i  ,j,k);
         yflux(i,j+1,k,qty_index) = rho_v(i,j+1,k);
         yflux(i,j  ,k,qty_index) = rho_v(i,j  ,k);
         zflux(i,j,k+1,qty_index) = rho_w(i,j,k+1);
         zflux(i,j,k  ,qty_index) = rho_w(i,j,k  );
     } else {
         const int prim_index = qty_index - RhoTheta_comp;
         Real uadv_hi = rho_u(i+1,j,k);
         Real uadv_lo = rho_u(i  ,j,k);
         Real vadv_hi = rho_v(i,j+1,k);
         Real vadv_lo = rho_v(i,j  ,k);
         Real wadv_hi = rho_w(i,j,k+1);
         Real wadv_lo = rho_w(i,j,k  );
         xflux(i+1,j,k,qty_index) = rho_u(i+1,j,k) *
             InterpolateFromCellOrFace(i+1, j, k, cell_prim, prim_index, uadv_hi, Coord::x, spatial_order);
         xflux(i  ,j,k,qty_index) = rho_u(i  ,j,k) *
             InterpolateFromCellOrFace(i  , j, k, cell_prim, prim_index, uadv_lo, Coord::x, spatial_order);
         yflux(i,j+1,k,qty_index) = rho_v(i,j+1,k) *
             InterpolateFromCellOrFace(i, j+1, k, cell_prim, prim_index, vadv_hi, Coord::y, spatial_order);
         yflux(i,j  ,k,qty_index) = rho_v(i,j  ,k) *
             InterpolateFromCellOrFace(i, j  , k, cell_prim, prim_index, vadv_lo, Coord::y, spatial_order);
         zflux(i,j,k+1,qty_index) = rho_w(i,j,k+1)*
             InterpolateFromCellOrFace(i, j, k+1, cell_prim, prim_index, wadv_hi, Coord::z, spatial_order);
         zflux(i,j,k  ,qty_index) = rho_w(i,j,k  )*
             InterpolateFromCellOrFace(i, j, k  , cell_prim, prim_index, wadv_lo, Coord::z, spatial_order);
     }
     advectionSrc = (xflux(i+1,j,k,qty_index) - xflux(i  ,j,k,qty_index)) * dxInv
                           + (yflux(i,j+1,k,qty_index) - yflux(i,j  ,k,qty_index)) * dyInv
                           + (zflux(i,j,k+1,qty_index) - zflux(i,j,k  ,qty_index)) * dzInv;
     return advectionSrc;
 }
Referenced by erf_implicit_fast_rhs(), and erf_rhs().
AdvectionSrcForXMom()
AMREX_GPU_DEVICE Real AdvectionSrcForXMom (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & u, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
Meant for {x, y, z}- momentum equations
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real rho_u_avg, rho_v_avg, rho_w_avg;
     rho_u_avg = 0.5 * (rho_u(i+1, j, k) + rho_u(i, j, k));
     Real centFluxXXNext = rho_u_avg *
                           InterpolateFromCellOrFace(i+1, j, k, u, 0, rho_u_avg, Coord::x, spatial_order);
     rho_u_avg = 0.5 * (rho_u(i-1, j, k) + rho_u(i, j, k));
     Real centFluxXXPrev = rho_u_avg *
                           InterpolateFromCellOrFace(i  , j, k, u, 0, rho_u_avg, Coord::x, spatial_order);
     rho_v_avg = 0.5 * (rho_v(i, j+1, k) + rho_v(i-1, j+1, k));
     Real edgeFluxXYNext = rho_v_avg *
                           InterpolateFromCellOrFace(i, j+1, k, u, 0, rho_v_avg, Coord::y, spatial_order);
     rho_v_avg = 0.5 * (rho_v(i, j  , k) + rho_v(i-1, j  , k));
     Real edgeFluxXYPrev = rho_v_avg *
                           InterpolateFromCellOrFace(i, j  , k, u, 0, rho_v_avg, Coord::y, spatial_order);
     rho_w_avg = 0.5 * (rho_w(i, j, k+1) + rho_w(i-1, j, k+1));
     Real edgeFluxXZNext = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k+1, u, 0, rho_w_avg, Coord::z, spatial_order);
     rho_w_avg = 0.5 * (rho_w(i, j, k) + rho_w(i-1, j, k));
     Real edgeFluxXZPrev = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k  , u, 0, rho_w_avg, Coord::z, spatial_order);
     Real advectionSrc = (centFluxXXNext - centFluxXXPrev) * dxInv
                                + (edgeFluxXYNext - edgeFluxXYPrev) * dyInv
                                + (edgeFluxXZNext - edgeFluxXZPrev) * dzInv;
     return advectionSrc;
 }
Referenced by erf_rhs().
AdvectionSrcForYMom()
AMREX_GPU_DEVICE Real AdvectionSrcForYMom (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & v, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real rho_u_avg, rho_v_avg, rho_w_avg;
     rho_u_avg = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j-1, k));
     Real edgeFluxYXNext = rho_u_avg *
                           InterpolateFromCellOrFace(i+1, j, k, v, 0, rho_u_avg, Coord::x, spatial_order);
     rho_u_avg = 0.5*(rho_u(i  , j, k) + rho_u(i  , j-1, k));
     Real edgeFluxYXPrev = rho_u_avg *
                           InterpolateFromCellOrFace(i  , j, k, v, 0, rho_u_avg, Coord::x, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j, k) + rho_v(i, j+1, k));
     Real centFluxYYNext = rho_v_avg *
                           InterpolateFromCellOrFace(i, j+1, k, v, 0, rho_v_avg, Coord::y, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j, k) + rho_v(i, j-1, k));
     Real centFluxYYPrev = rho_v_avg *
                           InterpolateFromCellOrFace(i, j  , k, v, 0, rho_v_avg, Coord::y, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j, k+1) + rho_w(i, j-1, k+1));
     Real edgeFluxYZNext = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k+1, v, 0, rho_w_avg, Coord::z, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j, k) + rho_w(i, j-1, k));
     Real edgeFluxYZPrev = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k  , v, 0, rho_w_avg, Coord::z, spatial_order);
     Real advectionSrc = (edgeFluxYXNext - edgeFluxYXPrev) * dxInv
                                + (centFluxYYNext - centFluxYYPrev) * dyInv
                                + (edgeFluxYZNext - edgeFluxYZPrev) * dzInv;
     return advectionSrc;
 }
Referenced by erf_rhs().
AdvectionSrcForZMom()
AMREX_GPU_DEVICE Real AdvectionSrcForZMom (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & w, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real rho_u_avg, rho_v_avg, rho_w_avg;
     rho_u_avg = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j, k-1));
     Real edgeFluxZXNext = rho_u_avg *
                           InterpolateFromCellOrFace(i+1, j, k, w, 0, rho_u_avg, Coord::x, spatial_order);
     rho_u_avg = 0.5*(rho_u(i  , j, k) + rho_u(i  , j, k-1));
     Real edgeFluxZXPrev = rho_u_avg *
                           InterpolateFromCellOrFace(i  , j, k, w, 0, rho_u_avg, Coord::x, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j+1, k) + rho_v(i, j+1, k-1));
     Real edgeFluxZYNext = rho_v_avg *
                           InterpolateFromCellOrFace(i, j+1, k, w, 0, rho_v_avg, Coord::y, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j  , k) + rho_v(i, j  , k-1));
     Real edgeFluxZYPrev = rho_v_avg *
                           InterpolateFromCellOrFace(i, j  , k, w, 0, rho_v_avg, Coord::y, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j  , k+1) + rho_w(i, j, k));
     Real centFluxZZNext = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k+1, w, 0, rho_w_avg, Coord::z, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j  , k-1) + rho_w(i, j, k));
     Real centFluxZZPrev = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k  , w, 0, rho_w_avg, Coord::z, spatial_order);
     Real advectionSrc = (edgeFluxZXNext - edgeFluxZXPrev) * dxInv
                                + (edgeFluxZYNext - edgeFluxZYPrev) * dyInv
                                + (centFluxZZNext - centFluxZZPrev) * dzInv;
     return advectionSrc;
 }
Referenced by erf_rhs().
ComputeDiffusionFluxForState()
AMREX_GPU_DEVICE Real ComputeDiffusionFluxForState (const int & i, const int & j, const int & k, const Array4< const Real > & cell_data, const Array4< const Real > & cell_prim, const int & prim_index, const amrex::Real invCellWidth, const Array4< Real > & Ksmag, const SolverChoice & solverChoice, const enum Coord & coordDir)
 {
   // Get indices of states to left and right of the face on which we want the flux
   const int il = i - (coordDir == Coord::x);
   const int ir = i;
   const int jl = j - (coordDir == Coord::y);
   const int jr = j;
   const int kl = k - (coordDir == Coord::z);
   const int kr = k;
   // Get diffusion coefficients
   amrex::Real rhoAlpha_molec;
   int eddy_diff_idx;
   amrex::Real rhoFace;
   if (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha) {
     rhoFace = (cell_data(il, jl, kl, Rho_comp) + cell_data(ir, jr, kr, Rho_comp)) * 0.5;
   }
   switch(prim_index) {
       case PrimTheta_comp: // Potential Temperature
           if (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha) {
               rhoAlpha_molec = rhoFace * solverChoice.alpha_T;
           } else {
               rhoAlpha_molec = solverChoice.rhoAlpha_T;
           }
           if (coordDir == Coord::z) {
               eddy_diff_idx = EddyDiff::Theta_v;
           } else {
               eddy_diff_idx = EddyDiff::Theta_h;
           }
           break;
       case PrimKE_comp: // Turbulent KE
           rhoAlpha_molec = 0.;
           if (coordDir == Coord::z) {
               eddy_diff_idx = EddyDiff::KE_v;
           } else {
               eddy_diff_idx = EddyDiff::KE_h;
           }
           break;
       case PrimQKE_comp: // Turbulent QKE
           rhoAlpha_molec = 0.;
           if (coordDir == Coord::z) {
               eddy_diff_idx = EddyDiff::QKE_v;
           } else {
               eddy_diff_idx = EddyDiff::QKE_h;
           }
           break;
       case PrimScalar_comp: // Scalar
           if (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha) {
               rhoAlpha_molec = rhoFace * solverChoice.alpha_C;
           } else {
               rhoAlpha_molec = solverChoice.rhoAlpha_C;
           }
           if (coordDir == Coord::z) {
               eddy_diff_idx = EddyDiff::Scalar_v;
           } else {
               eddy_diff_idx = EddyDiff::Scalar_h;
           }
           break;
       default:
           amrex::Abort("Error: Diffusion term for the data index isn't implemented");
   }
   amrex::Real rhoAlpha = 0.0;
   if ( (solverChoice.molec_diff_type == MolecDiffType::Constant) ||
        (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha) ) {
     rhoAlpha += rhoAlpha_molec;
   }
   if ( (solverChoice.les_type == LESType::Smagorinsky) ||
        (solverChoice.les_type == LESType::Deardorff  ) ||
        (solverChoice.pbl_type == PBLType::MYNN25     ) ) {
     rhoAlpha += 0.5*(K_turb(ir,jr,kr,eddy_diff_idx) + K_turb(il,jl,kl,eddy_diff_idx));
   }
   // Compute the flux
   amrex::Real diffusionFlux = rhoAlpha * invCellWidth *
       (cell_prim(ir, jr, kr, prim_index) - cell_prim(il, jl, kl, prim_index));
   return diffusionFlux;
 }
Referenced by DiffusionSrcForState().
ComputeStressTerm()
AMREX_GPU_DEVICE Real ComputeStressTerm (const int & i, const int & j, const int & k, const Array4< const Real > & u, const Array4< const Real > & v, const Array4< const Real > & w, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & Ksmag, const SolverChoice & solverChoice, const Box & domain, const amrex::BCRec * bc_ptr) inline
Compute tau_ij (m + 1/2), tau_ij (m - 1/2) where m = {i, j, k} for DNS or Smagorinsky
 {
     // Here, we have computed strain rate on the fly.
     // TODO: It may be better to store S11, S12 etc. at all the (m+1/2) and (m-1/2) grid points (edges) and use them here.
     Real strainRate = ComputeStrainRate(i, j, k, u, v, w, momentumEqn, diffDir, cellSizeInv, domain, bc_ptr);
     // D_ij term
     Real expansionRate = ComputeExpansionRate(i, j, k, u, v, w, momentumEqn, diffDir, cellSizeInv);
     Real strainRateDeviatoric = strainRate - expansionRate; // sigma_ij = S_ij - D_ij
     Real stressTerm = ComputeStressGivenRates(i,j,k,momentumEqn,diffDir,K_turb,solverChoice, strainRateDeviatoric);
     return stressTerm;
 }
Referenced by DiffusionSrcForMom().
DiffusionSrcForMom()
AMREX_GPU_DEVICE Real DiffusionSrcForMom (const int & i, const int & j, const int & k, const Array4< const Real > & u, const Array4< const Real > & v, const Array4< const Real > & w, const Array4< const Real > & cons, const enum MomentumEqn & momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & Ksmag, const SolverChoice & solverChoice, const Box & domain, const amrex::BCRec * bc_ptr)
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real diffContrib = 0.0;
     int l_spatial_order = solverChoice.spatial_order;
     switch (momentumEqn) {
         case MomentumEqn::x:
             Real tau11Next, tau11Prev, tau12Next, tau12Prev, tau13Next, tau13Prev;
             tau11Next = ComputeStressTerm(i+1, j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau11Prev = ComputeStressTerm(i  , j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau12Next = ComputeStressTerm(i, j+1, k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau12Prev = ComputeStressTerm(i, j  , k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau13Next = ComputeStressTerm(i, j, k+1, u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau13Prev = ComputeStressTerm(i, j, k  , u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             diffContrib = (tau11Next - tau11Prev) * dxInv  // Contribution to x-mom eqn from diffusive flux in x-dir
                         + (tau12Next - tau12Prev) * dyInv  // Contribution to x-mom eqn from diffusive flux in y-dir
                         + (tau13Next - tau13Prev) * dzInv; // Contribution to x-mom eqn from diffusive flux in z-dir
             if (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
             {
                 diffContrib *= InterpolateFromCellOrFace(i, j, k, cons, Rho_comp, u(i,j,k), Coord::x, l_spatial_order) /
                                solverChoice.rho0_trans;
             }
             break;
         case MomentumEqn::y:
             Real tau21Next, tau21Prev, tau22Next, tau22Prev, tau23Next, tau23Prev;
             tau21Next = ComputeStressTerm(i+1, j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau21Prev = ComputeStressTerm(i  , j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau22Next = ComputeStressTerm(i, j+1, k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau22Prev = ComputeStressTerm(i, j  , k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau23Next = ComputeStressTerm(i, j, k+1, u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau23Prev = ComputeStressTerm(i, j, k  , u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             diffContrib = (tau21Next - tau21Prev) * dxInv  // Contribution to y-mom eqn from diffusive flux in x-dir
                         + (tau22Next - tau22Prev) * dyInv  // Contribution to y-mom eqn from diffusive flux in y-dir
                         + (tau23Next - tau23Prev) * dzInv; // Contribution to y-mom eqn from diffusive flux in z-dir
             if (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
             {
                 diffContrib *= InterpolateFromCellOrFace(i, j, k, cons, Rho_comp, v(i,j,k), Coord::y, l_spatial_order) /
                                solverChoice.rho0_trans;
             }
             break;
         case MomentumEqn::z:
             Real tau31Next, tau31Prev, tau32Next, tau32Prev, tau33Next, tau33Prev;
             tau31Next = ComputeStressTerm(i+1, j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau31Prev = ComputeStressTerm(i  , j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau32Next = ComputeStressTerm(i, j+1, k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau32Prev = ComputeStressTerm(i, j  , k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau33Next = ComputeStressTerm(i, j, k+1, u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             tau33Prev = ComputeStressTerm(i, j, k  , u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_turb, solverChoice, domain, bc_ptr);
             diffContrib = (tau31Next - tau31Prev) * dxInv  // Contribution to z-mom eqn from diffusive flux in x-dir
                         + (tau32Next - tau32Prev) * dyInv  // Contribution to z-mom eqn from diffusive flux in y-dir
                         + (tau33Next - tau33Prev) * dzInv; // Contribution to z-mom eqn from diffusive flux in z-dir
             if (solverChoice.molec_diff_type == MolecDiffType::ConstantAlpha)
             {
                 diffContrib *= InterpolateFromCellOrFace(i, j, k, cons, Rho_comp, w(i,j,k), Coord::z, l_spatial_order) /
                                solverChoice.rho0_trans;
             }
             break;
         default:
             amrex::Abort("Error: Momentum equation is unrecognized");
     }
     return diffContrib;
 }
Referenced by erf_rhs().
DiffusionSrcForState()
AMREX_GPU_DEVICE Real DiffusionSrcForState (const int & i, const int & j, const int & k, const Array4< const Real > & cell_data, const Array4< const Real > & cell_prim, const int & qty_index, const Array4< Real > & flux_x, const Array4< Real > & flux_y, const Array4< Real > & flux_z, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & Ksmag, const SolverChoice & solverChoice)
 {
   const amrex::Real dx_inv = cellSizeInv[0];
   const amrex::Real dy_inv = cellSizeInv[1];
   const amrex::Real dz_inv = cellSizeInv[2];
   const int prim_index = qty_index - RhoTheta_comp;
   // TODO : could be more efficient to compute and save all fluxes before taking divergence (now all fluxes are computed 2x);
   xflux(i+1,j,k,qty_index) = ComputeDiffusionFluxForState(i+1, j, k, cell_data, cell_prim, prim_index, dx_inv, K_turb, solverChoice, Coord::x);
   xflux(i  ,j,k,qty_index) = ComputeDiffusionFluxForState(i  , j, k, cell_data, cell_prim, prim_index, dx_inv, K_turb, solverChoice, Coord::x);
   yflux(i,j+1,k,qty_index) = ComputeDiffusionFluxForState(i, j+1, k, cell_data, cell_prim, prim_index, dy_inv, K_turb, solverChoice, Coord::y);
   yflux(i,j  ,k,qty_index) = ComputeDiffusionFluxForState(i, j  , k, cell_data, cell_prim, prim_index, dy_inv, K_turb, solverChoice, Coord::y);
   zflux(i,j,k+1,qty_index) = ComputeDiffusionFluxForState(i, j, k+1, cell_data, cell_prim, prim_index, dz_inv, K_turb, solverChoice, Coord::z);
   zflux(i,j,k  ,qty_index) = ComputeDiffusionFluxForState(i, j, k  , cell_data, cell_prim, prim_index, dz_inv, K_turb, solverChoice, Coord::z);
   Real diffusionSrc =
       (xflux(i+1,j,k,qty_index) - xflux(i  ,j,k,qty_index)) * dx_inv   // Diffusive flux in x-dir
      +(yflux(i,j+1,k,qty_index) - yflux(i,j  ,k,qty_index)) * dy_inv   // Diffusive flux in y-dir
      +(zflux(i,j,k+1,qty_index) - zflux(i,j,k  ,qty_index)) * dz_inv;  // Diffusive flux in z-dir
   return diffusionSrc;
 }
Referenced by erf_rhs().
InterpolateDensityPertFromCellToFace()
AMREX_GPU_DEVICE Real InterpolateDensityPertFromCellToFace (const int & i, const int & j, const int & k, const Array4< const Real > & cons_in, const Real & uadv, const enum Coord & coordDir, const int & spatial_order, const amrex::Real * dptr_hse)
InterpolateFromCellOrFace()
AMREX_GPU_DEVICE Real InterpolateFromCellOrFace (const int & i, const int & j, const int & k, const Array4< const Real > & qty, const int & qty_index, const Real & uadv, const enum Coord & coordDir, const int & spatial_order)
InterpolatePertFromCell()
AMREX_GPU_DEVICE Real InterpolatePertFromCell (const int & i, const int & j, const int & k, const Array4< const Real > & qty, const int & qty_index, const Real & uadv, const enum Coord & coordDir, const int & spatial_order, const amrex::Real * dptr_hse)
InterpolateTurbulentViscosity()
AMREX_GPU_DEVICE Real InterpolateTurbulentViscosity (const int & i, const int & j, const int & k, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const Array4< Real > & Ksmag) inline
Compute K_turb (i-1/2, j+1/2, k) etc given K_turb (i, j, k) is known.
Compute K (i-1/2, j+1/2, k) etc given K(i, j, k) or nut (i, j, k) is known
{
   // Assuming we already have 'K_turb' computed for all (i, j, k)
   Real turbViscInterpolated = 1.0;
   switch (momentumEqn) {
   case MomentumEqn::x: // Reference face is x-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       turbViscInterpolated = K_turb(i-1, j, k, EddyDiff::Mom_h);
       break;
     case DiffusionDir::y:
       turbViscInterpolated = 0.25*( K_turb(i-1, j, k, EddyDiff::Mom_h) + K_turb(i, j, k, EddyDiff::Mom_h)
                     + K_turb(i-1, j-1, k, EddyDiff::Mom_h) + K_turb(i, j-1, k, EddyDiff::Mom_h) );
       break;
     case DiffusionDir::z:
       turbViscInterpolated = 0.25*( K_turb(i-1, j, k, EddyDiff::Mom_v) + K_turb(i, j, k, EddyDiff::Mom_v)
                     + K_turb(i-1, j, k-1, EddyDiff::Mom_v) + K_turb(i, j, k-1, EddyDiff::Mom_v) );
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::y: // Reference face is y-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       turbViscInterpolated = 0.25*( K_turb(i, j-1, k, EddyDiff::Mom_h) + K_turb(i, j, k, EddyDiff::Mom_h)
                     + K_turb(i-1, j-1, k, EddyDiff::Mom_h) + K_turb(i-1, j, k, EddyDiff::Mom_h) );
       break;
     case DiffusionDir::y:
       turbViscInterpolated = K_turb(i, j-1, k, EddyDiff::Mom_h);
       break;
     case DiffusionDir::z:
       turbViscInterpolated = 0.25*( K_turb(i, j-1, k, EddyDiff::Mom_v) + K_turb(i, j, k, EddyDiff::Mom_v)
                     + K_turb(i, j-1, k-1, EddyDiff::Mom_v) + K_turb(i, j, k-1, EddyDiff::Mom_v) );
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::z: // Reference face is z-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       turbViscInterpolated = 0.25*( K_turb(i, j, k-1, EddyDiff::Mom_v) + K_turb(i, j, k, EddyDiff::Mom_v)
                     + K_turb(i-1, j, k-1, EddyDiff::Mom_v) + K_turb(i-1, j, k, EddyDiff::Mom_v) );
       break;
     case DiffusionDir::y:
       turbViscInterpolated = 0.25*( K_turb(i, j, k-1, EddyDiff::Mom_v) + K_turb(i, j, k, EddyDiff::Mom_v)
                     + K_turb(i, j-1, k-1, EddyDiff::Mom_v) + K_turb(i, j-1, k, EddyDiff::Mom_v) );
       break;
     case DiffusionDir::z:
       turbViscInterpolated = K_turb(i, j, k-1, EddyDiff::Mom_v);
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   default:
     amrex::Abort("Error: Momentum equation is unrecognized");
   }
   return turbViscInterpolated;
 }
Referenced by ComputeStressGivenRates().
MomentumToVelocity()
void MomentumToVelocity (MultiFab & xvel, MultiFab & yvel, MultiFab & zvel, const MultiFab & cons_in, const MultiFab & xmom_in, const MultiFab & ymom_in, const MultiFab & zmom_in, const IntVect & ngrow)
Convert updated momentum to updated velocity
 {
     BL_PROFILE_VAR("MomentumToVelocity()",MomentumToVelocity);
     // Loop over boxes = valid boxes grown by ngrow
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
     for ( MFIter mfi(cons_in,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& tbx = amrex::grow(mfi.nodaltilebox(0),ngrow);
         const Box& tby = amrex::grow(mfi.nodaltilebox(1),ngrow);
         const Box& tbz = amrex::grow(mfi.nodaltilebox(2),ngrow);
         // Conserved variables on cell centers -- we use this for density
         const Array4<const Real>& cons = cons_in.array(mfi);
         // Momentum on faces
         Array4<Real const> const& momx = xmom_in.array(mfi);
         Array4<Real const> const& momy = ymom_in.array(mfi);
         Array4<Real const> const& momz = zmom_in.array(mfi);
         // Velocity on faces
         const Array4<Real>& velx = xvel.array(mfi);
         const Array4<Real>& vely = yvel.array(mfi);
         const Array4<Real>& velz = zvel.array(mfi);
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             velx(i,j,k) = momx(i,j,k)/(0.5 * (cons(i,j,k,Rho_comp) + cons(i-1,j,k,Rho_comp)));
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             vely(i,j,k) = momy(i,j,k)/(0.5 * (cons(i,j,k,Rho_comp) + cons(i,j-1,k,Rho_comp)));
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             velz(i,j,k) = momz(i,j,k)/(0.5 * (cons(i,j,k,Rho_comp) + cons(i,j,k-1,Rho_comp)));
         });
     } // end MFIter
 }
Referenced by ERF::erf_advance(), and MomentumToVelocity().
OmegaFromW()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real OmegaFromW (int i, int j, int k, Real w, const amrex::Array4< const Real > u, const amrex::Array4< const Real > v, const amrex::Array4< const Real > z_nd, const GpuArray< Real, AMREX_SPACEDIM > & dxInv)
 {
     // This is dh/dxi at z-face (i,j,k-1/2)
     Real met_zlo_xi   = 0.5 * dxInv[0] *
                               ( z_nd(i+1,j+1,k  ) + z_nd(i+1,j  ,k  )    // hi i, lo k
                                -z_nd(i  ,j+1,k  ) - z_nd(i  ,j  ,k  ) ); // lo i, lo k
     // This is dh/deta at z-face (i,j,k-1/2)
     Real met_zlo_eta  = 0.5 * dxInv[1] *
                               ( z_nd(i+1,j+1,k  ) + z_nd(i  ,j+1,k  )    // hi j, lo k
                                -z_nd(i+1,j  ,k  ) - z_nd(i  ,j  ,k  ) ); // lo j, lo k
     // Use extrapolation instead of interpolation if at the bottom boundary
     Real vec_zlo_xi   = (k == 0) ? 1.5 * (0.5*(u(i,j,k)+u(i+1,j,k))) - 0.5*(0.5*(u(i,j,k+1)+u(i+1,j,k+1))) :
         0.25 * ( u(i,j,k-1) + u(i+1,j,k-1) + u(i,j,k) + u(i+1,j,k) );
     Real vec_zlo_eta  = (k == 0) ? 1.5 * (0.5*( v(i,j,k)+v(i,j+1,k))) - 0.5*(0.5*(v(i,j,k+1)+v(i,j+1,k+1))) :
         0.25 * ( v(i,j,k-1) + v(i,j+1,k-1) + v(i,j,k) + v(i,j+1,k) );
     Real omega = -met_zlo_xi * vec_zlo_xi - met_zlo_eta * vec_zlo_eta + w;
     return omega;
 }
Referenced by erf_implicit_fast_rhs().
VelocityToMomentum()
void VelocityToMomentum (const MultiFab & xvel_in, const MultiFab & yvel_in, const MultiFab & zvel_in, const MultiFab & cons_in, MultiFab & xmom, MultiFab & ymom, MultiFab & zmom, const IntVect & ngrow)
Convert velocity to momentum.
 {
     BL_PROFILE_VAR("VelocityToMomentum()",VelocityToMomentum);
     // Loop over boxes = valid boxes grown by ngrow
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
     for ( MFIter mfi(cons_in,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& tbx = amrex::grow(mfi.nodaltilebox(0),ngrow);
         const Box& tby = amrex::grow(mfi.nodaltilebox(1),ngrow);
         const Box& tbz = amrex::grow(mfi.nodaltilebox(2),ngrow);
         // Conserved/state variables on cell centers -- we use this for density
         const Array4<const Real>& cons = cons_in.array(mfi);
         // Momentum on faces, to be computed
         Array4<Real> const& momx = xmom.array(mfi);
         Array4<Real> const& momy = ymom.array(mfi);
         Array4<Real> const& momz = zmom.array(mfi);
         // Velocity on faces, used in computation
         const Array4<Real const>& velx = xvel_in.array(mfi);
         const Array4<Real const>& vely = yvel_in.array(mfi);
         const Array4<Real const>& velz = zvel_in.array(mfi);
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momx(i,j,k) = velx(i,j,k) * 0.5 * (cons(i,j,k,Rho_comp) + cons(i-1,j,k,Rho_comp));
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momy(i,j,k) = vely(i,j,k) * 0.5 * (cons(i,j,k,Rho_comp) + cons(i,j-1,k,Rho_comp));
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momz(i,j,k) = velz(i,j,k) * 0.5 * (cons(i,j,k,Rho_comp) + cons(i,j,k-1,Rho_comp));
         });
     } // end MFIter
 }
Referenced by ERF::Advance(), and ERF::erf_advance().
WFromOmega()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WFromOmega (int i, int j, int k, amrex::Real omega, const amrex::Array4< const Real > & u, const amrex::Array4< const Real > & v, const amrex::Array4< const Real > & z_nd, const GpuArray< Real, AMREX_SPACEDIM > & dxInv)
 {
     // This is dh/dxi at z-face (i,j,k-1/2)
     Real met_zlo_xi   = 0.5 * dxInv[0] *
                               ( z_nd(i+1,j+1,k  ) + z_nd(i+1,j  ,k  )    // hi i, lo k
                                -z_nd(i  ,j+1,k  ) - z_nd(i  ,j  ,k  ) ); // lo i, lo k
     // This is dh/deta at z-face (i,j,k-1/2)
     Real met_zlo_eta  = 0.5 * dxInv[1] *
                               ( z_nd(i+1,j+1,k  ) + z_nd(i  ,j+1,k  )    // hi j, lo k
                                -z_nd(i+1,j  ,k  ) - z_nd(i  ,j  ,k  ) ); // lo j, lo k
     // Use extrapolation instead of interpolation if at the bottom boundary
     Real vec_zlo_xi   = (k == 0) ? 1.5 * (0.5*(u(i,j,k)+u(i+1,j,k))) - 0.5*(0.5*(u(i,j,k+1)+u(i+1,j,k+1))) :
         0.25 * ( u(i,j,k-1) + u(i+1,j,k-1) + u(i,j,k) + u(i+1,j,k) );
     Real vec_zlo_eta  = (k == 0) ? 1.5 * (0.5*( v(i,j,k)+v(i,j+1,k))) - 0.5*(0.5*(v(i,j,k+1)+v(i,j+1,k+1))) :
         0.25 * ( v(i,j,k-1) + v(i,j+1,k-1) + v(i,j,k) + v(i,j+1,k) );
     Real w = met_zlo_xi * vec_zlo_xi + met_zlo_eta * vec_zlo_eta + omega;
     return w;
 }
Referenced by erf_implicit_fast_rhs().