ERF: /home/runner/work/ERF/ERF/Source/SpatialStencils/StrainRate.H File Reference
StrainRate.H File Reference
#include <AMReX_BCRec.H>
#include <IndexDefines.H>
#include <TerrainMetrics.H>
Functions
AMREX_GPU_DEVICE bool is_on_face (int bc_in)
AMREX_GPU_DEVICE amrex::Real ComputeS11WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &met_h_xi, const amrex::Real &, const amrex::Real &met_h_zeta)
AMREX_GPU_DEVICE amrex::Real ComputeS22WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &v, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &, const amrex::Real &met_h_eta, const amrex::Real &met_h_zeta)
AMREX_GPU_DEVICE amrex::Real ComputeS33WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &, const amrex::Real &, const amrex::Real &met_h_zeta, const amrex::Box &domain)
AMREX_GPU_DEVICE amrex::Real ComputeS12WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &met_h_xi, const amrex::Real &met_h_eta, const amrex::Real &met_h_zeta, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS13WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &met_h_xi, const amrex::Real &, const amrex::Real &met_h_zeta, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS23WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &, const amrex::Real &met_h_eta, const amrex::Real &met_h_zeta, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS21WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &met_h_xi, const amrex::Real &met_h_eta, const amrex::Real &met_h_zeta, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS31WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &met_h_xi, const amrex::Real &met_h_eta, const amrex::Real &met_h_zeta, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS32WithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Real &met_h_xi, const amrex::Real &met_h_eta, const amrex::Real &met_h_zeta, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeStrainRateWithTerrain (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS11 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv)
AMREX_GPU_DEVICE amrex::Real ComputeS22 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &v, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv)
AMREX_GPU_DEVICE amrex::Real ComputeS33 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain)
AMREX_GPU_DEVICE amrex::Real ComputeS12 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS13 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS23 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS21 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS31 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeS32 (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
AMREX_GPU_DEVICE amrex::Real ComputeStrainRate (const int &i, const int &j, const int &k, const amrex::Array4< amrex::Real const > &u, const amrex::Array4< amrex::Real const > &v, const amrex::Array4< amrex::Real const > &w, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Box &domain, const amrex::BCRec *bc_ptr)
Function Documentation
ComputeS11()
AMREX_GPU_DEVICE amrex::Real ComputeS11 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv) inline
 {
   amrex::Real dx_inv = cellSizeInv[0];
   return (u(i, j, k) - u(i-1, j, k))*dx_inv;
 }
Referenced by ComputeSmnSmn(), and ComputeStrainRate().
ComputeS11WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS11WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & met_h_xi, const amrex::Real & , const amrex::Real & met_h_zeta) inline
 {
   amrex::Real GradUz;
   amrex::Real strainRate = 0;
   amrex::Real dx_inv = cellSizeInv[0];
   amrex::Real dz_inv = cellSizeInv[2];
   // At cell center
   GradUz = 0.25 * dz_inv *
     ( u(i  ,j  ,k+1) + u(i-1,j  ,k+1)
      -u(i  ,j  ,k-1) - u(i-1,j  ,k-1) );
   strainRate = ( u(i  ,j  ,k  ) - u(i-1,j  ,k  ) ) * dx_inv
              - (met_h_xi/met_h_zeta) * GradUz;
   return strainRate;
 }
Referenced by ComputeSmnSmnWithTerrain(), and ComputeStrainRateWithTerrain().
ComputeS12()
AMREX_GPU_DEVICE amrex::Real ComputeS12 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & , const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     amrex::Real dx_inv = cellSizeInv[0];
     amrex::Real dy_inv = cellSizeInv[1];
     amrex::Real strainRate = 0;
     if (j == domain.smallEnd(1) && is_on_face(bc_ptr[BCVars::xvel_bc].lo(1))) {
         strainRate =  (-(8./3.) * u(i,j-1,k) + 3. * u(i,j,k) - (1./3.) * u(i,j+1,k))*dy_inv;
     } else if (j == domain.bigEnd(1)+1 && is_on_face(bc_ptr[BCVars::xvel_bc].hi(1))) {
         strainRate = -(-(8./3.) * u(i,j,k) + 3. * u(i,j-1,k) - (1./3.) * u(i,j-2,k))*dy_inv;
     } else {
         strainRate = (u(i, j, k) - u(i, j-1, k))*dy_inv;
     }
     if (i == domain.smallEnd(0) && is_on_face(bc_ptr[BCVars::yvel_bc].lo(0))) {
         strainRate +=  (-(8./3.) * v(i-1,j,k) + 3. * v(i,j,k) - (1./3.) * v(i+1,j,k))*dx_inv;
     } else if (i == domain.bigEnd(0)+1 && is_on_face(bc_ptr[BCVars::yvel_bc].hi(0))) {
         strainRate += -(-(8./3.) * v(i,j,k) + 3. * v(i-1,j,k) - (1./3.) * v(i-2,j,k))*dx_inv;
     } else {
         strainRate += (v(i, j, k) - v(i-1, j, k)) * dx_inv;
     }
     strainRate *= 0.5;
     return strainRate;
 }
Referenced by ComputeS21(), ComputeSmnSmn(), and ComputeStrainRate().
ComputeS12WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS12WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & , const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & met_h_xi, const amrex::Real & met_h_eta, const amrex::Real & met_h_zeta, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
   amrex::Real strainRate = 0;
   amrex::Real GradUz,GradVz;
   amrex::Real dx_inv = cellSizeInv[0];
   amrex::Real dy_inv = cellSizeInv[1];
   amrex::Real dz_inv = cellSizeInv[2];
   if (j == domain.smallEnd(1) && is_on_face(bc_ptr[BCVars::xvel_bc].lo(1))) {
     strainRate  = (-(8./3.) * u(i,j-1,k) + 3. * u(i,j,k) -
                     (1./3.) * u(i,j+1,k))*dy_inv;
   } else if (j == domain.bigEnd(1)+1 && is_on_face(bc_ptr[BCVars::xvel_bc].hi(1))) {
     strainRate  = -(-(8./3.) * u(i,j,k) + 3. * u(i,j-1,k) -
                      (1./3.) * u(i,j-2,k))*dy_inv;
   } else {
     strainRate  =  (u(i, j, k) - u(i, j-1, k)) * dy_inv;
   }
   if (i == domain.smallEnd(0) && is_on_face(bc_ptr[BCVars::yvel_bc].lo(0))) {
     strainRate += (-(8./3.) * v(i-1,j,k) + 3. * v(i,j,k) -
                     (1./3.) * v(i+1,j,k))*dx_inv;
   } else if (i == domain.bigEnd(0)+1 && is_on_face(bc_ptr[BCVars::yvel_bc].hi(0))) {
     strainRate += -(-(8./3.) * v(i,j,k) + 3. * v(i-1,j,k) -
                      (1./3.) * v(i-2,j,k))*dx_inv;
   } else {
     strainRate +=  (v(i, j, k) - v(i-1, j, k)) * dx_inv;
   }
   // At EdgeCenterK
   GradUz = 0.25 * dz_inv *
     ( u(i  ,j  ,k+1) + u(i  ,j-1,k+1)
      -u(i  ,j  ,k-1) - u(i  ,j-1,k-1) );
   GradVz = 0.25 * dz_inv *
     ( v(i  ,j  ,k+1) + v(i-1,j  ,k+1)
      -v(i  ,j  ,k-1) - v(i-1,j  ,k-1) );
   strainRate += -(met_h_eta/met_h_zeta)*GradUz - (met_h_xi/met_h_zeta)*GradVz;
   strainRate *= 0.5;
   return strainRate;
 }
Referenced by ComputeS21WithTerrain(), ComputeSmnSmnWithTerrain(), and ComputeStrainRateWithTerrain().
ComputeS13()
AMREX_GPU_DEVICE amrex::Real ComputeS13 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & , const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     amrex::Real dx_inv = cellSizeInv[0];
     amrex::Real dz_inv = cellSizeInv[2];
     amrex::Real strainRate;
     if (k == domain.smallEnd(2) && is_on_face(bc_ptr[BCVars::xvel_bc].lo(2))) {
         strainRate =  (-(8./3.) * u(i,j,k-1) + 3. * u(i,j,k) - (1./3.) * u(i,j,k+1))*dz_inv;
     } else if (k == domain.bigEnd(2)+1 && is_on_face(bc_ptr[BCVars::xvel_bc].hi(2))) {
         strainRate = -(-(8./3.) * u(i,j,k) + 3. * u(i,j,k-1) - (1./3.) * u(i,j,k-2))*dz_inv;
     } else {
         strainRate = (u(i, j, k) - u(i, j, k-1))*dz_inv;
     }
     if (i == domain.smallEnd(0) && is_on_face(bc_ptr[BCVars::zvel_bc].lo(0))) {
         strainRate +=  (-(8./3.) * w(i-1,j,k) + 3. * w(i,j,k) - (1./3.) * w(i+1,j,k))*dx_inv;
     } else if (i == domain.bigEnd(0)+1 && is_on_face(bc_ptr[BCVars::zvel_bc].hi(0))) {
         strainRate += -(-(8./3.) * w(i,j,k) + 3. * w(i-1,j,k) - (1./3.) * w(i-2,j,k))*dx_inv;
     } else {
         if (k > domain.smallEnd(2) && k <= domain.bigEnd(2)+1) {
             strainRate += (w(i, j, k) - w(i-1, j, k)) * dx_inv;
         }
     }
     strainRate *= 0.5;
     return strainRate;
 }
Referenced by ComputeS31(), ComputeSmnSmn(), and ComputeStrainRate().
ComputeS13WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS13WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & , const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & met_h_xi, const amrex::Real & , const amrex::Real & met_h_zeta, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
   amrex::Real GradWz;
   amrex::Real strainRate = 0;
   amrex::Real dx_inv = cellSizeInv[0];
   amrex::Real dz_inv = cellSizeInv[2];
   if (k == domain.smallEnd(2) && is_on_face(bc_ptr[BCVars::xvel_bc].lo(2))) {
     strainRate  =  (-(8./3.) * u(i,j,k-1) + 3. * u(i,j,k) -
                      (1./3.) * u(i,j,k+1)) * dz_inv / met_h_zeta;
   } else if (k == domain.bigEnd(2)+1 && is_on_face(bc_ptr[BCVars::xvel_bc].hi(2))) {
     strainRate  = -(-(8./3.) * u(i,j,k) + 3. * u(i,j,k-1) -
                      (1./3.) * u(i,j,k-2)) * dz_inv / met_h_zeta;
   } else {
     strainRate  =  (u(i, j, k) - u(i, j, k-1)) * dz_inv / met_h_zeta;
   }
   if (i == domain.smallEnd(0) && is_on_face(bc_ptr[BCVars::zvel_bc].lo(0))) {
     strainRate +=  (-(8./3.) * w(i-1,j,k) + 3. * w(i,j,k) - (1./3.) * w(i+1,j,k))*dx_inv;
   } else if (i == domain.bigEnd(0)+1 && is_on_face(bc_ptr[BCVars::zvel_bc].hi(0))) {
     strainRate += -(-(8./3.) * w(i,j,k) + 3. * w(i-1,j,k) - (1./3.) * w(i-2,j,k))*dx_inv;
   } else {
     strainRate +=  (w(i, j, k) - w(i-1, j, k)) * dx_inv;
   }
   // At EdgeCenterJ
   if (k == 0)
       GradWz = 0.5  * dz_inv * ( w(i  ,j  ,k+1) + w(i-1,j  ,k+1) -w(i  ,j  ,k  ) - w(i-1,j  ,k  ) );
   else
       GradWz = 0.25 * dz_inv * ( w(i  ,j  ,k+1) + w(i-1,j  ,k+1) -w(i  ,j  ,k-1) - w(i-1,j  ,k-1) );
   strainRate += -(met_h_xi/met_h_zeta)*GradWz;
   strainRate *= 0.5;
   return strainRate;
 }
Referenced by ComputeS31WithTerrain(), ComputeSmnSmnWithTerrain(), and ComputeStrainRateWithTerrain().
ComputeS21()
AMREX_GPU_DEVICE amrex::Real ComputeS21 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     return ComputeS12(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
 }
Referenced by ComputeStrainRate().
ComputeS21WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS21WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & met_h_xi, const amrex::Real & met_h_eta, const amrex::Real & met_h_zeta, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
   return ComputeS12WithTerrain(i,j,k,u,v,w,cellSizeInv,
             met_h_xi,met_h_eta,met_h_zeta,domain,bc_ptr);
 }
Referenced by ComputeStrainRateWithTerrain().
ComputeS22()
AMREX_GPU_DEVICE amrex::Real ComputeS22 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & v, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv) inline
 {
   amrex::Real dy_inv = cellSizeInv[1];
   return (v(i, j, k) - v(i, j-1, k))*dy_inv;
 }
Referenced by ComputeSmnSmn(), and ComputeStrainRate().
ComputeS22WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS22WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & v, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & , const amrex::Real & met_h_eta, const amrex::Real & met_h_zeta) inline
 {
   amrex::Real GradVz;
   amrex::Real strainRate = 0;
   amrex::Real dy_inv = cellSizeInv[1];
   amrex::Real dz_inv = cellSizeInv[2];
   // At cell center
   GradVz = 0.25 * dz_inv *
     ( v(i  ,j  ,k+1) + v(i  ,j-1,k+1)
      -v(i  ,j  ,k-1) - v(i  ,j-1,k-1) );
   strainRate = (v(i, j, k) - v(i, j-1, k)) * dy_inv
              - (met_h_eta/met_h_zeta) * GradVz;
   return strainRate;
 }
Referenced by ComputeSmnSmnWithTerrain(), and ComputeStrainRateWithTerrain().
ComputeS23()
AMREX_GPU_DEVICE amrex::Real ComputeS23 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & , const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     amrex::Real dy_inv = cellSizeInv[1];
     amrex::Real dz_inv = cellSizeInv[2];
     amrex::Real strainRate;
     if (k == domain.smallEnd(2) && is_on_face(bc_ptr[BCVars::yvel_bc].lo(2))) {
         strainRate =  (-(8./3.) * v(i,j,k-1) + 3. * v(i,j,k  ) - (1./3.) * v(i,j,k+1))*dz_inv;
     } else if (k == domain.bigEnd(2)+1 && is_on_face(bc_ptr[BCVars::yvel_bc].hi(2))) {
         strainRate = -(-(8./3.) * v(i,j,k  ) + 3. * v(i,j,k-1) - (1./3.) * v(i,j,k-2))*dz_inv;
     } else {
         strainRate = (v(i, j, k) - v(i, j, k-1))*dz_inv;
     }
     if (j == domain.smallEnd(1) && is_on_face(bc_ptr[BCVars::zvel_bc].lo(1))) {
         strainRate +=  (-(8./3.) * w(i,j-1,k) + 3. * w(i,j  ,k) - (1./3.) * w(i,j+1,k))*dy_inv;
     } else if (j == domain.bigEnd(1)+1 && is_on_face(bc_ptr[BCVars::zvel_bc].hi(1))) {
         strainRate += -(-(8./3.) * w(i,j  ,k) + 3. * w(i,j-1,k) - (1./3.) * w(i,j-2,k))*dy_inv;
     } else {
         if (k > domain.smallEnd(2) && k <= domain.bigEnd(2)+1)
             strainRate += (w(i, j, k) - w(i, j-1, k))*dy_inv;
     }
     strainRate *= 0.5;
     return strainRate;
 }
Referenced by ComputeS32(), ComputeSmnSmn(), and ComputeStrainRate().
ComputeS23WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS23WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & , const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & , const amrex::Real & met_h_eta, const amrex::Real & met_h_zeta, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
   amrex::Real GradWz;
   amrex::Real strainRate = 0;
   amrex::Real dy_inv = cellSizeInv[1];
   amrex::Real dz_inv = cellSizeInv[2];
   if (k == domain.smallEnd(2) && is_on_face(bc_ptr[BCVars::yvel_bc].lo(2))) {
     strainRate  =  (-(8./3.) * v(i,j,k-1) + 3. * v(i,j,k  ) -
                      (1./3.) * v(i,j,k+1)) * dz_inv / met_h_zeta;
   } else if (k == domain.bigEnd(2)+1 && is_on_face(bc_ptr[BCVars::yvel_bc].hi(2))) {
     strainRate  = -(-(8./3.) * v(i,j,k  ) + 3. * v(i,j,k-1) -
                      (1./3.) * v(i,j,k-2)) * dz_inv / met_h_zeta;
   } else {
     strainRate  =  (v(i, j, k) - v(i, j, k-1)) * dz_inv / met_h_zeta;
   }
   if (j == domain.smallEnd(1) && is_on_face(bc_ptr[BCVars::zvel_bc].lo(1))) {
     strainRate +=  (-(8./3.) * w(i,j-1,k) + 3. * w(i,j  ,k) - (1./3.) * w(i,j+1,k))*dy_inv;
   } else if (j == domain.bigEnd(1)+1 && is_on_face(bc_ptr[BCVars::zvel_bc].hi(1))) {
     strainRate += -(-(8./3.) * w(i,j  ,k) + 3. * w(i,j-1,k) - (1./3.) * w(i,j-2,k))*dy_inv;
   } else {
     strainRate +=  (w(i, j, k) - w(i, j-1, k)) * dy_inv;
   }
   // At EdgeCenterI
   if (k == 0)
       GradWz = 0.5  * dz_inv * ( w(i  ,j  ,k+1) + w(i  ,j-1,k+1) -w(i  ,j  ,k  ) - w(i  ,j-1,k  ) );
   else
       GradWz = 0.25 * dz_inv * ( w(i  ,j  ,k+1) + w(i  ,j-1,k+1) -w(i  ,j  ,k-1) - w(i  ,j-1,k-1) );
   strainRate += -(met_h_eta/met_h_zeta)*GradWz;
   strainRate *= 0.5;
   return strainRate;
 }
Referenced by ComputeS32WithTerrain(), ComputeSmnSmnWithTerrain(), and ComputeStrainRateWithTerrain().
ComputeS31()
AMREX_GPU_DEVICE amrex::Real ComputeS31 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     return ComputeS13(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
 }
Referenced by ComputeStrainRate().
ComputeS31WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS31WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & met_h_xi, const amrex::Real & met_h_eta, const amrex::Real & met_h_zeta, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
  return ComputeS13WithTerrain(i,j,k,u,v,w,cellSizeInv,
             met_h_xi,met_h_eta,met_h_zeta,domain,bc_ptr);
 }
Referenced by ComputeStrainRateWithTerrain().
ComputeS32()
AMREX_GPU_DEVICE amrex::Real ComputeS32 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     return ComputeS23(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
 }
Referenced by ComputeStrainRate().
ComputeS32WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS32WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & met_h_xi, const amrex::Real & met_h_eta, const amrex::Real & met_h_zeta, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
   return ComputeS23WithTerrain(i,j,k,u,v,w,cellSizeInv,
             met_h_xi,met_h_eta,met_h_zeta,domain,bc_ptr);
 }
Referenced by ComputeStrainRateWithTerrain().
ComputeS33()
AMREX_GPU_DEVICE amrex::Real ComputeS33 (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain) inline
 {
   amrex::Real dz_inv = cellSizeInv[2];
   if (k > domain.smallEnd(2) && k <= domain.bigEnd(2)+1)
       return (w(i, j, k) - w(i, j, k-1))*dz_inv;
   else
       return 0.;
 }
Referenced by ComputeSmnSmn(), and ComputeStrainRate().
ComputeS33WithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeS33WithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & w, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Real & , const amrex::Real & , const amrex::Real & met_h_zeta, const amrex::Box & domain) inline
 {
   amrex::Real strainRate = 0;
   amrex::Real dz_inv = cellSizeInv[2];
   if (k > domain.smallEnd(2) && k <= domain.bigEnd(2)+1)
       strainRate = ( w(i, j, k) - w(i, j, k-1) ) * dz_inv / met_h_zeta ;
   else
       strainRate = 0.;
   return strainRate;
 }
Referenced by ComputeSmnSmnWithTerrain(), and ComputeStrainRateWithTerrain().
ComputeStrainRate()
AMREX_GPU_DEVICE amrex::Real ComputeStrainRate (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
     amrex::Real strainRate;
     switch (momentumEqn) {
       case MomentumEqn::x:
         switch (diffDir) {
           case DiffusionDir::x: // S11
             strainRate = ComputeS11(i,j,k,u,cellSizeInv);
             break;
           case DiffusionDir::y: // S12
             strainRate = ComputeS12(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
             break;
           case DiffusionDir::z: // S13
              strainRate = ComputeS13(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
              break;
           default:
              amrex::Abort("Error: Diffusion direction is unrecognized");
           }
           break;
       case MomentumEqn::y:
         switch (diffDir) {
           case DiffusionDir::x: // S21
             strainRate = ComputeS21(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
             break;
           case DiffusionDir::y: // S22
             strainRate = ComputeS22(i,j,k,v,cellSizeInv);
             break;
           case DiffusionDir::z: // S23
             strainRate = ComputeS23(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
             break;
           default:
             amrex::Abort("Error: Diffusion direction is unrecognized");
         }
         break;
       case MomentumEqn::z:
         switch (diffDir) {
           case DiffusionDir::x: // S31
             strainRate = ComputeS31(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
             break;
           case DiffusionDir::y: // S32
             strainRate = ComputeS32(i,j,k,u,v,w,cellSizeInv,domain,bc_ptr);
             break;
           case DiffusionDir::z: // S33
             strainRate = ComputeS33(i,j,k,w,cellSizeInv,domain);
             break;
           default:
             amrex::Abort("Error: Diffusion direction is unrecognized");
         }
         break;
       default:
           amrex::Abort("Error: Momentum equation is unrecognized");
   }
   return strainRate;
 }
Referenced by ComputeStressTerm(), and ComputeStressTermWithTerrain().
ComputeStrainRateWithTerrain()
AMREX_GPU_DEVICE amrex::Real ComputeStrainRateWithTerrain (const int & i, const int & j, const int & k, const amrex::Array4< amrex::Real const > & u, const amrex::Array4< amrex::Real const > & v, const amrex::Array4< amrex::Real const > & w, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const amrex::Box & domain, const amrex::BCRec * bc_ptr) inline
 {
   amrex::Real strainRate;
   amrex::Real met_h_xi,met_h_eta,met_h_zeta;
   switch (momentumEqn) {
   case MomentumEqn::x:
     switch (diffDir) {
     case DiffusionDir::x: // S11
       // Cell-Center is staggered
       ComputeMetricAtCellCenter(i-1,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                 cellSizeInv,z_nd,TerrainMet::h_xi_zeta);
       strainRate = ComputeS11WithTerrain(i,j,k,u,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta);
       break;
     case DiffusionDir::y: // S12
       ComputeMetricAtEdgeCenterK(i,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                  cellSizeInv,z_nd,TerrainMet::all);
       strainRate = ComputeS12WithTerrain(i,j,k,u,v,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,
                               domain,bc_ptr);
       break;
     case DiffusionDir::z: // S13
       ComputeMetricAtEdgeCenterJ(i,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                  cellSizeInv,z_nd,TerrainMet::h_xi_zeta);
       strainRate = ComputeS13WithTerrain(i,j,k,u,v,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,
                               domain,bc_ptr);
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::y:
     switch (diffDir) {
     case DiffusionDir::x: // S21
       ComputeMetricAtEdgeCenterK(i,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                  cellSizeInv,z_nd,TerrainMet::all);
       strainRate = ComputeS21WithTerrain(i,j,k,u,v,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,
                               domain,bc_ptr);
       break;
     case DiffusionDir::y: // S22
       // Cell-Center is staggered
       ComputeMetricAtCellCenter(i,j-1,k,met_h_xi,met_h_eta,met_h_zeta,
                                 cellSizeInv,z_nd,TerrainMet::h_eta_zeta);
       strainRate = ComputeS22WithTerrain(i,j,k,v,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta);
       break;
     case DiffusionDir::z: // S23
       ComputeMetricAtEdgeCenterI(i,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                  cellSizeInv,z_nd,TerrainMet::h_eta_zeta);
       strainRate = ComputeS23WithTerrain(i,j,k,u,v,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,
                               domain,bc_ptr);
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::z:
     switch (diffDir) {
     case DiffusionDir::x: // S31
       ComputeMetricAtEdgeCenterJ(i,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                  cellSizeInv,z_nd,TerrainMet::h_xi_zeta);
       strainRate = ComputeS31WithTerrain(i,j,k,u,v,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,
                               domain,bc_ptr);
       break;
     case DiffusionDir::y: // S32
       ComputeMetricAtEdgeCenterI(i,j,k,met_h_xi,met_h_eta,met_h_zeta,
                                  cellSizeInv,z_nd,TerrainMet::h_eta_zeta);
       strainRate = ComputeS32WithTerrain(i,j,k,u,v,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,
                               domain,bc_ptr);
       break;
     case DiffusionDir::z: // S33
       // Cell-Center is staggered
       ComputeMetricAtCellCenter(i,j,k-1,met_h_xi,met_h_eta,met_h_zeta,
                                 cellSizeInv,z_nd,TerrainMet::h_zeta);
       strainRate = ComputeS33WithTerrain(i,j,k,w,cellSizeInv,
                               met_h_xi,met_h_eta,met_h_zeta,domain);
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   default:
     amrex::Abort("Error: Momentum equation is unrecognized");
   }
   return strainRate;
 }
Referenced by ComputeStressTermWithTerrain().
is_on_face()
AMREX_GPU_DEVICE bool is_on_face (int bc_in) inline
 {
     if ( (bc_in == ERFBCType::ext_dir) || (bc_in == ERFBCType::ext_dir_ingested) ) {
         return true;
     } else {
         return false;
     }
 }
Referenced by ComputeS12(), ComputeS12WithTerrain(), ComputeS13(), ComputeS13WithTerrain(), ComputeS23(), and ComputeS23WithTerrain().