ERF: WENO_MZQ3 Struct Reference
WENO_MZQ3 Struct Reference
#include <Interpolation_WENO_Z.H>
Public Member Functions
WENO_MZQ3 (const amrex::Array4< const amrex::Real > &phi)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInX (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real &val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInY (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real &val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_lo (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_hi (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real upw_hi) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real Evaluate (const amrex::Real &sm1, const amrex::Real &s, const amrex::Real &sp1) const
Private Attributes
amrex::Array4< const amrex::Real > m_phi
const amrex::Real eps =1.0e-6
const amrex::Real tol =1.0e-12
Static Private Attributes
static constexpr amrex::Real g1 =(1.0/3.0)
static constexpr amrex::Real g2 =(2.0/3.0)
Detailed Description
Interpolation operators used for WENO_MZQ3 scheme
Constructor & Destructor Documentation
WENO_MZQ3()
WENO_MZQ3::WENO_MZQ3 (const amrex::Array4< const amrex::Real > & phi) inline
         : m_phi(phi) {}
Member Function Documentation
Evaluate()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WENO_MZQ3::Evaluate (const amrex::Real & sm1, const amrex::Real & s, const amrex::Real & sp1) const inline
     {
         // Smoothing factors
         amrex::Real b1 = (s - sm1) * (s - sm1);
         amrex::Real b2 = (sp1 - s) * (sp1 - s);
         // Weight factors
         amrex::Real t5 = std::abs(b2 - b1);
         amrex::Real w1 = g1 * ( 1.0 + (t5*t5) / ((eps + b1) * (eps + b1)) );
         amrex::Real w2 = g2 * ( 1.0 + (t5*t5) / ((eps + b2) * (eps + b2)) );
         // Weight factor norm
         amrex::Real wsum = w1 + w2;
         // Taylor expansions
         amrex::Real v1 = -sm1 + 3.0 * s;
         amrex::Real v2 =  s   + sp1;
         // Interpolated value
         return ( (w1 * v1 + w2 * v2) / (2.0 * wsum) );
     }
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
InterpolateInX()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_MZQ3::InterpolateInX (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real & val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i+2, j  , k  , qty_index);
         amrex::Real sp1 = m_phi(i+1, j  , k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i-1, j  , k  , qty_index);
         amrex::Real sm2 = m_phi(i-2, j  , k  , qty_index);
         if (upw_hi > tol){
             val_hi = Evaluate(sm1,s  ,sp1);
         } else if (upw_hi < -tol) {
             val_hi = Evaluate(sp2,sp1,s  );
         } else {
             val_hi = 0.5 * (s + sp1);
         }
         if (upw_lo > tol) {
             val_lo = Evaluate(sm2,sm1,s  );
         } else if (upw_lo < -tol) {
             val_lo = Evaluate(sp1,s  ,sm1);
         } else {
             val_lo = 0.5 * (s + sm1);
         }
     }
InterpolateInY()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_MZQ3::InterpolateInY (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real & val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i  , j+2, k  , qty_index);
         amrex::Real sp1 = m_phi(i  , j+1, k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j-1, k  , qty_index);
         amrex::Real sm2 = m_phi(i  , j-2, k  , qty_index);
         if (upw_hi > tol){
             val_hi = Evaluate(sm1,s  ,sp1);
         } else if (upw_hi < -tol) {
             val_hi = Evaluate(sp2,sp1,s  );
         } else {
             val_hi = 0.5 * (s + sp1);
         }
         if (upw_lo > tol) {
             val_lo = Evaluate(sm2,sm1,s  );
         } else if (upw_lo < -tol) {
             val_lo = Evaluate(sp1,s  ,sm1);
         } else {
             val_lo = 0.5 * (s + sm1);
         }
     }
InterpolateInZ_hi()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_MZQ3::InterpolateInZ_hi (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real upw_hi) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i  , j  , k+2, qty_index);
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         if (upw_hi > tol){
             val_hi = Evaluate(sm1,s  ,sp1);
         } else if (upw_hi < -tol) {
             val_hi = Evaluate(sp2,sp1,s  );
         } else {
             val_hi = 0.5 * (s + sp1);
         }
     }
InterpolateInZ_lo()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_MZQ3::InterpolateInZ_lo (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
         if (upw_lo > tol) {
             val_lo = Evaluate(sm2,sm1,s  );
         } else if (upw_lo < -tol) {
             val_lo = Evaluate(sp1,s  ,sm1);
         } else {
             val_lo = 0.5 * (s + sm1);
         }
     }
Member Data Documentation
eps
const amrex::Real WENO_MZQ3::eps =1.0e-6 private
Referenced by Evaluate().
g1
constexpr amrex::Real WENO_MZQ3::g1 =(1.0/3.0) static constexpr private
Referenced by Evaluate().
g2
constexpr amrex::Real WENO_MZQ3::g2 =(2.0/3.0) static constexpr private
Referenced by Evaluate().
m_phi
amrex::Array4<const amrex::Real> WENO_MZQ3::m_phi private
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
tol
const amrex::Real WENO_MZQ3::tol =1.0e-12 private
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
The documentation for this struct was generated from the following file:
Source/Utils/Interpolation_WENO_Z.H