ERF: UPWINDALL Struct Reference
UPWINDALL Struct Reference
#include <Interpolation_UPW.H>
Public Member Functions
UPWINDALL (const amrex::Array4< const amrex::Real > &phi)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_lo (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo, const int &spatial_order) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_hi (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real upw_hi, const int &spatial_order) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real Evaluate (const amrex::Real &sp2, const amrex::Real &sp1, const amrex::Real &s, const amrex::Real &sm1, const amrex::Real &sm2, const amrex::Real &sm3, const amrex::Real &upw, const int &spatial_order) const
Private Attributes
amrex::Array4< const amrex::Real > m_phi
Static Private Attributes
static constexpr amrex::Real g1_3_4 =(7.0/12.0)
static constexpr amrex::Real g2_3_4 =(1.0/12.0)
static constexpr amrex::Real g1_5_6 =(37.0/60.0)
static constexpr amrex::Real g2_5_6 =(2.0/15.0)
static constexpr amrex::Real g3_5_6 =(1.0/60.0)
Detailed Description
Interpolation operators used for all central/upwind schemes
Constructor & Destructor Documentation
UPWINDALL()
UPWINDALL::UPWINDALL (const amrex::Array4< const amrex::Real > & phi) inline
         : m_phi(phi) {}
Member Function Documentation
Evaluate()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real UPWINDALL::Evaluate (const amrex::Real & sp2, const amrex::Real & sp1, const amrex::Real & s, const amrex::Real & sm1, const amrex::Real & sm2, const amrex::Real & sm3, const amrex::Real & upw, const int & spatial_order) const inline
     {
         // Averages and diffs
         amrex::Real a1 = (s   + sm1);
         amrex::Real a2 = (sp1 + sm2);
         amrex::Real d1 = (s   - sm1);
         amrex::Real d2 = (sp1 - sm2);
         amrex::Real a3 = (sp2 + sm3);
         amrex::Real d3 = (sp2 - sm3);
         // Interpolated value
         amrex::Real iv;
         switch (spatial_order) {
         case 2:
             iv = 0.5 * a1;
             break;
         case 3:
             iv = g1_3_4*a1 - g2_3_4*a2 + upw * g2_3_4 * (d2 - 3.0*d1);
             break;
         case 4:
             iv = g1_3_4*a1 - g2_3_4*a2;
             break;
         case 5:
             iv = g1_5_6*a1 - g2_5_6*a2 + g3_5_6*a3 - upw * g3_5_6 * (d3 - 5.0*d2 + 10.0*d1);
             break;
         case 6:
             iv = g1_5_6*a1 - g2_5_6*a2 + g3_5_6*a3;
             break;
         }
         return ( iv );
     }
Referenced by InterpolateInZ_hi(), and InterpolateInZ_lo().
InterpolateInZ_hi()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWINDALL::InterpolateInZ_hi (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real upw_hi, const int & spatial_order) const inline
     {
         if (spatial_order == 2) {
             val_hi = 0.5 * ( m_phi(i,j,k,qty_index) + m_phi(i,j,k+1,qty_index) );
             return;
         } else {
             // Data to interpolate on
             amrex::Real sp3 = (spatial_order > 4) ? m_phi(i  , j  , k+3, qty_index): 0.;
             amrex::Real sp2 = m_phi(i  , j  , k+2, qty_index);
             amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
             amrex::Real s   = m_phi(i  , j  , k  , qty_index);
             amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
             amrex::Real sm2 = (spatial_order > 4) ? m_phi(i  , j  , k-2, qty_index) : 0.;
             // Upwinding flags
             if (upw_hi != 0.) upw_hi = (upw_hi > 0) ? 1. : -1.;
             // Interpolate hi
             val_hi = Evaluate(sp3,sp2,sp1,s,sm1,sm2,upw_hi,spatial_order);
         }
     }
InterpolateInZ_lo()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWINDALL::InterpolateInZ_lo (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo, const int & spatial_order) const inline
     {
         if (spatial_order == 2) {
             val_lo = 0.5 * ( m_phi(i,j,k,qty_index) + m_phi(i,j,k-1,qty_index) );
             return;
         } else {
             // Data to interpolate on
             amrex::Real sp2 = (spatial_order > 4) ? m_phi(i  , j  , k+2, qty_index): 0.;
             amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
             amrex::Real s   = m_phi(i  , j  , k  , qty_index);
             amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
             amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
             amrex::Real sm3 = (spatial_order > 4) ? m_phi(i  , j  , k-3, qty_index) : 0.;
             // Upwinding flags
             if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
             // Interpolate lo
             val_lo = Evaluate(sp2,sp1,s,sm1,sm2,sm3,upw_lo,spatial_order);
         }
     }
Member Data Documentation
g1_3_4
constexpr amrex::Real UPWINDALL::g1_3_4 =(7.0/12.0) static constexpr private
Referenced by Evaluate().
g1_5_6
constexpr amrex::Real UPWINDALL::g1_5_6 =(37.0/60.0) static constexpr private
Referenced by Evaluate().
g2_3_4
constexpr amrex::Real UPWINDALL::g2_3_4 =(1.0/12.0) static constexpr private
Referenced by Evaluate().
g2_5_6
constexpr amrex::Real UPWINDALL::g2_5_6 =(2.0/15.0) static constexpr private
Referenced by Evaluate().
g3_5_6
constexpr amrex::Real UPWINDALL::g3_5_6 =(1.0/60.0) static constexpr private
Referenced by Evaluate().
m_phi
amrex::Array4<const amrex::Real> UPWINDALL::m_phi private
Referenced by InterpolateInZ_hi(), and InterpolateInZ_lo().
The documentation for this struct was generated from the following file:
Source/Utils/Interpolation_UPW.H