ERF: WENO_Z5 Struct Reference
WENO_Z5 Struct Reference
#include <Interpolation_WENO_Z.H>
Public Member Functions
WENO_Z5 (const amrex::Array4< const amrex::Real > &phi)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInX (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real &val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInY (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real &val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_lo (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_hi (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real upw_hi) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real Evaluate (const amrex::Real &sm2, const amrex::Real &sm1, const amrex::Real &s, const amrex::Real &sp1, const amrex::Real &sp2) const
Private Attributes
const amrex::Array4< const amrex::Real > & m_phi
const amrex::Real eps =1.0e-6
const amrex::Real tol =1.0e-12
Static Private Attributes
static constexpr amrex::Real c1 =(13.0/12.0)
static constexpr amrex::Real g1 =(1.0/10.0)
static constexpr amrex::Real g2 =(3.0/5.0)
static constexpr amrex::Real g3 =(3.0/10.0)
Detailed Description
Interpolation operators used for WENO_Z-5 scheme
Constructor & Destructor Documentation
WENO_Z5()
WENO_Z5::WENO_Z5 (const amrex::Array4< const amrex::Real > & phi) inline
         : m_phi(phi) {}
Member Function Documentation
Evaluate()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WENO_Z5::Evaluate (const amrex::Real & sm2, const amrex::Real & sm1, const amrex::Real & s, const amrex::Real & sp1, const amrex::Real & sp2) const inline
     {
         // Smoothing factors
         amrex::Real b1 = c1 * (sm2 - 2.0 * sm1 + s) * (sm2 - 2.0 * sm1 + s) +
                        0.25 * (sm2 - 4.0 * sm1 + 3.0 * s) * (sm2 - 4.0 * sm1 + 3.0 * s);
         amrex::Real b2 = c1 * (sm1 - 2.0 * s + sp1) * (sm1 - 2.0 * s + sp1) +
                        0.25 * (sm1 - sp1) * (sm1 - sp1);
         amrex::Real b3 = c1 * (s - 2.0 * sp1 + sp2) * (s - 2.0 * sp1 + sp2) +
                        0.25 * (3.0 * s - 4.0 * sp1 + sp2) * (3.0 * s - 4.0 * sp1 + sp2);
         // Weight factors
         amrex::Real t5 = std::abs(b3 - b1);
         amrex::Real w1 = g1 * ( 1.0 + (t5*t5) / ((eps + b1) * (eps + b1)) );
         amrex::Real w2 = g2 * ( 1.0 + (t5*t5) / ((eps + b2) * (eps + b2)) );
         amrex::Real w3 = g3 * ( 1.0 + (t5*t5) / ((eps + b3) * (eps + b3)) );
         // Weight factor norm
         amrex::Real wsum = w1 + w2 + w3;
         // Taylor expansions
         amrex::Real v1 = 2.0 * sm2 - 7.0 * sm1 + 11.0 * s;
         amrex::Real v2 = -sm1 + 5.0 * s + 2.0 * sp1;
         amrex::Real v3 = 2.0 * s + 5.0 * sp1 - sp2;
         // Interpolated value
         return ( (w1 * v1 + w2 * v2 + w3 * v3) / (6.0 * wsum) );
     }
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
InterpolateInX()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z5::InterpolateInX (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real & val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp3 = m_phi(i+3, j  , k  , qty_index);
         amrex::Real sp2 = m_phi(i+2, j  , k  , qty_index);
         amrex::Real sp1 = m_phi(i+1, j  , k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i-1, j  , k  , qty_index);
         amrex::Real sm2 = m_phi(i-2, j  , k  , qty_index);
         amrex::Real sm3 = m_phi(i-3, j  , k  , qty_index);
         if (upw_hi > tol){
             val_hi = Evaluate(sm2,sm1,s,sp1,sp2);
         } else if (upw_hi < -tol) {
             val_hi = Evaluate(sp3,sp2,sp1,s  ,sm1);
         } else {
             val_hi = 0.5 * (s + sp1);
         }
         if (upw_lo > tol) {
             val_lo = Evaluate(sm3,sm2,sm1,s  ,sp1);
         } else if (upw_lo < -tol) {
             val_lo = Evaluate(sp2,sp1,s,sm1,sm2);
         } else {
             val_lo = 0.5 * (s + sm1);
         }
     }
InterpolateInY()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z5::InterpolateInY (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real & val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp3 = m_phi(i  , j+3, k  , qty_index);
         amrex::Real sp2 = m_phi(i  , j+2, k  , qty_index);
         amrex::Real sp1 = m_phi(i  , j+1, k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j-1, k  , qty_index);
         amrex::Real sm2 = m_phi(i  , j-2, k  , qty_index);
         amrex::Real sm3 = m_phi(i  , j-3, k  , qty_index);
         if (upw_hi > tol){
             val_hi = Evaluate(sm2,sm1,s,sp1,sp2);
         } else if (upw_hi < -tol) {
             val_hi = Evaluate(sp3,sp2,sp1,s  ,sm1);
         } else {
             val_hi = 0.5 * (s + sp1);
         }
         if (upw_lo > tol) {
             val_lo = Evaluate(sm3,sm2,sm1,s  ,sp1);
         } else if (upw_lo < -tol) {
             val_lo = Evaluate(sp2,sp1,s,sm1,sm2);
         } else {
             val_lo = 0.5 * (s + sm1);
         }
     }
InterpolateInZ_hi()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z5::InterpolateInZ_hi (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real upw_hi) const inline
     {
         // Data to interpolate on
         amrex::Real sp3 = m_phi(i  , j  , k+3, qty_index);
         amrex::Real sp2 = m_phi(i  , j  , k+2, qty_index);
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
         if (upw_hi > tol){
             val_hi = Evaluate(sm2,sm1,s,sp1,sp2);
         } else if (upw_hi < -tol) {
             val_hi = Evaluate(sp3,sp2,sp1,s  ,sm1);
         } else {
             val_hi = 0.5 * (s + sp1);
         }
     }
InterpolateInZ_lo()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z5::InterpolateInZ_lo (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i  , j  , k+2, qty_index);
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
         amrex::Real sm3 = m_phi(i  , j  , k-3, qty_index);
         if (upw_lo > tol) {
             val_lo = Evaluate(sm3,sm2,sm1,s  ,sp1);
         } else if (upw_lo < -tol) {
             val_lo = Evaluate(sp2,sp1,s,sm1,sm2);
         } else {
             val_lo = 0.5 * (s + sm1);
         }
     }
Member Data Documentation
c1
constexpr amrex::Real WENO_Z5::c1 =(13.0/12.0) static constexpr private
Referenced by Evaluate().
eps
const amrex::Real WENO_Z5::eps =1.0e-6 private
Referenced by Evaluate().
g1
constexpr amrex::Real WENO_Z5::g1 =(1.0/10.0) static constexpr private
Referenced by Evaluate().
g2
constexpr amrex::Real WENO_Z5::g2 =(3.0/5.0) static constexpr private
Referenced by Evaluate().
g3
constexpr amrex::Real WENO_Z5::g3 =(3.0/10.0) static constexpr private
Referenced by Evaluate().
m_phi
const amrex::Array4<const amrex::Real>& WENO_Z5::m_phi private
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
tol
const amrex::Real WENO_Z5::tol =1.0e-12 private
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
The documentation for this struct was generated from the following file:
Source/Utils/Interpolation_WENO_Z.H