ERF: UPWIND3 Struct Reference
UPWIND3 Struct Reference
#include <Interpolation_UPW.H>
Public Member Functions
UPWIND3 (const amrex::Array4< const amrex::Real > &phi)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInX (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real &val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInY (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real &val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_lo (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ_hi (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_hi, amrex::Real upw_hi) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real Evaluate (const amrex::Real &sp1, const amrex::Real &s, const amrex::Real &sm1, const amrex::Real &sm2, const amrex::Real &upw) const
Private Attributes
const amrex::Array4< const amrex::Real > & m_phi
Static Private Attributes
static constexpr amrex::Real g1 =(7.0/12.0)
static constexpr amrex::Real g2 =(1.0/12.0)
Detailed Description
Interpolation operators used for 3rd order upwind scheme
Constructor & Destructor Documentation
UPWIND3()
UPWIND3::UPWIND3 (const amrex::Array4< const amrex::Real > & phi) inline
         : m_phi(phi) {}
Member Function Documentation
Evaluate()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real UPWIND3::Evaluate (const amrex::Real & sp1, const amrex::Real & s, const amrex::Real & sm1, const amrex::Real & sm2, const amrex::Real & upw) const inline
     {
         // Averages and diffs
         amrex::Real a1 = (s   + sm1);
         amrex::Real d1 = (s   - sm1);
         amrex::Real a2 = (sp1 + sm2);
         amrex::Real d2 = (sp1 - sm2);
         // Interpolated value
         return ( g1*a1 - g2*a2 + upw * g2 * (d2 - 3.0*d1) );
     }
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
InterpolateInX()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3::InterpolateInX (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real & val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i+2, j  , k  , qty_index);
         amrex::Real sp1 = m_phi(i+1, j  , k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i-1, j  , k  , qty_index);
         amrex::Real sm2 = m_phi(i-2, j  , k  , qty_index);
         // Upwinding flags
         if (upw_hi != 0.) upw_hi = (upw_hi > 0) ? 1. : -1.;
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Interpolate hi
         val_hi = Evaluate(sp2,sp1,s,sm1,upw_hi);
         // Interpolate lo
         val_lo = Evaluate(sp1,s,sm1,sm2,upw_lo);
     }
InterpolateInY()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3::InterpolateInY (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real & val_lo, amrex::Real upw_hi, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i  , j+2, k  , qty_index);
         amrex::Real sp1 = m_phi(i  , j+1, k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j-1, k  , qty_index);
         amrex::Real sm2 = m_phi(i  , j-2, k  , qty_index);
         // Upwinding flags
         if (upw_hi != 0.) upw_hi = (upw_hi > 0) ? 1. : -1.;
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Interpolate hi
         val_hi = Evaluate(sp2,sp1,s,sm1,upw_hi);
         // Interpolate lo
         val_lo = Evaluate(sp1,s,sm1,sm2,upw_lo);
     }
InterpolateInZ_hi()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3::InterpolateInZ_hi (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_hi, amrex::Real upw_hi) const inline
     {
         // Data to interpolate on
         amrex::Real sp2 = m_phi(i  , j  , k+2, qty_index);
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         // Upwinding flags
         if (upw_hi != 0.) upw_hi = (upw_hi > 0) ? 1. : -1.;
         // Interpolate lo
         val_hi = Evaluate(sp2,sp1,s,sm1,upw_hi);
     }
InterpolateInZ_lo()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3::InterpolateInZ_lo (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Data to interpolate on
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Interpolate lo
         val_lo = Evaluate(sp1,s,sm1,sm2,upw_lo);
     }
Member Data Documentation
g1
constexpr amrex::Real UPWIND3::g1 =(7.0/12.0) static constexpr private
Referenced by Evaluate().
g2
constexpr amrex::Real UPWIND3::g2 =(1.0/12.0) static constexpr private
Referenced by Evaluate().
m_phi
const amrex::Array4<const amrex::Real>& UPWIND3::m_phi private
Referenced by InterpolateInX(), InterpolateInY(), InterpolateInZ_hi(), and InterpolateInZ_lo().
The documentation for this struct was generated from the following file:
Source/Utils/Interpolation_UPW.H