ERF: moeng_flux_eb Struct Reference
moeng_flux_eb Struct Reference
#include <ERF_EBMOSTStress.H>
Public Member Functions
moeng_flux_eb ()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_q_flux (const int &i, const int &j, const int &k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &umm_arr, const amrex::Array4< const amrex::Real > &qvm_arr, const amrex::Array4< const amrex::Real > &u_star_arr, const amrex::Array4< const amrex::Real > &q_star_arr, const amrex::Array4< const amrex::Real > &q_surf_arr, const amrex::Array4< const amrex::Real > &u_vfrac_arr, const amrex::Array4< const amrex::Real > &v_vfrac_arr) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_t_flux (const int &i, const int &j, const int &k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &velz_arr, const amrex::Array4< const amrex::Real > &umm_arr, const amrex::Array4< const amrex::Real > &tm_arr, const amrex::Array4< const amrex::Real > &u_star_arr, const amrex::Array4< const amrex::Real > &t_star_arr, const amrex::Array4< const amrex::Real > &t_surf_arr, const amrex::Array4< const amrex::Real > &u_vfrac_arr, const amrex::Array4< const amrex::Real > &v_vfrac_arr, const amrex::Array4< const amrex::Real > &w_vfrac_arr, const amrex::Array4< const amrex::Real > &bnorm_arr) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_u_flux (int i, int j, int k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &velz_arr, const amrex::Array4< const amrex::Real > &umm_arr, const amrex::Array4< const amrex::Real > &um_arr, const amrex::Array4< const amrex::Real > &u_star_arr, const amrex::Array4< const amrex::Real > &u_vfrac_arr, const amrex::Array4< const amrex::Real > &v_vfrac_arr, const amrex::Array4< const amrex::Real > &w_vfrac_arr, const amrex::Array4< const amrex::Real > &cc_vfrac_arr, const amrex::Array4< const amrex::EBCellFlag > &cc_flag_arr, const amrex::Array4< const amrex::Real > &bnorm_arr, int idir=0) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_v_flux (int i, int j, int k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &velz_arr, const amrex::Array4< const amrex::Real > &umm_arr, const amrex::Array4< const amrex::Real > &vm_arr, const amrex::Array4< const amrex::Real > &u_star_arr, const amrex::Array4< const amrex::Real > &u_vfrac_arr, const amrex::Array4< const amrex::Real > &v_vfrac_arr, const amrex::Array4< const amrex::Real > &w_vfrac_arr, const amrex::Array4< const amrex::Real > &cc_vfrac_arr, const amrex::Array4< const amrex::EBCellFlag > &cc_flag_arr, const amrex::Array4< const amrex::Real > &bnorm_arr, int idir=0) const
Private Attributes
const amrex::Real eps = amrex::Real(1e-12)
const amrex::Real WSMIN = amrex::Real(0.1)
Detailed Description
Moeng flux formulation
Constructor & Destructor Documentation
moeng_flux_eb()
moeng_flux_eb::moeng_flux_eb () inline
 {}
Member Function Documentation
compute_q_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real moeng_flux_eb::compute_q_flux (const int & i, const int & j, const int & k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & umm_arr, const amrex::Array4< const amrex::Real > & qvm_arr, const amrex::Array4< const amrex::Real > & u_star_arr, const amrex::Array4< const amrex::Real > & q_star_arr, const amrex::Array4< const amrex::Real > & q_surf_arr, const amrex::Array4< const amrex::Real > & u_vfrac_arr, const amrex::Array4< const amrex::Real > & v_vfrac_arr) const inline
     {
         amrex::Real rho   = cons_arr(i,j,k,Rho_comp);
         amrex::Real qv    = cons_arr(i,j,k,RhoQ1_comp) / rho;
         // Volume-weighted average of x-face velocities to cell center
         amrex::Real u_vfrac_sum = u_vfrac_arr(i,j,k) + u_vfrac_arr(i+1,j,k);
         amrex::Real velx = (u_vfrac_sum > eps) ?
             (velx_arr(i,j,k) * u_vfrac_arr(i,j,k) + velx_arr(i+1,j,k) * u_vfrac_arr(i+1,j,k))
             / u_vfrac_sum : zero;
         // Volume-weighted average of y-face velocities to cell center
         amrex::Real v_vfrac_sum = v_vfrac_arr(i,j,k) + v_vfrac_arr(i,j+1,k);
         amrex::Real vely = (v_vfrac_sum > eps) ?
             (vely_arr(i,j,k) * v_vfrac_arr(i,j,k) + vely_arr(i,j+1,k) * v_vfrac_arr(i,j+1,k))
             / v_vfrac_sum : zero;
         amrex::Real qv_mean  = qvm_arr(i,j,0);
         amrex::Real ustar    = u_star_arr(i,j,k);
         amrex::Real qstar    = q_star_arr(i,j,k);
         amrex::Real qv_surf  = q_surf_arr(i,j,k);
         amrex::Real wsp_mean = umm_arr(i,j,0);
         wsp_mean = std::max(wsp_mean, WSMIN);
         amrex::Real wsp     = std::sqrt(velx*velx+vely*vely);
         amrex::Real num1    = wsp * (qv_mean-qv_surf);
         amrex::Real num2    = wsp_mean * (qv-qv_mean);
         // NOTE: this is rho*<Qv'w'> = -K dQvdz
         amrex::Real moflux  = (std::abs(qstar) > eps) ?
                               -rho*qstar*ustar*(num1+num2)/((qv_mean-qv_surf)*wsp_mean) : zero;
         return moflux;
     }
compute_t_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real moeng_flux_eb::compute_t_flux (const int & i, const int & j, const int & k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & velz_arr, const amrex::Array4< const amrex::Real > & umm_arr, const amrex::Array4< const amrex::Real > & tm_arr, const amrex::Array4< const amrex::Real > & u_star_arr, const amrex::Array4< const amrex::Real > & t_star_arr, const amrex::Array4< const amrex::Real > & t_surf_arr, const amrex::Array4< const amrex::Real > & u_vfrac_arr, const amrex::Array4< const amrex::Real > & v_vfrac_arr, const amrex::Array4< const amrex::Real > & w_vfrac_arr, const amrex::Array4< const amrex::Real > & bnorm_arr) const inline
     {
         amrex::Real rho   = cons_arr(i,j,k,Rho_comp);
         amrex::Real theta = cons_arr(i,j,k,RhoTheta_comp) / rho;
         // Volume-weighted average of x-face velocities to cell center
         amrex::Real u_vfrac_sum = u_vfrac_arr(i,j,k) + u_vfrac_arr(i+1,j,k);
         amrex::Real velx = (u_vfrac_sum > eps) ?
             (velx_arr(i,j,k) * u_vfrac_arr(i,j,k) + velx_arr(i+1,j,k) * u_vfrac_arr(i+1,j,k))
             / u_vfrac_sum : zero;
         // Volume-weighted average of y-face velocities to cell center
         amrex::Real v_vfrac_sum = v_vfrac_arr(i,j,k) + v_vfrac_arr(i,j+1,k);
         amrex::Real vely = (v_vfrac_sum > eps) ?
             (vely_arr(i,j,k) * v_vfrac_arr(i,j,k) + vely_arr(i,j+1,k) * v_vfrac_arr(i,j+1,k))
             / v_vfrac_sum : zero;
         // Volume-weighted average of z-face velocities to cell center
         amrex::Real w_vfrac_sum = w_vfrac_arr(i,j,k) + w_vfrac_arr(i,j,k+1);
         amrex::Real velz = (w_vfrac_sum > eps) ?
             (velz_arr(i,j,k) * w_vfrac_arr(i,j,k) + velz_arr(i,j,k+1) * w_vfrac_arr(i,j,k+1))
             / w_vfrac_sum : zero;
         // Get boundary normal components
         amrex::Real nx = bnorm_arr(i,j,k,0);
         amrex::Real ny = bnorm_arr(i,j,k,1);
         amrex::Real nz = bnorm_arr(i,j,k,2);
         // Project velocity onto tangent plane (remove normal component)
         amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
         amrex::Real velx_tangent = velx - v_dot_n * nx;
         amrex::Real vely_tangent = vely - v_dot_n * ny;
         amrex::Real theta_mean  = tm_arr(i,j,0);
         amrex::Real ustar       = u_star_arr(i,j,k);
         amrex::Real tstar       = t_star_arr(i,j,k);
         amrex::Real theta_surf  = t_surf_arr(i,j,k);
         amrex::Real wsp_mean    = umm_arr(i,j,0);
         wsp_mean = std::max(wsp_mean, WSMIN);
         // Use tangential velocity magnitude instead of Cartesian
         amrex::Real wsp     = std::sqrt(velx_tangent*velx_tangent+vely_tangent*vely_tangent);
         amrex::Real num1    = wsp * (theta_mean-theta_surf);
         amrex::Real num2    = wsp_mean * (theta-theta_mean);
         // NOTE: this is rho*<T'w'> = -K dTdz
         amrex::Real moflux  = (std::abs(tstar) > eps) ?
                               -rho*tstar*ustar*(num1+num2)/((theta_mean-theta_surf)*wsp_mean) : zero;
         return moflux;
     }
compute_u_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real moeng_flux_eb::compute_u_flux (int i, int j, int k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & velz_arr, const amrex::Array4< const amrex::Real > & umm_arr, const amrex::Array4< const amrex::Real > & um_arr, const amrex::Array4< const amrex::Real > & u_star_arr, const amrex::Array4< const amrex::Real > & u_vfrac_arr, const amrex::Array4< const amrex::Real > & v_vfrac_arr, const amrex::Array4< const amrex::Real > & w_vfrac_arr, const amrex::Array4< const amrex::Real > & cc_vfrac_arr, const amrex::Array4< const amrex::EBCellFlag > & cc_flag_arr, const amrex::Array4< const amrex::Real > & bnorm_arr, int idir = 0) const inline
     {
         amrex::Real velx, vely, rho, ustar, wsp_mean;
         amrex::Real velx_tangent, vely_tangent;
         if (idir == 0) {
             // x-face: average to x-face
             velx = velx_arr(i,j,k);
             // Volume-weighted average of y-face velocities to x-face
             amrex::Real v_vfrac_sum = v_vfrac_arr(i,j,k) + v_vfrac_arr(i,j+1,k) +
                                       v_vfrac_arr(i-1,j,k) + v_vfrac_arr(i-1,j+1,k);
             vely = (v_vfrac_sum > eps) ?
                 (vely_arr(i,j,k)   * v_vfrac_arr(i,j,k)   + vely_arr(i,j+1,k) * v_vfrac_arr(i,j+1,k) +
                  vely_arr(i-1,j,k) * v_vfrac_arr(i-1,j,k) + vely_arr(i-1,j+1,k) * v_vfrac_arr(i-1,j+1,k))
                  / v_vfrac_sum : zero;
             // Volume-weighted average of z-face velocities to x-face
             amrex::Real w_vfrac_sum = w_vfrac_arr(i,j,k) + w_vfrac_arr(i,j,k+1) +
                                       w_vfrac_arr(i-1,j,k) + w_vfrac_arr(i-1,j,k+1);
             amrex::Real velz = (w_vfrac_sum > eps) ?
                 (velz_arr(i,j,k)   * w_vfrac_arr(i,j,k)   + velz_arr(i,j,k+1)   * w_vfrac_arr(i,j,k+1) +
                  velz_arr(i-1,j,k) * w_vfrac_arr(i-1,j,k) + velz_arr(i-1,j,k+1) * w_vfrac_arr(i-1,j,k+1))
                  / w_vfrac_sum : zero;
             // Get boundary normal at x-face (already at correct staggered location)
             amrex::Real nx = bnorm_arr(i,j,k,0);
             amrex::Real ny = bnorm_arr(i,j,k,1);
             amrex::Real nz = bnorm_arr(i,j,k,2);
             // Project velocity onto tangent plane
             amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
             velx_tangent = velx - v_dot_n * nx;
             vely_tangent = vely - v_dot_n * ny;
             // Volume-weighted average of cell-centered density to x-face
             amrex::Real cc_vfrac_sum = cc_vfrac_arr(i-1,j,k) + cc_vfrac_arr(i,j,k);
             rho = (cc_vfrac_sum > eps) ?
                 (cons_arr(i-1,j,k,Rho_comp) * cc_vfrac_arr(i-1,j,k) + cons_arr(i,j,k,Rho_comp) * cc_vfrac_arr(i,j,k))
                 / cc_vfrac_sum : zero;
             // Average cell-centered u_star and wsp_mean to x-face, using only valid (SingleValued) cells
             bool low_valid  = cc_flag_arr(i-1,j,k).isSingleValued();
             bool high_valid = cc_flag_arr(i,j,k).isSingleValued();
             if (low_valid && high_valid) {
                 ustar    = myhalf * (u_star_arr(i-1,j,k) + u_star_arr(i,j,k));
                 wsp_mean = myhalf * (umm_arr(i-1,j,0) + umm_arr(i,j,0));
             } else if (low_valid) {
                 ustar    = u_star_arr(i-1,j,k);
                 wsp_mean = umm_arr(i-1,j,0);
             } else if (high_valid) {
                 ustar    = u_star_arr(i,j,k);
                 wsp_mean = umm_arr(i,j,0);
             } else {
                 ustar    = zero;
                 wsp_mean = WSMIN;
             }
         } else if (idir == 1) {
             // y-face: average to y-face
             vely = vely_arr(i,j,k);
             // Volume-weighted average of x-face velocities to y-face
             amrex::Real u_vfrac_sum = u_vfrac_arr(i,j,k) + u_vfrac_arr(i+1,j,k) +
                                       u_vfrac_arr(i,j-1,k) + u_vfrac_arr(i+1,j-1,k);
             velx = (u_vfrac_sum > eps) ?
                 (velx_arr(i,j,k)   * u_vfrac_arr(i,j,k)   + velx_arr(i+1,j,k)   * u_vfrac_arr(i+1,j,k) +
                  velx_arr(i,j-1,k) * u_vfrac_arr(i,j-1,k) + velx_arr(i+1,j-1,k) * u_vfrac_arr(i+1,j-1,k))
                  / u_vfrac_sum : zero;
             // Volume-weighted average of z-face velocities to y-face
             amrex::Real w_vfrac_sum = w_vfrac_arr(i,j,k) + w_vfrac_arr(i,j,k+1) +
                                       w_vfrac_arr(i,j-1,k) + w_vfrac_arr(i,j-1,k+1);
             amrex::Real velz = (w_vfrac_sum > eps) ?
                 (velz_arr(i,j,k)   * w_vfrac_arr(i,j,k)   + velz_arr(i,j,k+1)   * w_vfrac_arr(i,j,k+1) +
                  velz_arr(i,j-1,k) * w_vfrac_arr(i,j-1,k) + velz_arr(i,j-1,k+1) * w_vfrac_arr(i,j-1,k+1))
                  / w_vfrac_sum : zero;
             // Get boundary normal at y-face (already at correct staggered location)
             amrex::Real nx = bnorm_arr(i,j,k,0);
             amrex::Real ny = bnorm_arr(i,j,k,1);
             amrex::Real nz = bnorm_arr(i,j,k,2);
             // Project velocity onto tangent plane
             amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
             velx_tangent = velx - v_dot_n * nx;
             vely_tangent = vely - v_dot_n * ny;
             // Volume-weighted average of cell-centered density to y-face
             amrex::Real cc_vfrac_sum = cc_vfrac_arr(i,j-1,k) + cc_vfrac_arr(i,j,k);
             rho = (cc_vfrac_sum > eps) ?
                 (cons_arr(i,j-1,k,Rho_comp) * cc_vfrac_arr(i,j-1,k) + cons_arr(i,j,k,Rho_comp) * cc_vfrac_arr(i,j,k))
                 / cc_vfrac_sum : zero;
             // Average cell-centered u_star and wsp_mean to y-face, using only valid (SingleValued) cells
             bool low_valid  = cc_flag_arr(i,j-1,k).isSingleValued();
             bool high_valid = cc_flag_arr(i,j,k).isSingleValued();
             if (low_valid && high_valid) {
                 ustar    = myhalf * (u_star_arr(i,j-1,k) + u_star_arr(i,j,k));
                 wsp_mean = myhalf * (umm_arr(i,j-1,0) + umm_arr(i,j,0));
             } else if (low_valid) {
                 ustar    = u_star_arr(i,j-1,k);
                 wsp_mean = umm_arr(i,j-1,0);
             } else if (high_valid) {
                 ustar    = u_star_arr(i,j,k);
                 wsp_mean = umm_arr(i,j,0);
             } else {
                 ustar    = zero;
                 wsp_mean = WSMIN;
             }
         } else {
             // z-face: average to z-face
             // Volume-weighted average of x-face velocities to z-face
             amrex::Real u_vfrac_sum = u_vfrac_arr(i,j,k-1) + u_vfrac_arr(i+1,j,k-1) +
                                       u_vfrac_arr(i,j,k) + u_vfrac_arr(i+1,j,k);
             velx = (u_vfrac_sum > eps) ?
                 (velx_arr(i,j,k-1)   * u_vfrac_arr(i,j,k-1)   + velx_arr(i+1,j,k-1)   * u_vfrac_arr(i+1,j,k-1) +
                  velx_arr(i,j,k) * u_vfrac_arr(i,j,k) + velx_arr(i+1,j,k) * u_vfrac_arr(i+1,j,k))
                  / u_vfrac_sum : zero;
             // Volume-weighted average of y-face velocities to z-face
             amrex::Real v_vfrac_sum = v_vfrac_arr(i,j,k-1) + v_vfrac_arr(i,j+1,k-1) +
                                       v_vfrac_arr(i,j,k) + v_vfrac_arr(i,j+1,k);
             vely = (v_vfrac_sum > eps) ?
                 (vely_arr(i,j,k-1)   * v_vfrac_arr(i,j,k-1)   + vely_arr(i,j+1,k-1)   * v_vfrac_arr(i,j+1,k-1) +
                  vely_arr(i,j,k) * v_vfrac_arr(i,j,k) + vely_arr(i,j+1,k) * v_vfrac_arr(i,j+1,k))
                  / v_vfrac_sum : zero;
             // z-velocity is already at z-face
             amrex::Real velz = velz_arr(i,j,k);
             // Get boundary normal at z-face (already at correct staggered location)
             amrex::Real nx = bnorm_arr(i,j,k,0);
             amrex::Real ny = bnorm_arr(i,j,k,1);
             amrex::Real nz = bnorm_arr(i,j,k,2);
             // Project velocity onto tangent plane
             amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
             velx_tangent = velx - v_dot_n * nx;
             vely_tangent = vely - v_dot_n * ny;
             // Volume-weighted average of cell-centered density to z-face
             amrex::Real cc_vfrac_sum = cc_vfrac_arr(i,j,k-1) + cc_vfrac_arr(i,j,k);
             rho = (cc_vfrac_sum > eps) ?
                 (cons_arr(i,j,k-1,Rho_comp) * cc_vfrac_arr(i,j,k-1) + cons_arr(i,j,k,Rho_comp) * cc_vfrac_arr(i,j,k))
                 / cc_vfrac_sum : zero;
             // Average cell-centered u_star and wsp_mean to z-face, using only valid (SingleValued) cells
             bool low_valid  = cc_flag_arr(i,j,k-1).isSingleValued();
             bool high_valid = cc_flag_arr(i,j,k).isSingleValued();
             if (low_valid && high_valid) {
                 ustar    = myhalf * (u_star_arr(i,j,k-1) + u_star_arr(i,j,k));
                 wsp_mean = myhalf * (umm_arr(i,j,0) + umm_arr(i,j,0));
             } else if (low_valid) {
                 ustar    = u_star_arr(i,j,k-1);
                 wsp_mean = umm_arr(i,j,0);
             } else if (high_valid) {
                 ustar    = u_star_arr(i,j,k);
                 wsp_mean = umm_arr(i,j,0);
             } else {
                 ustar    = zero;
                 wsp_mean = WSMIN;
             }
         }
         wsp_mean = std::max(wsp_mean, WSMIN);
         amrex::Real umean = um_arr(i,j,0);
         // Note: The surface mean shear stress is decomposed into tau_xz by
         //       multiplying the modeled shear stress (rho*ustar^2) with
         //       a factor of umean/wsp_mean for directionality; this factor
         //       modifies the denominator from what is in Moeng amrex::Real(1984.)
         amrex::Real wsp     = std::sqrt(velx_tangent*velx_tangent+vely_tangent*vely_tangent);
         amrex::Real num1    = wsp * umean;
         amrex::Real num2    = wsp_mean * (velx_tangent-umean);
         // NOTE: this is rho*<u'w'> = -K dudz
         amrex::Real stressx = -rho*ustar*ustar * (num1+num2)/(wsp_mean*wsp_mean);
         return stressx;
     }
compute_v_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real moeng_flux_eb::compute_v_flux (int i, int j, int k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & velz_arr, const amrex::Array4< const amrex::Real > & umm_arr, const amrex::Array4< const amrex::Real > & vm_arr, const amrex::Array4< const amrex::Real > & u_star_arr, const amrex::Array4< const amrex::Real > & u_vfrac_arr, const amrex::Array4< const amrex::Real > & v_vfrac_arr, const amrex::Array4< const amrex::Real > & w_vfrac_arr, const amrex::Array4< const amrex::Real > & cc_vfrac_arr, const amrex::Array4< const amrex::EBCellFlag > & cc_flag_arr, const amrex::Array4< const amrex::Real > & bnorm_arr, int idir = 0) const inline
     {
         amrex::Real velx, vely, rho, ustar, wsp_mean;
         amrex::Real velx_tangent, vely_tangent;
         if (idir == 0) {
             // x-face: average from cells (i-1) and (i)
             // Volume-weighted average of y-face velocities to x-face
             amrex::Real v_vfrac_sum = v_vfrac_arr(i,j,k) + v_vfrac_arr(i,j+1,k) +
                                       v_vfrac_arr(i-1,j,k) + v_vfrac_arr(i-1,j+1,k);
             vely = (v_vfrac_sum > eps) ?
                 (vely_arr(i,j,k)   * v_vfrac_arr(i,j,k)   + vely_arr(i,j+1,k)   * v_vfrac_arr(i,j+1,k) +
                  vely_arr(i-1,j,k) * v_vfrac_arr(i-1,j,k) + vely_arr(i-1,j+1,k) * v_vfrac_arr(i-1,j+1,k))
                  / v_vfrac_sum : zero;
             velx = velx_arr(i,j,k);
             // Volume-weighted average of z-face velocities to x-face
             amrex::Real w_vfrac_sum = w_vfrac_arr(i,j,k) + w_vfrac_arr(i,j,k+1) +
                                       w_vfrac_arr(i-1,j,k) + w_vfrac_arr(i-1,j,k+1);
             amrex::Real velz = (w_vfrac_sum > eps) ?
                 (velz_arr(i,j,k)   * w_vfrac_arr(i,j,k)   + velz_arr(i,j,k+1)   * w_vfrac_arr(i,j,k+1) +
                  velz_arr(i-1,j,k) * w_vfrac_arr(i-1,j,k) + velz_arr(i-1,j,k+1) * w_vfrac_arr(i-1,j,k+1))
                  / w_vfrac_sum : zero;
             // Get boundary normal at x-face (already at correct staggered location)
             amrex::Real nx = bnorm_arr(i,j,k,0);
             amrex::Real ny = bnorm_arr(i,j,k,1);
             amrex::Real nz = bnorm_arr(i,j,k,2);
             // Project velocity onto tangent plane
             amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
             velx_tangent = velx - v_dot_n * nx;
             vely_tangent = vely - v_dot_n * ny;
             // Volume-weighted average of cell-centered density to x-face
             amrex::Real cc_vfrac_sum = cc_vfrac_arr(i-1,j,k) + cc_vfrac_arr(i,j,k);
             rho = (cc_vfrac_sum > eps) ?
                 (cons_arr(i-1,j,k,Rho_comp) * cc_vfrac_arr(i-1,j,k) + cons_arr(i,j,k,Rho_comp) * cc_vfrac_arr(i,j,k))
                 / cc_vfrac_sum : zero;
             // Average cell-centered u_star and wsp_mean to x-face, using only valid (SingleValued) cells
             bool low_valid  = cc_flag_arr(i-1,j,k).isSingleValued();
             bool high_valid = cc_flag_arr(i,j,k).isSingleValued();
             if (low_valid && high_valid) {
                 ustar    = myhalf * (u_star_arr(i-1,j,k) + u_star_arr(i,j,k));
                 wsp_mean = myhalf * (umm_arr(i-1,j,0) + umm_arr(i,j,0));
             } else if (low_valid) {
                 ustar    = u_star_arr(i-1,j,k);
                 wsp_mean = umm_arr(i-1,j,0);
             } else if (high_valid) {
                 ustar    = u_star_arr(i,j,k);
                 wsp_mean = umm_arr(i,j,0);
             } else {
                 ustar    = zero;
                 wsp_mean = WSMIN;
             }
         } else if (idir == 1) {
             // y-face: average from cells (j-1) and (j)
             // Volume-weighted average of x-face velocities to y-face
             amrex::Real u_vfrac_sum = u_vfrac_arr(i,j,k) + u_vfrac_arr(i+1,j,k) +
                                       u_vfrac_arr(i,j-1,k) + u_vfrac_arr(i+1,j-1,k);
             velx = (u_vfrac_sum > eps) ?
                 (velx_arr(i,j,k)   * u_vfrac_arr(i,j,k)   + velx_arr(i+1,j,k)   * u_vfrac_arr(i+1,j,k) +
                  velx_arr(i,j-1,k) * u_vfrac_arr(i,j-1,k) + velx_arr(i+1,j-1,k) * u_vfrac_arr(i+1,j-1,k))
                  / u_vfrac_sum : zero;
             vely = vely_arr(i,j,k);
             // Volume-weighted average of z-face velocities to y-face
             amrex::Real w_vfrac_sum = w_vfrac_arr(i,j,k) + w_vfrac_arr(i,j,k+1) +
                                       w_vfrac_arr(i,j-1,k) + w_vfrac_arr(i,j-1,k+1);
             amrex::Real velz = (w_vfrac_sum > eps) ?
                 (velz_arr(i,j,k)   * w_vfrac_arr(i,j,k)   + velz_arr(i,j,k+1)   * w_vfrac_arr(i,j,k+1) +
                  velz_arr(i,j-1,k) * w_vfrac_arr(i,j-1,k) + velz_arr(i,j-1,k+1) * w_vfrac_arr(i,j-1,k+1))
                  / w_vfrac_sum : zero;
             // Get boundary normal at y-face (already at correct staggered location)
             amrex::Real nx = bnorm_arr(i,j,k,0);
             amrex::Real ny = bnorm_arr(i,j,k,1);
             amrex::Real nz = bnorm_arr(i,j,k,2);
             // Project velocity onto tangent plane
             amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
             velx_tangent = velx - v_dot_n * nx;
             vely_tangent = vely - v_dot_n * ny;
             // Volume-weighted average of cell-centered density to y-face
             amrex::Real cc_vfrac_sum = cc_vfrac_arr(i,j-1,k) + cc_vfrac_arr(i,j,k);
             rho = (cc_vfrac_sum > eps) ?
                 (cons_arr(i,j-1,k,Rho_comp) * cc_vfrac_arr(i,j-1,k) + cons_arr(i,j,k,Rho_comp) * cc_vfrac_arr(i,j,k))
                 / cc_vfrac_sum : zero;
             // Average cell-centered u_star and wsp_mean to y-face, using only valid (SingleValued) cells
             bool low_valid  = cc_flag_arr(i,j-1,k).isSingleValued();
             bool high_valid = cc_flag_arr(i,j,k).isSingleValued();
             if (low_valid && high_valid) {
                 ustar    = myhalf * (u_star_arr(i,j-1,k) + u_star_arr(i,j,k));
                 wsp_mean = myhalf * (umm_arr(i,j-1,0) + umm_arr(i,j,0));
             } else if (low_valid) {
                 ustar    = u_star_arr(i,j-1,k);
                 wsp_mean = umm_arr(i,j-1,0);
             } else if (high_valid) {
                 ustar    = u_star_arr(i,j,k);
                 wsp_mean = umm_arr(i,j,0);
             } else {
                 ustar    = zero;
                 wsp_mean = WSMIN;
             }
         } else {
             // z-face: average from cells (k-1) and (k)
             // Volume-weighted average of x-face velocities to z-face
             amrex::Real u_vfrac_sum = u_vfrac_arr(i,j,k-1) + u_vfrac_arr(i+1,j,k-1) +
                                       u_vfrac_arr(i,j,k) + u_vfrac_arr(i+1,j,k);
             velx = (u_vfrac_sum > eps) ?
                 (velx_arr(i,j,k-1)   * u_vfrac_arr(i,j,k-1)   + velx_arr(i+1,j,k-1)   * u_vfrac_arr(i+1,j,k-1) +
                  velx_arr(i,j,k)     * u_vfrac_arr(i,j,k)     + velx_arr(i+1,j,k)     * u_vfrac_arr(i+1,j,k))
                  / u_vfrac_sum : zero;
             // Volume-weighted average of y-face velocities to z-face
             amrex::Real v_vfrac_sum = v_vfrac_arr(i,j,k-1) + v_vfrac_arr(i,j+1,k-1) +
                                       v_vfrac_arr(i,j,k) + v_vfrac_arr(i,j+1,k);
             vely = (v_vfrac_sum > eps) ?
                 (vely_arr(i,j,k-1)   * v_vfrac_arr(i,j,k-1)   + vely_arr(i,j+1,k-1)   * v_vfrac_arr(i,j+1,k-1) +
                  vely_arr(i,j,k)     * v_vfrac_arr(i,j,k)     + vely_arr(i,j+1,k)     * v_vfrac_arr(i,j+1,k))
                  / v_vfrac_sum : zero;
             // z-velocity is already at z-face
             amrex::Real velz = velz_arr(i,j,k);
             // Get boundary normal at z-face (already at correct staggered location)
             amrex::Real nx = bnorm_arr(i,j,k,0);
             amrex::Real ny = bnorm_arr(i,j,k,1);
             amrex::Real nz = bnorm_arr(i,j,k,2);
             // Project velocity onto tangent plane
             amrex::Real v_dot_n = velx*nx + vely*ny + velz*nz;
             velx_tangent = velx - v_dot_n * nx;
             vely_tangent = vely - v_dot_n * ny;
             // Volume-weighted average of cell-centered density to z-face
             amrex::Real cc_vfrac_sum = cc_vfrac_arr(i,j,k-1) + cc_vfrac_arr(i,j,k);
             rho = (cc_vfrac_sum > eps) ?
                 (cons_arr(i,j,k-1,Rho_comp) * cc_vfrac_arr(i,j,k-1) + cons_arr(i,j,k,Rho_comp) * cc_vfrac_arr(i,j,k))
                 / cc_vfrac_sum : zero;
             // Average cell-centered u_star and wsp_mean to z-face, using only valid (SingleValued) cells
             bool low_valid  = cc_flag_arr(i,j,k-1).isSingleValued();
             bool high_valid = cc_flag_arr(i,j,k).isSingleValued();
             if (low_valid && high_valid) {
                 ustar    = myhalf * (u_star_arr(i,j,k-1) + u_star_arr(i,j,k));
                 wsp_mean = myhalf * (umm_arr(i,j,0) + umm_arr(i,j,0));
             } else if (low_valid) {
                 ustar    = u_star_arr(i,j,k-1);
                 wsp_mean = umm_arr(i,j,0);
             } else if (high_valid) {
                 ustar    = u_star_arr(i,j,k);
                 wsp_mean = umm_arr(i,j,0);
             } else {
                 ustar    = zero;
                 wsp_mean = WSMIN;
             }
         }
         wsp_mean = std::max(wsp_mean, WSMIN);
         amrex::Real vmean = vm_arr(i,j,0);
         // Note: The surface mean shear stress is decomposed into tau_yz by
         //       multiplying the modeled shear stress (rho*ustar^2) with
         //       a factor of vmean/wsp_mean for directionality; this factor
         //       modifies the denominator from what is in Moeng amrex::Real(1984.)
         amrex::Real wsp     = std::sqrt(velx_tangent*velx_tangent+vely_tangent*vely_tangent);
         amrex::Real num1    = wsp * vmean;
         amrex::Real num2    = wsp_mean * (vely_tangent-vmean);
         // NOTE: this is rho*<v'w'> = -K dvdz
         amrex::Real stressy = -rho*ustar*ustar * (num1+num2)/(wsp_mean*wsp_mean);
         return stressy;
     }
Member Data Documentation
eps
const amrex::Real moeng_flux_eb::eps = amrex::Real(1e-12) private
Referenced by compute_q_flux(), compute_t_flux(), compute_u_flux(), and compute_v_flux().
WSMIN
const amrex::Real moeng_flux_eb::WSMIN = amrex::Real(0.1) private
Referenced by compute_q_flux(), compute_t_flux(), compute_u_flux(), and compute_v_flux().
The documentation for this struct was generated from the following file:
Source/EB/ERF_EBMOSTStress.H