ERF: UPWIND3SL Struct Reference
UPWIND3SL Struct Reference
#include <ERF_Interpolation_UPW.H>
Public Member Functions
UPWIND3SL (const amrex::Array4< const amrex::Real > &phi, const amrex::Real)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInX (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInY (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real Evaluate (const amrex::Real &s, const amrex::Real &sm1, const amrex::Real &sm2) const
int GetUpwindCellNumber () const
Private Attributes
amrex::Array4< const amrex::Real > m_phi
Static Private Attributes
static constexpr amrex::Real eps =(1.0e-16)
static constexpr amrex::Real l1 =(1.0/6.0)
static constexpr amrex::Real l2 =(1.0/3.0)
Detailed Description
Interpolation operators used for 3rd order upwind scheme
Constructor & Destructor Documentation
UPWIND3SL()
UPWIND3SL::UPWIND3SL (const amrex::Array4< const amrex::Real > & phi, const amrex::Real) inline
         : m_phi(phi)
     {}
Member Function Documentation
Evaluate()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real UPWIND3SL::Evaluate (const amrex::Real & s, const amrex::Real & sm1, const amrex::Real & sm2) const inline
     {
         amrex::Real rmh = (s - sm1) / ((sm1 - sm2) + eps);
         amrex::Real K   = l2 + 2.0*l2*rmh;
         amrex::Real phi = std::max(0.0,std::min(2.0*rmh,std::min(2.0,K)));
         return (sm1 + 0.5 * phi * (sm1 - sm2));
     }
Referenced by InterpolateInX(), InterpolateInY(), and InterpolateInZ().
GetUpwindCellNumber()
int UPWIND3SL::GetUpwindCellNumber () const inline
 {return 2;}
InterpolateInX()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3SL::InterpolateInX (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Data to interpolate on
         amrex::Real sp1 = m_phi(i+1, j  , k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i-1, j  , k  , qty_index);
         amrex::Real sm2 = m_phi(i-2, j  , k  , qty_index);
         // Left and right fluxes
         amrex::Real Fhi = Evaluate(s  ,sm1,sm2);
         amrex::Real Flo = Evaluate(sm1,s  ,sp1);
         // Numerical flux
         val_lo = (1.0 + upw_lo)/2.0 * Fhi + (1.0 - upw_lo)/2.0 * Flo;
     }
InterpolateInY()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3SL::InterpolateInY (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Data to interpolate on
         amrex::Real sp1 = m_phi(i  , j+1, k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j-1, k  , qty_index);
         amrex::Real sm2 = m_phi(i  , j-2, k  , qty_index);
         // Left and right fluxes
         amrex::Real Fhi = Evaluate(s  ,sm1,sm2);
         amrex::Real Flo = Evaluate(sm1,s  ,sp1);
         // Numerical flux
         val_lo = (1.0 + upw_lo)/2.0 * Fhi + (1.0 - upw_lo)/2.0 * Flo;
     }
InterpolateInZ()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void UPWIND3SL::InterpolateInZ (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Data to interpolate on
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
         // Left and right fluxes
         amrex::Real Fhi = Evaluate(s  ,sm1,sm2);
         amrex::Real Flo = Evaluate(sm1,s  ,sp1);
         // Numerical flux
         val_lo = (1.0 + upw_lo)/2.0 * Fhi + (1.0 - upw_lo)/2.0 * Flo;
     }
Member Data Documentation
eps
constexpr amrex::Real UPWIND3SL::eps =(1.0e-16) static constexpr private
Referenced by Evaluate().
l1
constexpr amrex::Real UPWIND3SL::l1 =(1.0/6.0) static constexpr private
l2
constexpr amrex::Real UPWIND3SL::l2 =(1.0/3.0) static constexpr private
Referenced by Evaluate().
m_phi
amrex::Array4<const amrex::Real> UPWIND3SL::m_phi private
Referenced by InterpolateInX(), InterpolateInY(), and InterpolateInZ().
The documentation for this struct was generated from the following file:
Source/Utils/ERF_Interpolation_UPW.H