ERF: surface_temp_wave_coupled Struct Reference
surface_temp_wave_coupled Struct Reference
#include <ERF_MOSTStress.H>
Public Member Functions
surface_temp_wave_coupled (amrex::Real Tflux, amrex::Real Qvflux, bool cons_qflux)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void iterate_flux (const int &i, const int &j, const int &k, const int &max_iters, const amrex::Array4< const amrex::Real > &zref_arr, const amrex::Array4< amrex::Real > &z0_arr, const amrex::Array4< const amrex::Real > &umm_arr, const amrex::Array4< const amrex::Real > &tm_arr, const amrex::Array4< const amrex::Real > &tvm_arr, const amrex::Array4< const amrex::Real > &qvm_arr, const amrex::Array4< amrex::Real > &u_star_arr, const amrex::Array4< amrex::Real > &w_star_arr, const amrex::Array4< amrex::Real > &t_star_arr, const amrex::Array4< amrex::Real > &q_star_arr, const amrex::Array4< amrex::Real > &t_surf_arr, const amrex::Array4< amrex::Real > &q_surf_arr, const amrex::Array4< amrex::Real > &olen_arr, const amrex::Array4< amrex::Real > &pblh_arr, const amrex::Array4< amrex::Real > &Hwave_arr, const amrex::Array4< amrex::Real > &Lwave_arr, const amrex::Array4< amrex::Real > &eta_arr) const
Private Attributes
most_data mdata
bool spec_qflux
similarity_funs sfuns
const amrex::Real tol = amrex::Real(1.0e-5)
const amrex::Real eps = amrex::Real(1e-15)
const amrex::Real z0_eps = amrex::Real(1.0e-6)
const amrex::Real z0_max = amrex::Real(0.1)
const amrex::Real WSMIN = amrex::Real(0.1)
Detailed Description
Surface temperature with wave-coupled roughness
Constructor & Destructor Documentation
surface_temp_wave_coupled()
surface_temp_wave_coupled::surface_temp_wave_coupled (amrex::Real Tflux, amrex::Real Qvflux, bool cons_qflux) inline
     {
         mdata.surf_temp_flux  = Tflux;
         mdata.surf_moist_flux = Qvflux;
         spec_qflux = cons_qflux;
     }
Member Function Documentation
iterate_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void surface_temp_wave_coupled::iterate_flux (const int & i, const int & j, const int & k, const int & max_iters, const amrex::Array4< const amrex::Real > & zref_arr, const amrex::Array4< amrex::Real > & z0_arr, const amrex::Array4< const amrex::Real > & umm_arr, const amrex::Array4< const amrex::Real > & tm_arr, const amrex::Array4< const amrex::Real > & tvm_arr, const amrex::Array4< const amrex::Real > & qvm_arr, const amrex::Array4< amrex::Real > & u_star_arr, const amrex::Array4< amrex::Real > & w_star_arr, const amrex::Array4< amrex::Real > & t_star_arr, const amrex::Array4< amrex::Real > & q_star_arr, const amrex::Array4< amrex::Real > & t_surf_arr, const amrex::Array4< amrex::Real > & q_surf_arr, const amrex::Array4< amrex::Real > & olen_arr, const amrex::Array4< amrex::Real > & pblh_arr, const amrex::Array4< amrex::Real > & Hwave_arr, const amrex::Array4< amrex::Real > & Lwave_arr, const amrex::Array4< amrex::Real > & eta_arr) const inline
     {
         int iter = 0;
         amrex::Real ustar = zero;
         amrex::Real wstar = zero;
         amrex::Real z0    = zero;
         amrex::Real tflux = zero;
         amrex::Real qflux = zero;
         amrex::Real zeta  = zero;
         amrex::Real psi_m = zero;
         amrex::Real psi_h = zero;
         amrex::Real Olen  = zero;
         amrex::Real Oleno = zero;
         amrex::Real zref  = zref_arr(i,j,k);
         int ie, je;
         ie = i  < lbound(eta_arr).x ? lbound(eta_arr).x : i;
         je = j  < lbound(eta_arr).y ? lbound(eta_arr).y : j;
         ie = ie > ubound(eta_arr).x ? ubound(eta_arr).x : ie;
         je = je > ubound(eta_arr).y ? ubound(eta_arr).y : je;
         amrex::Real umm   = std::max(umm_arr(i,j,k), WSMIN);
         if (u_star_arr(i,j,k) == bogus_large_value) {
             u_star_arr(i,j,k) = mdata.kappa * umm / std::log(zref / z0_arr(i,j,k));
         } else {
             Olen  = olen_arr(i,j,k);
             Oleno = Olen;
             zeta  = zref / Olen;
             psi_m = sfuns.calc_psi_m(zeta);
             psi_h = sfuns.calc_psi_h(zeta);
         }
         do {
             ustar = u_star_arr(i,j,k);
             z0    = std::min( std::max(amrex::Real(1200.0) * Hwave_arr(i,j,k) * std::pow( Hwave_arr(i,j,k)/(Lwave_arr(i,j,k)+eps), amrex::Real(4.5) )
                                       + amrex::Real(0.11) * eta_arr(ie,je,k,EddyDiff::Mom_v) / ustar, z0_eps), z0_max );
             tflux = -(tm_arr(i,j,k) - t_surf_arr(i,j,k)) * ustar * mdata.kappa /
                      (std::log(zref / z0) - psi_h); // <w'T'>
             tflux *= (1 + amrex::Real(0.61)*qvm_arr(i,j,k));
             qflux = (spec_qflux) ? mdata.surf_moist_flux :
                                  -(qvm_arr(i,j,k) - q_surf_arr(i,j,k)) * ustar * mdata.kappa /
                                   (std::log(zref / z0_arr(i,j,k)) - psi_h); // <w'Qv'>
             tflux += amrex::Real(0.61)*tm_arr(i,j,k) * qflux; // ~= <w'Tv'>
             if (w_star_arr) {
                 // update w* and Umagmean
                 w_star_arr(i,j,k) = calc_wstar(tflux, pblh_arr(i,j,k), tvm_arr(i,j,k));
                 wstar = mdata.Bjr_beta * w_star_arr(i,j,k);
                 umm = std::sqrt(umm_arr(i,j,k)*umm_arr(i,j,k) + wstar*wstar);
                 umm = std::max(umm, WSMIN);
             }
             Olen = -ustar * ustar * ustar * tvm_arr(i,j,k) / (mdata.kappa * mdata.gravity * tflux);
             if ( (((Olen >= zero) && (Oleno <= zero)) ||
                   ((Olen <= zero) && (Oleno >= zero))) &&
                  std::fabs(Olen) + std::fabs(Oleno) < amrex::Real(1.0)) {
                 Olen = myhalf * (Olen + Oleno);
             }
             Oleno = Olen;
             zeta  = zref / Olen;
             psi_m = sfuns.calc_psi_m(zeta);
             psi_h = sfuns.calc_psi_h(zeta);
             u_star_arr(i,j,k) = mdata.kappa * umm / (std::log(zref / z0) - psi_m);
             ++iter;
         } while ((std::abs(u_star_arr(i,j,k) - ustar) > tol) && iter <= max_iters);
         AMREX_ALWAYS_ASSERT_WITH_MESSAGE(iter < max_iters,
                                          "Maximum number of MOST iterations reached.");
         // Populate the stored MOST arrays
         z0_arr(i,j,k)     = z0;
         olen_arr(i,j,k)   = Olen;
         t_star_arr(i,j,k) = mdata.kappa * (tm_arr(i,j,k) - t_surf_arr(i,j,k)) /
                             (std::log(zref / z0) - psi_h);
         if (spec_qflux) {
             q_surf_arr(i,j,k) = mdata.surf_moist_flux * (std::log(zref / z0_arr(i,j,k)) - psi_h) /
                                 (u_star_arr(i,j,k) * mdata.kappa) + qvm_arr(i,j,k);
             q_star_arr(i,j,k) = -mdata.surf_moist_flux / u_star_arr(i,j,k);
         } else {
             q_star_arr(i,j,k) = mdata.kappa * (qvm_arr(i,j,k) - q_surf_arr(i,j,k)) /
                                 (std::log(zref / z0_arr(i,j,k)) - psi_h);
         }
     }
Member Data Documentation
eps
const amrex::Real surface_temp_wave_coupled::eps = amrex::Real(1e-15) private
Referenced by iterate_flux().
mdata
most_data surface_temp_wave_coupled::mdata private
Referenced by iterate_flux(), and surface_temp_wave_coupled().
sfuns
similarity_funs surface_temp_wave_coupled::sfuns private
Referenced by iterate_flux().
spec_qflux
bool surface_temp_wave_coupled::spec_qflux private
Referenced by iterate_flux(), and surface_temp_wave_coupled().
tol
const amrex::Real surface_temp_wave_coupled::tol = amrex::Real(1.0e-5) private
Referenced by iterate_flux().
WSMIN
const amrex::Real surface_temp_wave_coupled::WSMIN = amrex::Real(0.1) private
Referenced by iterate_flux().
z0_eps
const amrex::Real surface_temp_wave_coupled::z0_eps = amrex::Real(1.0e-6) private
Referenced by iterate_flux().
z0_max
const amrex::Real surface_temp_wave_coupled::z0_max = amrex::Real(0.1) private
Referenced by iterate_flux().
The documentation for this struct was generated from the following file:
Source/BoundaryConditions/ERF_MOSTStress.H