ERF: rico_flux Struct Reference
rico_flux Struct Reference
#include <ERF_MOSTStress.H>
Public Member Functions
rico_flux (amrex::Real l_theta_z0, amrex::Real l_qsat_z0)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_q_flux (const int &i, const int &j, const int &k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &q_star_arr, const amrex::Array4< const amrex::Real > &) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_t_flux (const int &i, const int &j, const int &k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &t_star_arr, const amrex::Array4< const amrex::Real > &) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_u_flux (const int &i, const int &j, const int &k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &u_star_arr) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real compute_v_flux (const int &i, const int &j, const int &k, const amrex::Array4< const amrex::Real > &cons_arr, const amrex::Array4< const amrex::Real > &velx_arr, const amrex::Array4< const amrex::Real > &vely_arr, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &, const amrex::Array4< const amrex::Real > &u_star_arr) const
Private Attributes
const amrex::Real eps = amrex::Real(1e-15)
amrex::Real theta_z0 = amrex::Real(298.0)
amrex::Real qsat_z0 = amrex::Real(0.0010)
Detailed Description
RICO flux formulation
Constructor & Destructor Documentation
rico_flux()
rico_flux::rico_flux (amrex::Real l_theta_z0, amrex::Real l_qsat_z0) inline
       : theta_z0{l_theta_z0}, qsat_z0{l_qsat_z0} {}
Member Function Documentation
compute_q_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real rico_flux::compute_q_flux (const int & i, const int & j, const int & k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & q_star_arr, const amrex::Array4< const amrex::Real > &) const inline
     {
         amrex::Real rho   = cons_arr(i,j,k,Rho_comp);
         amrex::Real qstar = q_star_arr(i,j,0);
         amrex::Real q     = cons_arr(i, j, k, RhoQ1_comp) / rho;
         amrex::Real velx = myhalf * (velx_arr(i,j,k) + velx_arr(i+1,j,k));
         amrex::Real vely = myhalf * (vely_arr(i,j,k) + vely_arr(i,j+1,k));
         amrex::Real wsp = std::sqrt(velx*velx + vely*vely);
         // NOTE: this is rho*<q'w'> = -K dqdz
         amrex::Real moflux  = (std::abs(qstar) > eps) ? - rho * qstar * wsp * (q - qsat_z0) : zero;
         return moflux;
     }
compute_t_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real rico_flux::compute_t_flux (const int & i, const int & j, const int & k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & t_star_arr, const amrex::Array4< const amrex::Real > &) const inline
     {
         amrex::Real rho   = cons_arr(i,j,k,Rho_comp);
         amrex::Real tstar = t_star_arr(i, j, 0);
         amrex::Real theta = cons_arr(i, j, k, RhoTheta_comp) / rho;
         amrex::Real velx = myhalf * (velx_arr(i,j,k) + velx_arr(i+1,j,k));
         amrex::Real vely = myhalf * (vely_arr(i,j,k) + vely_arr(i,j+1,k));
         amrex::Real wsp = std::sqrt(velx*velx + vely*vely);
         // NOTE: this is rho*<T'w'> = -K dTdz
         amrex::Real moflux  = (std::abs(tstar) > eps) ? - rho * tstar * wsp * (theta - theta_z0) : zero;
         return moflux;
     }
compute_u_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real rico_flux::compute_u_flux (const int & i, const int & j, const int & k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & u_star_arr) const inline
     {
         amrex::Real velx = velx_arr(i,j,k);
         amrex::Real vely = fourth * ( vely_arr(i  ,j,k) + vely_arr(i  ,j+1,k)
                                     + vely_arr(i-1,j,k) + vely_arr(i-1,j+1,k) );
         amrex::Real rho  = myhalf * ( cons_arr(i-1,j,k,Rho_comp) + cons_arr(i,j,k,Rho_comp) );
         amrex::Real ustar = myhalf * ( u_star_arr(i-1,j,0) + u_star_arr(i,j,0) );
         amrex::Real wsp   = std::sqrt(velx*velx+vely*vely);
         // NOTE: this is rho*<u'w'> = -K dudz
         amrex::Real stressx = -rho * ustar * wsp * velx;
         return stressx;
     }
compute_v_flux()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real rico_flux::compute_v_flux (const int & i, const int & j, const int & k, const amrex::Array4< const amrex::Real > & cons_arr, const amrex::Array4< const amrex::Real > & velx_arr, const amrex::Array4< const amrex::Real > & vely_arr, const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & , const amrex::Array4< const amrex::Real > & u_star_arr) const inline
     {
         amrex::Real velx  = fourth * ( velx_arr(i,j  ,k) + velx_arr(i+1,j  ,k)
                                      + velx_arr(i,j-1,k) + velx_arr(i+1,j-1,k) );
         amrex::Real vely  = vely_arr(i,j,k);
         amrex::Real rho   = myhalf * ( cons_arr(i,j-1,k,Rho_comp) + cons_arr(i,j,k,Rho_comp) );
         amrex::Real ustar   = myhalf * ( u_star_arr(i,j-1,0) + u_star_arr(i,j,0) );
         amrex::Real wsp     = std::sqrt(velx*velx+vely*vely);
         // NOTE: this is rho*<v'w'> = -K dvdz
         amrex::Real stressy = -rho * ustar * wsp * vely;
         return stressy;
     }
Member Data Documentation
eps
const amrex::Real rico_flux::eps = amrex::Real(1e-15) private
Referenced by compute_q_flux(), and compute_t_flux().
qsat_z0
amrex::Real rico_flux::qsat_z0 = amrex::Real(0.0010) private
Referenced by compute_q_flux().
theta_z0
amrex::Real rico_flux::theta_z0 = amrex::Real(298.0) private
Referenced by compute_t_flux().
The documentation for this struct was generated from the following file:
Source/BoundaryConditions/ERF_MOSTStress.H