ERF: WENO_Z7 Struct Reference
WENO_Z7 Struct Reference
#include <ERF_Interpolation_WENO_Z.H>
Public Member Functions
WENO_Z7 (const amrex::Array4< const amrex::Real > &phi, const amrex::Real)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInX (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInY (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void InterpolateInZ (const int &i, const int &j, const int &k, const int &qty_index, amrex::Real &val_lo, amrex::Real upw_lo) const
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real Evaluate (const amrex::Real &sm3, const amrex::Real &sm2, const amrex::Real &sm1, const amrex::Real &s, const amrex::Real &sp1, const amrex::Real &sp2, const amrex::Real &sp3) const
Private Attributes
amrex::Array4< const amrex::Real > m_phi
const amrex::Real eps =1.0e-40
Static Private Attributes
static constexpr amrex::Real g1 =(1.0/64.0)
static constexpr amrex::Real g2 =(21.0/64.0)
static constexpr amrex::Real g3 =(35.0/64.0)
static constexpr amrex::Real g4 =(7.0/64.0)
Detailed Description
Interpolation operators used for WENO_Z-7 scheme
Constructor & Destructor Documentation
WENO_Z7()
WENO_Z7::WENO_Z7 (const amrex::Array4< const amrex::Real > & phi, const amrex::Real) inline
         : m_phi(phi) {}
Member Function Documentation
Evaluate()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WENO_Z7::Evaluate (const amrex::Real & sm3, const amrex::Real & sm2, const amrex::Real & sm1, const amrex::Real & s, const amrex::Real & sp1, const amrex::Real & sp2, const amrex::Real & sp3) const inline
     {
         // Smoothing factors
         amrex::Real b1 = ( sm3 * sm3 * 6649./2880.0
                          - sm3 * sm2 * 2623./160.0
                          + sm3 * sm1 * 9449./480.0
                          - sm3 * s   * 11389./1440.0
                          + sm2 * sm2 * 28547./960.0
                          - sm2 * sm1 * 35047./480.0
                          + sm2 * s   * 14369./480.0
                          + sm1 * sm1 * 44747./960.0
                          - sm1 * s   * 6383./160.0
                          + s   * s   * 25729./2880.0 );
         amrex::Real b2 = ( sm2 * sm2 * 3169/2880.0
                          - sm2 * sm1 * 3229/480.0
                          + sm2 * s   * 3169/480.0
                          - sm2 * sp1 * 2989/1440.0
                          + sm1 * sm1 * 11147/960.0
                          - sm1 * s   * 11767/480.0
                          + sm1 * sp1 * 1283/160.0
                          + s   * s   * 13667/960.0
                          - s   * sp1 * 5069/480.0
                          + sp1 * sp1 * 6649/2880.0 );
         amrex::Real b3 = ( sm1 * sm1 * 6649./2880.0
                          - sm1 * s   * 5069./480.0
                          + sm1 * sp1 * 1283./160.0
                          - sm1 * sp2 * 2989./1440.0
                          + s   * s   * 13667./960.0
                          - s   * sp1 * 11767./480.0
                          + s   * sp2 * 3169./480.0
                          + sp1 * sp1 * 11147./960.0
                          - sp1 * sp2 * 3229./480.0
                          + sp2 * sp2 * 3169./2880.0 );
         amrex::Real b4 = ( s   * s   * 25729./2880.
                          - s   * sp1 * 6383./160.
                          + s   * sp2 * 14369./480.
                          - s   * sp3 * 11389./1440.
                          + sp1 * sp1 * 44747./960.
                          - sp1 * sp2 * 35047./480.
                          + sp1 * sp3 * 9449./480.
                          + sp2 * sp2 * 28547./960.
                          - sp2 * sp3 * 2623./160.
                          + sp3 * sp3 * 6649./2880. );
         // Weight factors
         amrex::Real t5 = std::abs(b1 - b2 - b3 + b4);
         amrex::Real w1 = g1 * ( 1.0 + (t5*t5) / ((eps + b1) * (eps + b1)) );
         amrex::Real w2 = g2 * ( 1.0 + (t5*t5) / ((eps + b2) * (eps + b2)) );
         amrex::Real w3 = g3 * ( 1.0 + (t5*t5) / ((eps + b3) * (eps + b3)) );
         amrex::Real w4 = g4 * ( 1.0 + (t5*t5) / ((eps + b3) * (eps + b3)) );
         // Weight factor norm
         amrex::Real wsum = w1 + w2 + w3 + w4;
         // Taylor expansions
         amrex::Real v1 = (-0.3125)*sm3 + ( 1.3125)*sm2 + (-2.1875)*sm1 + ( 2.1875)*s;
         amrex::Real v2 = ( 0.0625)*sm2 + (-0.3125)*sm1 + ( 0.9375)*s   + ( 0.3125)*sp1;
         amrex::Real v3 = (-0.0625)*sm1 + ( 0.5625)*s   + ( 0.5625)*sp1 + (-0.0625)*sp2;
         amrex::Real v4 = ( 0.3125)*s   + ( 0.9375)*sp1 + (-0.3125)*sp2 + ( 0.0625)*sp3;
         // Interpolated value
         return ( (w1 * v1 + w2 * v2 + w3 * v3 + w4 * v4) / (wsum) );
     }
Referenced by InterpolateInX(), InterpolateInY(), and InterpolateInZ().
InterpolateInX()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z7::InterpolateInX (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Data to interpolate on
         amrex::Real sp3 = m_phi(i+3, j  , k  , qty_index);
         amrex::Real sp2 = m_phi(i+2, j  , k  , qty_index);
         amrex::Real sp1 = m_phi(i+1, j  , k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i-1, j  , k  , qty_index);
         amrex::Real sm2 = m_phi(i-2, j  , k  , qty_index);
         amrex::Real sm3 = m_phi(i-3, j  , k  , qty_index);
         amrex::Real sm4 = m_phi(i-4, j  , k  , qty_index);
         // Left and right fluxes
         amrex::Real Fhi = Evaluate(sm4,sm3,sm2,sm1,s  ,sp1,sp2);
         amrex::Real Flo = Evaluate(sp3,sp2,sp1,s  ,sm1,sm2,sm3);
         // Numerical flux
         val_lo = (1.0 + upw_lo)/2.0 * Fhi + (1.0 - upw_lo)/2.0 * Flo;
     }
InterpolateInY()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z7::InterpolateInY (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Data to interpolate on
         amrex::Real sp3 = m_phi(i  , j+3, k  , qty_index);
         amrex::Real sp2 = m_phi(i  , j+2, k  , qty_index);
         amrex::Real sp1 = m_phi(i  , j+1, k  , qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j-1, k  , qty_index);
         amrex::Real sm2 = m_phi(i  , j-2, k  , qty_index);
         amrex::Real sm3 = m_phi(i  , j-3, k  , qty_index);
         amrex::Real sm4 = m_phi(i  , j-4, k  , qty_index);
         // Left and right fluxes
         amrex::Real Fhi = Evaluate(sm4,sm3,sm2,sm1,s  ,sp1,sp2);
         amrex::Real Flo = Evaluate(sp3,sp2,sp1,s  ,sm1,sm2,sm3);
         // Numerical flux
         val_lo = (1.0 + upw_lo)/2.0 * Fhi + (1.0 - upw_lo)/2.0 * Flo;
     }
InterpolateInZ()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE void WENO_Z7::InterpolateInZ (const int & i, const int & j, const int & k, const int & qty_index, amrex::Real & val_lo, amrex::Real upw_lo) const inline
     {
         // Upwinding flags
         if (upw_lo != 0.) upw_lo = (upw_lo > 0) ? 1. : -1.;
         // Data to interpolate on
         amrex::Real sp3 = m_phi(i  , j  , k+2, qty_index);
         amrex::Real sp2 = m_phi(i  , j  , k+2, qty_index);
         amrex::Real sp1 = m_phi(i  , j  , k+1, qty_index);
         amrex::Real s   = m_phi(i  , j  , k  , qty_index);
         amrex::Real sm1 = m_phi(i  , j  , k-1, qty_index);
         amrex::Real sm2 = m_phi(i  , j  , k-2, qty_index);
         amrex::Real sm3 = m_phi(i  , j  , k-3, qty_index);
         amrex::Real sm4 = m_phi(i  , j  , k-3, qty_index);
         // Left and right fluxes
         amrex::Real Fhi = Evaluate(sm4,sm3,sm2,sm1,s  ,sp1,sp2);
         amrex::Real Flo = Evaluate(sp3,sp2,sp1,s  ,sm1,sm2,sm3);
         // Numerical flux
         val_lo = (1.0 + upw_lo)/2.0 * Fhi + (1.0 - upw_lo)/2.0 * Flo;
     }
Member Data Documentation
eps
const amrex::Real WENO_Z7::eps =1.0e-40 private
Referenced by Evaluate().
g1
constexpr amrex::Real WENO_Z7::g1 =(1.0/64.0) static constexpr private
Referenced by Evaluate().
g2
constexpr amrex::Real WENO_Z7::g2 =(21.0/64.0) static constexpr private
Referenced by Evaluate().
g3
constexpr amrex::Real WENO_Z7::g3 =(35.0/64.0) static constexpr private
Referenced by Evaluate().
g4
constexpr amrex::Real WENO_Z7::g4 =(7.0/64.0) static constexpr private
Referenced by Evaluate().
m_phi
amrex::Array4<const amrex::Real> WENO_Z7::m_phi private
Referenced by InterpolateInX(), InterpolateInY(), and InterpolateInZ().
The documentation for this struct was generated from the following file:
Source/Utils/ERF_Interpolation_WENO_Z.H