ERF: similarity_funs Struct Reference
similarity_funs Struct Reference
#include <ERF_MOSTStress.H>
Public Member Functions
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real calc_psi_m2 (amrex::Real zeta) const
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real calc_psi_h2 (amrex::Real zeta) const
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real calc_psi_m (amrex::Real zeta) const
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real calc_psi_h (amrex::Real zeta) const
Private Attributes
amrex::Real beta_m {5.0}
Constants from Dyer, BLM, 1974.
amrex::Real beta_h {5.0}
https://doi.org/10.1007/BF00240838
amrex::Real gamma_m {16.0}
amrex::Real gamma_h {16.0}
Detailed Description
Structure of similarity functions for Moeng formulation
Member Function Documentation
calc_psi_h()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real similarity_funs::calc_psi_h (amrex::Real zeta) const inline
     {
         if (zeta > 0) {
             return -beta_h * zeta;
         } else {
             amrex::Real x = std::sqrt(1.0 - gamma_h * zeta);
             return 2.0 * std::log(0.5 * (1.0 + x));
         }
     }
Referenced by surface_flux_charnock::iterate_flux(), surface_flux_mod_charnock::iterate_flux(), surface_flux_donelan::iterate_flux(), surface_temp_donelan::iterate_flux(), surface_flux_wave_coupled::iterate_flux(), surface_temp_wave_coupled::iterate_flux(), surface_flux::iterate_flux(), make_mom_sources(), and make_sources().
calc_psi_h2()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real similarity_funs::calc_psi_h2 (amrex::Real zeta) const inline
     {
         if (zeta > 0) {
             amrex::Real x = std::pow(1.0 + std::pow(zeta, 1.1), 1.0/1.1);
             return ( -6.1*std::log(zeta + x) );
         } else {
             amrex::Real x = std::sqrt(1.0 - 16.0*zeta);
             amrex::Real psi_k_h = 2.0 * std::log(0.5 * (1.0 + x));
             amrex::Real y = std::pow(1.0 - 34.0*zeta, 1.0/3.0);
             amrex::Real psi_c_h = (3.0/2.0)*std::log((y*y + y + 1.0)/3.0)
                                 - std::sqrt(3.0)*std::atan((2.0*y + 1.0)/std::sqrt(3.0))
                                 + PI/std::sqrt(3.0);
             return ( (psi_k_h + zeta*zeta*psi_c_h) / (1. + zeta*zeta) );
         }
     }
Referenced by surface_temp_charnock::iterate_flux(), surface_temp_mod_charnock::iterate_flux(), and surface_temp::iterate_flux().
calc_psi_m()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real similarity_funs::calc_psi_m (amrex::Real zeta) const inline
     {
         if (zeta > 0) {
             return -beta_m * zeta;
         } else {
             amrex::Real x = std::sqrt(std::sqrt(1.0 - gamma_m * zeta));
             return 2.0 * std::log(0.5 * (1.0 + x)) + log(0.5 * (1.0 + x * x)) -
                    2.0 * std::atan(x) + PIoTwo;
         }
     }
Referenced by surface_flux_charnock::iterate_flux(), surface_flux_mod_charnock::iterate_flux(), surface_flux_donelan::iterate_flux(), surface_temp_donelan::iterate_flux(), surface_flux_wave_coupled::iterate_flux(), surface_temp_wave_coupled::iterate_flux(), surface_flux::iterate_flux(), make_mom_sources(), and make_sources().
calc_psi_m2()
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real similarity_funs::calc_psi_m2 (amrex::Real zeta) const inline
     {
         if (zeta > 0) {
             amrex::Real x = std::pow(1.0 + std::pow(zeta, 2.5), 1.0/2.5);
             return ( -6.1*std::log(zeta + x) );
         } else {
             amrex::Real x = std::pow(1.0 - 16.0*zeta, 0.25);
             amrex::Real psi_k_m =  2.0 * std::log(0.5 * (1.0 + x)) + log(0.5 * (1.0 + x * x)) -
                                    2.0 * std::atan(x) + PIoTwo;
             amrex::Real y = std::pow(1.0 - 10.0*zeta, 1.0/3.0);
             amrex::Real psi_c_m = (3.0/2.0)*std::log((y*y + y + 1.0)/3.0)
                                 - std::sqrt(3.0)*std::atan((2.0*y + 1.0)/std::sqrt(3.0))
                                 + PI/std::sqrt(3.0);
             return ( (psi_k_m + zeta*zeta*psi_c_m) / (1. + zeta*zeta) );
         }
     }
Referenced by surface_temp_charnock::iterate_flux(), surface_temp_mod_charnock::iterate_flux(), and surface_temp::iterate_flux().
Member Data Documentation
beta_h
amrex::Real similarity_funs::beta_h {5.0} private
https://doi.org/10.1007/BF00240838
Referenced by calc_psi_h().
beta_m
amrex::Real similarity_funs::beta_m {5.0} private
Constants from Dyer, BLM, 1974.
Referenced by calc_psi_m().
gamma_h
amrex::Real similarity_funs::gamma_h {16.0} private
Referenced by calc_psi_h().
gamma_m
amrex::Real similarity_funs::gamma_m {16.0} private
Referenced by calc_psi_m().
The documentation for this struct was generated from the following file:
Source/BoundaryConditions/ERF_MOSTStress.H