ERF: MaterialProperties Struct Reference
MaterialProperties Struct Reference
#include <ERF_MaterialProperties.H>
Public Member Functions
AMREX_GPU_HOST_DEVICE MaterialProperties (const Species::Name &a_name)
Constructor.
AMREX_GPU_HOST_DEVICE MaterialProperties (const MaterialProperties &a_matprop)
Copy constructor.
AMREX_GPU_HOST_DEVICE ~MaterialProperties ()=default
Default destructor.
AMREX_GPU_HOST void print () const
Print parameters.
AMREX_GPU_HOST_DEVICE void setProperties_H2O ()
Set this material to H20.
AMREX_GPU_HOST_DEVICE void setProperties_water ()
Set this material to water.
AMREX_GPU_HOST_DEVICE void setProperties_agua ()
Set this material to agua.
AMREX_GPU_HOST_DEVICE void setProperties_NaCl ()
Set this material to NaCl.
AMREX_GPU_HOST_DEVICE void setProperties_NH42SO4 ()
Set this material to ammonium sulfate.
AMREX_GPU_HOST_DEVICE void setProperties_NH4HSO4 ()
Set this material to ammonium bisulfate.
AMREX_GPU_HOST_DEVICE void setProperties_soil ()
Set this material to soil.
AMREX_GPU_HOST AMREX_FORCE_INLINE void computeSaturationPressure (amrex::MultiFab &a_e, const amrex::MultiFab &a_T) const
Compute saturation pressure.
AMREX_GPU_HOST AMREX_FORCE_INLINE void computeSaturationVapFrac (amrex::MultiFab &a_S, const amrex::MultiFab &a_T, const amrex::MultiFab &a_p) const
Compute saturation vapour fraction.
Public Member Functions inherited from MaterialPropertiesCore
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real molarHeatCapacity (const amrex::Real a_T) const
Return the molar heat capacity.
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real surfaceTension (const amrex::Real a_T) const
Compute the surface tension coeff given temperature.
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real coeffCurv (const amrex::Real a_T) const
Return the coeff of curvature given the temperature.
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real coeffVPSolute () const
Return the vapour pressure coefficient.
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE amrex::Real coeffMolecularDiffusion (const amrex::Real a_T, const amrex::Real a_P) const
Return the molecular diffusion coefficient given temperature and pressure.
Public Attributes
Species::Name m_name = Species::Name::none
decltype(saturation_funcs::compute_saturation_pressure_null) * m_saturation_pressure_func = nullptr
decltype(saturation_funcs::compute_saturation_vapfrac_null) * m_saturation_vapfrac_func = nullptr
Public Attributes inherited from MaterialPropertiesCore
amrex::Real m_density = DBL_MAX
amrex::Real m_ionization = DBL_MAX
amrex::Real m_mol_weight = DBL_MAX
amrex::Real m_lat_vap = DBL_MAX
amrex::Real m_Rv = DBL_MAX
amrex::Real m_Tc = DBL_MAX
amrex::Real m_Tb = DBL_MAX
amrex::Real m_Nav_by_molweight = DBL_MAX
amrex::Real m_mol_Cp_coeffs [7]
bool m_is_soluble = false
bool m_is_water = false
Additional Inherited Members
Static Public Attributes inherited from MaterialPropertiesCore
static constexpr amrex::Real s_N_av = amrex::Real(6.02214076e23)
static constexpr amrex::Real s_kb = amrex::Real(1.380649e-23)
static constexpr amrex::Real s_mol_weight_air = amrex::Real(0.0289647)
static constexpr amrex::Real s_sigma_air = amrex::Real(3.62e-10)
static constexpr amrex::Real s_eps_air_k = 97
Detailed Description
Class for material properties
Constructor & Destructor Documentation
MaterialProperties() [1/2]
AMREX_GPU_HOST_DEVICE MaterialProperties::MaterialProperties (const Species::Name & a_name)
Constructor.
 {
     m_name = a_name;
     if (a_name == Species::Name::H2O) {
         setProperties_H2O();
     } else if (a_name == Species::Name::water) {
         setProperties_water();
     } else if (a_name == Species::Name::agua) {
         setProperties_agua();
     } else if (a_name == Species::Name::NaCl) {
         setProperties_NaCl();
     } else if (a_name == Species::Name::NH42SO4) {
         setProperties_NH42SO4();
     } else if (a_name == Species::Name::NH4HSO4) {
         setProperties_NH4HSO4();
     } else if (a_name == Species::Name::soil) {
         setProperties_soil();
     } else {
         amrex::Abort("ERROR: undefined material in MaterialProperties()");
     }
     m_is_soluble = (m_ionization > 0);
 }
MaterialProperties() [2/2]
AMREX_GPU_HOST_DEVICE MaterialProperties::MaterialProperties (const MaterialProperties & a_matprop)
Copy constructor.
 {
     m_name = a_matprop.m_name;
     m_density = a_matprop.m_density;
     m_ionization = a_matprop.m_ionization;
     m_mol_weight = a_matprop.m_mol_weight;
     m_lat_vap = a_matprop.m_lat_vap;
     m_Rv = a_matprop.m_Rv;
     m_Tc = a_matprop.m_Tc;
     m_Tb = a_matprop.m_Tb;
     m_Nav_by_molweight = a_matprop.m_Nav_by_molweight;
     for (auto i = 0; i < 7; i++) { m_mol_Cp_coeffs[i] = a_matprop.m_mol_Cp_coeffs[i]; }
     m_is_soluble = a_matprop.m_is_soluble;
     m_is_water = a_matprop.m_is_water;
     AMREX_IF_ON_HOST((
         m_saturation_pressure_func = a_matprop.m_saturation_pressure_func;
         m_saturation_vapfrac_func = a_matprop.m_saturation_vapfrac_func;
     ))
 }
~MaterialProperties()
AMREX_GPU_HOST_DEVICE MaterialProperties::~MaterialProperties () default
Default destructor.
Member Function Documentation
computeSaturationPressure()
AMREX_GPU_HOST AMREX_FORCE_INLINE void MaterialProperties::computeSaturationPressure (amrex::MultiFab & a_e, const amrex::MultiFab & a_T) const inline
Compute saturation pressure.
     {
         m_saturation_pressure_func(a_e, a_T);
     }
computeSaturationVapFrac()
AMREX_GPU_HOST AMREX_FORCE_INLINE void MaterialProperties::computeSaturationVapFrac (amrex::MultiFab & a_S, const amrex::MultiFab & a_T, const amrex::MultiFab & a_p) const inline
Compute saturation vapour fraction.
     {
         m_saturation_vapfrac_func(a_S, a_T, a_p);
     }
print()
AMREX_GPU_HOST void MaterialProperties::print () const inline
Print parameters.
{
         amrex::Print() << "Material properties of " << amrex::getEnumNameString(m_name) << ":\n";
         amrex::Print() << "    density: " << m_density << "\n";
         amrex::Print() << "    ionization: " << m_ionization << "\n";
         amrex::Print() << "    mol. weight: " << m_mol_weight << "\n";
         amrex::Print() << "    latent heat (vap.): " << m_lat_vap << "\n";
         amrex::Print() << "    Rv: " << m_Rv << "\n";
         amrex::Print() << "    Tc: " << m_Tc << "\n";
         amrex::Print() << "    Tb: " << m_Tb << "\n";
         amrex::Print() << "    N_av/mol.weight: " << m_Nav_by_molweight << "\n";
         amrex::Print() << "    mol. Cp coeffs: ";
         for (int i = 0; i < 7; i++) { amrex::Print() << m_mol_Cp_coeffs[i] << ", "; }
         amrex::Print() << "\n";
     }
setProperties_agua()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_agua ()
Set this material to agua.
 {
     setProperties_H2O();
 }
setProperties_H2O()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_H2O ()
Set this material to H20.
 {
     m_density = rhor; // ERF_Constants.H
     m_ionization = 0;
     m_mol_weight = Real(1.802e-02); // kg mol^-1
     m_lat_vap = L_v; // ERF_Constants.H
     m_Rv = R_v; // ERF_Constants.H
     m_Tb = Real(373.15); // K
     m_Nav_by_molweight = s_N_av / m_mol_weight;
     m_is_water = true;
     AMREX_IF_ON_HOST((
         m_saturation_pressure_func = saturation_funcs::compute_saturation_pressure_H2O;
         m_saturation_vapfrac_func = saturation_funcs::compute_saturation_vapfrac_H2O;
     ))
 }
setProperties_NaCl()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_NaCl ()
Set this material to NaCl.
 {
     m_density = Real(2170.0);
     m_ionization = 2;
     m_mol_weight = Real(5.844e-02); //kg mol^-1
     m_saturation_pressure_func = nullptr;
     m_saturation_vapfrac_func = nullptr;
 }
setProperties_NH42SO4()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_NH42SO4 ()
Set this material to ammonium sulfate.
 {
     m_density = Real(1770.0);
     m_ionization = 3; // 2xNH4 + 1xSO4
     m_mol_weight = Real(1.3214e-01); //kg mol^-1
     m_saturation_pressure_func = nullptr;
     m_saturation_vapfrac_func = nullptr;
 }
setProperties_NH4HSO4()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_NH4HSO4 ()
Set this material to ammonium bisulfate.
 {
     m_density = Real(1780.0);
     m_ionization = 2; // NH4+ and HSO4-
     m_mol_weight = Real(1.1511e-01); //kg mol^-1
     m_saturation_pressure_func = nullptr;
     m_saturation_vapfrac_func = nullptr;
 }
setProperties_soil()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_soil ()
Set this material to soil.
 {
     m_density = Real(1220.0); // loose dry dirt
     m_ionization = 0;
     m_saturation_pressure_func = nullptr;
     m_saturation_vapfrac_func = nullptr;
 }
setProperties_water()
AMREX_GPU_HOST_DEVICE void MaterialProperties::setProperties_water ()
Set this material to water.
 {
     setProperties_H2O();
 }
Member Data Documentation
m_name
Species::Name MaterialProperties::m_name = Species::Name::none
name
Referenced by MaterialProperties(), and print().
m_saturation_pressure_func
decltype(saturation_funcs::compute_saturation_pressure_null) * MaterialProperties::m_saturation_pressure_func = nullptr
pointer to function to compute saturation pressure
Referenced by computeSaturationPressure(), and MaterialProperties().
m_saturation_vapfrac_func
decltype(saturation_funcs::compute_saturation_vapfrac_null) * MaterialProperties::m_saturation_vapfrac_func = nullptr
pointer to function to compute vapour fraction
Referenced by computeSaturationVapFrac(), and MaterialProperties().
The documentation for this struct was generated from the following files:
Source/MaterialProperties/ERF_MaterialProperties.H
Source/MaterialProperties/ERF_MaterialProperties.cpp