ERF: TimeInterpolatedData Struct Reference
TimeInterpolatedData Struct Reference
#include <TimeInterpolatedData.H>
Public Member Functions
TimeInterpolatedData ()
TimeInterpolatedData (Real time)
~TimeInterpolatedData ()
void set_time (Real time)
Real get_time ()
void add_var (MultiFab *var_data, int own_data)
MultiFab & get_var (int var_idx)
int num_vars ()
void clear ()
Public Attributes
const int owning = 1
const int non_owning = 0
Private Attributes
Vector< MultiFab * > m_data
Vector< int > m_owns_data
Real m_time
Constructor & Destructor Documentation
TimeInterpolatedData() [1/2]
TimeInterpolatedData::TimeInterpolatedData () inline
 {}
TimeInterpolatedData() [2/2]
TimeInterpolatedData::TimeInterpolatedData (Real time) inline
 : m_time(time) {}
~TimeInterpolatedData()
TimeInterpolatedData::~TimeInterpolatedData () inline
{
         clear();
     }
Member Function Documentation
add_var()
void TimeInterpolatedData::add_var (MultiFab * var_data, int own_data) inline
{
         m_data.push_back(var_data);
         m_owns_data.push_back(own_data);
     }
Referenced by ERF::GetDataAtTime().
clear()
void TimeInterpolatedData::clear () inline
                  {
         // clear all data owned by this object
         for (int i = 0; i < num_vars(); ++i) {
             if (m_owns_data[i] == owning) {
                 m_data[i]->clear();
                 delete m_data[i];
             }
         }
         // clear internal memory
         m_data.clear();
         m_owns_data.clear();
         m_time = 0.;
     }
get_time()
Real TimeInterpolatedData::get_time () inline
 { return m_time; }
Referenced by ERF::FillCoarsePatch(), ERF::FillIntermediatePatch(), and ERF::FillPatch().
get_var()
MultiFab& TimeInterpolatedData::get_var (int var_idx) inline
{
         return *m_data[var_idx];
     }
Referenced by ERFPhysBCFunct::ERFPhysBCFunct(), ERF::FillCoarsePatch(), ERF::FillIntermediatePatch(), ERF::FillPatch(), and ERFPhysBCFunct::operator()().
num_vars()
int TimeInterpolatedData::num_vars () inline
 { return m_data.size(); }
set_time()
void TimeInterpolatedData::set_time (Real time) inline
{
         m_time = time;
     }
Referenced by ERF::GetDataAtTime().
Member Data Documentation
m_data
Vector<MultiFab*> TimeInterpolatedData::m_data private
m_owns_data
Vector<int> TimeInterpolatedData::m_owns_data private
m_time
Real TimeInterpolatedData::m_time private
non_owning
const int TimeInterpolatedData::non_owning = 0
Referenced by ERF::GetDataAtTime().
owning
const int TimeInterpolatedData::owning = 1
Referenced by ERF::GetDataAtTime().
The documentation for this struct was generated from the following file:
/home/runner/work/ERF/ERF/Source/TimeInterpolatedData.H