ERF: /home/runner/work/ERF/ERF/Source/SpatialStencils/TerrainMetrics.H File Reference
TerrainMetrics.H File Reference
#include <AMReX.H>
#include <AMReX_Geometry.H>
#include <AMReX_MultiFab.H>
#include <IndexDefines.H>
Functions
void init_terrain_grid (int lev, amrex::Geometry &geom, amrex::MultiFab &z_phys_nd)
AMREX_GPU_DEVICE void ComputeMetricAtCellCenter (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE void ComputeMetricAtIface (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE void ComputeMetricAtJface (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE void ComputeMetricAtKface (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE void ComputeMetricAtEdgeCenterK (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE void ComputeMetricAtEdgeCenterJ (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE void ComputeMetricAtEdgeCenterI (const int &i, const int &j, const int &k, amrex::Real &met_h_xi, amrex::Real &met_h_eta, amrex::Real &met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &cellSizeInv, const amrex::Array4< const amrex::Real > &z_nd, const int flag)
AMREX_GPU_DEVICE amrex::Real OmegaFromW (int i, int j, int k, amrex::Real w, const amrex::Array4< const amrex::Real > u, const amrex::Array4< const amrex::Real > v, const amrex::Array4< const amrex::Real > z_nd, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv)
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WFromOmega (int i, int j, int k, amrex::Real omega, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &z_nd, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv)
AMREX_GPU_DEVICE amrex::Real WFromOmegaBC (int i, int j, int k, amrex::Real omega, const amrex::Array4< const amrex::Real > &u, const amrex::Array4< const amrex::Real > &v, const amrex::Array4< const amrex::Real > &z_nd, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > &dxInv)
void make_metrics (amrex::Geometry &geom, amrex::MultiFab &z_phys_nd, amrex::MultiFab &z_phys_cc, amrex::MultiFab &detJ_cc)
Function Documentation
ComputeMetricAtCellCenter()
AMREX_GPU_DEVICE void ComputeMetricAtCellCenter (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi   = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) - z_nd(i  ,j,k+1) - z_nd(i  ,j+1,k+1) );
     break;
   case TerrainMet::h_eta:
     met_h_eta  = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) - z_nd(i,j  ,k+1) - z_nd(i+1,j  ,k+1) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = 0.25 * dzInv *
       ( z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1) + z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
        -z_nd(i+1,j,k  ) - z_nd(i+1,j+1,k  ) - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi   = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) - z_nd(i  ,j,k+1) - z_nd(i  ,j+1,k+1) );
     met_h_eta  = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) - z_nd(i,j  ,k+1) - z_nd(i+1,j  ,k+1) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi   = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) - z_nd(i  ,j,k+1) - z_nd(i  ,j+1,k+1) );
     met_h_zeta = 0.25 * dzInv *
       ( z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1) + z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
        -z_nd(i+1,j,k  ) - z_nd(i+1,j+1,k  ) - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
      break;
   case TerrainMet::h_eta_zeta:
     met_h_eta  = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) - z_nd(i,j  ,k+1) - z_nd(i+1,j  ,k+1) );
     met_h_zeta = 0.25 * dzInv *
       ( z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1) + z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
        -z_nd(i+1,j,k  ) - z_nd(i+1,j+1,k  ) - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
     break;
   default:
     met_h_xi   = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) - z_nd(i  ,j,k+1) - z_nd(i  ,j+1,k+1) );
     met_h_eta  = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) - z_nd(i,j  ,k+1) - z_nd(i+1,j  ,k+1) );
     met_h_zeta = 0.25 * dzInv *
       ( z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k+1) + z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
        -z_nd(i+1,j,k  ) - z_nd(i+1,j+1,k  ) - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
   }
 }
ComputeMetricAtEdgeCenterI()
AMREX_GPU_DEVICE void ComputeMetricAtEdgeCenterI (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi  = dxInv * ( z_nd(i+1,j,k) - z_nd(i,j,k) );
     break;
   case TerrainMet::h_eta:
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i+1,j+1,k) + z_nd(i,j+1,k)
        -z_nd(i+1,j-1,k) - z_nd(i,j-1,k) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) );
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi  = dxInv * ( z_nd(i+1,j,k) - z_nd(i,j,k) );
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i+1,j+1,k) + z_nd(i,j+1,k)
        -z_nd(i+1,j-1,k) - z_nd(i,j-1,k) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi  = dxInv * ( z_nd(i+1,j,k) - z_nd(i,j,k) );
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) );
     break;
   case TerrainMet::h_eta_zeta:
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i+1,j+1,k) + z_nd(i,j+1,k)
        -z_nd(i+1,j-1,k) - z_nd(i,j-1,k) );
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) );
     break;
   default:
     met_h_xi  = dxInv * ( z_nd(i+1,j,k) - z_nd(i,j,k) );
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i+1,j+1,k) + z_nd(i,j+1,k)
        -z_nd(i+1,j-1,k) - z_nd(i,j-1,k) );
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) );
   }
 }
ComputeMetricAtEdgeCenterJ()
AMREX_GPU_DEVICE void ComputeMetricAtEdgeCenterJ (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi = 0.25 * dxInv *
       ( z_nd(i+1,j+1,k) + z_nd(i+1,j  ,k)
        -z_nd(i-1,j+1,k) - z_nd(i-1,j  ,k) );
     break;
   case TerrainMet::h_eta:
     met_h_eta = dyInv * ( z_nd(i,j+1,k) - z_nd(i,j,k) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i,j+1,k-1) );
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi = 0.25 * dxInv *
       ( z_nd(i+1,j+1,k) + z_nd(i+1,j  ,k)
        -z_nd(i-1,j+1,k) - z_nd(i-1,j  ,k) );
     met_h_eta = dyInv * ( z_nd(i,j+1,k) - z_nd(i,j,k) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi = 0.25 * dxInv *
       ( z_nd(i+1,j+1,k) + z_nd(i+1,j  ,k)
        -z_nd(i-1,j+1,k) - z_nd(i-1,j  ,k) );
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i,j+1,k-1) );
      break;
   case TerrainMet::h_eta_zeta:
     met_h_eta = dyInv * ( z_nd(i,j+1,k) - z_nd(i,j,k) );
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i,j+1,k-1) );
     break;
   default:
     met_h_xi = 0.25 * dxInv *
       ( z_nd(i+1,j+1,k) + z_nd(i+1,j  ,k)
        -z_nd(i-1,j+1,k) - z_nd(i-1,j  ,k) );
     met_h_eta = dyInv * ( z_nd(i,j+1,k) - z_nd(i,j,k) );
     met_h_zeta = 0.25 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                  -z_nd(i,j,k-1) - z_nd(i,j+1,k-1) );
   }
 }
ComputeMetricAtEdgeCenterK()
AMREX_GPU_DEVICE void ComputeMetricAtEdgeCenterK (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi  = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) );
     break;
   case TerrainMet::h_eta:
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = dzInv * (z_nd(i,j,k+1) - z_nd(i,j,k));
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi  = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) );
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi  = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) );
     met_h_zeta = dzInv * (z_nd(i,j,k+1) - z_nd(i,j,k));
      break;
   case TerrainMet::h_eta_zeta:
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) );
     met_h_zeta = dzInv * (z_nd(i,j,k+1) - z_nd(i,j,k));
     break;
   default:
     met_h_xi  = 0.25 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) );
     met_h_eta = 0.25 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) );
     met_h_zeta = dzInv * (z_nd(i,j,k+1) - z_nd(i,j,k));
   }
 }
ComputeMetricAtIface()
AMREX_GPU_DEVICE void ComputeMetricAtIface (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi   = 0.125 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) - z_nd(i-1,j+1,k) - z_nd(i-1,j+1,k+1) );
     break;
   case TerrainMet::h_eta:
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j,k  ) + z_nd(i,j  ,k+1)
                                - z_nd(i,j+1,k) - z_nd(i,j+1,k+1) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi   = 0.125 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) - z_nd(i-1,j+1,k) - z_nd(i-1,j+1,k+1) );
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j,k  ) + z_nd(i,j  ,k+1)
                                - z_nd(i,j+1,k) - z_nd(i,j+1,k+1) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi   = 0.125 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) - z_nd(i-1,j+1,k) - z_nd(i-1,j+1,k+1) );
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
      break;
   case TerrainMet::h_eta_zeta:
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j,k  ) + z_nd(i,j  ,k+1)
                                - z_nd(i,j+1,k) - z_nd(i,j+1,k+1) );
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
     break;
   default:
     met_h_xi   = 0.125 * dxInv *
       ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i-1,j,k) - z_nd(i-1,j,k+1) - z_nd(i-1,j+1,k) - z_nd(i-1,j+1,k+1) );
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j,k  ) + z_nd(i,j  ,k+1)
                                - z_nd(i,j+1,k) - z_nd(i,j+1,k+1) );
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i,j+1,k+1)
                                - z_nd(i,j,k  ) - z_nd(i,j+1,k  ) );
   }
 }
Referenced by AdvectionSrcForState(), erf_fast_rhs(), erf_slow_rhs(), and ERF::WritePlotFile().
ComputeMetricAtJface()
AMREX_GPU_DEVICE void ComputeMetricAtJface (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j,k+1) );
     break;
   case TerrainMet::h_eta:
     met_h_eta  = 0.125 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) - z_nd(i+1,j-1,k) - z_nd(i+1,j-1,k+1) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                - z_nd(i,j,k  ) - z_nd(i+1,j,k  ) );
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j,k+1) );
     met_h_eta  = 0.125 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) - z_nd(i+1,j-1,k) - z_nd(i+1,j-1,k+1) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j,k+1) );
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                - z_nd(i,j,k  ) - z_nd(i+1,j,k  ) );
      break;
   case TerrainMet::h_eta_zeta:
     met_h_eta  = 0.125 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) - z_nd(i+1,j-1,k) - z_nd(i+1,j-1,k+1) );
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                - z_nd(i,j,k  ) - z_nd(i+1,j,k  ) );
     break;
   default:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j,k+1)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j,k+1) );
     met_h_eta  = 0.125 * dyInv *
       ( z_nd(i,j+1,k) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j-1,k) - z_nd(i,j-1,k+1) - z_nd(i+1,j-1,k) - z_nd(i+1,j-1,k+1) );
     met_h_zeta = 0.5 * dzInv * ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1)
                                - z_nd(i,j,k  ) - z_nd(i+1,j,k  ) );
   }
 }
Referenced by AdvectionSrcForState(), erf_fast_rhs(), erf_slow_rhs(), and ERF::WritePlotFile().
ComputeMetricAtKface()
AMREX_GPU_DEVICE void ComputeMetricAtKface (const int & i, const int & j, const int & k, amrex::Real & met_h_xi, amrex::Real & met_h_eta, amrex::Real & met_h_zeta, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & cellSizeInv, const amrex::Array4< const amrex::Real > & z_nd, const int flag) inline
 {
   met_h_xi   = 0.0;
   met_h_eta  = 0.0;
   met_h_zeta = 0.0;
   amrex::Real dxInv = cellSizeInv[0];
   amrex::Real dyInv = cellSizeInv[1];
   amrex::Real dzInv = cellSizeInv[2];
   switch(flag) {
   case TerrainMet::h_xi:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) );
     break;
   case TerrainMet::h_eta:
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) );
     break;
   case TerrainMet::h_zeta:
     met_h_zeta = 0.125 * dzInv *
       ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) - z_nd(i,j+1,k-1) - z_nd(i+1,j+1,k-1) );
     break;
   case TerrainMet::h_xi_eta:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) );
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) );
     break;
   case TerrainMet::h_xi_zeta:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) );
     met_h_zeta = 0.125 * dzInv *
       ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) - z_nd(i,j+1,k-1) - z_nd(i+1,j+1,k-1) );
      break;
   case TerrainMet::h_eta_zeta:
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) );
     met_h_zeta = 0.125 * dzInv *
       ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) - z_nd(i,j+1,k-1) - z_nd(i+1,j+1,k-1) );
     break;
   default:
     met_h_xi   = 0.5 * dxInv * ( z_nd(i+1,j,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i  ,j,k) - z_nd(i  ,j+1,k) );
     met_h_eta  = 0.5 * dyInv * ( z_nd(i,j+1,k) + z_nd(i+1,j+1,k)
                                 -z_nd(i,j  ,k) - z_nd(i+1,j  ,k) );
     met_h_zeta = 0.125 * dzInv *
       ( z_nd(i,j,k+1) + z_nd(i+1,j,k+1) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
        -z_nd(i,j,k-1) - z_nd(i+1,j,k-1) - z_nd(i,j+1,k-1) - z_nd(i+1,j+1,k-1) );
   }
 }
Referenced by erf_slow_rhs().
init_terrain_grid()
void init_terrain_grid (int lev, amrex::Geometry & geom, amrex::MultiFab & z_phys_nd)
 {
   auto dx = geom.CellSizeArray();
   auto ProbHiArr = geom.ProbHiArray();
   auto ProbLoArr = geom.ProbLoArray();
   // z_nd is nodal in all directions
   const amrex::Box& dbx = geom.Domain();
   int imin = dbx.smallEnd(0); int imax = dbx.bigEnd(0) + 1;
   int jmin = dbx.smallEnd(1); int jmax = dbx.bigEnd(1) + 1;
   int kmin = dbx.smallEnd(2); int kmax = dbx.bigEnd(2) + 1;
   // User-selected method from inputs file (BTF default)
   amrex::ParmParse pp("erf");
   int terrain_smoothing = 0;
   pp.query("terrain_smoothing", terrain_smoothing);
   switch(terrain_smoothing) {
     case 0: // BTF Method
     {
       //********************************************************************************
       // Populate z_nd in valid box and account for domain boundary cells (zero grad).
       // Top and bottom z boundary populated at end (fillboundary doesn't touch these)
       //********************************************************************************
       int k0 = 0;
       amrex::Real ztop = ProbHiArr[2];
       // WoA terms to compute ghost cell values
       amrex::Real a = 0.5;
       amrex::Real num = 8 * a * a * a;
       amrex::Real xcen = 0.5 * (ProbLoArr[0] + ProbHiArr[0]);
       amrex::Real ycen = 0.5 * (ProbLoArr[1] + ProbHiArr[1]);
       for ( amrex::MFIter mfi(z_phys_nd, amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi )
       {
           //use valid box to get domain bounds in all cases
           const amrex::Box& vbx = mfi.validbox();
           amrex::Array4<amrex::Real> const& z_arr = z_phys_nd.array(mfi);
           // Does the box border the domain
           int limin = vbx.smallEnd(0); int limax = vbx.bigEnd(0);
           int ljmin = vbx.smallEnd(1); int ljmax = vbx.bigEnd(1);
           int lkmax = vbx.bigEnd(2);
           int bxflag  = (limin == imin || limax == imax) ? 1 : 0;
           int byflag  = (ljmin == jmin || ljmax == jmax) ? 1 : 0;
           amrex::Box xybx;
           if (lev > 0) {
               xybx = mfi.growntilebox(1);
               xybx.setRange(2,0,lkmax+1);
           }
           else
               xybx = vbx;
           ParallelFor(xybx, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
               // Location of nodes
               amrex::Real x = (i * dx[0] - xcen);
               amrex::Real y = (j * dx[1] - ycen);
               amrex::Real z =  k * dx[2];
               // WoA Hill for ghost points
               amrex::Real height = num / (x*x + 4*a*a);
               // YZ plane ghost cells
               if(i<limin) z_arr(i,j,k) = height;
               if(i>limax) z_arr(i,j,k) = height;
               // XZ plane ghost cells
               if(j<ljmin) z_arr(i,j,k) = height;
               if(j>ljmax) z_arr(i,j,k) = height;
               // Corner cells along z
               if(i<limin && j<ljmin) z_arr(i,j,k) = height;
               if(i>limax && j>ljmax) z_arr(i,j,k) = height;
               if(i<limin && j>ljmax) z_arr(i,j,k) = height;
               if(i>limax && j<ljmin) z_arr(i,j,k) = height;
               // Fill non-ghost cells with BTF model from p2163 of Klemp2011
               z_arr(i,j,k) = z + (1. - (z/ztop)) * z_arr(i,j,k0);
               // Fill boundary cells if needed
               if(bxflag || byflag) terrain_fill_domain_bndry_XY(i, j, k, limin, ljmin, limax, ljmax, z_arr(i,j,k), z_arr);
           });
         }
         break;
     }
     case 1: // STF Method
     {
         // Get Multifab spanning domain with 1 level of ghost cells
         amrex::MultiFab h_mf(z_phys_nd.boxArray(), z_phys_nd.DistributionMap(), 1, 1);
         amrex::MultiFab h_mf_old(z_phys_nd.boxArray(), z_phys_nd.DistributionMap(), 1, 1);
         // Save max height for smoothing
         amrex::Real max_h;
         // Crete 2D MF without allocation
         amrex::MultiFab mf2d;
         {
             amrex::BoxList bl2d = h_mf.boxArray().boxList();
             for (auto& b : bl2d) {
                 b.setRange(2,0);
             }
             amrex::BoxArray ba2d(std::move(bl2d));
             mf2d = amrex::MultiFab(ba2d, h_mf.DistributionMap(), 1, 0, amrex::MFInfo().SetAlloc(false));
         }
         // Get MultiArray4s from the multifabs
         amrex::MultiArray4<amrex::Real> const& ma_h_s     = h_mf.arrays();
         amrex::MultiArray4<amrex::Real> const& ma_h_s_old = h_mf_old.arrays();
         amrex::MultiArray4<amrex::Real> const& ma_z_phys  = z_phys_nd.arrays();
         // Get max value
         max_h = ParReduce(amrex::TypeList<amrex::ReduceOpMax>{}, amrex::TypeList<amrex::Real>{}, mf2d, amrex::IntVect(0),
                     [=] AMREX_GPU_DEVICE (int box_no, int i, int j, int) noexcept
                         -> amrex::GpuTuple<amrex::Real>
                 {
                   // Bottom boundary
                   int k0 = 0;
                   // Get Array4s
                   auto& h     = ma_h_s[box_no];
                   auto& z_arr = ma_z_phys[box_no];
                   // Does the box border the domain?
                   int limin = lbound(h).x; int limax = ubound(h).x;
                   int ljmin = lbound(h).y; int ljmax = ubound(h).y;
                   int bxflag  = (limin == imin || limax == imax) ? 1 : 0;
                   int byflag  = (ljmin == jmin || ljmax == jmax) ? 1 : 0;
                   // Populate h with terrain
                   h(i,j,k0) = z_arr(i,j,k0);
                   // Fill boundary cells if needed
                   if(bxflag || byflag){
                     terrain_fill_domain_bndry_XY(i, j, k0, imin, jmin, imax, jmax, z_arr(i,j,k0), z_arr);
                     terrain_fill_domain_bndry_XY(i, j, k0, imin, jmin, imax, jmax, z_arr(i,j,k0), h    );
                   }
                   // Return height for max
                   return { z_arr(i,j,k0) };
                 });
         // Fill ghost cells (neglects domain boundary)
         h_mf.FillBoundary(geom.periodicity());
         // Make h_mf copy for old values
         amrex::MultiFab::Copy(h_mf_old, h_mf,0,0,1,1);
         // Populate h_mf at k>0 with h_s, solving in ordered 2D slices
         for (int k = kmin+1; k <= kmax; k++) // skip terrain level
         {
             amrex::Real zz = k * dx[2];
             amrex::Real zz_minus = (k - 1) * dx[2];
             amrex::Real gamma_m = 0.5; // min allowed fractional grid spacing
             amrex::Real z_H = 2.44/(1-gamma_m);
             amrex::Real foo = cos((PI/2)*(zz/z_H));
             amrex::Real A;
             if(zz < z_H) { A = foo*foo*foo*foo*foo*foo; } // A controls rate of return to atm
             else         { A = 0; }
             amrex::Real foo_minus = cos((PI/2)*(zz_minus/z_H));
             amrex::Real A_minus;
             if(zz_minus < z_H) { A_minus = foo_minus*foo_minus*foo_minus*foo_minus*foo_minus*foo_minus; } // A controls rate of return to atm
             else               { A_minus = 0; }
             unsigned maxIter = 50; // M_k in paper
             unsigned iter = 0;
             amrex::Real threshold = gamma_m;
             amrex::Real diff = 1.e20;
             while (iter < maxIter && diff > threshold)
             {
                 diff = ParReduce(amrex::TypeList<amrex::ReduceOpMin>{}, amrex::TypeList<amrex::Real>{}, mf2d, amrex::IntVect(0),
                     [=] AMREX_GPU_DEVICE (int box_no, int i, int j, int) noexcept
                         -> amrex::GpuTuple<amrex::Real>
                 {
                     auto& h_s     = ma_h_s[box_no];
                     auto& h_s_old = ma_h_s_old[box_no];
                     amrex::Real h_m    = max_h; //high point of hill
                     amrex::Real beta_k = 0.2*std::min(zz/(2*h_m),1.0); //smoothing coefficient
                     if (iter == 0) {
                         h_s(i,j,k) = h_s_old(i,j,k-1) + beta_k*(h_s_old(i+1,j  ,k-1)
                                                               + h_s_old(i-1,j  ,k-1)
                                                               + h_s_old(i  ,j+1,k-1)
                                                               + h_s_old(i  ,j-1,k-1) - 4*h_s_old(i,j,k-1));
                     }
                     else {
                         h_s(i,j,k) = h_s_old(i,j,k) + beta_k*(h_s_old(i+1,j  ,k)
                                                             + h_s_old(i-1,j  ,k)
                                                             + h_s_old(i  ,j+1,k)
                                                             + h_s_old(i  ,j-1,k) - 4*h_s_old(i,j,k));
                     }
                     return { (zz + A * h_s(i,j,k) - (zz_minus + A_minus * h_s(i,j,k-1))) / (zz - zz_minus) };
                 }); //ParReduce
                 ParallelFor(mf2d, amrex::IntVect(1,1,0),
                     [=] AMREX_GPU_DEVICE (int box_no, int i, int j, int)
                 {
                     ma_h_s_old[box_no](i,j,k) = ma_h_s[box_no](i,j,k);
                     // Fill boundary cells
                     terrain_fill_domain_bndry_XY(i, j, k, imin, jmin, imax, jmax, ma_h_s[box_no](i,j,k), ma_h_s_old[box_no]);
                 });
                 amrex::ParallelDescriptor::ReduceRealMin(diff);
                 iter++;
                 //fill ghost points
                 h_mf_old.FillBoundary(geom.periodicity());
             } //while
             //Populate z_phys_nd by solving z_arr(i,j,k) = z + A*h_s(i,j,k)
             for ( amrex::MFIter mfi(z_phys_nd, amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi )
             {
                 // Only loop the XY-plane of valid box
                 const amrex::Box& vbx = mfi.validbox();
                 amrex::Box xybx = vbx;
                 xybx.setRange(2,0);
                 amrex::Array4<amrex::Real> const& h_s   = h_mf_old.array(mfi);
                 amrex::Array4<amrex::Real> const& z_arr = z_phys_nd.array(mfi);
                 // Does the box border the domain?
                 int limin = vbx.smallEnd(0); int limax = vbx.bigEnd(0);
                 int ljmin = vbx.smallEnd(1); int ljmax = vbx.bigEnd(1);
                 int bxflag  = (limin == imin || limax == imax) ? 1 : 0;
                 int byflag  = (ljmin == jmin || ljmax == jmax) ? 1 : 0;
                 ParallelFor(xybx, [=] AMREX_GPU_DEVICE (int i, int j, int) {
                     // Location of nodes
                     amrex::Real z = k * dx[2];
                     // STF model from p2164 of Klemp2011
                     z_arr(i,j,k) = z + A*h_s(i,j,k);
                     // Fill boundary cells if needed
                     if(bxflag || byflag) terrain_fill_domain_bndry_XY(i, j, k, imin, jmin, imax, jmax, z_arr(i,j,k), z_arr);
                 });
             }//mfi
         } //k
         amrex::Gpu::streamSynchronize();
         break;
       }
   } //switch
   // Fill ghost layers and corners
   z_phys_nd.FillBoundary(geom.periodicity());
   //********************************************************************************
   // Populate domain boundary cells in z-direction
   //********************************************************************************
   for ( amrex::MFIter mfi(z_phys_nd, amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi )
   {
        // Only loop the XY-plane of grown box
        const amrex::Box& vbx = mfi.growntilebox(1);
        amrex::Box xybx = vbx;
        xybx.setRange(2,0);
        amrex::Array4<amrex::Real> const& z_arr = z_phys_nd.array(mfi);
        ParallelFor(xybx, [=] AMREX_GPU_DEVICE (int i, int j, int ) {
            // Extrapolate top/bottom layer
            z_arr(i,j,kmin-1) = 2.0*z_arr(i,j,kmin) - z_arr(i,j,kmin+1);
            z_arr(i,j,kmax+1) = 2.0*z_arr(i,j,kmax) - z_arr(i,j,kmax-1);
            });
   }
   /*
   // Debug
   for ( amrex::MFIter mfi(z_phys_nd, amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi )
   {
        const amrex::Box& gbx = mfi.growntilebox(1);
        amrex::Print() << "Ann print: " << z_phys_nd[mfi].box() << std::endl;
        amrex::Array4<amrex::Real> z_arr = z_phys_nd.array(mfi);
        int rank = 0;
        amrex::Print(rank) << gbx << "\n";
        ParallelFor(gbx, [=] AMREX_GPU_DEVICE (int i, int j, int k) {
            amrex::Print(rank) << amrex::IntVect(i,j,k) << "\n";
            amrex::Print(rank) << z_arr(i,j,k) << "\n";
            amrex::Print(rank) << "\n";
        });
    }
   */
 }
Referenced by ERF::InitData().
make_metrics()
void make_metrics (amrex::Geometry & geom, amrex::MultiFab & z_phys_nd, amrex::MultiFab & z_phys_cc, amrex::MultiFab & detJ_cc) inline
 {
     auto dx = geom.CellSize();
     amrex::Real dzInv = 1.0/dx[2];
 #ifdef _OPENMP
 #pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
 #endif
     for ( amrex::MFIter mfi(z_phys_cc, amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi )
     {
         const amrex::Box& gbx = mfi.growntilebox(1);
         amrex::Array4<amrex::Real const> z_nd = z_phys_nd.const_array(mfi);
         amrex::Array4<amrex::Real      > z_cc = z_phys_cc.array(mfi);
         amrex::Array4<amrex::Real      > detJ = detJ_cc.array(mfi);
         amrex::ParallelFor(gbx, [=]
            AMREX_GPU_DEVICE(int i, int j, int k) noexcept {
                z_cc(i, j, k) = .125 * (
                        z_nd(i,j,k  ) + z_nd(i+1,j,k  ) + z_nd(i,j+1,k  ) + z_nd(i+1,j+1,k  )
                       +z_nd(i,j,k+1) + z_nd(i+1,j,k+1) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1) );
                detJ(i, j, k) = .25 * dzInv * (
                        z_nd(i,j,k+1) + z_nd(i+1,j,k+1) + z_nd(i,j+1,k+1) + z_nd(i+1,j+1,k+1)
                       -z_nd(i,j,k  ) - z_nd(i+1,j,k  ) - z_nd(i,j+1,k  ) - z_nd(i+1,j+1,k  ) );
                });
     }
     detJ_cc.FillBoundary(geom.periodicity());
 }
Referenced by ERF::InitData().
OmegaFromW()
AMREX_GPU_DEVICE amrex::Real OmegaFromW (int i, int j, int k, amrex::Real w, const amrex::Array4< const amrex::Real > u, const amrex::Array4< const amrex::Real > v, const amrex::Array4< const amrex::Real > z_nd, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv) inline
 {
   // This is dh/dxi at z-face (i,j,k-1/2)
   amrex::Real met_zlo_xi   = 0.5 * dxInv[0] *
     ( z_nd(i+1,j+1,k  ) + z_nd(i+1,j  ,k  )    // hi i, lo k
      -z_nd(i  ,j+1,k  ) - z_nd(i  ,j  ,k  ) ); // lo i, lo k
   // This is dh/deta at z-face (i,j,k-1/2)
   amrex::Real met_zlo_eta  = 0.5 * dxInv[1] *
     ( z_nd(i+1,j+1,k  ) + z_nd(i  ,j+1,k  )    // hi j, lo k
      -z_nd(i+1,j  ,k  ) - z_nd(i  ,j  ,k  ) ); // lo j, lo k
   // Use extrapolation instead of interpolation if at the bottom boundary
   amrex::Real vec_zlo_xi   = (k == 0) ? 1.5 * (0.5*(u(i,j,k)+u(i+1,j,k))) - 0.5*(0.5*(u(i,j,k+1)+u(i+1,j,k+1))) :
     0.25 * ( u(i,j,k-1) + u(i+1,j,k-1) + u(i,j,k) + u(i+1,j,k) );
   amrex::Real vec_zlo_eta  = (k == 0) ? 1.5 * (0.5*( v(i,j,k)+v(i,j+1,k))) - 0.5*(0.5*(v(i,j,k+1)+v(i,j+1,k+1))) :
     0.25 * ( v(i,j,k-1) + v(i,j+1,k-1) + v(i,j,k) + v(i,j+1,k) );
   amrex::Real omega = -met_zlo_xi * vec_zlo_xi - met_zlo_eta * vec_zlo_eta + w;
   return omega;
 }
Referenced by AdvectionSrcForState(), and erf_fast_rhs().
WFromOmega()
AMREX_GPU_DEVICE AMREX_FORCE_INLINE amrex::Real WFromOmega (int i, int j, int k, amrex::Real omega, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & z_nd, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv)
 {
   // This is dh/dxi at z-face (i,j,k-1/2)
   amrex::Real met_zlo_xi   = 0.5 * dxInv[0] *
     ( z_nd(i+1,j+1,k  ) + z_nd(i+1,j  ,k  )    // hi i, lo k
      -z_nd(i  ,j+1,k  ) - z_nd(i  ,j  ,k  ) ); // lo i, lo k
   // This is dh/deta at z-face (i,j,k-1/2)
   amrex::Real met_zlo_eta  = 0.5 * dxInv[1] *
     ( z_nd(i+1,j+1,k  ) + z_nd(i  ,j+1,k  )    // hi j, lo k
      -z_nd(i+1,j  ,k  ) - z_nd(i  ,j  ,k  ) ); // lo j, lo k
   // Use extrapolation instead of interpolation if at the bottom boundary
   amrex::Real vec_zlo_xi   = (k == 0) ? 1.5 * (0.5*(u(i,j,k)+u(i+1,j,k))) - 0.5*(0.5*(u(i,j,k+1)+u(i+1,j,k+1))) :
     0.25 * ( u(i,j,k-1) + u(i+1,j,k-1) + u(i,j,k) + u(i+1,j,k) );
   amrex::Real vec_zlo_eta  = (k == 0) ? 1.5 * (0.5*( v(i,j,k)+v(i,j+1,k))) - 0.5*(0.5*(v(i,j,k+1)+v(i,j+1,k+1))) :
     0.25 * ( v(i,j,k-1) + v(i,j+1,k-1) + v(i,j,k) + v(i,j+1,k) );
   amrex::Real w = met_zlo_xi * vec_zlo_xi + met_zlo_eta * vec_zlo_eta + omega;
   return w;
 }
Referenced by erf_fast_rhs().
WFromOmegaBC()
AMREX_GPU_DEVICE amrex::Real WFromOmegaBC (int i, int j, int k, amrex::Real omega, const amrex::Array4< const amrex::Real > & u, const amrex::Array4< const amrex::Real > & v, const amrex::Array4< const amrex::Real > & z_nd, const amrex::GpuArray< amrex::Real, AMREX_SPACEDIM > & dxInv) inline
 {
   // Clip metric indices for ghost cell BCs
   amrex::Dim3 hi = ubound(z_nd);
   amrex::Dim3 lo = lbound(z_nd);
   int  im = (i  >= hi.x) ? (hi.x-1) : i;
        im = (im <= lo.x) ? (lo.x+1) : im;
   int  jm = (j  >= hi.y) ? (hi.y-1) : j;
        jm = (jm <= lo.y) ? (lo.y+1) : jm;
   int  km = (k  >= hi.z) ? (hi.z-1) : k;
        km = (km <= lo.z) ? (lo.z+1) : km;
   // This is dh/dxi at z-face (i,j,k-1/2)
   amrex::Real met_zlo_xi   = 0.5 * dxInv[0] *
     ( z_nd(im+1,jm+1,km  ) + z_nd(im+1,jm  ,km  )    // hi i, lo k
      -z_nd(im  ,jm+1,km  ) - z_nd(im  ,jm  ,km  ) ); // lo i, lo k
   // This is dh/deta at z-face (i,j,k-1/2)
   amrex::Real met_zlo_eta  = 0.5 * dxInv[1] *
     ( z_nd(im+1,jm+1,km  ) + z_nd(im  ,jm+1,km  )    // hi j, lo k
      -z_nd(im+1,jm  ,km  ) - z_nd(im  ,jm  ,km  ) ); // lo j, lo k
   // Clip velocity indices for ghost cell BCs
   amrex::Real vec_zlo_xi;
   amrex::Real vec_zlo_eta;
   hi = ubound(u);
   lo = lbound(u);
   hi.z = hi.z + 1; // nodal for W-velocity
   if( k == hi.z) {
     // foextrap to highest k-face
     vec_zlo_xi  = 0.75*( u(i,j,k-1)+u(i+1,j,k-1) ) - 0.25*( u(i,j,k-2)+u(i+1,j,k-2) );
     vec_zlo_eta = 0.75*( v(i,j,k-1)+v(i,j+1,k-1) ) - 0.25*( v(i,j,k-2)+v(i,j+1,k-2) );
   } else if (k == lo.z) {
     // foextrap to lowest k-face
     vec_zlo_xi  = 0.75*( u(i,j,k)+u(i+1,j,k) ) - 0.25*( u(i,j,k+1)+u(i+1,j,k+1) );
     vec_zlo_eta = 0.75*( v(i,j,k)+v(i,j+1,k) ) - 0.25*( v(i,j,k+1)+v(i,j+1,k+1) );
   } else {
     // Valid ghost cell for u & v
     vec_zlo_xi  = 0.25 * ( u(i,j,k-1) + u(i+1,j,k-1) + u(i,j,k) + u(i+1,j,k) );
     vec_zlo_eta = 0.25 * ( v(i,j,k-1) + v(i,j+1,k-1) + v(i,j,k) + v(i,j+1,k) );
   }
   amrex::Real w = met_zlo_xi * vec_zlo_xi + met_zlo_eta * vec_zlo_eta + omega;
   return w;
 }
Referenced by ERFPhysBCFunct::operator()().