ERF: Source/Utils/TileNoZ.H File Reference
TileNoZ.H File Reference
#include <AMReX.H>
Functions
AMREX_FORCE_INLINE amrex::IntVect TileNoZ ()
Function Documentation
TileNoZ()
AMREX_FORCE_INLINE amrex::IntVect TileNoZ ()
Function returns explicit tile size that prevents tiling in z
 {
     if (amrex::TilingIfNotGPU()) {
         return amrex::IntVect{amrex::FabArrayBase::mfiter_tile_size[0],
                               amrex::FabArrayBase::mfiter_tile_size[1],
                               1024000};
     }
     else {
         return amrex::IntVect::TheZeroVector();
     }
 }
Referenced by add_thin_body_sources(), ERF::Advance(), ERF::advance_dycore(), TurbulentPerturbation::calc_tpi_meanMag_perBox(), MOSTAverage::compute_plane_averages(), MOSTAverage::compute_region_averages(), ComputeTurbulentViscosityLES(), ERF::erf_enforce_hse(), erf_fast_rhs_N(), erf_fast_rhs_T(), erf_init_dens_hse(), erf_make_tau_terms(), erf_slow_rhs_pre(), SAM::IceFall(), Kessler::Init(), SAM::Init(), ERF::init_custom(), ERF::init_from_hse(), make_fast_coeffs(), make_sources(), TurbulentPerturbation::netZeroBuoyantAdd(), TurbulentPerturbation::netZeroBuoyantAdjust(), SAM::PrecipFall(), TurbulentPerturbation::pseudoRandomPert(), MOSTAverage::set_k_indices_T(), MOSTAverage::set_norm_indices_T(), MOSTAverage::set_norm_positions_T(), MOSTAverage::set_rotated_fields(), MOSTAverage::set_z_positions_T(), ERF::turbPert_amplitude(), MOSTAverage::write_averages(), MOSTAverage::write_k_indices(), MOSTAverage::write_norm_indices(), and MOSTAverage::write_xz_positions().