ERF: /home/runner/work/ERF/ERF/Source/TimeIntegration/TimeIntegration.H File Reference
TimeIntegration.H File Reference
#include <AMReX.H>
#include <AMReX_MultiFab.H>
#include <AMReX_ArrayLim.H>
#include <AMReX_InterpFaceRegister.H>
#include "DataStruct.H"
#include "IndexDefines.H"
Namespaces
IntVar
Enumerations
enum {
IntVar::cons = 0, IntVar::xmom, IntVar::ymom, IntVar::zmom,
IntVar::xflux, IntVar::yflux, IntVar::zflux
}
Functions
void MomentumToVelocity (MultiFab &xvel_out, MultiFab &yvel_out, MultiFab &zvel_out, const MultiFab &cons_in, const MultiFab &xmom_in, const MultiFab &ymom_in, const MultiFab &zmom_in, const int l_spatial_order, const int ngrow)
void VelocityToMomentum (const MultiFab &xvel_in, const MultiFab &yvel_in, const MultiFab &zvel_in, const MultiFab &cons_in, MultiFab &xmom_out, MultiFab &ymom_out, MultiFab &zmom_out, const int l_spatial_order, const int ngrow)
void erf_advance (int level, MultiFab &cons_old, MultiFab &cons_new, MultiFab &U_old, MultiFab &V_old, MultiFab &W_old, MultiFab &U_new, MultiFab &V_new, MultiFab &W_new, MultiFab &xmom_crse, MultiFab &ymom_crse, MultiFab &zmom_crse, MultiFab &source, std::array< MultiFab, AMREX_SPACEDIM > &flux, const amrex::Geometry crse_geom, const amrex::Geometry fine_geom, const amrex::IntVect ref_ratio, const amrex::Real dt, const amrex::Real time, amrex::InterpFaceRegister *ifr, const SolverChoice &solverChoice, const amrex::Real *dptr_dens_hse, const amrex::Real *dptr_pres_hse, const amrex::Real *dptr_rayleigh_tau, const amrex::Real *dptr_rayleigh_ubar, const amrex::Real *dptr_rayleigh_vbar, const amrex::Real *dptr_rayleigh_thetabar)
void erf_rhs (int level, Vector< MultiFab > &S_rhs, const Vector< MultiFab > &S_data, const MultiFab &S_prim, const MultiFab &xvel, const MultiFab &yvel, const MultiFab &zvel, MultiFab &source, std::array< MultiFab, AMREX_SPACEDIM > &advflux, std::array< MultiFab, AMREX_SPACEDIM > &diffflux, const amrex::Geometry geom, const amrex::Real dt, amrex::InterpFaceRegister *ifr, const SolverChoice &solverChoice, const bool lo_z_is_dirichlet, const bool hi_z_is_dirichlet, const amrex::Real *dptr_dens_hse, const amrex::Real *dptr_pres_hse, const amrex::Real *dptr_rayleigh_tau, const amrex::Real *dptr_rayleigh_ubar, const amrex::Real *dptr_rayleigh_vbar, const amrex::Real *dptr_rayleigh_thetabar)
void erf_fast_rhs (int level, Vector< MultiFab > &S_rhs, const Vector< MultiFab > &S_stage_data, const Vector< MultiFab > &S_data, std::array< MultiFab, AMREX_SPACEDIM > &advflux, std::array< MultiFab, AMREX_SPACEDIM > &diffflux, const amrex::Geometry geom, const amrex::Real dt, amrex::InterpFaceRegister *ifr, const SolverChoice &solverChoice, const amrex::Real *dptr_dens_hse, const amrex::Real *dptr_pres_hse, const amrex::Real *dptr_rayleigh_tau, const amrex::Real *dptr_rayleigh_ubar, const amrex::Real *dptr_rayleigh_vbar, const amrex::Real *dptr_rayleigh_thetabar)
AMREX_GPU_DEVICE Real InterpolateFromCellOrFace (const int &i, const int &j, const int &k, const Array4< const Real > &qty, const int &qty_index, const Real &uadv, const enum Coord &coordDir, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolatePertFromCell (const int &i, const int &j, const int &k, const Array4< const Real > &qty, const int &qty_index, const Real &uadv, const enum Coord &coordDir, const int &spatial_order, const amrex::Real *dptr_hse)
AMREX_GPU_DEVICE Real InterpolateDensityPertFromCellToFace (const int &i, const int &j, const int &k, const Array4< const Real > &cons_in, const Real &uadv, const enum Coord &coordDir, const int &spatial_order, const amrex::Real *dptr_hse)
AMREX_GPU_DEVICE Real AdvectionContributionForXMom (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &u, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionContributionForYMom (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &v, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionContributionForZMom (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &w, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real AdvectionContributionForState (const int &i, const int &j, const int &k, const Array4< const Real > &rho_u, const Array4< const Real > &rho_v, const Array4< const Real > &rho_w, const Array4< const Real > &cell_prim, const int &qty_index, const Array4< Real > &flux_x, const Array4< Real > &flux_y, const Array4< Real > &flux_z, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const int &spatial_order)
AMREX_GPU_DEVICE Real InterpolateTurbulentViscosity (const int &i, const int &j, const int &k, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const Array4< Real > &Ksmag)
Compute K_LES (i-1/2, j+1/2, k) etc given K_LES (i, j, k) is known.
AMREX_GPU_DEVICE Real ComputeStressTerm (const int &i, const int &j, const int &k, const Array4< const Real > &u, const Array4< const Real > &v, const Array4< const Real > &w, const enum MomentumEqn &momentumEqn, const enum DiffusionDir &diffDir, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &Ksmag, const SolverChoice &solverChoice)
AMREX_GPU_DEVICE Real DiffusionContributionForMom (const int &i, const int &j, const int &k, const Array4< const Real > &u, const Array4< const Real > &v, const Array4< const Real > &w, const enum MomentumEqn &momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &Ksmag, const SolverChoice &solverChoice, bool dirichlet_at_lo_k, bool dirichlet_at_hi_k)
AMREX_GPU_DEVICE Real ComputeDiffusionFluxForState (const int &i, const int &j, const int &k, const Array4< const Real > &cell_data, const Array4< const Real > &cell_prim, const int &prim_index, const amrex::Real invCellWidth, const Array4< Real > &Ksmag, const SolverChoice &solverChoice, const enum Coord &coordDir)
AMREX_GPU_DEVICE Real DiffusionContributionForState (const int &i, const int &j, const int &k, const Array4< const Real > &cell_data, const Array4< const Real > &cell_prim, const int &qty_index, const Array4< Real > &flux_x, const Array4< Real > &flux_y, const Array4< Real > &flux_z, const GpuArray< Real, AMREX_SPACEDIM > &cellSize, const Array4< Real > &Ksmag, const SolverChoice &solverChoice)
int ComputeGhostCells (const int &spatial_order)
Function Documentation
AdvectionContributionForState()
AMREX_GPU_DEVICE Real AdvectionContributionForState (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & cell_prim, const int & qty_index, const Array4< Real > & flux_x, const Array4< Real > & flux_y, const Array4< Real > & flux_z, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
Meant for the continuity, energy, and scalar equations
{
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real advectionContribution;
     if (qty_index == Rho_comp)
     {
         xflux(i+1,j,k,qty_index) = rho_u(i+1,j,k);
         xflux(i  ,j,k,qty_index) = rho_u(i  ,j,k);
         yflux(i,j+1,k,qty_index) = rho_v(i,j+1,k);
         yflux(i,j  ,k,qty_index) = rho_v(i,j  ,k);
         zflux(i,j,k+1,qty_index) = rho_w(i,j,k+1);
         zflux(i,j,k  ,qty_index) = rho_w(i,j,k  );
     } else {
         const int prim_index = qty_index - RhoTheta_comp;
         Real uadv_hi = rho_u(i+1,j,k);
         Real uadv_lo = rho_u(i  ,j,k);
         Real vadv_hi = rho_v(i,j+1,k);
         Real vadv_lo = rho_v(i,j  ,k);
         Real wadv_hi = rho_w(i,j,k+1);
         Real wadv_lo = rho_w(i,j,k  );
         xflux(i+1,j,k,qty_index) = rho_u(i+1,j,k) *
             InterpolateFromCellOrFace(i+1, j, k, cell_prim, prim_index, uadv_hi, Coord::x, spatial_order);
         xflux(i  ,j,k,qty_index) = rho_u(i  ,j,k) *
             InterpolateFromCellOrFace(i  , j, k, cell_prim, prim_index, uadv_lo, Coord::x, spatial_order);
         yflux(i,j+1,k,qty_index) = rho_v(i,j+1,k) *
             InterpolateFromCellOrFace(i, j+1, k, cell_prim, prim_index, vadv_hi, Coord::y, spatial_order);
         yflux(i,j  ,k,qty_index) = rho_v(i,j  ,k) *
             InterpolateFromCellOrFace(i, j  , k, cell_prim, prim_index, vadv_lo, Coord::y, spatial_order);
         zflux(i,j,k+1,qty_index) = rho_w(i,j,k+1)*
             InterpolateFromCellOrFace(i, j, k+1, cell_prim, prim_index, wadv_hi, Coord::z, spatial_order);
         zflux(i,j,k  ,qty_index) = rho_w(i,j,k  )*
             InterpolateFromCellOrFace(i, j, k  , cell_prim, prim_index, wadv_lo, Coord::z, spatial_order);
     }
     advectionContribution = (xflux(i+1,j,k,qty_index) - xflux(i  ,j,k,qty_index)) * dxInv
                           + (yflux(i,j+1,k,qty_index) - yflux(i,j  ,k,qty_index)) * dyInv
                           + (zflux(i,j,k+1,qty_index) - zflux(i,j,k  ,qty_index)) * dzInv;
     return advectionContribution;
 }
Referenced by erf_fast_rhs(), and erf_rhs().
AdvectionContributionForXMom()
AMREX_GPU_DEVICE Real AdvectionContributionForXMom (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & u, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
Meant for {x, y, z}- momentum equations
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real rho_u_avg, rho_v_avg, rho_w_avg;
     rho_u_avg = 0.5 * (rho_u(i+1, j, k) + rho_u(i, j, k));
     Real centFluxXXNext = rho_u_avg *
                           InterpolateFromCellOrFace(i+1, j, k, u, 0, rho_u_avg, Coord::x, spatial_order);
     rho_u_avg = 0.5 * (rho_u(i-1, j, k) + rho_u(i, j, k));
     Real centFluxXXPrev = rho_u_avg *
                           InterpolateFromCellOrFace(i  , j, k, u, 0, rho_u_avg, Coord::x, spatial_order);
     rho_v_avg = 0.5 * (rho_v(i, j+1, k) + rho_v(i-1, j+1, k));
     Real edgeFluxXYNext = rho_v_avg *
                           InterpolateFromCellOrFace(i, j+1, k, u, 0, rho_v_avg, Coord::y, spatial_order);
     rho_v_avg = 0.5 * (rho_v(i, j  , k) + rho_v(i-1, j  , k));
     Real edgeFluxXYPrev = rho_v_avg *
                           InterpolateFromCellOrFace(i, j  , k, u, 0, rho_v_avg, Coord::y, spatial_order);
     rho_w_avg = 0.5 * (rho_w(i, j, k+1) + rho_w(i-1, j, k+1));
     Real edgeFluxXZNext = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k+1, u, 0, rho_w_avg, Coord::z, spatial_order);
     rho_w_avg = 0.5 * (rho_w(i, j, k) + rho_w(i-1, j, k));
     Real edgeFluxXZPrev = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k  , u, 0, rho_w_avg, Coord::z, spatial_order);
     Real advectionContribution = (centFluxXXNext - centFluxXXPrev) * dxInv
                                + (edgeFluxXYNext - edgeFluxXYPrev) * dyInv
                                + (edgeFluxXZNext - edgeFluxXZPrev) * dzInv;
     return advectionContribution;
 }
Referenced by erf_rhs().
AdvectionContributionForYMom()
AMREX_GPU_DEVICE Real AdvectionContributionForYMom (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & v, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real rho_u_avg, rho_v_avg, rho_w_avg;
     rho_u_avg = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j-1, k));
     Real edgeFluxYXNext = rho_u_avg *
                           InterpolateFromCellOrFace(i+1, j, k, v, 0, rho_u_avg, Coord::x, spatial_order);
     rho_u_avg = 0.5*(rho_u(i  , j, k) + rho_u(i  , j-1, k));
     Real edgeFluxYXPrev = rho_u_avg *
                           InterpolateFromCellOrFace(i  , j, k, v, 0, rho_u_avg, Coord::x, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j, k) + rho_v(i, j+1, k));
     Real centFluxYYNext = rho_v_avg *
                           InterpolateFromCellOrFace(i, j+1, k, v, 0, rho_v_avg, Coord::y, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j, k) + rho_v(i, j-1, k));
     Real centFluxYYPrev = rho_v_avg *
                           InterpolateFromCellOrFace(i, j  , k, v, 0, rho_v_avg, Coord::y, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j, k+1) + rho_w(i, j-1, k+1));
     Real edgeFluxYZNext = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k+1, v, 0, rho_w_avg, Coord::z, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j, k) + rho_w(i, j-1, k));
     Real edgeFluxYZPrev = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k  , v, 0, rho_w_avg, Coord::z, spatial_order);
     Real advectionContribution = (edgeFluxYXNext - edgeFluxYXPrev) * dxInv
                                + (centFluxYYNext - centFluxYYPrev) * dyInv
                                + (edgeFluxYZNext - edgeFluxYZPrev) * dzInv;
     return advectionContribution;
 }
Referenced by erf_rhs().
AdvectionContributionForZMom()
AMREX_GPU_DEVICE Real AdvectionContributionForZMom (const int & i, const int & j, const int & k, const Array4< const Real > & rho_u, const Array4< const Real > & rho_v, const Array4< const Real > & rho_w, const Array4< const Real > & w, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const int & spatial_order)
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real rho_u_avg, rho_v_avg, rho_w_avg;
     rho_u_avg = 0.5*(rho_u(i+1, j, k) + rho_u(i+1, j, k-1));
     Real edgeFluxZXNext = rho_u_avg *
                           InterpolateFromCellOrFace(i+1, j, k, w, 0, rho_u_avg, Coord::x, spatial_order);
     rho_u_avg = 0.5*(rho_u(i  , j, k) + rho_u(i  , j, k-1));
     Real edgeFluxZXPrev = rho_u_avg *
                           InterpolateFromCellOrFace(i  , j, k, w, 0, rho_u_avg, Coord::x, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j+1, k) + rho_v(i, j+1, k-1));
     Real edgeFluxZYNext = rho_v_avg *
                           InterpolateFromCellOrFace(i, j+1, k, w, 0, rho_v_avg, Coord::y, spatial_order);
     rho_v_avg = 0.5*(rho_v(i, j  , k) + rho_v(i, j  , k-1));
     Real edgeFluxZYPrev = rho_v_avg *
                           InterpolateFromCellOrFace(i, j  , k, w, 0, rho_v_avg, Coord::y, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j  , k+1) + rho_w(i, j, k));
     Real centFluxZZNext = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k+1, w, 0, rho_w_avg, Coord::z, spatial_order);
     rho_w_avg = 0.5*(rho_w(i, j  , k-1) + rho_w(i, j, k));
     Real centFluxZZPrev = rho_w_avg *
                           InterpolateFromCellOrFace(i, j, k  , w, 0, rho_w_avg, Coord::z, spatial_order);
     Real advectionContribution = (edgeFluxZXNext - edgeFluxZXPrev) * dxInv
                                + (edgeFluxZYNext - edgeFluxZYPrev) * dyInv
                                + (centFluxZZNext - centFluxZZPrev) * dzInv;
     return advectionContribution;
 }
Referenced by erf_rhs().
ComputeDiffusionFluxForState()
AMREX_GPU_DEVICE Real ComputeDiffusionFluxForState (const int & i, const int & j, const int & k, const Array4< const Real > & cell_data, const Array4< const Real > & cell_prim, const int & prim_index, const amrex::Real invCellWidth, const Array4< Real > & Ksmag, const SolverChoice & solverChoice, const enum Coord & coordDir)
 {
   // Get indices of states to left and right of the face on which we want the flux
   const int il = i - (coordDir == Coord::x);
   const int ir = i;
   const int jl = j - (coordDir == Coord::y);
   const int jr = j;
   const int kl = k - (coordDir == Coord::z);
   const int kr = k;
   // Get diffusion coefficients
   amrex::Real rhoAlpha_molec;
   amrex::Real Pr_or_Sc_turb_inv;
   amrex::Real rhoFace;
   if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity) {
     rhoFace = (cell_data(il, jl, kl, Rho_comp) + cell_data(ir, jr, kr, Rho_comp)) * 0.5;
   }
   switch(prim_index) {
   case PrimTheta_comp: // Potential Temperature
     if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity) {
         rhoAlpha_molec = rhoFace * solverChoice.alpha_T;
     } else {
         rhoAlpha_molec = solverChoice.rhoAlpha_T;
     }
     Pr_or_Sc_turb_inv = solverChoice.Pr_t_inv;
     break;
   case PrimKE_comp: // Turbulent KE
     if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity) {
         rhoAlpha_molec = rhoFace * solverChoice.alpha_T;
     } else {
         rhoAlpha_molec = solverChoice.rhoAlpha_T;
     }
     Pr_or_Sc_turb_inv = solverChoice.Pr_t_inv;
     break;
   case PrimScalar_comp: // Scalar
     if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity) {
         rhoAlpha_molec = rhoFace * solverChoice.alpha_C;
     } else {
         rhoAlpha_molec = solverChoice.rhoAlpha_C;
     }
     Pr_or_Sc_turb_inv = solverChoice.Sc_t_inv;
     break;
   default:
     amrex::Abort("Error: Diffusion term for the data index isn't implemented");
   }
   amrex::Real rhoAlpha = 0.0;
   switch (solverChoice.molec_diff_type) {
   case MolecDiffType::Constant:
   case MolecDiffType::ConstantDiffusivity:
     rhoAlpha += rhoAlpha_molec;
     break;
   case MolecDiffType::None:
     break;
   default:
     amrex::Abort("Error: Molecular diffusion/viscosity model is unrecognized");
   }
   amrex::Real rhoAlpha_r = 0.0, rhoAlpha_l = 0.0;
   amrex::Real l_sigma_k = solverChoice.sigma_k;
   switch (solverChoice.les_type) {
   case LESType::Smagorinsky:
     // K_LES = 2*mu_t -> extra factor of 0.5 when computing rhoAlpha
     rhoAlpha_r = K_LES(ir, jr, kr) * Pr_or_Sc_turb_inv;
     rhoAlpha_l = K_LES(il, jl, kl) * Pr_or_Sc_turb_inv;
     rhoAlpha += 0.25*(rhoAlpha_l + rhoAlpha_r);
     break;
   case LESType::Deardorff:
     // K_LES = 2*mu_t -> extra factor of 0.5 when computing rhoAlpha
     rhoAlpha_r = K_LES(ir, jr, kr) * Pr_or_Sc_turb_inv;
     rhoAlpha_l = K_LES(il, jl, kl) * Pr_or_Sc_turb_inv;
     rhoAlpha += 0.25*(rhoAlpha_l + rhoAlpha_r) / l_sigma_k;
     break;
   case LESType::None:
     break;
   default:
     amrex::Abort("Error:  LES model is unrecognized");
   }
   // Compute the flux
   amrex::Real diffusionFlux = rhoAlpha * invCellWidth *
       (cell_prim(ir, jr, kr, prim_index) - cell_prim(il, jl, kl, prim_index));
   return diffusionFlux;
 }
Referenced by DiffusionContributionForState().
ComputeGhostCells()
int ComputeGhostCells (const int & spatial_order)
{
   int nGhostCells;
   switch (spatial_order) {
     case 2:
       nGhostCells = 1;
       break;
     case 3:
       nGhostCells = 2;
       break;
     case 4:
       nGhostCells = 2;
       break;
     case 5:
       nGhostCells = 2;
       break;
     case 6:
       nGhostCells = 3;
       break;
     default:
       amrex::Error("Must specify spatial order to be 2,4, or 6");
   }
   return nGhostCells;
 }
ComputeStressTerm()
AMREX_GPU_DEVICE Real ComputeStressTerm (const int & i, const int & j, const int & k, const Array4< const Real > & u, const Array4< const Real > & v, const Array4< const Real > & w, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & Ksmag, const SolverChoice & solverChoice)
Compute tau_ij (m + 1/2), tau_ij (m - 1/2) where m = {i, j, k} for DNS or Smagorinsky
DiffusionContributionForMom()
AMREX_GPU_DEVICE Real DiffusionContributionForMom (const int & i, const int & j, const int & k, const Array4< const Real > & u, const Array4< const Real > & v, const Array4< const Real > & w, const enum MomentumEqn & momentumEqn, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & Ksmag, const SolverChoice & solverChoice, bool dirichlet_at_lo_k, bool dirichlet_at_hi_k)
 {
     auto dxInv = cellSizeInv[0], dyInv = cellSizeInv[1], dzInv = cellSizeInv[2];
     Real diffusionContribution = 0.0;
     switch (momentumEqn) {
         case MomentumEqn::x:
             Real tau11Next, tau11Prev, tau12Next, tau12Prev, tau13Next, tau13Prev;
             tau11Next = ComputeStressTerm(i+1, j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_LES, solverChoice, false, false);
             tau11Prev = ComputeStressTerm(i  , j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_LES, solverChoice, false, false);
             tau12Next = ComputeStressTerm(i, j+1, k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_LES, solverChoice, false, false);
             tau12Prev = ComputeStressTerm(i, j  , k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_LES, solverChoice, false, false);
             tau13Next = ComputeStressTerm(i, j, k+1, u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_LES, solverChoice,
                                           false, dirichlet_at_hi_k);
             tau13Prev = ComputeStressTerm(i, j, k  , u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_LES, solverChoice,
                                           dirichlet_at_lo_k, false);
             diffusionContribution = (tau11Next - tau11Prev) * dxInv  // Contribution to x-mom eqn from diffusive flux in x-dir
                                   + (tau12Next - tau12Prev) * dyInv  // Contribution to x-mom eqn from diffusive flux in y-dir
                                   + (tau13Next - tau13Prev) * dzInv; // Contribution to x-mom eqn from diffusive flux in z-dir
             break;
         case MomentumEqn::y:
             Real tau21Next, tau21Prev, tau22Next, tau22Prev, tau23Next, tau23Prev;
             tau21Next = ComputeStressTerm(i+1, j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_LES, solverChoice, false, false);
             tau21Prev = ComputeStressTerm(i  , j, k, u, v, w, momentumEqn,
                                            DiffusionDir::x, cellSizeInv, K_LES, solverChoice, false, false);
             tau22Next = ComputeStressTerm(i, j+1, k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_LES, solverChoice, false, false);
             tau22Prev = ComputeStressTerm(i, j  , k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_LES, solverChoice, false, false);
             tau23Next = ComputeStressTerm(i, j, k+1, u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_LES, solverChoice,
                                           false, dirichlet_at_hi_k);
             tau23Prev = ComputeStressTerm(i, j, k  , u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_LES, solverChoice,
                                           dirichlet_at_lo_k, false);
             diffusionContribution = (tau21Next - tau21Prev) * dxInv  // Contribution to y-mom eqn from diffusive flux in x-dir
                                   + (tau22Next - tau22Prev) * dyInv  // Contribution to y-mom eqn from diffusive flux in y-dir
                                   + (tau23Next - tau23Prev) * dzInv; // Contribution to y-mom eqn from diffusive flux in z-dir
             break;
         case MomentumEqn::z:
             Real tau31Next, tau31Prev, tau32Next, tau32Prev, tau33Next, tau33Prev;
             tau31Next = ComputeStressTerm(i+1, j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_LES, solverChoice, false, false);
             tau31Prev = ComputeStressTerm(i  , j, k, u, v, w, momentumEqn,
                                           DiffusionDir::x, cellSizeInv, K_LES, solverChoice, false, false);
             tau32Next = ComputeStressTerm(i, j+1, k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_LES, solverChoice, false, false);
             tau32Prev = ComputeStressTerm(i, j  , k, u, v, w, momentumEqn,
                                           DiffusionDir::y, cellSizeInv, K_LES, solverChoice, false, false);
             tau33Next = ComputeStressTerm(i, j, k+1, u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_LES, solverChoice, false, false);
             tau33Prev = ComputeStressTerm(i, j, k  , u, v, w, momentumEqn,
                                           DiffusionDir::z, cellSizeInv, K_LES, solverChoice, false, false);
             diffusionContribution = (tau31Next - tau31Prev) * dxInv  // Contribution to z-mom eqn from diffusive flux in x-dir
                                   + (tau32Next - tau32Prev) * dyInv  // Contribution to z-mom eqn from diffusive flux in y-dir
                                   + (tau33Next - tau33Prev) * dzInv; // Contribution to z-mom eqn from diffusive flux in z-dir
             break;
         default:
             amrex::Abort("Error: Momentum equation is unrecognized");
     }
     return diffusionContribution;
 }
Referenced by erf_rhs().
DiffusionContributionForState()
AMREX_GPU_DEVICE Real DiffusionContributionForState (const int & i, const int & j, const int & k, const Array4< const Real > & cell_data, const Array4< const Real > & cell_prim, const int & qty_index, const Array4< Real > & flux_x, const Array4< Real > & flux_y, const Array4< Real > & flux_z, const GpuArray< Real, AMREX_SPACEDIM > & cellSize, const Array4< Real > & Ksmag, const SolverChoice & solverChoice)
 {
   const amrex::Real dx_inv = cellSizeInv[0];
   const amrex::Real dy_inv = cellSizeInv[1];
   const amrex::Real dz_inv = cellSizeInv[2];
   const int prim_index = qty_index - RhoTheta_comp;
   // TODO : could be more efficient to compute and save all fluxes before taking divergence (now all fluxes are computed 2x);
   xflux(i+1,j,k,qty_index) = ComputeDiffusionFluxForState(i+1, j, k, cell_data, cell_prim, prim_index, dx_inv, K_LES, solverChoice, Coord::x);
   xflux(i  ,j,k,qty_index) = ComputeDiffusionFluxForState(i  , j, k, cell_data, cell_prim, prim_index, dx_inv, K_LES, solverChoice, Coord::x);
   yflux(i,j+1,k,qty_index) = ComputeDiffusionFluxForState(i, j+1, k, cell_data, cell_prim, prim_index, dy_inv, K_LES, solverChoice, Coord::y);
   yflux(i,j  ,k,qty_index) = ComputeDiffusionFluxForState(i, j  , k, cell_data, cell_prim, prim_index, dy_inv, K_LES, solverChoice, Coord::y);
   zflux(i,j,k+1,qty_index) = ComputeDiffusionFluxForState(i, j, k+1, cell_data, cell_prim, prim_index, dz_inv, K_LES, solverChoice, Coord::z);
   zflux(i,j,k  ,qty_index) = ComputeDiffusionFluxForState(i, j, k  , cell_data, cell_prim, prim_index, dz_inv, K_LES, solverChoice, Coord::z);
   Real diffusionContribution =
       (xflux(i+1,j,k,qty_index) - xflux(i  ,j,k,qty_index)) * dx_inv   // Diffusive flux in x-dir
      +(yflux(i,j+1,k,qty_index) - yflux(i,j  ,k,qty_index)) * dy_inv   // Diffusive flux in y-dir
      +(zflux(i,j,k+1,qty_index) - zflux(i,j,k  ,qty_index)) * dz_inv;  // Diffusive flux in z-dir
   return diffusionContribution;
 }
Referenced by erf_rhs().
erf_advance()
void erf_advance (int level, MultiFab & cons_old, MultiFab & cons_new, MultiFab & U_old, MultiFab & V_old, MultiFab & W_old, MultiFab & U_new, MultiFab & V_new, MultiFab & W_new, MultiFab & xmom_crse, MultiFab & ymom_crse, MultiFab & zmom_crse, MultiFab & source, std::array< MultiFab, AMREX_SPACEDIM > & flux, const amrex::Geometry crse_geom, const amrex::Geometry fine_geom, const amrex::IntVect ref_ratio, const amrex::Real dt, const amrex::Real time, amrex::InterpFaceRegister * ifr, const SolverChoice & solverChoice, const amrex::Real * dptr_dens_hse, const amrex::Real * dptr_pres_hse, const amrex::Real * dptr_rayleigh_tau, const amrex::Real * dptr_rayleigh_ubar, const amrex::Real * dptr_rayleigh_vbar, const amrex::Real * dptr_rayleigh_thetabar)
Update the cell-centered state and face-based velocity using a time integrator
Parameters
[in] S_old state on cell centers
[in] U_old x-velocity on x-faces
[in] V_old y-velocity on y-faces
[in] W_old z-velocity on z-faces
[in] source source term on cell centers
[out] S_new state on cell centers
[out] U_new x-velocity on x-faces
[out] V_new y-velocity on y-faces
[out] W_new z-velocity on z-faces
 {
     BL_PROFILE_VAR("erf_advance()",erf_advance);
     int nvars = cons_old.nComp();
     const BoxArray& ba            = cons_old.boxArray();
     const DistributionMapping& dm = cons_old.DistributionMap();
     // **************************************************************************************
     // Temporary array that we use to store primitive advected quantities for the RHS
     // **************************************************************************************
     auto cons_to_prim = [&](const MultiFab& cons_state, MultiFab& prim_state) {
       for (MFIter mfi(cons_state,TilingIfNotGPU()); mfi.isValid(); ++mfi) {
           const Box& gbx = mfi.growntilebox(cons_state.nGrowVect());
           const Array4<const Real>& cons_arr = cons_state.array(mfi);
           const Array4<Real>& prim_arr = prim_state.array(mfi);
           amrex::ParallelFor(gbx, [=] AMREX_GPU_DEVICE (int i, int j, int k) noexcept {
             for (int n = 0; n < NUM_PRIM; ++n) {
               prim_arr(i,j,k,PrimTheta_comp + n) = cons_arr(i,j,k,RhoTheta_comp + n) / cons_arr(i,j,k,Rho_comp);
             }
           });
       }
     };
     MultiFab S_prim(ba, dm, NUM_PRIM, cons_old.nGrowVect());
     // **************************************************************************************
     // These are temporary arrays that we use to store the accumulation of the fluxes
     // **************************************************************************************
     std::array< MultiFab, AMREX_SPACEDIM >  advflux;
     std::array< MultiFab, AMREX_SPACEDIM > diffflux;
      advflux[0].define(convert(ba,IntVect(1,0,0)), dm, nvars, 0);
     diffflux[0].define(convert(ba,IntVect(1,0,0)), dm, nvars, 0);
      advflux[1].define(convert(ba,IntVect(0,1,0)), dm, nvars, 0);
     diffflux[1].define(convert(ba,IntVect(0,1,0)), dm, nvars, 0);
      advflux[2].define(convert(ba,IntVect(0,0,1)), dm, nvars, 0);
     diffflux[2].define(convert(ba,IntVect(0,0,1)), dm, nvars, 0);
      advflux[0].setVal(0.);
      advflux[1].setVal(0.);
      advflux[2].setVal(0.);
     diffflux[0].setVal(0.);
     diffflux[1].setVal(0.);
     diffflux[2].setVal(0.);
     // **************************************************************************************
     // Here we define state_old and state_new which are the Nvectors to be advanced
     // **************************************************************************************
     // Initial solution
     amrex::Vector<amrex::MultiFab> state_old;
     state_old.push_back(MultiFab(ba, dm, nvars, cons_old.nGrow())); // cons
     state_old.push_back(MultiFab(convert(ba,IntVect(1,0,0)), dm, 1, xvel_old.nGrow())); // xmom
     state_old.push_back(MultiFab(convert(ba,IntVect(0,1,0)), dm, 1, yvel_old.nGrow())); // ymom
     state_old.push_back(MultiFab(convert(ba,IntVect(0,0,1)), dm, 1, zvel_old.nGrow())); // zmom
     state_old.push_back(MultiFab(convert(ba,IntVect(1,0,0)), dm, nvars, 1)); // x-fluxes
     state_old.push_back(MultiFab(convert(ba,IntVect(0,1,0)), dm, nvars, 1)); // y-fluxes
     state_old.push_back(MultiFab(convert(ba,IntVect(0,0,1)), dm, nvars, 1)); // z-fluxes
     // Final solution
     amrex::Vector<amrex::MultiFab> state_new;
     state_new.push_back(MultiFab(ba, dm, nvars, cons_old.nGrow())); // cons
     state_new.push_back(MultiFab(convert(ba,IntVect(1,0,0)), dm, 1, xvel_old.nGrow())); // xmom
     state_new.push_back(MultiFab(convert(ba,IntVect(0,1,0)), dm, 1, yvel_old.nGrow())); // ymom
     state_new.push_back(MultiFab(convert(ba,IntVect(0,0,1)), dm, 1, zvel_old.nGrow())); // zmom
     state_new.push_back(MultiFab(convert(ba,IntVect(1,0,0)), dm, nvars, 1)); // x-fluxes
     state_new.push_back(MultiFab(convert(ba,IntVect(0,1,0)), dm, nvars, 1)); // y-fluxes
     state_new.push_back(MultiFab(convert(ba,IntVect(0,0,1)), dm, nvars, 1)); // z-fluxes
     // Temporary data
     amrex::Vector<amrex::MultiFab> state_store;
     state_store.push_back(MultiFab(ba, dm, nvars, cons_old.nGrow())); // cons
     state_store.push_back(MultiFab(convert(ba,IntVect(1,0,0)), dm, 1, xvel_old.nGrow())); // xmom
     state_store.push_back(MultiFab(convert(ba,IntVect(0,1,0)), dm, 1, yvel_old.nGrow())); // ymom
     state_store.push_back(MultiFab(convert(ba,IntVect(0,0,1)), dm, 1, zvel_old.nGrow())); // zmom
     state_store.push_back(MultiFab(convert(ba,IntVect(1,0,0)), dm, nvars, 1)); // x-fluxes
     state_store.push_back(MultiFab(convert(ba,IntVect(0,1,0)), dm, nvars, 1)); // y-fluxes
     state_store.push_back(MultiFab(convert(ba,IntVect(0,0,1)), dm, nvars, 1)); // z-fluxes
     // **************************************************************************************
     // Prepare the old-time data for calling the integrator
     // **************************************************************************************
     // Note that we have filled the ghost cells of cons_old and we are copying the ghost cell values
     //      so we don't need to enforce BCs again here
     MultiFab::Copy(state_old[IntVar::cons], cons_old, 0, 0, cons_old.nComp(), cons_old.nGrow());
     // Convert old velocity available on faces to old momentum on faces to be used in time integration
     // **************************************************************************************
     VelocityToMomentum(xvel_old, yvel_old, zvel_old,
                        state_old[IntVar::cons],
                        state_old[IntVar::xmom],
                        state_old[IntVar::ymom],
                        state_old[IntVar::zmom],
                        solverChoice.spatial_order,
                        xvel_old.nGrow());
     // Apply BC on old momentum data on faces before integration
     // **************************************************************************************
     state_old[IntVar::xmom].FillBoundary(fine_geom.periodicity());
     state_old[IntVar::ymom].FillBoundary(fine_geom.periodicity());
     state_old[IntVar::zmom].FillBoundary(fine_geom.periodicity());
     // **************************************************************************************
     // Initialize the fluxes to zero
     // **************************************************************************************
     state_old[IntVar::xflux].setVal(0.0_rt);
     state_old[IntVar::yflux].setVal(0.0_rt);
     state_old[IntVar::zflux].setVal(0.0_rt);
     auto interpolate_coarse_fine_faces = [&](Vector<MultiFab>& S_data) {
         if (level > 0)
         {
             amrex::Array<const MultiFab*,3> cmf_const{&xmom_crse, &ymom_crse, &zmom_crse};
             amrex::Array<MultiFab*,3> fmf{&S_data[IntVar::xmom],
                                           &S_data[IntVar::ymom],
                                           &S_data[IntVar::zmom]};
             // Interpolate from coarse faces to fine faces *only* on the coarse-fine boundary
             ifr->interp(fmf,cmf_const,0,1);
             amrex::Array<MultiFab*,3> cmf{&xmom_crse, &ymom_crse, &zmom_crse};
             int nGrow = 1;
             BoxArray fine_grids(cons_old.boxArray());
             // Interpolate from coarse faces on fine faces outside the fine region
             create_umac_grown(level, nGrow, fine_grids, crse_geom, fine_geom, cmf, fmf, ref_ratio);
         }
     };
     auto apply_bcs = [&](Vector<MultiFab>& S_data) {
         amrex::Vector<MultiFab*> state_p{&S_data[IntVar::cons],
                                          &S_data[IntVar::xmom],
                                          &S_data[IntVar::ymom],
                                          &S_data[IntVar::zmom]};
         ERF::applyBCs(fine_geom, state_p);
         MomentumToVelocity(xvel_new, yvel_new, zvel_new,
                            S_data[IntVar::cons],
                            S_data[IntVar::xmom],
                            S_data[IntVar::ymom],
                            S_data[IntVar::zmom],
                            solverChoice.spatial_order,
                            xvel_new.nGrow());
         xvel_new.FillBoundary(fine_geom.periodicity());
         yvel_new.FillBoundary(fine_geom.periodicity());
         zvel_new.FillBoundary(fine_geom.periodicity());
         // Apply BC on velocity data on faces
         // Note that the BC was already applied on momentum
         amrex::Vector<MultiFab*> vel_vars{&xvel_new, &yvel_new, &zvel_new};
         ERF::applyBCs(fine_geom, vel_vars, true);
     };
     interpolate_coarse_fine_faces(state_old);
     apply_bcs(state_old);
     cons_to_prim(state_old[IntVar::cons], S_prim);
     // **************************************************************************************
     // Setup the integrator
     // **************************************************************************************
     TimeIntegrator<amrex::Vector<amrex::MultiFab> > integrator(state_old);
 #ifdef AMREX_USE_SUNDIALS
     ////STEP ONE
     // Create SUNDIALS specific objects
     SUNNonlinearSolver NLS = NULL;    /* empty nonlinear solver object */
     SUNLinearSolver LS = NULL;    /* empty linear solver object */
     void *arkode_mem = NULL;      /* empty ARKode memory structure */
     SUNNonlinearSolver NLSf = NULL;    /* empty nonlinear solver object */
     SUNLinearSolver LSf = NULL;    /* empty linear solver object */
     void *inner_mem = NULL;      /* empty ARKode memory structure */
     void *mristep_mem = NULL;      /* empty ARKode memory structure */
     // Create an N_Vector wrapper for the solution MultiFab
     auto get_length = [&](int index) -> sunindextype {
         auto* p_mf = &state_old[index];
         return p_mf->nComp() * (p_mf->boxArray()).numPts();
     };
     ////STEP TWO
     sunindextype length = get_length(IntVar::cons);
     sunindextype length_mx = get_length(IntVar::xmom);
     sunindextype length_my = get_length(IntVar::ymom);
     sunindextype length_mz = get_length(IntVar::zmom);
     sunindextype length_fx = get_length(IntVar::xflux);
     sunindextype length_fy = get_length(IntVar::yflux);
     sunindextype length_fz = get_length(IntVar::zflux);
     // Testing data structures, this length may be different for "real" initial condition
     int NVar             = 7;
     //Arbitrary tolerances
     Real reltol          = 1e-4;
     Real abstol          = 1e-4;
     Real t               = time;
     Real tout            = time+dt;
     Real hfixed          = dt;
     Real m               = 2;
     Real hfixed_mri      = dt / m;
     N_Vector nv_cons     = amrex::sundials::N_VMake_MultiFab(length, &state_old[IntVar::cons]);
     N_Vector nv_xmom     = amrex::sundials::N_VMake_MultiFab(length_mx, &state_old[IntVar::xmom]);
     N_Vector nv_ymom     = amrex::sundials::N_VMake_MultiFab(length_my, &state_old[IntVar::ymom]);
     N_Vector nv_zmom     = amrex::sundials::N_VMake_MultiFab(length_mz, &state_old[IntVar::zmom]);
     N_Vector nv_xflux    = amrex::sundials::N_VMake_MultiFab(length_mx, &state_old[IntVar::xflux]);
     N_Vector nv_yflux    = amrex::sundials::N_VMake_MultiFab(length_my, &state_old[IntVar::yflux]);
     N_Vector nv_zflux    = amrex::sundials::N_VMake_MultiFab(length_mz, &state_old[IntVar::zflux]);
     N_Vector nv_many_arr[NVar];              /* vector array composed of cons, xmom, ymom, zmom component vectors */
     ////STEP THREE
     /* Create manyvector for solution */
     nv_many_arr[IntVar::cons] = nv_cons;
     nv_many_arr[IntVar::xmom] = nv_xmom;
     nv_many_arr[IntVar::ymom] = nv_ymom;
     nv_many_arr[IntVar::zmom] = nv_zmom;
     nv_many_arr[IntVar::xflux] = nv_xflux;
     nv_many_arr[IntVar::yflux] = nv_yflux;
     nv_many_arr[IntVar::zflux] = nv_zflux;
     N_Vector nv_S = N_VNew_ManyVector(NVar, nv_many_arr);
     N_Vector nv_store = N_VClone(nv_S);
 #endif
     //Create function lambdas
     bool l_lo_z_is_dirichlet = ERF::lo_z_is_dirichlet;
     bool l_hi_z_is_dirichlet = ERF::hi_z_is_dirichlet;
     auto rhs_fun = [&](      Vector<MultiFab>& S_rhs,
                        const Vector<MultiFab>& S_data, const Real time) {
         erf_rhs(level, S_rhs, S_data, S_prim,
                 xvel_new, yvel_new, zvel_new,
                 source,
                 advflux, diffflux,
                 fine_geom, dt,
                 ifr,
                 solverChoice,
                 l_lo_z_is_dirichlet,
                 l_hi_z_is_dirichlet,
                 dptr_dens_hse, dptr_pres_hse,
                 dptr_rayleigh_tau, dptr_rayleigh_ubar,
                 dptr_rayleigh_vbar, dptr_rayleigh_thetabar);
     };
     auto rhs_fun_fast = [&](      Vector<MultiFab>& S_rhs,
                             const Vector<MultiFab>& S_stage_data,
                             const Vector<MultiFab>& S_data, const Real time) {
         erf_fast_rhs(level, S_rhs, S_stage_data, S_data,
                      advflux, diffflux,
                      fine_geom, dt,
                      ifr,
                      solverChoice,
                      dptr_dens_hse, dptr_pres_hse,
                      dptr_rayleigh_tau, dptr_rayleigh_ubar,
                      dptr_rayleigh_vbar, dptr_rayleigh_thetabar);
     };
     auto post_update_fun = [&](Vector<MultiFab>& S_data, const Real time) {
         // Apply BC on updated state and momentum data
         for (auto& mfp : S_data) {
             mfp.FillBoundary(fine_geom.periodicity());
         }
         // TODO: we should interpolate coarse data in time first, so that this interplation
         // in space is at the correct time indicated by the `time` function argument.
         interpolate_coarse_fine_faces(S_data);
         apply_bcs(S_data);
         cons_to_prim(S_data[IntVar::cons], S_prim);
     };
     // define rhs and 'post update' utility function that is called after calculating
     // any state data (e.g. at RK stages or at the end of a timestep)
     integrator.set_rhs(rhs_fun);
     integrator.set_post_update(post_update_fun);
 #ifdef AMREX_USE_SUNDIALS
     bool use_erk3 = true;
     bool use_linear = false;
     bool advance_erk=false;
     bool advance_mri=false;
     bool advance_mri_test=false;
     bool advance_rk=!(advance_erk||advance_mri);
     amrex::ParmParse pp("integration.sundials");
     std::string theStrategy;
     if (pp.query("strategy", theStrategy))
     {
         if (theStrategy == "ERK")
         {
             advance_erk=true;
         }
         else if (theStrategy == "MRI")
         {
             advance_mri=true;
         }
         else if (theStrategy == "MRITEST")
         {
             advance_mri=true;
             advance_mri_test=true;
         }
         else if (theStrategy == "NATIVE")
         {
             advance_rk=true;
         }
         else
         {
             std::string msg("Unknown strategy: ");
             msg += theStrategy;
             amrex::Warning(msg.c_str());
         }
     advance_rk=!(advance_erk||advance_mri);
     }
     else
     {
         advance_rk=true;  // default
     }
     ////STEP FOUR
     if(advance_mri_test)
     {
     if(use_erk3)
       inner_mem = ARKStepCreate(f0, NULL, time, nv_S);
     else
       inner_mem = ARKStepCreate(NULL, f0, time, nv_S);
     }
     else
     {
     if(use_erk3)
       inner_mem = ARKStepCreate(f_fast, NULL, time, nv_S);
     else
       inner_mem = ARKStepCreate(NULL, f_fast, time, nv_S);
     }
     ////STEP FIVE
     ARKStepSetFixedStep(inner_mem, hfixed_mri);            // Specify fixed time step size
     FastRhsData fast_userdata;
     fast_userdata.integrator = &integrator;
     fast_userdata.rhs_fun_fast = rhs_fun_fast;
     //For the sundials solve, use state_new as temporary data;
     fast_userdata.S_stage_data = &state_store;
     fast_userdata.nv_stage_data = nv_store;
     fast_userdata.inner_mem = inner_mem;
     /* Call ERKStepCreate to initialize the inner ARK timestepper module and
     specify the right-hand side function in y'=f(t,y), the initial time
     T0, and the initial dependent variable vector y. */
     arkode_mem = ERKStepCreate(f, time, nv_S);
     ERKStepSetUserData(arkode_mem, (void *) &fast_userdata);  /* Pass udata to user functions */
     ERKStepSetPostprocessStageFn(arkode_mem, ProcessStage);
     /* Specify tolerances */
     ERKStepSStolerances(arkode_mem, reltol, abstol);
     ERKStepSetFixedStep(arkode_mem, hfixed);
     ARKStepSetUserData(inner_mem, (void *) &fast_userdata);  /* Pass udata to user functions */
     for(int i=0; i<N_VGetNumSubvectors_ManyVector(nv_S); i++)
     {
     MultiFab::Copy(state_store[i], *amrex::sundials::getMFptr(N_VGetSubvector_ManyVector(nv_S, i)), 0, 0, state_store[i].nComp(), state_store[i].nGrow());
     MultiFab::Copy(*amrex::sundials::getMFptr(N_VGetSubvector_ManyVector(nv_store, i)), *amrex::sundials::getMFptr(N_VGetSubvector_ManyVector(nv_S, i)), 0, 0, state_store[i].nComp(), state_store[i].nGrow());
     }
     ARKodeButcherTable B = ARKodeButcherTable_Alloc(3, SUNFALSE);
     ARKodeButcherTable B2 = ARKodeButcherTable_Alloc(2, SUNFALSE);
     if(use_erk3)
     {
     if(advance_erk)
     {
     // Use SSP-RK3
     B->A[1][0] = 1.0;
     B->A[2][0] = 0.25;
     B->A[2][1] = 0.25;
     B->b[0] = 1./6.;
     B->b[1] = 1./6.;
     B->b[2] = 2./3.;
     B->c[1] = 1.0;
     B->c[2] = 0.5;
     B->q=3;
     }
     if(advance_mri)
         {
     B->A[1][0] = 1.0;
     B->A[2][0] = 1.0;
     B->A[2][2] = 0.0;
     B->b[0] = 0.5;
     B->b[2] = 0.5;
     B->c[1] = 1.0;
     B->c[2] = 1.0;
     B->q=2;
     B->p=0;
     B2->A[1][0] = 1.0;
     B2->b[0] = 0.5;
     B2->b[1] = 0.5;
     B2->c[1] = 1.0;
     B2->q=2;
     B2->p=0;
         }
     if(advance_mri)
       if(advance_mri_test)
     ARKStepSetTables(inner_mem, B->q, B->p, NULL, B);       // Specify Butcher table
       else
     ARKStepSetTables(inner_mem, B2->q, B2->p, NULL, B2);       // Specify Butcher table
     }
     else
     {
     B->A[1][0] = 1.0;
     B->A[2][0] = 1.0;
     B->A[2][2] = 0.0;
     B->b[0] = 0.5;
     B->b[2] = 0.5;
     B->c[1] = 1.0;
     B->c[2] = 1.0;
     B->q=2;
     ARKStepSetTables(inner_mem, B->q, B->p, B, NULL);       // Specify Butcher table
     }
     /*
     LSf = SUNLinSol_SPGMR(nv_S, PREC_Namrex::Real(1.0), 10);
     NLSf = SUNNonlinSol_FixedPoint(nv_S, 50);
     if(use_linear)
       ARKStepSetLinearSolver(inner_mem, LSf, NULL);
     else
       ARKStepSetNonlinearSolver(inner_mem, NLSf);
 */
     //Set table
     //    ERKStepSetTable(arkode_mem, B);
     if(advance_mri)
     {
     ////STEP SIX
     mristep_mem = MRIStepCreate(f, time, nv_S, MRISTEP_ARKSTEP, inner_mem);
     ////STEP SEVEN
     MRIStepSetFixedStep(mristep_mem, hfixed);
     ////STEP 8.1
     /* Specify tolerances */
     MRIStepSStolerances(mristep_mem, reltol, abstol);
     ////STEP 8.2
     /* Initialize spgmr solver */
     LS = SUNLinSol_SPGMR(nv_S, PREC_NONE, 10);
     NLS = SUNNonlinSol_FixedPoint(nv_S, 50);
     ////STEP 8.3
     //    ARKStepSetNonlinearSolver(inner_mem, NLS);
     if(use_linear)
       MRIStepSetLinearSolver(mristep_mem, LS, NULL);
     else
       MRIStepSetNonlinearSolver(mristep_mem, NLS);
     ////STEP NINE
     MRIStepSetUserData(mristep_mem, (void *) &fast_userdata);  /* Pass udata to user functions */
     MRIStepSetPostInnerFn(mristep_mem, PostStoreStage);
     //    ARKStepSetPostprocessStepFn(inner_mem, PostStoreStage);
     //    MRIStepSetPreInnerFn(mristep_mem, StoreStage);
     MRIStepSetPostprocessStageFn(mristep_mem, ProcessStage);
     }
     //Set table
     ERKStepSetTable(arkode_mem, B);
     if(advance_mri)
       if(advance_mri_test)
         MRIStepSetTable(mristep_mem, B->q, B);
       else
         MRIStepSetTable(mristep_mem, B2->q, B2);
     // Free the Butcher table
     ARKodeButcherTable_Free(B);
     if(!advance_rk)
     {
     if(advance_erk)
     {
     // Use ERKStep to evolve state_old data (wrapped in nv_S) from t to tout=t+dt
     ERKStepEvolve(arkode_mem, tout, nv_S, &t, ARK_NORMAL);
     }
     ////STEP ELEVEN
     if(advance_mri)
     {
     // Use MRIStep to evolve state_old data (wrapped in nv_S) from t to tout=t+dt
     MRIStepEvolve(mristep_mem, tout, nv_S, &t, ARK_NORMAL);
     }
     // Copy the result stored in nv_S to state_new
     for(int i=0; i<N_VGetNumSubvectors_ManyVector(nv_S); i++)
     {
     MultiFab::Copy(state_new[i], *amrex::sundials::getMFptr(N_VGetSubvector_ManyVector(nv_S, i)), 0, 0, state_new[i].nComp(), state_new[i].nGrow());
     }
     }
     else
 #endif
     {
     // **************************************************************************************
     // Integrate for a single timestep
     // **************************************************************************************
     integrator.advance(state_old, state_new, time, dt);
     }
 #ifdef AMREX_USE_SUNDIALS
   ////STEP THIRTEEN
   N_VDestroy(nv_cons);
   N_VDestroy(nv_xmom);
   N_VDestroy(nv_ymom);
   N_VDestroy(nv_zmom);
   N_VDestroy(nv_xflux);
   N_VDestroy(nv_yflux);
   N_VDestroy(nv_zflux);
   N_VDestroy(nv_S);
   ////STEP FOURTEEN
   if(advance_mri)
   MRIStepFree(&mristep_mem);
   ARKStepFree(&inner_mem);
   ERKStepFree(&arkode_mem);
   if(advance_mri)
   {
   SUNLinSolFree(LS);    // Free nonlinear solvers
   SUNNonlinSolFree(NLS);    // Free nonlinear solvers
   }
 #endif
     // **************************************************************************************
     // Convert updated momentum to updated velocity on faces after we have taken a timestep
     // **************************************************************************************
     MomentumToVelocity(xvel_new, yvel_new, zvel_new,
                        state_new[IntVar::cons],
                        state_new[IntVar::xmom],
                        state_new[IntVar::ymom],
                        state_new[IntVar::zmom],
                        solverChoice.spatial_order, 0);
     // **************************************************************************************
     // Get the final cell centered variables after the step
     // (do this at the very end because its a swap not a copy)
     // **************************************************************************************
     std::swap(cons_new, state_new[IntVar::cons]);
     std::swap(flux[0], state_new[IntVar::xflux]);
     std::swap(flux[1], state_new[IntVar::yflux]);
     std::swap(flux[2], state_new[IntVar::zflux]);
     // One final application of internal and periodic ghost cell filling
     xvel_new.FillBoundary(fine_geom.periodicity());
     yvel_new.FillBoundary(fine_geom.periodicity());
     zvel_new.FillBoundary(fine_geom.periodicity());
     // One final application of non-periodic BCs
     amrex::Vector<MultiFab*> cons_vars{&cons_new};
     ERF::applyBCs(fine_geom, cons_vars);
     amrex::Vector<MultiFab*> vel_vars{&xvel_new, &yvel_new, &zvel_new};
     ERF::applyBCs(fine_geom, vel_vars, true);
 }
erf_fast_rhs()
void erf_fast_rhs (int level, Vector< MultiFab > & S_rhs, const Vector< MultiFab > & S_stage_data, const Vector< MultiFab > & S_data, std::array< MultiFab, AMREX_SPACEDIM > & advflux, std::array< MultiFab, AMREX_SPACEDIM > & diffflux, const amrex::Geometry geom, const amrex::Real dt, amrex::InterpFaceRegister * ifr, const SolverChoice & solverChoice, const amrex::Real * dptr_dens_hse, const amrex::Real * dptr_pres_hse, const amrex::Real * dptr_rayleigh_tau, const amrex::Real * dptr_rayleigh_ubar, const amrex::Real * dptr_rayleigh_vbar, const amrex::Real * dptr_rayleigh_thetabar)
 {
     BL_PROFILE_VAR("erf_rhs()",erf_rhs);
     int klo = geom.Domain().smallEnd()[2];
     int khi = geom.Domain().bigEnd()[2];
     const GpuArray<Real, AMREX_SPACEDIM> dxInv = geom.InvCellSizeArray();
     const auto& ba = S_data[IntVar::cons].boxArray();
     const auto& dm = S_data[IntVar::cons].DistributionMap();
     amrex::MultiFab Delta_rho_u(    convert(ba,IntVect(1,0,0)), dm, 1, 1);
     amrex::MultiFab Delta_rho_v(    convert(ba,IntVect(0,1,0)), dm, 1, 1);
     amrex::MultiFab Delta_rho_w(    convert(ba,IntVect(0,0,1)), dm, 1, 1);
     amrex::MultiFab Delta_rho  (            ba                , dm, 1, 1);
     amrex::MultiFab Delta_rho_theta(        ba                , dm, 1, 1);
     // Create delta_rho_u/v/w/theta  = U'', V'', W'', Theta'' in the docs
     MultiFab::Copy(Delta_rho_u    , S_data[IntVar::xmom], 0, 0, 1, 1);
     MultiFab::Copy(Delta_rho_v    , S_data[IntVar::ymom], 0, 0, 1, 1);
     MultiFab::Copy(Delta_rho_w    , S_data[IntVar::zmom], 0, 0, 1, 1);
     MultiFab::Copy(Delta_rho      , S_data[IntVar::cons], Rho_comp     , 0, 1,1);
     MultiFab::Copy(Delta_rho_theta, S_data[IntVar::cons], RhoTheta_comp, 0, 1,1);
     MultiFab::Subtract(Delta_rho_u    , S_stage_data[IntVar::xmom], 0, 0, 1, 1);
     MultiFab::Subtract(Delta_rho_v    , S_stage_data[IntVar::ymom], 0, 0, 1, 1);
     MultiFab::Subtract(Delta_rho_w    , S_stage_data[IntVar::zmom], 0, 0, 1, 1);
     MultiFab::Subtract(Delta_rho      , S_stage_data[IntVar::cons], Rho_comp     , 0, 1, 1);
     MultiFab::Subtract(Delta_rho_theta, S_stage_data[IntVar::cons], RhoTheta_comp, 0, 1, 1);
     // Not sure if we need these
     Delta_rho_u.FillBoundary(geom.periodicity());
     Delta_rho_v.FillBoundary(geom.periodicity());
     Delta_rho_w.FillBoundary(geom.periodicity());
     Delta_rho_theta.FillBoundary(geom.periodicity());
     // *************************************************************************
     // Set gravity as a vector
     const    Array<Real,AMREX_SPACEDIM> grav{0.0, 0.0, -solverChoice.gravity};
     const GpuArray<Real,AMREX_SPACEDIM> grav_gpu{grav[0], grav[1], grav[2]};
     const iMultiFab *mlo_mf_x, *mhi_mf_x;
     const iMultiFab *mlo_mf_y, *mhi_mf_y;
     const iMultiFab *mlo_mf_z, *mhi_mf_z;
     if (level > 0)
     {
         mlo_mf_x = &(ifr->mask(Orientation(0,Orientation::low)));
         mhi_mf_x = &(ifr->mask(Orientation(0,Orientation::high)));
         mlo_mf_y = &(ifr->mask(Orientation(1,Orientation::low)));
         mhi_mf_y = &(ifr->mask(Orientation(1,Orientation::high)));
         mlo_mf_z = &(ifr->mask(Orientation(2,Orientation::low)));
         mhi_mf_z = &(ifr->mask(Orientation(2,Orientation::high)));
     }
     // *************************************************************************
     // Define updates in the current RK stage, fluxes are computed here itself
     //TODO: Benchmarking of performance. We are computing the fluxes on the fly.
     //If the performance slows, consider saving all the fluxes apriori and accessing them here.
     // *************************************************************************
     for ( MFIter mfi(S_data[IntVar::cons],TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const Box& bx = mfi.tilebox();
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         Box const& valid_bx = mfi.validbox();
         int vlo_x = valid_bx.smallEnd(0);
         int vhi_x = valid_bx.bigEnd(0);
         int vlo_y = valid_bx.smallEnd(1);
         int vhi_y = valid_bx.bigEnd(1);
         int vlo_z = valid_bx.smallEnd(2);
         int vhi_z = valid_bx.bigEnd(2);
         auto mlo_x = (level > 0) ? mlo_mf_x->const_array(mfi) : Array4<const int>{};
         auto mhi_x = (level > 0) ? mhi_mf_x->const_array(mfi) : Array4<const int>{};
         auto mlo_y = (level > 0) ? mlo_mf_y->const_array(mfi) : Array4<const int>{};
         auto mhi_y = (level > 0) ? mhi_mf_y->const_array(mfi) : Array4<const int>{};
         auto mlo_z = (level > 0) ? mlo_mf_z->const_array(mfi) : Array4<const int>{};
         auto mhi_z = (level > 0) ? mhi_mf_z->const_array(mfi) : Array4<const int>{};
         const Array4<const Real> & cell_data        = S_data[IntVar::cons].array(mfi);
         const Array4<Real> & cell_rhs         = S_rhs[IntVar::cons].array(mfi);
         const Array4<const Real> & cell_stage_data  = S_stage_data[IntVar::cons].array(mfi);
         const Array4<Real>& delta_rho_u     = Delta_rho_u.array(mfi);
         const Array4<Real>& delta_rho_v     = Delta_rho_v.array(mfi);
         const Array4<Real>& delta_rho_w     = Delta_rho_w.array(mfi);
         const Array4<Real>& delta_rho       = Delta_rho.array(mfi);
         const Array4<Real>& delta_rho_theta = Delta_rho_theta.array(mfi);
         const Array4<Real>& rho_u_rhs = S_rhs[IntVar::xmom].array(mfi);
         const Array4<Real>& rho_v_rhs = S_rhs[IntVar::ymom].array(mfi);
         const Array4<Real>& rho_w_rhs = S_rhs[IntVar::zmom].array(mfi);
         const Array4<Real>& xflux_rhs = S_rhs[IntVar::xflux].array(mfi);
         const Array4<Real>& yflux_rhs = S_rhs[IntVar::yflux].array(mfi);
         const Array4<Real>& zflux_rhs = S_rhs[IntVar::zflux].array(mfi);
         // These are temporaries we use to add to the S_rhs for the fluxes
         const Array4<Real>& advflux_x = advflux[0].array(mfi);
         const Array4<Real>& advflux_y = advflux[1].array(mfi);
         const Array4<Real>& advflux_z = advflux[2].array(mfi);
         // **************************************************************************
         // Define updates in the RHS of continuity, temperature, and scalar equations
         // **************************************************************************
         amrex::ParallelFor(bx, S_data[IntVar::cons].nComp(),
             [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept {
             if (n == Rho_comp)
             {
                 // We use the most current momenta here to update rho
                 cell_rhs(i, j, k, n) += -AdvectionContributionForState(i, j, k, delta_rho_u, delta_rho_v, delta_rho_w,
                                          cell_data, Rho_comp,
                                          advflux_x, advflux_y, advflux_z, dxInv, solverChoice.spatial_order);
             } else if (n == RhoTheta_comp) {
                 // We use the most current momenta but the "lagged" theta here to update (rho theta)
                 cell_rhs(i, j, k, n) += -AdvectionContributionForState(i, j, k, delta_rho_u, delta_rho_v, delta_rho_w,
                                          cell_stage_data, RhoTheta_comp,
                                          advflux_x, advflux_y, advflux_z, dxInv, solverChoice.spatial_order);
             } else {
                 cell_rhs(i, j, k, n) = 0.0;
             }
         }
         );
         // Compute the RHS for the flux terms from this stage --
         //     we do it this way so we don't double count
         amrex::ParallelFor(tbx, S_data[IntVar::cons].nComp(),
         [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             if (n == Rho_comp && n == RhoTheta_comp)
                 xflux_rhs(i,j,k,n) = advflux_x(i,j,k,n);
             else
                 xflux_rhs(i,j,k,n) = 0.0;
         });
         amrex::ParallelFor(tby, S_data[IntVar::cons].nComp(),
         [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             if (n == Rho_comp && n == RhoTheta_comp)
                 yflux_rhs(i,j,k,n) = advflux_y(i,j,k,n);
             else
                 yflux_rhs(i,j,k,n) = 0.0;
         });
         amrex::ParallelFor(tbz, S_data[IntVar::cons].nComp(),
         [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
             if (n == Rho_comp && n == RhoTheta_comp)
                 zflux_rhs(i,j,k,n) = advflux_z(i,j,k,n);
             else
                 zflux_rhs(i,j,k,n) = 0.0;
         });
         // *********************************************************************
         // Define updates in the RHS of {x, y, z}-momentum equations
         // *********************************************************************
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // x-momentum equation
             rho_u_rhs(i, j, k) = 0.0; // Initialize the updated x-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (i == vlo_x && mlo_x(i,j,k)) || (i == vhi_x+1 && mhi_x(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
                 // Add (negative) gradient of (rho theta) multiplied by lagged "pi"
                 Real exner_pi_l = std::pow(getPgivenRTh(cell_stage_data(i-1,j,k,RhoTheta_comp))/p_0,R_d/c_p);
                 Real exner_pi_r = std::pow(getPgivenRTh(cell_stage_data(i  ,j,k,RhoTheta_comp))/p_0,R_d/c_p);
                 Real exner_pi_c =  0.5 * (exner_pi_l + exner_pi_r);
                 rho_u_rhs(i, j, k) += (-dxInv[0]) * Gamma * R_d * exner_pi_c *
                   (delta_rho_theta(i  ,j,k,0) - delta_rho_theta(i-1,j,k,0));
             } // not on coarse-fine boundary
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // y-momentum equation
             rho_v_rhs(i, j, k) = 0.0; // Initialize the updated y-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (j == vlo_y && mlo_y(i,j,k)) || (j == vhi_y+1 && mhi_y(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
                 // Add (negative) gradient of (rho theta) multiplied by lagged "pi"
                 Real exner_pi_l = std::pow(getPgivenRTh(cell_stage_data(i,j-1,k,RhoTheta_comp))/p_0,R_d/c_p);
                 Real exner_pi_r = std::pow(getPgivenRTh(cell_stage_data(i,j  ,k,RhoTheta_comp))/p_0,R_d/c_p);
                 Real exner_pi_c =  0.5 * (exner_pi_l + exner_pi_r);
                 rho_v_rhs(i, j, k) += (-dxInv[1]) * Gamma * R_d * exner_pi_c *
                   (delta_rho_theta(i,j  ,k,0) - delta_rho_theta(i,j-1,k,0));
             } // not on coarse-fine boundary
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // z-momentum equation
             rho_w_rhs(i, j, k) = 0.0; // Initialize the updated z-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (k == vlo_z && mlo_z(i,j,k)) || (k == vhi_z+1 && mhi_z(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
                 Real exner_pi_l = std::pow(getPgivenRTh(cell_stage_data(i,j,k-1,RhoTheta_comp))/p_0,R_d/c_p);
                 Real exner_pi_r = std::pow(getPgivenRTh(cell_stage_data(i,j,k  ,RhoTheta_comp))/p_0,R_d/c_p);
                 Real exner_pi_c =  0.5 * (exner_pi_l + exner_pi_r);
                 // Add (negative) gradient of (rho theta) multiplied by lagged "pi"
                 rho_w_rhs(i, j, k) += -1.0 * Gamma * R_d * exner_pi_c *
                   (delta_rho_theta(i,j,k,0) - delta_rho_theta(i,j,k-1,0))*dxInv[2];
                 // Add gravity term
                 Real rhobar = 0.5 * (dptr_dens_hse[k] + dptr_dens_hse[k-1]);
                 Real  pibar = std::pow(0.5 * (dptr_pres_hse[k] + dptr_pres_hse[k-1]),R_d/c_p);
                 Real wadv = 0.0; // We will not use this since we are using 2nd order interpolation
                 rho_w_rhs(i, j, k) += grav_gpu[2] * (
                     InterpolateFromCellOrFace(i, j, k, delta_rho, 0, wadv, Coord::z, 2)
                     - (R_d / (c_p - R_d)) * exner_pi_c * rhobar / pibar *
                     InterpolateFromCellOrFace(i, j, k, delta_rho_theta,             0, wadv, Coord::z, 2) /
                     InterpolateFromCellOrFace(i, j, k, cell_stage_data, RhoTheta_comp, wadv, Coord::z, 2) );
             } // not on coarse-fine boundary
         });
     }
 }
Referenced by erf_advance().
erf_rhs()
void erf_rhs (int level, Vector< MultiFab > & S_rhs, const Vector< MultiFab > & S_data, const MultiFab & S_prim, const MultiFab & xvel, const MultiFab & yvel, const MultiFab & zvel, MultiFab & source, std::array< MultiFab, AMREX_SPACEDIM > & advflux, std::array< MultiFab, AMREX_SPACEDIM > & diffflux, const amrex::Geometry geom, const amrex::Real dt, amrex::InterpFaceRegister * ifr, const SolverChoice & solverChoice, const bool lo_z_is_dirichlet, const bool hi_z_is_dirichlet, const amrex::Real * dptr_dens_hse, const amrex::Real * dptr_pres_hse, const amrex::Real * dptr_rayleigh_tau, const amrex::Real * dptr_rayleigh_ubar, const amrex::Real * dptr_rayleigh_vbar, const amrex::Real * dptr_rayleigh_thetabar)
 {
     BL_PROFILE_VAR("erf_rhs()",erf_rhs);
     const int l_spatial_order = solverChoice.spatial_order;
     int klo = geom.Domain().smallEnd()[2];
     int khi = geom.Domain().bigEnd()[2];
     const GpuArray<Real, AMREX_SPACEDIM> dx    = geom.CellSizeArray();
     const GpuArray<Real, AMREX_SPACEDIM> dxInv = geom.InvCellSizeArray();
     const auto& ba = S_data[IntVar::cons].boxArray();
     const auto& dm = S_data[IntVar::cons].DistributionMap();
     // *************************************************************************
     // Set gravity as a vector
     const    Array<Real,AMREX_SPACEDIM> grav{0.0, 0.0, -solverChoice.gravity};
     const GpuArray<Real,AMREX_SPACEDIM> grav_gpu{grav[0], grav[1], grav[2]};
     // *************************************************************************
     // Calculate cell-centered eddy viscosity
     //
     // Notes:
     // 1. Need to apply BC on velocity field so that ComputeStrainRate works
     //    properly
     // 2. Need to call FillBoundary and applyBCs to set ghost values on all
     //    boundaries so that InterpolateTurbulentViscosity works properly
     // *************************************************************************
     MultiFab eddyViscosity(S_data[IntVar::cons].boxArray(),S_data[IntVar::cons].DistributionMap(),1,1);
     if (solverChoice.les_type == LESType::Smagorinsky ||
         solverChoice.les_type == LESType::Deardorff)
     {
         if (solverChoice.les_type == LESType::Smagorinsky)
             ComputeTurbulentViscosity(xvel, yvel, zvel, S_data[IntVar::cons],
                                       eddyViscosity, dxInv, solverChoice,
                                       lo_z_is_dirichlet, klo, hi_z_is_dirichlet, khi);
         else if (solverChoice.les_type == LESType::Deardorff)
             ComputeTurbulentViscosity(xvel, yvel, zvel, S_data[IntVar::cons],
                                       eddyViscosity, dxInv, solverChoice,
                                       lo_z_is_dirichlet, klo, hi_z_is_dirichlet, khi);
         eddyViscosity.FillBoundary(geom.periodicity());
         amrex::Vector<MultiFab*> eddyvisc_update{&eddyViscosity};
         ERF::applyBCs(geom, eddyvisc_update, true);
     }
     const iMultiFab *mlo_mf_x, *mhi_mf_x;
     const iMultiFab *mlo_mf_y, *mhi_mf_y;
     const iMultiFab *mlo_mf_z, *mhi_mf_z;
     bool l_use_deardorff = (solverChoice.les_type == LESType::Deardorff);
     Real l_Delta         = std::pow(dx[0] * dx[1] * dx[2],1./3.);
     Real l_C_e           = solverChoice.Ce;
     if (level > 0)
     {
         mlo_mf_x = &(ifr->mask(Orientation(0,Orientation::low)));
         mhi_mf_x = &(ifr->mask(Orientation(0,Orientation::high)));
         mlo_mf_y = &(ifr->mask(Orientation(1,Orientation::low)));
         mhi_mf_y = &(ifr->mask(Orientation(1,Orientation::high)));
         mlo_mf_z = &(ifr->mask(Orientation(2,Orientation::low)));
         mhi_mf_z = &(ifr->mask(Orientation(2,Orientation::high)));
     }
     // *************************************************************************
     // Define updates and fluxes in the current RK stage
     // *************************************************************************
     for ( MFIter mfi(S_data[IntVar::cons],TilingIfNotGPU()); mfi.isValid(); ++mfi) {
         const Box& bx = mfi.tilebox();
         const Box& tbx = mfi.nodaltilebox(0);
         const Box& tby = mfi.nodaltilebox(1);
         const Box& tbz = mfi.nodaltilebox(2);
         Box const& valid_bx = mfi.validbox();
         int vlo_x = valid_bx.smallEnd(0);
         int vhi_x = valid_bx.bigEnd(0);
         int vlo_y = valid_bx.smallEnd(1);
         int vhi_y = valid_bx.bigEnd(1);
         int vlo_z = valid_bx.smallEnd(2);
         int vhi_z = valid_bx.bigEnd(2);
         auto mlo_x = (level > 0) ? mlo_mf_x->const_array(mfi) : Array4<const int>{};
         auto mhi_x = (level > 0) ? mhi_mf_x->const_array(mfi) : Array4<const int>{};
         auto mlo_y = (level > 0) ? mlo_mf_y->const_array(mfi) : Array4<const int>{};
         auto mhi_y = (level > 0) ? mhi_mf_y->const_array(mfi) : Array4<const int>{};
         auto mlo_z = (level > 0) ? mlo_mf_z->const_array(mfi) : Array4<const int>{};
         auto mhi_z = (level > 0) ? mhi_mf_z->const_array(mfi) : Array4<const int>{};
         const Array4<const Real> & cell_data  = S_data[IntVar::cons].array(mfi);
         const Array4<const Real> & cell_prim  = S_prim.array(mfi);
         const Array4<Real> & cell_rhs   = S_rhs[IntVar::cons].array(mfi);
         const Array4<Real> & source_fab = source.array(mfi);
         const Array4<const Real> & u = xvel.array(mfi);
         const Array4<const Real> & v = yvel.array(mfi);
         const Array4<const Real> & w = zvel.array(mfi);
         const Array4<const Real>& rho_u = S_data[IntVar::xmom].array(mfi);
         const Array4<const Real>& rho_v = S_data[IntVar::ymom].array(mfi);
         const Array4<const Real>& rho_w = S_data[IntVar::zmom].array(mfi);
         const Array4<Real>& rho_u_rhs = S_rhs[IntVar::xmom].array(mfi);
         const Array4<Real>& rho_v_rhs = S_rhs[IntVar::ymom].array(mfi);
         const Array4<Real>& rho_w_rhs = S_rhs[IntVar::zmom].array(mfi);
         const Array4<Real>& xflux_rhs = S_rhs[IntVar::xflux].array(mfi);
         const Array4<Real>& yflux_rhs = S_rhs[IntVar::yflux].array(mfi);
         const Array4<Real>& zflux_rhs = S_rhs[IntVar::zflux].array(mfi);
         // These are temporaries we use to add to the S_rhs for the fluxes
         const Array4<Real>& advflux_x = advflux[0].array(mfi);
         const Array4<Real>& advflux_y = advflux[1].array(mfi);
         const Array4<Real>& advflux_z = advflux[2].array(mfi);
         // These are temporaries we use to add to the S_rhs for the fluxes
         const Array4<Real>& diffflux_x = diffflux[0].array(mfi);
         const Array4<Real>& diffflux_y = diffflux[1].array(mfi);
         const Array4<Real>& diffflux_z = diffflux[2].array(mfi);
         const Array4<Real>& K_LES = eddyViscosity.array(mfi);
         // **************************************************************************
         // Define updates in the RHS of continuity, temperature, and scalar equations
         // **************************************************************************
         amrex::ParallelFor(bx, S_data[IntVar::cons].nComp(),
        [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept {
             cell_rhs(i, j, k, n) = 0.0; // Initialize the updated state eqn term to zero.
             // Add advection terms.
             if ((n != RhoKE_comp) || l_use_deardorff)
                 cell_rhs(i, j, k, n) += -AdvectionContributionForState(i, j, k, rho_u, rho_v, rho_w, cell_prim, n,
                                          advflux_x, advflux_y, advflux_z, dxInv, l_spatial_order);
             // Add diffusive terms.
             if (n == RhoTheta_comp)
                 cell_rhs(i, j, k, n) += DiffusionContributionForState(i, j, k, cell_data, cell_prim, RhoTheta_comp,
                                         diffflux_x, diffflux_y, diffflux_z, dxInv, K_LES, solverChoice);
             if (n == RhoScalar_comp)
                 cell_rhs(i, j, k, n) += DiffusionContributionForState(i, j, k, cell_data, cell_prim, RhoScalar_comp,
                                         diffflux_x, diffflux_y, diffflux_z, dxInv, K_LES, solverChoice);
             if (l_use_deardorff && n == RhoKE_comp)
                 cell_rhs(i, j, k, n) += DiffusionContributionForState(i, j, k, cell_data, cell_prim, RhoKE_comp,
                                         diffflux_x, diffflux_y, diffflux_z, dxInv, K_LES, solverChoice);
             // Add Rayleigh damping
             if (solverChoice.use_rayleigh_damping && n == RhoTheta_comp)
             {
                 Real theta = cell_prim(i,j,k,PrimTheta_comp);
                 cell_rhs(i, j, k, n) -= dptr_rayleigh_tau[k] * (theta - dptr_rayleigh_thetabar[k]) * cell_data(i,j,k,Rho_comp);
             }
             if (l_use_deardorff && n == RhoKE_comp)
             {
                 bool dirichlet_at_lo_k = ( (k == klo) && lo_z_is_dirichlet );
                 bool dirichlet_at_hi_k = ( (k == khi) && hi_z_is_dirichlet );
                 cell_rhs(i, j, k, n) += ComputeTKEProduction(i,j,k,u,v,w,dxInv,K_LES,solverChoice,
                                                              dirichlet_at_lo_k, dirichlet_at_hi_k)
                                      +  cell_data(i,j,k,Rho_comp) * l_C_e *
                     std::pow(cell_prim(i,j,k,PrimKE_comp),1.5) / l_Delta;
             }
             // Add source terms. TODO: Put this under a if condition when we implement source term
             cell_rhs(i, j, k, n) += source_fab(i, j, k, n);
         }
         );
         // Compute the RHS for the flux terms from this stage -- we do it this way so we don't double count
         //         fluxes at fine-fine interfaces
         amrex::ParallelFor(tbx, S_data[IntVar::cons].nComp(),
         [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
              xflux_rhs(i,j,k,n) = advflux_x(i,j,k,n) + diffflux_x(i,j,k,n);
         });
         amrex::ParallelFor(tby, S_data[IntVar::cons].nComp(),
         [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
              yflux_rhs(i,j,k,n) = advflux_y(i,j,k,n) + diffflux_y(i,j,k,n);
         });
         amrex::ParallelFor(tbz, S_data[IntVar::cons].nComp(),
         [=] AMREX_GPU_DEVICE (int i, int j, int k, int n) noexcept
         {
              zflux_rhs(i,j,k,n) = advflux_z(i,j,k,n) + diffflux_z(i,j,k,n);
         });
         // *********************************************************************
         // Define updates in the RHS of {x, y, z}-momentum equations
         // *********************************************************************
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // x-momentum equation
             rho_u_rhs(i, j, k) = 0.0; // Initialize the updated x-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (i == vlo_x && mlo_x(i,j,k)) || (i == vhi_x+1 && mhi_x(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
             // Add advective terms
             rho_u_rhs(i, j, k) += -AdvectionContributionForXMom(i, j, k, rho_u, rho_v, rho_w, u,
                                                                 dxInv, l_spatial_order);
             // Add diffusive terms
             bool dirichlet_at_lo_k = ( (k == klo) && lo_z_is_dirichlet);
             bool dirichlet_at_hi_k = ( (k == khi) && hi_z_is_dirichlet);
             if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity)
             {
                 // DiffusionContributionForMom calls ComputeStressTerm, which returns mu_effective * strainRateDeviatoric
                 // For "ConstantK" (in DNS mode), mu_effective is twice the kinematic viscosity
                 // The factor of rho is provided by passing in rho*u instead of u
                 rho_u_rhs(i, j, k) += DiffusionContributionForMom(i, j, k, rho_u, rho_v, rho_w, MomentumEqn::x, dxInv, K_LES, solverChoice,
                                                                   dirichlet_at_lo_k,dirichlet_at_hi_k);
             }
             else
             {
                 rho_u_rhs(i, j, k) += DiffusionContributionForMom(i, j, k, u, v, w, MomentumEqn::x, dxInv, K_LES, solverChoice,
                                                                   dirichlet_at_lo_k,dirichlet_at_hi_k);
             }
             // Add pressure gradient
             rho_u_rhs(i, j, k) += (-dxInv[0]) *
                 (getPprimegivenRTh(cell_data(i    , j, k, RhoTheta_comp),dptr_pres_hse[k]) -
                  getPprimegivenRTh(cell_data(i - 1, j, k, RhoTheta_comp),dptr_pres_hse[k]));
             // Add driving pressure gradient
             if (solverChoice.abl_driver_type == ABLDriverType::PressureGradient)
                 rho_u_rhs(i, j, k) += -solverChoice.abl_pressure_grad[0];
             // Add Coriolis forcing (that assumes east is +x, north is +y)
             if (solverChoice.use_coriolis)
             {
                 Real rho_v_loc = 0.25 * (rho_v(i,j+1,k) + rho_v(i,j,k) + rho_v(i-1,j+1,k) + rho_v(i-1,j,k));
                 Real rho_w_loc = 0.25 * (rho_w(i,j,k+1) + rho_w(i,j,k) + rho_w(i,j-1,k+1) + rho_w(i,j-1,k));
                 rho_u_rhs(i, j, k) += solverChoice.coriolis_factor *
                         (rho_v_loc * solverChoice.sinphi - rho_w_loc * solverChoice.cosphi);
             }
             // Add geostrophic forcing
             if (solverChoice.abl_driver_type == ABLDriverType::GeostrophicWind)
                 rho_u_rhs(i, j, k) += solverChoice.abl_geo_forcing[0];
             // Add Rayleigh damping
             if (solverChoice.use_rayleigh_damping)
             {
                 Real uu = rho_u(i,j,k) / cell_data(i,j,k,Rho_comp);
                 rho_u_rhs(i, j, k) -= dptr_rayleigh_tau[k] * (uu - dptr_rayleigh_ubar[k]) * cell_data(i,j,k,Rho_comp);
             }
             } // not on coarse-fine boundary
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // y-momentum equation
             rho_v_rhs(i, j, k) = 0.0; // Initialize the updated y-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (j == vlo_y && mlo_y(i,j,k)) || (j == vhi_y+1 && mhi_y(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
             // Add advective terms
             rho_v_rhs(i, j, k) += -AdvectionContributionForYMom(i, j, k, rho_u, rho_v, rho_w, v,
                                                                 dxInv, l_spatial_order);
             // Add diffusive terms
             bool dirichlet_at_lo_k = ( (k == klo) && lo_z_is_dirichlet);
             bool dirichlet_at_hi_k = ( (k == khi) && hi_z_is_dirichlet);
             if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity)
             {
                 // DiffusionContributionForMom calls ComputeStressTerm, which returns mu_effective * strainRateDeviatoric
                 // For "ConstantK" (in DNS mode), mu_effective is twice the kinematic viscosity
                 // The factor of rho is provided by passing in rho*u instead of u
                 rho_v_rhs(i, j, k) += DiffusionContributionForMom(i, j, k, rho_u, rho_v, rho_w, MomentumEqn::y, dxInv, K_LES, solverChoice,
                                                                   dirichlet_at_lo_k,dirichlet_at_hi_k);
             }
             else
             {
                 rho_v_rhs(i, j, k) += DiffusionContributionForMom(i, j, k, u, v, w, MomentumEqn::y, dxInv, K_LES, solverChoice,
                                                                   dirichlet_at_lo_k,dirichlet_at_hi_k);
             }
             // Add pressure gradient
             rho_v_rhs(i, j, k) += (-dxInv[1]) *
                 (getPprimegivenRTh(cell_data(i, j    , k, RhoTheta_comp),dptr_pres_hse[k]) -
                  getPprimegivenRTh(cell_data(i, j - 1, k, RhoTheta_comp),dptr_pres_hse[k]));
             // Add driving pressure gradient
             if (solverChoice.abl_driver_type == ABLDriverType::PressureGradient)
                 rho_v_rhs(i, j, k) += -solverChoice.abl_pressure_grad[1];
             // Add Coriolis forcing (that assumes east is +x, north is +y)
             if (solverChoice.use_coriolis)
             {
                 Real rho_u_loc = 0.25 * (rho_u(i+1,j,k) + rho_u(i,j,k) + rho_u(i+1,j-1,k) + rho_u(i,j-1,k));
                 rho_v_rhs(i, j, k) += -solverChoice.coriolis_factor * rho_u_loc * solverChoice.sinphi;
             }
             // Add geostrophic forcing
             if (solverChoice.abl_driver_type == ABLDriverType::GeostrophicWind)
                 rho_v_rhs(i, j, k) += solverChoice.abl_geo_forcing[1];
             // Add Rayleigh damping
             if (solverChoice.use_rayleigh_damping)
             {
                 Real vv = rho_v(i,j,k) / cell_data(i,j,k,Rho_comp);
                 rho_v_rhs(i, j, k) -= dptr_rayleigh_tau[k] * (vv - dptr_rayleigh_vbar[k]) * cell_data(i,j,k,Rho_comp);
             }
             } // not on coarse-fine boundary
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) { // z-momentum equation
             rho_w_rhs(i, j, k) = 0.0; // Initialize the updated z-mom eqn term to zero
             bool on_coarse_fine_boundary = false;
             if (level > 0)
             {
                on_coarse_fine_boundary =
                  ( (k == vlo_z && mlo_z(i,j,k)) || (k == vhi_z+1 && mhi_z(i,j,k)) );
             }
             if (!on_coarse_fine_boundary)
             {
             // Add advective terms
             rho_w_rhs(i, j, k) += -AdvectionContributionForZMom(i, j, k, rho_u, rho_v, rho_w, w,
                                                                 dxInv, l_spatial_order);
             // Add diffusive terms
             if (solverChoice.molec_diff_type == MolecDiffType::ConstantDiffusivity)
             {
                 // DiffusionContributionForMom calls ComputeStressTerm, which returns mu_effective * strainRateDeviatoric
                 // For "ConstantK" (in DNS mode), mu_effective is twice the kinematic viscosity
                 // The factor of rho is provided by passing in rho*u instead of u
                 rho_w_rhs(i, j, k) += DiffusionContributionForMom(i, j, k, rho_u, rho_v, rho_w, MomentumEqn::z, dxInv, K_LES, solverChoice,
                                                                   false, false);
             }
             else
             {
                 rho_w_rhs(i, j, k) += DiffusionContributionForMom(i, j, k, u, v, w, MomentumEqn::z, dxInv, K_LES, solverChoice,
                                                                   false, false);
             }
             // Add pressure gradient
             rho_w_rhs(i, j, k) += (-dxInv[2]) *
                 (getPprimegivenRTh(cell_data(i, j, k    , RhoTheta_comp),dptr_pres_hse[k  ]) -
                  getPprimegivenRTh(cell_data(i, j, k - 1, RhoTheta_comp),dptr_pres_hse[k-1]));
             // Add gravity term
             if (solverChoice.use_gravity)
             {
                 int local_spatial_order = 2;
                 rho_w_rhs(i, j, k) += grav_gpu[2] *
                      InterpolateDensityPertFromCellToFace(i, j, k, cell_data, rho_w(i,j,k),
                                                           Coord::z, local_spatial_order, dptr_dens_hse);
             }
             // Add driving pressure gradient
             if (solverChoice.abl_driver_type == ABLDriverType::PressureGradient)
                 rho_w_rhs(i, j, k) += -solverChoice.abl_pressure_grad[2];
             // Add Coriolis forcing (that assumes east is +x, north is +y)
             if (solverChoice.use_coriolis)
             {
                 Real rho_u_loc = 0.25 * (rho_u(i+1,j,k) + rho_u(i,j,k) + rho_u(i+1,j,k-1) + rho_u(i,j,k-1));
                 rho_w_rhs(i, j, k) += solverChoice.coriolis_factor * rho_u_loc * solverChoice.cosphi;
             }
             // Add geostrophic forcing
             if (solverChoice.abl_driver_type == ABLDriverType::GeostrophicWind)
                 rho_w_rhs(i, j, k) += solverChoice.abl_geo_forcing[2];
             // Add Rayleigh damping
             if (solverChoice.use_rayleigh_damping)
             {
                 rho_w_rhs(i, j, k) -= dptr_rayleigh_tau[k] * rho_w(i,j,k);
             }
             } // not on coarse-fine boundary
         });
     }
 }
Referenced by erf_advance(), and erf_fast_rhs().
InterpolateDensityPertFromCellToFace()
AMREX_GPU_DEVICE Real InterpolateDensityPertFromCellToFace (const int & i, const int & j, const int & k, const Array4< const Real > & cons_in, const Real & uadv, const enum Coord & coordDir, const int & spatial_order, const amrex::Real * dptr_hse)
InterpolateFromCellOrFace()
AMREX_GPU_DEVICE Real InterpolateFromCellOrFace (const int & i, const int & j, const int & k, const Array4< const Real > & qty, const int & qty_index, const Real & uadv, const enum Coord & coordDir, const int & spatial_order)
InterpolatePertFromCell()
AMREX_GPU_DEVICE Real InterpolatePertFromCell (const int & i, const int & j, const int & k, const Array4< const Real > & qty, const int & qty_index, const Real & uadv, const enum Coord & coordDir, const int & spatial_order, const amrex::Real * dptr_hse)
InterpolateTurbulentViscosity()
AMREX_GPU_DEVICE Real InterpolateTurbulentViscosity (const int & i, const int & j, const int & k, const enum MomentumEqn & momentumEqn, const enum DiffusionDir & diffDir, const Array4< Real > & Ksmag) inline
Compute K_LES (i-1/2, j+1/2, k) etc given K_LES (i, j, k) is known.
Compute K (i-1/2, j+1/2, k) etc given K(i, j, k) or nut (i, j, k) is known
{
   // Assuming we already have 'K_LES' computed for all (i, j, k)
   Real turbViscInterpolated = 1.0;
   switch (momentumEqn) {
   case MomentumEqn::x: // Reference face is x-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       turbViscInterpolated = K_LES(i-1, j, k);
       break;
     case DiffusionDir::y:
       turbViscInterpolated = 0.25*( K_LES(i-1, j, k) + K_LES(i, j, k) + K_LES(i-1, j-1, k) + K_LES(i, j-1, k) );
       break;
     case DiffusionDir::z:
       turbViscInterpolated = 0.25*( K_LES(i-1, j, k) + K_LES(i, j, k) + K_LES(i-1, j, k-1) + K_LES(i, j, k-1) );
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::y: // Reference face is y-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       turbViscInterpolated = 0.25*( K_LES(i, j-1, k) + K_LES(i, j, k) + K_LES(i-1, j-1, k) + K_LES(i-1, j, k) );
       break;
     case DiffusionDir::y:
       turbViscInterpolated = K_LES(i, j-1, k);
       break;
     case DiffusionDir::z:
       turbViscInterpolated = 0.25*( K_LES(i, j-1, k) + K_LES(i, j, k) + K_LES(i, j-1, k-1) + K_LES(i, j, k-1) );
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   case MomentumEqn::z: // Reference face is z-face index (i, j, k)
     switch (diffDir) {
     case DiffusionDir::x:
       turbViscInterpolated = 0.25*( K_LES(i, j, k-1) + K_LES(i, j, k) + K_LES(i-1, j, k-1) + K_LES(i-1, j, k) );
       break;
     case DiffusionDir::y:
       turbViscInterpolated = 0.25*( K_LES(i, j, k-1) + K_LES(i, j, k) + K_LES(i, j-1, k-1) + K_LES(i, j-1, k) );
       break;
     case DiffusionDir::z:
       turbViscInterpolated = K_LES(i, j, k-1);
       break;
     default:
       amrex::Abort("Error: Diffusion direction is unrecognized");
     }
     break;
   default:
     amrex::Abort("Error: Momentum equation is unrecognized");
   }
   return turbViscInterpolated;
 }
Referenced by ComputeStressGivenRates().
MomentumToVelocity()
void MomentumToVelocity (MultiFab & xvel, MultiFab & yvel, MultiFab & zvel, const MultiFab & cons_in, const MultiFab & xmom_in, const MultiFab & ymom_in, const MultiFab & zmom_in, const int l_spatial_order, const int ngrow)
Convert updated momentum to updated velocity
 {
     BL_PROFILE_VAR("MomentumToVelocity()",MomentumToVelocity);
     // Loop over boxes = valid boxes grown by ngrow
     for ( MFIter mfi(cons_in,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& tbx = amrex::grow(mfi.nodaltilebox(0),IntVect(0,ngrow,ngrow));
         const Box& tby = amrex::grow(mfi.nodaltilebox(1),IntVect(ngrow,0,ngrow));
         const Box& tbz = amrex::grow(mfi.nodaltilebox(2),IntVect(ngrow,ngrow,0));
         // Conserved variables on cell centers -- we use this for density
         const Array4<const Real>& cons = cons_in.array(mfi);
         // Momentum on faces
         Array4<Real const> const& momx = xmom_in.array(mfi);
         Array4<Real const> const& momy = ymom_in.array(mfi);
         Array4<Real const> const& momz = zmom_in.array(mfi);
         // Velocity on faces
         const Array4<Real>& velx = xvel.array(mfi);
         const Array4<Real>& vely = yvel.array(mfi);
         const Array4<Real>& velz = zvel.array(mfi);
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             velx(i,j,k) = momx(i,j,k)/InterpolateFromCellOrFace(
                                         i, j, k, cons, Rho_comp, momx(i,j,k), Coord::x, l_spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             vely(i,j,k) = momy(i,j,k)/InterpolateFromCellOrFace(
                                         i, j, k, cons, Rho_comp, momy(i,j,k), Coord::y, l_spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             velz(i,j,k) = momz(i,j,k)/InterpolateFromCellOrFace(
                                         i, j, k, cons, Rho_comp, momz(i,j,k), Coord::z, l_spatial_order);
         });
     } // end MFIter
 }
Referenced by erf_advance(), and MomentumToVelocity().
VelocityToMomentum()
void VelocityToMomentum (const MultiFab & xvel_in, const MultiFab & yvel_in, const MultiFab & zvel_in, const MultiFab & cons_in, MultiFab & xmom, MultiFab & ymom, MultiFab & zmom, const int l_spatial_order, const int ngrow)
Convert velocity to momentum.
 {
     BL_PROFILE_VAR("VelocityToMomentum()",VelocityToMomentum);
     // Loop over boxes = valid boxes grown by ngrow
     for ( MFIter mfi(cons_in,TilingIfNotGPU()); mfi.isValid(); ++mfi)
     {
         const Box& tbx = amrex::grow(mfi.nodaltilebox(0),IntVect(0,ngrow,ngrow));
         const Box& tby = amrex::grow(mfi.nodaltilebox(1),IntVect(ngrow,0,ngrow));
         const Box& tbz = amrex::grow(mfi.nodaltilebox(2),IntVect(ngrow,ngrow,0));
         // Conserved/state variables on cell centers -- we use this for density
         const Array4<const Real>& cons = cons_in.array(mfi);
         // Momentum on faces, to be computed
         Array4<Real> const& momx = xmom.array(mfi);
         Array4<Real> const& momy = ymom.array(mfi);
         Array4<Real> const& momz = zmom.array(mfi);
         // Velocity on faces, used in computation
         const Array4<Real const>& velx = xvel_in.array(mfi);
         const Array4<Real const>& vely = yvel_in.array(mfi);
         const Array4<Real const>& velz = zvel_in.array(mfi);
         amrex::ParallelFor(tbx, tby, tbz,
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momx(i,j,k) = velx(i,j,k)* InterpolateFromCellOrFace(
                                 i, j, k, cons, Rho_comp, velx(i,j,k), Coord::x, l_spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momy(i,j,k) = vely(i,j,k)* InterpolateFromCellOrFace(
                                 i, j, k, cons, Rho_comp, vely(i,j,k), Coord::y, l_spatial_order);
         },
         [=] AMREX_GPU_DEVICE (int i, int j, int k) {
             momz(i,j,k) = velz(i,j,k)* InterpolateFromCellOrFace(
                                 i, j, k, cons, Rho_comp, velz(i,j,k), Coord::z, l_spatial_order);
         });
     } // end MFIter
 }
Referenced by erf_advance().