var searchData=
[
  ['c_5fp_41',['c_p',['../_constants_8_h.html#a7f928aa35dcd2f4e48fdf6d6a3166f1a',1,'Constants.H']]],
  ['checkpoint_42',['checkPoint',['../class_i_o_manager.html#a7d90373f66fdbcacbf31bbe42fc2b4a8',1,'IOManager']]],
  ['close_43',['close',['../classncutils_1_1_n_c_file.html#af2c4a20c38edb3fae69087a80875b8b9',1,'ncutils::NCFile']]],
  ['computeadvectedquantityformom_44',['ComputeAdvectedQuantityForMom',['../_advection_8cpp.html#aa1cf510c66651ac7cc4b41796fd1aa32',1,'ComputeAdvectedQuantityForMom(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;rho_u, const Array4&lt; Real &gt; &amp;rho_v, const Array4&lt; Real &gt; &amp;rho_w, const Array4&lt; Real &gt; &amp;u, const Array4&lt; Real &gt; &amp;v, const Array4&lt; Real &gt; &amp;w, const enum NextOrPrev &amp;nextOrPrev, const enum AdvectedQuantity &amp;advectedQuantity, const enum AdvectingQuantity &amp;advectingQuantity, const int &amp;spatial_order):&#160;Advection.cpp'],['../_r_k3_8_h.html#aa1cf510c66651ac7cc4b41796fd1aa32',1,'ComputeAdvectedQuantityForMom(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;rho_u, const Array4&lt; Real &gt; &amp;rho_v, const Array4&lt; Real &gt; &amp;rho_w, const Array4&lt; Real &gt; &amp;u, const Array4&lt; Real &gt; &amp;v, const Array4&lt; Real &gt; &amp;w, const enum NextOrPrev &amp;nextOrPrev, const enum AdvectedQuantity &amp;advectedQuantity, const enum AdvectingQuantity &amp;advectingQuantity, const int &amp;spatial_order):&#160;Advection.cpp']]],
  ['computeadvectedquantityforstate_45',['ComputeAdvectedQuantityForState',['../_advection_8cpp.html#a7555f3ea9581b73befdd315ebd2ed01a',1,'ComputeAdvectedQuantityForState(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;rho_u, const Array4&lt; Real &gt; &amp;rho_v, const Array4&lt; Real &gt; &amp;rho_w, const Array4&lt; Real &gt; &amp;cell_data, const enum NextOrPrev &amp;nextOrPrev, const enum AdvectedQuantity &amp;advectedQuantity, const enum AdvectingQuantity &amp;advectingQuantity, const int &amp;spatial_order):&#160;Advection.cpp'],['../_r_k3_8_h.html#a7555f3ea9581b73befdd315ebd2ed01a',1,'ComputeAdvectedQuantityForState(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;rho_u, const Array4&lt; Real &gt; &amp;rho_v, const Array4&lt; Real &gt; &amp;rho_w, const Array4&lt; Real &gt; &amp;cell_data, const enum NextOrPrev &amp;nextOrPrev, const enum AdvectedQuantity &amp;advectedQuantity, const enum AdvectingQuantity &amp;advectingQuantity, const int &amp;spatial_order):&#160;Advection.cpp']]],
  ['computediffusiontermforstate_46',['ComputeDiffusionTermForState',['../_diffusion_8cpp.html#a8f95216619a2e0534067ca31b3bb122a',1,'ComputeDiffusionTermForState(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;cell_data, const int &amp;qty_index, const enum Coord &amp;coordDir):&#160;Diffusion.cpp'],['../_r_k3_8_h.html#a8f95216619a2e0534067ca31b3bb122a',1,'ComputeDiffusionTermForState(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;cell_data, const int &amp;qty_index, const enum Coord &amp;coordDir):&#160;Diffusion.cpp']]],
  ['computeghostcells_47',['ComputeGhostCells',['../_r_k3_8_h.html#ae0317d92e01689ac723ac07807389e3e',1,'ComputeGhostCells(const int &amp;spatial_order):&#160;RK3_utils.cpp'],['../_r_k3__utils_8cpp.html#ae0317d92e01689ac723ac07807389e3e',1,'ComputeGhostCells(const int &amp;spatial_order):&#160;RK3_utils.cpp']]],
  ['computestrainrate_48',['ComputeStrainRate',['../_r_k3_8_h.html#aa27eafcf74a31a4f240a7fbf2bfc9e9c',1,'ComputeStrainRate(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;u, const Array4&lt; Real &gt; &amp;v, const Array4&lt; Real &gt; &amp;w, const enum NextOrPrev &amp;nextOrPrev, const enum MomentumEqn &amp;momentumEqn, const enum DiffusionDir &amp;diffDir, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;cellSize):&#160;StrainRate.cpp'],['../_strain_rate_8cpp.html#aa27eafcf74a31a4f240a7fbf2bfc9e9c',1,'ComputeStrainRate(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;u, const Array4&lt; Real &gt; &amp;v, const Array4&lt; Real &gt; &amp;w, const enum NextOrPrev &amp;nextOrPrev, const enum MomentumEqn &amp;momentumEqn, const enum DiffusionDir &amp;diffDir, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;cellSize):&#160;StrainRate.cpp']]],
  ['computestressterm_49',['ComputeStressTerm',['../_diffusion_8cpp.html#abc43ad73f9226b0ff44b044bf73bf969',1,'ComputeStressTerm(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;u, const Array4&lt; Real &gt; &amp;v, const Array4&lt; Real &gt; &amp;w, const enum NextOrPrev &amp;nextOrPrev, const enum MomentumEqn &amp;momentumEqn, const enum DiffusionDir &amp;diffDir, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;cellSize, const Array4&lt; Real &gt; &amp;nut, const SolverChoice &amp;solverChoice):&#160;Diffusion.cpp'],['../_r_k3_8_h.html#abc43ad73f9226b0ff44b044bf73bf969',1,'ComputeStressTerm(const int &amp;i, const int &amp;j, const int &amp;k, const Array4&lt; Real &gt; &amp;u, const Array4&lt; Real &gt; &amp;v, const Array4&lt; Real &gt; &amp;w, const enum NextOrPrev &amp;nextOrPrev, const enum MomentumEqn &amp;momentumEqn, const enum DiffusionDir &amp;diffDir, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;cellSize, const Array4&lt; Real &gt; &amp;nut, const SolverChoice &amp;solverChoice):&#160;Diffusion.cpp']]],
  ['computeturbulentviscosity_50',['ComputeTurbulentViscosity',['../_eddy_viscosity_8cpp.html#a40d501968d03df4ca8fe3c9b053c9266',1,'ComputeTurbulentViscosity(MultiFab &amp;xvel, MultiFab &amp;yvel, MultiFab &amp;zvel, MultiFab &amp;cons_in, MultiFab &amp;eddyViscosity, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;cellSize, const SolverChoice &amp;solverChoice):&#160;EddyViscosity.cpp'],['../_r_k3_8_h.html#a40d501968d03df4ca8fe3c9b053c9266',1,'ComputeTurbulentViscosity(MultiFab &amp;xvel, MultiFab &amp;yvel, MultiFab &amp;zvel, MultiFab &amp;cons_in, MultiFab &amp;eddyViscosity, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;cellSize, const SolverChoice &amp;solverChoice):&#160;EddyViscosity.cpp']]],
  ['const_5fgrav_51',['CONST_GRAV',['../_constants_8_h.html#a063fd3095e4994e6136a62d78b7c5901',1,'Constants.H']]],
  ['constants_2eh_52',['Constants.H',['../_constants_8_h.html',1,'']]],
  ['coord_53',['Coord',['../_data_struct_8_h.html#a627f1f843904477f763577ad1460de01',1,'DataStruct.H']]],
  ['coriolis_5ffactor_54',['coriolis_factor',['../struct_solver_choice.html#aa60641bb49bf6dc870fc07613dc7c0b2',1,'SolverChoice']]],
  ['cosphi_55',['cosphi',['../struct_solver_choice.html#ac10a89429ffd40d3edd2d5a97c61c68c',1,'SolverChoice']]],
  ['create_56',['create',['../classncutils_1_1_n_c_file.html#a47bdccee2cc22a735ca715d9c88e4f6b',1,'ncutils::NCFile']]],
  ['create_5fpar_57',['create_par',['../classncutils_1_1_n_c_file.html#a6607bd5f3f75b451e2436ff713931f19',1,'ncutils::NCFile']]],
  ['create_5fumac_5fgrown_58',['create_umac_grown',['../group___utilities.html#ga51811d0b14000eb915dca15418dd2409',1,'create_umac_grown(int lev, int nGrow, BoxArray &amp;fine_grids, const Geometry &amp;crse_geom, const Geometry &amp;fine_geom, const Array&lt; MultiFab *, AMREX_SPACEDIM &gt; u_mac_crse, const Array&lt; MultiFab *, AMREX_SPACEDIM &gt; u_mac_fine, const IntVect &amp;crse_ratio):&#160;Utils.cpp'],['../group___utilities.html#ga0b68072582792e86f3a05e7f5aa12b23',1,'create_umac_grown(int lev, int nGrow, amrex::BoxArray &amp;fine_grids, const amrex::Geometry &amp;crse_geom, const amrex::Geometry &amp;fine_geom, const amrex::Array&lt; amrex::MultiFab *, AMREX_SPACEDIM &gt; u_mac_crse, const amrex::Array&lt; amrex::MultiFab *, AMREX_SPACEDIM &gt; u_mac_fine, const amrex::IntVect &amp;crse_ratio):&#160;utils.H']]],
  ['cs_59',['Cs',['../struct_solver_choice.html#adf71cefcbf89e69db9229515be3cd36f',1,'SolverChoice']]]
];
