var searchData=
[
  ['datalog_1057',['DataLog',['../classERF.html#aa2c3ee1910008b828b9da79ccdfe3871',1,'ERF']]],
  ['datalogname_1058',['DataLogName',['../classERF.html#afbf411b8cb24554d9aad7c76b0210e92',1,'ERF']]],
  ['def_5farray_1059',['def_array',['../classncutils_1_1NCGroup.html#acdfa4a8e44ca0f1901ea120a3946d1db',1,'ncutils::NCGroup']]],
  ['def_5fdim_1060',['def_dim',['../classncutils_1_1NCGroup.html#ae0ecaad10c77614a283bd6e66d2dca41',1,'ncutils::NCGroup']]],
  ['def_5fgroup_1061',['def_group',['../classncutils_1_1NCGroup.html#ac5c99d691660e36a00afffae6f0d6f71',1,'ncutils::NCGroup']]],
  ['def_5fscalar_1062',['def_scalar',['../classncutils_1_1NCGroup.html#a43450deb9f15f2b0b805612d76145bbc',1,'ncutils::NCGroup']]],
  ['def_5fvar_1063',['def_var',['../classncutils_1_1NCGroup.html#aa049e7d6f5f7f88ad840fa2ced3c61b4',1,'ncutils::NCGroup']]],
  ['define_5flevel_5fdata_1064',['define_level_data',['../classReadBndryPlanes.html#a16ed881bb428b7abb89e4284b356c8d6',1,'ReadBndryPlanes']]],
  ['diffusionsrcformom_5fn_1065',['DiffusionSrcForMom_N',['../Diffusion_8H.html#a1c684527eefa79162174bdf44baaa7ff',1,'DiffusionSrcForMom_N(const amrex::Box &amp;bxx, const amrex::Box &amp;bxy, const amrex::Box &amp;bxz, const amrex::Box &amp;domain, const amrex::Array4&lt; amrex::Real &gt; &amp;rho_u_rhs, const amrex::Array4&lt; amrex::Real &gt; &amp;rho_v_rhs, const amrex::Array4&lt; amrex::Real &gt; &amp;rho_w_rhs, const amrex::Array4&lt; const amrex::Real &gt; &amp;u, const amrex::Array4&lt; const amrex::Real &gt; &amp;v, const amrex::Array4&lt; const amrex::Real &gt; &amp;w, const amrex::Array4&lt; const amrex::Real &gt; &amp;K_turb, const amrex::Array4&lt; const amrex::Real &gt; &amp;cell_data, const amrex::Array4&lt; const amrex::Real &gt; &amp;er_arr, const SolverChoice &amp;solverChoice, const amrex::BCRec *bc_ptr, const amrex::GpuArray&lt; amrex::Real, AMREX_SPACEDIM &gt; &amp;cellSizeInv):&#160;Diffusion.H'],['../DiffusionSrcForMom__N_8cpp.html#a699736f7c92b8c79a9c5d165c7d9838e',1,'DiffusionSrcForMom_N(const Box &amp;bxx, const Box &amp;bxy, const Box &amp;bxz, const Box &amp;domain, const Array4&lt; Real &gt; &amp;rho_u_rhs, const Array4&lt; Real &gt; &amp;rho_v_rhs, const Array4&lt; Real &gt; &amp;rho_w_rhs, const Array4&lt; const Real &gt; &amp;u, const Array4&lt; const Real &gt; &amp;v, const Array4&lt; const Real &gt; &amp;w, const Array4&lt; const Real &gt; &amp;K_turb, const Array4&lt; const Real &gt; &amp;cell_data, const Array4&lt; const Real &gt; &amp;er_arr, const SolverChoice &amp;solverChoice, const BCRec *bc_ptr, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;dxInv):&#160;DiffusionSrcForMom_N.cpp']]],
  ['diffusionsrcformom_5ft_1066',['DiffusionSrcForMom_T',['../Diffusion_8H.html#a82292956214c3f30c7a79961c133d0be',1,'DiffusionSrcForMom_T(const amrex::Box &amp;bxx, const amrex::Box &amp;bxy, const amrex::Box &amp;bxz, const amrex::Box &amp;domain, const amrex::Array4&lt; amrex::Real &gt; &amp;rho_u_rhs, const amrex::Array4&lt; amrex::Real &gt; &amp;rho_v_rhs, const amrex::Array4&lt; amrex::Real &gt; &amp;rho_w_rhs, const amrex::Array4&lt; const amrex::Real &gt; &amp;u, const amrex::Array4&lt; const amrex::Real &gt; &amp;v, const amrex::Array4&lt; const amrex::Real &gt; &amp;w, const amrex::Array4&lt; const amrex::Real &gt; &amp;K_turb, const amrex::Array4&lt; const amrex::Real &gt; &amp;cell_data, const amrex::Array4&lt; const amrex::Real &gt; &amp;er_arr, const SolverChoice &amp;solverChoice, const amrex::BCRec *bc_ptr, const amrex::Array4&lt; const amrex::Real &gt; &amp;z_nd, const amrex::Array4&lt; const amrex::Real &gt; &amp;detJ, const amrex::GpuArray&lt; amrex::Real, AMREX_SPACEDIM &gt; &amp;cellSizeInv):&#160;Diffusion.H'],['../DiffusionSrcForMom__T_8cpp.html#a2bb50b08988ba505701105997a226955',1,'DiffusionSrcForMom_T(const Box &amp;bxx, const Box &amp;bxy, const Box &amp;bxz, const Box &amp;domain, const Array4&lt; Real &gt; &amp;rho_u_rhs, const Array4&lt; Real &gt; &amp;rho_v_rhs, const Array4&lt; Real &gt; &amp;rho_w_rhs, const Array4&lt; const Real &gt; &amp;u, const Array4&lt; const Real &gt; &amp;v, const Array4&lt; const Real &gt; &amp;w, const Array4&lt; const Real &gt; &amp;K_turb, const Array4&lt; const Real &gt; &amp;cell_data, const Array4&lt; const Real &gt; &amp;er_arr, const SolverChoice &amp;solverChoice, const BCRec *bc_ptr, const Array4&lt; const Real &gt; &amp;z_nd, const Array4&lt; const Real &gt; &amp;detJ, const GpuArray&lt; Real, AMREX_SPACEDIM &gt; &amp;dxInv):&#160;DiffusionSrcForMom_T.cpp']]],
  ['diffusionsrcforstate_1067',['DiffusionSrcForState',['../Diffusion_8H.html#a7c4f788bf47f268fbc3b69b6e2a65123',1,'DiffusionSrcForState(const amrex::Box &amp;bx, const amrex::Box &amp;domain, int n_start, int n_end, const amrex::Array4&lt; const amrex::Real &gt; &amp;u, const amrex::Array4&lt; const amrex::Real &gt; &amp;v, const amrex::Array4&lt; const amrex::Real &gt; &amp;w, const amrex::Array4&lt; const amrex::Real &gt; &amp;cell_data, const amrex::Array4&lt; const amrex::Real &gt; &amp;cell_prim, const amrex::Array4&lt; const amrex::Real &gt; &amp;source_fab, const amrex::Array4&lt; amrex::Real &gt; &amp;cell_rhs, const amrex::Array4&lt; amrex::Real &gt; &amp;xflux, const amrex::Array4&lt; amrex::Real &gt; &amp;yflux, const amrex::Array4&lt; amrex::Real &gt; &amp;zflux, const amrex::GpuArray&lt; amrex::Real, AMREX_SPACEDIM &gt; &amp;cellSizeInv, const amrex::Array4&lt; const amrex::Real &gt; &amp;K_turb, const SolverChoice &amp;solverChoice, const amrex::Real &amp;theta_mean, const amrex::GpuArray&lt; amrex::Real, AMREX_SPACEDIM &gt; grav_gpu, const amrex::BCRec *bc_ptr):&#160;DiffusionSrcForState.cpp'],['../DiffusionSrcForState_8cpp.html#a7c4f788bf47f268fbc3b69b6e2a65123',1,'DiffusionSrcForState(const amrex::Box &amp;bx, const amrex::Box &amp;domain, int n_start, int n_end, const amrex::Array4&lt; const amrex::Real &gt; &amp;u, const amrex::Array4&lt; const amrex::Real &gt; &amp;v, const amrex::Array4&lt; const amrex::Real &gt; &amp;w, const amrex::Array4&lt; const amrex::Real &gt; &amp;cell_data, const amrex::Array4&lt; const amrex::Real &gt; &amp;cell_prim, const amrex::Array4&lt; const amrex::Real &gt; &amp;source_fab, const amrex::Array4&lt; amrex::Real &gt; &amp;cell_rhs, const amrex::Array4&lt; amrex::Real &gt; &amp;xflux, const amrex::Array4&lt; amrex::Real &gt; &amp;yflux, const amrex::Array4&lt; amrex::Real &gt; &amp;zflux, const amrex::GpuArray&lt; amrex::Real, AMREX_SPACEDIM &gt; &amp;cellSizeInv, const amrex::Array4&lt; const amrex::Real &gt; &amp;K_turb, const SolverChoice &amp;solverChoice, const amrex::Real &amp;theta_mean, const amrex::GpuArray&lt; amrex::Real, AMREX_SPACEDIM &gt; grav_gpu, const amrex::BCRec *bc_ptr):&#160;DiffusionSrcForState.cpp']]],
  ['diffusionsrcforxmom_1068',['DiffusionSrcForXMom',['../DiffusionSrcForMom__N_8H.html#a5b6b778012fe3b5d408ae1978eb125c8',1,'DiffusionSrcForMom_N.H']]],
  ['diffusionsrcforxmomwithterrain_1069',['DiffusionSrcForXMomWithTerrain',['../DiffusionSrcForMom__T_8H.html#a62c93acddb26bee8aa7b101511725872',1,'DiffusionSrcForMom_T.H']]],
  ['diffusionsrcforymom_1070',['DiffusionSrcForYMom',['../DiffusionSrcForMom__N_8H.html#a199b251f48ea03275bc4ead584bc926e',1,'DiffusionSrcForMom_N.H']]],
  ['diffusionsrcforymomwithterrain_1071',['DiffusionSrcForYMomWithTerrain',['../DiffusionSrcForMom__T_8H.html#a4245f263cd83a94a5f5a8254bc1f5b7d',1,'DiffusionSrcForMom_T.H']]],
  ['diffusionsrcforzmom_1072',['DiffusionSrcForZMom',['../DiffusionSrcForMom__N_8H.html#a4624574cd84898e5b799050d68961b39',1,'DiffusionSrcForMom_N.H']]],
  ['diffusionsrcforzmomwithterrain_1073',['DiffusionSrcForZMomWithTerrain',['../DiffusionSrcForMom__T_8H.html#a3ccbbdb261f04badd40a3be6cf063b13',1,'DiffusionSrcForMom_T.H']]],
  ['dim_1074',['dim',['../classncutils_1_1NCGroup.html#addc8bbac9a2cfa8d9c49497b7da0310f',1,'ncutils::NCGroup']]],
  ['display_1075',['display',['../structSolverChoice.html#abb95d84167308078ce369b4196ef979c',1,'SolverChoice']]],
  ['dx_1076',['dx',['../classPlaneAverage.html#abf7bfae5c1b6fed56ff09fd06368b12c',1,'PlaneAverage']]]
];
